hmcts/sds-flux-config

.github/renovate.json
[tools.hmcts.net/jira/browse/DTSPO-7557](https://tools.hmcts.net/jira/browse/DTSPO-7557)
Test enable renovate
```
[ ] Yes
[x] No
```
=> DTSPO-7557 Add renovate config

apps/vh/bookings-api/bookings-api.yaml, apps/vh/bookings-api/image-policy.yaml, k8s/namespaces/vh/vh-bookings-api/patches/prod.yaml, k8s/namespaces/vh/vh-bookings-api/vh-bookings-api.yaml
VIH-8951
Correct the config to pull correct helm charts and images
```
[ ] Yes
[ ] No
```
=> VIH-8951 - update flux config

apps/toffee/demo/base/azure-identity-patch.yaml, apps/toffee/demo/base/kustomization.yaml, apps/toffee/frontend/demo.yaml, apps/toffee/identity/demo.yaml, apps/toffee/recipe-backend/demo.yaml, clusters/demo/00/kustomization.yaml, clusters/demo/01/kustomization.yaml, clusters/demo/base/kustomization.yaml, k8s/environments/demo/common-overlay/kustomization.yaml
DTSPO-6491
Migrate toffee demo to flux v2
```
[ ] Yes
[X] No
```
=> DTSPO-6491 - Migrate toffee demo to flux v2

apps/pip/account-management/demo.yaml, apps/pip/channel-management/demo.yaml, apps/pip/data-management/demo.yaml, apps/pip/demo/base/azure-identity-patch.yaml, apps/pip/demo/base/kustomization.yaml, apps/pip/frontend/demo.yaml, apps/pip/identity/demo.yaml, apps/pip/publication-services/demo.yaml, apps/pip/subscription-management/demo.yaml, clusters/demo/base/kustomization.yaml, k8s/environments/demo/common-overlay/kustomization.yaml
DTSPO-6491
Migrate pip app to Flux V2
```
[ ] Yes
[X] No
```
=> DTSPO-6491 - Migrate pip app to Flux V2

apps/pip/data-management/demo.yaml
DTSPO-6491
Update image for data-management
```
[ ] Yes
[X] No
```
=> DTSPO-6491 - Update image for data-management

apps/juror-digital/jd-bureau/jd-bureau.yaml, apps/juror-digital/jd-public/jd-public.yaml
=> Releasing 2.26 to NLE

apps/vh/bookings-api/demo.yaml, apps/vh/demo/base/azure-identity-patch.yaml, apps/vh/demo/base/kustomization.yaml, apps/vh/identity/demo.yaml, clusters/demo/base/kustomization.yaml, k8s/environments/demo/common-overlay/kustomization.yaml
DTSPO-6491
Migrate VH to Flux V2
```
[ ] Yes
[X] No
```
=> DTSPO-6491 - Migrate VH to Flux V2

apps/admin/external-dns/external-dns-private.yaml, apps/admin/external-dns/external-dns.yaml
DTSPO-6491
Add annotations to app helm charts
```
[ ] Yes
[X] No
```
=> DTSPO-6491 - Add annotations to app helm charts

apps/admin/external-dns/external-dns.yaml
DTSPO-6491
Update external-dns.yaml
```
[ ] Yes
[X] No
```
=> DTSPO-6491 - Update external-dns.yaml

apps/admin/external-dns/external-dns.yaml
DTSPO-6491
Change external dns version
```
[ ] Yes
[X] No
```
=> DTSPO-6491 - Change external dns version

apps/admin/oauth2-proxy/oauth2-proxy.yaml
DTSPO-6491
Remove podLabels section from helm chart
```
[ ] Yes
[X] No
```
=> DTSPO-6491 - Remove podLabels section from helm chart

apps/admin/demo/00/kustomization.yaml, apps/admin/demo/01/kustomization.yaml
DTSPO-6491
Add Files to Kustomise
```
[ ] Yes
[X] No
```
=> DTSPO-6491 - Add Files to Kustomise

apps/admin/oauth2-proxy/oauth2-proxy.yaml
Reverts hmcts/sds-flux-config#1829
=> Revert "DTSPO-6491 - Remove podLabels section from helm chart"

apps/admin/oauth2-proxy/secret-provider.yaml
DTSPO-6491
Update secret-provider.yaml
```
[ ] Yes
[X] No
```
=> DTSPO-6491 - Update secret-provider.yaml

apps/admin/demo/00/kustomization.yaml
DTSPO-6491
Remove Oauth-proxy from flux config on 00 demo cluster
```
[ ] Yes
[X] No
```
=> DTSPO-6491 - Remove Oauth-proxy from flux config on 00 demo cluster

apps/admin/base/kustomization.yaml, apps/admin/demo/01/kustomization.yaml
DTSPO-6491 
Remove Oauth-proxy from kustomization.yaml
```
[ ] Yes
[X] No
```
=> DTSPO-6491 - Remove Oauth-proxy from kustomization.yaml

apps/admin/traefik2/demo/00-traefik2.yaml
DTSPO-6491
Change IP address for demo private load balancer
```
[ ] Yes
[X] No
```
=> DTSPO-6491 - Change IP address for demo private load balancer

apps/admin/demo/00/kustomization.yaml
Trying to resolve an issue in demo with ingress
```
[ ] Yes
[x] No
```
=> DTSPO-6491 - testing removing public traefiks for now

apps/admin/demo/01/kustomization.yaml, apps/admin/traefik2/kustomization.yaml
removing public traefiks for now to focus on the private one
```
[ ] Yes
[x] No
```
=> DTSPO-6491 - remove public traefiks from demo for now

apps/admin/base/kustomization.yaml, apps/admin/demo/00/kustomization.yaml, apps/admin/demo/01/kustomization.yaml
Removing for now, we will need to move it into the demo configuration
```
[ ] Yes
[x] No
```
=> DTSPO-6491 - removing oauth proxy from admin base config

apps/admin/traefik-auth-proxy/demo/00-traefik-auth-proxy.yaml
update lb up for auth proxy in demo
```
[ ] Yes
[x] No
```
=> DTSPO-6491 - update lb up for auth proxy in demo

apps/admin/traefik-auth-proxy/traefik-auth-proxy.yaml, apps/admin/traefik-no-proxy/traefik-no-proxy.yaml
fix traefik release names
```
[ ] Yes
[x] No
```
=> DTSPO-6491 fix traefik release names

apps/admin/oauth2-proxy/secret-provider.yaml
Attempt fix oauth values 
```
[ ] Yes
[x] No
```
=> DTSPO-6491 - fix oauth values

apps/admin/oauth2-proxy/secret-provider.yaml
I think this will fix the oauth 2 secrets 🙏🏼 
```
[ ] Yes
[x] No
```
=> DTSPO-6491 - fix oauth secrets

apps/admin/traefik-no-proxy/demo/00-traefik-no-proxy.yaml
=> Fix no proxy ip address

apps/admin/traefik-auth-proxy/oauth-headers.yaml
Add admin namespace to middleware resource
```
[ ] Yes
[x] No
```
=> DTSPO-6491 - add namespace to resource

apps/admin/traefik-auth-proxy/oauth-headers.yaml, apps/admin/traefik-auth-proxy/oauth-routes.yaml, apps/admin/traefik-auth-proxy/traefik-auth-proxy.yaml
Fix naming on oauth headers
```
[ ] Yes
[x] No
```
=> Dtspo 6491 oauth header

apps/vh/dev/base/azure-identity-patch.yaml, apps/vh/identity/dev.yaml
N/A
update the client id for MI vh-infra-core-dev-kvuser
```
[ ] Yes
[X ] No
```
=> VH - Update Dev Flux Patch with New Client ID

k8s/namespaces/jenkins/patches/ptl/cluster-00/jenkins.yaml
https://tools.hmcts.net/jira/browse/DTSPO-8384
Added Libra GoB Jenkins Build Dashboard
```
[ ] Yes
[X] No
```
=> Added Libra GoB Jenkins Build Dashboard

README.md
DTSPO-6491
Update README.md to show Flux V2 migration completed for demo
```
[ ] Yes
[X] No
```
=> DTSPO-6491 - Update README.md to show Flux V2 migration completed for demo

k8s/namespaces/vh/vh-bookings-api/patches/stg.yaml
N/A
VH - Add Staging Patch for Resource ID
```
[ ] Yes
[ X ] No
```
=> VH - Add Staging Patch for Resource ID

k8s/namespaces/vh/vh-bookings-api/vh-bookings-api.yaml
VH Bookings API - update disableTraefikTls
```
[ ] Yes
[ X ] No
```
=> VH Bookings API - update disableTraefikTls

k8s/namespaces/pip/pip-account-management/patches/stg/pip-account-management.yaml, k8s/namespaces/pip/pip-account-management/patches/test/pip-account-management.yaml, k8s/namespaces/pip/pip-data-management/patches/dev/pip-data-management.yaml, k8s/namespaces/pip/pip-data-management/patches/prod/pip-data-management.yaml, k8s/namespaces/pip/pip-data-management/patches/test/pip-data-management.yaml, k8s/namespaces/pip/pip-subscription-management/patches/dev/pip-subscription-management.yaml, k8s/namespaces/pip/pip-subscription-management/patches/prod/pip-subscription-management.yaml, k8s/namespaces/pip/pip-subscription-management/patches/stg/pip-subscription-management.yaml, k8s/namespaces/pip/pip-subscription-management/patches/test/pip-subscription-management.yaml
N/A
Updated missing environment variables for the different environments in PIP
```
[ ] Yes
[x] No
```
=> Updated environment variables

apps/admin/aad-pod-identity/stg/azure-identity-patch.yaml, apps/admin/kube-slack/stg/00.yaml, apps/admin/kube-slack/stg/01.yaml, apps/admin/kube-slack/stg/kube-slack-values.enc.yaml, apps/admin/kured/stg/00.yaml, apps/admin/kured/stg/01.yaml, apps/admin/kured/stg/kured-values.enc.yaml, apps/admin/secrets-csi-driver/stg/01.yaml, apps/admin/stg/00/kustomization.yaml, apps/admin/stg/01/kustomization.yaml, apps/admin/stg/base/kustomization.yaml, apps/admin/traefik2/stg/00-traefik2.yaml, apps/admin/traefik2/stg/01-traefik2.yaml, apps/admin/traefik2/stg/kustomization.yaml, apps/admin/traefik2/stg/secret-provider.yaml
add admin ns
```
[ ] Yes
[x] No
```
=> DTSPO-6488 Upgrade Admin ns to Flux v2 - Staging

k8s/environments/test/common-overlay/pip/kustomization.yaml
N/A
Updated patch files for test
```
[ ] Yes
[x] No
```
=> Fixed patch file for test

apps/admin/base/kustomization.yaml, apps/admin/demo/00/kustomization.yaml, apps/admin/demo/01/kustomization.yaml
It installed itself on staging but it's only intended for demo atm
=> Move external DNS to demo only

k8s/environments/prod/common-overlay/.flux.yaml
Add Flux Patch to Prod
```
[ ] Yes
[ x ] No
```
=> VH - Add Flux Patch to Prod

apps/admin/aad-pod-identity/prod/azure-identity-patch.yaml, apps/admin/demo/01/kustomization.yaml, apps/admin/dev/01/kustomization.yaml, apps/admin/ithc/01/kustomization.yaml, apps/admin/kube-slack/prod/kube-slack-values.enc.yaml, apps/admin/sbox/01/kustomization.yaml, apps/admin/secrets-csi-driver/demo/01.yaml, apps/admin/secrets-csi-driver/dev/01.yaml, apps/admin/secrets-csi-driver/ithc/01.yaml, apps/admin/secrets-csi-driver/sbox/01.yaml, apps/admin/secrets-csi-driver/stg/01.yaml, apps/admin/stg/01/kustomization.yaml
and a couple of flux v2 prod things...
=> DTSPO-8052 Remove unused patch for csi driver

k8s/environments/prod/common-overlay/juror-digital/jd-bureau-patch.yaml, k8s/environments/prod/common-overlay/juror-digital/jd-public-patch.yaml
=> Updated to 2.26 release

apps/toffee/frontend/stg.yaml, apps/toffee/identity/stg.yaml, apps/toffee/recipe-backend/stg.yaml, apps/toffee/stg/base/azure-identity-patch.yaml, apps/toffee/stg/base/kustomization.yaml, clusters/stg/base/kustomization.yaml
https://tools.hmcts.net/jira/browse/DTSPO-6490
```
[ ] Yes
[x] No
```
=> DTSPO-6488 Upgrade toffee ns to Flux v2 - Staging

apps/admin/kube-slack/test/kube-slack-values.enc.yaml, apps/admin/kured/test/kured-values.enc.yaml, apps/admin/test/00/kustomization.yaml, apps/admin/test/01/kustomization.yaml, apps/admin/test/base/kustomization.yaml, apps/admin/traefik2/test/00-traefik2.yaml, apps/admin/traefik2/test/01-traefik2.yaml, apps/admin/traefik2/test/kustomization.yaml, apps/admin/traefik2/test/secret-provider.yaml, k8s/environments/test/cluster-00-overlay/kustomization.yaml, k8s/environments/test/cluster-01-overlay/kustomization.yaml
Migrate admin namespace in test to fluxv2
```
[ ] Yes
[x] No
```
=> DTSPO-6488 - Flux v2 migration - test - admin

apps/neuvector/neuvector/stg/00.yaml, apps/neuvector/neuvector/stg/01.yaml, apps/neuvector/stg/00/kustomization.yaml, apps/neuvector/stg/01/kustomization.yaml
=> Neuvector fixing - staging

apps/admin/traefik2/test/secret-provider.yaml
tools.hmcts.net/jira/browse/DTSPO-6488
Fix traefik wildcard cert environment
[ ] Yes
[x] No
=> DTSPO-6488 - Flux v2 migration - test - admin - patch 2

apps/azure-devops/azure-devops-agent/test.yaml, apps/azure-devops/test/base/kustomization.yaml, clusters/test/base/kustomization.yaml, k8s/environments/test/cluster-00-overlay/kustomization.yaml, k8s/environments/test/cluster-01-overlay/kustomization.yaml
Migrate azure-devops to fluxv2 in test
```
[ ] Yes
[x] No
```
=> DTSPO-6488 - Flux v2 migration - test - azure-devops

apps/mi/mi-adf-shir/image-policy.yaml, apps/mi/mi-adf-shir/test/mi-adf-auth-values.enc.yaml, apps/mi/mi-adf-shir/test/test.yaml, apps/mi/mi-azure-functions/test-identity-patch.yaml, apps/mi/mi-azure-functions/test.yaml, apps/mi/mi-data-extractor/image-policy.yaml, apps/mi/mi-data-extractor/test-identity-patch.yaml, apps/mi/mi-data-extractor/test.yaml, apps/mi/mi-extraction-service/image-policy.yaml, apps/mi/mi-extraction-service/test-identity-patch.yaml, apps/mi/mi-extraction-service/test.yaml, apps/mi/mi-house-keeping-service/image-policy.yaml, apps/mi/mi-house-keeping-service/test-identity-patch.yaml, apps/mi/mi-house-keeping-service/test.yaml, apps/mi/mi-integration-service/image-policy.yaml, apps/mi/mi-integration-service/test-identity-patch.yaml, apps/mi/mi-integration-service/test.yaml, apps/mi/mi-staging-service/image-policy.yaml, apps/mi/mi-staging-service/test-identity-patch.yaml, apps/mi/mi-staging-service/test.yaml, apps/mi/test/base/kustomization.yaml, clusters/test/base/kustomization.yaml, k8s/environments/test/common-overlay/kustomization.yaml
tools.hmcts.net/jira/browse/DTSPO-6488
Migrate MI apps to flux v2 in test
[ ] Yes
[x] No
=> DTSPO-6488 - Flux v2 migration - test - mi

apps/neuvector/neuvector/stg/00.yaml, apps/neuvector/neuvector/stg/01.yaml, apps/neuvector/neuvector/stg/stg.yaml, apps/neuvector/stg/00/kustomization.yaml, apps/neuvector/stg/01/kustomization.yaml
=> Neuvector patch - staging

apps/mi/mi-adf-shir/test/mi-adf-auth-values.enc.yaml, apps/mi/mi-azure-functions/test.yaml
Fix mi-adf values
Update test image for azure-functions
```
[ ] Yes
[x] No
```
=> DTSPO-6488 - Flux v2 migration - test - mi - patch 2

apps/neuvector/identity/test.yaml, apps/neuvector/neuvector/test/00.yaml, apps/neuvector/neuvector/test/01.yaml, apps/neuvector/neuvector/test/test.yaml, apps/neuvector/test/00/kustomization.yaml, apps/neuvector/test/01/kustomization.yaml, apps/neuvector/test/base/fluentbit-log.yaml, apps/neuvector/test/base/kustomization.yaml, apps/neuvector/test/base/nv-storage-secret-hack.yaml, apps/neuvector/test/base/nv-storage-secret.yaml, k8s/environments/test/cluster-00-overlay/kustomization.yaml, k8s/environments/test/cluster-01-overlay/kustomization.yaml
Migrate neuvector to flux v2 on test
```
[ ] Yes
[x] No
```
=> DTSPO-6488 - Flux v2 migration - test - neuvector

clusters/test/base/kustomization.yaml
Add neuvector to test kustomization base
```
[ ] Yes
[x] No
```
=> DTSPO-6488 - Flux v2 migration - test - neuvector - patch 2

apps/neuvector/neuvector/stg/stg.yaml, apps/neuvector/neuvector/test/test.yaml
Fix reference to neuvector secret in vault
```
[ ] Yes
[x] No
```
=> DTSPO-6488 - Flux v2 migration - test - neuvector - patch 3

apps/pip/account-management/test.yaml, apps/pip/channel-management/test.yaml, apps/pip/data-management/test.yaml, apps/pip/frontend/test.yaml, apps/pip/identity/test.yaml, apps/pip/publication-services/test.yaml, apps/pip/subscription-management/test.yaml, apps/pip/test/base/azure-identity-patch.yaml, apps/pip/test/base/kustomization.yaml, clusters/test/base/kustomization.yaml, k8s/environments/test/common-overlay/kustomization.yaml
Migrate pip apps on test to fluxv2
```
[ ] Yes
[x] No
```
=> DTSPO-6488 - Flux v2 migration - test - pip

clusters/test/base/kustomization.yaml
Re-add neuvector
```
[ ] Yes
[x] No
```
=> DTSPO-6488 - Re-add neuvector

apps/pip/account-management/pip-account-management.yaml, apps/pip/channel-management/pip-channel-management.yaml, apps/pip/data-management/pip-data-management.yaml, apps/pip/frontend/pip-frontend.yaml, apps/pip/publication-services/pip-publication-services.yaml, apps/pip/subscription-management/pip-subscription-management.yaml
N/A
Updated old image versions
```
[ ] Yes
[x] No
```
=> Upated image versions for PIP

apps/pip/stg/base/kustomization.yaml
Add staging patch files for fluxv2
```
[ ] Yes
[ x ] No
```
=> PIP Add staging patch files for fluxv2

apps/pip/frontend/pip-frontend.yaml, apps/pip/ithc/base/kustomization.yaml, apps/pip/stg/base/kustomization.yaml, apps/pip/test/base/kustomization.yaml
Add test patch files
correct frontend language name
```
[ ] Yes
[ x ] No
```
=> PIP - add frontend fix and correct test patches

README.md
Update readme with updated flux migration status for test cluster
```
[ ] Yes
[x] No
```
=> DTSPO-6488 - Update test cluster flux migration status

apps/pip/account-management/image-repo.yaml, apps/pip/channel-management/image-repo.yaml, apps/pip/data-management/image-repo.yaml, apps/pip/frontend/image-repo.yaml, apps/pip/publication-services/image-repo.yaml, apps/pip/subscription-management/image-repo.yaml, apps/vh/admin-web/image-repo.yaml, apps/vh/booking-queue-subscriber/image-repo.yaml, apps/vh/bookings-api/image-repo.yaml, apps/vh/notification-api/image-repo.yaml, apps/vh/scheduler-jobs/image-repo.yaml, apps/vh/service-web/image-repo.yaml, apps/vh/test-api/image-repo.yaml, apps/vh/test-web/image-repo.yaml, apps/vh/user-api/image-repo.yaml, apps/vh/video-api/image-repo.yaml, apps/vh/video-web/image-repo.yaml
Fix broken image repos
```
[ ] Yes
[x] No
```
=> Fix image repos

apps/flux-system/test/01/kustomize.yaml
Update kustomize for test-01 to correct cluster
```
[ ] Yes
[x] No
```
=> DTSPO-6488 - Fix test-01 kustomize

README.md
https://tools.hmcts.net/jira/browse/DTSPO-6490
Migration to Flux v2 is complete.
```
[ ] Yes
[x] No
```
=> DTSPO-6490 Update Readme

apps/pip/account-management/pip-account-management.yaml, apps/pip/data-management/pip-data-management.yaml, apps/pip/frontend/pip-frontend.yaml, apps/pip/publication-services/pip-publication-services.yaml, apps/pip/subscription-management/pip-subscription-management.yaml
N/A
Updated images for PIP
```
[ ] Yes
[ ] No
```
=> Updated images for PIP

apps/pip/frontend/pip-frontend.yaml
N/A
Updated prod image
```
[ ] Yes
[x] No
```
=> Updated frontend image

apps/pip/frontend/pip-frontend.yaml, apps/pip/subscription-management/pip-subscription-management.yaml
N/A
Updated subscription image name
```
[ ] Yes
[x] No
```
=> Update subscription management image

apps/toffee/recipe-receiver/ithc.yaml, apps/toffee/recipe-receiver/sbox.yaml, apps/toffee/recipe-receiver/stg.yaml, apps/toffee/recipe-receiver/toffee-recipe-receiver.yaml
Adding values files for each env for keda
```
[ ] Yes
[x] No
```
=> DTSPO-8169 - switch to values files for envs

apps/toffee/frontend/demo.yaml
Add traefik tls setting to toffee in demo
```
[ ] Yes
[x] No
```
=> DTSPO-8837 - Update toffee traefik tls setting demo

apps/toffee/recipe-receiver/demo.yaml, apps/toffee/recipe-receiver/ithc.yaml, apps/toffee/recipe-receiver/sbox.yaml, apps/toffee/recipe-receiver/stg.yaml, apps/toffee/recipe-receiver/toffee-recipe-receiver.yaml
=> DTSPO-8169 - fix flux config for keda

apps/toffee/recipe-receiver/toffee-recipe-receiver.yaml
Fix env vars for recipe receiver
```
[ ] Yes
[x] No
```
=> DTSPO-8169 - fix env vars

k8s/charts/netbox-chart/values.yaml
Reverts hmcts/sds-flux-config#1803
Netbox and nginx throwing 502 bad gateway
=> Revert "Update helm values netboxcommunity/netbox to v2.11.12"

apps/mi/mi-azure-functions/stg.yaml
=> Fixed wrong clientId for stg mi azure functions

k8s/charts/netbox-chart/templates/configmap.yaml, k8s/charts/netbox-chart/templates/deployment.yaml, k8s/charts/netbox-chart/values.yaml
Fix issues with netbox after upgrade to newer version
```
[ ] Yes
[x] No
```
=> DTSPO-8837 - Fix netbox issues after upgrade

apps/pip/account-management/prod.yaml, apps/pip/channel-management/prod.yaml, apps/pip/data-management/prod.yaml, apps/pip/identity/prod.yaml, apps/pip/prod/base/azure-identity-patch.yaml, apps/pip/prod/base/kustomization.yaml, apps/pip/publication-services/prod.yaml, apps/pip/subscription-management/prod.yaml, clusters/prod/base/kustomization.yaml, k8s/environments/prod/common-overlay/kustomization.yaml
DTSPO-6494 
DTSPO-6494 - Migrate PIP to FluxV2
```
[ ] Yes
[X] No
```
=> DTSPO-6494 - Migrate PIP to FluxV2

apps/pip/frontend/prod.yaml, apps/pip/frontend/stg.yaml, apps/pip/frontend/test.yaml, k8s/namespaces/pip/pip-frontend/patches/prod/pip-frontend.yaml
Add PIP Frontend URL
```
[ ] Yes
[ x ] No
```
=> Add PIP Frontend URL

k8s/environments/prod/common-overlay/flux-patch.yaml
Removing patches for pip
```
[ ] Yes
[x] No
```
=> DTSPO-6494 - remove patches for pip

k8s/charts/netbox-chart/templates/configmap.yaml, k8s/charts/netbox-chart/templates/deployment.yaml, k8s/charts/netbox-chart/values.yaml
Revert netbox to 2.8.5
```
[ ] Yes
[x] No
```
=> DTSPO-8837 - Revert netbox to 2.8.5

k8s/charts/netbox-chart/templates/configmap.yaml, k8s/charts/netbox-chart/templates/deployment.yaml, k8s/charts/netbox-chart/values.yaml
Add postStart commands to ensure netbox starts correctly
```
[ ] Yes
[x] No
```
=> DTSPO-8837 - Add postStart commands to netbox

apps/dts-legacy/automation/kustomization.yaml, apps/dts-legacy/base/kustomization.yaml, apps/dts-legacy/base/kustomize.yaml, apps/dts-legacy/identity/identity.yaml, apps/dts-legacy/lgy-iac-web/image-policy.yaml, apps/dts-legacy/lgy-iac-web/image-repo.yaml, apps/dts-legacy/lgy-iac-web/lgy-iac-web.yaml, apps/dts-legacy/sbox/base/kustomization.yaml, apps/flux-system/automation/kustomization.yaml, clusters/sbox/base/kustomization.yaml
https://tools.hmcts.net/jira/browse/RST-4505
Initial flux config for the first app in DTS Legacy namespace
Create a sandbox only environment
```
[ ] Yes
[x] No
```
=> Adding IAC Fees application flux config with sandbox only environment

apps/mi/mi-adf-shir/stg/mi-adf-auth-values.enc.yaml, apps/mi/mi-azure-functions/dev.yaml, apps/mi/mi-azure-functions/ithc.yaml, apps/mi/mi-azure-functions/sbox.yaml, apps/mi/mi-azure-functions/stg.yaml, apps/mi/mi-azure-functions/test.yaml
Also changes azure-functions to target the new resource groups
=> Update MI SHIR Auth Key Secret

apps/mi/mi-adf-shir/dev/mi-adf-auth-values.enc.yaml
=> SDP Update dev shir

apps/juror-digital/jd-bureau/jd-bureau.yaml
=> Updated to 2.27

k8s/environments/prod/cluster-00/mi/mi-adf-shir.yaml
=> Restart MI Adf SHIR for Prod

apps/pip/account-management/pip-account-management.yaml
N/A
Updated image for account management
```
[ ] Yes
[ ] No
```
=> Updated image for PIP

apps/toffee/frontend/toffee-frontend.yaml, apps/toffee/recipe-backend/toffee-recipe-backend.yaml
Removing custom startup config, the defaults are fine 
```
[ ] Yes
[x] No
```
=> use default values for startup probe

clusters/stg/00/kustomization.yaml, clusters/stg/base/kustomization.yaml
testing deploying to single cluster
```
[ ] Yes
[x] No
```
=> DTSPO-6494 - test deploying to cluster 00 only

clusters/stg/00/kustomization.yaml, clusters/stg/01/kustomization.yaml
Testing switching app to different cluster
```
[ ] Yes
[x] No
```
=> DTSPO-6494 - switch toffee to staging 01

clusters/stg/00/kustomization.yaml, clusters/stg/01/kustomization.yaml
This should work, tested it locally and looks like it gives us what we want
```
[ ] Yes
[x] No
```
=> DTSPO-6494 - deploy toffee to cluster 00 only

clusters/stg/01/kustomization.yaml
deploy toffee to stg 01
```
[ ] Yes
[x] No
```
=> DTSPO-6494 - deploy toffee to cluster 01 only

apps/pip/account-management/pip-account-management.yaml
N/A
Updated account management image
```
[ ] Yes
[x] No
```
=> Updated image

apps/pip/account-management/pip-account-management.yaml
N/A
Updated image for AM
```
[ ] Yes
[x] No
```
=> Updated image for AM

apps/admin/keda/prod/identity.yaml
Updating the MI for keda in prod as the CFT one was accidentally used.
```
[ ] Yes
[x] No
```
=> DTSPO-8169 - fix managed identity config for keda in prod

k8s/environments/prod/cluster-01-overlay/flux-patch.yaml
Add missing patch file 
```
[ ] Yes
[x] No
```
=> DTSPO-6494 - add patch file for vh prod 01

k8s/environments/prod/common-overlay/flux-patch.yaml
not need anymore 
```
[ ] Yes
[x] No
```
=> Remove old vh patch config

apps/juror-digital/base/kustomization.yaml, apps/juror-digital/dev/base/kustomization.yaml, apps/juror-digital/identity/dev-identity-patch.yaml, apps/juror-digital/identity/dev.yaml, apps/juror-digital/identity/juror-digital-azure-identity-binding.yaml, apps/juror-digital/identity/juror-digital-azure-identity.yaml
Tidying up Juror digital identity
```
[ ] Yes
[x] No
```
=> DTSPO-6494 - tidy up identity for jd dev

apps/mi/mi-azure-functions/dev.yaml, apps/mi/mi-azure-functions/ithc.yaml, apps/mi/mi-azure-functions/sbox.yaml, apps/mi/mi-azure-functions/stg.yaml, apps/mi/mi-azure-functions/test.yaml
Add whitespace between hash and imagePolicy, and fix existing tags used
=> Fix Mi Azure Functions Image Policy

apps/mi/mi-reverse-proxy/dev-secret-provider-patch.yaml, apps/mi/mi-reverse-proxy/mi-reverse-proxy.yaml, apps/mi/mi-reverse-proxy/test-secret-provider-patch.yaml
Issue with case sensitivity of the patch in the secret-provider has been resolved.
=> Fixed patch for mi reverse proxy secret-provider

apps/mailrelay2/dev/base/kustomization.yaml
Removing certs as they apparently aren't needed any longer
```
[ ] Yes
[x] No
```
=> Removing certs as they apparently aren't needed any longer

apps/pip/data-management/pip-data-management.yaml, apps/pip/frontend/pip-frontend.yaml
N/A
Update images for PIP
```
[ ] Yes
[x] No
```
=> Update Images for PIP

apps/pip/channel-management/pip-channel-management.yaml, apps/pip/data-management/pip-data-management.yaml, apps/pip/frontend/pip-frontend.yaml, apps/pip/publication-services/pip-publication-services.yaml
N/A
Updated pods for PIP
```
[ ] Yes
[x] No
```
=> Updated pod values

apps/pip/frontend/pip-frontend.yaml
N/A
Updated image for pip frontend
```
[ ] Yes
[x] No
```
=> Updated image for pip frontend

apps/pip/account-management/image-policy.yaml, apps/pip/channel-management/image-policy.yaml, apps/pip/data-management/image-policy.yaml, apps/pip/frontend/image-policy.yaml, apps/pip/publication-services/image-policy.yaml, apps/pip/subscription-management/image-policy.yaml
Removing annotation and duplicate config from image policies 
```
[ ] Yes
[x] No
```
=> remove duplicate config

clusters/prod/00/kustomization.yaml, clusters/prod/01/kustomization.yaml, clusters/prod/base/kustomization.yaml
Deploying mailrelay2 to 01 and moving config into base 
```
[ ] Yes
[x] No
```
=> DTSPO-6494 - deploy mailrelay2 to prod 01

apps/neuvector/neuvector/neuvector.yaml, k8s/namespaces/neuvector/neuvector.yaml, k8s/namespaces/neuvector/patches/ithc/cluster-00/neuvector.yaml, k8s/namespaces/neuvector/patches/ithc/cluster-01/neuvector.yaml
=> Upgrading neuvector chart and set forcelicense flag to renew license

clusters/stg/00/kustomization.yaml, clusters/stg/01/kustomization.yaml
This is probably not a issue
```
[ ] Yes
[x] No
```
=> try fixing stg kustomize issues

clusters/stg/00/kustomization.yaml, clusters/stg/01/kustomization.yaml, clusters/stg/base/kustomization.yaml
=> move toffee to stg base

apps/neuvector/neuvector/neuvector.yaml, k8s/namespaces/neuvector/neuvector.yaml
=> Disable nv license foceupdate

k8s/environments/prod/cluster-01-overlay/kustomization.yaml
Remove mailrelay flux v1 config from prod-01 
```
[ ] Yes
[x] No
```
=> DTSPO-6494 - remove mailrelay from prod-01 cluster

k8s/environments/prod/cluster-00-overlay/kustomization.yaml
and pod identity
```
[ ] Yes
[x] No
```
=> DTSPO-6495 - remove flux v1 traefik config from prod 00

apps/vh/dev/base/kustomization.yaml
VIH-9999
Re add Dev Identity Patch.
```
[ ] Yes
[x ] No
```
=> VIH-9999 - Re-Add Dev identity.

k8s/namespaces/jenkins/patches/ptl/cluster-00/jenkins.yaml
=> Swapping Jenkins to 00

apps/pip/channel-management/prod.yaml, apps/pip/channel-management/test.yaml, apps/pip/data-management/test.yaml, apps/pip/publication-services/prod.yaml, apps/pip/publication-services/test.yaml, apps/pip/subscription-management/prod.yaml, apps/pip/subscription-management/test.yaml
N/A
Added missing URL's for PIP Prod
```
[ ] Yes
[x] No
```
=> Updated URLs

k8s/environments/prod/cluster-01-overlay/kustomization.yaml
Removing nv from prod 01
```
[ ] Yes
[x] No
```
=> DTSPO-6494 - remove nv from prod 01

k8s/environments/ptl/cluster-00-overlay/kustomization.yaml
=> add reader perms for devs on ptl to debug image automation

apps/vh/automation/kustomization.yaml, apps/vh/base/kustomization.yaml, apps/vh/demo/base/kustomization.yaml, apps/vh/dev/base/kustomization.yaml, apps/vh/prod/base/kustomization.yaml, apps/vh/stg/base/kustomization.yaml, apps/vh/test/base/kustomization.yaml, apps/vh/video-api/demo.yaml, apps/vh/video-api/dev.yaml, apps/vh/video-api/image-policy.yaml, apps/vh/video-api/image-repo.yaml, apps/vh/video-api/prod.yaml, apps/vh/video-api/stg.yaml, apps/vh/video-api/test.yaml, apps/vh/video-api/video-api.yaml
VIH-8972
Add Video API
```
[ ] Yes
[ x ] No
```
=> VIH-8972 - Add Video API

k8s/namespaces/jenkins/patches/ptl/cluster-00/jenkins.yaml, k8s/namespaces/jenkins/patches/ptlsbox/cluster-00/jenkins.yaml
https://tools.hmcts.net/jira/browse/DTSPO-9278
Set disableTraefikTls flag to false in SDS jenkins, set to true in CFT below:
https://github.com/hmcts/cnp-flux-config/pull/16592
```
[ ] Yes
[ ] No
```
=> Set flag to false

apps/vh/notification-api/demo.yaml, apps/vh/notification-api/dev.yaml, apps/vh/notification-api/image-policy.yaml, apps/vh/notification-api/prod.yaml, apps/vh/notification-api/stg.yaml, apps/vh/notification-api/test.yaml
VIH-8975
SDS Flux Patch for Notification Api
```
[ ] Yes
[ x ] No
```
=> VIH-8975 - SDS Flux Patch Notification Api

apps/vh/bookings-api/image-policy.yaml, apps/vh/bookings-api/prod.yaml, apps/vh/user-api/image-policy.yaml, apps/vh/user-api/prod.yaml
VIH-8975
Update prod image policies for user api & bookings api
```
[ ] Yes
[ x ] No
```
=> VIH-8975 - Update prod image policies for user api & bookings api

apps/mailrelay2/mailrelay2/dev/dev.yaml
https://tools.hmcts.net/jira/browse/DTSPO-4401
Getting certificate mismatch errors of some sort, updating config to use the same certificate.
```
[ ] Yes
[ ] No
```
=> DTSPO-4401: Updated image and certificate configuration

apps/vh/automation/kustomization.yaml, apps/vh/base/kustomization.yaml, apps/vh/demo/base/kustomization.yaml, apps/vh/dev/base/kustomization.yaml, apps/vh/prod/base/kustomization.yaml, apps/vh/stg/base/kustomization.yaml, apps/vh/test-api/demo.yaml, apps/vh/test-api/dev.yaml, apps/vh/test-api/image-policy.yaml, apps/vh/test-api/image-repo.yaml, apps/vh/test-api/prod.yaml, apps/vh/test-api/stg.yaml, apps/vh/test-api/test-api.yaml, apps/vh/test-api/test.yaml, apps/vh/test/base/kustomization.yaml, k8s/namespaces/vh/kustomization.yaml
VIH-8969 
add flux patches for test api.
```
[ ] Yes
[ x] No
```
=> VIH-8969 - Test Api Patches

apps/mailrelay2/mailrelay2/dev/mailrelay-values.enc.yaml
https://tools.hmcts.net/jira/browse/DTSPO-8561
Updated the release namespace to correct value
```
[ ] Yes
[ ] No
```
=> DTSPO-8561: Updated release namespace to correct value

apps/mailrelay/dev/base/kustomization.yaml, apps/mailrelay/prod/base/kustomization.yaml, apps/mailrelay2/mailrelay2/dev/mailrelay-values.enc.yaml
https://tools.hmcts.net/jira/browse/DTSPO-8561
Re-generated the sops generate file as a manual change was made, just to be sure it does not make the file invalid to sops
Also updated `sops` on my machine as new version is available.
```
[ ] Yes
[ ] No
```
=> DTSPO-8561: connectivity from external clients 3

apps/vh/admin-web/admin-web.yaml, apps/vh/admin-web/demo.yaml, apps/vh/admin-web/dev.yaml, apps/vh/admin-web/image-policy.yaml, apps/vh/admin-web/image-repo.yaml, apps/vh/admin-web/prod.yaml, apps/vh/admin-web/stg.yaml, apps/vh/admin-web/test.yaml, apps/vh/automation/kustomization.yaml, apps/vh/base/kustomization.yaml, apps/vh/demo/base/kustomization.yaml, apps/vh/dev/base/kustomization.yaml, apps/vh/prod/base/kustomization.yaml, apps/vh/stg/base/kustomization.yaml, apps/vh/test/base/kustomization.yaml
VIH-8966
Add Admin Web Flux Config
```
[ ] Yes
[ x ] No
```
=> VIH-8966 - Add Admin Web Flux Config

clusters/prod/base/kustomization.yaml
Add VH To Prod
VIH-9999 - Add VH to Prod
```
[ ] Yes
[ ] No
```
=> VIH-9999 - Add VH to Prod

k8s/namespaces/jenkins/patches/ptl/cluster-00/jenkins.yaml, k8s/namespaces/jenkins/patches/ptlsbox/cluster-00/jenkins.yaml
Reverts hmcts/sds-flux-config#2042
this is not correct
=> Revert "Set flag to false"

apps/azure-devops/azure-devops-agent/ptlsbox.yaml, apps/azure-devops/ptlsbox/base/kustomization.yaml, clusters/ptlsbox/base/kustomization.yaml, k8s/environments/ptlsbox/cluster-00-overlay/kustomization.yaml
Migrating the azure devops agent to flux v2
```
[ ] Yes
[x] No
```
=> DTSPO-6493 - ptlsbox flux v2 - migrate ado agent

apps/admin/kube-slack/ptlsbox/kube-slack-values.enc.yaml, apps/admin/kured/ptlsbox/kured-values.enc.yaml, apps/monitoring/ptlsbox/prometheus-values.enc.yaml, apps/netbox/ptlsbox/netbox-postgresql.enc.yaml, apps/netbox/ptlsbox/netbox-redis.enc.yaml
Just Re-encrypting the ptlsbox secrets and moving them to right location. Config to come in future prs.
```
[ ] Yes
[x] No
```
=> DTSPO-2880 - re-encrypt secrets

README.md, k8s/environments/ptlsbox/cluster-00-overlay/kustomization.yaml
Removing admin apps from ptlsbox
```
[ ] Yes
[x] No
```
=> DTSPO-6493 - remove admin apps from flux v1

apps/netbox/netbox/netbox.yaml, k8s/environments/ptlsbox/cluster-00-overlay/kustomization.yaml
Remove ptlsbox flux v1 config for netbox 
Increasing timeout on netbox release as 5 minutes isn't enough
```
[ ] Yes
[x] No
```
=> DTSPO-6493 - flux v1 remove netbox

apps/jenkins/base/kustomization.yaml, apps/jenkins/base/kustomize.yaml, apps/jenkins/identity/identity.yaml, apps/jenkins/identity/ptl.yaml, apps/jenkins/identity/ptlsbox.yaml, apps/jenkins/jenkins/disk.yaml, apps/jenkins/jenkins/jenkins.yaml, apps/jenkins/jenkins/kustomization.yaml, apps/jenkins/jenkins/logging.yaml, apps/jenkins/jenkins/ptl/disk.yaml, apps/jenkins/jenkins/ptl/jenkins.yaml, apps/jenkins/jenkins/ptlsbox/disk.yaml, apps/jenkins/jenkins/ptlsbox/jenkins.yaml, apps/jenkins/ptl/00/kustomization.yaml, apps/jenkins/ptl/base/kustomization.yaml, apps/jenkins/ptlsbox/00/kustomization.yaml, apps/jenkins/ptlsbox/base/kustomization.yaml, clusters/ptlsbox/base/kustomization.yaml
- Added flux v2 config for PTL and PTLSBOX
- Added jenkins to PTLSBOX flux v2 sync
```
[ ] Yes
[x] No
```
=> DTSPO-6493 - add flux v2 jenkins config to ptlsbox

apps/jenkins/identity/identity.yaml, apps/jenkins/identity/ptl.yaml, apps/jenkins/identity/ptlsbox.yaml, apps/jenkins/jenkins/disk.yaml, apps/jenkins/jenkins/kustomization.yaml, apps/jenkins/jenkins/ptlsbox/disk.yaml, apps/jenkins/ptl/00/kustomization.yaml, apps/jenkins/ptlsbox/00/kustomization.yaml
Kustomization doesn't want to work, removing resources to start debugging
```
[ ] Yes
[x] No
```
=> DTSPO-6493 - debugging - remove jenkins hr

apps/mailrelay2/mailrelay2/dev/dev.yaml, apps/mailrelay2/mailrelay2/prod/prod.yaml
https://tools.hmcts.net/jira/browse/DTSPO-8561
Reverting back, previous setting was the right one
```
[ ] Yes
[ ] No
```
=> DTSPO-8561: Revert to previous value

apps/pip/frontend/test.yaml
=> Updated test image

apps/dts-legacy/dev/base/kustomization.yaml, apps/dts-legacy/stg/base/kustomization.yaml, clusters/dev/base/kustomization.yaml, clusters/stg/base/kustomization.yaml
https://tools.hmcts.net/jira/browse/RST-4469
Add dev and stg namespaces for dts-legacy apps
```
[ ] Yes
[x] No
```
=> Add dev and stg namespaces for dts-legacy

k8s/environments/ptl/cluster-00-overlay/kustomization.yaml
remove admin ns from flux v1 sync
```
[ ] Yes
[x] No
```
=> DTSPO-6492 - ptl - remove admin ns from flux v1 sync

k8s/environments/ptl/cluster-00-overlay/kustomization.yaml
Removing Jenkins ns from flux v1 sync, will merge this later on tonight when its quieter.
```
[ ] Yes
[x] No
```
=> DTSPO-6492 - PTL - remove jenkins ns from flux v1 sync

apps/kube-system/demo/base/kustomization.yaml, apps/kube-system/dev/base/kustomization.yaml, apps/kube-system/ithc/base/kustomization.yaml, apps/kube-system/prod/base/kustomization.yaml, apps/kube-system/ptl/base/kustomization.yaml, apps/kube-system/ptlsbox/base/kustomization.yaml, apps/kube-system/test/base/kustomization.yaml, clusters/demo/base/kustomization.yaml, clusters/dev/base/kustomization.yaml, clusters/ithc/base/kustomization.yaml, clusters/prod/base/kustomization.yaml, clusters/ptl/base/kustomization.yaml, clusters/ptlsbox/base/kustomization.yaml, clusters/stg/base/kustomization.yaml, clusters/test/base/kustomization.yaml
Adding kube-system to flux v2 sync for all environments (it was already there for sbox)
```
[ ] Yes
[x] No
```
=> DTSPO-6492 - add kube-system mic exception to flux v2 config

apps/vh/automation/kustomization.yaml, apps/vh/base/kustomization.yaml, apps/vh/demo/base/kustomization.yaml, apps/vh/dev/base/kustomization.yaml, apps/vh/prod/base/kustomization.yaml, apps/vh/scheduler-jobs/demo.yaml, apps/vh/scheduler-jobs/dev.yaml, apps/vh/scheduler-jobs/image-policy.yaml, apps/vh/scheduler-jobs/image-repo.yaml, apps/vh/scheduler-jobs/prod.yaml, apps/vh/scheduler-jobs/scheduler-jobs.yaml, apps/vh/scheduler-jobs/stg.yaml, apps/vh/scheduler-jobs/test.yaml, apps/vh/stg/base/kustomization.yaml, apps/vh/test/base/kustomization.yaml
VIH-9130
Add scheduler-jobs flux config
```
[ ] Yes
[ x ] No
```
=> VIH-9130 - Add scheduler-jobs flux config

apps/mailrelay2/mailrelay2/dev/dev.yaml, apps/mailrelay2/mailrelay2/prod/prod.yaml
https://tools.hmcts.net/jira/browse/DTSPO-9393
updating tag version for dev & prod
```
[X] Yes
[ ] No
```
=> update version tag in dev & prod

apps/mailrelay2/mailrelay2/dev/dev.yaml, apps/mailrelay2/mailrelay2/mailrelay2.yaml, apps/mailrelay2/mailrelay2/prod/prod.yaml
https://tools.hmcts.net/jira/browse/DTSPO-9393
updated tags to v0.2.16
```
[ ] Yes
[x] No
```
=> Dtspo 9393 update tag

apps/dts-legacy/lgy-iac-web/image-repo.yaml, apps/dts-legacy/lgy-iac-web/lgy-iac-web.yaml
https://tools.hmcts.net/jira/browse/RST-4505
- change image url to be sdshmctspublic
- remove namespace from metadata (doesn't seem to be used in other projects)
```
[ ] Yes
[x] No
```
=> Modify the chart values to match pip-frontend

apps/admin/aad-pod-identity/aks-kubelet-binding.yaml, apps/admin/aad-pod-identity/aks-kubelet-identity.yaml, apps/admin/aad-pod-identity/kustomization.yaml, apps/admin/aad-pod-identity/sbox/azure-kubelet-identity-patch.yaml, apps/admin/sbox/base/kustomization.yaml, apps/flux-system/automation/registry-credential-sync/sdshmctspublic/kustomization.yaml, apps/flux-system/sbox/base/kustomization.yaml
https://tools.hmcts.net/jira/browse/DTSPO-8697
Add patches for using newer method of authenticating to ACR in flux
```
[ ] Yes
[x] No
```
=> DTSPO-8697 - Update image automation auth

apps/vh/admin-web/prod.yaml, apps/vh/admin-web/stg.yaml
VIH-8966
amend overides for stg
```
[ ] Yes
[ x ] No
```
=> VIH-8966 - amend overrides for stg

apps/vh/admin-web/prod.yaml
add prod config for admin web
```
[ ] Yes
[x ] No
```
=> VIh-9999 - add prod config for admin web

apps/pip/frontend/test.yaml
Updated test pod
```
[ ] Yes
[x] No
```
=> Updated test

apps/toffee/identity/sbox.yaml
toffee sbox id was deleted, so I reran the pipeline to re-create
```
[ ] Yes
[x] No
```
=> Update toffee client id 

apps/vh/bookings-api/demo.yaml, apps/vh/bookings-api/dev.yaml, apps/vh/bookings-api/prod.yaml, apps/vh/bookings-api/stg.yaml, apps/vh/bookings-api/test.yaml, apps/vh/scheduler-jobs/demo.yaml, apps/vh/scheduler-jobs/dev.yaml, apps/vh/scheduler-jobs/image-policy.yaml, apps/vh/scheduler-jobs/prod.yaml, apps/vh/scheduler-jobs/stg.yaml, apps/vh/scheduler-jobs/test.yaml, apps/vh/user-api/demo.yaml, apps/vh/user-api/dev.yaml, apps/vh/user-api/prod.yaml, apps/vh/user-api/stg.yaml, apps/vh/user-api/test.yaml, apps/vh/video-api/demo.yaml, apps/vh/video-api/dev.yaml, apps/vh/video-api/image-policy.yaml, apps/vh/video-api/prod.yaml, apps/vh/video-api/stg.yaml, apps/vh/video-api/test.yaml
- Amend Image Policies
- Amend unrequired settings.
```
[ ] Yes
[ ] No
```
=> VIH-9999 - Amend API & Web App Configs.

apps/admin/aad-pod-identity/demo/azure-kubelet-identity-patch.yaml, apps/admin/aad-pod-identity/dev/azure-kubelet-identity-patch.yaml, apps/admin/aad-pod-identity/ithc/azure-kubelet-identity-patch.yaml, apps/admin/aad-pod-identity/prod/azure-kubelet-identity-patch.yaml, apps/admin/aad-pod-identity/ptl/azure-kubelet-identity-patch.yaml, apps/admin/aad-pod-identity/ptlsbox/azure-kubelet-identity-patch.yaml, apps/admin/aad-pod-identity/stg/azure-kubelet-identity-patch.yaml, apps/admin/aad-pod-identity/test/azure-kubelet-identity-patch.yaml, apps/admin/demo/base/kustomization.yaml, apps/admin/dev/base/kustomization.yaml, apps/admin/ithc/base/kustomization.yaml, apps/admin/prod/base/kustomization.yaml, apps/admin/ptl/base/kustomization.yaml, apps/admin/ptlsbox/base/kustomization.yaml, apps/admin/stg/base/kustomization.yaml, apps/admin/test/base/kustomization.yaml, apps/flux-system/demo/base/kustomization.yaml, apps/flux-system/dev/base/kustomization.yaml, apps/flux-system/ithc/base/kustomization.yaml, apps/flux-system/prod/base/kustomization.yaml, apps/flux-system/ptl/base/kustomization.yaml, apps/flux-system/ptlsbox/base/kustomization.yaml, apps/flux-system/stg/base/kustomization.yaml, apps/flux-system/test/base/kustomization.yaml
https://tools.hmcts.net/jira/browse/DSTPO-9517
Add new image automation authentication method to other nonprod environments
```
[ ] Yes
[x] No
```
=> DTSPO-9517 - Add image auth to other nonprod envs

apps/mailrelay2/mailrelay2/dev/dev.yaml, apps/mailrelay2/mailrelay2/mailrelay2.yaml
Configuration modifications where made to the exim conf file to further tune smtp relay
Looking through documentation to better understand exim configuration settings. Making changes to further tune the smpt relay using the smarthost. Need to update the tag as new image has been created.
```
[ ] Yes
[ ] No
```
=> DTSPO-6561: Exim image tag update

apps/mailrelay2/mailrelay2/mailrelay2.yaml
Minor update to tag version
```
[ ] Yes
[ ] No
```
=> Tag version update

apps/admin/demo/base/kustomization.yaml, clusters/demo/base/kustomization.yaml
remove csi driver from demo cluster
```
[ ] Yes
[x] No
```
=> DTSPO-9539 - remove csi driver from demo cluster

apps/admin/dev/base/kustomization.yaml, apps/admin/ithc/base/kustomization.yaml, apps/admin/stg/base/kustomization.yaml, apps/admin/test/base/kustomization.yaml, clusters/dev/base/kustomization.yaml, clusters/ithc/base/kustomization.yaml, clusters/stg/base/kustomization.yaml, clusters/test/base/kustomization.yaml
removing csi driver config from the dev, test, stg and ithc cluster
```
[ ] Yes
[x] No
```
=> DTSPO-9539 - remove csi driver dev test stg ithc

apps/c100/base/kustomization.yaml, apps/c100/base/kustomize.yaml, apps/c100/demo/base/kustomization.yaml, apps/c100/dev/base/kustomization.yaml, apps/c100/ithc/base/kustomization.yaml, apps/c100/prod/base/kustomization.yaml, apps/c100/stg/base/kustomization.yaml, apps/c100/test/base/kustomization.yaml, clusters/demo/base/kustomization.yaml, clusters/dev/base/kustomization.yaml, clusters/ithc/base/kustomization.yaml, clusters/prod/base/kustomization.yaml, clusters/stg/base/kustomization.yaml, clusters/test/base/kustomization.yaml
I just ran the scripts in the bin directory, it changed some indenting, let's see if it passes
=> DTSPO-9578 Add namespace for c100

apps/mailrelay2/mailrelay2/dev/dev.yaml, apps/mailrelay2/mailrelay2/mailrelay2.yaml
Fixing error:
`Exim configuration error for smarthost router:
route_list or route_data (but not both) must be specified`
Need to update the image tag as a new one will be built via the exim repo [PR](https://github.com/hmcts/exim-relay/pull/55) 
```
[ ] Yes
[ ] No
```
=> DTSPO-8561: Fix update to config

apps/admin/ptlsbox/base/kustomization.yaml, clusters/ptlsbox/base/kustomization.yaml
Remove csi driver from pltsbox cluster
```
[ ] Yes
[x] No
```
=> DTSPO-9539 - remove csi driver from pltsbox cluster

apps/admin/ptl/base/kustomization.yaml, clusters/ptl/base/kustomization.yaml
remove csi driver from ptl cluster
```
[ ] Yes
[x] No
```
=> DTSPO-9539 - remove csi driver from ptl cluster

apps/vh/admin-web/demo.yaml, apps/vh/bookings-api/demo.yaml, apps/vh/notification-api/demo.yaml, apps/vh/scheduler-jobs/demo.yaml, apps/vh/test-api/demo.yaml, apps/vh/user-api/demo.yaml, apps/vh/video-api/demo.yaml, apps/vh/video-web/demo.yaml
amend VH demo apps
```
[ ] Yes
[ x ] No
```
=> VIH-9999 - amend VH demo apps

apps/pip/frontend/test.yaml
Updated pip test image
```
[ ] Yes
[x] No
```
=> Updated pip test image

apps/pip/frontend/test.yaml
=> Remove image for test pip

apps/pip/frontend/prod.yaml
Added admin config endpoint for pip
```
[ ] Yes
[x] No
```
=> PIP Added admin config endpoint

apps/pip/data-management/prod.yaml, apps/pip/data-management/stg.yaml, apps/pip/data-management/test.yaml
https://tools.hmcts.net/jira/browse/PUB-1504
Added the PUBLICATION_SERVICES_URL for stg, test and prod for pip.
```
[ ] Yes
[x] No
```
=> Update env vars for PIP

apps/pip/frontend/test.yaml
Updating PIP test image
```
[ ] Yes
[x] No
```
=> update test image pip

apps/pip/frontend/test.yaml
Update PIP test image
```
[ ] Yes
[x] No
```
=> Update test PIP

apps/pip/frontend/test.yaml
=> PIP test image update

apps/mi/mi-adf-shir/dev.yaml, apps/mi/mi-adf-shir/image-policy-dev.yaml, apps/mi/mi-adf-shir/ithc.yaml, apps/mi/mi-adf-shir/prod.yaml, apps/mi/mi-adf-shir/sbox.yaml, apps/mi/mi-adf-shir/stg.yaml, apps/mi/mi-adf-shir/test.yaml
Attempt to fix, needs further checking.
=> Fixed SHIR imagepolicy

apps/juror-digital/jd-public/jd-public.yaml
Release for 2.29 Juror digital into NLE. Updated image version to reflect latest version.
```
[ ] Yes
[ ] No
```
=> 2.29 NLE JD Release

apps/jenkins/jenkins/ptl/jenkins.yaml, apps/jenkins/jenkins/ptlsbox/jenkins.yaml
https://tools.hmcts.net/jira/browse/DTSPO-8699
Update jenkins agent to 1.4.2
```
[ ] Yes
[x] No
```
=> DTSPO-8699 - Update jenkins agent

apps/jenkins/jenkins/ptl/jenkins.yaml, apps/jenkins/jenkins/ptlsbox/jenkins.yaml
Includes https://github.com/hmcts/jenkins-packer/pull/99
=> DTSPO-9578 Update agent

CODEOWNERS, CODEOWNERS.md
Add codeowners
```
[ ] Yes
[x] No
```
=> DTSPO-8837 - Add codeowners

apps/rbac/nonprod-role.yaml
Updating the helm release api version to the one used by flux v2 
```
[ ] Yes
[x] No
```
=>  DTSPO-9739 - update api for helmreleases

apps/jenkins/jenkins/ptlsbox/jenkins.yaml
=> Upgrade sandbox SDS Jenkins

apps/jenkins/jenkins/ptl/jenkins.yaml
https://tools.hmcts.net/jira/browse/DTSPO-8699
Adding envVars for ptl in jenkins config so they can be used in reconciling image repository
```
[ ] Yes
[x] No
```
=> DTSPO-8699 - Add envVars for ptl

apps/mailrelay2/mailrelay2/prod/prod.yaml
https://tools.hmcts.net/jira/browse/DTSPO-9705
Bringing prod up-to-speed as well
```
[ ] Yes
[ ] No
```
=> DTSPO-9705: Update to recent image tag

apps/jenkins/jenkins/jenkins.yaml, apps/jenkins/jenkins/ptlsbox/jenkins.yaml
=> upgrade prod jenkins

apps/c100/identity/prod.yaml, apps/c100/prod/base/kustomization.yaml
=> Dtspo 9828

apps/mailrelay2/mailrelay2/dev/dev.yaml, apps/mailrelay2/mailrelay2/prod/prod.yaml
https://tools.hmcts.net/jira/browse/DTSPO-9852
Bringin UIpath onboard
```
[ ] Yes
[ ] No
```
=> DTSPO-9852: Bringing UIpath onboard

apps/mailrelay2/mailrelay2/dev/dev.yaml
https://tools.hmcts.net/jira/browse/DTSPO-4414
Adding `pcol` details for `pcol` authentication to the relay
```
[ ] Yes
[ ] No
```
=> DTSPO-4414: Bringing pcol dev onboard

CODEOWNERS
Allow Juror Digital team to approve PRs for flux config changes to their apps
```
[ ] Yes
[x] No
```
=> Allow Juror Digital team to approve PRs for flux changes to their apps

apps/juror-digital/jd-bureau/prod.yaml, apps/juror-digital/jd-public/prod.yaml
Updated the image numbers in each .yaml to reflect the new versions of Juror Digital.
```
[ ] Yes
[X] No
```
=> Latest version numbers of Juror Digital 2.29

apps/pip/publication-services/prod.yaml, apps/pip/publication-services/stg.yaml
https://tools.hmcts.net/jira/browse/PUB-1502
Updated the sign in links. They were missing the response type as POST, so was erroring while returning to the service.
```
[ ] Yes
[x] No
```
=> PUB-1502 - Updated Sign In links

apps/c100/demo/base/kustomization.yaml
Add demo patch for c100
```
[ ] Yes
[x] No
```
=> Add demo patch for c100

apps/c100/c100-application/c100-application.yaml, apps/c100/c100-application/stg.yaml
Fixed to set the correct values
```
[ ] Yes
[x] No
```
=> Fix c100 flux config

apps/dts-legacy/identity/dev.yaml
https://tools.hmcts.net/jira/browse/RST-4469
Give access to staging mi in dev env for lgy-ac-web application
```
[ ] Yes
[x] No
```
=> Add the staging managed identity to the dev environment for lgy-iac-web

apps/jenkins/jenkins/ptl/jenkins.yaml
https://tools.hmcts.net/jira/browse/DTSPO-6455 
```
[ ] Yes
[x] No
```
=> Update PTL jenkins agent to 1.4.5

apps/rbac/nonprod-role.yaml
Update Non Prod Role
```
[ ] Yes
[ ] No
```
=> VIH-9999 - Update Non Prod Role

apps/jenkins/jenkins/ptl/jenkins.yaml, apps/jenkins/jenkins/ptlsbox/jenkins.yaml
https://tools.hmcts.net/jira/browse/DTSPO-9910
Update jenkins agent with pyenv support
```
[ ] Yes
[x] No
```
=> DTSPO-9910 - Update jenkins agent

apps/vh/booking-queue-subscriber/booking-queue-subscriber.yaml, apps/vh/booking-queue-subscriber/demo.yaml, apps/vh/booking-queue-subscriber/dev.yaml, apps/vh/booking-queue-subscriber/prod.yaml, apps/vh/booking-queue-subscriber/stg.yaml, apps/vh/booking-queue-subscriber/test.yaml
Update BQS
```
[ ] Yes
[x ] No
```
=> VIH-9999 - Update BQS

apps/admin/reply-urls-operator/kustomization.yaml, apps/admin/reply-urls-operator/sbox/secret.enc.yaml, apps/admin/sbox/00/kustomization.yaml
Testing on the branch im working on for now, will move to master once its all good.
```
[ ] Yes
[x] No
```
=> DTSPO-6556 - add reply url operator flux config

apps/admin/reply-urls-operator/sbox/reply-url-sync-config.yaml
Added sync config to sbox
```
[ ] Yes
[x] No
```
=> DTSPO-6556 - add reply url sync flux config

CODEOWNERS, apps/pip/publication-services/prod.yaml, apps/pip/publication-services/stg.yaml
https://tools.hmcts.net/jira/browse/PUB-1455
Update gov notify links
```
[ ] Yes
[x] No
```
=> Pub 1455 - Update gov notify links

apps/admin/reply-urls-operator/kustomization.yaml
=> Fix branch name

apps/admin/reply-urls-operator/sbox/reply-url-sync-config.yaml
=> update sync config

apps/vh/booking-queue-subscriber/demo.yaml, apps/vh/booking-queue-subscriber/dev.yaml, apps/vh/booking-queue-subscriber/prod.yaml, apps/vh/booking-queue-subscriber/stg.yaml, apps/vh/booking-queue-subscriber/test.yaml
VIH-9273 
amend booking queue
```
[ ] Yes
[ x ] No
```
=> VIH-9273 - amend booking queue

apps/juror-digital/jd-bureau/jd-bureau.yaml, apps/juror-digital/jd-public/jd-public.yaml
=> Updated NLE to 2.30

apps/admin/reply-urls-operator/sbox/deployment-patch.yaml, apps/admin/sbox/00/kustomization.yaml
- Bringing image config to sds flux
```
[ ] Yes
[x] No
```
=> DTSPO-6556 - add image config for reply-urls-operator

apps/toffee/frontend/toffee-frontend.yaml
Testing moving ingressClassName to the spec of the ingress rather than an annotation
```
[ ] Yes
[x] No
```
=> DTSPO-6556 - test moving ingressClassName to spec

apps/admin/demo/base/kustomization.yaml, apps/admin/reply-urls-operator/demo/deployment-patch.yaml, apps/admin/reply-urls-operator/demo/reply-url-sync-config.yaml, apps/admin/reply-urls-operator/demo/secret.enc.yaml
Adding flux config for the reply urls operator to demo
```
[ ] Yes
[x] No
```
=> DTSPO-6556 - add config for reply urls operator to demo

apps/vh/booking-queue-subscriber/demo.yaml, apps/vh/booking-queue-subscriber/dev.yaml, apps/vh/booking-queue-subscriber/prod.yaml, apps/vh/booking-queue-subscriber/stg.yaml, apps/vh/booking-queue-subscriber/test.yaml
amend BQS settings.
```
[ ] Yes
[ x ] No
```
=> VIH-9999 - Amend BQS

apps/dts-legacy/lgy-iac-web/lgy-iac-web.yaml
Remove the probe path values and increase the interval for the chart
```
[ ] Yes
[x] No
```
=> Remove the probe path values and increase the interval for the chart

apps/dts-legacy/lgy-iac-web/lgy-iac-web.yaml
Add a bespoke startup probe that doesn't depend on tomcat having started
```
[ ] Yes
[x] No
```
=> Rst 4467 add bespoke startup probe

apps/dts-legacy/lgy-iac-web/lgy-iac-web.yaml
Refactor startup-probe lgy-iac-web
```
[ ] Yes
[x] No
```
=> Refactor startup-probe

apps/dts-legacy/lgy-iac-web/stg.yaml
=> Add staging startup-probe override values

apps/dts-legacy/lgy-iac-web/lgy-iac-web.yaml
Reduce pods to one
```
[ ] Yes
[x] No
```
=> Reduce pods to one

apps/admin/reply-urls-operator/sbox/deployment-patch.yaml
Updating to latest reply urls operator image
```
[ ] Yes
[x] No
```
=> DTSPO-6556 - update reply-urls-operator to latest prod image

apps/pip/publication-services/prod.yaml, apps/pip/publication-services/stg.yaml
https://tools.hmcts.net/jira/browse/PUB-1214
https://tools.hmcts.net/jira/browse/PUB-1215
Add admin sign-in URL for PIP
```
[ ] Yes
[x] No
```
=> PUB-1214 Add environment variable for admin sign-in path

apps/pip/frontend/test.yaml, apps/pip/publication-services/test.yaml
Removing test image to use latest.
```
[ ] Yes
[x] No
```
=> Pip update test env

apps/vh/admin-web/demo.yaml, apps/vh/test-web/demo.yaml, apps/vh/video-web/demo.yaml
VIH-9331
Make VH Demo Public
```
[ ] Yes
[x ] No
```
=> VIH-9331 - Make VH Demo Public

apps/vh/admin-web/admin-web.yaml, apps/vh/admin-web/demo.yaml, apps/vh/test-web/demo.yaml, apps/vh/test-web/test-web.yaml, apps/vh/video-web/demo.yaml, apps/vh/video-web/video-web.yaml
VIH-9331 
VIH-9331 - Demo VH Changes
```
[ ] Yes
[ x ] No
```
=> VIH-9331 - Demo VH Changes

apps/vh/admin-web/admin-web.yaml, apps/vh/admin-web/demo.yaml, apps/vh/test-web/demo.yaml, apps/vh/test-web/test-web.yaml, apps/vh/video-web/demo.yaml, apps/vh/video-web/video-web.yaml
VIH-9331 
VIH-9331 - Revert Changes in Dev, Test, Staging
```
[ ] Yes
[ x ] No
```
=> VIH-9331 - Revert Changes in Dev, Test, Staging

apps/pip/frontend/stg.yaml, apps/pip/publication-services/stg.yaml
https://tools.hmcts.net/jira/browse/PUB-1486
Updated vars for staging PIP.
```
[ ] Yes
[x] No
```
=> PUB-1486 Update staging vars

apps/vh/demo/base/azure-identity-patch.yaml, apps/vh/dev/base/azure-identity-patch.yaml, apps/vh/identity/demo.yaml, apps/vh/identity/dev.yaml, apps/vh/identity/prod.yaml, apps/vh/identity/stg.yaml, apps/vh/identity/test.yaml, apps/vh/identity/vh-aad-identity.yaml, apps/vh/prod/base/azure-identity-patch.yaml, apps/vh/stg/base/azure-identity-patch.yaml, apps/vh/test/base/azure-identity-patch.yaml
VIH-9338
VIH-9338 - add storage MI for Wowza
```
[ ] Yes
[ x ] No
```
=> VIH-9338 - add storage MI for Wowza

apps/juror-digital/jd-bureau/prod.yaml, apps/juror-digital/jd-public/prod.yaml
=> Updated LIVE to 2.30

apps/met/themis-fe/themis-fe.yaml
=> fix: updated national met schema ingress hostname

apps/vh/identity/demo.yaml, apps/vh/identity/dev.yaml, apps/vh/identity/prod.yaml, apps/vh/identity/stg.yaml, apps/vh/identity/test.yaml, apps/vh/identity/vh-aad-identity.yaml
update to generic MI in VH.
```
[ ] Yes
[ x ] No
```
=> VIH-9999 - update MI's in VH

apps/admin/reply-urls-operator/demo/deployment-patch.yaml
updating to latest image
```
[ ] Yes
[x] No
```
=> Update Reply URLs Operator to latest image

apps/my-time/base/kustomization.yaml, apps/my-time/demo/base/kustomization.yaml, apps/my-time/identity/demo.yaml, apps/my-time/identity/ithc.yaml, apps/my-time/identity/stg.yaml, apps/my-time/identity/test.yaml, apps/my-time/ithc/base/kustomization.yaml, apps/my-time/preview/base/kustomization.yaml, apps/my-time/stg/base/kustomization.yaml, bin/v2/add-namespace.sh, clusters/demo/base/kustomization.yaml, clusters/stg/base/kustomization.yaml
=> adding my-time to envs

.github/workflows/updatecli.yaml, updatecli/values.github-action.yaml, updatecli/weekly.d/jenkins-packer.yaml
https://tools.hmcts.net/jira/browse/DTSPO-9917
Use updatecli to automatically update the latest image definition for packer-jenkins image. 
```
[ ] Yes
[x] No
```
=> DTSPO-9917 Updatecli

.github/workflows/updatecli.yaml
https://tools.hmcts.net/jira/browse/DTSPO-9917
Use updatecli to automatically update the latest image definition for packer-jenkins image. 
```
[ ] Yes
[x] No
```
=> Enable updatecli on pull_request trigger

apps/pip/publication-services/prod.yaml, apps/pip/publication-services/stg.yaml
https://tools.hmcts.net/jira/browse/PUB-1571
Update env vars for pip publication services
```
[ ] Yes
[x] No
```
=> PUB-1571 update env vars PIP

apps/mi/mi-azure-functions/image-policy.yaml, apps/mi/mi-azure-functions/prod.yaml
Tags were not bing updated as expected. Made the regex filters more simple to see if it fixes the issue.
=> Added updated imagepolicy filter for MI

apps/vh/admin-web/stg.yaml, apps/vh/test-web/stg.yaml, apps/vh/video-web/stg.yaml
Amend staging ingress for VH Apps
```
[ ] Yes
[ x ] No
```
=> VIH-9999 - Amend staging ingress for VH Apps

apps/pip/frontend/test.yaml
https://tools.hmcts.net/jira/browse/PUB-942
Updated image in test
```
[ ] Yes
[x] No
```
=> Updated image in test for pip

apps/pip/frontend/test.yaml
N/A
Updated image for test
```
[ ] Yes
[x] No
```
=> Pub 942 update test image

apps/met/test/base/kustomization.yaml, apps/met/themis-fe/test.yaml
=> fix: added test kv name to test patch

apps/met/test/base/kustomization.yaml, apps/met/themis-fe/themis-fe.yaml
https://tools.hmcts.net/jira/browse/DTSPO-10602
```
[ ] Yes
[x] No
```
=> fix: added missing podLabels

apps/met/test/base/kustomization.yaml, apps/met/themis-fe/test.yaml
=> fix: attempting a different patch for libragob kv

apps/met/themis-fe/test.yaml
=> fix: moved secrets from helm values to env specific patch

apps/pip/frontend/test.yaml
https://tools.hmcts.net/jira/browse/PUB-942
Update PIP Frontend
```
[ ] Yes
[x] No
```
=> PUB-942 - Updated frontend

apps/pip/data-management-no-match-artefacts-cron/pip-data-management-no-match-artefacts-cron.yaml
Updated indentation for file
```
[ ] Yes
[x] No
```
=> Updated the flux yaml for PIP Cron

apps/pip/frontend/test.yaml
https://tools.hmcts.net/jira/browse/PUB-942
Updated image
```
[ ] Yes
[x] No
```
=> PUB-942 - Updated image

apps/pip/data-management-no-match-artefacts-cron/pip-data-management-no-match-artefacts-cron.yaml, apps/pip/data-management-no-match-artefacts-cron/test/00.yaml, apps/pip/data-management-no-match-artefacts-cron/test/01.yaml
Updated schedule to every 10 mins for testing
```
[ ] Yes
[x] No
```
=> Pub 1591 Updated timer

apps/pip/data-management-no-match-artefacts-cron/pip-data-management-no-match-artefacts-cron.yaml, apps/pip/data-management-no-match-artefacts-cron/test/00.yaml, apps/pip/data-management-no-match-artefacts-cron/test/01.yaml, apps/pip/frontend/test.yaml
Updated images for cron and reverted test
```
[ ] Yes
[x] No
```
=> PUB-1591 - Updated dockerfile

apps/pip/data-management-no-match-artefacts-cron/pip-data-management-no-match-artefacts-cron.yaml, apps/pip/data-management-no-match-artefacts-cron/test/00.yaml, apps/pip/data-management-no-match-artefacts-cron/test/01.yaml, apps/pip/frontend/test.yaml
Updated dockerfile
```
[ ] Yes
[x] No
```
=> Pub 1591 updated dockerfile

apps/vh/scheduler-jobs/dev.yaml, apps/vh/scheduler-jobs/image-repo.yaml, apps/vh/scheduler-jobs/prod.yaml, apps/vh/scheduler-jobs/scheduler-jobs.yaml, apps/vh/scheduler-jobs/stg.yaml, apps/vh/scheduler-jobs/test.yaml
VIH-9351 
VIH-9351 - Roll out flux changes for vh scheduler jobs
```
[ ] Yes
[ x ] No
```
=> VIH-9351 - Roll out flux changes for vh scheduler jobs

apps/vh/base/kustomization.yaml, apps/vh/scheduler-jobs/dev.yaml, apps/vh/scheduler-jobs/scheduler-jobs.yaml
VIH-9999
remove scheduler jobs temporarily
```
[ ] Yes
[x ] No
```
=> VIH-9999 - remove scheduler jobs temporarily

.github/workflows/updatecli.yaml, updatecli/values.github-action.yaml
https://tools.hmcts.net/jira/browse/DTSPO-9917
Use hmcts-dependency-updater app token for updatecli
```
[ ] Yes
[X] No
```
=> DTSPO-9917 - Use hmcts-dependency-updater app token for updatecli

apps/pip/account-management-inactive-verification-cron/pip-account-management-inactive-verification-cron.yaml, apps/pip/account-management-media-reporting-cron/pip-account-management-media-reporting-cron.yaml, apps/pip/data-management-expired-artefacts-cron/pip-data-management-expired-artefacts-cron.yaml, apps/pip/data-management-no-match-artefacts-cron/pip-data-management-no-match-artefacts-cron.yaml, apps/pip/data-management-subscriptions-cron/pip-data-management-subscriptions-cron.yaml
Updated image + policy
```
[ ] Yes
[x] No
```
=> PUB-1591 - Updated image + policy

apps/mi/mi-azure-functions/prod.yaml
=> Increased MI Azure Functions Prod pod count from 2 to 4

apps/juror-digital/jd-bureau/jd-bureau.yaml, apps/juror-digital/jd-public/jd-public.yaml
=> Release 3.1

apps/pip/prod/00/kustomization.yaml, apps/pip/prod/01/kustomization.yaml, apps/pip/prod/base/kustomization.yaml
Deployment of CRON timers to prod for PIP
```
[ ] Yes
[x] No
```
=> PUB-1591 - Deploy cron timers to prod

apps/jenkins/jenkins/ptlsbox/jenkins.yaml
=> patch sandbox jenkins

apps/jenkins/jenkins/ptlsbox/jenkins.yaml
Reverts hmcts/sds-flux-config#2313
=> Revert "patch sandbox jenkins"

apps/pip/account-management/test.yaml, apps/pip/data-management/test.yaml, apps/pip/publication-services-mi-reporting-cron/pip-publication-services-mi-reporting-cron.yaml, apps/pip/publication-services-mi-reporting-cron/test/00.yaml, apps/pip/publication-services-mi-reporting-cron/test/01.yaml, apps/pip/publication-services/test.yaml, apps/pip/subscription-management/test.yaml
MI data reporting cron testing
```
[ ] Yes
[x] No
```
=> PUB-1551 MI data reporting cron testing

apps/vh/admin-web/prod.yaml, apps/vh/video-web/prod.yaml
https://tools.hmcts.net/jira/browse/VIH-9445
Change Admin web and video web ingress hosts urls for sds versions
```
[ ] Yes
[X ] No
```
=> VIH-9445-change admin and video web urls for SDS

apps/pip/publication-services-mi-reporting-cron/test/00.yaml, apps/pip/publication-services-mi-reporting-cron/test/01.yaml, apps/pip/publication-services/test.yaml
[Add key vaults to test MI report](https://tools.hmcts.net/jira/browse/PUB-1551)
Add key vaults to test MI report
```
[ ] Yes
[x] No
```
=> PUB-1551 Add key vaults to test MI report

apps/pip/account-management/test.yaml, apps/pip/data-management/test.yaml, apps/pip/publication-services-mi-reporting-cron/test/00.yaml, apps/pip/publication-services-mi-reporting-cron/test/01.yaml, apps/pip/publication-services/test.yaml, apps/pip/subscription-management/test.yaml
https://tools.hmcts.net/jira/browse/PUB-1551
Revert testing changes for MI data reporting
```
[ ] Yes
[x] No
```
=> PUB-1551 Revert testing changes for MI data reporting

apps/jenkins/jenkins/ptlsbox/jenkins.yaml
=> Upgrade Sandbox Jenkins

apps/pip/demo/00/kustomization.yaml, apps/pip/demo/01/kustomization.yaml, apps/pip/demo/base/kustomization.yaml, apps/pip/prod/00/kustomization.yaml, apps/pip/prod/01/kustomization.yaml, apps/pip/prod/base/kustomization.yaml, apps/pip/stg/00/kustomization.yaml, apps/pip/stg/01/kustomization.yaml, apps/pip/stg/base/kustomization.yaml
https://tools.hmcts.net/jira/browse/PUB-1551
Add cron job kustomization for demo, stg and prod
```
[ ] Yes
[x] No
```
=> PUB-1551 Add cron job kustomization for demo, stg and prod

apps/pip/account-management-inactive-verification-cron/pip-account-management-inactive-verification-cron.yaml, apps/pip/account-management-media-reporting-cron/pip-account-management-media-reporting-cron.yaml, apps/pip/data-management-expired-artefacts-cron/pip-data-management-expired-artefacts-cron.yaml, apps/pip/data-management-no-match-artefacts-cron/pip-data-management-no-match-artefacts-cron.yaml, apps/pip/data-management-subscriptions-cron/pip-data-management-subscriptions-cron.yaml, apps/pip/publication-services-mi-reporting-cron/pip-publication-services-mi-reporting-cron.yaml
https://tools.hmcts.net/jira/browse/PUB-1551
Update cron job images after merging to master
```
[ ] Yes
[ ] No
```
=> PUB-1551 Update cron job images

apps/pip/automation/kustomization.yaml
N/A
Add image automation for PIP cron
```
[ ] Yes
[x] No
```
=> Add image automation for PIP cron

apps/admin/oauth2-proxy/oauth2-proxy.yaml
See:
- https://github.com/hmcts/cnp-flux-config/pull/18933
- https://github.com/hmcts/cnp-flux-config/pull/18935
=> Port changes from CFT to SDS for oauth-proxy

apps/vh/video-api/prod.yaml, apps/vh/video-api/stg.yaml
N?A
updates to vh video api stg values
```
[ ] Yes
[ X] No
```
=> Vih 9999 updates to vh video api stg values

apps/juror-digital/jd-bureau/prod.yaml, apps/juror-digital/jd-public/prod.yaml
=> Release 31

apps/vh/admin-web/prod.yaml, apps/vh/admin-web/stg.yaml
VIH-9999 - amend env vars
```
[ ] Yes
[ x ] No
```
=> VIH-9999 - amend env vars

apps/vh/booking-queue-subscriber/prod.yaml, apps/vh/booking-queue-subscriber/stg.yaml, apps/vh/video-api/prod.yaml
Amend URLs
```
[ ] Yes
[x ] No
```
=> VIH-9999 - Amend URLs

apps/admin/oauth2-proxy/oauth2-proxy.yaml
https://github.com/hmcts/cnp-flux-config/pull/19110/files
```
[ ] Yes
[ ] No
```
=> Copying change from CFT

apps/vh/video-web/prod.yaml, apps/vh/video-web/stg.yaml
VIH-9999 - amend URLs for Video Web
VIH-9999 - amend URLs for Video Web
```
[ ] Yes
[ x ] No
```
=> VIH-9999 - amend URLs for Video Web

apps/vh/admin-web/prod.yaml, apps/vh/video-web/prod.yaml
VIH-9999 - Restore Correct Redirect URI's
VIH-9999 - Restore Correct Redirect URI's
```
[ ] Yes
[ x ] No
```
=> VIH-9999 - Restore Correct Redirect URI's

apps/admin/aad-pod-identity/ptlsbox/azure-identity-patch.yaml, apps/azure-devops/azure-devops-agent/ptlsbox.yaml
updating the ptlsbox mi's as they've changed
```
[ ] Yes
[x] No
```
=> Fix mi client id for ptlsbox aks mi

apps/vh/admin-web/prod.yaml, apps/vh/video-web/prod.yaml
Amend URLs for cutover
```
[ ] Yes
[ x ] No
```
=> VIH-9999 - Amend URLs for cutover

apps/vh/booking-queue-subscriber/prod.yaml, apps/vh/video-api/prod.yaml
Update Video Web URL to new production URL
```
[ ] Yes
[ x ] No
```
=> Update VH Video Web URL to new production URL

apps/vh/admin-web/prod.yaml, apps/vh/booking-queue-subscriber/prod.yaml, apps/vh/video-api/prod.yaml, apps/vh/video-web/prod.yaml
VH Rollback
```
[ ] Yes
[ x ] No
```
=> VH Rollback

apps/pip/frontend/demo.yaml, apps/pip/frontend/prod.yaml, apps/pip/frontend/stg.yaml, apps/pip/frontend/test.yaml
https://tools.hmcts.net/jira/browse/PUB-1570
Add channel management url environment variable for front-end
```
[ ] Yes
[x] No
```
=> Add environment variable for front-end

apps/pip/data-management/test.yaml
Revert PR image used for testing App Insights log
```
[ ] Yes
[x] No
```
=> PUB-1598 Revert PR image used for testing App Insights log

apps/pip/data-management/test.yaml
https://tools.hmcts.net/jira/browse/PUB-1598
Testing data-management in app insights
```
[ ] Yes
[ ] No
```
=> PUB-1598 Testing data-management in app insights

apps/pip/data-management/test.yaml
https://tools.hmcts.net/jira/browse/PUB-1598
Revert back test-environment changes
```
[ ] Yes
[x] No
```
=> PUN-1598 Revert back test-environment changes

apps/flux-system/demo/01/kustomize.yaml
Update CLUSTER value to 01 for demo-01
```
[ ] Yes
[X] No
```
=> Update CLUSTER value to 01 for demo-01

apps/vh/video-web/dev.yaml
VIH-9999 - Update dev.yaml
VIH-9999 - Update dev.yaml
```
[ ] Yes
[x  ] No
```
=> VIH-9999 - Update dev.yaml

apps/flux-system/demo/01/kustomize.yaml
https://tools.hmcts.net/jira/browse/DTSPO-11347
updated to env number for demo
```
[ ] Yes
[x] No
```
=> updated demo01 kustomization

apps/pip/frontend/stg.yaml
PUB-942
Enable CFT IDAM in Staging
```
[ ] Yes
[x] No
```
=> Enable CFT IDAM in Staging

apps/pip/frontend/test.yaml
N/A
Enable CFT IDAM in Test
```
[ ] Yes
[x] No
```
=> Added CFT IDAM to test

apps/admin/reply-urls-operator/sbox/kustomization.yaml, apps/toffee/frontend/prod.yaml, apps/toffee/recipe-backend/prod.yaml
=> DTSPO-12023.   Testing updated helm charts

apps/pip/account-management/dev.yaml, apps/pip/channel-management/dev.yaml, apps/pip/data-management/dev.yaml, apps/pip/dev/base/kustomization.yaml, apps/pip/frontend/dev.yaml, apps/pip/publication-services/dev.yaml, apps/pip/subscription-management/dev.yaml
Added back pip dev config and set the replica count to 0 to stop unneeded pods spinning up in dev.
```
[ ] Yes
[x] No
```
=> Added back pip dev config and set replica to 0

apps/vh/video-api/dev.yaml
VIH-9512 - Amend Key Vault Values for Dev Video API
VIH-9512 - Amend Key Vault Values for Dev Video API
```
[ ] Yes
[ x ] No
```
=> VIH-9512 - Amend Key Vault Values for Dev Video API

apps/admin/reply-urls-operator/demo/deployment-patch.yaml
Updating to latest image
```
[ ] Yes
[X] No
```
=> Reply-URLS-Operator - update to latest image

apps/vh/video-api/dev.yaml
VIH-9999 - Amend App Setting
VIH-9999 - Amend App Setting
```
[ ] Yes
[ x ] No
```
=> VIH-9999 - Amend App Setting

apps/admin/external-dns/demo/01-external-dns-private.yaml, apps/admin/external-dns/demo/01-external-dns.yaml, apps/admin/external-dns/external-dns.yaml
Pods in 01 cluster spun up and helm release succeeded, so upgrading in base
```
[ ] Yes
[ ] No
```
=> Upgrade base as 01 was successful

apps/pip/dev/base/kustomization.yaml
=> remove account management release from dev

apps/neuvector/neuvector/test/test.yaml
https://tools.hmcts.net/jira/browse/DTSPO-10284
Bump Neuvector chart version to 1.2.10-alpha for test env
```
[ ] Yes
[x ] No
```
=> Bump neuvector chart 1.2.10-alpha

apps/pip/dev/01/kustomization.yaml, apps/pip/dev/base/kustomization.yaml
Updated config for removing unneeded PIP dev pods.
```
[ ] Yes
[x] No
```
=> Remove dev pods for pip

apps/pip/frontend/test.yaml
N/A
Update Test env for PIP to check Session-cookie
```
[ ] Yes
[x] No
```
=> Updated Test env

apps/pip/dev/base/kustomization.yaml
Added back dev role for PIP that was removed by mistake.
```
[ ] Yes
[x] No
```
=> Added back dev role for PIP

apps/neuvector/neuvector/neuvector.yaml, apps/neuvector/neuvector/test/test.yaml
https://tools.hmcts.net/jira/browse/DTSPO-10284
Update neuvector charts to 1.2.10 for all environments
```
[ ] Yes
[ x] No
```
=> Update Neuvector chart to 1.2.10 for all envs

apps/juror-digital/jd-bureau/jd-bureau.yaml, apps/juror-digital/jd-public/jd-public.yaml
=> Updated NLE to 3.2.96

clusters/test/base/kustomization.yaml
https://tools.hmcts.net/jira/browse/DTSPO-11430
Adding Toffee to test environment
```
[ ] Yes
[x] No
```
=> DTSPO-11430-adding-toffee-to-test-env

apps/admin/external-dns/demo/00-external-dns-private.yaml, apps/admin/external-dns/demo/00-external-dns.yaml, apps/admin/external-dns/demo/01-external-dns-private.yaml, apps/admin/external-dns/demo/01-external-dns.yaml, apps/jenkins/jenkins/ptl/jenkins.yaml
https://tools.hmcts.net/jira/browse/DTSPO-11347
swapped demo active cluster from demo-00 to demo-01
```
[ ] Yes
[x] No
```
=> swapped demo active cluster to 01

apps/toffee/frontend/demo.yaml
=> Revert back to original

apps/admin/external-dns/demo/01-external-dns-private.yaml
Reverts hmcts/sds-flux-config#2420
=> Revert "Update 01-external-dns-private.yaml"

renovate.json
=> Add flux Renovate

apps/toffee/frontend/test.yaml, apps/toffee/identity/test.yaml, apps/toffee/recipe-backend/test.yaml, apps/toffee/recipe-receiver/test.yaml, apps/toffee/test/base/azure-identity-patch.yaml, apps/toffee/test/base/kustomization.yaml
https://tools.hmcts.net/jira/browse/DTSPO-11424
Adding Toffee to the test cluster.
```
[ ] Yes
[x] No
```
=> DTSPO-11424 adding files and folders needed for toffee on test cluster

apps/mi/mi-azure-functions/image-policy.yaml, apps/mi/mi-azure-functions/test.yaml
=> Update test image policy

apps/toffee/frontend/demo.yaml
Test toffee without oauth2-proxy for troubleshooting
```
[ ] Yes
[x] No
```
=> Toffee with traefik-no-proxy

apps/toffee/frontend/demo.yaml
Disable oauth on toffee
Troubleshooting issues with oauth-proxy
```
[ ] Yes
[x] No
```
=> Toffee - disable oauth

apps/toffee/frontend/demo.yaml
Re-enable oauth on toffee in demo
```
[ ] Yes
[x] No
```
=> Toffee - enable oauth in demo

apps/vh/admin-web/demo.yaml, apps/vh/booking-queue-subscriber/demo.yaml, apps/vh/bookings-api/demo.yaml, apps/vh/demo/base/kustomization.yaml, apps/vh/identity/demo.yaml, apps/vh/notification-api/demo.yaml, apps/vh/scheduler-jobs/demo.yaml, apps/vh/test-api/demo.yaml, apps/vh/test-web/demo.yaml, apps/vh/user-api/demo.yaml, apps/vh/video-api/demo.yaml, apps/vh/video-web/demo.yaml, apps/vh/video-web/dev.yaml, clusters/demo/base/kustomization.yaml
https://tools.hmcts.net/jira/browse/VIH-9642
Add flux configuration for VH Demo environment
```
[ ] Yes
[  X ] No
```
=> Vih 9642 add demo environment

apps/pip/frontend/stg.yaml
Testing with PR
```
[ ] Yes
[x] No
```
=> Testing with PR pod

apps/admin/aad-pod-identity/test/ds-patch.yaml, apps/admin/test/base/kustomization.yaml
seeing if this resolves the issues when restarting clusters
```
[ ] Yes
[x] No
```
=> testing preemptionPolicy: Never to see if it fixes nmi issues

apps/admin/aad-pod-identity/test/ds-patch.yaml, apps/admin/test/base/kustomization.yaml
Setting priority class to pod identity in sbox
=> Set higher priority for pod identity pods in sbox

apps/admin/aad-pod-identity/sbox/ds-patch.yaml, apps/admin/sbox/base/kustomization.yaml
Give higher priority to nmi daemonset in sbox to resolve issues when starting up
```
[ ] Yes
[x] No
```
=> Give higher priority to nmi daemonset - sbox

apps/pip/frontend/stg.yaml
Revert image change
```
[ ] Yes
[x] No
```
=> Reverted image change

apps/monitoring/kube-prometheus-stack/kube-prometheus-stack.yaml
=> Remove old flux monitors

apps/pip/frontend/stg.yaml
Updated logging in staging
```
[ ] Yes
[x] No
```
=> Updated logging

apps/pip/frontend/stg.yaml
Updates to change to redirect
```
[ ] Yes
[ ] No
```
=> Further updates

apps/pip/frontend/stg.yaml
Updates to image
```
[ ] Yes
[x] No
```
=> Update pip staging

apps/admin/aad-pod-identity/demo/ds-patch.yaml, apps/admin/demo/base/kustomization.yaml
https://tools.hmcts.net/jira/browse/DTSPO-11430
Prioritise NMI (Demo)
Already implemented in SBOX: https://github.com/hmcts/sds-flux-config/pull/2459
```
[ ] Yes
[X] No
```
=> DTSPO-11430 -  Prioritise NMI

apps/pip/frontend/stg.yaml
Remove staging image
```
[ ] Yes
[x] No
```
=> Removed staging image

apps/jenkins/jenkins/ptl/jenkins.yaml, apps/jenkins/jenkins/ptlsbox/jenkins.yaml
=> remove chart override

apps/monitoring/dev/base/kustomization.yaml, apps/monitoring/flux-monitoring/dashboards/cluster.json, apps/monitoring/flux-monitoring/dashboards/control-plane.json, apps/monitoring/flux-monitoring/dashboards/logs.json, apps/monitoring/flux-monitoring/kustomization.yaml, apps/monitoring/flux-monitoring/podmonitor.yaml
https://tools.hmcts.net/jira/browse/DTSPO-8717
Adding flux monitoring to dev environment for testing
```
[ ] Yes
[X] No
```
=> Adds flux monitoring to dev environment

apps/admin/external-dns/demo/01-external-dns-private.yaml, apps/admin/external-dns/demo/01-external-dns.yaml
=> remove filter now to unblock team

apps/admin/ithc/base/kustomization.yaml, clusters/ithc/base/kustomization.yaml
upgrade traefik to v20.8.0 in ITHC
```
[ ] Yes
[x] No
```
=> DTSPO-12282 - upgrade traefik to v20.8.0 in ITHC

apps/admin/ptlsbox/base/kustomization.yaml, clusters/ptlsbox/base/kustomization.yaml
upgrade traefik to v20.8.0 in ptlsbox
```
[ ] Yes
[x] No
```
=> DTSPO-12282 - upgrade traefik to v20.8.0 in ptlsbox

apps/admin/aad-pod-identity/ithc/ds-patch.yaml, apps/admin/ithc/base/kustomization.yaml
https://tools.hmcts.net/jira/browse/DTSPO-11430
Add NMI Priority to ITHC Environment
```
[ ] Yes
[X] No
```
=> DTSPO-11430 - Add NMI Priority to ITHC Environment

apps/admin/aad-pod-identity/ptlsbox/ds-patch.yaml, apps/admin/ptlsbox/base/kustomization.yaml
DTSPO-11430
Add NMI Priority to PTLSBOX Environment
```
[ ] Yes
[X] No
```
=> DTSPO-11430 - Add NMI Priority to PTLSBOX Environment

apps/admin/ptlsbox/base/kustomization.yaml
https://tools.hmcts.net/jira/browse/DTSPO-11430
Fix Typo in Directory
```
[ ] Yes
[X] No
```
=> DTSPO-11430 - Fix Typo in Directory

apps/juror-digital/jd-bureau/prod.yaml, apps/juror-digital/jd-public/prod.yaml
Updated version numbers to 3.2.96 for Juror Digital release 3.2
```
[ ] Yes
[x] No
```
=> Updated version numbers

apps/admin/dev/base/kustomization.yaml, clusters/dev/base/kustomization.yaml
upgrade traefik in dev to  v20.8.0
```
[ ] Yes
[x] No
```
=> DTSPO-12282 - upgrade traefik in dev

apps/monitoring/kube-prometheus-stack/kube-prometheus-stack.yaml
https://tools.hmcts.net/jira/browse/DTSPO-8717
Enabling grafana on dev01 to test flux monitoring locally on dev 01
```
[ ] Yes
[X] No
```
=> Enables grafana locally on prom stack on dev01 for testing

clusters/prod/base/kustomization.yaml
=> Upgrade prod dynatrace

apps/monitoring/dev/base/kustomization.yaml, apps/monitoring/flux-monitoring/podmonitor.yaml, apps/monitoring/loki-stack/kustomization.yaml, apps/monitoring/loki-stack/release.yaml, apps/monitoring/loki-stack/repository.yaml
https://tools.hmcts.net/jira/browse/DTSPO-8717
Adds loki stack for flux monitoring logs
```
[ ] Yes
[X] No
```
=> Adds loki stack for flux monitoring logs

apps/pip/frontend/stg.yaml
Update version to test staging
```
[ ] Yes
[x] No
```
=> Updated version to test staging

apps/pip/frontend/stg.yaml
Revert image change
```
[ ] Yes
[x] No
```
=> Reverted image change following testing

apps/admin/demo/base/kustomization.yaml, apps/admin/traefik-auth-proxy/traefik-auth-proxy.yaml, apps/admin/traefik-no-proxy/traefik-no-proxy.yaml, apps/admin/traefik2-private/traefik2-private.yaml, clusters/demo/base/kustomization.yaml
upgrade traefik to v20.8.0 in demo
```
[ ] Yes
[x] No
```
=> DTSPO-12282 - upgrade traefik to v20.8.0 in demo

apps/admin/stg/base/kustomization.yaml, clusters/stg/base/kustomization.yaml
upgrade traefik to v20.8.0 in staging
```
[ ] Yes
[x] No
```
=> DTSPO-12282 - upgrade traefik to v20.8.0 in stg

apps/admin/ptl/base/kustomization.yaml, clusters/ptl/base/kustomization.yaml
upgrade ptl traefik to 20.8.0
```
[ ] Yes
[x] No
```
=> DTSPO-12282 - upgrade ptl traefik to 20.8.0

apps/monitoring/dev/base/kustomization.yaml, apps/monitoring/flux-monitoring/dashboards/logs2.json, apps/monitoring/flux-monitoring/kustomization.yaml, apps/monitoring/flux-monitoring/podmonitor.yaml, apps/monitoring/loki-stack/kustomization.yaml, apps/monitoring/loki-stack/release.yaml, apps/monitoring/loki-stack/repository.yaml
https://tools.hmcts.net/jira/browse/DTSPO-8717
Adding second log dashboard to test
```
[ ] Yes
[X] No
```
=> Dtspo 8717 fluxv2 monitoring 3

apps/monitoring/flux-monitoring/dashboards/logs.json
Update log title and uid
```
[ ] Yes
[X] No
```
=> Update log title and uid

apps/dynatrace/dynakube.yaml
add priority class to dynatrace
```
[ ] Yes
[x] No
```
=> DTSPO-11430 - add priority class to dynatrace

apps/azure-devops/azure-devops-agent/azure-devops-agent.yaml
=> Set replica counnt to 2 to keep ha

apps/admin/traefik-crds/kustomization.yaml, apps/admin/traefik-crds_20.8.0/kustomization.yaml, clusters/demo/base/kustomization.yaml, clusters/dev/base/kustomization.yaml, clusters/ithc/base/kustomization.yaml, clusters/ptlsbox/base/kustomization.yaml, clusters/sbox/base/kustomization.yaml, clusters/stg/base/kustomization.yaml
Reverts hmcts/sds-flux-config#2526
=> Revert "DTSPO-12282 - upgrade traefik crds"

apps/admin/dev/base/kustomization.yaml, apps/admin/ithc/base/kustomization.yaml, apps/admin/ptl/base/kustomization.yaml, apps/admin/ptlsbox/base/kustomization.yaml, apps/admin/sbox/base/kustomization.yaml, apps/admin/stg/base/kustomization.yaml, apps/admin/traefik2/temp_upgrade_20-8-0.yaml, apps/admin/traefik2/traefik2.yaml
Reverts hmcts/sds-flux-config#2524
=> Revert "DTSPO-12282 - upgrade traefik to 20.8.0"

apps/jenkins/identity/ptlsbox.yaml
=> ptlsbox update clientid

apps/admin/kured/kured-helmrepo.yaml, apps/admin/kured/kured.yaml
=> DTSPO-10564 update kured

apps/monitoring/kube-prometheus-stack-crds/kustomization.yaml, apps/monitoring/kube-prometheus-stack/kube-prometheus-stack.yaml
=> DTSPO-10565.  update kube-prometheus-stack

apps/flux-system/demo/base/kustomization.yaml, apps/flux-system/dev/base/kustomization.yaml
upgrade flux to v0.38.3 in demo and dev
```
[ ] Yes
[x] No
```
=> DTSPO-10557 - upgrade flux to v0.38.3 in demo and dev

apps/admin/demo/00/kustomization.yaml, apps/admin/demo/01/kustomization.yaml
=> remove external dns on demo

apps/admin/external-dns/external-dns-private.yaml, apps/admin/external-dns/external-dns.yaml, apps/admin/kured/kured.yaml, apps/admin/oauth2-proxy/oauth2-proxy.yaml, apps/admin/traefik-auth-proxy/traefik-auth-proxy.yaml, apps/admin/traefik-no-proxy/traefik-no-proxy.yaml, apps/admin/traefik2/traefik2.yaml, apps/neuvector/fluentbit-log/fluentbit-log.yaml, k8s/release/admin/kube-slack/kube-slack.yaml, k8s/release/admin/kured/kured.yaml
=> remove old annotations

apps/pip/account-management-clear-audit-cron/demo/00.yaml, apps/pip/account-management-clear-audit-cron/demo/01.yaml, apps/pip/account-management-clear-audit-cron/image-policy.yaml, apps/pip/account-management-clear-audit-cron/image-repo.yaml, apps/pip/account-management-clear-audit-cron/pip-account-management-clear-audit-cron.yaml, apps/pip/account-management-clear-audit-cron/prod/00.yaml, apps/pip/account-management-clear-audit-cron/prod/01.yaml, apps/pip/account-management-clear-audit-cron/stg/00.yaml, apps/pip/account-management-clear-audit-cron/stg/01.yaml, apps/pip/account-management-clear-audit-cron/test/00.yaml, apps/pip/account-management-clear-audit-cron/test/01.yaml, apps/pip/automation/kustomization.yaml, apps/pip/demo/00/kustomization.yaml, apps/pip/demo/01/kustomization.yaml, apps/pip/demo/base/kustomization.yaml, apps/pip/prod/00/kustomization.yaml, apps/pip/prod/01/kustomization.yaml, apps/pip/prod/base/kustomization.yaml, apps/pip/stg/00/kustomization.yaml, apps/pip/stg/01/kustomization.yaml, apps/pip/stg/base/kustomization.yaml, apps/pip/test/00/kustomization.yaml, apps/pip/test/01/kustomization.yaml, apps/pip/test/base/kustomization.yaml
https://tools.hmcts.net/jira/browse/PUB-1669
Created CRON for Clearing audit table once logs reach retention period
```
[ ] Yes
[x] No
```
=> PUB-1669 - Created Cron

apps/admin/external-dns/demo/00-external-dns-private.yaml, apps/admin/external-dns/demo/00-external-dns.yaml, apps/admin/external-dns/demo/01-external-dns-private.yaml, apps/admin/external-dns/demo/01-external-dns.yaml, apps/admin/external-dns/external-dns-private.yaml, apps/admin/external-dns/external-dns.yaml
=> move demo specific external dns config out of base

apps/admin/dev/00/kustomization.yaml, apps/admin/dev/01/kustomization.yaml, apps/admin/dev/base/kustomization.yaml, apps/admin/external-dns/dev/00-external-dns.yaml, apps/admin/external-dns/dev/01-external-dns.yaml
=> Add external dns to dev

apps/mi/mi-adf-shir/mi-adf-shir.yaml, apps/mi/mi-azure-functions/mi-azure-functions.yaml, apps/mi/mi-house-keeping-service/mi-house-keeping-service.yaml
Adding image policy to base apps for mi namespace.
=> Added image to mi base apps

apps/toffee/frontend/demo.yaml
=> Remove oauth flag from demo toffee

apps/toffee/frontend/toffee-frontend.yaml, apps/vh/admin-web/demo.yaml, apps/vh/bookings-api/demo.yaml, apps/vh/notification-api/demo.yaml, apps/vh/test-api/demo.yaml, apps/vh/test-web/demo.yaml, apps/vh/user-api/demo.yaml, apps/vh/video-api/demo.yaml, apps/vh/video-web/demo.yaml
=> Remove demo flag

apps/pip/account-management-clear-audit-cron/image-policy.yaml, apps/pip/account-management-clear-audit-cron/image-repo.yaml
=> fix api version

apps/toffee/frontend/demo.yaml
Testing if ingress-class changes have effect on FD availability
```
[ ] Yes
[ ] No
```
=> Set ingressClass to traefik to test with FD

apps/toffee/frontend/demo.yaml
=> Test FD connectivity with TLS flag

apps/toffee/base/kustomize.yaml, apps/toffee/frontend/sbox.yaml, apps/toffee/sbox/base/toffee-values.enc.yaml
=> testing creating sop on toffee namespace

apps/toffee/recipe-backend/demo.yaml
=> Test flag behaviour for backend application

apps/toffee/frontend/toffee-values.enc.yaml, values.yaml
running through sops documentation. testing creating sops on toffee namespace on sbox cluster
=> Dtspo 12417 testing sops on toffee sbox

Docs/secrets-sops-encryption.md, README.md
https://tools.hmcts.net/jira/browse/DTSPO-12417
Updating Readme for sops instructions
```
[ ] Yes
[x] No
```
=> updating readme

apps/admin/sbox/base/kustomization.yaml
Update aad-pod-identity for sbox via patch (1.8.4 -> 1.8.9)
```
[ ] Yes
[X] No
```
=> DTSPO-10573 - Update aad-pod-identity for sbox via patch (1.8.4 -> 1.8.9)

apps/admin/demo/base/kustomization.yaml
Missed to add this back to base in clean up pr
```
[ ] Yes
[ ] No
```
=> Add secret provider back

apps/mi/mi-house-keeping-service/sbox.yaml
Update job schedule to every 5 minutes temporarily to test errors on sbox
```
[ ] Yes
[x] No
```
=> DTSPO-12090 - mi-house-keeping-service schedule

apps/admin/test/base/kustomization.yaml
Update aad-pod-identity for test via patch (1.8.4 -> 1.8.9)
```
[ ] Yes
[X] No
```
=> DTSPO-10573 - Update aad-pod-identity for test via patch (1.8.4 -> 1.8.9)

apps/mi/mi-house-keeping-service/sbox.yaml
Reverts hmcts/sds-flux-config#2588
=> Revert "DTSPO-12090 - mi-house-keeping-service schedule" (#2590

apps/admin/ithc/base/kustomization.yaml
Update aad-pod-identity for ithc via patch (1.8.4 -> 1.8.9)
```
[ ] Yes
[X] No
```
=> DTSPO-10573 - Update aad-pod-identity for ithc via patch (1.8.4 -> 1.8.9)

apps/flux-system/base/chart-job-gitrepo.yaml, apps/flux-system/base/kustomization.yaml, apps/mi/mi-house-keeping-service/sbox.yaml
Ue chart-job in mi-house-keeping-service-sbox instead of custom chart
```
[ ] Yes
[x] No
```
=> DTSPO-12090 - use chart-job in mi

apps/mi/mi-house-keeping-service/sbox.yaml
Add mi_client_id env var
```
[ ] Yes
[x] No
```
=> DTSPO-12090 - add mi_client_id (#2595

apps/mi/mi-house-keeping-service/sbox.yaml
Add aadIdentityName
```
[ ] Yes
[x] No
```
=> DTSPO-12090 - add aadIdentityName

apps/mi/mi-house-keeping-service/sbox.yaml
Update mi-house-keeping-service job schedule
```
[ ] Yes
[x] No
```
=> DTSPO-12090 - Update job schedule

apps/mi/mi-house-keeping-service/sbox.yaml
Currently kind is set to job but this needs to be cronjob so it recurs
```
[ ] Yes
[x] No
```
=> DTSPO-12090 - Update job to cronjob

apps/admin/demo/base/kustomization.yaml
DTSPO-10573 - Update aad-pod-identity for demo via patch (1.8.4 -> 1.8.9)
```
[ ] Yes
[X] No
```
=> DTSPO-10573 - Update aad-pod-identity for demo via patch (1.8.4 -> 1.8.9)

apps/admin/stg/base/kustomization.yaml
DTSPO-10573 - Update aad-pod-identity for stg via patch (1.8.4 -> 1.8.9)
```
[ ] Yes
[X] No
```
=> DTSPO-10573 - Update aad-pod-identity for stg via patch (1.8.4 -> 1.8.9)

apps/admin/aad-pod-identity/kustomization.yaml, apps/admin/demo/base/kustomization.yaml, apps/admin/ithc/base/kustomization.yaml, apps/admin/sbox/base/kustomization.yaml, apps/admin/stg/base/kustomization.yaml, apps/admin/test/base/kustomization.yaml
Update aad-pod-identity (1.8.4 -> 1.8.9) and cleanup patches
```
[ ] Yes
[X] No
```
=> DTSPO-10573 - Update aad-pod-identity and cleanup patches

apps/mi/mi-azure-functions/test.yaml
=> Fix mi-azure-functions-test

apps/neuvector/neuvector/test/00.yaml, apps/neuvector/neuvector/test/01.yaml, apps/neuvector/neuvector/test/test.yaml
=> DTSPO-8924 Update test.yaml

apps/monitoring/dev/base/kustomization.yaml, apps/monitoring/loki/kustomization.yaml, apps/monitoring/loki/release.yaml, apps/monitoring/promtail/kustomization.yaml, apps/monitoring/promtail/release.yaml, apps/monitoring/promtail/repository.yaml
Adding loki and promtail to dev
```
[ ] Yes
[X] No
```
=> Adds loki and promtail to dev cluster

apps/neuvector/ithc/base/fluentbit-log-patch.yaml, apps/neuvector/ithc/base/kustomization.yaml, apps/neuvector/neuvector/ithc/00.yaml, apps/neuvector/neuvector/ithc/01.yaml
=> DTSPO-8924-Update-neuvector-chart-version-ithc

apps/jenkins/jenkins/ptlsbox/jenkins.yaml
upgrading jenkins to 2.391-328 
```
[ ] Yes
[x] No
```
=> DTSPO-10964 - upgrade to jenkins 2.391-328

apps/jenkins/jenkins/jenkins.yaml
upgrading ptl jenkins to latest version, tested in ptlsbox
```
[ ] Yes
[x] No
```
=> DTSPO-10964 - upgrade ptl jenkins to 2.391-328

apps/monitoring/dev/01/kustomization.yaml, apps/monitoring/loki/dev/01.yaml, apps/monitoring/loki/release.yaml
Disable gateway and canary, add ingress for dev01
```
[ ] Yes
[X] No
```
=> Disable gateway and canary, add ingress for dev01

apps/monitoring/loki/dev/01.yaml
update ingress for loki on dev01
```
[ ] Yes
[x] No
```
=> update ingress for loki on dev01

apps/monitoring/loki/dev/01.yaml
Set ingressClassName to traefik
```
[ ] Yes
[x] No
```
=> Set ingressClassName to traefik

apps/jenkins/jenkins/jenkins.yaml, apps/jenkins/jenkins/ptl/jenkins.yaml, apps/jenkins/jenkins/ptlsbox/jenkins.yaml
=> Add overlay

apps/rbac/temp-cronjob-role.yaml
VIH-9999 - Update temp-cronjob-role.yaml
```
[ ] Yes
[ x ] No
```
=> VIH-9999 - Update temp-cronjob-role.yaml

apps/jenkins/jenkins/ptl/jenkins.yaml
DTSPO-12792
Remove Jenkins setup for ss-stg-01-aks due to rebuild
```
[ ] Yes
[ X] No
```
=> Remove Jenkins setup for ss-stg-01-aks due to rebuild

apps/jenkins/jenkins/ptl/jenkins.yaml, apps/jenkins/jenkins/ptlsbox/jenkins.yaml
=> bump ptl and ptlsbox sku size

.github/renovate.json
=> Update renovate.json to create PR per file changed

apps/vh/scheduler-jobs/prod.yaml, apps/vh/scheduler-jobs/stg.yaml
VIH-9999 - Amend Scheduler Jobs URLS
VIH-9999 - Amend Scheduler Jobs URLS
```
[ ] Yes
[ x ] No
```
=> VIH-9999 - Amend Scheduler Jobs URLS

apps/monitoring/loki/dev/01.yaml
Remove loki from spec.values
```
[ ] Yes
[X] No
```
=> Removes loki from values spec

apps/vh/booking-queue-subscriber/stg.yaml
https://tools.hmcts.net/jira/browse/DTSPO-12091
Update image on stg for booking queue subscriber to test updated image works
Disable flux image automation
```
[ ] Yes
[x] No
```
=> DTSPO-12091 - vh bqs stg image - 2

apps/flux-system/base/booking-queue-subscriber-gitrepo-branch.yaml, apps/flux-system/base/kustomization.yaml, apps/vh/booking-queue-subscriber/stg.yaml
https://tools.hmcts.net/jira/browse/DTSPO-12091
Add chart repo branch to test updates
```
[ ] Yes
[x] No
```
=> DTSPO-12091 - vh bqs stg chart (#2662

apps/azure-devops/azure-devops-agent/azure-devops-agent.yaml, apps/azure-devops/azure-devops-agent/image-repo.yaml
to match this change:
https://github.com/hmcts/azure-devops-agent/pull/27
=> Fix rename agent for azure devops agent

apps/monitoring/loki/release.yaml
Diable loki canary
```
[ ] Yes
[X] No
```
=> Disable loki canary

apps/monitoring/loki/release.yaml
Reverts hmcts/sds-flux-config#2664
=> Revert "Disable loki canary"

apps/monitoring/dev/01/kustomization.yaml, apps/monitoring/loki/release.yaml, apps/monitoring/promtail/dev/01.yaml
Update promtail client url to push logs to
```
[ ] Yes
[X] No
```
=> Update promtail url using patch to dev01

apps/testkube/base/kustomization.yaml, apps/testkube/base/kustomize.yaml, apps/testkube/ptlsbox/00/kustomization.yaml, apps/testkube/ptlsbox/base/kustomization.yaml, apps/testkube/testkube/helmrepo.yaml, apps/testkube/testkube/testkube.yaml, clusters/ptlsbox/base/kustomization.yaml
=> Add testkube application 

apps/vh/dev/base/kustomization.yaml
Allow CronJobs in Dev
```
[ ] Yes
[ x ] No
```
=> VIH-0000 - update Dev VH Kustomization

apps/azure-devops/azure-devops-agent/image-policy.yaml
=> fix ADO image policy

apps/monitoring/loki/dev/01.yaml, apps/monitoring/loki/release.yaml
Enable gateway and ingress on gateway
```
[ ] Yes
[X] No
```
=> Enable gateway and ingress on gateway

apps/monitoring/loki/dev/01.yaml
Adds missing paths value for host ingress on gateway
```
[ ] Yes
[x] No
```
=> Adds missing paths value

apps/monitoring/loki/dev/01.yaml
Adds pathType to gateway ingress required by traefik
```
[ ] Yes
[x] No
```
=> Adds pathType to gateway ingress required by traefik

apps/monitoring/dev/01/kustomization.yaml, apps/monitoring/promtail/dev/01.yaml
Patch promtail client url on dev01
```
[ ] Yes
[x] No
```
=> Patch promtail client url on dev01

apps/mi/mi-adf-shir/prod.yaml
Reverts hmcts/sds-flux-config#2682
=> Revert "Enforce SHIR kube node on prod"

apps/pip/frontend/test.yaml
Reverts hmcts/sds-flux-config#2704
=> Revert "Moved frontend to test build"

apps/netbox/netbox/ptlsbox/netbox.yaml
Reverts hmcts/sds-flux-config#2667
=> Revert "Update Helm release netbox to v5.0.4"

apps/netbox/netbox/ptlsbox/netbox.yaml
Reverts hmcts/sds-flux-config#2740
=> Revert "Revert "Update Helm release netbox to v5.0.4""

apps/netbox/netbox/ptlsbox/netbox.yaml
Reverts hmcts/sds-flux-config#2740
=> Update Helm release netbox to v5.0.4

.github/workflows/test-netbox-app.yaml
=> update the action 

apps/juror-digital/jd-bureau/jd-bureau.yaml, apps/juror-digital/jd-public/jd-public.yaml
=> Updated NLE to 3.3

apps/mailrelay/mailrelay/mailrelay.yaml
Reverts hmcts/sds-flux-config#2762
=> Revert "fix "

apps/mailrelay/mailrelay/prod/00.yaml
Reverts hmcts/sds-flux-config#2767
=> Revert "testing of promethus is issue"

apps/pip/frontend/test.yaml
https://tools.hmcts.net/jira/browse/PUB-1932
turned off httpOnly option in express-session.
```
[ ] Yes
[x] No
```
=> turn off httpOnly cookie - test

apps/vh/dev/base/kustomization.yaml, apps/vh/stg/base/kustomization.yaml, apps/vh/test/base/kustomization.yaml
VIH-9795 - Remove Test Apps
```
[ ] Yes
[ x ] No
```
=> VIH-9795 - Remove Test Apps

apps/darts-modernisation/stg/base/kustomization.yaml, clusters/demo/base/kustomization.yaml, clusters/ithc/base/kustomization.yaml, clusters/prod/base/kustomization.yaml, clusters/sbox/base/kustomization.yaml, clusters/stg/base/kustomization.yaml
https://tools.hmcts.net/jira/browse/DMP-26
adding the staging folder 
```
[ ] Yes
[x] No
```
=> Dmp 26 environment changes

apps/mi/mi-house-keeping-service/stg.yaml
https://tools.hmcts.net/jira/browse/DTSPO-12091
Update mi appId for stg
```
[ ] Yes
[x] No
```
=> DTSPO-12091 - Update stg mi for house-keeping-service

apps/pip/data-management/sbox.yaml, apps/pip/identity/sbox.yaml, apps/pip/sbox/00/kustomization.yaml, apps/pip/sbox/01/kustomization.yaml, apps/pip/sbox/base/azure-identity-patch.yaml, apps/pip/sbox/base/kustomization.yaml
Added pip data man to sbox.
```
[ ] Yes
[x] No
```
=> Added pip data man to sbox

clusters/sbox/base/kustomization.yaml
Added pip to cluster sbox.
```
[ ] Yes
[x] No
```
=> Added pip to cluster sbox

apps/darts-modernisation/base/kustomization.yaml
Missing reference to the darts-api.yaml file in the base/kustomization.yaml file
```
[ ] Yes
[x] No
```
=> adding missing config to kustomziation file

apps/darts-modernisation/base/kustomization.yaml, apps/darts-modernisation/dev/01/kustomization.yaml, apps/darts-modernisation/dev/base/kustomization.yaml
adding in missing folders and kustomization files too the dev folder for pr's 
```
[ ] Yes
[x] No
```
=> Darts modernisation config

apps/vh/admin-web/dev.yaml, apps/vh/admin-web/image-policy.yaml, apps/vh/booking-queue-subscriber/dev.yaml, apps/vh/booking-queue-subscriber/image-policy.yaml, apps/vh/bookings-api/dev.yaml, apps/vh/bookings-api/image-policy.yaml, apps/vh/notification-api/dev.yaml, apps/vh/notification-api/image-policy.yaml, apps/vh/scheduler-jobs/dev.yaml, apps/vh/scheduler-jobs/image-policy.yaml, apps/vh/user-api/dev.yaml, apps/vh/user-api/image-policy.yaml, apps/vh/video-api/dev.yaml, apps/vh/video-api/image-policy.yaml, apps/vh/video-web/dev.yaml, apps/vh/video-web/image-policy.yaml
VIH-9814 - Amend Master Release
VIH-9814 - Amend Master Release
```
[ ] Yes
[  x ] No
```
=> VIH-9814 - Amend Master Release

apps/monitoring/loki/dev/01.yaml, apps/monitoring/loki/release.yaml
Change Ingress from gateway
```
[ ] Yes
[X] No
```
=> Update ingress for testing loki

apps/monitoring/dev/01/kustomization.yaml
Remove ingress changes for dev and promtail for testing
```
[ ] Yes
[x] No
```
=> Remove ingress changes for dev and promtail for testing

apps/monitoring/dev/01/kustomization.yaml, apps/monitoring/loki/release.yaml
Change read replicas to 1
```
[ ] Yes
[X] No
```
=> Dtspo 12412 revert read reps

apps/monitoring/loki/release.yaml
Enable loki gateway
```
[ ] Yes
[X] No
```
=> Enable gateway

apps/monitoring/loki/release.yaml
Strip back values for testing locally on cluster
```
[ ] Yes
[X] No
```
=> Dtspo 12412 enable gateway

apps/monitoring/loki/release.yaml
Reverts hmcts/sds-flux-config#2805
=> Revert "Dtspo 12412 enable gateway"

apps/vh/admin-web/demo.yaml, apps/vh/admin-web/stg.yaml, apps/vh/booking-queue-subscriber/demo.yaml, apps/vh/booking-queue-subscriber/stg.yaml, apps/vh/bookings-api/demo.yaml, apps/vh/bookings-api/stg.yaml, apps/vh/notification-api/demo.yaml, apps/vh/notification-api/stg.yaml, apps/vh/scheduler-jobs/demo.yaml, apps/vh/scheduler-jobs/stg.yaml, apps/vh/user-api/demo.yaml, apps/vh/user-api/stg.yaml, apps/vh/video-api/demo.yaml, apps/vh/video-api/stg.yaml, apps/vh/video-web/demo.yaml, apps/vh/video-web/stg.yaml
VIH-9814 - Amend Charts for Demo, Staging
```
[ ] Yes
[  x ] No
```
=> VIH-9814 - Amend Charts for Demo, Staging

apps/monitoring/dev/base/kustomization.yaml
Reverts hmcts/sds-flux-config#2809
=> Revert "Removing loki and promtail from cluster"

apps/monitoring/dev/01/kustomization.yaml, apps/monitoring/promtail/dev/01.yaml
Doing fresh setup of ingress now that locally working again after fresh install across cluster dev 01
```
[ ] Yes
[X] No
```
=> Fresh setup of ingress and update path in promtail

apps/darts-modernisation/darts-portal/darts-portal.yaml, apps/darts-modernisation/darts-portal/demo.yaml, apps/darts-modernisation/darts-portal/image-policy.yaml, apps/darts-modernisation/darts-portal/image-repo.yaml, apps/darts-modernisation/darts-portal/prod.yaml, apps/darts-modernisation/darts-portal/stg.yaml, apps/darts-modernisation/darts-portal/test.yaml
https://tools.hmcts.net/jira/browse/DMP-37
creating folder for darts-portal frontend application
```
[ ] Yes
[x] No
```
=> Dmp 37 front end config

apps/mailrelay/mailrelay/dev/dev.yaml
=> refactor dev values

apps/darts-modernisation/darts-api/demo.yaml, apps/darts-modernisation/darts-api/prod.yaml, apps/darts-modernisation/darts-api/stg.yaml, apps/darts-modernisation/darts-api/test.yaml
https://tools.hmcts.net/jira/browse/DMP-43
the creation of the environment files for the darts-api
```
[ ] Yes
[x] No
```
=> darts-api environment files

apps/darts-modernisation/darts-api/darts-api.yaml, apps/darts-modernisation/darts-portal/darts-portal.yaml, apps/darts-modernisation/demo/base/kustomization.yaml
https://tools.hmcts.net/jira/browse/DMP-43
running the add-namespace-to-env and the add-helm-release scripts for demo
```
[ ] Yes
[x] No
```
=> running the helm release script and adding an env folder for demo

apps/darts-modernisation/demo/00/kustomization.yaml, apps/darts-modernisation/demo/01/kustomization.yaml
https://tools.hmcts.net/jira/browse/DMP-43
demo kustomization files and 01/00 folders 
```
[ ] Yes
[x] No
```
=> adding the 00 and 01 folders and kustomization files to demo

apps/darts-modernisation/darts-portal/stg.yaml
=> Fixing darts portal staging ingressHost

apps/darts-modernisation/stg/base/kustomization.yaml
=> Darts staging env fix

apps/juror-digital/jd-bureau/prod.yaml, apps/juror-digital/jd-public/prod.yaml
=> Updated LIVE to 3.3

apps/jenkins/jenkins/ptl/jenkins.yaml
add AKS subscription_IDs
```
[ ] Yes
[X] No
```
=> add AKS subscription_IDs

apps/darts-modernisation/darts-api/sbox.yaml, apps/darts-modernisation/darts-gateway/sbox.yaml, apps/darts-modernisation/darts-portal/sbox.yaml, apps/darts-modernisation/sbox/base/kustomization.yaml
https://tools.hmcts.net/jira/browse/DMP-61
adding in the sbox.yaml files and folder for sandbox deployments 
```
[ ] Yes
[x] No
```
=> adding sandbox config for darts modernisation

apps/hmi/hmi-rota-dtu/sbox.yaml
Updated HMI sbox img.
```
[ ] Yes
[x] No
```
=> Updated sbox img

apps/jenkins/jenkins/ptlsbox/jenkins.yaml
[DTSPO-13250](https://tools.hmcts.net/jira/browse/DTSPO-13250)
Replace SBOX subscription name with its ID 
```
[ ] Yes
[ x ] No
```
=> Replace sbox subs name with its ID

apps/jenkins/jenkins/ptlsbox/jenkins.yaml
add sbox subscription ID
```
[ ] Yes
[X] No
```
=> add sbox subscription ID

apps/monitoring/dev/01/kustomization.yaml, apps/monitoring/dev/base/kustomization.yaml
Remove loki and promtail for testing clean install again
```
[ ] Yes
[X] No
```
=> Remove loki and promtail for testing clean install again

apps/monitoring/dev/01/kustomization.yaml, apps/monitoring/dev/base/kustomization.yaml
Reverts hmcts/sds-flux-config#2829
=> Revert "Remove loki and promtail for testing clean install again"

apps/monitoring/loki/release.yaml, apps/monitoring/loki/repository.yaml
Disable gateway on loki and add repo
```
[ ] Yes
[X] No
```
=> Disable gateway on loki and add repo

apps/monitoring/dev/01/kustomization.yaml, apps/monitoring/dev/base/kustomization.yaml
Reverts hmcts/sds-flux-config#2846
=> Revert "Revert "Remove loki and promtail for testing clean install again""

apps/monitoring/dev/01/kustomization.yaml, apps/monitoring/dev/base/kustomization.yaml
Reverts hmcts/sds-flux-config#2848
=> Revert "Revert "Revert "Remove loki and promtail for testing clean install again"""

apps/monitoring/promtail/dev/01.yaml
Update promtail client url to ptl
```
[ ] Yes
[X] No
```
=> Update promtail client url to ptl

apps/monitoring/promtail/dev/01.yaml
Update promtail client loki ingress url
```
[ ] Yes
[X] No
```
=> Update promtail client loki ingress url

apps/hmi/hmi-rota-dtu/sbox.yaml
Updated HMI sbox
```
[ ] Yes
[x] No
```
=> Update hmi sbox

apps/hmi/hmi-rota-dtu/sbox.yaml
Updated HMI sbox img.
```
[ ] Yes
[x] No
```
=> Updated hmi sbox img

apps/hmi/hmi-rota-dtu/test.yaml
Updated HMI test.
```
[ ] Yes
[x] No
```
=> updated hmi test

apps/toffee/recipe-backend/sbox.yaml
=> Testing postgres flexserver access in sbox 

apps/vh/admin-web/stg.yaml
https://tools.hmcts.net/jira/browse/VIH-7741
Add values to stg for DOM1
```
[ ] Yes
[X] No
```
=> VIH-7741 add values to stg for DOM1

apps/hmi/identity/sbox.yaml, apps/hmi/sbox/base/azure-identity-patch.yaml
update sbox.
```
[ ] Yes
[x] No
```
=> Updated hmi sbox

apps/hmi/hmi-rota-dtu/sbox.yaml, apps/hmi/hmi-rota-dtu/test.yaml
updated sbox img and reset test hmi
```
[ ] Yes
[x] No
```
=> updated sbox img and reset test hmi

apps/darts-modernisation/darts-portal/sbox.yaml
=> Adding correct ingressHost for DARTS portal on sandbox env

apps/monitoring/kube-prometheus-stack/test/00.yaml, apps/monitoring/kube-prometheus-stack/test/01.yaml, apps/monitoring/kube-prometheus-stack/test/prometheus-values.enc.yaml, apps/monitoring/test/00/kustomization.yaml, apps/monitoring/test/01/kustomization.yaml, apps/monitoring/test/base/kustomization.yaml, clusters/test/base/kustomization.yaml
Adds prometheus to sds test environment
```
[ ] Yes
[X] No
```
=> Adds prometheus to sds test env

apps/darts-modernisation/darts-api/prod.yaml, apps/darts-modernisation/darts-api/sbox.yaml, apps/darts-modernisation/darts-api/stg.yaml, apps/darts-modernisation/darts-gateway/prod.yaml, apps/darts-modernisation/darts-gateway/sbox.yaml, apps/darts-modernisation/darts-gateway/stg.yaml
- overriding some ingressHost values to correctly match
```
[ ] Yes
[ ] No
```
=> DARTS backend services fix

apps/pip/account-management/stg.yaml
https://tools.hmcts.net/jira/browse/PUB-1830
Up max system admin account limit to 20 on staging
```
[ ] Yes
[x] No
```
=> Up max system admin account limit to 20 on staging

apps/toffee/recipe-backend/sbox.yaml
Reverts hmcts/sds-flux-config#2861
=> Revert "Testing postgres flexserver access in sbox "

apps/vh/scheduler-jobs/prod.yaml
VIH-Cutover - Enable Scheduler Jobs
```
[ ] Yes
[ x ] No
```
=> VIH-Cutover - Enable Scheduler Jobs

apps/vh/admin-web/prod.yaml, apps/vh/booking-queue-subscriber/prod.yaml, apps/vh/video-api/prod.yaml, apps/vh/video-web/prod.yaml
VIH-0000 - Amend Prod URLS for Cutover
```
[ ] Yes
[ x ] No
```
=> VIH-0000 - Amend Prod URLS for Cutover

.yamllint.yaml, apps/admin/aad-pod-identity/aad-pod-id-patch.yaml, apps/admin/external-dns/dev/00-external-dns.yaml, apps/admin/external-dns/dev/01-external-dns.yaml, apps/admin/kured/kured.yaml, apps/admin/traefik2/secret-provider.yaml, apps/azure-devops/automation/kustomization.yaml, apps/cronjob/cronjobtest/cronjobtest.yaml, apps/darts-modernisation/darts-api/prod.yaml, apps/darts-modernisation/darts-gateway/prod.yaml, apps/flux-system/prod/00/kustomize.yaml, apps/flux-system/prod/01/kustomize.yaml, apps/flux-system/ptl/base/kustomization.yaml, apps/flux-system/stg/00/kustomize.yaml, apps/flux-system/stg/01/kustomize.yaml, apps/mailrelay/mailrelay/mailrelay.yaml, apps/mi/identity/mi-azure-functions-identity-binding.yaml, apps/monitoring/kube-prometheus-stack/kube-prometheus-stack.yaml, apps/neuvector/neuvector/prod/prod.yaml, apps/pip/base/kustomization.yaml, apps/pip/frontend/prod.yaml, apps/pip/stg/base/kustomization.yaml, apps/testkube/ptlsbox/base/kustomization.yaml, apps/toffee/automation/kustomization.yaml
Fixes bug noted in: https://trello.com/c/E6s54kks/160-flux-check-var-substitution-failed-for-jenkins-yamltojson-yamltojson-yaml-line-542-found-unknown-escape-character
```
[ ] Yes
[X] No
```
=> Required as caused a bug in some flux. See Trello link attached

.yamllint.yaml, apps/admin/keda/keda.yaml, apps/admin/traefik2/ptl/00-traefik.yaml, apps/admin/traefik2/ptlsbox/00-traefik.yaml, apps/dts-legacy/identity/stg.yaml, apps/jenkins/jenkins/jenkins.yaml
yamllint - Set empty trailing lines to 1
```
[ ] Yes
[X] No
```
=> yamllint - Set empty trailing lines to 1

apps/toffee/recipe-backend/sbox.yaml
Switching toffee to postgres flexible server 
```
[ ] Yes
[x] No
```
=> DTSPO-13244 - switch toffee sbox to postgres flexible server

apps/toffee/recipe-backend/sbox.yaml
Putting config in the right place
```
[ ] Yes
[x] No
```
=> DTSPO-13244 - fix typo

clusters/dev/base/kustomization.yaml, clusters/stg/base/kustomization.yaml
Remove my-time from dev and stg clusters, their are OOM errors on the clusters
```
[ ] Yes
[X] No
```
=> Remove my-time from dev and stg clusters

apps/monitoring/dev/01/kustomization.yaml, apps/monitoring/dev/base/kustomization.yaml
Remove Loki and Promtail from dev, using lots of resources
```
[ ] Yes
[X] No
```
=> Remove Loki and Promtail from dev, using lots of resources

apps/darts-modernisation/dev/base/kustomization.yaml, apps/darts-modernisation/identity/stg.yaml, apps/darts-modernisation/identity/test.yaml, apps/darts-modernisation/stg/base/kustomization.yaml, apps/darts-modernisation/test/base/kustomization.yaml
=> Darts managed identities

apps/mi/base/kustomization.yaml, apps/mi/dev/base/kustomization.yaml, apps/mi/ithc/base/kustomization.yaml, apps/mi/mi-adf-shir-2/dev.yaml, apps/mi/mi-adf-shir-2/ithc.yaml, apps/mi/mi-adf-shir-2/mi-adf-shir.yaml, apps/mi/mi-adf-shir-2/prod.yaml, apps/mi/mi-adf-shir-2/sbox.yaml, apps/mi/mi-adf-shir-2/stg.yaml, apps/mi/mi-adf-shir-2/test.yaml, apps/mi/prod/base/kustomization.yaml, apps/mi/sbox/base/kustomization.yaml, apps/mi/stg/base/kustomization.yaml, apps/mi/test/base/kustomization.yaml
Need a second SHIR as the current one only supports 4 nodes. We need a different set of 4 pods for the second SHIR with differing auth key secret value.
=> added second SHIR for mi

apps/jenkins/jenkins/ptlsbox/jenkins.yaml
DTSPO-13211
updating sds sbox jenkins to latest version
```
[ ] Yes
[ x] No
```
=> DTSPO-13211 - updating sds sbox jenkins to latest version

apps/jenkins/jenkins/jenkins.yaml, apps/jenkins/jenkins/ptl/jenkins.yaml
DTSPO-13211
Jenkins update to latest version
```
[ ] Yes
[ x] No
```
=> DTSPO-13211 - Jenkins update to latest version

apps/monitoring/kube-prometheus-stack/test/00.yaml
Fix ingress for test 00
```
[ ] Yes
[X] No
```
=> Updates ingress for test 00

apps/monitoring/kube-prometheus-stack/stg/00.yaml, apps/monitoring/kube-prometheus-stack/stg/01.yaml, apps/monitoring/kube-prometheus-stack/stg/prometheus-values.enc.yaml, apps/monitoring/stg/00/kustomization.yaml, apps/monitoring/stg/01/kustomization.yaml, apps/monitoring/stg/base/kustomization.yaml
Adds prometheus to stg 
```
[ ] Yes
[X] No
```
=> Dtspo 11262 monitoring stg env

apps/monitoring/ithc/00/kustomization.yaml, apps/monitoring/ithc/01/kustomization.yaml, apps/monitoring/ithc/base/kustomization.yaml, apps/monitoring/kube-prometheus-stack/ithc/00.yaml, apps/monitoring/kube-prometheus-stack/ithc/01.yaml, apps/monitoring/kube-prometheus-stack/ithc/prometheus-values.enc.yaml, clusters/ithc/base/kustomization.yaml
Adds monitoring to ITHC on SDS
```
[ ] Yes
[X] No
```
=> Dtspo 11262 monitoring ithc env

apps/monitoring/kube-prometheus-stack/stg/00.yaml, apps/monitoring/kube-prometheus-stack/stg/01.yaml
Updates ingress for staging
```
[ ] Yes
[X] No
```
=> Updates ingress for staging

apps/monitoring/kube-prometheus-stack/kube-prometheus-stack.yaml
Disable grafana on sds
```
[ ] Yes
[X] No
```
=> Disable grafana on sds

apps/dynatrace/dynakube-cnfs.yaml, apps/dynatrace/dynatrace-crds/kustomization.yaml, apps/dynatrace/dynatrace-operator-cnfs.yaml, apps/dynatrace/stg/01/kustomization.yaml
This change deploys dynatrace Cloud Native Full Stack to staging 01
```
[ ] Yes
[x] No
```
=> DTSPO-13594  - deploy dynatrace cnfs to staging 01

clusters/dev/base/kustomization.yaml, clusters/ithc/base/kustomization.yaml, clusters/test/base/kustomization.yaml
Reverts hmcts/sds-flux-config#2905
=> Revert "Temporary remove monitoring from dev, ithc and test"

apps/vh/scheduler-jobs/prod.yaml
VIH - Enable scheduler jobs
```
[ ] Yes
[X] No
```
=> VIH - Enable scheduler jobs

apps/vh/admin-web/prod.yaml, apps/vh/booking-queue-subscriber/prod.yaml, apps/vh/scheduler-jobs/prod.yaml, apps/vh/video-api/prod.yaml, apps/vh/video-web/prod.yaml
VIH-0000 - Amend Prod URLS for Cutover 
```
[ ] Yes
[x] No
```
=> VIH-0000 - Amend Prod URLS for Cutover 

apps/hmi/hmi-rota-dtu/test.yaml
Update test img for hmi
```
[ ] Yes
[x] No
```
=> Update test img for hmi

apps/hmi/hmi-rota-dtu/test.yaml
update hmi test img.
```
[ ] Yes
[x] No
```
=> Update hmi test img

apps/hmi/hmi-rota-dtu/test.yaml
Updated test HMI
```
[ ] Yes
[x] No
```
=> updated test HMI

apps/hmi/hmi-rota-dtu/test.yaml
Update hmi test image.
```
[ ] Yes
[x] No
```
=> Update test img

.github/renovate.json, apps/jenkins/jenkins/jenkins.yaml, apps/jenkins/jenkins/ptlsbox/jenkins.yaml
see https://github.com/hmcts/.github/pull/20
=> Use shared flux renovate config

apps/hmi/hmi-rota-dtu/test.yaml
reset image for hmi test
```
[ ] Yes
[x] No
```
=> reset image for hmi test

apps/admin/ptlsbox/base/keda-identity.yaml, apps/admin/ptlsbox/base/kustomization.yaml
DTSPO-12577
Added SDS Keda MI to ptlsbox
```
[ ] Yes
[ x ] No
```
=> Dtspo 12577 keda

apps/pip/frontend/test.yaml
https://tools.hmcts.net/jira/browse/PUB-2024
Updated image in test
```
[ ] Yes
[x] No
```
=> PUB-2024 - Updated test image

apps/azure-devops/azure-devops-agent-keda/azure-devops-agent.yaml, apps/azure-devops/azure-devops-agent-keda/ptlsbox.yaml, apps/azure-devops/base/kustomization.yaml, apps/azure-devops/dev/base/kustomization.yaml, apps/azure-devops/ithc/base/kustomization.yaml, apps/azure-devops/prod/base/kustomization.yaml, apps/azure-devops/ptl/base/kustomization.yaml, apps/azure-devops/ptlsbox/base/azure-devops-token.yaml, apps/azure-devops/ptlsbox/base/kustomization.yaml, apps/azure-devops/sbox/base/kustomization.yaml, apps/azure-devops/stg/base/kustomization.yaml, apps/azure-devops/test/base/kustomization.yaml
DTSPO-12577
Added Keda DevOps agent
```
[ ] Yes
[ x ] No
```
=> New Keda DevOps Agent

.github/workflows/tests.yml
=> Fix typo - remove unwanted runs

apps/darts-modernisation/dev/base/kustomization.yaml, apps/hmi/dev/base/kustomization.yaml, apps/juror-digital/dev/base/kustomization.yaml, apps/pip/dev/base/kustomization.yaml, apps/toffee/dev/base/kustomization.yaml
=> Add apps/base to to missing namespaces in dev

apps/monitoring/kube-prometheus-stack/dev/01.yaml
Fixes typo in dev 01 ingess for alertmanger
```
[ ] Yes
[X] No
```
=> Fixes typo in dev 01 ingess for alertmanger

apps/vh/identity/test.yaml, apps/vh/test/base/kustomization.yaml
N/A
Update VH test identity clientID
Add cron rbac role to vh test
```
[ ] Yes
[X ] No
```
=> VIH-0000 Update VH test identity clientID

apps/hmi/hmi-rota-dtu/stg.yaml
Update HMI stg.
```
[ ] Yes
[x] No
```
=> Update hmi stg

apps/jenkins/jenkins/ptlsbox/temporary-ingress.yaml
=> DTSPO-13970.  ADD a new ingress to jenkins for testing

apps/jenkins/jenkins/ptlsbox/temporary-ingress.yaml, apps/jenkins/ptlsbox/00/kustomization.yaml
=> DTSPO-13970. ADD a new ingress to jenkins for testing 

apps/jenkins/jenkins/ptlsbox/temporary-ingress.yaml, apps/jenkins/ptlsbox/00/kustomization.yaml
=> DTSPO-13970. Change the name

apps/jenkins/ptlsbox/00/kustomization.yaml
Reverts hmcts/sds-flux-config#3021
=> Revert "Update kustomization.yaml"

apps/azure-devops/azure-devops-agent-keda/azure-devops-agent.yaml, apps/azure-devops/azure-devops-agent-keda/identity.yaml, apps/azure-devops/azure-devops-agent-keda/prod.yaml, apps/azure-devops/azure-devops-agent-keda/prod/identity.yaml, apps/azure-devops/prod/00/kustomization.yaml
DTSPO-12577
Added AAD Identity to Keda agent 
```
[ ] Yes
[ x ] No
```
=> Add aad identity

apps/met/themis-fe/themis-fe.yaml
Changing version from 1.0.1 to 1.0.2
=> updating themis version

apps/met/themis-fe/themis-fe.yaml
Updating to version 1.0.3 after fixing deployment issue
=> updating to version 1.0.3

apps/dynatrace/dynatrace-operator.yaml
[DTSPO-14073](https://tools.hmcts.net/jira/browse/DTSPO-14073)
```
[ ] Yes
[ ] No
```
=> Re-add windows tolerations dynatrace

apps/mi/mi-adf-shir-2/mi-adf-shir.yaml
=> Update annotations position

apps/mi/mi-adf-shir-2/prod.yaml
=> Add one more annotation

apps/dynatrace/dynakube.yaml
=> Update dynakube.yaml indentation

apps/met/themis-fe/themis-fe.yaml
Updating themis to version 1.0.4 which includes SSL certificates for interaction with VF component
=> Updated to verison 1.0.4

apps/dynatrace/dynakube.yaml
=> Update label selector

apps/dynatrace/dynakube.yaml
=> Update dynakube.yaml values to yes

apps/mi/mi-adf-shir-2/mi-adf-shir.yaml, apps/mi/mi-adf-shir/mi-adf-shir.yaml
=> Update mi shir chart ver

apps/monitoring/kube-prometheus-stack/prod/01.yaml
Testing change to slack alerting message
```
[ ] Yes
[ ] No
```
=> Testing change to slack alerting message

apps/monitoring/kube-prometheus-stack/prod/01.yaml
Reverts hmcts/sds-flux-config#3055
=> Revert "Testing change to slack alerting message"

apps/met/themis-fe/themis-fe.yaml
Adding additional debugging options
=> updating themis to 1.0.7

apps/netbox/netbox/ptlsbox/netbox.yaml, apps/netbox/ptlsbox/netbox-postgresql.enc.yaml, apps/netbox/ptlsbox/netbox-redis.enc.yaml
=> DTSPO-14023 update password for Netbox

apps/aspnet/base/kustomization.yaml, apps/aspnet/base/kustomize.yaml, apps/aspnet/dotnet4.8/dotnet4.8.yaml, apps/aspnet/sbox/base/kustomization.yaml, clusters/sbox/base/kustomization.yaml
=> Adding aspnetapp sbox

apps/aspnet/sbox/base/kustomization.yaml
=> missed to add this in last commit and merge

apps/aspnet/dotnet4.8/dotnet4.8.yaml
=> removed chart reference

apps/aspnet/dotnet4.8/dotnet4.8.yaml
=> updated charts location

apps/aspnet/dotnet4.8/dotnet4.8.yaml
=> testing helm chart location

apps/aspnet/dotnet4.8/dotnet4.8.yaml
=> updated foldername

apps/aspnet/dotnet48/dotnet48.yaml, apps/aspnet/sbox/base/kustomization.yaml
=> updated from 4.8 to 48

apps/aspnet/dotnet48/dotnet48.yaml
=> added node selector

apps/aspnet/dotnet48/dotnet48.yaml
=> added comment

apps/aspnet/dotnet48/dotnet48.yaml
=> dot net app re-added

apps/aspnet/dotnet48/dotnet48.yaml
=> updated again

apps/netbox/netbox/ptlsbox/netbox.yaml
=> Update netbox image version.

apps/met/themis-fe/themis-fe.yaml
=> Updating replicas back to 4

apps/pip/frontend/test.yaml
PUB-2040
Revert old test image
```
[ ] Yes
[x] No
```
=> PUB-2040 - Removed old test image

apps/pip/frontend/test.yaml
https://tools.hmcts.net/jira/browse/PUB-2040
Updated test to try out redis upgrade
```
[ ] Yes
[x] No
```
=> PUB-2040 - Updated test

apps/pip/frontend/test.yaml
https://tools.hmcts.net/jira/browse/PUB-2040
Removed test changes
```
[ ] Yes
[x] No
```
=> PUB-2040 - Removed test changes

apps/netbox/netbox/ptlsbox/netbox.yaml
=> Update netbox chart version

apps/netbox/netbox/ptlsbox/netbox.yaml
=> Update netbox chart

apps/met/themis-fe/themis-fe.yaml
=> Updating to version 1.0.8

apps/pip/frontend/test.yaml
https://tools.hmcts.net/jira/browse/PUB-1953
Updated frontend test image
```
[ ] Yes
[x] No
```
=> PUB-1953 - Updated test yaml

apps/pip/frontend/test.yaml
https://tools.hmcts.net/jira/browse/PUB-1953
Removed test image
```
[ ] Yes
[x] No
```
=> PUB-1953 -Removed Test Image

apps/met/themis-fe/themis-fe.yaml
=> Updating version to 1.0.9

apps/met/themis-fe/themis-fe.yaml
Lowering startup an liveness delay
=> Lowering startup delay

apps/met/themis-fe/themis-fe.yaml
=> Updating version to 1.0.10

apps/netbox/netbox/ptlsbox/netbox.yaml
Update netbox chart to 5.0.7
```
[ ] Yes
[x] No
```
=> DTSPO-14224 - Update netbox chart to 5.0.7

apps/met/themis-fe/test.yaml
Adding spring JSM service bus pricing tier env var
=> Themis-addingJMSTier

clusters/ptlsbox/base/kustomization.yaml
Remove netbox on ptlsbox to allow manual testing
Currently stuck on containerCreating without any errors
```
[ ] Yes
[x] No
```
=> DTSPO-14224 - Remove netbox on ptlsbox

apps/netbox/netbox/ptlsbox/netbox.yaml
Update redis values to use ssl
Update chart
Depends on https://github.com/hmcts/rdo-netbox/pull/24
```
[ ] Yes
[x] No
```
=> DTSPO-14224 - Update netbox ptlsbox values

clusters/ptlsbox/base/kustomization.yaml
Re-add netbox to ptlsbox
```
[ ] Yes
[x] No
```
=> DTSPO-14224 - Re-add netbox to ptlsbox

apps/netbox/netbox/ptlsbox/netbox.yaml
Update to new version of chart
```
[ ] Yes
[x] No
```
=> DTSPO-14224 - Update netbox ptlsbox

apps/pip/frontend/test.yaml
https://tools.hmcts.net/jira/browse/PUB-2040
Remove old test config
```
[ ] Yes
[x] No
```
=> Reverted extra test config
