apps/netbox/netbox/ptlsbox/netbox.yaml
Revert to 5.0.8 for netbox
```
[ ] Yes
[x] No
```
=> DTSPO-14224 - Revert to 5.0.8

apps/monitoring/version-reporter/version-reporter.yaml
https://tools.hmcts.net/jira/browse/DTSPO-14325
Adds image version
```
[ ] Yes
[x] No
```
=> Adds image

apps/monitoring/version-reporter/version-reporter.yaml
https://tools.hmcts.net/jira/browse/DTSPO-14325
Fix cron schedule for testing - missing / also changed to 2 mins
```
[ ] Yes
[ ] No
```
=> Fix cron schedule for testing

apps/monitoring/version-reporter/version-reporter.yaml
https://tools.hmcts.net/jira/browse/DTSPO-14325
Change cron to run at 9am
```
[ ] Yes
[X] No
```
=> Change cron to run at 9am

apps/pip/account-management/test.yaml, apps/pip/channel-management/test.yaml, apps/pip/data-management/test.yaml
https://tools.hmcts.net/jira/browse/PUB-1793
Update test env image and add env to test MI blob access
```
[ ] Yes
[x] No
```
=> PUB-1793 Update test env image and add env to test MI blob access

apps/pip/account-management/test.yaml, apps/pip/channel-management/test.yaml, apps/pip/data-management/test.yaml
https://tools.hmcts.net/jira/browse/PUB-1793
Add env variables to test MI blob access
```
[ ] Yes
[x] No
```
=> PUB-1793 Add env variables to test MI blob access

apps/pip/account-management/test.yaml, apps/pip/channel-management/test.yaml, apps/pip/data-management/test.yaml
https://tools.hmcts.net/jira/browse/PUB-1793
Removed test settings
```
[ ] Yes
[x] No
```
=> PUB-1793 Removed test settings

apps/dynatrace/dynakube.yaml
Reverts hmcts/sds-flux-config#3063
=> Revert "Remove namespace exclusion"

apps/pip/account-management/stg.yaml, apps/pip/data-management/stg.yaml, apps/pip/subscription-management/stg.yaml
https://tools.hmcts.net/jira/browse/PUB-1995
Add env variable to staging to enable testing support API
```
[ ] Yes
[x] No
```
=> PUB-1995 Add env variable to staging to enable testing support API

apps/jenkins/jenkins/ptl/jenkins.yaml
DTSPO-12896
Change jenkins to use stg 01
```
[ ] Yes
[ x ] No
```
=> change jenkins stg

apps/flux-system/automation/kustomization.yaml, apps/flux-system/base/jenkins-webhook-relay-gitrepo.yaml, apps/flux-system/base/kustomization.yaml, apps/jenkins/automation/kustomization.yaml, apps/jenkins/base/kustomization.yaml, apps/jenkins/jenkins-webhook-relay/image-policy.yaml, apps/jenkins/jenkins-webhook-relay/image-repo.yaml, apps/jenkins/jenkins-webhook-relay/jenkins-webhook-relay.yaml, apps/jenkins/jenkins-webhook-relay/ptl/jenkins-webhook-relay.enc.yaml, apps/jenkins/jenkins-webhook-relay/ptl/jenkins-webhook-relay.yaml, apps/jenkins/jenkins-webhook-relay/ptlsbox/jenkins-webhook-relay.enc.yaml, apps/jenkins/jenkins-webhook-relay/ptlsbox/jenkins-webhook-relay.yaml, apps/jenkins/ptl/base/kustomization.yaml, apps/jenkins/ptlsbox/base/kustomization.yaml
=> Create jenkins webhook app

apps/juror-digital/jd-bureau/jd-bureau.yaml
R3.5 NLE Bureau
```
[ ] Yes
[ ] No
```
=> r3.5 NLE Bureau

apps/juror-digital/jd-public/jd-public.yaml
R3.5 NLE Public release
```
[ ] Yes
[ ] No
```
=> R3.5 NLE Public

apps/jenkins/jenkins-webhook-relay/jenkins-webhook-relay.yaml
=> Update jenkins url

apps/pip/data-management/test.yaml
Update test env image
```
[ ] Yes
[x] No
```
=> PUB-1793 Update test env image

apps/monitoring/dev/base/kustomization.yaml, apps/monitoring/dev/base/version-reporter.enc.yaml, apps/monitoring/version-reporter/version-reporter.yaml
https://tools.hmcts.net/jira/browse/DTSPO-14149 (branch name wrong)
Adds secrets for paloalto version reporter
```
[ ] Yes
[X] No
```
=> Adds secrets for paloalto version reporter

apps/monitoring/dev/base/version-reporter.enc.yaml
=> Update secret for version reporter

apps/monitoring/version-reporter/version-reporter.yaml
=> Change cron to run every hour

apps/monitoring/version-reporter/version-reporter.yaml
Adds new env vars for updated app code
```
[ ] Yes
[X] No
```
=> Adds new env vars

apps/pip/base/kustomization.yaml, apps/pip/frontend/demo.yaml, apps/pip/frontend/ithc.yaml, apps/pip/frontend/prod.yaml, apps/pip/frontend/stg.yaml, apps/pip/frontend/test.yaml, apps/pip/ithc/base/kustomization.yaml, apps/pip/prod/base/kustomization.yaml, apps/pip/stg/base/kustomization.yaml, apps/pip/test/base/kustomization.yaml
DTSPO-12896
Remove pip-frontend from demo
```
[ ] Yes
[ x ] No
```
=> remove pip-frontend

clusters/demo/base/kustomization.yaml
DTSPO-12896
Remove darts namespace from demo clusters
```
[ ] Yes
[ x ] No
```
=> remove darts

apps/monitoring/version-reporter/version-reporter.yaml
Updated job interval. Close of play no need to for more frequent run which was needed to test out.
Would reduce time during testing phase during working hours and while testing things out.
```
[ ] Yes
[ ] No
```
=> DTSPO-7962: Reducing cron run time

apps/hmi/hmi-rota-dtu/stg.yaml
update hmi stg img.
```
[ ] Yes
[x] No
```
=> update hmi stg img

apps/hmi/hmi-rota-dtu/stg.yaml
Update hmi stg img.
```
[ ] Yes
[x] No
```
=> Update hmi stg image

apps/hmi/hmi-rota-dtu/stg.yaml
Update stg image.
```
[ ] Yes
[x] No
```
=> Update hmi stg env vars

apps/met/prod/base/kustomization.yaml, apps/met/themis-fe/prod.yaml, apps/met/themis-fe/themis-fe.yaml
*
Raised for @morgansaycea.
```
[ ] Yes
[X] No
```
=> Themis prod

apps/hmi/hmi-rota-dtu/stg.yaml
Reset image for hmi staging.
```
[ ] Yes
[x] No
```
=> reset stg back to before testing

apps/monitoring/version-reporter/version-reporter.yaml
Setting the Palo Alto report cron job to run once every 2 weeks. As version dont change everyday i feel doing a check every fortnight is sufficient to keep us informed of changes.
```
[ ] Yes
[ ] No
```
=> DTSPO-7962: Updating how frequent the job runs

apps/monitoring/ptl/base/kustomization.yaml, apps/monitoring/version-reporter/hello-world.yaml, apps/monitoring/version-reporter/kustomization.yaml, apps/monitoring/version-reporter/palo-alto.yaml, apps/monitoring/version-reporter/ptl/ptl.yaml, apps/monitoring/version-reporter/ptlsbox/ptlsbox.yaml
Adds new cronjob for hello world testing and rename files
```
[ ] Yes
[X] No
```
=> Adds new cronjob for hello world testing and rename files

apps/pip/frontend/test.yaml
https://tools.hmcts.net/jira/browse/PUB-2075
Updated image in test to try out changes
```
[ ] Yes
[x] No
```
=> PUB-2075 - Tried out test image

apps/pip/frontend/test.yaml
https://tools.hmcts.net/jira/browse/PUB-2075
Removed test image
```
[ ] Yes
[x] No
```
=> PUB-2075 - Remove test image

apps/jenkins/jenkins/ptl/jenkins.yaml
N/A
Remove outdated cluster values in Jenkins
```
[ ] Yes
[ x ] No
```
=> Remove Outdated Cluster values

apps/pip/frontend/test.yaml
https://tools.hmcts.net/jira/browse/PUB-1959
```
[ ] Yes
[x] No
```
=> Pub 1959 update test image

apps/pip/refresh-views-cron/demo/00.yaml, apps/pip/refresh-views-cron/demo/01.yaml, apps/pip/refresh-views-cron/stg/00.yaml, apps/pip/refresh-views-cron/stg/01.yaml, apps/pip/refresh-views-cron/test/00.yaml, apps/pip/refresh-views-cron/test/01.yaml
N/A
Updated cron trigger time
```
[ ] Yes
[x] No
```
=> Updated refresh views cron time

apps/juror-digital/jd-bureau/prod.yaml, apps/juror-digital/jd-public/prod.yaml
Updated the image version number for R3.5 Live.
```
[ ] Yes
[x] No
```
=> R3.5 Updated the image version

apps/monitoring/version-reporter/helm-charts.yaml, apps/monitoring/version-reporter/kustomization.yaml, apps/monitoring/version-reporter/palo-alto.yaml, apps/monitoring/version-reporter/rbac.yaml
https://tools.hmcts.net/jira/browse/DTSPO-14148
Adding configuration for helm chart report.
Schedule would be updated after testing is complete to run fewer times in a week, or nightly
```
[ ] Yes
[ ] No
```
=> DTSPO-14148: Adding configuration for helmchart report

apps/monitoring/version-reporter/rbac.yaml
https://tools.hmcts.net/jira/browse/DTSPO-14148
Error in helm whatup
`Error: list: failed to list: secrets is forbidden: User "system:serviceaccount:monitoring:version-reporter-service-sa" cannot list resource "secrets" in API group "" at the cluster scope`
```
[ ] Yes
[X] No
```
=> Get secrets permission

apps/pip/frontend/test.yaml
https://tools.hmcts.net/jira/browse/PUB-1959
```
[ ] Yes
[x] No
```
=> PUB-1959 - Updated image

apps/monitoring/version-reporter/helm-charts.yaml
https://tools.hmcts.net/jira/browse/DTSPO-14148
Updated report image tag. Some error fixes in new image
```
[ ] Yes
[ ] No
```
=> DTSPO-14148: Updated to a newer image

apps/pip/frontend/test.yaml
https://tools.hmcts.net/jira/browse/PUB-2043
Update frontend image with extra logging for test env
```
[ ] Yes
[x] No
```
=> PUB-2043 Update frontend image for test env

apps/monitoring/version-reporter/helmcharts/helm-charts.yaml, apps/monitoring/version-reporter/paloalto/palo-alto.yaml
Replace / with : - typo in the image path causing failure
```
[ ] Yes
[X] No
```
=> Replace / with :

apps/monitoring/version-reporter/helmcharts/image-repo.yaml, apps/monitoring/version-reporter/paloalto/image-repo.yaml
Repository tag has been updated to follow the same pattern for other images stored in ACR
```
[ ] Yes
[ ] No
```
=> DTSPO-14674: Repository path update

apps/monitoring/version-reporter/helmcharts/helm-charts.yaml, apps/monitoring/version-reporter/paloalto/palo-alto.yaml
Update image path
```
[ ] Yes
[X] No
```
=> Update image path

apps/monitoring/version-reporter/helmcharts/helm-charts.yaml, apps/monitoring/version-reporter/paloalto/palo-alto.yaml
Update image path to remove hmcts
```
[ ] Yes
[X] No
```
=> Update image path to remove hmcts

apps/flux-system/automation/kustomization.yaml
Adds montoring auotomation to flux-system
```
[ ] Yes
[X] No
```
=> Adds montoring auotomation to flux-system

apps/monitoring/version-reporter/helmcharts/image-repo.yaml, apps/monitoring/version-reporter/paloalto/image-repo.yaml
Update repo path
```
[ ] Yes
[ ] No
```
=> Update repo path

apps/monitoring/version-reporter/helmcharts/helm-charts.yaml
Setting the cron job to run once a day just before work starts at 8:45am
```
[ ] Yes
[ ] No
```
=> DTSPO-14674: Update cron job frequency

apps/met/themis-fe/test.yaml
https://tools.hmcts.net/jira/browse/DTSPO-14677
Added updated secret to run test
```
[ ] Yes
[ X] No
```
=> added updated secret

apps/met/themis-fe/test.yaml
Reverts hmcts/sds-flux-config#3254
=> Revert "added updated secret"

apps/monitoring/kube-prometheus-stack-crds/kustomization.yaml, apps/monitoring/kube-prometheus-stack/kube-prometheus-stack.yaml
=> Prometheus patching upgrade to 48.2.2

apps/vh/admin-web/test.yaml, apps/vh/booking-queue-subscriber/test.yaml, apps/vh/bookings-api/test.yaml, apps/vh/notification-api/test.yaml, apps/vh/scheduler-jobs/test.yaml, apps/vh/user-api/test.yaml, apps/vh/video-api/test.yaml, apps/vh/video-web/test.yaml
https://tools.hmcts.net/jira/browse/VIH-10061
VH update to use staging chart for test env
```
[ ] Yes
[X] No
```
=> VIH-10061 VH update to use staging chart for test env

apps/netbox/ptlsbox/netbox-redis.enc.yaml
https:///tools.hmcts.net/jira/browse/DTSPO-14613
Update secret for redis in ptlsbox
```
[ ] Yes
[x] No
```
=> Update ptlsbox netbox redis secret

apps/admin/traefik-crds/kustomization.yaml, apps/admin/traefik2/traefik2.yaml
=> Upgrade traefik to latest version 

apps/pip/frontend/test.yaml
https://tools.hmcts.net/jira/browse/PUB-2108
Testing updated limits
```
[ ] Yes
[x] No
```
=> PUB-2108 - Testing updated requests + limits

apps/pip/frontend/test.yaml
https://tools.hmcts.net/jira/browse/PUB-2108
Removed test config
```
[ ] Yes
[x] No
```
=> PUB-2108 - Removed config

apps/azure-devops/azure-devops-agent-keda/ptlsbox.yaml, apps/azure-devops/ptlsbox/base/azure-devops-token.yaml
=> adding sp token to test on ptlsbox

apps/admin/sbox/base/kustomization.yaml
=> testing aad-pod-id update 1.8.17 on sbox

apps/admin/aad-pod-identity/kustomization.yaml, apps/admin/sbox/base/kustomization.yaml
=> updating aad-pod-id to 1.8.17

apps/jenkins/jenkins/ptlsbox/jenkins-azure-vm-agent.yaml
Test arm64 based jenkins image in ptlsbox
```
[ ] Yes
[x] No
```
=> DTSPO-14034 - Test jenkins arm image

apps/pip/frontend/test.yaml
https://tools.hmcts.net/jira/browse/PUB-2108
Updated memory + cpu limits
```
[ ] Yes
[x] No
```
=> PUB-2108 - Updated requests / limits

apps/jenkins/jenkins/ptlsbox/jenkins-azure-vm-agent.yaml
Add new vm template for arm agent
git diff isn't displaying right, click view file from the elipsis menu
```
[ ] Yes
[x] No
```
=> DTSPO-14034 - Add new agent template

apps/admin/delete-hung-pods/cron.yaml, apps/admin/delete-hung-pods/hung-pod-script.yaml, apps/admin/delete-hung-pods/kustomization.yaml, apps/admin/sbox/base/kustomization.yaml, apps/admin/stg/base/kustomization.yaml
DTSPO-14741
Adding a cronjob to look for pods with a status of "ContainerCreating" and delete that pod.
Temporary solution for [DTSPO-14705](https://hmcts-reform.slack.com/archives/C8SR5CAMU/p1690796363295179)
```
[ ] Yes
[ x] No
```
=> adding cronjob to restart pods stuck in 'ContainerCreating state'

apps/admin/delete-hung-pods/cron.yaml
=> correcting permissions typo

apps/toffee/frontend/sbox.yaml, apps/toffee/recipe-backend/sbox.yaml
Deploy toffee to arm based node in sbox to test it works
```
[ ] Yes
[x] No
```
=> DTSPO-14034 - Deploy toffee to arm node in sbox

apps/admin/delete-hung-pods/cron.yaml
DTSPO-14741
Cron frequency change
```
[ ] Yes
[x ] No
```
=> Dtspo 14741

apps/base/kustomize.yaml
DTSPO-14697
Add global cluster_name variable
```
[ ] Yes
[ x ] No
```
=> add global cluster_name

apps/admin/delete-hung-pods/cron.yaml, apps/admin/demo/base/kustomization.yaml, apps/admin/dev/base/kustomization.yaml, apps/admin/ithc/base/kustomization.yaml, apps/admin/ptl/base/kustomization.yaml, apps/admin/ptlsbox/base/kustomization.yaml, apps/admin/test/base/kustomization.yaml
DTSPO-14741
Adding cron to all env's excluding prod.
```
[ ] Yes
[x ] No
```
=> DTSPO-14741

apps/jenkins/jenkins/ptlsbox/jenkins-azure-vm-agent.yaml
Change indent of anchor
Image gallery version and defintion is being left blank at the moment - possibly due to how the common and customized values are interacting
```
[ ] Yes
[x] No
```
=> DTSPO-14034 - Update sbox jenkins config

apps/jenkins/jenkins/ptlsbox/jenkins-azure-vm-agent.yaml
Accidentally removed anchor in previous commit
Re-adding
```
[ ] Yes
[x] No
```
=> DTSPO-14034 - Add missing anchor to sbox jenkins casc

apps/darts-modernisation/darts-api/prod.yaml, apps/darts-modernisation/darts-api/sbox.yaml, apps/darts-modernisation/darts-api/stg.yaml, apps/darts-modernisation/darts-gateway/prod.yaml, apps/darts-modernisation/darts-gateway/sbox.yaml, apps/darts-modernisation/darts-gateway/stg.yaml
https://tools.hmcts.net/jira/browse/DMP-722
Config for DARTS API and gatewau
```
[ ] Yes
[x] No
```
=> DMP-722 Adding config for darts API and gateway

apps/monitoring/version-reporter/renovate/renovate.yaml
https://tools.hmcts.net/jira/browse/DTSPO-14763
Updates to correct image tag reference to fix container creation errors
```
[ ] Yes
[ ] No
```
=> DTSPO-14763: Update image tag value

apps/monitoring/ptl/base/kustomization.yaml, apps/monitoring/ptlsbox/base/kustomization.yaml, apps/monitoring/version-reporter/kustomization.yaml, apps/monitoring/version-reporter/paloalto/kustomization.yaml, apps/monitoring/version-reporter/renovate/renovate.yaml
N/A
Install only the palo alto version reporter on sbox - currently installing all version reporter app in ptl sbox
```
[ ] Yes
[X] No
```
=> Install only the palo alto version reporter on sbox

apps/monitoring/version-reporter/renovate/renovate.yaml
https://tools.hmcts.net/jira/browse/DTSPO-14763
Updated the frequency or cron job run 
```
[ ] Yes
[ ] No
```
=> DTSPO-14763: Update to image tag and schedule

apps/jenkins/jenkins/ptl/jenkins-azure-vm-agent.yaml
Update vm agents config to use multiple templates
Add arm agents
```
[ ] Yes
[x] No
```
=> DTSPO-14034 - Update vm agent config

apps/monitoring/automation/kustomization.yaml
add version reporter renovate to kustomize for image policy
```
[ ] Yes
[X] No
```
=> add version reporter renovate to kustomize for image policy

CODEOWNERS, apps/met/themis-fe/prod.yaml
=> Updating themis prod to 1.0.11

CODEOWNERS, apps/met/themis-fe/prod.yaml
Reverts hmcts/sds-flux-config#3320
=> Revert "Updating themis prod to 1.0.11"

apps/met/themis-fe/themis-fe.yaml
=> Revert health check update

apps/pip/demo/base/kustomization.yaml, apps/pip/dev/base/kustomization.yaml, apps/pip/ithc/base/kustomization.yaml, apps/pip/prod/base/kustomization.yaml, apps/pip/sbox/base/kustomization.yaml, apps/pip/stg/base/kustomization.yaml, apps/pip/test/base/kustomization.yaml
=> Fix pip namespace references

apps/monitoring/version-reporter/renovate/renovate.yaml
Updating the report schedule to run once every hour so that more recent updates within the working hours can be reflected sooner
```
[ ] Yes
[ ] No
```
=> DTSPO-7962: Update to cron schedule for report

apps/monitoring/version-reporter/renovate/renovate.yaml
https://tools.hmcts.net/jira/browse/DTSPO-10954
Updated schedule, previous schedule was incorrect, this is needed only once every hour
```
[ ] Yes
[ ] No
```
=> Update to cron schedule for report

apps/pip/demo/base/kustomization.yaml
Added back in Data Management to demo environment following removal while the environment was being fixed.
```
[ ] Yes
[x] No
```
=> PUB-1763 - Added back in data management to demo

apps/pip/demo/base/kustomization.yaml
Added back in Frontend into demo due to removal while the environment was being fixed
```
[ ] Yes
[x] No
```
=> PUB-1763 - Added back in frontend yaml

apps/pip/data-management/demo.yaml
Add update flag to fix demo DB
```
[ ] Yes
[x] No
```
=> PUB-1763 - Update demo env

apps/pip/account-management/demo.yaml, apps/pip/data-management/demo.yaml, apps/pip/subscription-management/demo.yaml
Add update flag to fix demo env
```
[ ] Yes
[x] No
```
=> PUB-1763 - Fix demo env

apps/pip/account-management/demo.yaml, apps/pip/subscription-management/demo.yaml
Changed back DB update
```
[ ] Yes
[x] No
```
=> PUB-1763 - Changed back DB update

apps/pip/frontend/demo.yaml
Enabled CFT for Demo
```
[ ] Yes
[x] No
```
=> PUB-1763 - Enabled CFT

apps/azureserviceoperator-system/demo/00/kustomization.yaml, apps/azureserviceoperator-system/demo/01/kustomization.yaml, apps/azureserviceoperator-system/demo/base/aso-controller-settings.yaml, apps/azureserviceoperator-system/demo/base/kustomization.yaml, apps/azureserviceoperator-system/dev/00/kustomization.yaml, apps/azureserviceoperator-system/dev/01/kustomization.yaml, apps/azureserviceoperator-system/dev/base/aso-controller-settings.yaml, apps/azureserviceoperator-system/dev/base/kustomization.yaml, apps/azureserviceoperator-system/ithc/00/kustomization.yaml, apps/azureserviceoperator-system/ithc/01/kustomization.yaml, apps/azureserviceoperator-system/ithc/base/aso-controller-settings.yaml, apps/azureserviceoperator-system/ithc/base/kustomization.yaml, apps/azureserviceoperator-system/test/00/kustomization.yaml, apps/azureserviceoperator-system/test/01/kustomization.yaml, apps/azureserviceoperator-system/test/base/aso-controller-settings.yaml, apps/azureserviceoperator-system/test/base/kustomization.yaml, clusters/demo/base/kustomization.yaml, clusters/dev/base/kustomization.yaml, clusters/ithc/base/kustomization.yaml, clusters/test/base/kustomization.yaml
https://tools.hmcts.net/jira/browse/DTSPO-13635
Added Azure Service Operator in all non-prod environments
```
[ ] Yes
[ X] No
```
=> added aso for non-prod environments

apps/azureserviceoperator-system/prod/00/kustomization.yaml, apps/azureserviceoperator-system/prod/01/kustomization.yaml, apps/azureserviceoperator-system/prod/base/aso-controller-settings.yaml, apps/azureserviceoperator-system/prod/base/kustomization.yaml, apps/azureserviceoperator-system/ptl/00/kustomization.yaml, apps/azureserviceoperator-system/ptl/base/aso-controller-settings.yaml, apps/azureserviceoperator-system/ptl/base/kustomization.yaml, apps/azureserviceoperator-system/ptlsbox/00/kustomization.yaml, apps/azureserviceoperator-system/ptlsbox/base/aso-controller-settings.yaml, apps/azureserviceoperator-system/ptlsbox/base/kustomization.yaml, apps/azureserviceoperator-system/stg/00/kustomization.yaml, apps/azureserviceoperator-system/stg/01/kustomization.yaml, apps/azureserviceoperator-system/stg/base/aso-controller-settings.yaml, apps/azureserviceoperator-system/stg/base/kustomization.yaml, clusters/prod/base/kustomization.yaml, clusters/ptl/base/kustomization.yaml, clusters/ptlsbox/base/kustomization.yaml, clusters/stg/base/kustomization.yaml
https://tools.hmcts.net/jira/browse/DTSPO-13635 
Added ASO base64 variables to all prod environments.
```
[ ] Yes
[ X ] No
```
=> added ASO variables to all prod environments

apps/darts-modernisation/darts-api/darts-api.yaml
https://tools.hmcts.net/jira/browse/DMP-107
Add the function chart to get the Keda scaled job running.
```
[ ] Yes
[x] No
```
=> DMP-107 Adding keda function to darts-api HelmRelease

apps/admin/dev/00/kustomization.yaml, apps/admin/dev/01/kustomization.yaml, apps/admin/dev/base/kustomization.yaml
need to uncomment external dns flux so it fix an issue with terraform. cannot delete record manually 
```
[ ] Yes
[ ] No
```
=> uncomment external dns

apps/admin/dev/00/kustomization.yaml, apps/admin/dev/01/kustomization.yaml, apps/admin/dev/base/kustomization.yaml
revert change to external dns 
```
[ ] Yes
[ ] No
```
=> revert-change-to-external-dns

apps/darts-modernisation/darts-api/stg.yaml
https://tools.hmcts.net/jira/browse/DMP-107
Add to stg release
```
[ ] Yes
[x] No
```
=> DMP-107 Adding darts-api keda for stg

apps/flux-system/sbox/00/kustomize.yaml, apps/flux-system/sbox/01/kustomize.yaml
HAve added incorrect environment name
```
[ ] Yes
[ X] No
```
=> updated WI_ENVIRONMENT value

apps/admin/dev/00/kustomization.yaml, apps/admin/dev/01/kustomization.yaml, apps/admin/dev/base/kustomization.yaml
remove external dns to test video hearing
```
[ ] Yes
[ ] No
```
=> Remove external dns tempoary

apps/azureserviceoperator-system/aso/kustomization.yaml
Currently scheduling on arm but it's not working
```
[ ] Yes
[x] No
```
=> Schedule ASO on amd64 node

apps/admin/dev/00/kustomization.yaml, apps/admin/dev/01/kustomization.yaml, apps/admin/dev/base/kustomization.yaml
revert changes to external dns to test video hearing url on vpn
```
[ ] Yes
[ ] No
```
=> Revert change to external dns

clusters/sbox/base/kustomization.yaml
fix issue of WORKLOAD_IDENTITY_ID and AZURE_CLIENT_ID not being set
```
[ ] Yes
[ x] No
```
=> Sbox - Toffee- Workload Identity Fix

apps/pip/publication-services/test.yaml
https://tools.hmcts.net/jira/browse/PUB-2134
Testing out pip change for base 64 in test
```
[ ] Yes
[x] No
```
=> PUB-2038 - Updated test image

apps/jenkins/jenkins/ptl/jenkins-azure-vm-agent.yaml, apps/jenkins/jenkins/ptlsbox/jenkins-azure-vm-agent.yaml
Update jenkins agent imageVersions
```
[ ] Yes
[x] No
```
=> Update agent image

apps/flux-system/demo/00/kustomize.yaml, apps/flux-system/demo/01/kustomize.yaml, apps/toffee/demo/base/kustomization.yaml, apps/toffee/demo/base/kustomize.yaml, apps/toffee/demo/base/workload-identity.yaml, apps/toffee/frontend/demo.yaml, apps/toffee/recipe-backend/demo.yaml, clusters/demo/base/kustomization.yaml
Added workload identity for DEMO environment for toffee.
```
[ ] Yes
[ X ] No
```
=> added workload identity for demo env

apps/flux-system/dev/00/kustomize.yaml, apps/flux-system/dev/01/kustomize.yaml, apps/flux-system/ithc/00/kustomize.yaml, apps/flux-system/ithc/01/kustomize.yaml, apps/flux-system/test/00/kustomize.yaml, apps/flux-system/test/01/kustomize.yaml, apps/toffee/dev/base/kustomization.yaml, apps/toffee/dev/base/kustomize.yaml, apps/toffee/dev/base/workload-identity.yaml, apps/toffee/frontend/ithc.yaml, apps/toffee/frontend/test.yaml, apps/toffee/frontend/toffee-frontend.yaml, apps/toffee/ithc/base/kustomization.yaml, apps/toffee/ithc/base/kustomize.yaml, apps/toffee/ithc/base/workload-identity.yaml, apps/toffee/recipe-backend/ithc.yaml, apps/toffee/recipe-backend/test.yaml, apps/toffee/recipe-backend/toffee-recipe-backend.yaml, apps/toffee/test/base/kustomization.yaml, apps/toffee/test/base/kustomize.yaml, apps/toffee/test/base/workload-identity.yaml, clusters/dev/base/kustomization.yaml, clusters/ithc/base/kustomization.yaml, clusters/test/base/kustomization.yaml
Added workload identity to test, ithc and dev environments.
```
[ ] Yes
[ X] No
```
=> added workload identity for all lower envs

apps/toffee/dev/base/kustomize.yaml, apps/toffee/ithc/base/kustomize.yaml, apps/toffee/test/base/kustomize.yaml, clusters/dev/base/kustomization.yaml, clusters/ithc/base/kustomization.yaml, clusters/test/base/kustomization.yaml
Fixed path issue from previous PR and merge
```
[ ] Yes
[ X] No
```
=> fixed path issues

apps/netbox/ptlsbox/netbox-redis.enc.yaml
Update secret to remove new line character
```
[ ] Yes
[x] No
```
=> DTSPO-14224 - Update netbox redis secret ptlsbox

apps/netbox/netbox/ptlsbox/netbox.yaml
Update netbox chart in ptlsbox
```
[ ] Yes
[x] No
```
=> DTSPO-14224 - Update netbox to 5.1.1

apps/met/themis-fe/test.yaml
Updating themis/met to version 1.0.12
```
[ ] Yes
[ ] No
```
=> Updating themis to 1.0.12

apps/flux-system/automation/kustomization.yaml, apps/pre/automation/kustomization.yaml, apps/pre/base/kustomization.yaml, apps/pre/base/kustomize.yaml, apps/pre/identity/pre-azure-identity.yaml.yaml, apps/pre/pre-portal/dev.yaml, apps/pre/pre-portal/image-policy.yaml, apps/pre/pre-portal/image-repo.yaml, apps/pre/pre-portal/pre-portal.yaml
=> Add pre to flux

apps/netbox/netbox/ptlsbox/netbox.yaml
Bump netbox chart
```
[ ] Yes
[x] No
```
=> DTSPO-14224 - Update netbox

apps/netbox/netbox/ptl/netbox.yaml, apps/netbox/ptl/netbox-postgresql.enc.yaml
Upgrade ptl netbox
Update values
Update secret for postgres
```
[ ] Yes
[x] No
```
=> DTSPO-14224 - Upgrade ptl netbox

apps/netbox/netbox/ptl/netbox.yaml
Fix sslMode in ptl postgres config for netbox
```
[ ] Yes
[x] No
```
=> DTSPO-14224 - Fix sslMode in postgres ptl

apps/netbox/ptl/netbox-postgresql.enc.yaml
https://tools.hmcts.net/jira/browse/DSTPO-14224
Fix new line in secret
```
[ ] Yes
[x] No
```
=> DTSPO-14224 - Fix postgres secret ptl

apps/monitoring/version-reporter/docsoutdated/docs-outdated.yaml, apps/monitoring/version-reporter/docsoutdated/image-policy.yaml, apps/monitoring/version-reporter/docsoutdated/image-repo.yaml, apps/monitoring/version-reporter/kustomization.yaml
https://tools.hmcts.net/jira/browse/DTSPO-14815
Adding additional report for up coming demo
```
[ ] Yes
[ ] No
```
=> DTSPO-14815: Adding additional report

apps/admin/keda/sbox/identity.yaml, apps/admin/sbox/base/kustomization.yaml, clusters/sbox/base/kustomization.yaml
=> Move keda sbox to use wi

apps/admin/dev/base/kustomization.yaml, clusters/dev/base/kustomization.yaml
=> Swap dev keda to wi

apps/admin/ithc/base/kustomization.yaml, apps/admin/keda/ithc/identity.yaml, clusters/ithc/base/kustomization.yaml
=> Swapkedaithc

apps/admin/keda/test/identity.yaml, apps/admin/test/base/kustomization.yaml, clusters/test/base/kustomization.yaml
=> move perftest keda to wi

apps/neuvector/neuvector/neuvector.yaml
=> add keda ns to nv whitelist

apps/admin/demo/base/kustomization.yaml, apps/admin/keda/demo/identity.yaml, clusters/demo/base/kustomization.yaml
=> swap keda to wi demo

apps/admin/keda/stg/identity.yaml, apps/admin/stg/base/kustomization.yaml, clusters/stg/base/kustomization.yaml
=> Swap stg keda to wi

apps/pip/data-management/test.yaml, apps/pip/publication-services/test.yaml
https://tools.hmcts.net/jira/browse/PUB-2147
Updated test environment
```
[ ] Yes
[x] No
```
=> PUB-2147 - Updated test env

apps/azure-devops/ptlsbox/base/azure-devops-token.yaml, apps/hmi/hmi-libra-dtu/hmi-libra-dtu.yaml, apps/hmi/hmi-rota-dtu/hmi-rota-dtu.yaml, apps/toffee/recipe-receiver/toffee-recipe-receiver.yaml, apps/vh/booking-queue-subscriber/booking-queue-subscriber.yaml
=> swap to workload identity

apps/darts-modernisation/stg/base/darts-api-function.enc.yaml
https://tools.hmcts.net/jira/browse/DMP-107
```
[ ] Yes
[x] No
```
=> Re-encrypting darts-api-function secret

clusters/sbox/base/kustomization.yaml
N/A
Removing DARTS from sbox env as the Helm releases are failing and blocked an upgrade.
```
[ ] Yes
[x] No
```
=> Removing darts from sbox as it's failing

apps/darts-modernisation/stg/base/kustomization.yaml
Temp fix for DARTS, until I can work out why the secret is not decrypting
```
[ ] Yes
[ ] No
```
=> Temp removal of secret for darts in stg

apps/darts-modernisation/stg/base/darts-api-function.enc.yaml, apps/darts-modernisation/stg/base/kustomization.yaml
=> Regenerate secret

apps/darts-modernisation/automation/kustomization.yaml, apps/darts-modernisation/base/kustomization.yaml, apps/darts-modernisation/darts-stub-services/darts-stub-services.yaml, apps/darts-modernisation/darts-stub-services/demo.yaml, apps/darts-modernisation/darts-stub-services/image-policy.yaml, apps/darts-modernisation/darts-stub-services/image-repo.yaml, apps/darts-modernisation/darts-stub-services/sbox.yaml, apps/darts-modernisation/darts-stub-services/stg.yaml, apps/darts-modernisation/darts-stub-services/test.yaml, apps/darts-modernisation/demo/base/kustomization.yaml, apps/darts-modernisation/sbox/base/kustomization.yaml, apps/darts-modernisation/stg/base/kustomization.yaml, apps/darts-modernisation/test/base/kustomization.yaml
=> Config for darts-stub service

apps/jenkins/jenkins/jenkins.yaml
https://tools.hmcts.net/jira/browse/DSTPO-14754
Add new credential for sds specific github app
```
[ ] Yes
[x] No
```
=> DTSPO-14754 - Jenkins SDS Github

apps/jenkins/jenkins-webhook-relay/ptl/jenkins-webhook-relay.yaml
Reverts hmcts/sds-flux-config#3484
=> Revert "DTSPO-13992 - Update ptl jenkins webhook relay connection url"

apps/azure-devops/ptlsbox/base/azure-devops-token.yaml
=> updating sops version

apps/pip/frontend/test.yaml
https://tools.hmcts.net/jira/browse/PUB-2126
Update frontend image for test env
```
[ ] Yes
[x] No
```
=> PUB-2126 Update frontend image for test env

apps/jenkins/jenkins/ptl/jenkins-azure-vm-agent.yaml, apps/jenkins/jenkins/ptlsbox/jenkins-azure-vm-agent.yaml
Will be needed tomorrow
https://github.com/jenkinsci/azure-vm-agents-plugin/releases/tag/883.v63c930b_025dc
=> Adapt to breaking change in Jenkins config

apps/jenkins/jenkins-webhook-relay/ptlsbox/jenkins-webhook-relay.yaml
Update webhook relay image to pr in ptlsbox to test changes
```
[ ] Yes
[x] No
```
=> DTSPO-14754 - Update jenkins-webhook-relay image ptlsbox

apps/jenkins/jenkins-webhook-relay/ptlsbox/jenkins-webhook-relay.yaml
Remove pr image on ptlsbox webhook
```
[ ] Yes
[x] No
```
=> DTSPO-14754 - Remove PR image on ptlsbox

apps/jenkins/jenkins/jenkins.yaml
Remove github app creds I added during troubleshooting
```
[ ] Yes
[x] No
```
=> DTSPO-14754 - Remove sds gh app

apps/azure-devops/ptlsbox/base/azure-devops-token.yaml, apps/pre/automation/kustomization.yaml, apps/pre/base/kustomization.yaml, apps/pre/demo/base/kustomization.yaml, apps/pre/dev/base/kustomization.yaml, apps/pre/pre-api/demo.yaml, apps/pre/pre-api/dev.yaml, apps/pre/pre-api/image-policy.yaml, apps/pre/pre-api/image-repo.yaml, apps/pre/pre-api/pre-api.yaml, apps/pre/pre-api/prod.yaml, apps/pre/pre-api/sbox.yaml, apps/pre/pre-api/stg.yaml, apps/pre/pre-api/test.yaml, apps/pre/prod/base/kustomization.yaml, apps/pre/sbox/base/kustomization.yaml, apps/pre/stg/base/kustomization.yaml, apps/pre/test/base/kustomization.yaml
=> add pre-api to flux

apps/pip/data-management/test.yaml, apps/pip/frontend/test.yaml
Remove specific data-management and frontend images from test env
```
[ ] Yes
[x] No
```
=> Remove specific data-management and frontend images from test env

apps/pip/frontend/test.yaml
https://tools.hmcts.net/jira/browse/PUB-2068
```
[ ] Yes
[x] No
```
=> PUB-2115 - Updated test image

apps/jenkins/jenkins/ptl/jenkins-azure-vm-agent.yaml
Brings it more in line with cft
```
[ ] Yes
[x] No
```
=> Update ptl arm labels

apps/pip/frontend/stg.yaml
Temp updated image for staging for pip
```
[ ] Yes
[x] No
```
=> PUB-2116 - Updated image

apps/pip/frontend/stg.yaml
Change back staging image
```
[ ] Yes
[x] No
```
=> PUB-2116 - Change back staging

apps/pip/frontend/test.yaml
Missing env var in test
```
[ ] Yes
[x] No
```
=> Update config endpoint for pip

apps/pip/frontend/test.yaml
Removed old image / config from test
```
[ ] Yes
[x] No
```
=> PUB-2115 - Removed old config for pip

apps/pip/frontend/stg.yaml
Updating staging image to test
```
[ ] Yes
[x] No
```
=> PUB-2115 - Updated staging image

apps/pip/frontend/stg.yaml, apps/pip/frontend/test.yaml
Updated test images
```
[ ] Yes
[x] No
```
=> PUB-2115 - Updated staging + test envs

apps/dynatrace/dynakube.yaml
INC5548600
Only difference I've found between this and dev apart from the hostname
=> Exclude dynatrace on mailrelay2

apps/admin/traefik2/traefik2.yaml
https://tools.hmcts.net/jira/browse/DTSPO-15327
Outage today on SDS PTL that was only running one instance, and there was just an issue on one node, this would have prevented it.
Removed the affinity as CFT doesn't use system for this
=> DTSPO-15327 Scale traefik and allow it to schedule on linux node pool too

apps/admin/traefik2/traefik2.yaml
Only 1 pod and no HPA existed...
=> DTSPO-15327 Enable traefik autoscaling

Docs/secrets-sops-encryption.md, apps/azure-devops/azure-devops-agent-keda/test.yaml, apps/azure-devops/azure-devops-agent-keda/test/identity.yaml, apps/azure-devops/azure-devops-agent/test.yaml, apps/azure-devops/test/base/azure-devops-token.yaml, apps/azure-devops/test/base/kustomization.yaml
DTSPO-13981
Add secret and pool details for Perftest agent
=> add secret/pool for Perftest agents

apps/pip/frontend/stg.yaml
Temp deploy to staging to test
=> PUB-2115 - Testing out image

apps/pip/frontend/stg.yaml
=> PUB-2115 - Change image back

apps/darts-modernisation/base/kustomization.yaml, apps/darts-modernisation/base/kustomize.yaml, apps/darts-modernisation/demo/00/kustomization.yaml, apps/darts-modernisation/dev/00/kustomization.yaml, apps/darts-modernisation/sbox/00/kustomization.yaml, apps/darts-modernisation/sbox/01/kustomization.yaml, apps/darts-modernisation/sbox/base/kustomization.yaml, apps/darts-modernisation/stg/00/kustomization.yaml, apps/darts-modernisation/stg/01/kustomization.yaml, apps/darts-modernisation/stg/base/kustomization.yaml, apps/darts-modernisation/test/00/kustomization.yaml, apps/darts-modernisation/test/01/kustomization.yaml, apps/darts-modernisation/test/base/kustomization.yaml
Running the darts-stub on 1 cluster
=> DMP-817: Running the darts-stub on 1 cluster

apps/neuvector/base/kustomize.yaml, apps/neuvector/crds/kustomization.yaml, apps/neuvector/neuvector/neuvector.yaml
Otherwise the helm chart can't use CRDs inside of it as they aren't ready first
=> Move NeuVector CRDs to flux

apps/jenkins/ptl/00/kustomization.yaml
=> DTSPO-14754 - Fix kustomization typo

apps/neuvector/ithc/base/fluentbit-log.enc.yaml
```
flux-system   neuvector        205d    False   decryption failed for 'fluentbit-log': failed to decrypt and format 'neuvector/fluentbit-log' Secret data: error decrypting sops tree: Error walking tree: Could not decrypt value: Input string v1 does not match sops' data format
```
=> Fix neuvector on ITHC

apps/admin/traefik2/ptl/secret-provider.yaml, apps/admin/traefik2/ptlsbox/secret-provider.yaml
Add new wildcard cert to traefik in ptlsbox and ptl
=> DTSPO-14754 - Add new cert to traefik

apps/neuvector/neuvector/prod/prod.yaml
NeuVector have asked if we can try disabling admission control to see if the logs stop
=> Temp disable NeuVector admission control prod

CODEOWNERS
=> Update CODEOWNERS for Juror

apps/azure-devops/azure-devops-agent-keda/ithc.yaml, apps/azure-devops/azure-devops-agent-keda/ptl.yaml
N/A
Remove maxReplicaCount from ITHC config and add it to PTL config.
=> fix: set ado agent max replicas to 6 in PTL

apps/kube-system/base/kustomization.yaml, apps/kube-system/container-azm-ms-agentconfig/container-azm-ms-agentconfig.yaml, apps/kube-system/container-azm-ms-agentconfig/kustomization.yaml
Imported config from CFT and made minor tuning for SDS
https://github.com/hmcts/cnp-flux-config/blob/master/apps/kube-system/container-azm-ms-agentconfig/container-azm-ms-agentconfig.yaml
=> Add configmap for tuning log analytics ingestion

apps/neuvector/ithc/base/nv-storage-secret.yaml
ITHC neuvector is failing to install at all:
```
decryption failed for 'nv-storage-secret': failed to decrypt and format 'neuvector/nv-storage-secret' Secret data: error decrypting sops tree: Error walking tree: Could not decrypt value: Input string v1 does not match sops' data format
```
There was a few differences in ithc vs other envs, so regerated the secret to see if that helps things
=> Update neuvector sops secret

apps/pip/account-management/demo.yaml, apps/pip/channel-management/demo.yaml, apps/pip/data-management/demo.yaml, apps/pip/frontend/demo.yaml, apps/pip/publication-services/demo.yaml, apps/pip/subscription-management/demo.yaml
Remove demo environment pods for migration
=> PUB-2188 - Remove demo environment pods for migration

apps/pip/account-management/demo.yaml, apps/pip/channel-management/demo.yaml, apps/pip/data-management/demo.yaml, apps/pip/frontend/demo.yaml, apps/pip/publication-services/demo.yaml, apps/pip/subscription-management/demo.yaml
Re-enable demo apps and point to flex server
=> PUB-2188 - Re-enabled apps

apps/toffee/dev/base/workload-identity.yaml
DTSPO-15411
Remove outdated WI file
=> remove outdated WI file

apps/darts-modernisation/darts-api/stg.yaml
=> Forcing darts-api restart in stg

apps/azureserviceoperator-system/resources/flexibleserver-postgres-config.yaml, apps/azureserviceoperator-system/resources/flexibleserver-postgres.yaml, apps/azureserviceoperator-system/resources/resource-group.yaml, apps/darts-modernisation/dev/aso/darts-postgres.yaml, apps/darts-modernisation/dev/base/kustomization.yaml, apps/darts-modernisation/dev/sops-secrets/dev-postgres.yaml, apps/darts-modernisation/dev/sops-secrets/kustomization.yaml
https://tools.hmcts.net/jira/browse/DMP-1216
=> DMP-1216 Adding DARTS Dev postgres for PRs

apps/pip/account-management/test.yaml, apps/pip/channel-management/test.yaml, apps/pip/data-management/test.yaml, apps/pip/frontend/test.yaml, apps/pip/publication-services/test.yaml, apps/pip/subscription-management/test.yaml
Switch off test environment for DB Migration
=> PUB-2188 - Switch off Test Env for PIP

apps/toffee/dev/base/azure-identity-patch.yaml, apps/toffee/dev/base/kustomization.yaml, apps/toffee/dev/base/kustomize.yaml, apps/toffee/frontend/toffee-frontend.yaml, apps/toffee/recipe-backend/toffee-recipe-backend.yaml
=> Dtspo 15411 2

apps/pip/account-management/test.yaml, apps/pip/channel-management/test.yaml, apps/pip/data-management/test.yaml, apps/pip/frontend/test.yaml, apps/pip/publication-services/test.yaml, apps/pip/subscription-management/test.yaml
=> PUB-2188 - Re-enabled test

apps/pip/publication-services/test.yaml
Updated pip publication services in test
=> Update pip publication services in test

apps/admin/external-dns/dev/00-external-dns.yaml, apps/admin/external-dns/dev/01-external-dns.yaml, apps/admin/external-dns/external-dns.yaml
Follow on from https://github.com/hmcts/sds-flux-config/pull/3629/files which had errors
Think this was missed which may not help things
=> Remove managedidentityextension

apps/jenkins/base/kustomize.yaml, apps/jenkins/ptlsbox/base/kustomization.yaml
- Only adding resources for now to see if federated credentials work without any issue
=> Add wlidentity for jenkins ptlsbox

apps/darts-modernisation/base/kustomize.yaml, apps/darts-modernisation/dev/base/kustomization.yaml, apps/darts-modernisation/stg/base/kustomization.yaml
=> DARTS nonprod rbac added to dev/stg

apps/jenkins/base/kustomization.yaml, apps/jenkins/ptl/base/kustomization.yaml, apps/jenkins/ptlsbox/base/kustomization.yaml
- Adding them ahead to limit the downtime when swapped to wl identity
=> Add federated creds for prod jenkins

apps/jenkins/jenkins/jenkins.yaml, apps/jenkins/jenkins/ptl/jenkins.yaml, apps/jenkins/jenkins/ptlsbox/jenkins.yaml
=> Add wl identity for prod jenkins

apps/pip/publication-services/test.yaml
updated pub services img in pip test
=> updated pub services img in pip test

apps/mi/base/kustomization.yaml, apps/mi/base/kustomize.yaml, apps/mi/dev/base/kustomization.yaml, apps/mi/ithc/base/kustomization.yaml, apps/mi/sbox/base/kustomization.yaml, apps/mi/serviceaccount/dev.yaml, apps/mi/serviceaccount/test.yaml, apps/mi/test/base/kustomization.yaml
Adding service account to dev and test first for testing
=> Add workload identity for mi on dev and test

apps/pip/account-management/stg.yaml, apps/pip/channel-management/stg.yaml, apps/pip/data-management/stg.yaml, apps/pip/frontend/stg.yaml, apps/pip/publication-services/stg.yaml, apps/pip/subscription-management/stg.yaml
Shutdown staging for PIP for DB migration
=> PUB-2188 - Shutdown staging for PIP

apps/pip/account-management/stg.yaml, apps/pip/channel-management/stg.yaml, apps/pip/data-management/stg.yaml, apps/pip/frontend/stg.yaml, apps/pip/publication-services/stg.yaml, apps/pip/subscription-management/stg.yaml
=> Pub 2188 lower env migration staging

apps/admin/ptl/base/kustomize.yaml, apps/admin/stg/base/kustomize.yaml, apps/admin/traefik2/ptl/00-traefik.yaml, apps/admin/traefik2/ptl/secret-provider.yaml, apps/admin/traefik2/stg/00-traefik2.yaml, apps/admin/traefik2/stg/01-traefik2.yaml, apps/admin/traefik2/stg/secret-provider.yaml, clusters/ptl/base/kustomization.yaml, clusters/stg/base/kustomization.yaml
[DTSPO-12677](https://tools.hmcts.net/jira/browse/DTSPO-12677)
Similar done for nonprod in https://github.com/hmcts/sds-flux-config/pull/3664/files - which are all working
=> Migrate aat&PTL traefik to workload identity

apps/pip/account-management/stg.yaml, apps/pip/channel-management/stg.yaml, apps/pip/data-management/stg.yaml, apps/pip/frontend/stg.yaml, apps/pip/publication-services/stg.yaml, apps/pip/subscription-management/stg.yaml
Migrated to flexible server + remove replica
=> PUB-2188 - Lower env migration staging

apps/admin/prod/base/kustomize.yaml, apps/admin/traefik2/prod/00-traefik2.yaml, apps/admin/traefik2/prod/01-traefik2.yaml, apps/admin/traefik2/prod/secret-provider.yaml, clusters/prod/base/kustomization.yaml
[DTSPO-12677](https://tools.hmcts.net/jira/browse/DTSPO-12677)
Similar done for STG&PTL in https://github.com/hmcts/sds-flux-config/pull/3678 - which are all working
=> Migrate prod traefik to workload identity

apps/pip/account-management/demo.yaml, apps/pip/account-management/stg.yaml, apps/pip/account-management/test.yaml
https://tools.hmcts.net/jira/browse/PUB-2192
Remove AM AAD flag for workload identity
=> PUB-2192 - Updated AM AAD Flag

apps/pip/data-management/demo.yaml, apps/pip/data-management/stg.yaml, apps/pip/data-management/test.yaml
https://tools.hmcts.net/jira/browse/PUB-2192
Removed DM AAD flag for Workload identity
=> PUB-2192 - Updated DM AAD Flag

apps/jenkins/jenkins/ptlsbox/jenkins.yaml
https://tools.hmcts.net/jira/browse/DTSPO-15318
Application [added in config](https://github.com/hmcts/azure-app-proxy/pull/23)
[Similar done in CFT](https://github.com/hmcts/cnp-flux-config/pull/24120/files)
=> DTSPO-15318: Move sbox jenkins to new domain with app proxy

apps/jenkins/jenkins/ptlsbox/jenkins.yaml
https://tools.hmcts.net/jira/browse/DTSPO-15318
Updates to point to new URL
DNS pointing to traefik for this added in https://github.com/hmcts/azure-private-dns/pull/671
=> DTSPO-15318: Update flux for static sds sbox jenkins

apps/jenkins/jenkins/ptl/jenkins.yaml
Reverts hmcts/sds-flux-config#3709
=> Revert "DTSPO-15318: Update sds jenkins ingress URLs and client secret"

apps/juror/dev/aso/juror-postgres.yaml, apps/juror/dev/base/kustomization.yaml, apps/juror/dev/sops-secrets/dev-postgres.yaml, apps/juror/dev/sops-secrets/kustomization.yaml
n/a (on CGI Jira board)
Add Postgress via Azure Service Operator for use on dev PRs
- [] README and other documentation has been updated / added (if needed)
- [] tests have been updated / new tests has been added (if needed)
=> add aso postgres for Juror

apps/jenkins/jenkins/ptl/jenkins.yaml
Reverts hmcts/sds-flux-config#3710 after client secret was added correctly
=> Revert "Revert "DTSPO-15318: Update sds jenkins ingress URLs and client secret""

apps/jenkins/jenkins/ptl/jenkins.yaml
https://tools.hmcts.net/jira/browse/DTSPO-15318
Add config for static ptl jenkins in sds
=> DTSPO-15318: Switch last ingress for static to new one

apps/darts-modernisation/darts-portal/stg.yaml
=> Setting DARTS_ALLOW_AUTH_BOOTSTRAP for darts-portal stg

apps/jenkins/jenkins/ptl/jenkins.yaml, apps/jenkins/jenkins/ptlsbox/jenkins.yaml
CFT Done in https://github.com/hmcts/cnp-flux-config/pull/25849
=> DTSPO-15318: Fix bug where dashboard views are not showing on new url

apps/jenkins/jenkins/ptl/jenkins.yaml, apps/jenkins/jenkins/ptlsbox/jenkins.yaml
Reverts hmcts/sds-flux-config#3734 -- app registration graph permissions were not approved which was the real cause
=> Revert "DTSPO-15318: Fix bug where dashboard views are not showing on new url"

apps/opal/base/kustomization.yaml, apps/opal/base/kustomize.yaml, apps/opal/dev/base/kustomization.yaml, apps/opal/serviceaccount/stg.yaml, apps/opal/stg/base/kustomization.yaml, clusters/dev/base/kustomization.yaml, clusters/stg/base/kustomization.yaml
Creating namespace/config for master/PR builds. Not yet deploying any apps.
=> Initial Opal base

apps/darts-modernisation/darts-portal/stg.yaml
=> DARTS portal - temporarily disable secure cookies on staging env

apps/vh/video-api/dev.yaml
=> add value for vh

apps/pip/account-management-media-reporting-cron/stg/01.yaml, apps/pip/publication-services-mi-reporting-cron/stg/01.yaml
=> PIP - Testing cron changes

apps/pip/account-management-media-reporting-cron/stg/01.yaml, apps/pip/publication-services-mi-reporting-cron/stg/01.yaml
=> Pub 2189 testing schedule

apps/vh/admin-web/test.yaml, apps/vh/booking-queue-subscriber/test.yaml, apps/vh/bookings-api/test.yaml, apps/vh/notification-api/test.yaml, apps/vh/scheduler-jobs/test.yaml, apps/vh/user-api/test.yaml, apps/vh/video-api/test.yaml, apps/vh/video-web/test.yaml
https://tools.hmcts.net/jira/browse/VIH-10259
update test to use dev image
=> VIH-10259 update test to use dev image

apps/netbox/netbox/ptlsbox/traefik-netbox.yaml
https://tools.hmcts.net/jira/browse/DTSPO-15319
* netbox-sandbox ingress host change for app proxy integration
=> Netbox: netbox-sandbox ingress host change for app proxy integration

apps/netbox/netbox/ptlsbox/netbox.yaml
https://tools.hmcts.net/jira/browse/DTSPO-15319
* Change other netbox-sandbox ingress host for app proxy integration
=> Netbox: change other netbox-sandbox ingress host for app proxy integration

apps/pip/account-management-media-reporting-cron/prod/00.yaml, apps/pip/publication-services-mi-reporting-cron/prod/00.yaml
Updated timings cron trigger for prod
=> PUB-2189 - Updated timings

apps/pip/account-management/prod.yaml, apps/pip/channel-management/prod.yaml, apps/pip/data-management/prod.yaml, apps/pip/frontend/prod.yaml, apps/pip/publication-services/prod.yaml, apps/pip/subscription-management/prod.yaml
=> Do not merge - PUB-2189 - Switch off prod pods PIP

apps/pip/account-management/prod.yaml, apps/pip/channel-management/prod.yaml, apps/pip/data-management/prod.yaml, apps/pip/frontend/prod.yaml, apps/pip/publication-services/prod.yaml, apps/pip/subscription-management/prod.yaml
Switch back on PIP application
=> PUB-2189 - Switch back on application

apps/pip/account-management-media-reporting-cron/prod/00.yaml, apps/pip/publication-services-mi-reporting-cron/prod/00.yaml
=> PUB-2189 - Update cron triggers

apps/darts-modernisation/darts-api/stg.yaml
=> Changes to restart DARTS Pods

apps/netbox/netbox/ptl/netbox.yaml, apps/netbox/netbox/ptl/traefik-netbox.yaml
https://tools.hmcts.net/jira/browse/DTSPO-15319
* Change Netbox ingress URLs for compatability with App Proxy
=> PTL: Change Netbox ingress URLs for compatability with App Proxy

apps/juror/automation/kustomization.yaml, apps/juror/base/kustomization.yaml, apps/juror/demo/base/kustomization.yaml, apps/juror/ithc/base/kustomization.yaml, apps/juror/juror-public/demo.yaml, apps/juror/juror-public/image-policy.yaml, apps/juror/juror-public/image-repo.yaml, apps/juror/juror-public/ithc.yaml, apps/juror/juror-public/juror-public.yaml, apps/juror/juror-public/prod.yaml, apps/juror/juror-public/sbox.yaml, apps/juror/juror-public/stg.yaml, apps/juror/juror-public/test.yaml, apps/juror/prod/base/kustomization.yaml, apps/juror/sbox/base/kustomization.yaml, apps/juror/stg/base/kustomization.yaml, apps/juror/test/base/kustomization.yaml
=> juror: add juror-public

apps/darts-modernisation/darts-portal/stg.yaml
=> Removing unused config for DARTS portal

apps/jenkins/jenkins/ptl/jenkins-azure-vm-agent.yaml, apps/jenkins/jenkins/ptlsbox/jenkins-azure-vm-agent.yaml
DTSPO-15526
updating ARM jenkins image version to 1.4.97
=> DTSPO-15526 - updating ARM jenkins image version

apps/admin/external-dns/external-dns.yaml
https://tools.hmcts.net/jira/browse/DTSPO-14560
Add ability for ingresses to be excluded from external-dns
=> DTSPO-14559 - Enable exclusions on external-dns

apps/admin/external-dns/external-dns.yaml
https://tools.hmcts.net/jira/browse/DTSPO-14559
Update extraArgs, current config is not working
=> DTSPO-14559 - Update extraArgs in external-dns

apps/vh/video-web/prod.yaml
=> VIH-0000 Update prod values

apps/vh/admin-web/prod.yaml, apps/vh/video-web/prod.yaml
N/A
update urls for prod release
=> VIH-0000 update urls for prod release

apps/vh/admin-web/dev.yaml, apps/vh/video-web/dev.yaml
[VIH-10233](https://tools.hmcts.net/jira/browse/VIH-10233)
Adding annotation to exclude admin and video web from external DNS
=> VIH-10233 add external-dns annotation

apps/pip/publication-services/test.yaml
https://tools.hmcts.net/jira/browse/PUB-2193
Add publication services OTP test image
=> PUB-2193 Add publication services OTP test image

CODEOWNERS, apps/flux-system/automation/kustomization.yaml, apps/opal/automation/kustomization.yaml, apps/opal/base/kustomization.yaml, apps/opal/opal-fines-service/image-policy.yaml, apps/opal/opal-fines-service/image-repo.yaml, apps/opal/opal-fines-service/opal-fines-service.yaml, apps/opal/opal-fines-service/stg.yaml, apps/opal/opal-frontend/image-policy.yaml, apps/opal/opal-frontend/image-repo.yaml, apps/opal/opal-frontend/opal-frontend.yaml, apps/opal/opal-frontend/stg.yaml, apps/opal/stg/base/kustomization.yaml
=> Deploy initial Opal apps to staging

apps/darts-modernisation/darts-api/prod.yaml, apps/darts-modernisation/darts-api/sbox.yaml, apps/darts-modernisation/darts-api/stg.yaml
https://tools.hmcts.net/jira/browse/DMP-1472
=> DMP-1472 - Add portal url to environment variables

apps/opal/opal-fines-service/stg.yaml, apps/opal/opal-frontend/stg.yaml
=> Update ingress for Opal staging

apps/juror/automation/kustomization.yaml, apps/juror/base/kustomization.yaml, apps/juror/demo/base/kustomization.yaml, apps/juror/ithc/base/kustomization.yaml, apps/juror/juror-pnc/demo.yaml, apps/juror/juror-pnc/image-policy.yaml, apps/juror/juror-pnc/image-repo.yaml, apps/juror/juror-pnc/ithc.yaml, apps/juror/juror-pnc/juror-pnc.yaml, apps/juror/juror-pnc/prod.yaml, apps/juror/juror-pnc/sbox.yaml, apps/juror/juror-pnc/stg.yaml, apps/juror/juror-pnc/test.yaml, apps/juror/prod/base/kustomization.yaml, apps/juror/sbox/base/kustomization.yaml, apps/juror/stg/base/kustomization.yaml, apps/juror/test/base/kustomization.yaml
=> add juror-pnc

apps/pre/demo/base/kustomization.yaml, apps/pre/dev/base/kustomization.yaml, apps/pre/sbox/base/kustomization.yaml, apps/pre/stg/base/kustomization.yaml, apps/pre/test/base/kustomization.yaml
=> Add nonprod rbac to PRE

apps/pip/publication-services/test.yaml
https://tools.hmcts.net/jira/browse/PUB-2193
Update OTP test image
=> PUB-2193 Update OTP test image

apps/pip/data-management-expired-artefacts-cron/stg/00.yaml, apps/pip/data-management-expired-artefacts-cron/stg/01.yaml
=> Updated cron for pip

apps/pip/data-management-expired-artefacts-cron/stg/00.yaml, apps/pip/data-management-expired-artefacts-cron/stg/01.yaml
=> Updated pip cron trigger

apps/dc/automation/kustomization.yaml, apps/dc/base/kustomize.yaml, apps/dc/dc-purview-shir/dc-purview-shir.yaml, apps/dc/dc-purview-shir/dev.yaml, apps/dc/dc-purview-shir/image-policy.yaml, apps/dc/dev/00/kustomization.yaml, apps/dc/dev/01/kustomization.yaml, apps/dc/dev/base/kustomization.yaml, apps/dc/serviceaccount/dev.yaml, apps/dc/serviceaccount/stg.yaml
https://tools.hmcts.net/jira/browse/DC-78
Extend dc shir config to get a passing build locally by running through https://github.com/hmcts/cnp-flux-config/blob/master/docs/app-deployment-v2.md
=> Dc 78 dc shir deployment config

apps/dc/dc-purview-shir/dc-purview-shir.yaml
https://tools.hmcts.net/jira/browse/DC-78
Fix bugs in the dc shir config
=> Update chart base reference for dc shir

apps/dc/dc-purview-shir/dc-purview-shir.yaml, apps/dc/dc-purview-shir/dev.yaml
https://tools.hmcts.net/jira/browse/DC-78
Remove nested base attribute that is not needed
=> Remove base attribute

apps/monitoring/automation/kustomization.yaml, apps/monitoring/prod/00/hourlyusage.enc.yaml, apps/monitoring/prod/00/kustomization.yaml, apps/monitoring/version-reporter/ptl/hourlyusage.enc.yaml, apps/monitoring/vm-hourlyusage/hourlyusage.yaml, apps/monitoring/vm-hourlyusage/image-policy.yaml, apps/monitoring/vm-hourlyusage/image-repo.yaml, apps/monitoring/vm-hourlyusage/kustomization.yaml, apps/monitoring/vm-hourlyusage/rbac.yaml
https://tools.hmcts.net/jira/browse/DTSPO-16039
DTSPO-16039 hourlyusage move to prod
=> DTSPO-16039 hourlyusage move to prod

apps/monitoring/version-reporter/hourlyusage/hourlyusage.yaml, apps/monitoring/vm-hourlyusage/hourlyusage.yaml
https://tools.hmcts.net/jira/browse/DTSPO-15953
Should run every hour 5min past the hour. 5 min buffer for any other vms start up at the hour to start
=> DTSPO-15953: Update to cron schedule

apps/dc/dc-purview-shir/dev.yaml, apps/dc/dc-purview-shir/image-repo.yaml
https://tools.hmcts.net/jira/browse/DC-78
Update incorrect image reference for dc purview shir
=> Update incorrect image name for purview-integration-runtime

apps/monitoring/vm-hourlyusage/hourlyusage.yaml
https://tools.hmcts.net/jira/browse/DTSPO-15924
Adds label for ignoring dynatrace
=> Adds label for ignoring dynatrace

apps/dynatrace/dynakube.yaml, apps/monitoring/vm-hourlyusage/hourlyusage.yaml
https://tools.hmcts.net/jira/browse/DTSPO-16039
Dtspo 15953 hourlyusage move oneagent issue 2
=> Dtspo 15953 hourlyusage move oneagent issue 2

apps/darts-modernisation/demo/base/kustomization.yaml, clusters/demo/base/kustomization.yaml
=> DMP-1590-Darts-Demo-Env

apps/dynatrace/dynakube.yaml, apps/monitoring/prod/00/kustomization.yaml, apps/monitoring/prod/00/version-reporter.enc.yaml, apps/monitoring/vm-hourlyusage/hourlyusage.yaml
https://tools.hmcts.net/jira/browse/DTSPO-16039
Adds secrets for the version reporter side for cosmos db
=> Dtspo-16039 hourlyusage move oneagent issue 2

apps/pip/publication-services/test.yaml
https://tools.hmcts.net/jira/browse/PUB-2234
Update image in test env to rate-limiting PR
=> PUB-2234 Update image in test env to rate-limiting PR

apps/pip/publication-services/test.yaml
https://tools.hmcts.net/jira/browse/PUB-2234
Update rate limiting test image
=> PUB-2234 Update rate limiting test image

clusters/prod/base/kustomization.yaml
=> Added HMI namespace to prod

apps/pip/frontend/stg.yaml
https://tools.hmcts.net/jira/browse/PUB-2007
frontend braking changes related to 2007 deploying into staging.
=> frontend braking changes related to 2007 deploying into staging.

apps/jenkins/jenkins/ptl/jenkins-azure-vm-agent.yaml, apps/jenkins/jenkins/ptlsbox/jenkins-azure-vm-agent.yaml
Version 1.4.106 doesn't exist. Agents aren't scheduling as a result
=> Update image gallery version

apps/neuvector/neuvector/neuvector.yaml
Updates Neuvector to latest chart version in SDS
=> Update neuvector chart version

apps/jenkins/jenkins/ptl/jenkins-azure-vm-agent.yaml
https://tools.hmcts.net/jira/browse/DTSPO-15526
Update vm image on arm agents
=> DTSPO-15526 - Update arm image

apps/pip/publication-services/stg.yaml
https://tools.hmcts.net/jira/browse/PUB-2234
Add staging env variables for rate limiting
=> PUB-2234 Add staging env variables for rate limiting

apps/pip/publication-services/test.yaml
https://tools.hmcts.net/jira/browse/PUB-2193
New test image for OTP
=> New test image for OTP

apps/pip/frontend/test.yaml
=> Updated test image for pip

apps/pip/frontend/test.yaml
=> PUB-2118 - Updated test image

apps/pip/frontend/test.yaml
https://tools.hmcts.net/jira/browse/PUB-2112
Replace console.log with logger.<level> in Frontend
=> Replace console.log with logger.<level> in Frontend

apps/pip/frontend/test.yaml, apps/pip/publication-services/test.yaml
https://tools.hmcts.net/jira/browse/PUB-2112
Reverted changes in publication services and front end
=> Reverted changes in publication services and front end

apps/pip/frontend/test.yaml
=> PUB-1180 - Updated test image

apps/pip/frontend/test.yaml
=> Updated test image pip

apps/darts-modernisation/darts-api/demo.yaml, apps/darts-modernisation/darts-portal/demo.yaml
=> update demo docker images

apps/pip/frontend/test.yaml
=> PUB-2118 - Updated image

apps/pip/frontend/stg.yaml, apps/pip/frontend/test.yaml
=> PUB-2118 - Updated pip

apps/pip/frontend/stg.yaml
=> PUB-2118 - Updated image for pip

apps/admin/kured/kured.yaml
Reverts hmcts/sds-flux-config#3278
Error: unknown flag: --metrics-port
=> Revert "Update Helm release kured to v4.7.0 in kured"

apps/darts-modernisation/darts-api/demo.yaml
=> darts-api restart on demo

apps/darts-modernisation/darts-gateway/demo.yaml
=> darts-gateway demo restart

apps/darts-modernisation/demo/base/kustomization.yaml
=> Adding nonprod-role for darts demo

apps/pip/account-management/ithc.yaml, apps/pip/data-management/ithc.yaml, apps/pip/publication-services/ithc.yaml, apps/pip/subscription-management/ithc.yaml
https://tools.hmcts.net/jira/browse/DTSPO-15841
missed out the s
=> DTSPO-15841: Adding in replica

apps/pip/account-management/ithc.yaml, apps/pip/publication-services/ithc.yaml, apps/pip/subscription-management/ithc.yaml
=> move to spec.values.replicas

apps/azure-devops/azure-devops-agent-keda/dev.yaml, apps/azure-devops/azure-devops-agent-keda/ithc.yaml, apps/azure-devops/azure-devops-agent-keda/sbox.yaml, apps/azure-devops/azure-devops-agent-keda/test.yaml, apps/azure-devops/base/kustomization.yaml, apps/azure-devops/base/kustomize.yaml, apps/azure-devops/dev/base/kustomization.yaml, apps/azure-devops/ithc/base/kustomization.yaml, apps/azure-devops/sbox/base/kustomization.yaml, apps/azure-devops/serviceaccount/ithc.yaml, apps/azure-devops/serviceaccount/sbox.yaml, apps/azure-devops/serviceaccount/stg.yaml, apps/azure-devops/serviceaccount/test.yaml, apps/azure-devops/test/base/kustomization.yaml
Reverts hmcts/sds-flux-config#4063
More permissions are required on the MI so reverting for now
=> Revert "DTSPO-15812: move ado-agents in dev,ithc,sbox,test to workload identity"

apps/azure-devops/azure-devops-agent-keda/test.yaml, apps/azure-devops/base/kustomization.yaml, apps/azure-devops/base/kustomize.yaml, apps/azure-devops/serviceaccount/test.yaml, apps/azure-devops/test/base/kustomization.yaml
https://tools.hmcts.net/jira/browse/DTSPO-15812
* enable workload identity azure-devops test env for MI/SDP testing
=> DTSPO-15812: enable workload identity azure-devops test env

apps/azure-devops/azure-devops-agent-keda/test.yaml
https://tools.hmcts.net/jira/browse/DTSPO-15812
* fix indentation for azure-devops agents
=> DTSPO-15812: fix indentation for azure-devops agents

apps/darts-modernisation/darts-api/demo.yaml, apps/darts-modernisation/darts-gateway/demo.yaml, apps/darts-modernisation/darts-portal/demo.yaml, apps/darts-modernisation/darts-stub-services/demo.yaml
=> Fixing DARTS application versions for demo environment

apps/darts-modernisation/automation/kustomization.yaml, apps/darts-modernisation/base/kustomization.yaml, apps/darts-modernisation/darts-automated-tasks/darts-automated-tasks.yaml, apps/darts-modernisation/darts-automated-tasks/image-policy.yaml, apps/darts-modernisation/darts-automated-tasks/image-repo.yaml, apps/darts-modernisation/darts-automated-tasks/stg.yaml, apps/darts-modernisation/stg/base/kustomization.yaml
- used for running automated tasks
=> Test creating another deployment for darts-api

apps/jenkins/jenkins/jenkins-controller-version.yaml
DTSPO-16334
Downgrading sonar plugin to 2.16.1
=> downgrade sonar plugin

clusters/ithc/base/kustomization.yaml, clusters/test/base/kustomization.yaml
Add Juror Base flux to ithc and test clusters
- [] README and other documentation has been updated / added (if needed)
- [] tests have been updated / new tests has been added (if needed)
=> Add Juror Base to ithc and test

apps/darts-modernisation/darts-api/darts-api.yaml, apps/darts-modernisation/darts-api/demo.yaml, apps/darts-modernisation/darts-automated-tasks/darts-automated-tasks.yaml, apps/darts-modernisation/darts-automated-tasks/stg.yaml, apps/darts-modernisation/darts-gateway/darts-gateway.yaml, apps/darts-modernisation/darts-gateway/demo.yaml, apps/darts-modernisation/darts-portal/darts-portal.yaml, apps/darts-modernisation/darts-portal/demo.yaml
N/A
- running 2 replicas
- don't run keda for darts-automated-tasks release
=> Darts tweaks

apps/juror/serviceaccount/ithc.yaml, apps/juror/serviceaccount/prod.yaml, apps/juror/serviceaccount/test.yaml
Add Client IDs of Managed Identities to enable keyvault access
=> add client ID of MI for vaults

apps/jenkins/jenkins/jenkins-controller-version.yaml
DTSPO-16334
downgrade sonar plugin
=> Dtspo 16334

apps/darts-modernisation/darts-api/darts-api.yaml
N/A
- moving it from the darts-api chart so that the chart can be re-used for automated tasks
- this prevents the automated tasks HR from including a function deployment
=> Adding chart function to darts-api HR

apps/darts-modernisation/darts-api/darts-api.yaml
N/A
Pods are being killed due to out of memory, increasing the memory.
=> Increase darts-api memory

apps/pip/frontend/test.yaml
=> PUB-2118 Update lax cookie text image

apps/pip/frontend/test.yaml
Added SESSION_COOKIE_SAME_SITE to test env
=> Added SESSION_COOKIE_SAME_SITE to test env

apps/azure-devops/azure-devops-agent-keda/prod.yaml
DTSPO-16403
Bump up memory requests for prod keda agents, as some pipelines are failing on exceeding memory requests
=> bump up memory requests for prod

apps/juror/juror-public/demo.yaml, apps/juror/juror-public/ithc.yaml, apps/juror/juror-public/juror-public.yaml, apps/juror/juror-public/prod.yaml, apps/juror/juror-public/sbox.yaml, apps/juror/juror-public/stg.yaml, apps/juror/juror-public/test.yaml
Alter ingress Hosts for juror-public to be .apps.hmcts.net
=> convert Juror to use apps

apps/juror/juror-pnc/demo.yaml, apps/juror/juror-pnc/ithc.yaml, apps/juror/juror-pnc/sbox.yaml, apps/juror/juror-pnc/test.yaml, apps/juror/juror-public/demo.yaml, apps/juror/juror-public/ithc.yaml, apps/juror/juror-public/sbox.yaml, apps/juror/juror-public/test.yaml, apps/juror/juror-scheduler-api/demo.yaml, apps/juror/juror-scheduler-api/ithc.yaml, apps/juror/juror-scheduler-api/sbox.yaml, apps/juror/juror-scheduler-api/test.yaml
add replicas to demo and comments about fixing images
=> add replicas to demo and comments about fixing images

apps/juror/automation/kustomization.yaml, apps/juror/base/kustomization.yaml, apps/juror/demo/base/kustomization.yaml, apps/juror/ithc/base/kustomization.yaml, apps/juror/juror-scheduler-execution/demo.yaml, apps/juror/juror-scheduler-execution/image-policy.yaml, apps/juror/juror-scheduler-execution/image-repo.yaml, apps/juror/juror-scheduler-execution/ithc.yaml, apps/juror/juror-scheduler-execution/juror-scheduler-execution.yaml, apps/juror/juror-scheduler-execution/prod.yaml, apps/juror/juror-scheduler-execution/sbox.yaml, apps/juror/juror-scheduler-execution/stg.yaml, apps/juror/juror-scheduler-execution/test.yaml, apps/juror/prod/base/kustomization.yaml, apps/juror/sbox/base/kustomization.yaml, apps/juror/stg/base/kustomization.yaml, apps/juror/test/base/kustomization.yaml
https://centralgovernmentcgi.atlassian.net/browse/JM-5597
=> Juror: Add JSE

apps/mailrelay/mailrelay/dev/dev.yaml
https://tools.hmcts.net/jira/browse/DTSPO-15842
Adding service account for Dev mailrelay
=> Adding service account for Dev mailrelay

apps/mailrelay2/mailrelay2/dev/dev.yaml
https://tools.hmcts.net/jira/browse/DTSPO-15842
Adding service account for Dev mailrelay2
=> Adding service account for Dev mailrelay2

apps/met/themis-fe/themis-fe.yaml
N/A
Bumped memory limit and request to avoid OOM errors.
=> fix: updated memory request and limit for LibraGoB

apps/met/themis-fe/themis-fe.yaml
N/A
Bump memory limit and request to match projected application usage.
=> fix: updated LibraGob memory request/limit to match projected app usage

apps/pip/account-management/stg.yaml, apps/pip/channel-management/stg.yaml, apps/pip/data-management/stg.yaml, apps/pip/frontend/stg.yaml, apps/pip/publication-services/stg.yaml, apps/pip/subscription-management/stg.yaml
N/A
Updated PIP replicas for staging
=> Updated replicas for staging

apps/pip/account-management/prod.yaml, apps/pip/account-management/test.yaml, apps/pip/channel-management/prod.yaml, apps/pip/channel-management/test.yaml, apps/pip/data-management/prod.yaml, apps/pip/data-management/test.yaml, apps/pip/frontend/prod.yaml, apps/pip/frontend/test.yaml, apps/pip/publication-services/prod.yaml, apps/pip/publication-services/test.yaml, apps/pip/subscription-management/prod.yaml, apps/pip/subscription-management/test.yaml
=> Updated replicas for pip

apps/azure-devops/serviceaccount/dev.yaml
=> DTSPO-15812: Update to use stg mi in dev

apps/azure-devops/azure-devops-agent-keda/azure-devops-agent.yaml, apps/azure-devops/azure-devops-agent-keda/dev.yaml, apps/azure-devops/azure-devops-agent-keda/ptlsbox.yaml, apps/azure-devops/azure-devops-agent-keda/sbox.yaml, apps/azure-devops/azure-devops-agent-keda/stg.yaml, apps/azure-devops/azure-devops-agent-keda/test.yaml, apps/azure-devops/prod/base/kustomization.yaml, apps/azure-devops/ptl/base/kustomization.yaml, apps/azure-devops/serviceaccount/prod.yaml, apps/azure-devops/serviceaccount/ptl.yaml
Reverts hmcts/sds-flux-config#4126
=> Revert "DTSPO-15812: Add prod&ptl, move chart upgrade to base"

apps/opal/opal-frontend/stg.yaml
=> Override staging URLs for opal-frontend

apps/opal/opal-frontend/stg.yaml
=> Enable redis in stg

apps/juror/automation/kustomization.yaml, apps/juror/base/kustomization.yaml, apps/juror/demo/base/kustomization.yaml, apps/juror/ithc/base/kustomization.yaml, apps/juror/juror-bureau/demo.yaml, apps/juror/juror-bureau/image-policy.yaml, apps/juror/juror-bureau/image-repo.yaml, apps/juror/juror-bureau/ithc.yaml, apps/juror/juror-bureau/juror-bureau.yaml, apps/juror/juror-bureau/prod.yaml, apps/juror/juror-bureau/sbox.yaml, apps/juror/juror-bureau/stg.yaml, apps/juror/juror-bureau/test.yaml, apps/juror/prod/base/kustomization.yaml, apps/juror/sbox/base/kustomization.yaml, apps/juror/stg/base/kustomization.yaml, apps/juror/test/base/kustomization.yaml
=> juror: add bureau

apps/opal/opal-frontend/stg.yaml
=> Use repo values again

apps/pip/account-management/test.yaml, apps/pip/data-management/test.yaml, apps/pip/frontend/test.yaml, apps/pip/subscription-management/test.yaml
https://tools.hmcts.net/jira/browse/PUB-2133
Update pip
=> Updated pip

apps/azure-devops/azure-devops-agent-keda/azure-devops-agent.yaml, apps/azure-devops/azure-devops-agent-keda/prod.yaml, apps/azure-devops/azure-devops-agent-keda/stg.yaml
[DTSPO-16540](https://tools.hmcts.net/jira/browse/DTSPO-16540)
Did this already for stg and it fixed the issue, but same is needed for prod
Not doing other envs, as I watched them running and this would be overkill
=> Upgrade limits in prod env for ado agents

apps/pip/account-management/test.yaml, apps/pip/subscription-management/test.yaml
https://tools.hmcts.net/jira/browse/PUB-2133
Removed test images
=> Removed old images pip

apps/ipam/ipam-ingress.yaml, apps/ipam/ptl/base/kustomization.yaml
DTSPO-16537 
Added ingress config for ipam.
=> DTSPO-16537 - added ingress config for ipam

apps/azureserviceoperator-system/resources/cosmos-db.yaml, apps/ipam/ptl/aso/ipam-cosmosdb.yaml, apps/ipam/ptl/base/kustomization.yaml
https://tools.hmcts.net/jira/browse/DTSPO-16538
Added config to create azure cosmos db using Azure service operator.
=> DTSPO-16538 -  aso cosmos db

apps/ipam/ipam-ingress.yaml
To fix this error on the flux config.
Ingress/ipam/ipam-ingress dry-run failed (Conflict): Operation cannot be fulfilled on ingresses.networking.k8s.io "ipam-ingress": the object has been modified; please apply your changes to the latest version and try again...
=> DTSPO-16538 fixing error

apps/ipam/ipam-ingress.yaml
fixing this error on  flux with regards to this resource.
dry-run failed (Conflict): Operation cannot be fulfilled on ingresses.networking.k8s.io "ipam-ingress": the object has been modified; please apply your changes to the latest version and try again
=> fixing error

apps/ipam/ipam-engine.yaml
https://tools.hmcts.net/jira/browse/DTSPO-16537
Configure environment variables to fix connection from ipam engine to cosmos db
=> DTSPO-16537 - configure environment variables to connect engine with db

apps/darts-modernisation/darts-stub-services/demo.yaml
N/A
No longer set a specific version
=> DARTS stub services - demo fix

apps/ipam/ipam-engine.yaml
https://tools.hmcts.net/jira/browse/DTSPO-15954
Trying to fix errors on the engine pod on ipam
=> DTSPO-15954 - setup up all the env vars

apps/juror/automation/kustomization.yaml, apps/juror/base/kustomization.yaml, apps/juror/demo/base/kustomization.yaml, apps/juror/ithc/base/kustomization.yaml, apps/juror/juror-api/demo.yaml, apps/juror/juror-api/image-policy.yaml, apps/juror/juror-api/image-repo.yaml, apps/juror/juror-api/ithc.yaml, apps/juror/juror-api/juror-api.yaml, apps/juror/juror-api/prod.yaml, apps/juror/juror-api/sbox.yaml, apps/juror/juror-api/stg.yaml, apps/juror/juror-api/test.yaml, apps/juror/juror-bureau/demo.yaml, apps/juror/juror-pnc/demo.yaml, apps/juror/juror-public/demo.yaml, apps/juror/juror-scheduler-api/demo.yaml, apps/juror/juror-scheduler-execution/demo.yaml, apps/juror/prod/base/kustomization.yaml, apps/juror/sbox/base/kustomization.yaml, apps/juror/stg/base/kustomization.yaml, apps/juror/test/base/kustomization.yaml
add juror api to all envs & remove 2 replicas from every other application.
=>  add juror-api

apps/pdm/base/kustomization.yaml, apps/pdm/base/kustomize.yaml, apps/pdm/dev/base/kustomization.yaml, clusters/dev/base/kustomization.yaml
=> Add PDM application to sds-flux-config

apps/keda/keda/keda-patch.yaml, apps/keda/ptlsbox/base/kustomization.yaml
DTSPO-16659
Testing keda patches in ptlsbox
=> patching keda in ptlsbox

apps/opal/automation/kustomization.yaml, apps/opal/opal-legacy-db-stub/image-policy.yaml, apps/opal/opal-legacy-db-stub/image-repo.yaml, apps/opal/opal-legacy-db-stub/opal-legacy-db-stub.yaml, apps/opal/opal-legacy-db-stub/stg.yaml, apps/opal/stg/base/kustomization.yaml
=> Add Opal Legacy Stub

apps/ipam/ptl/sops-secrets/ipam-sop-secrets.enc.yaml
=> DTSPO-16537 - updated UI app id

apps/ipam/ptl/sops-secrets/ipam-sop-secrets.enc.yaml
=> updated ipam secrets

apps/ipam/ipam-ingress.yaml
=> fixing ipam with engine added in the ingress

apps/ipam/ipam-engine.yaml, apps/ipam/ipam-ui.yaml
=> Ipam - fix 5

apps/darts-modernisation/darts-stub-services/test.yaml, apps/darts-modernisation/stg/base/darts-api-function.enc.yaml, apps/darts-modernisation/test/base/darts-api-function.enc.yaml, apps/darts-modernisation/test/base/kustomization.yaml, clusters/test/base/kustomization.yaml
=> DMP-1876-Darts-Test-Environment

apps/ipam/ipam-engine.yaml, apps/ipam/ipam-ui.yaml
=> Ipam fix attempt 8

apps/ipam/ipam-ingress.yaml
=> Ipam fix attempt 9

apps/met/themis-fe/prod.yaml
=> Update prod.yaml 1.13.0

apps/ipam/ptl/sops-secrets/ipam-sop-secrets.enc.yaml
Another fix attempt by changing the UI id
=> fix ipam attempt 10

apps/met/themis-fe/prod.yaml
=> Update prod.yaml Rel 1.13.0

apps/met/themis-fe/prod.yaml
=> Update prod.yaml  revert to 1.0.10

apps/pip/frontend/test.yaml
https://tools.hmcts.net/jira/browse/PUB-1619
=> PUB-2115-Updated image in test.yaml

apps/ipam/ipam-ingress.yaml
https://tools.hmcts.net/jira/browse/DTSPO-15956
Applying fix to cert invalid error on below ipam URL.
https://ipam.platform.hmcts.net/
=> DTSPO-15956 - applying fix to SSL issue on ipam

apps/jenkins/jenkins/ptl/jenkins.yaml, apps/opal/automation/kustomization.yaml, apps/opal/opal-print-service/image-policy.yaml, apps/opal/opal-print-service/image-repo.yaml, apps/opal/opal-print-service/opal-print-service.yaml, apps/opal/opal-print-service/stg.yaml, apps/opal/stg/base/kustomization.yaml
[PO-193](https://tools.hmcts.net/jira/browse/PO-193)
Add Opal Print Service
=> Add Opal Print Service

apps/ipam/README.md
https://tools.hmcts.net/jira/browse/DTSPO-16306
IPAM documentation for future references.
=> DTSPO-16306 - IPAM documentation

apps/darts-modernisation/darts-migration/darts-api-migration.yaml
=> Avoid scaling KEDA on darts-api-migration helm release

apps/darts-modernisation/darts-migration/prod.yaml
=> ddm-26 update image

apps/dynatrace/dynatrace-crds/kustomization.yaml, apps/dynatrace/dynatrace-operator.yaml
To be upgraded as part of patching: https://tools.hmcts.net/jira/browse/DTSPO-16790
Similarly done in https://github.com/hmcts/cnp-flux-config/commit/f366d00c7e1783c47524c2537018dfa9c300307c
=> DTSPO-16790: Upgrade dynatrace oneagent &operator

apps/pip/data-management-expired-artefacts-cron/test/00.yaml, apps/pip/data-management-expired-artefacts-cron/test/01.yaml
https://tools.hmcts.net/jira/browse/PUB-2336
Fix cron triggers
=> PUB-2336 - Updated cron

apps/pip/data-management-expired-artefacts-cron/test/00.yaml, apps/pip/data-management-expired-artefacts-cron/test/01.yaml
https://tools.hmcts.net/jira/browse/PUB-2336
Change back schedule
=> PUB-2336 - Changed back schedule

apps/pip/data-management/test.yaml
https://tools.hmcts.net/jira/browse/PUB-2337
Added graceful shutdown
=> PUB-2337 - Testing graceful shutdown

apps/pip/publication-services/test.yaml
https://tools.hmcts.net/jira/browse/PUB-2305
Add Notify link for subscription page to test environment
=> Add Notify link for subscription page to test environment

apps/juror/juror-api/stg.yaml, apps/juror/juror-bureau/stg.yaml, apps/juror/juror-pnc/ithc.yaml, apps/juror/juror-pnc/prod.yaml, apps/juror/juror-pnc/stg.yaml, apps/juror/juror-public/stg.yaml, apps/juror/juror-scheduler-execution/stg.yaml
=> Juror update envs

apps/juror/juror-bureau/stg.yaml, apps/juror/juror-public/stg.yaml
=> juror: update api endpoint

apps/juror/juror-api/prod.yaml, apps/juror/juror-bureau/prod.yaml, apps/juror/juror-public/prod.yaml, apps/juror/juror-scheduler-execution/prod.yaml
=> juror: add prod urls

apps/admin/kured/kured.yaml
https://tools.hmcts.net/jira/browse/DTSPO-16858
Updated Kured to the latest version
=> DTSPO-16858 - Update Kured to 1.15

apps/darts-modernisation/darts-api/ithc.yaml, apps/darts-modernisation/darts-gateway/ithc.yaml, apps/darts-modernisation/darts-portal/ithc.yaml, apps/darts-modernisation/darts-stub-services/ithc.yaml, apps/darts-modernisation/identity/ithc.yaml, apps/darts-modernisation/ithc/00/kustomization.yaml, apps/darts-modernisation/ithc/01/kustomization.yaml, apps/darts-modernisation/ithc/base/kustomization.yaml, apps/darts-modernisation/serviceaccount/ithc.yaml, clusters/ithc/base/kustomization.yaml
=> add ITHC for DARTS

apps/admin/kured/kured.yaml
https://tools.hmcts.net/jira/browse/DTSPO-16858
Removed unnecessary code.
=> DTSPO-16858 - removed unnecessary code

apps/juror/stg/00/kustomization.yaml, apps/juror/stg/base/kustomization.yaml
=> juror: switch bureau to 00 cluster only

apps/pip/frontend/test.yaml
=> Removed test image

apps/admin/external-dns/external-dns.yaml
https://tools.hmcts.net/jira/browse/DTSPO-16859
Patching external DNS
=> Update external dns chart version

.github/workflows/tests.yml, tests/install-tools.sh
Add auth to install yq and kustomize - same as cft-flux-config
=> Add auth to install yq and kustomize

apps/opal/automation/kustomization.yaml, apps/opal/opal-log-audit-service/image-policy.yaml, apps/opal/opal-log-audit-service/image-repo.yaml, apps/opal/opal-log-audit-service/opal-log-audit-service.yaml, apps/opal/opal-log-audit-service/stg.yaml, apps/opal/stg/base/kustomization.yaml
PO-214
Add Opal log and audit service in SDS pipelines
=> PO-214: Add Opal log and audit service

apps/juror/stg/00/kustomization.yaml, apps/juror/stg/base/kustomization.yaml
=> juror: revert bureau on 00 cluster only

apps/juror/juror-bureau/juror-bureau.yaml, apps/juror/juror-public/juror-public.yaml
Increase memory Limits for Juror FE
=> increase memory for juror FE

apps/ipam/ipam-engine.yaml
Testing ipam from the localhost to see if we can find its usage before comparing it with netbox.  This is preparation for the show and tell this week.
=> IPAM - testing from localhost

apps/ipam/ipam-ui.yaml
=> testing url change

apps/ipam/ipam-engine.yaml, apps/ipam/ipam-ui.yaml
=> Revert ipam url change

apps/ipam/ipam-engine.yaml, apps/ipam/ipam-ingress.yaml, apps/ipam/ipam-ui.yaml
Setting up ipam2 to test the api outside Application proxy.
=> Testing with ipam2

apps/neuvector/crds/kustomization.yaml, apps/neuvector/neuvector/ithc/ithc.yaml, apps/neuvector/neuvector/neuvector.yaml, apps/neuvector/neuvector/stg/stg.yaml, apps/neuvector/neuvector/test/test.yaml, clusters/ithc/base/kustomization.yaml, clusters/stg/base/kustomization.yaml, clusters/test/base/kustomization.yaml
https://tools.hmcts.net/jira/browse/DTSPO-16875
updating spect version to 1.5.4 for prod neuvector
=> update spec version prod 1.5.4

apps/darts-modernisation/darts-api/demo.yaml, apps/darts-modernisation/darts-api/prod.yaml, apps/darts-modernisation/darts-api/sbox.yaml, apps/darts-modernisation/darts-api/stg.yaml, apps/darts-modernisation/darts-automated-tasks/demo.yaml, apps/darts-modernisation/darts-automated-tasks/ithc.yaml, apps/darts-modernisation/darts-automated-tasks/prod.yaml, apps/darts-modernisation/darts-automated-tasks/sbox.yaml, apps/darts-modernisation/darts-automated-tasks/stg.yaml, apps/darts-modernisation/darts-automated-tasks/test.yaml
=> Amending DARTS_GATEWAY_URL to http

apps/azure-devops/dev/base/azure-devops-token.yaml
Reverts hmcts/sds-flux-config#4339 - as it's spinning and destroying pods because my account does not have access, looking into another way to generate PAT
=> Revert "Update dev ado token"

apps/pre/pre-portal/stg.yaml
=> PRE Portal Staging Env vars

apps/azure-devops/ithc/base/azure-devops-token.yaml, apps/azure-devops/ptl/base/azure-devops-token.yaml, apps/azure-devops/ptlsbox/base/azure-devops-token.yaml, apps/azure-devops/sbox/base/azure-devops-token.yaml, apps/azure-devops/stg/base/azure-devops-token.yaml, apps/azure-devops/test/base/azure-devops-token.yaml
Updates ado tokens everywhere except prod for now
=> Updating ADO token

apps/azure-devops/dev/base/azure-devops-token.yaml, apps/azure-devops/ithc/base/azure-devops-token.yaml, apps/azure-devops/prod/base/azure-devops-token.yaml, apps/azure-devops/ptlsbox/base/azure-devops-token.yaml, apps/azure-devops/sbox/base/azure-devops-token.yaml, apps/azure-devops/stg/base/azure-devops-token.yaml, apps/azure-devops/test/base/azure-devops-token.yaml
Updates working token but to one with a reduced scope for only agent pools
=> Update token to one with limited scope

apps/darts-modernisation/darts-automated-tasks/test.yaml
=> Force restart of darts-automated-tasks on test

apps/darts-modernisation/automation/kustomization.yaml, apps/darts-modernisation/base/kustomization.yaml, apps/darts-modernisation/darts-proxy/darts-proxy.yaml, apps/darts-modernisation/darts-proxy/demo.yaml, apps/darts-modernisation/darts-proxy/image-policy.yaml, apps/darts-modernisation/darts-proxy/image-repo.yaml, apps/darts-modernisation/demo/base/kustomization.yaml
=> add in darts-proxy

apps/darts-modernisation/test/base/kustomization.yaml
=> apply test patch

apps/darts-modernisation/demo/base/kustomization.yaml, apps/darts-modernisation/ithc/base/kustomization.yaml, apps/darts-modernisation/prod/base/kustomization.yaml, apps/darts-modernisation/sbox/base/kustomization.yaml
=> Applying darts-automated-tasks patches to appropriate environments

apps/darts-modernisation/darts-api/demo.yaml, apps/darts-modernisation/darts-api/ithc.yaml, apps/darts-modernisation/darts-api/prod.yaml, apps/darts-modernisation/darts-api/sbox.yaml, apps/darts-modernisation/darts-api/stg.yaml, apps/darts-modernisation/darts-api/test.yaml
https://tools.hmcts.net/jira/browse/DMP-2506
Dynamic Azure DNS
=> dmp-2506: Dynamic Azure DNS names

apps/darts-modernisation/darts-gateway/demo.yaml, apps/darts-modernisation/darts-gateway/ithc.yaml, apps/darts-modernisation/darts-gateway/prod.yaml, apps/darts-modernisation/darts-gateway/sbox.yaml, apps/darts-modernisation/darts-gateway/stg.yaml, apps/darts-modernisation/darts-gateway/test.yaml
https://tools.hmcts.net/jira/browse/DMP-1601
- [ x tests have been updated / new tests has been added (if needed)
=> dmp 1601 dar notify config env var

apps/darts-modernisation/ithc/base/kustomization.yaml
=> add in stubbed services to ithc

apps/pip/data-management/test.yaml, apps/pip/publication-services/test.yaml
https://tools.hmcts.net/jira/browse/PUB-2281
Removed test images
=> PUB-2281 - Remove test images

apps/met/base/kustomization.yaml, apps/met/test/base/kustomization.yaml
=> fix: only deploy to test

apps/met/batch-jobs/batch-jobs.yaml, apps/met/batch-jobs/test.yaml
=> feat: update LibraGob Housekeeping job

apps/met/batch-jobs/image-policy.yaml
=> fix: update image repository ref

apps/met/batch-jobs/batch-jobs.yaml, apps/met/batch-jobs/test.yaml
Added AMS reporting batch job.
=> feat: add ams reporting batch job

apps/met/batch-jobs/test.yaml
=> feat: update libragob ams reporting schedule

apps/darts-modernisation/darts-gateway/demo.yaml
N/A
Fixing the darts-gateway image version so that a test can be carried out on a previous version.
=> Fix darts-gateway demo version

apps/met/batch-jobs/test.yaml
=> feat: update housekeeping schedule for demo

apps/darts-modernisation/darts-gateway/demo.yaml
=> Revert gateway version fix

CODEOWNERS
might need to be given write access to the repo
=> Update CODEOWNERS to include PRE

apps/pre/pre-api/stg.yaml
=> S28-2641/Scale pre-api to 2 replicas in stg to test zero downtime deployments

apps/juror/juror-api/ithc.yaml, apps/juror/juror-bureau/ithc.yaml, apps/juror/juror-pnc/ithc.yaml, apps/juror/juror-public/ithc.yaml, apps/juror/juror-scheduler-api/ithc.yaml, apps/juror/juror-scheduler-execution/ithc.yaml
=> juror: lock ithc deployments

apps/darts-modernisation/darts-gateway/stg.yaml
https://tools.hmcts.net/jira/browse/DMP-1601
turn dar notify off
- [ x] README and other documentation has been updated / added (if needed)
- [ x] tests have been updated / new tests has been added (if needed)
=> dmp 1601 turn off

apps/azure-devops/azure-devops-agent-keda/ptlsbox.yaml, apps/azure-devops/ptlsbox/base/azure-devops-token.yaml
[DTSPO-13833](https://tools.hmcts.net/jira/browse/DTSPO-13833)
=> DTSPO-13833 Testing Bearer Token 

apps/azure-devops/azure-devops-agent-keda/ptlsbox.yaml, apps/azure-devops/ptlsbox/base/azure-devops-token.yaml
Reverts hmcts/sds-flux-config#4394
=> Revert "DTSPO-13833 Testing Bearer Token "

apps/darts-modernisation/darts-gateway/stg.yaml
https://tools.hmcts.net/jira/browse/DMP-1601
Turn the notify back on
=> dmp 1601 turn back on

apps/met/batch-jobs/image-policy.yaml, apps/mi/mi-azure-functions/image-policy.yaml, apps/mi/mi-house-keeping-service/image-policy.yaml, apps/vh/video-web/image-policy.yaml, tests/flux-v2-image-automation.sh
Adding Helm Release checks to image automation
=> Adding Helm Release checks to image automation

apps/juror/juror-api/juror-api.yaml, apps/juror/juror-bureau/juror-bureau.yaml, apps/juror/juror-pnc/juror-pnc.yaml, apps/juror/juror-public/juror-public.yaml, apps/juror/juror-scheduler-api/juror-scheduler-api.yaml, apps/juror/juror-scheduler-execution/juror-scheduler-execution.yaml
=> juror: resource update

apps/pip/data-management/test.yaml
=> PUB-2261 - Updated replicas

apps/vh/video-web/demo.yaml, apps/vh/video-web/image-policy.yaml
https://tools.hmcts.net/jira/browse/VIH-10554
Currently demo is a replica of prod, hence we need to change this process to enable file to be uploaded temporarily to demo environment 
- [ x] README and other documentation has been updated / added (if needed)
=> VIH-10554 Demo Config

apps/juror/juror-api/ithc.yaml, apps/juror/juror-bureau/ithc.yaml, apps/juror/juror-pnc/ithc.yaml, apps/juror/juror-public/ithc.yaml, apps/juror/juror-scheduler-api/ithc.yaml, apps/juror/juror-scheduler-execution/ithc.yaml
re-enable ITHC deployments
- [] README and other documentation has been updated / added (if needed)
- [] tests have been updated / new tests has been added (if needed)
=> re-enable ITHC deployments

apps/juror/juror-api/prod.yaml, apps/juror/juror-api/stg.yaml
=> update pnc url

apps/pip/data-management/ithc.yaml, apps/pip/ithc/base/kustomization.yaml
=> PUB-2298 - Fix ITHC config for PIP

apps/darts-modernisation/darts-gateway/demo.yaml, apps/darts-modernisation/darts-gateway/ithc.yaml, apps/darts-modernisation/darts-gateway/prod.yaml, apps/darts-modernisation/darts-gateway/sbox.yaml, apps/darts-modernisation/darts-gateway/stg.yaml, apps/darts-modernisation/darts-gateway/test.yaml
https://tools.hmcts.net/jira/browse/DMP-2607
Azure AD B2C Dynamic Attributes
=> dmp-2607: Dynamic Azure DNS names

apps/pip/data-management/test.yaml, apps/pip/publication-services/test.yaml
https://tools.hmcts.net/jira/browse/PUB-2281
Updating test images to test change
=> PUB-2281 - Updated test images

apps/darts-modernisation/darts-gateway/demo.yaml, apps/darts-modernisation/darts-gateway/ithc.yaml, apps/darts-modernisation/darts-gateway/prod.yaml, apps/darts-modernisation/darts-gateway/sbox.yaml, apps/darts-modernisation/darts-gateway/stg.yaml, apps/darts-modernisation/darts-gateway/test.yaml
DMP-2607
Dynamic Azure B2C attributes
=> Dynamic Azure DNS names

apps/juror/juror-scheduler-execution/prod.yaml, apps/juror/juror-scheduler-execution/stg.yaml
=> update juror env vars

apps/pip/data-management/test.yaml, apps/pip/publication-services/test.yaml
Removed old test images for pip
=> PUB-2281 - Removed old images

apps/pip/account-management/ithc.yaml
=> PUB-2298 - Updated DB

apps/pip/account-management/ithc.yaml
Removed update flag for account management
=> PUB-2298 - Removed update flag

apps/pip/ithc/00/kustomization.yaml, apps/pip/ithc/01/kustomization.yaml, apps/pip/ithc/base/kustomization.yaml
Enabled cron triggers for pip ITHC
=> PUB-2298 - PIP ITHC for Cron triggers

apps/darts-modernisation/darts-api/prod.yaml
[DMP-2261](https://tools.hmcts.net/jira/browse/DMP-2261)
See related darts-api application config e.g. `darts.storage.arm.transcription-record-properties-file` which uses this environment variable
=> DMP-2261 ARM_PROPERTY_FILE_ENVIRONMENT: live

apps/met/themis-fe/test.yaml
=> Update test.yaml with code version 1.16.0

apps/pre/pre-api/demo.yaml, apps/pre/pre-api/prod.yaml, apps/pre/pre-portal/demo.yaml, apps/pre/pre-portal/prod.yaml, apps/pre/pre-portal/stg.yaml, apps/pre/pre-portal/test.yaml
=> Setup remaining env vars for PRE apps

apps/met/batch-jobs/prod.yaml, apps/met/prod/base/kustomization.yaml
N/A
Enable LibraGoB PostgreSQL housekeeping job in production. Runs every day at 1900.
=> feat: enable LibraGoB Housekeeping job in prod

apps/pre/pre-portal/demo.yaml
=> Add AMS env vars to demo

apps/darts-modernisation/base/kustomization.yaml, apps/darts-modernisation/demo/00/kustomization.yaml, apps/darts-modernisation/demo/base/kustomization.yaml
=> deploy only to demo 00

apps/juror/juror-api/ithc.yaml, apps/juror/juror-bureau/ithc.yaml, apps/juror/juror-pnc/ithc.yaml, apps/juror/juror-public/ithc.yaml, apps/juror/juror-scheduler-api/ithc.yaml, apps/juror/juror-scheduler-execution/ithc.yaml
=> lock ITHC deployments

apps/vh/video-api/demo.yaml, apps/vh/video-api/image-policy.yaml
https://tools.hmcts.net/jira/browse/VIH-10554
Enable changes to made to demo environment without deploying to prod
=> VIH-10554 Demo Video Api

apps/met/batch-jobs/test.yaml
=> fix: update housekeeping schedule

apps/vh/video-api/demo.yaml, apps/vh/video-api/image-policy.yaml
=> Reverted to Prod

apps/vh/video-api/demo.yaml
=> Updated demo.yml to refer prod ACR image

apps/vh/video-web/image-policy.yaml
=> Update image-policy.yaml - refer to PR regex

apps/met/batch-jobs/test.yaml
N/A
Update schedule to run at 1900 daily in test.
=> fix: update LibraGoB Test Housekeeping schedule

apps/vh/video-web/image-policy.yaml
=> Update image-policy to refer to PR regex

apps/juror/juror-pnc/ithc.yaml, apps/juror/juror-pnc/prod.yaml, apps/juror/juror-pnc/stg.yaml
update tran code for juror pnc
=> update tran code for juror pnc

apps/juror/juror-api/ithc.yaml, apps/juror/juror-bureau/ithc.yaml, apps/juror/juror-pnc/ithc.yaml, apps/juror/juror-public/ithc.yaml, apps/juror/juror-scheduler-api/ithc.yaml, apps/juror/juror-scheduler-execution/ithc.yaml
Update and 're-lock' ITHC images
=> update ithc images

apps/juror/juror-pnc/stg.yaml
=> update stg urls

apps/toffee/identity/apple-azure-identity.yaml
=> Fix apple pod identity

apps/pip/frontend/test.yaml
https://tools.hmcts.net/jira/browse/PUB-2122
Add image
=> PUB-2122 - Add image

apps/darts-modernisation/test/base/darts-api-function.enc.yaml
=> Fixing encrypted secret for KEDA on DARTS test env

apps/darts-modernisation/test/base/kustomization.yaml
=> Use secret resource on DARTS test env

apps/met/themis-fe/test.yaml
=> Update image version to 1.16.0

apps/pip/channel-management/test.yaml, apps/pip/frontend/test.yaml
=> Pub 2122 - Add image

apps/juror/juror-public/ithc.yaml
update public for secure cookies
=> update public for secure cookies

apps/jenkins/jenkins/ptlsbox/jenkins-azure-vm-agent.yaml
https://tools.hmcts.net/jira/browse/DTSPO-17285
Add alpha release to Jenkins ptlsbox to test latest build
=> Add alpha release to Jenkins ptlsbox to test latest build

apps/met/themis-fe/prod.yaml
=> feat: reduce libragob replicas to 0

apps/met/themis-fe/prod.yaml
=> fix: replicas 0 -> 4

apps/juror/juror-api/ithc.yaml, apps/juror/juror-bureau/ithc.yaml
update api and bureau to latest in ithc
=> update api and bureau to latest in ithc

apps/juror/juror-api/ithc.yaml, apps/juror/juror-bureau/ithc.yaml
=> juror: ithc update bureau & api

apps/neuvector/neuvector/neuvector.yaml
[DTSPO-17301](https://tools.hmcts.net/jira/browse/DTSPO-17301)
=> Update neuvector to latest version

apps/met/themis-fe/prod.yaml
=> Update prod.yaml - Replicas 4 -> 0

apps/met/themis-fe/prod.yaml
=> Update prod.yaml - Replicas 0 -> 4

apps/pip/channel-management/test.yaml, apps/pip/frontend/test.yaml
Removed outdated images in test env
=> Removed outdated images in test env

apps/darts-modernisation/darts-api/demo.yaml
=> DARTS temp fix demo version

apps/juror/juror-api/demo.yaml, apps/juror/juror-bureau/demo.yaml, apps/juror/juror-pnc/demo.yaml, apps/juror/juror-public/demo.yaml, apps/juror/juror-scheduler-api/demo.yaml, apps/juror/juror-scheduler-execution/demo.yaml
=> juror: update demo locked images

apps/juror/juror-api/juror-api.yaml, apps/juror/juror-bureau/juror-bureau.yaml, apps/juror/juror-pnc/juror-pnc.yaml, apps/juror/juror-public/juror-public.yaml, apps/juror/juror-scheduler-api/juror-scheduler-api.yaml, apps/juror/juror-scheduler-execution/juror-scheduler-execution.yaml
=> juror: first hpa config

apps/juror/juror-pnc/juror-pnc.yaml, apps/juror/juror-scheduler-api/juror-scheduler-api.yaml, apps/juror/juror-scheduler-execution/juror-scheduler-execution.yaml
=> juror: disable hpa on certain apps

apps/darts-modernisation/darts-api/darts-api.yaml
N/A
Giving the KEDA ATS process more memory.
=> DARTS KEDA function memory increase

apps/pip/frontend/test.yaml, apps/pip/publication-services/test.yaml
https://tools.hmcts.net/jira/browse/PUB-2122
Fix issue with images on the test env### Change description ###
=> PUB-2122 Fix issue with images on the test env

apps/darts-modernisation/darts-api/demo.yaml
Reverting hardcoded docker image
=> Revert the hardcoded docker image

apps/jenkins/jenkins/ptlsbox/jenkins.yaml
https://tools.hmcts.net/jira/browse/DTSPO-16590
Update jenkin to 01
=> DTSPO-16590 - update jenkins to 01

apps/juror/juror-api/demo.yaml, apps/juror/juror-bureau/demo.yaml, apps/juror/juror-pnc/demo.yaml, apps/juror/juror-public/demo.yaml, apps/juror/juror-scheduler-api/demo.yaml, apps/juror/juror-scheduler-execution/demo.yaml
=> juror: update demo

apps/jenkins/jenkins/ptlsbox/jenkins.yaml
Reverts hmcts/sds-flux-config#4526
=> Revert "DTSPO-16590 - update jenkins to 01"

clusters/dev/base/kustomization.yaml
Number of apps are not running state, turning them off to continue with upgrade
=> DTSPO-16591 - tuning off all the failed pods which has pdb set to 0

clusters/dev/base/kustomization.yaml
Reverts hmcts/sds-flux-config#4533
=> Revert "DTSPO-16591 - tuning off all the failed pods which has pdb set to 0"

apps/admin/traefik2/sbox/00-traefik2.yaml, apps/admin/traefik2/sbox/01-traefik2.yaml
DTSPO-16270
Set traefik logs to debug for testing
=> Set traefik logs to debug for testing

clusters/ithc/base/kustomization.yaml
Reverts hmcts/sds-flux-config#4536
=> Revert "DTSPO-16591 - turn off Juror and darts because of failed pods"

clusters/demo/base/kustomization.yaml
Turn off darts and mytime apps
=> DTSPO-16591 - turning off darts and my-time

apps/juror/juror-api/demo.yaml, apps/juror/juror-bureau/demo.yaml, apps/juror/juror-scheduler-api/demo.yaml
=> juror: update demo images

apps/juror/juror-api/demo.yaml
=> juror: update api demo image

apps/pip/account-management/test.yaml, apps/pip/channel-management/test.yaml, apps/pip/data-management/test.yaml, apps/pip/frontend/test.yaml, apps/pip/subscription-management/test.yaml
https://tools.hmcts.net/jira/browse/PUB-1936
Enable testing support API for test env
Remove outdated test env images
=> PUB-1936 Enable testing support API for test env

apps/my-time/my-time-api/my-time-api.yaml
=> DTSPO-16591 - trying to change pdb value

apps/darts-modernisation/darts-migration/darts-api-migration.yaml
Disabling poddistribution to continue with cluster upgrade
=> DTSPO-16591 - disable darts pdb

apps/pre/pre-portal/test.yaml
Disable PDB for test clusters to upgrade them.
=> DTSPO-16591 - pre - disable pdb for test clusters

apps/opal/opal-log-audit-service/stg.yaml
https://tools.hmcts.net/jira/browse/DTSPO-16589
disable OPAL pdb to continue with cluster upgrade
=> DTSPO-16591 - disbale - opal - pdb

apps/juror/juror-bureau/demo.yaml
=> juror: update bureau image for demo

apps/met/themis-fe/prod.yaml, apps/met/themis-fe/themis-fe.yaml
N/A
Increase the number of pods from 4 to 8, and decrease the number of instances from 13 to 2.
=> feat: increase number of pods and reduce instance keys

apps/juror/juror-api/ithc.yaml
=> juror: force ithc redeploy

apps/juror/juror-api/demo.yaml, apps/juror/juror-bureau/demo.yaml, apps/juror/juror-pnc/demo.yaml, apps/juror/juror-public/demo.yaml, apps/juror/juror-scheduler-api/demo.yaml, apps/juror/juror-scheduler-execution/demo.yaml
=> juror: update all apps for demo

apps/juror/juror-pnc/demo.yaml
=> Juror demo pnc

apps/admin/traefik2/prod/00-traefik2.yaml, apps/admin/traefik2/prod/01-traefik2.yaml, apps/admin/traefik2/stg/00-traefik2.yaml, apps/admin/traefik2/stg/01-traefik2.yaml
DTSPO-16270
Traefik logging set to debug for prod troubleshooting
=> DTSPO-16270 - traefik logging set to debug for prod troubleshooting

apps/juror/juror-api/demo.yaml, apps/juror/juror-bureau/demo.yaml
Realigned Juror demo to juror master
=> Realigned Juror demo to juror master

apps/admin/traefik-crds-upgrade-v27.0.2/kustomization.yaml, apps/admin/traefik-crds-upgrade-v27.0.2/kustomize.yaml, apps/admin/traefik2/sbox/00-traefik2.yaml, apps/admin/traefik2/sbox/01-traefik2.yaml, clusters/sbox/base/kustomization.yaml
https://tools.hmcts.net/jira/browse/DTSPO-17534
- Upgrade Traefik in sbox to v27.0.2
=> DTSPO-17524: traefik upgrade to v27.0.2 for sbox

apps/met/themis-fe/prod.yaml
=> Update prod.yaml to 1.19.0

apps/met/themis-fe/test.yaml
=> Update test.yaml to v 1.20.0

apps/darts-modernisation/demo/base/darts-api-function.enc.yaml, apps/darts-modernisation/demo/base/kustomization.yaml
=> Adding encrypted secret for KEDA on DARTS demo env

apps/darts-modernisation/demo/base/darts-api-function.enc.yaml
=> Fixing DARTS demo KEDA secret

apps/juror/juror-pnc/ithc.yaml
=> pnc ithc pr146

apps/admin/traefik2/demo/00-traefik2.yaml, apps/admin/traefik2/demo/01-traefik2.yaml, apps/admin/traefik2/dev/00-traefik2.yaml, apps/admin/traefik2/dev/01-traefik2.yaml, apps/admin/traefik2/ithc/00-traefik2.yaml, apps/admin/traefik2/ithc/01-traefik2.yaml, apps/admin/traefik2/ptl/00-traefik.yaml, apps/admin/traefik2/ptlsbox/00-traefik.yaml, clusters/demo/base/kustomization.yaml, clusters/dev/base/kustomization.yaml, clusters/ithc/base/kustomization.yaml, clusters/ptl/base/kustomization.yaml, clusters/ptlsbox/base/kustomization.yaml
upgrade traefik to version 27.0.2
=> update traefik to version 27.0.2

apps/juror/juror-pnc/ithc.yaml
=> pnc back to 2 replicas

apps/pre/pre-api/pre-api.yaml, apps/pre/pre-api/stg.yaml, apps/pre/pre-portal/pre-portal.yaml, apps/pre/pre-portal/stg.yaml
autoscaling config for pre app.
=> Configure autoscaling for PRE

apps/juror/juror-pnc/ithc.yaml
=> bump ithc version of pnc

apps/juror/juror-pnc/ithc.yaml
=> reinstate retry

apps/admin/traefik2/demo/00-traefik2.yaml
=> increase read timeout traefik

apps/darts-modernisation/darts-api/demo.yaml, apps/darts-modernisation/darts-api/ithc.yaml, apps/darts-modernisation/darts-api/prod.yaml, apps/darts-modernisation/darts-api/stg.yaml, apps/darts-modernisation/darts-api/test.yaml
https://tools.hmcts.net/jira/browse/DMP-3014
=>  DMP-3014 added arm url config

apps/admin/traefik2/demo/00-traefik2.yaml
=> temporarily reduce traefik to 1

apps/darts-modernisation/darts-api/stg.yaml
N/A
Temporary change to enable automated task mode on the DARTS API pods.
=> Enabling automated tasks mode for DARTS API on staging

apps/juror/juror-bureau/prod.yaml, apps/juror/juror-bureau/stg.yaml
=> juror: add env specific urls for ad

apps/juror/juror-pnc/ithc.yaml
=> unlock pnc in ITHC

apps/admin/traefik2/prod/00-traefik2.yaml, apps/admin/traefik2/prod/01-traefik2.yaml, clusters/prod/base/kustomization.yaml
=> upgrade traefik version

apps/juror/juror-api/demo.yaml, apps/juror/juror-bureau/demo.yaml, apps/juror/juror-pnc/demo.yaml, apps/juror/juror-public/demo.yaml, apps/juror/juror-scheduler-api/demo.yaml, apps/juror/juror-scheduler-execution/demo.yaml
=> update demo env

apps/juror/juror-api/test.yaml, apps/juror/juror-bureau/test.yaml, apps/juror/juror-pnc/test.yaml, apps/juror/juror-public/test.yaml, apps/juror/juror-scheduler-api/test.yaml, apps/juror/juror-scheduler-execution/test.yaml
=> juror: freeze deploys on test

apps/pre/pre-portal/prod.yaml
=> Update PRE Prod ingress host

apps/keda/keda/keda.yaml
This reverts commit 2213350efb1b6354fce391f3bc8165f9e27b2909.
=> Revert "Update Helm release keda to v2.14.2 in keda (#4318)"

apps/keda/keda/keda.yaml, apps/keda/keda/ptlsbox.yaml, apps/keda/ptlsbox/base/kustomization.yaml
Reverts hmcts/sds-flux-config#4660
=> retest KEDA update

.github/workflows/pr-summary.yml
add AEP PR Summary
- Created a new workflow file named `pr-summary.yml` in the `.github/workflows` directory
- The workflow is triggered on pull requests to the `master` branch and via manual triggers
- The workflow includes a job named `review` that runs on the `ubuntu-latest` operating system
- Within the `review` job, steps are defined to checkout code, create a diff file, generate a response using environment variables, and then send the response via API
- A step is added to save the response as a variable and then update the pull request body with the response using GitHub script in the last step
=> add AEP PR Summary

apps/juror/juror-api/demo.yaml, apps/juror/juror-bureau/demo.yaml, apps/juror/juror-public/demo.yaml, apps/juror/juror-scheduler-api/demo.yaml, apps/juror/juror-scheduler-execution/demo.yaml
- Updated the Java image version to prod-430fe95-20240509163033.
- Updated the `ingressHost` to juror-api.demo.platform.hmcts.net.
- Updated the Nodejs image version to prod-7d33760-20240510071729.
- Updated the `ingressHost` to juror.demo.apps.hmcts.net.
- Updated the Nodejs image version to prod-d36bd82-20240510073338.
- Updated the `ingressHost` to juror-public.demo.apps.hmcts.net.
- Updated the Java image version to prod-760c972-20240509082047.
- Updated the `ingressHost` to juror-scheduler-api.demo.platform.hmcts.net.
- Updated the Java image version to prod-54d7c12-20240508165808.
- Updated the `ingressHost` to juror-scheduler-execution.demo.platform.hmcts.net.
=> juror: update demo env

apps/met/themis-fe/prod.yaml
- Changed the number of replicas from 8 to 0.
=> feat: reduce replica count for libragob prod

apps/met/themis-fe/prod.yaml
- Changed the number of replicas from 0 to 8 🔄
=> feat: increase replica count for libragob prod 0->8

apps/darts-modernisation/darts-api/stg.yaml
N/A
- Removed the `AUTOMATED_TASK_MODE` configuration with the value `true`.
=> Reverting automated tasks mode in DARTS API on staging

apps/admin/traefik2/prod/00-traefik2.yaml, apps/admin/traefik2/prod/01-traefik2.yaml
DTSPO-16270
DTSPO-16270 - traefik prod debug logging removed
=> DTSPO-16270 - traefik prod debug logging removed

apps/darts-modernisation/darts-portal/stg.yaml
N/A
As title
yaml
stg.yaml
- Added DARTS_PORTAL_ALLOW_STUB_DATA: true to enable stub data in the DARTS portal for testing.
```
=> DARTS portal - allow stub data in staging

apps/toffee/recipe-backend/prod.yaml, apps/toffee/recipe-receiver/prod.yaml
=> Trigger toffee restart

apps/juror/juror-api/test.yaml
- Updated the image tag for the Java container to prod-80aa422-20240515120635``` and ingressHost to ```juror-api.test.platform.hmcts.net``` 🛠️
=> juror: temp unlock api

apps/dynatrace/dynatrace-crds/kustomization.yaml, apps/dynatrace/dynatrace-operator.yaml
To be upgraded as part of patching: https://tools.hmcts.net/jira/browse/DTSPO-17585 
Similarly done in [hmcts/cnp-flux-config](https://github.com/hmcts/sds-flux-config/pull/4256/commits/c94b2e1e3af6b8972ece8577188f94408408ee66)
=> DTSPO-17585: Upgrade Dynatrace Oneagent & Operrator - SDS

apps/juror/juror-pnc/prod.yaml, apps/juror/juror-scheduler-execution/prod.yaml
=> Missing juror prod overrides

apps/dynatrace/dynatrace-crds/kustomization.yaml, apps/dynatrace/dynatrace-operator.yaml
DTSPO-17585
reverting https://github.com/hmcts/sds-flux-config/pull/4781
=>  DTSPO-17585 revert dynatrace upgrade

apps/met/themis-fe/test.yaml
=> Update test.yaml replicas to 0

apps/met/themis-fe/test.yaml
- Changed replicas from 0 to 1.
=> Update test.yaml replicas to 1

apps/met/themis-fe/test.yaml
- Updated the image version in `test.yaml` from `'sdshmctspublic.azurecr.io/themis/themis_sb_azure:1.23.0'` to `'sdshmctspublic.azurecr.io/themis/themis_sb_azure:1.24.0'` 🔄
=> Update test.yaml to version 1.24

apps/met/themis-fe/test.yaml
- Updated the `image` field to version `1.25.0` from `1.24.0`. 🔄
=> Update test.yaml to 1.25.0

apps/met/themis-fe/test.yaml
- The file `test.yaml` has been modified.
- The `image` tag has been changed from `sdshmctspublic.azurecr.io/themis/themis_sb_azure:1.25.0` to `sdshmctspublic.azurecr.io/themis/themis_sb_azure:1.22.0`.
=> Update test.yaml - revert to 1.22.0

apps/juror/juror-api/test.yaml, apps/juror/juror-bureau/test.yaml
=> Juror PVT Alignment

apps/met/themis-fe/test.yaml
- Updated the `image` field to use version `1.25.1` instead of `1.22.0` 🚀
=> Update test.yaml to 1.25.1

apps/met/themis-fe/test.yaml
- Updated the image version from 'sdshmctspublic.azurecr.io/themis/themis_sb_azure:1.25.1' to 'sdshmctspublic.azurecr.io/themis/themis_sb_azure:1.25.2' 🔄
=> Update test.yaml to 1.25.2

apps/juror/juror-api/demo.yaml, apps/juror/juror-bureau/demo.yaml, apps/juror/juror-pnc/demo.yaml, apps/juror/juror-public/demo.yaml, apps/juror/juror-scheduler-execution/demo.yaml
bump demo to latest versions
- `demo.yaml`:
- Updated the image for the Java service of the juror-api, juror-pnc, and juror-scheduler-execution apps to newer versions.
- Updated the image for the Node.js service of juror-bureau and juror-public apps to newer versions.
- Updated the ingressHost for all the apps mentioned above.
=> bump demo to latest versions

apps/juror/juror-api/test.yaml, apps/juror/juror-bureau/test.yaml
PVT Alignment
- Modified `test.yaml` in `juror-api` and `juror-bureau` directories
- Updated the image for `java` in `juror-api` from `prod-4242308-20240517175523` to `prod-9b8dbb6-20240521144211`
- Updated the image for `nodejs` in `juror-bureau` from `prod-cfd33a8-20240517172326` to `prod-c9509eb-20240521141215`
=> PVT Alignment

apps/juror/juror-api/demo.yaml, apps/juror/juror-bureau/demo.yaml, apps/juror/juror-bureau/test.yaml, apps/juror/juror-pnc/test.yaml, apps/juror/juror-public/demo.yaml, apps/juror/juror-public/test.yaml, apps/juror/juror-scheduler-api/test.yaml, apps/juror/juror-scheduler-execution/demo.yaml, apps/juror/juror-scheduler-execution/test.yaml
bump demo and test to latest versions
- Updated image for Java in `demo.yaml` for juror-api, juror-scheduler-execution, and juror-public
- Updated image for Nodejs in `demo.yaml` and `test.yaml` for juror-bureau and juror-public
- Updated image for Java in `test.yaml` for juror-pnc and juror-scheduler-api
=> bump demo and test to latest versions

apps/admin/kured/kured.yaml
As per patching rota: https://github.com/hmcts/bau-patching-rota/blob/main/rota.md
https://tools.hmcts.net/jira/browse/DTSPO-17588
Upgrades kured to latest version as per https://github.com/kubereboot/charts/releases
- Updated the version of the `kured` chart from 5.4.2 to 5.4.5. 🔄
=> DTSPO-17588: Upgrade kured to latest

apps/flux-system/automation/kustomization.yaml, apps/flux-system/automation/sdshmctsprivate-image-repo.yaml, apps/ipam/README.md
https://tools.hmcts.net/jira/browse/DTSPO-17730
Removed references to sdshmctsprivate
- Updated `apps/flux-system/automation/kustomization.yaml`
- Removed `sdshmctsprivate-image-repo.yaml`
- Updated the `annotationSelector` for the ImageRepository target
- Updated `apps/ipam/README.md`
- Updated the URL for accessing ipam from `https://ipam.platform.hmcts.net/` to `https://ipam.hmcts.net/`
=> DTSPO-17730 - removed refrences to sdshmctsprivate

apps/neuvector/neuvector/neuvector.yaml
https://tools.hmcts.net/jira/browse/DTSPO-17730
Update neuvector after releasing new version
- Updated neuvector.yaml```:
- Changed the version from 1.5.5 to 1.5.6.
=> DTSPO-17730 - update neuvector

apps/juror/juror-api/test.yaml, apps/juror/juror-bureau/test.yaml
Juror Test Alignment
- Updated `test.yaml` in `juror-api` and `juror-bureau` directories
- Updated image version for Java and Nodejs services
- Image version changed from `prod-9b8dbb6-20240521144211` to `prod-28c5c18-20240522172627` for `juror-api`
- Image version changed from `prod-b3336f4-20240521194537` to `prod-739f4be-20240522163253` for `juror-bureau`
=> Juror Test Alignment

apps/darts-modernisation/darts-api/demo.yaml, apps/darts-modernisation/darts-api/test.yaml, apps/darts-modernisation/darts-gateway/demo.yaml, apps/darts-modernisation/darts-gateway/test.yaml, apps/darts-modernisation/darts-portal/demo.yaml
- `demo.yaml`, `test.yaml` (darts-api, darts-gateway): Updated environment variables including DARTS_GATEWAY_URL, DARTS_LOG_LEVEL, and APPLICATIONINSIGHTS_INSTRUMENTATION_LOGGING_LEVEL
- `demo.yaml`, `test.yaml` (darts-portal): Updated environment variables including RESTART_ME, and removed replicas configuration.
=> Align flux config for test environment

apps/pip/frontend/demo.yaml
https://tools.hmcts.net/jira/browse/PUB-2467
Update demo image to link to FaCT
- Updated the `nodejs` image to `sdshmctspublic.azurecr.io/pip/frontend:pr-1281-0620c74-20240522162521` 🚀
=> PUB-2467 Update demo image to link to FaCT

apps/darts-modernisation/darts-automated-tasks/demo.yaml, apps/darts-modernisation/darts-automated-tasks/ithc.yaml, apps/darts-modernisation/darts-automated-tasks/prod.yaml, apps/darts-modernisation/darts-automated-tasks/stg.yaml, apps/darts-modernisation/darts-automated-tasks/test.yaml
- Updated demo.yaml```, ```ithc.yaml```, ```prod.yaml```, ```stg.yaml```, and ```test.yaml``` in the `darts-automated-tasks` directory to include the `ARM_URL` parameter with its respective URL.
- The URLs were updated to:  
+ ```demo.yaml``` - `https://www.test.court-tribunal-records-archive.service.justice.gov.uk`
+ ```ithc.yaml``` - `http://darts-stub-services.ithc.platform.hmcts.net`
+ ```prod.yaml``` - `https://www.court-tribunal-records-archive.service.justice.gov.uk`
+ ```stg.yaml``` - `http://darts-stub-services.staging.platform.hmcts.net`
+ ```test.yaml``` - `http://darts-stub-services.test.platform.hmcts.net`
=> Dynamic ARM URL

apps/pre/pre-portal/stg.yaml
[S28-2756](https://tools.hmcts.net/jira/browse/S28-2756)
- Removed B2C_APP_CLIENT_ID, B2C_BASE_URL, and B2C_END_SESSION_ENDPOINT environment variables.
- Added B2C_APP_CLIENT_ID: d20a7462-f222-46b8-a363-d2e30eb274eb environment variable.
=> Use stg B2C in PRE stg env

apps/juror/juror-api/demo.yaml, apps/juror/juror-api/test.yaml, apps/juror/juror-bureau/demo.yaml, apps/juror/juror-bureau/test.yaml, apps/juror/juror-pnc/test.yaml, apps/juror/juror-public/demo.yaml, apps/juror/juror-public/test.yaml, apps/juror/juror-scheduler-api/demo.yaml, apps/juror/juror-scheduler-api/test.yaml, apps/juror/juror-scheduler-execution/test.yaml
- Updated image for juror-api demo.yaml from prod-38963c7-20240524100811 to prod-06b2ee4-20240528171627
- Updated image for juror-api test.yaml from prod-cb54a05-20240523144752 to prod-06b2ee4-20240528171627
- Updated image for juror-bureau demo.yaml from prod-6f83b10-20240528085332 to prod-ec5280a-20240529070913
- Updated image for juror-bureau test.yaml from prod-7e19dfd-20240523151517 to prod-ec5280a-20240529070913
- Updated image for juror-pnc test.yaml from prod-dca116c-20240520121719 to prod-02bedd7-20240527062614
- Updated image for juror-public demo.yaml from prod-6744fd4-20240524160324 to prod-35d9e90-20240528155654
- Updated image for juror-public test.yaml from prod-fce20c7-20240522082127 to prod-35d9e90-20240528155654
- Updated image for juror-scheduler-api demo.yaml from …
=> juror: update demo & test

apps/juror/juror-bureau/demo.yaml, apps/juror/juror-bureau/ithc.yaml, apps/juror/juror-bureau/stg.yaml, apps/juror/juror-bureau/test.yaml
- Added `SKIP_SSO: true` to the environment configuration.
- Added `SKIP_SSO: true` to the environment configuration.
- Added `SKIP_SSO: true` to the environment configuration.
- Added `SKIP_SSO: true` to the environment configuration.
=> juror: add sso skip to lower envs

apps/dynatrace/dynatrace-crds-upgrade-1.1.0/kustomization.yaml, apps/dynatrace/dynatrace-crds-upgrade-1.1.0/kustomize.yaml, apps/dynatrace/dynatrace-operator-upgrade-1.1.0.yaml, apps/dynatrace/stg/00/kustomization.yaml, clusters/stg/00/kustomization.yaml
https://tools.hmcts.net/jira/browse/DTSPO-17585
Testing on STG to see if the version upgrades without any issues
- **New file:** This file specifies the resources required for the Dynatrace CRDs upgrade to version 1.1.0.
- **New file:** Specifies the Kustomization for the Dynatrace CRD resources upgrade to version 1.1.0, with an interval of 10 minutes.
- **New file:** Specifies the HelmRelease for the Dynatrace operator upgrade to version 1.1.0, with an interval of 5 minutes.
- **Updated:** Added a patch for the path to the Dynatrace operator upgrade to version 1.1.0.
- **Updated:** Added a patch for the path to the Dynatrace CRDs upgrade to version 1.1.0.
=> DTSPO-17585: Dynatrace Test 1.1.0

apps/pip/frontend/prod.yaml
N/A
Restart prod pip
- Added a new environment variable `RESTART_PROD` set to `true`.
=> Restart prod pip

apps/juror/juror-api/demo.yaml, apps/juror/juror-api/test.yaml, apps/juror/juror-bureau/demo.yaml, apps/juror/juror-bureau/test.yaml, apps/juror/juror-public/demo.yaml, apps/juror/juror-public/test.yaml, apps/juror/juror-scheduler-api/demo.yaml, apps/juror/juror-scheduler-api/test.yaml, apps/juror/juror-scheduler-execution/demo.yaml, apps/juror/juror-scheduler-execution/test.yaml
update demo and test
- Updated image version for juror-api/demo.yaml and juror-api/test.yaml
- Updated image version for juror-bureau/demo.yaml and juror-bureau/test.yaml
- Updated image version for juror-public/demo.yaml and juror-public/test.yaml
- Updated image version for juror-scheduler-api/demo.yaml and juror-scheduler-api/test.yaml
- Updated image version for juror-scheduler-execution/demo.yaml and juror-scheduler-execution/test.yaml
=> Juror update demo and test

apps/neuvector/neuvector/ithc/ithc.yaml, apps/neuvector/neuvector/stg/stg.yaml, apps/neuvector/neuvector/test/test.yaml, apps/neuvector/patching-crds1/kustomization.yaml, apps/neuvector/patching-crds1/kustomize.yaml, clusters/ithc/base/kustomization.yaml, clusters/stg/base/kustomization.yaml, clusters/test/base/kustomization.yaml
https://tools.hmcts.net/jira/browse/DTSPO-17592
patching neuvector non-prod
- Added chart spec with version 1.5.8.
- Added chart spec with version 1.5.8.
- Added chart spec with version 1.5.8.
- Added new file specifying API versions, kinds, resources, and paths.
- Added new file specifying API versions, kinds, metadata, and specifications.
- Updated file paths.
- Updated file path.
- Updated file path.
=> Update neuvector version for nonprod

apps/juror/juror-api/test.yaml
- Added a list of keyVaults and their secrets to the `test.yaml` file in the `juror-api` directory. This includes aliases for various secrets such as `AppInsightsInstrumentationKey`, `DB_URL`, `JWT_SECRET_BUREAU`, etc.
=> juror: nle update for test env

apps/juror/juror-api/test.yaml
- Changed the image value from \"sdshmctspublic.azurecr.io/juror/api:prod-255d550-20240531174011\" to \"sdshmctspublic.azurecr.io/juror/api:prod-f4402b3-20240603102107\"
=> juror: test image update

apps/juror/juror-api/test.yaml
- In `test.yaml`, the image version for the `java` service has been updated to `prod-da25f68-20240603155311`.
- The environment variable `api-POSTGRES-PASS` has been renamed to `api-POSTGRES-PASS-TEMP`.
=> juror: switch to using test

apps/juror/juror-api/prod.yaml, apps/juror/juror-api/test.yaml
Juror flyway split
- `apps/juror/juror-api/prod.yaml`
- `apps/juror/juror-api/test.yaml`
- Added `FLYWAY_LOC_OVERRIDE: db/migrationv2` to the environment in prod.yaml.
- Updated the image to `sdshmctspublic.azurecr.io/juror/api:prod-94d3366-20240604132235` in test.yaml.
- Added `FLYWAY_LOC_OVERRIDE: db/migrationv2` to the environment in test.yaml.
- Added `ingressHost: juror-api.test.platform.hmcts.net` to the values in test.yaml.
=> Juror flyway split

apps/dynatrace/base/kustomize-upgrade.yaml, apps/dynatrace/dynatrace-crds-upgrade-1.1.0/kustomization.yaml, apps/dynatrace/dynatrace-crds-upgrade/kustomization.yaml, apps/dynatrace/dynatrace-operator-upgrade.yaml, apps/dynatrace/stg/00/kustomization.yaml
https://tools.hmcts.net/jira/browse/DTSPO-17585
try version 1.0.1
- Modified `kustomize-upgrade.yaml`:
- Updated the path from `./apps/dynatrace/dynatrace-crds-upgrade-1.1.0` to `./apps/dynatrace/dynatrace-crds-upgrade`.
- Renamed `dynatrace-crds-upgrade-1.1.0/kustomization.yaml` to `dynatrace-crds-upgrade/kustomization.yaml`:
- Updated the URL in the resources section from v1.1.0 to v1.0.1.
- Renamed `dynatrace-operator-upgrade-1.1.0.yaml` to `dynatrace-operator-upgrade.yaml`:
- Updated the version from 1.1.0 to 1.0.1.
- Modified `00/kustomization.yaml`:
- Updated the path from `././dynatrace-operator-upgrade-1.1.0.yaml` to `././dynatrace-operator-upgrade.yaml`.
=> Change version to troubleshoot and rename files

apps/darts-modernisation/darts-api/darts-api.yaml
N/A
As title
- Updated `darts-api.yaml`
- Added `maxReplicaCount: 5` 🚀
=> Increasing darts-api KEDA function maxReplicaCount to 5

apps/darts-modernisation/darts-portal/darts-portal.yaml
- Added environment variable DEBUG with value express-session. 🛠️
=> DARTS portal session debug

apps/pip/frontend/test.yaml
https://tools.hmcts.net/jira/browse/PUB-2485
Deploy WAF Rule changes to test env
- Added image configuration to specify the image for the frontend application.
- Updated replicas to 2.
- Modified the DATA_MANAGEMENT_URL environment variable to point to the test environment.
=> PUB-2485 Deploy WAF Rule changes to test env

apps/pip/frontend/test.yaml
https://tools.hmcts.net/jira/browse/PUB-2485
Removed frontend test image
- Removed one replica from the nodejs section.
- Removed the specific image reference.
- Updated the DATA_MANAGEMENT_URL to point to the test environment.
=> PUB-2485 Removed frontend test image

apps/juror/juror-api/test.yaml, apps/juror/juror-bureau/test.yaml, apps/juror/juror-pnc/test.yaml, apps/juror/juror-public/test.yaml, apps/juror/juror-scheduler-api/test.yaml, apps/juror/juror-scheduler-execution/test.yaml
- Updated apps/juror/juror-api/test.yaml:
- Updated the Java image from sdshmctspublic.azurecr.io/juror/api:prod-1332412-20240605133912 to sdshmctspublic.azurecr.io/juror/api:prod-0e42a79-20240610084805.
- Updated apps/juror/juror-bureau/test.yaml:
- Updated the Nodejs image from sdshmctspublic.azurecr.io/juror/bureau:prod-28c6755-20240531164917 to sdshmctspublic.azurecr.io/juror/bureau:prod-b72b9b9-20240610095842.
- Updated apps/juror/juror-pnc/test.yaml:
- Updated the Java image from sdshmctspublic.azurecr.io/juror/pnc:prod-02bedd7-20240527062614 to sdshmctspublic.azurecr.io/juror/pnc:prod-cea98a3-20240605110413.
- Updated apps/juror/juror-public/test.yaml:
- Updated the Nodejs image from sdshmctspublic.azurecr.io/juror/public:prod-39c60eb-20240531150507 to …
=> juror: update test images

apps/darts-modernisation/darts-portal/darts-portal.yaml
N/A
md
apps/darts-modernisation/darts-portal/darts-portal.yaml
- Removed the environment configuration for DEBUG and express-session
```
=> Reverting DARTS portal session debug

apps/mi/mi-adf-shir-2/prod.yaml
- Changed the image tag from \"prod-91ba39e-20240607154028\" to \"prod-91ba39e-20240312133745\" 🔄
=> Fix Prod SHIR 2 image version

apps/juror/juror-api/test.yaml, apps/juror/juror-bureau/test.yaml, apps/juror/juror-public/test.yaml, apps/juror/juror-scheduler-execution/test.yaml
- update images to latest master
- remove nle based secrets and the migration override
- Updated image version for juror-api/test.yaml from prod-0e42a79-20240610084805 to prod-1fcb9ff-20240610144424
- Updated image version for juror-bureau/test.yaml from prod-b72b9b9-20240610095842 to prod-fa556b6-20240611081052
- Updated image version for juror-public/test.yaml from prod-213f538-20240607154801 to prod-1d191a2-20240610115842
- Updated image version for juror-scheduler-execution/test.yaml from prod-a0132ed-20240606175242 to prod-c22aecf-20240611091755
=> juror: update test

apps/azure-devops/azure-devops-agent-keda/dev.yaml
[DTSPO-13833](https://tools.hmcts.net/jira/browse/DTSPO-13833)
changing dev mi to stg mi
=> DTSPO-13833-updating-dev-mi

apps/pip/frontend/demo.yaml
N/A
Change demo image back on pip
=> Updated demo image

apps/juror/juror-api/test.yaml
=> token extend on test

apps/juror/juror-api/test.yaml, apps/juror/juror-bureau/test.yaml, apps/juror/juror-scheduler-execution/test.yaml
bump test images
- Updated the image tag to `sdshmctspublic.azurecr.io/juror/api:prod-30515bf-20240612152625`
- Updated the image tag to `sdshmctspublic.azurecr.io/juror/bureau:prod-b24e62e-20240612130436`
- Set environment variable `SKIP_SSO` to `true`
- Updated the image tag to `sdshmctspublic.azurecr.io/juror/scheduler-execution:prod-48427a9-20240612153318`
=> bump test images

apps/juror/juror-scheduler-execution/ithc.yaml
temp try of image to ithc
- Updated the Java container image to 'sdshmctspublic.azurecr.io/juror/scheduler-execution:prod-c22aecf-20240611091755' 🐳.
=> temp try of image to ithc

apps/juror/juror-api/juror-api.yaml, apps/juror/juror-api/test.yaml
change token expiry
- Updated the image version to `prod-71d79d4-20240613121116`
- Changed `TOKEN_EXPIRY` value to `5h`
=> change token expiry

apps/juror/juror-scheduler-execution/ithc.yaml
try version from 6th June
- Updated the image version for java to `sdshmctspublic.azurecr.io/juror/scheduler-execution:prod-a0132ed-20240606175242` 🔄
=> try version from 6th June

apps/juror/juror-scheduler-execution/ithc.yaml
try next version
- Updated the image for the Java service to `sdshmctspublic.azurecr.io/juror/scheduler-execution:prod-c22aecf-20240611091755` 🐳.
=> try next version

apps/met/themis-fe/themis-fe.yaml
- Changed `TEMP_VAR` from `0` to `1`. 🔄
=> Update themis-fe.yaml (pod restart)

apps/juror/juror-scheduler-execution/ithc.yaml
put back to staging version
- Updated the `ingressHost` value to `juror-scheduler-execution.ithc.platform.hmcts.net` 🔄
=> put back to staging version

apps/jenkins/jenkins/ptl/jenkins-azure-vm-agent.yaml, apps/jenkins/jenkins/ptlsbox/jenkins-azure-vm-agent.yaml
https://tools.hmcts.net/jira/browse/DTSPO-17999
- Removes arm agent templates from Jenkins ptl and ptlsbox
- Changed file: jenkins-azure-vm-agent.yaml
- Removed configuration for \"cnp-jenkins-arm-builders\" and \"cnp-jenkins-builders-arm\" templates
- Updated template descriptions, labels, and configuration values for ARM64 build agents in both \"ptl/jenkins-azure-vm-agent.yaml\" and \"ptlsbox/jenkins-azure-vm-agent.yaml\"
=> Dtspo 17999 remove arm jenkins agents

apps/juror/juror-api/ithc.yaml, apps/juror/juror-bureau/ithc.yaml, apps/juror/juror-pnc/ithc.yaml, apps/juror/juror-public/ithc.yaml, apps/juror/juror-scheduler-api/ithc.yaml, apps/juror/juror-scheduler-execution/ithc.yaml
lock juror ithc
- Modified apps/juror/juror-api/ithc.yaml
- Updated the Java image to \"sdshmctspublic.azurecr.io/juror/api:prod-d1116ec-20240614161633\"
- Modified apps/juror/juror-bureau/ithc.yaml
- Updated the Node.js image to \"sdshmctspublic.azurecr.io/juror/bureau:prod-6a17bd3-20240617075816\"
- Modified apps/juror/juror-pnc/ithc.yaml
- Updated the Java image to \"sdshmctspublic.azurecr.io/juror/pnc:prod-e1c8c71-20240614060900\"
- Modified apps/juror/juror-public/ithc.yaml
- Updated the Node.js image to \"sdshmctspublic.azurecr.io/juror/public:prod-1d191a2-20240610115842\"
- Modified apps/juror/juror-scheduler-api/ithc.yaml
- Updated the Java image to \"sdshmctspublic.azurecr.io/juror/scheduler-api:prod-8037de2-20240612062147\"
- Modified …
=> lock juror ithc
