hmcts/sds-flux-config

- apps/darts-modernisation/darts-api/stg.yaml
DMP-3325
Fix ARM URL for ATS
- Added the environment block with the ARM_URL for the staging environment.
> dmp-3325: fix arm url for ATS

- apps/juror/juror-api/ithc.yaml
- apps/juror/juror-bureau/ithc.yaml
- apps/juror/juror-pnc/ithc.yaml
- apps/juror/juror-public/ithc.yaml
- apps/juror/juror-scheduler-api/ithc.yaml
- apps/juror/juror-scheduler-execution/ithc.yaml
unlock juror ithc
- ithc.yaml files for juror-api, juror-bureau, juror-pnc, juror-public, juror-scheduler-api, juror-scheduler-execution were modified to update the ingressHost with new domains for ithc platform.
- Updated the ingressHost in each file to point to the new domains for the ithc platform.
> unlock juror ithc

- apps/juror/juror-api/ithc.yaml
- apps/juror/juror-bureau/ithc.yaml
- apps/juror/juror-pnc/ithc.yaml
- apps/juror/juror-public/ithc.yaml
- apps/juror/juror-scheduler-api/ithc.yaml
- apps/juror/juror-scheduler-execution/ithc.yaml
unlock ithc for juror
- Updated ithc.yaml``` files for ```juror-api```, ```juror-bureau```, ```juror-pnc```, ```juror-public```, ```juror-scheduler-api```, and ```juror-scheduler-execution``` apps with new ```ingressHost``` values for the ITHC environment.
- Updated the image and ```ingressHost``` in the ```ithc.yaml``` files for the mentioned apps.
> unlock ithc for juror

- apps/juror/juror-api/demo.yaml
- apps/juror/juror-bureau/demo.yaml
- apps/juror/juror-pnc/demo.yaml
- apps/juror/juror-scheduler-api/demo.yaml
- apps/juror/juror-scheduler-execution/demo.yaml
- `demo.yaml` (juror-api): Updated Java image version to prod-805e416-20240620144803 and ingressHost to juror-api.demo.platform.hmcts.net
- `demo.yaml` (juror-bureau): Updated Nodejs image version to prod-7b2e7f3-20240621065920 and ingressHost to juror.demo.apps.hmcts.net
- `demo.yaml` (juror-pnc): Updated Java image version to prod-1ebadf8-20240620130057 and ingressHost to juror-pnc.demo.platform.hmcts.net
- `demo.yaml` (juror-scheduler-api): Updated Java image version to prod-d3dee41-20240619192634 and ingressHost to juror-scheduler-api.demo.platform.hmcts.net
- `demo.yaml` (juror-scheduler-execution): Updated Java image version to prod-727d705-20240620173522 and ingressHost to juror-scheduler-execution.demo.platform.hmcts.net
> juror: demo update

- apps/juror/juror-api/test.yaml
- apps/juror/juror-bureau/test.yaml
- apps/juror/juror-pnc/test.yaml
- apps/juror/juror-public/test.yaml
- apps/juror/juror-scheduler-api/test.yaml
- apps/juror/juror-scheduler-execution/test.yaml
- Updated test.yaml files in various directories within the juror application
- Updated image and ingress host for juror-api, juror-bureau, juror-pnc, juror-public, juror-scheduler-api, and juror-scheduler-execution applications.
> juror: remove test locking

- apps/met/themis-fe/test.yaml
- File **test.yaml**:
- Updated the image version from 'sdshmctspublic.azurecr.io/themis/themis_sb_azure:1.25.2' to 'sdshmctspublic.azurecr.io/themis/themis_sb_azure:1.26.0'.
> Update test.yaml to version 1.26.0

- apps/pre/pre-api/stg.yaml
Needed for this PR about to go in: https://github.com/hmcts/pre-api/pull/559/files 
- Added environment variable `PLATFORM_ENV_TAG` with the value \"Staging\" 🚀
> Add new env tag to pre-api for ams changes

- apps/met/themis-fe/themis-fe.yaml
POD restarts 27/06/24
- Changed the value of `TEMP_VAR` from `1` to `0`. 🔄
> POD Restart 27/06/2024

- apps/darts-modernisation/demo/00/kustomization.yaml
- apps/darts-modernisation/stg/00/kustomization.yaml
- Removed the path `././darts-proxy/demo.yaml`.
- Removed the path `././darts-proxy/stg.yaml`.
> remove proxy deployment as hosting is now via lb

- apps/darts-modernisation/darts-api/demo.yaml
- apps/darts-modernisation/darts-api/prod.yaml
DMP-3372
Update ARM URL for KEDA on Demo and PROD
- Updated `demo.yaml` in `darts-api`:
- Added a new function with an image and environment variables.
- Updated `prod.yaml` in `darts-api`:
- Added an environment variable `ARM_URL`.
> Dmp 3372 update arm url for keda

- apps/juror/juror-api/ithc.yaml
- Updated the version of the `java` image to `sdshmctspublic.azurecr.io/juror/api:pr-541-8da7aa5-20240627132719`.
> juror: update ithc api image

- apps/juror/juror-scheduler-execution/ithc.yaml
- Updated the environment variable `BAIS_PORT` to `2220` and added a new `environment` field with the same `BAIS_PORT` setting 🔄
> Juror break ithc bais

- apps/juror/juror-scheduler-execution/ithc.yaml
- Removed the environment configuration for BAIS_PORT.
> juror: unbreak bais

- apps/juror/juror-api/ithc.yaml
Update Juror API ITHC
- Updated the `java` image from `sdshmctspublic.azurecr.io/juror/api:pr-541-8da7aa5-20240627132719` to `sdshmctspublic.azurecr.io/juror/api:pr-541-e95fdad-20240701113008` 🔄
> Update Juror API ITHC

- apps/juror/juror-api/demo.yaml
- apps/juror/juror-bureau/demo.yaml
- apps/juror/juror-pnc/demo.yaml
- apps/juror/juror-public/demo.yaml
- apps/juror/juror-scheduler-execution/demo.yaml
update demo to latest
- Updated the image tag for the java container to prod-f8de700-20240701073641``` and the ingressHost to ```juror-api.demo.platform.hmcts.net```.
- Updated the image tag for the nodejs container to ```prod-5ad31bb-20240701110640``` and set ```SKIP_SSO: true``` in the environment.
- Updated the image tag for the java container to ```prod-c71b09d-20240701102144``` and set ```PNC_SERVICE_PNC_TRAN_CODE: ''``` in the environment.
- Updated the image tag for the nodejs container to ```prod-57c5e80-20240701064011``` and the ingressHost to ```juror-public.demo.apps.hmcts.net```.
- Updated the image tag for the java container to ```prod-d5ad846-20240701153720``` and the ingressHost to ```juror-scheduler-execution.demo.platform.hmcts.net```.
> update demo to latest

- apps/met/themis-fe/themis-fe.yaml
- Changed the value of TEMP_VAR from 0 to 1.
- No new feature added or removed.
> Update themis-fe.yaml - Bounce Pods

- apps/juror/juror-api/demo.yaml
- apps/juror/juror-bureau/demo.yaml
- apps/juror/juror-public/demo.yaml
- apps/juror/juror-scheduler-execution/demo.yaml
bump to latest versions
- Changed `demo.yaml` in `juror-api`, `juror-bureau`, `juror-public`, and `juror-scheduler-execution` apps
- Updated the image tags for Java and Node.js applications
- Updated the `ingressHost` for all apps
> bump to latest versions

- apps/met/themis-fe/themis-fe.yaml
- Updated file: themis-fe.yaml
- Updated logging_level_root from DEBUG to ERROR.
> Update themis-fe.yaml debug to ERROR

- apps/juror/juror-api/demo.yaml
- apps/juror/juror-bureau/demo.yaml
- apps/juror/juror-pnc/demo.yaml
- apps/juror/juror-public/demo.yaml
- apps/juror/juror-scheduler-api/demo.yaml
- apps/juror/juror-scheduler-execution/demo.yaml
unlock deployments to demo for Juror
- Updated demo.yaml in juror-api, juror-bureau, juror-pnc, juror-public, juror-scheduler-api, and juror-scheduler-execution.
- Changed the ingressHost for each service to point to the demo environment URLs for each app.
> unlock deployments to demo for Juror

- apps/darts-modernisation/darts-automated-tasks/darts-automated-tasks.yaml
- apps/darts-modernisation/darts-automated-tasks/demo.yaml
- apps/darts-modernisation/darts-automated-tasks/ithc.yaml
- apps/darts-modernisation/darts-automated-tasks/prod.yaml
- apps/darts-modernisation/darts-automated-tasks/sbox.yaml
- apps/darts-modernisation/darts-automated-tasks/stg.yaml
- apps/darts-modernisation/darts-automated-tasks/test.yaml
https://tools.hmcts.net/jira/browse/DMP-3124
As title
- darts-automated-tasks.yaml```: Added environment variables and disabled notification scheduler.
- ```demo.yaml```, ```ithc.yaml```, ```prod.yaml```, ```sbox.yaml```, ```stg.yaml```, ```test.yaml```: Removed specific environment-related variables.
> DARTS - Disabling notification scheduler on automated tasks pod

- apps/met/themis-fe/test.yaml
- In `test.yaml`, the image version has been updated from `1.26.0` to `1.26.1`.
> Update test.yaml to 1.26.1

- apps/met/batch-jobs/test.yaml
- Changed the schedule from \"*/5 * * * *\" to \"*/15 * * * *\" 🔄
> feat: update ams reporting for LibraGoB in prod to every 15 mins

- .gitignore
- apps/pre/pre-api-cron-cleanup-live-events/demo.yaml
- apps/pre/pre-api-cron-cleanup-live-events/image-policy.yaml
- apps/pre/pre-api-cron-cleanup-live-events/image-repo.yaml
- apps/pre/pre-api-cron-cleanup-live-events/pre-api-cron-cleanup-live-events.yaml
- apps/pre/pre-api-cron-cleanup-live-events/prod.yaml
- apps/pre/pre-api-cron-cleanup-live-events/stg.yaml
- apps/pre/pre-api-cron-cleanup-live-events/test.yaml
- apps/pre/pre-api/demo.yaml
- apps/pre/pre-api/prod.yaml
- apps/pre/pre-api/test.yaml
S28-2974
Adds config for a new cron job hosted within the pre-api code base to be called daily at 8pm
- Updated `.gitignore` file to include the `.iml` file and removed the `.DS_Store` file
- Added new files: `pre-api-cron-cleanup-live-events/demo.yaml`, `pre-api-cron-cleanup-live-events/image-policy.yaml`, `pre-api-cron-cleanup-live-events/image-repo.yaml`, `pre-api-cron-cleanup-live-events/prod.yaml`, `pre-api-cron-cleanup-live-events/stg.yaml`, `pre-api-cron-cleanup-live-events/test.yaml`, `pre-api-cron-cleanup-live-events/pre-api-cron-cleanup-live-events.yaml`, `pre-api/demo.yaml`, `pre-api/prod.yaml`, and `pre-api/test.yaml` files
- Configured the schedule and environment settings in the new `demo.yaml`, `prod.yaml`, `stg.yaml`, `test.yaml`, and …
> Config for new pre-api cron job

- apps/juror/juror-api/demo.yaml
- apps/juror/juror-api/ithc.yaml
lock ithc and demo to PR branch for letter testing
- `demo.yaml`: Added a new image for Java and updated the ingress host to `juror-api.demo.platform.hmcts.net`.
- `ithc.yaml`: Added a new image for Java and updated the ingress host to `juror-api.ithc.platform.hmcts.net`. Also added a new environment variable `EMPTY_VAR` with the value `one`.
> lock ithc and demo to PR branch for letter testing

- apps/juror/juror-api/demo.yaml
- apps/juror/juror-api/ithc.yaml
unlock ithc and demo after letter testing
- Updated the `ingressHost` from `juror-api.demo.platform.hmcts.net` to `juror-api.ithc.platform.hmcts.net`
- Updated the `ingressHost` from `juror-api.demo.platform.hmcts.net` to `juror-api.ithc.platform.hmcts.net`
- Added `EMPTY_VAR: one` to the environment variables
> unlock ithc and demo after letter testing

- apps/juror-digital/jd-public/prod.yaml
- apps/juror/juror-public/prod.yaml
> DRAFT - DO NOT MERGE YET - Reconfigure IngressHosts

- apps/jenkins/jenkins/jenkins-controller-version.yaml
- apps/jenkins/jenkins/ptlsbox/jenkins-controller-version.yaml
- Updated `jenkins-controller-version.yaml` in `apps/jenkins/` and `apps/jenkins/ptlsbox/`:
- Changed the Jenkins controller tag from `2.462-692` to `2.464-712` in both files.
- Removed unused code.
> Java upgrade for prod jenkins

- apps/pre/pre-api/stg.yaml
Use test storage accounts for staging api
- Added `AZURE_INGEST_SA: preingestsatest` and `AZURE_FINAL_SA: prefinalsatest` to the environment variables. 🔄
> Fix: PRE use test storage accounts

- CODEOWNERS
- apps/pdda/pdda-public-display-data-aggregator/image-repo.yaml
- apps/pdda/pdda-public-display-data-aggregator/pdda-public-display-data-aggregator.yaml
https://centralgovernmentcgi.atlassian.net/browse/PDDA-393
modified pdda component name
- [ No] Does this PR introduce a breaking change
- CODEOWNERS:
- Added an owner for the \"apps/pdda/\" directory.
- image-repo.yaml:
- Updated the image repository for \"pdda-public-display-data-aggregator\" to point to a new image location.
- pdda-public-display-data-aggregator.yaml:
- Changed the reference to the image for \"pdda-public-display-data-aggregator\" to use a new image location.
> changed name of pdda component

- apps/darts-modernisation/darts-gateway/stg.yaml
- Removed 1 replica for the `darts-gateway` service.
>  DMP-3354 restart gateway on stg

- apps/juror/juror-api/ithc.yaml
- apps/juror/juror-bureau/ithc.yaml
Deploy juror ithc
- Updated `ithc.yaml` in `juror-api` and `juror-bureau` directories
- In `juror-api`, the Java image version was changed to `pr-590-a97b91b-20240716114203`
- In `juror-bureau`, a Node.js image was added
- Environment variables were updated in both files
> Deploy juror ithc

- apps/juror/juror-api/demo.yaml
- apps/juror/juror-api/ithc.yaml
- apps/juror/juror-bureau/demo.yaml
- apps/juror/juror-bureau/ithc.yaml
Deploy lastest PRs to ITHC
- Modified demo.yaml``` and ```ithc.yaml``` under ```apps/juror/juror-api```: updated the image URLs and ingress hosts for Java application.
- Modified ```demo.yaml``` and ```ithc.yaml``` under ```apps/juror/juror-bureau```: updated the image URLs and ingress hosts for Node.js application.
> Deploy lastest PRs to ITHC

- apps/darts-modernisation/darts-gateway/stg.yaml
- apps/pdda/automation/kustomization.yaml
- apps/pdda/pdda-public-display-manager/image-policy.yaml
- apps/pdda/pdda-public-display-manager/image-repo.yaml
- apps/pdda/pdda-public-display-manager/pdda-public-display-manager.yaml
- apps/pdda/pdda-public-display-manager/stg.yaml
- apps/pdda/stg/base/kustomization.yaml
https://centralgovernmentcgi.atlassian.net/browse/PDDA-393
Added config for pdda-public-display-manager
- [ No] Does this PR introduce a breaking change
- Updated `apps/pdda/automation/kustomization.yaml`:
- Added image repository and policy for public display manager.
- Added `apps/pdda/pdda-public-display-manager/image-policy.yaml`:
- Added image policy for public display manager.
- Added `apps/pdda/pdda-public-display-manager/image-repo.yaml`:
- Added image repository for public display manager.
- Added `apps/pdda/pdda-public-display-manager/pdda-public-display-manager.yaml`:
- Added HelmRelease for public display manager with updated image reference and interval.
- Added …
> Added config for public-display-manager

- apps/juror/juror-api/prod.yaml
double timeout
- Changed `apps/juror/juror-api/prod.yaml`
- Changed `startupDelay` from 600 to 1200
- Updated `ingressHost` to `juror-api.platform.hmcts.net`
- Updated `SCHEDULER_SERVICE_HOST` to `juror-scheduler-api.platform.hmcts.net`
> double timeout

- apps/juror/juror-api/juror-api.yaml
- apps/juror/juror-api/prod.yaml
remove timeout
- juror-api.yaml:
- Removed the \"timeout\" field and specified the chart path as \"./stable/juror-api\".
- prod.yaml:
- Removed the \"startupDelay\" field under \"java\" and \"ingressHost\" field under \"values\", added \"SCHEDULER_SERVICE_HOST\" field under \"environment\" with value \"juror-scheduler-api.platform.hmcts.net\".
> remove timeout

- apps/juror/juror-api/stg.yaml
test in staging first
- `stg.yaml` 🔄 Added `TOKEN_EXPIRY` configuration with a value of `12h`.
> test in staging first

- apps/pip/channel-management/test.yaml
- apps/pip/data-management/test.yaml
- `test.yaml` in `pip/channel-management`:
- Added a new Java image `sdshmctspublic.azurecr.io/pip/channel-management:pr-366-6968457-20240716065415` and increased the number of replicas to 2.
- `test.yaml` in `pip/data-management`:
- Added a new Java image `sdshmctspublic.azurecr.io/pip/data-management:pr-606-a96204e-20240712124027` and increased the number of replicas to 2.
> PUB-2489 - test prs

- apps/juror/juror-api/prod.yaml
- apps/juror/juror-api/stg.yaml
https://centralgovernmentcgi.atlassian.net/browse/JM-7838 
apply token expiry  to prod for juror-api
- Updated **prod.yaml**:
- Added `TOKEN_EXPIRY: 12h` to the file
- Updated **stg.yaml**:
- Removed `TOKEN_EXPIRY: 12h` from the file
> apply token expiry  to prod for juror-api

- apps/pip/channel-management/test.yaml
- apps/pip/data-management/test.yaml
- test.yaml```:
- Removed a line specifying the number of replicas for the Java image sdshmctspublic.azurecr.io/pip/channel-management:pr-366-6968457-20240716065415 in the 'channel-management' test environment.
- Removed a line specifying the number of replicas for the Java image sdshmctspublic.azurecr.io/pip/data-management:pr-606-a96204e-20240712124027 in the 'data-management' test environment.
> PUB-2489-b - Remove test images

- apps/juror/juror-api/demo.yaml
- apps/juror/juror-api/ithc.yaml
- apps/juror/juror-bureau/demo.yaml
- apps/juror/juror-bureau/ithc.yaml
latest versions on PR
- `demo.yaml` in `apps/juror/juror-api/`:
- Updated the image version to `pr-604-674c0cc-20240718122914`.
- `ithc.yaml` in `apps/juror/juror-api/`:
- Updated the image version to `pr-604-674c0cc-20240718122914`.
- `demo.yaml` in `apps/juror/juror-bureau/`:
- Updated the image version to `pr-636-05fca4f-20240718112600`.
- `ithc.yaml` in `apps/juror/juror-bureau/`:
- Updated the image version to `pr-636-05fca4f-20240718112600`.
> latest versions on PR

- apps/pdda/pdda-public-display-data-aggregator/stg.yaml
changed pdda replica to 0
- [ X] commit messages are meaningful and follow good commit message guidelines
- [No ] Does this PR introduce a breaking change
- Added a new field `replicas: 0` under `values: java`
- Updated `ingressHost` to `pdda-public-display-data-aggregator.staging.platform.hmcts.net`
> added 0 replica

- apps/juror/juror-api/demo.yaml
- apps/juror/juror-api/ithc.yaml
- apps/juror/juror-bureau/demo.yaml
- apps/juror/juror-bureau/ithc.yaml
deploying latest stabilisation3 changes for testing
- Updated `demo.yaml` in `apps/juror/juror-api/` and `apps/juror/juror-bureau/`:
- Updated the image tags and ingress host for the demo environment.
- Updated `ithc.yaml` in `apps/juror/juror-api/` and `apps/juror/juror-bureau/`:
- Updated the image tags and ingress host for the ithc environment.
> deploying latest stabilisation3 changes

- apps/juror/juror-bureau/demo.yaml
- apps/juror/juror-bureau/ithc.yaml
---
- `demo.yaml` 🔄
- Updated the image version to `pr-644-19954cf-20240721174417` and modified the timestamp.
- `ithc.yaml` 🔄
- Updated the image version to `pr-644-19954cf-20240721174417` and modified the timestamp.
> Stabilisation3

- apps/met/themis-fe/themis-fe.yaml
Restart 22/07/2024
- Changed `TEMP_VAR` from `1` to `0`. 🔄
> Update themis-fe.yaml - restart 22/07/2024

- apps/jenkins/jenkins/ptl/jenkins-azure-vm-agent.yaml
- apps/jenkins/jenkins/ptlsbox/jenkins-azure-vm-agent.yaml
To be merged monday
- Changed `javaPath` from `java` to `/usr/lib/jvm/temurin-21-jdk-amd64/bin/java`.
- Changed `javaPath` from `java` to `/usr/lib/jvm/temurin-21-jdk-amd64/bin/java`.
> Upgrade jenkins agents prod

- apps/met/themis-fe/themis-fe.yaml
- Changed the value of `TEMP_VAR` from `1` to `0` ℹ️
> Update themis-fe.yaml - Restart 3 22/07/2024

- apps/juror/juror-api/demo.yaml
- apps/juror/juror-api/ithc.yaml
- apps/juror/juror-bureau/demo.yaml
- apps/juror/juror-bureau/ithc.yaml
Juror Stabilisation 3
- Updated image for juror-api demo.yaml and ithc.yaml with new image tag ending in \"3df107a-20240722100539\"
- Updated image for juror-bureau demo.yaml and ithc.yaml with new image tag ending in \"886e29d-20240722100836\"
> Juror Stabilisation 3

- apps/vh/admin-web/demo.yaml
- apps/vh/booking-queue-subscriber/demo.yaml
- apps/vh/video-api/demo.yaml
- apps/vh/video-web/demo.yaml
- `demo.yaml` (vh-admin-web, vh-booking-queue-subscriber, vh-video-api, vh-video-web):
- Added configuration to set replicas to 0 for Java services.
> Reducing pod count to 0 so I can run deployment against host

- apps/juror/juror-api/demo.yaml
- apps/juror/juror-api/ithc.yaml
- apps/juror/juror-bureau/demo.yaml
- apps/juror/juror-bureau/ithc.yaml
deployment of stabilisation3 changes into ITHC and Demo
- Updated the image tag to `pr-612-54a70b2-20240722111907`.
- Updated the ingress host to `juror-api.demo.platform.hmcts.net`.
- Updated the image tag to `pr-612-54a70b2-20240722111907`.
- Updated the ingress host to `juror-api.ithc.platform.hmcts.net`.
- Updated the image tag to `pr-644-ac7792a-20240722111938`.
- Updated the ingress host to `juror.demo.apps.hmcts.net`.
- Set environment variable `SKIP_SSO` to true.
- Updated the image tag to `pr-644-ac7792a-20240722111938`.
- Updated the ingress host to `juror.ithc.apps.hmcts.net`.
- Set environment variable `SKIP_SSO` to true.
> juror-deploys for stabilisation3

- apps/darts-modernisation/darts-api/test.yaml
- apps/darts-modernisation/darts-gateway/test.yaml
- apps/darts-modernisation/darts-portal/test.yaml
Updated Darts Test config for Azure AD B2C
- `test.yaml`:
- Updated `ACTIVE_DIRECTORY_B2C_BASE_URI` and `ACTIVE_DIRECTORY_B2C_AUTH_URI` values from the old URLs to the new URLs.
- Updated `ACTIVE_DIRECTORY_B2C_ON_MICROSOFT_URI` value from the old URL to the new URL.
- Updated `DARTS_AZUREAD_B2C_ORIGIN_HOST` value from the old URL to the new URL.
> update DARTS Test config for Azure AD B2C

- apps/juror/juror-api/test.yaml
reduce api to 0 in test
yaml
test.yaml
- Added configuration for disabling autoscaling by setting replicas to 0 and autoscaling enabled to false.
```
> reduce api to 0 in test

- apps/juror/juror-api/test.yaml
re enable api in test
- Removed the replicas``` and ```autoscaling``` configurations.
- Updated the ```TOKEN_EXPIRY``` to 5 hours.
> re enable api in test

- apps/pdda/pdda-public-display-data-aggregator/stg.yaml
removed autoscaling feature
- [No ] Does this PR introduce a breaking change
- Removed autoscaling configuration and set replicas to 0.
- Removed the ingressHost configuration for pdda-public-display-data-aggregator.staging.platform.hmcts.net.
> removed autoscaling

- apps/met/themis-fe/themis-fe.yaml
- File: themis-fe.yaml
- Changed TEMP_VAR from 0 to 1
> Update themis-fe.yaml - Restart 4 22/07/2024

- apps/toffee/sbox/base/slack-token.enc.yaml
https://tools.hmcts.net/jira/browse/DTSPO-15798
- update slack-token for toffee in sbox
- Updated the `created_at` and `lastmodified` fields with new date and time values.
- Updated the `enc` and `mac` values.
> DTSPO-15798 - Toffee sbox: update slack token

- apps/juror/juror-public/test.yaml
blank line change to force deploy
yaml
test.yaml
- Changed the image for the nodejs container to 'sdshmctspublic.azurecr.io/juror/public:pr-231-f6a1491-20240724093521'
```
> blank line change to force deploy

- apps/juror/juror-public/test.yaml
try this to force deployment
- Changed `minReadySeconds` from 30 to 45
- Added `autoscaling` configuration with `enabled: false` and `replicas: 1` ✨
> try this to force deployment

- apps/juror/juror-public/test.yaml
try startupDelay instead
- The file `test.yaml` in the `juror-public` directory has had changes made to it. The `minReadySeconds`, `autoscaling` parameters have been removed, and a new `startupDelay` parameter with a value of 30 has been added.
> try startupDelay instead

- apps/dynatrace/demo/00/kustomization.yaml
- apps/dynatrace/demo/01/kustomization.yaml
- apps/dynatrace/demo/base/dynakube-secret.enc.yaml
- apps/dynatrace/demo/base/dynakube.yaml
- apps/dynatrace/demo/base/kustomization.yaml
- clusters/demo/base/kustomization.yaml
[DTSPO-18295](https://tools.hmcts.net/jira/browse/DTSPO-18295)
Adds dynatrace to ss demo
- Added new files `kustomization.yaml` for `dynatrace` demo 00 and demo 01, listing the resources
- Added `dynakube-secret.enc.yaml` with encrypted data for dynakube and base kustomization for `dynatrace`
- Added `dynakube.yaml` file with DynaKube configuration for `dynatrace`
- Updated `kustomization.yaml` in `clusters/demo/base` to include `dynatrace` base kustomization file
> Adds Dynatrace to sds demo

- apps/juror/juror-public/test.yaml
try readinessDelay instead
- Changed the `readinessDelay` from 30 to 60. ⚙️
> try readinessDelay instead

- apps/juror/juror-public/test.yaml
force restart
- `test.yaml` 🛠️ Reduced the readiness delay from 60 to 30.
> force restart

- apps/toffee/sbox/base/kustomization.yaml
https://tools.hmcts.net/jira/browse/DTSPO-15798
- toffee sbox: add secret to kustomization
- Added `slack-token.enc.yaml` resource, and removed `identity/apple-azure-identity.yaml` and `broken-provider.yaml`.
> DTSPO-15798 - toffee sbox: add secret to kustomization

- apps/juror/juror-api/demo.yaml
- apps/juror/juror-api/ithc.yaml
- apps/juror/juror-bureau/demo.yaml
- apps/juror/juror-bureau/ithc.yaml
Deploying stabilisation5 release to ITHC and Demo (juror-api and juror-bureau only)
- Changed the image version to \"sdshmctspublic.azurecr.io/juror/api:pr-644-6fea0e0-20240725161921\" and updated the ingressHost to \"juror-api.demo.platform.hmcts.net\"
- Updated the image version to \"sdshmctspublic.azurecr.io/juror/api:pr-644-6fea0e0-20240725161921\" and modified the ingressHost to \"juror-api.ithc.platform.hmcts.net\"
- Added an environment variable \"EMPTY_VAR\" with the value \"one\"
- Changed the image version to \"sdshmctspublic.azurecr.io/juror/bureau:pr-665-a58dbe8-20240725151422\" and updated the ingressHost to \"juror.demo.apps.hmcts.net\"
- Added an environment variable \"SKIP_SSO\" with the value …
> Juror deployments

- apps/juror/juror-public/test.yaml
force again
yaml
apps/juror/juror-public/test.yaml
- Removed the \"replicas\" field from the spec section
```
> force again

- apps/juror/juror-bureau/demo.yaml
- apps/juror/juror-bureau/ithc.yaml
Juror bureau deployment to ITHC and Demo for stabilisation5
- Changed the image tag from \"pr-665-a58dbe8-20240725151422\" to \"pr-665-8eb06f6-20240726113251\"
- Changed the image tag from \"pr-665-a58dbe8-20240725151422\" to \"pr-665-8eb06f6-20240726113251\"
> juror-bureau deployment to ITHC and Demo

- apps/pre/pre-api/stg.yaml
- Added `MEDIA_SERVICE: MediaKind` to the spec section. 🚀
> Update pre-api to use MK in stg

- apps/juror/juror-api/prod.yaml
increase timeout
- Added a new configuration for `java` with a `startupDelay` of 600.
- Modified the `ingressHost` to `juror-api.platform.hmcts.net`.
> increase timeout

- apps/juror/juror-api/prod.yaml
decrease timeout
- Updated the `java` values to include `ingressHost: juror-api.platform.hmcts.net` 🚀
> decrease timeout

- apps/juror/juror-api/demo.yaml
- apps/juror/juror-api/ithc.yaml
juror-alignment
- Modified `demo.yaml` and `ithc.yaml` in `apps/juror/juror-api`:
- Updated the image version from `pr-644-bcd5d4f-20240726130544` to `pr-649-f83920d-20240729081305`
- Updated the `ingressHost` for both files.
> juror-alignment

- apps/juror/juror-api/test.yaml
flyway in pipeline instead
- Updated the `java` values by adding the `image` field with value `sdshmctspublic.azurecr.io/juror/api:pr-654-a59e4b8-20240729121348`.
> flyway in pipeline instead

- apps/juror/juror-api/test.yaml
test using flux ENV override
- Added a new environment variable `RUN_DB_MIGRATION_ON_STARTUP` and set its value to `false`.
- Updated the `TOKEN_EXPIRY` environment variable value to `5h`.
> test using flux ENV override

- apps/pdda/pdda-public-display-data-aggregator/stg.yaml
added default auto-scaling for pdda
- [ X] commit messages are meaningful and follow good commit message guidelines
- [ No] Does this PR introduce a breaking change
- Removed the autoscaling configuration for the \"pdda-public-display-data-aggregator\" release in the staging environment.
- Removed the replicas and autoscaling configurations for Java.
> added default autoscaling

- apps/juror/juror-api/test.yaml
just update test
- Updated the image tag from `pr-654-a59e4b8-20240729121348` to `pr-654-0c1e055-20240729134749` for the Java service.
- Modified the TOKEN_EXPIRY to 5h in the test environment.
> just update test

- apps/juror/juror-api/test.yaml
try setting like prod
- Added a new environment variable FLYWAY_LOC_OVERRIDE with the value db/migrationv2.
- Updated the test.yaml file to include the new environment variable.
> try setting like prod

- apps/juror/juror-api/test.yaml
Revert change needed for testing
- Removed the `RUN_DB_MIGRATION_ON_STARTUP` and `FLYWAY_LOC_OVERRIDE` environment variables.
- Updated the `image` and `ingressHost` values.
> Revert change needed for testing

- apps/pre/pre-api/stg.yaml
- Update pre-api to use AMS in stg
- Changed the value of MEDIA_SERVICE from \"MediaKind\" to \"AzureMediaService\" 🔄
> Update pre-api to use AMS in stg 

- apps/juror/juror-public/test.yaml
update VAR to force deploy
- Reduced the startupDelay from 10 to 5 ⬇️
> update VAR to force deploy

- apps/base/alert.yaml
https://tools.hmcts.net/jira/browse/DTSPO-15798
- add summary param to base flux notification alert resource
- Updated `alert.yaml`
- Added a `summary` field with the value `${CLUSTER_FULL_NAME}-aks`
> DTSPO-15798: Flux alerts add summary param to base

- apps/dynatrace/test/00/kustomization.yaml
- apps/dynatrace/test/01/kustomization.yaml
- apps/dynatrace/test/base/dynakube-secret.enc.yaml
- apps/dynatrace/test/base/dynakube.yaml
- apps/dynatrace/test/base/kustomization.yaml
- clusters/test/base/kustomization.yaml
https://tools.hmcts.net/jira/browse/DTSPO-18363
- add dynatrace for ss-test
The following changes were made in this pull request:
- Created new files:
- `apps/dynatrace/test/00/kustomization.yaml`
- `apps/dynatrace/test/01/kustomization.yaml`
- `apps/dynatrace/test/base/dynakube-secret.enc.yaml`
- `apps/dynatrace/test/base/dynakube.yaml`
- `apps/dynatrace/test/base/kustomization.yaml`
- Updated file:
- `clusters/test/base/kustomization.yaml` to include `apps/dynatrace/base/kustomize.yaml` as a resource.
> Dynatrace - test: add dynatrace for ss-test

- clusters/prod/base/kustomization.yaml
Approved under CHG5017419
VH team to test and confirm whether issue can be replicated after this.
Temporary disabling in change window.
- **clusters/prod/base/kustomization.yaml** 🔄
- Removed the NeuVector application and added the VH application.
> CHG5017419 - temp disabling for incident

- apps/juror/juror-public/test.yaml
force restart again
- test.yaml
- Added a new environment variable DUMMY_ENV_VAR``` with a value of ```1``` to the ```nodejs``` image configuration.
> force restart again

- clusters/prod/base/kustomization.yaml
Reverts hmcts/sds-flux-config#5153
- `clusters/prod/base/kustomization.yaml`:
- Removed the `neuvector` app from the resources.
> Revert "CHG5017419 - temp disabling for incident"

- apps/juror/juror-api/demo.yaml
- apps/juror/juror-api/ithc.yaml
deploy latest to demo and ithc
- Updated the image version for java in `demo.yaml` from `pr-665-2b00ea3-20240731122830` to `pr-665-f9fa308-20240731132622`.
- Updated the `ingressHost` for `demo.yaml` from `juror-api.demo.platform.hmcts.net`.
- Updated the image version for java in `ithc.yaml` from `pr-665-2b00ea3-20240731122830` to `pr-665-f9fa308-20240731132622`.
- Updated the `ingressHost` for `ithc.yaml` from `juror-api.ithc.platform.hmcts.net`.
- Added an environment variable `EMPTY_VAR: one`.
> deploy latest to demo and ithc

- apps/juror/juror-api/demo.yaml
- apps/juror/juror-api/ithc.yaml
bump ithc and demo an include ENV VAR for flyway 
- Added environment variable `RUN_DB_MIGRATION_ON_STARTUP` with a value of `true`.
- Updated the `image` field to `sdshmctspublic.azurecr.io/juror/api:pr-665-16cd22a-20240731143058`.
- Added environment variable `RUN_DB_MIGRATION_ON_STARTUP` with a value of `true`.
- Updated the `image` field to `sdshmctspublic.azurecr.io/juror/api:pr-665-16cd22a-20240731143058`.
> bump ithc and demo

- apps/juror/juror-public/test.yaml
update ENV VAR to force deploy
- Changed the value of `DUMMY_ENV_VAR` from `1` to `0`
> update ENV VAR to force deploy

- apps/juror/juror-public/test.yaml
try 30s startupDelay
md
- test.yaml
- Added a `startupDelay` of 30
```
> try 30s startupDelay

- apps/met/themis-fe/themis-fe.yaml
- Changed value of `TEMP_VAR` from `1` to `0`ℹ️
> Update themis-fe.yaml - Restart 01/08/2024

- apps/pdda/pdda-public-display-data-aggregator/stg.yaml
enabled autoscaling for pdda
- [ No] Does this PR introduce a breaking change
- Removed the `replicas`, `autoscaling`, and `ingressHost` configurations for the `pdda-public-display-data-aggregator` service in the staging environment.
> enabled autoscaling

- apps/juror/juror-public/test.yaml
update image to PR234
- Updated the `nodejs` image to `sdshmctspublic.azurecr.io/juror/public:pr-234-8e5f454-20240801110149` and removed the `startupDelay` field.
- Modified the `ingressHost` to `juror-public.test.apps.hmcts.net`.
> update image to PR234

- apps/juror/juror-public/test.yaml
update var to cause restart
- test.yaml 🚀
- Changed the value of the environment variable DUMMY_ENV_VAR from 0 to 1.
> update var to cause restart

- apps/juror/juror-public/test.yaml
more signal debugging
- Changed the image version from `pr-234-8e5f454-20240801110149` to `pr-234-7656229-20240801114255` for the `nodejs` service.
- Updated the environment variable `DUMMY_ENV_VAR` to `1`.
> more signal debugging

- apps/juror/juror-public/test.yaml
more signal debugging
- Changed the image version from \"pr-234-7656229-20240801114255\" to \"pr-234-ba89043-20240801115522\"
- Updated the value of \"DUMMY_ENV_VAR\" from 1 to 0
> update image 

- apps/juror/juror-public/test.yaml
force deploy
- The file `apps/juror/juror-public/test.yaml` has been modified.
- The `DUMMY_ENV_VAR` value has been changed from `0` to `1`.
> force deploy

- apps/juror/juror-public/test.yaml
more debugging
- Updated the image tag from \"pr-234-69f2ab0-20240801143733\" to \"pr-234-0031d6b-20240802063112\" 🚀
> more debugging

- apps/juror/juror-api/demo.yaml
- apps/juror/juror-api/ithc.yaml
- apps/juror/juror-bureau/demo.yaml
- apps/juror/juror-bureau/ithc.yaml
- apps/juror/juror-public/ithc.yaml
Stabilisation8 release into ITHC and Demo
- Updated demo.yaml and ithc.yaml files in juror-api and juror-bureau directories
- Updated image versions for Java and NodeJS applications in the spec section of the yaml files
- Changed the image tag for the specified applications in both demo and ithc environments in the yaml files.
> juror deployment for Stabilisation8

- apps/juror/juror-public/prod.yaml
https://centralgovernmentcgi.atlassian.net/browse/JM-7825
Add GA code for juror-public in prod
- Added a new environment variable TRACKING_CODE: GTM-W4F5BLC 🆕
> Add GA code for juror-public in prod

- apps/pre/pre-api-cron-cleanup-streaming-locators/demo.yaml
- apps/pre/pre-api-cron-cleanup-streaming-locators/image-policy.yaml
- apps/pre/pre-api-cron-cleanup-streaming-locators/image-repo.yaml
- apps/pre/pre-api-cron-cleanup-streaming-locators/pre-api-cron-cleanup-streaming-locators.yaml
- apps/pre/pre-api-cron-cleanup-streaming-locators/prod.yaml
- apps/pre/pre-api-cron-cleanup-streaming-locators/stg.yaml
- apps/pre/pre-api-cron-cleanup-streaming-locators/test.yaml
- Updated environment variables for Azure Media Services account, resource group, and subscription ID.
- Added a new file for a demo environment.
- Added a new file for image policy.
- Added a new file for image repository.
- Added a new file with a HelmRelease for the cron job to cleanup streaming locators.
- Added a new file for the production environment.
- Added a new file for the staging environment.
- Added a new file for the testing environment.
> New pre cron for cleaning up streaming locators

- apps/juror/juror-api/demo.yaml
- apps/juror/juror-api/ithc.yaml
- apps/juror/juror-bureau/demo.yaml
- apps/juror/juror-bureau/ithc.yaml
Stabilisation9 release to ITHC and Demo for juror-api and juror-bureau
- Updated demo.yaml``` and ```ithc.yaml``` in ```juror-api``` and ```juror-bureau``` directories to change the image version and deployment time for the corresponding environments.
- changes apply to the specified image and ingressHost values.
> juror deployment to ITHC and Demo

- apps/juror/juror-public/demo.yaml
- apps/juror/juror-public/ithc.yaml
- apps/juror/juror-public/test.yaml
Deploy PR-236 public and revert test to master
- Changed the image for the `nodejs` in the `spec` to `sdshmctspublic.azurecr.io/juror/public:pr-236-36f3877-20240805084841`
- Updated the `ingressHost` to `juror-public.demo.apps.hmcts.net`
- Updated the image for the `nodejs` in the `spec` to `sdshmctspublic.azurecr.io/juror/public:pr-236-36f3877-20240805084841`
- Updated the `ingressHost` to `juror-public.ithc.apps.hmcts.net`
- Changed the image for the `nodejs` in the `spec` to `sdshmctspublic.azurecr.io/juror/public:pr-234-d194b90-20240802091258`
- Updated the `ingressHost` to `juror-public.test.apps.hmcts.net`
- Added environment variable `DUMMY_ENV_VAR` with a value of `1`
> Deploy PR-236 public and revert test to master

- apps/juror/juror-api/demo.yaml
- apps/juror/juror-api/ithc.yaml
- apps/juror/juror-bureau/demo.yaml
- apps/juror/juror-bureau/ithc.yaml
Stabilisation9 release into ITHC and Demo
- Changed `demo.yaml` and `ithc.yaml` in `juror-api` and `juror-bureau` apps, updating the image version and timestamp for both Java and NodeJS.
- Updated the `ingressHost` for both demo and ithc environments in the `juror-api` and `juror-bureau` apps.
- Set `RUN_DB_MIGRATION_ON_STARTUP` to true for the `demo` environment in the `juror-api` app.
- Set `SKIP_SSO` to true for the `demo` environment in the `juror-bureau` app.
> juror deployment for stabilisation9

- apps/juror/juror-public/demo.yaml
- apps/juror/juror-public/ithc.yaml
Deploy PR-238 public to demo and ithc
- The image tag has been updated from `sdshmctspublic.azurecr.io/juror/public:pr-236-36f3877-20240805084841` to `sdshmctspublic.azurecr.io/juror/public:pr-238-4dd791d-20240806115937`.
- The `ingressHost` has been updated to `juror-public.demo.apps.hmcts.net`.
- The image tag has been updated from `sdshmctspublic.azurecr.io/juror/public:pr-236-36f3877-20240805084841` to `sdshmctspublic.azurecr.io/juror/public:pr-238-4dd791d-20240806115937`.
- The `ingressHost` has been updated to `juror-public.ithc.apps.hmcts.net`.
> Deploy PR-238 public to demo and ithc

- apps/pip/data-management/test.yaml
Update data-management image in test env for testing DM/CM merge
- Added a new image for the Java component: `sdshmctspublic.azurecr.io/pip/data-management:pr-610-942938c-20240730092746`
- Increased the number of replicas to 2 for the Java component.
> PUB-2359 Update data-management image in test env

- apps/pip/data-management/test.yaml
Update data-management image in test env
- Modified file: test.yaml
- Changed the image tag from \"pr-610-942938c-20240730092746\" to \"pr-610-962f2fb-20240808160138\" for the pip-data-management service.
> PUB-2359B Update data-management image in test env

- apps/pip/channel-management/test.yaml
- apps/pip/data-management/test.yaml
- apps/pip/frontend/test.yaml
- apps/pip/publication-services/test.yaml
Remove test env changes for DM/CM merge
- Changed replicas from 0 to 2 for the java service.
- Updated the image tag for the java service.
- Changed replicas from 0 to 2 for the java service.
- Updated the image tag for the nodejs service.
- Changed replicas from 0 to 2 for the nodejs service.
- Updated the image tag for the java service.
- Changed replicas from 0 to 2 for the java service.
> PUB-2359 Remove test env changes for DM/CM merge

- apps/juror/juror-api/demo.yaml
- apps/juror/juror-api/ithc.yaml
juror deployment into ITHC and Demo for Stabilisation10 fix in juror-api
- Updated the `image` field to `sdshmctspublic.azurecr.io/juror/api:pr-696-0ba8b12-20240809102412` from `sdshmctspublic.azurecr.io/juror/api:pr-685-3674b98-20240808112849` for both `demo.yaml` and `ithc.yaml` files.
> juror deployment into ITHC and Demo

- apps/pdda/pdda-public-display-manager/stg.yaml
- Added `environment` section with `TRIGGER_RESTART: 0` in the `stg.yaml` file 🔄
> pdda-393 Add environment variable to trigger application restart.

- apps/pip/frontend/demo.yaml
- apps/pip/frontend/ithc.yaml
- apps/pip/frontend/stg.yaml
- apps/pip/frontend/test.yaml
https://tools.hmcts.net/jira/browse/PUB-1566
Add Crime Idam URL
- Added CRIME_IDAM_URL: https://login.sit.cjscp.org.uk
- Added CRIME_IDAM_URL: https://login.sit.cjscp.org.uk
- Added CRIME_IDAM_URL: https://login.prp.cjscp.org.uk
- Added CRIME_IDAM_URL: https://login.sit.cjscp.org.uk
> PUB-1566 Add Crime Idam URL

- apps/pre/pre-api-cron-cleanup-live-events/stg.yaml
- apps/pre/pre-api-cron-cleanup-streaming-locators/stg.yaml
- apps/pre/pre-api/stg.yaml
- Updated the AZURE_INGEST_SA and AZURE_FINAL_SA values from `preingestsatest` and `prefinalsatest` to `preingestsastg` and `prefinalsastg`.
- Updated the AZURE_INGEST_SA and AZURE_FINAL_SA values from `preingestsatest` and `prefinalsatest` to `preingestsastg` and `prefinalsastg`.
- Updated the AZURE_INGEST_SA and AZURE_FINAL_SA values from `preingestsatest` and `prefinalsatest` to `preingestsastg` and `prefinalsastg`.
> Use stg SA for MK in Staging

- apps/dynatrace/demo/base/dynakube.yaml
- apps/dynatrace/dynakube-upgrade.yaml
Update the dynakube api
- Updated the `apiVersion` from `dynatrace.com/v1beta1` to `dynatrace.com/v1beta2` in the DynaKube resource.
- Updated the `apiVersion` from `dynatrace.com/v1beta1` to `dynatrace.com/v1beta2` in the DynaKube resource.
- Added metadata enrichment with enabled namespaceSelector.
> Update the dynakube api

- apps/dynatrace/test/base/dynakube.yaml
- apps/dynatrace/test/base/kustomization.yaml
- clusters/demo/base/kustomization.yaml
- clusters/test/base/kustomization.yaml
Dynatrace patch on test env
- Updated the `apiVersion` from `dynatrace.com/v1beta1` to `dynatrace.com/v1beta2`.
- Removed `././dynakube.yaml` and added `././dynakube-upgrade.yaml` in the `resources` list.
- Added `dynakube-operator-upgrade.yaml` in the `patches` section.
- Added `./././apps/dynatrace/base/kustomize-upgrade.yaml` in the `patches` section.
- Added `./././apps/dynatrace/base/kustomize-upgrade.yaml` in the `patches` section.
> Dynatrace patch on test env

- apps/dynatrace/test/base/dynakube.yaml
- apps/dynatrace/test/base/kustomization.yaml
- clusters/demo/base/kustomization.yaml
- clusters/test/base/kustomization.yaml
Reverts hmcts/sds-flux-config#5245
> Revert "Dynatrace patch on test env"

- apps/dynatrace/demo/base/dynakube.yaml
- apps/dynatrace/demo/base/kustomization.yaml
- clusters/demo/base/kustomization.yaml
try patching demo on v1beta1 api
- Updated `apiVersion` from `dynatrace.com/v1beta2` to `dynatrace.com/v1beta1`.
- Removed `./dynakube-upgrade.yaml` and added `./dynakube.yaml`.
- Added path to `./apps/dynatrace/base/kustomize-upgrade.yaml`.
> try patching demo on v1beta1 api

- apps/pdda/pdda-public-display-manager/stg.yaml
- Updated stg.yaml```
- Added environment variables for logging levels: ```LOGGING_LEVEL_UK_GOV_HMCTS_PDM``` and ```LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_SECURITY``` with value set to \"DEBUG\".
> Enable some additional debug logging

- apps/juror/juror-api/demo.yaml
- apps/juror/juror-api/ithc.yaml
- apps/juror/juror-bureau/demo.yaml
- apps/juror/juror-bureau/ithc.yaml
- apps/juror/juror-public/demo.yaml
- apps/juror/juror-public/ithc.yaml
Updated demo/ithc versions
- Updated images and timestamps in demo.yaml and ithc.yaml files for juror-api, juror-bureau, and juror-public apps. 🛠️
> Updated demo/ithc versions

- apps/dynatrace/dynakube-upgrade.yaml
- apps/dynatrace/test/base/dynakube.yaml
- apps/dynatrace/test/base/kustomization.yaml
- clusters/test/base/kustomization.yaml
Patch dynatrace on test env
- Updated apiVersion from dynatrace.com/v1beta1``` to ```dynatrace.com/v1beta2```.
- Updated apiVersion from ```dynatrace.com/v1beta1``` to ```dynatrace.com/v1beta2```.
- Removed ```././dynakube.yaml``` and added ```././dynakube-upgrade.yaml```.
- Added a new patch for ```././dynatrace-operator-upgrade.yaml```.
- Added a new path for ```./././apps/dynatrace/base/kustomize-upgrade.yaml```.
> Patching test env

- apps/darts-modernisation/darts-api/prod.yaml
Wrapping date in string to prevent error when injecting into application
- Modified the value of `MODERNISED_DARTS_START_DATE` from `2099-01-01` to `'2099-01-01'` 🔄.
> wrapping date in string

- apps/dynatrace/stg/base/dynakube.yaml
- apps/dynatrace/stg/base/kustomization.yaml
- clusters/stg/base/kustomization.yaml
Patch dynatrace on stg env
- Updated apiVersion from dynatrace.com/v1beta1 to dynatrace.com/v1beta2 for DynaKube.
- Removed dynakube.yaml and added dynakube-upgrade.yaml to resources.
- Added a path to dynatrace-operator-upgrade.yaml for patches.
- Added a path to apps/dynatrace/base/kustomize-upgrade.yaml for patches.
> Patch stg env

- apps/juror/juror-bureau/demo.yaml
Updated demo versions
- Updated the image for the `nodejs` service to `sdshmctspublic.azurecr.io/juror/bureau:pr-715-dbfa869-20240816144128` 🐳
- Set `SKIP_SSO` environment variable to `true`
> Updated demo versions

- apps/darts-modernisation/base/kustomization.yaml
- apps/darts-modernisation/darts-ucf-test-harness/test.yaml
- apps/darts-modernisation/stg/base/kustomization.yaml
- apps/darts-modernisation/test/base/kustomization.yaml
See [DMP-3511](https://tools.hmcts.net/jira/browse/DMP3511)
Add perftest env
- `apps/darts-modernisation/base/kustomization.yaml`:
- Added `darts-ucf-test-harness/darts-ucf-test-harness.yaml` as a resource.
- `apps/darts-modernisation/darts-ucf-test-harness/test.yaml`:
- Added a new file defining a HelmRelease resource for `darts-ucf-test-harness` with specific values.
- `apps/darts-modernisation/stg/base/kustomization.yaml`:
- Removed `./darts-ucf-test-harness/darts-ucf-test-harness.yaml` as a resource.
- `apps/darts-modernisation/test/base/kustomization.yaml`:
- Added `darts-ucf-test-harness/test.yaml` as a new path.
> DMP-3511: Add perftest env

- apps/pdda/pdda-public-display-data-aggregator/stg.yaml
- **stg.yaml**
- Added environment variables TRIGGER_RESTART, LOGGING_LEVEL_UK_GOV_HMCTS_PDM, LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_SECURITY, LOGGING_LEVEL_COM_ZAXXER_HIKARI 🚀
> Update stg.yaml - added debugging

- apps/juror/juror-api/demo.yaml
- apps/juror/juror-api/image-policy.yaml
- apps/juror/juror-api/ithc.yaml
- apps/juror/juror-bureau/demo.yaml
- apps/juror/juror-bureau/image-policy.yaml
- apps/juror/juror-bureau/ithc.yaml
- apps/juror/juror-pnc/image-policy.yaml
- apps/juror/juror-public/demo.yaml
- apps/juror/juror-public/image-policy.yaml
- apps/juror/juror-public/ithc.yaml
- apps/juror/juror-scheduler-api/image-policy.yaml
- apps/juror/juror-scheduler-execution/image-policy.yaml
JM-8097
- Made changes in `demo.yaml` files for `juror-api`, `juror-bureau`, and `juror-public` apps, updating the image and ingressHost values.
- Updated `image-policy.yaml` files for `juror-api`, `juror-bureau`, `juror-pnc`, `juror-public`, `juror-scheduler-api`, and `juror-scheduler-execution` apps, adding annotations and spec details for image policies.
> juror: add pr image policy

- apps/pre/base/kustomization.yaml
- apps/pre/pre-api-cron-cleanup-live-events/demo.yaml
- apps/pre/pre-api-cron-cleanup-live-events/stg.yaml
- apps/pre/pre-api-cron-cleanup-live-events/test.yaml
- apps/pre/pre-api-cron-cleanup-streaming-locators/demo.yaml
- apps/pre/pre-api-cron-cleanup-streaming-locators/stg.yaml
- apps/pre/pre-api-cron-cleanup-streaming-locators/test.yaml
- apps/pre/stg/base/kustomization.yaml
https://tools.hmcts.net/jira/browse/S28-3236
schedule CRONs for cleanup in STG
- `kustomization.yaml`: 
- Added new resources `pre-api-cron-cleanup-streaming-locators/pre-api-cron-cleanup-streaming-locators.yaml` and `pre-api-cron-cleanup-live-events/pre-api-cron-cleanup-live-events.yaml`.
- `pre-api-cron-cleanup-live-events/demo.yaml`, `pre-api-cron-cleanup-live-events/stg.yaml`, `pre-api-cron-cleanup-live-events/test.yaml`, `pre-api-cron-cleanup-streaming-locators/demo.yaml`, `pre-api-cron-cleanup-streaming-locators/stg.yaml`, `pre-api-cron-cleanup-streaming-locators/test.yaml`: 
- Updated the `suspend` attribute from `false` to `true`.
- Updated the `schedule` times for staging environment.
> PRE schedule CRONs for cleanup in STG

- apps/juror/juror-api/image-policy.yaml
- apps/juror/juror-bureau/image-policy.yaml
- Added annotations for prod-automated with disabled status.
- Added filterTags with extract and pattern fields.
- Added policy with alphabetical order in ascending order for imageRepositoryRef.
- Added annotations for prod-automated with disabled status.
- Added filterTags with extract and pattern fields.
- Added policy with alphabetical order in ascending order for imageRepositoryRef.
- Added annotations for prod-automated with disabled status.
- Added filterTags with extract and pattern fields.
- Added policy with alphabetical order in ascending order for imageRepositoryRef.
- Added annotations for prod-automated with disabled status.
- Added filterTags with extract and pattern fields.
- Added policy with alphabetical …
> update to stabilisation 13

- apps/juror/juror-api/image-policy.yaml
- apps/juror/juror-api/ithc.yaml
- Modified `image-policy.yaml`:
- Added a new `ImagePolicy` for `juror-api` with specific filter tags and annotations.
- Modified `ithc.yaml`:
- Updated the Java image for `juror-api` to `pr-740-316d4f3-20240823090653`.
> Updated ITHC image policy

- apps/pip/frontend/test.yaml
See [PUB-2327](https://tools.hmcts.net/jira/browse/PUB-2327)
Deploy rate-limiting prototype to test environment
- Updated the image reference for the pip frontend from \"sdshmctspublic.azurecr.io/pip/frontend:pr-1328-dd94025-20240822111649\" to \"sdshmctspublic.azurecr.io/pip/frontend:pr-1328-40214bd-20240823101238\".
> PUB-2327 Deploy rate-limiting prototype to test environment

- apps/pip/frontend/test.yaml
Update test env image with rate limiting prototype for frontend
- Updated the image for the frontend service to 'sdshmctspublic.azurecr.io/pip/frontend:pr-1328-37fd1d2-20240823112720'.
> PUB-2327 Update test env image with rate limiting prototype for frontend

- apps/juror/juror-api/image-policy.yaml
- apps/juror/juror-public/image-policy.yaml
- Added annotation for prod-automated disabling
- Updated filterTags to extract and pattern for production images
- Added policy for alphabetical order in image versioning
- Added annotation for prod-automated disabling
- Updated filterTags to extract and pattern for pull request images
- Added policy for alphabetical order in image versioning
- Updated filterTags pattern to match pull request images with a specific ID
- Added policy for alphabetical order in image versioning
> Updated public image policy

- apps/pip/frontend/test.yaml
Update test env image with rate limiting prototype
- Updated `test.yaml` in `frontend` directory of `pip` app:
- Changed the image tag from `pr-1328-37fd1d2-20240823112720` to `pr-1328-5038ba6-20240823152019` for the `frontend` service.
> PUB-2327 Update test env image with rate limiting prototype

- apps/pip/frontend/test.yaml
See [PUB-2327](https://tools.hmcts.net/jira/browse/PUB-2327)
Update test image with rate limiting prototype
- **test.yaml** 🚀
- Added a new image configuration for replicas in the nodejs section.
> PUB-2327 Update test image with rate limiting prototype

- apps/met/batch-jobs/test.yaml
N/A
Maps additional secrets required for AMS reporting.
- Added several new environment variables related to various data sources, such as \"themis-gateway\", \"dac\", \"fines\", \"maintenance\", and \"confiscation\". ⚙️
> fix: map additional secrets for ams reporting

- apps/pdda/pdda-public-display-data-aggregator/stg.yaml
> Update stg.yaml to force a restart

- apps/pdda/pdda-public-display-manager/stg.yaml
- Changed the value of `TRIGGER_RESTART` from 0 to 1.
- Updated the logging levels for `UK_GOV_HMCTS_PDM`, `ORG_SPRINGFRAMEWORK_SECURITY`, and `COM_ZAXXER_HIKARI` to DEBUG.
> Update PDM stg.yaml to force a restart

- apps/pre/pre-api-cron-cleanup-live-events/stg.yaml
- apps/pre/pre-api-cron-cleanup-streaming-locators/stg.yaml
- Updated `stg.yaml` in `pre-api-cron-cleanup-live-events`:
- Changed the schedule from \"55 17 * * *\" to \"55 16 * * *\"
- Updated `stg.yaml` in `pre-api-cron-cleanup-streaming-locators`:
- Changed the schedule from \"0 18 * * *\" to \"0 17 * * *\"
> test time change on PRE CRONS 

- apps/darts-modernisation/darts-api/demo.yaml
- Updated the environment variables for the application, specifically the `ARM_URL` and `FEIGN_LOG_LEVEL`.
- Removed the \"FEIGN_LOG_LEVEL\" and added it back with the same value to the function image.
>  NO_JIRA fixed wrong setting of FEIGN_LOG_LEVEL env var

- apps/neuvector/crds/kustomize.yaml
- apps/neuvector/neuvector/ithc/ithc.yaml
- apps/neuvector/neuvector/stg/stg.yaml
- apps/neuvector/neuvector/test/test.yaml
- clusters/ithc/base/kustomization.yaml
- clusters/stg/base/kustomization.yaml
- clusters/test/base/kustomization.yaml
See [DTSPO-18318](https://tools.hmcts.net/jira/browse/DTSPO-18318)
Upgrades nonprod neuvector to version 1.5.9
- Created a new file `kustomize.yaml` within the `apps/neuvector/crds` directory to define kustomization for NeuVector custom resource definitions (CRDs)
- Modified `ithc.yaml`, `stg.yaml`, and `test.yaml` within the `neuvector` directory to specify the chart version as 1.5.9 and set values for the keyvault
- Updated `kustomization.yaml` files for the `ithc`, `stg`, and `test` clusters to include the path to the `apps/neuvector/crds/kustomize.yaml` file as part of the kustomization diff
> Update Neuvector to Version 1.5.9

- apps/pip/frontend/test.yaml
- `test.yaml` 🛠️
- Added a new image `sdshmctspublic.azurecr.io/pip/frontend:pr-1330-dd1fbe7-20240829113917` and increased replicas to 2.
> PUB-2340 - Add PR image for test

- apps/pip/frontend/test.yaml
Reverts hmcts/sds-flux-config#5351
- Removed 1 replica and an image config for nodejs.
- Updated the ingressHost to pip-frontend.test.platform.hmcts.net.
- Updated the environment variable DATA_MANAGEMENT_URL to https://pip-data-management.test.platform.hmcts.net.
> Revert "PUB-2340 - Add PR image for test"

- apps/pip/frontend/test.yaml
- Added a new `image` field with the value `sdshmctspublic.azurecr.io/pip/frontend:pr-1330-dd1fbe7-20240829113917` to the `nodejs` section.
- Updated the `replicas` value to `2`.
> add pr image for test

- apps/darts-modernisation/darts-gateway/demo.yaml
- apps/darts-modernisation/darts-gateway/prod.yaml
- Updated `DARTS_LOG_LEVEL` to INFO and added `DARTS_SOAP_REQUEST_LOG_LEVEL` as TRACE in the `environment` section.
- Updated `DAR_NOTIFY_ENABLED` to true in the `environment` section.
- Updated `DARTS_LOG_LEVEL` to INFO and added `DARTS_SOAP_REQUEST_LOG_LEVEL` as TRACE in the `environment` section.
- Updated `DAR_NOTIFY_ENABLED` to true in the `environment` section.
> DMP-3723 - Added new environment property for additional log level

- apps/juror/juror-bureau/demo.yaml
- apps/juror/juror-bureau/ithc.yaml
https://github.com/hmcts/juror-bureau/pull/781
to be deployed for testing in ITHC and Demo
- Updated `demo.yaml` and `ithc.yaml` in the `apps/juror/juror-bureau/` directory.
- Changed the image version from `prod-449fdd8-20240828163031` to `pr-781-4ba273c-20240902110821`.
- Updated the `ingressHost` for both files to point to the respective environments.
- Set `SKIP_SSO` to `true` for both environments.
> deploying hotfix to ITHC and Demo

- apps/pre/pre-api-cron-cleanup-live-events/stg.yaml
- apps/pre/pre-api-cron-cleanup-streaming-locators/stg.yaml
- `pre-api-cron-cleanup-live-events/stg.yaml` 🔄
- Updated the schedule from \"30 14 * * *\" to \"30 17 * * *\"
- `pre-api-cron-cleanup-streaming-locators/stg.yaml` 🔄
- Updated the schedule from \"30 15 * * *\" to \"30 18 * * *\"
> Set PRE stg crons to run Out of Hours

- apps/azureserviceoperator-system/aso/kustomization.yaml
- apps/azureserviceoperator-system/cert-manager/kustomization.yaml
[DTSPO-18113](https://tools.hmcts.net/jira/browse/DTSPO-18113)
First Azure Service Operator upgrade
Completed previously on CFT
No breaking changes in this 2.3 release
- Updated Azure Service Operator version from 2.2.0 to 2.3.0.
- Updated Cert Manager version from 1.12.1 to 1.12.12.
> Azure Service Operator - 2.3

- apps/juror/juror-api/image-policy.yaml
- apps/juror/juror-public/image-policy.yaml
Deploying Interim1 release into ITHC and Demo
To be tested in ITHC and Demo
- [x ] Does this PR introduce a breaking change
- Added annotations for \"hmcts.github.com/prod-automated\" with disabled status
- Added filterTags with extract and pattern for image repository reference \"juror-api\"
- Added policy with alphabetical order in ascending order
- Added annotations for \"hmcts.github.com/prod-automated\" with disabled status
- Added filterTags with extract and pattern for image repository reference \"pr-762\"
- Added policy with alphabetical order in ascending order
- Updated the pattern in filterTags for image repository reference \"juror-public\" from 'pr-245' to 'pr-248'
> interim1 updates to Juror ITHC and Demo

- apps/azureserviceoperator-system/aso/kustomization.yaml
[DTSPO-18113](https://tools.hmcts.net/jira/browse/DTSPO-18113)
2.4 release notes: https://github.com/Azure/azure-service-operator/releases/tag/v2.4.0
Same work has been completed on CFT
https://github.com/hmcts/sds-flux-config/pull/5391 has gone in to enable this
- Updated the version of `azureserviceoperator_v2.3.0.yaml` to `azureserviceoperator_v2.4.0.yaml`. 🔄
> aso 2.4 upgrade

- apps/darts-modernisation/darts-portal/stg.yaml
See https://tools.hmcts.net/jira/browse/DMP-3863
- demo and staging use the staging B2C 
- set the URL on staging to demo so that a link we provide to the internal login page points to demo
- Added DARTS_PORTAL_URL: https://darts.demo.apps.hmcts.net 🌐
> DMP-3863 Fixing link on external login page

- apps/darts-modernisation/darts-portal/stg.yaml
Reverts hmcts/sds-flux-config#5402
- stg.yaml
- Removed redundant DARTS_PORTAL_URL entry
- Added DARTS_PORTAL_URL: https://darts.staging.apps.hmcts.net
> Revert "DMP-3863 Fixing link on external login page"

- apps/pre/pre-portal/demo.yaml
https://tools.hmcts.net/jira/browse/S28-3284
- Updated the image for the nodejs replicas to `sdshmctspublic.azurecr.io/pre/portal:prod-b2c7837-20240828140456`.
> revert demo to master image demo.yaml

- apps/darts-modernisation/darts-automated-tasks/darts-automated-tasks.yaml
- apps/darts-modernisation/darts-migration/darts-api-migration.yaml
https://tools.hmcts.net/jira/browse/DMP-3374
- setting `pollingInterval` to 24 hours
- only where we don't want it to run
- **darts-automated-tasks.yaml**
- Added a `pollingInterval` of 86400
- **darts-api-migration.yaml**
- Added a `pollingInterval` of 86400
> DARTS KEDA tweaks

- apps/pre/pre-api-cron-cleanup-live-events/stg.yaml
- apps/pre/pre-api-cron-cleanup-streaming-locators/stg.yaml
- apps/pre/pre-api/stg.yaml
- `stg.yaml`:
- Changed `MEDIA_SERVICE` from `MediaKind` to `AzureMediaService` in multiple stg.yaml files.
- Updated `AZURE_MEDIA_SERVICES_ACCOUNT_NAME`, `AZURE_RESOURCE_GROUP`, `AZURE_SUBSCRIPTION_ID`, and `MEDIA_SERVICE` values.
- Set `PLATFORM_ENV_TAG` to Staging in the environment configuration.
> Use AMS STG in stg env for PRE

- apps/darts-modernisation/darts-api/demo.yaml
- apps/darts-modernisation/darts-api/ithc.yaml
- apps/darts-modernisation/darts-api/prod.yaml
- apps/darts-modernisation/darts-api/stg.yaml
- apps/darts-modernisation/darts-api/test.yaml
See [DMP-2543](https://tools.hmcts.net/jira/browse/DMP-2543)
Added case expiry deletion flag to prod
- Added `CASE_EXPIRY_DELETION_ENABLED` with a value of `false` to the `demo.yaml`, `ithc.yaml`, `prod.yaml`, and `test.yaml` files in the `darts-api` directory.
- Updated the `ARM_URL` in the `ithc.yaml` file in the `darts-api` directory.
> Added case expiry deletion flag to prod

- apps/darts-modernisation/darts-api/prod.yaml
- apps/darts-modernisation/darts-api/test.yaml
- Modified `prod.yaml`: Added `DARTS_API_DB_POOL_SIZE` with a value of 200.
- Modified `test.yaml`: Added `DARTS_API_DB_POOL_SIZE` with a value of 200.
> DMP-3897 - increase db connection pool size

- apps/mailrelay/mailrelay/dev/dev.yaml
https://tools.hmcts.net/jira/browse/DTSPO-18598
Changing disk size and type for mailrelay application
- Changed storageClass from \"managed-premium\" to \"managed\" and storageSize from 500Gi to 64Gi for the volumeClaim. 📦
> DTSPO-18598 - changing disk size and type for mailrelay

- apps/pdda/pdda-public-display-manager/stg.yaml
- Changed environment variable `TRIGGER_RESTART` from `0` to `1`
- Updated logging levels for `UK_GOV_HMCTS_PDM`, `ORG_SPRINGFRAMEWORK_SECURITY`, and `COM_ZAXXER_HIKARI` to `DEBUG`
> Trigger a restart of pdm.

- apps/pdda/pdda-public-display-manager/stg.yaml
- Changed the value of `TRIGGER_RESTART` from `1` to `0`
- Updated the logging levels for `UK_GOV_HMCTS_PDM`, `ORG_SPRINGFRAMEWORK_SECURITY`, and `COM_ZAXXER_HIKARI` to `DEBUG` 🔄
> Restart PDM.

- clusters/test/base/kustomization.yaml
Removing for now so our AKS upgrades are not blocked. This can be added back when needed
- clusters/test/base/kustomization.yaml
- Replaced the reference to \"apps/pre/base/kustomize.yaml\" with \"apps/juror/base/kustomize.yaml\"
- Updated the patch for \"apps/admin/test/base/kustomize.yaml\"
> Remove PRE from test

- apps/pdda/pdda-public-display-data-aggregator/stg.yaml
- Changed the value of `TRIGGER_RESTART` from `0` to `1`
- Updated logging levels for `UK_GOV_HMCTS_PDDA`, `ORG_SPRINGFRAMEWORK_SECURITY`, and `COM_ZAXXER_HIKARI` to `DEBUG` 🔄
> Update stg.yaml - force a restart

- apps/pip/frontend/pip-frontend.yaml
Revert to previous image to sort P1. Pipeline broken so can't do revert of actual code. 
This will need to be put back to latest image and set back to automatic once pipeline is ok
- Updated the image for the \"pip-frontend\" service in the \"pip-frontend.yaml\" file to \"sdshmctspublic.azurecr.io/pip/frontend:prod-2003b22-20240920151637\" 🖼️
> Revert broken image

- apps/vh/video-web/test.yaml
See [VIH-10987](https://tools.hmcts.net/jira/browse/VIH-10987)
Experimenting with resource allocation for app in Test env only
- Added memory and CPU resources requests and limits for the Java application
- Set the number of replicas to 8 and enabled autoscaling with a max of 16 replicas
- Configured CPU and memory-based autoscaling with average utilization thresholds
> VIH-10987 adjust pod resources for test env

- apps/vh/booking-queue-subscriber/booking-queue-subscriber.yaml
https://tools.hmcts.net/jira/browse/VIH-10994
Remove horizontal pod autoscaler for booking queue subscriber, as it's causing an issue
- **apps/vh/booking-queue-subscriber/booking-queue-subscriber.yaml**
- Removed autoscaling configuration for Java, including maxReplicas, cpu, and memory settings. Disabled Traefik TLS.
> VIH-10994 Remove booking-queue-subscriber.yaml

- apps/vh/video-web/stg.yaml
- apps/vh/video-web/test.yaml
See [VIH-10987](https://tools.hmcts.net/jira/browse/VIH-10987)
Testing increased CPU limits in Stg and Test envs
- `stg.yaml`
- Added resource limits and requests for Java application
- Set up autoscaling with max replicas, CPU, and memory utilization
- Updated ingress host for staging environment
- `test.yaml`
- Updated number of replicas from 8 to 4
- Enabled autoscaling with max replicas of 16
> VIH-10987 adjust pod scale and resources

- apps/opal/opal-frontend/opal-frontend.yaml
- apps/pip/frontend/ithc.yaml
- apps/pip/frontend/test.yaml
https://tools.hmcts.net/jira/browse/PUB-2591
Use SSO image for Test and ITHC env
- `ithc.yaml`
- Updated the Node.js image for the `pip-frontend` release to `sdshmctspublic.azurecr.io/pip/frontend:pr-1334-11d87a1-20240926141159`
- `test.yaml`
- Updated the Node.js image for the `pip-frontend` release to `sdshmctspublic.azurecr.io/pip/frontend:pr-1334-11d87a1-20240926141159`
> PUB-2591 Use SSO image for Test and ITHC env

- apps/juror/juror-api/image-policy.yaml
- apps/juror/juror-bureau/image-policy.yaml
Deploying release2 into ITHC and Demo
The release is for the test team to test against
- Added annotations for disabling prod-automated
- Added filterTags with extract and pattern
- Added policy with alphabetical order: asc
- Added annotations for disabling prod-automated
- Added filterTags with extract and pattern
- Added policy with alphabetical order: asc
> release2 into ITHC and Demo

- apps/pre/pre-portal/demo.yaml
- Added ENABLE_MK_WATCH_PAGE: true``` to the spec.🚀
> Enable watch MK page on PRE demo

- apps/pip/frontend/test.yaml
https://tools.hmcts.net/jira/browse/PUB-2340
Change image to new version for testing
- Changed the image for the `nodejs` service from `sdshmctspublic.azurecr.io/pip/frontend:pr-1334-11d87a1-20240926141159` to `sdshmctspublic.azurecr.io/pip/frontend:prod-bff851f-20240927131931`
- Updated the ingress host to `pip-frontend.test.platform.hmcts.net`
> PUB-2340 - Change image to new in test

- apps/pre/pre-portal/demo.yaml
- Added a new configuration `USE_MK_ON_WATCH_PAGE` with the value `true`. 🎉
> PRE demo default to MK player

- apps/darts-modernisation/darts-ucf-test-harness/demo.yaml
https://tools.hmcts.net/jira/browse/DMP-3511
> DMP-3511 - add test harness environment variables

- apps/darts-modernisation/darts-api/demo.yaml
- apps/darts-modernisation/darts-api/ithc.yaml
- apps/darts-modernisation/darts-api/prod.yaml
- apps/darts-modernisation/darts-api/stg.yaml
- apps/darts-modernisation/darts-api/test.yaml
- apps/darts-modernisation/darts-portal/demo.yaml
- apps/darts-modernisation/darts-portal/ithc.yaml
- apps/darts-modernisation/darts-portal/prod.yaml
- apps/darts-modernisation/darts-portal/stg.yaml
- apps/darts-modernisation/darts-portal/test.yaml
See [DMP-3989](https://tools.hmcts.net/jira/browse/DMP-3989)
Added MANUAL_DELETION_ENABLED flag
- `demo.yaml` (darts-api): Added `MANUAL_DELETION_ENABLED: false` to the environment variables.
- `ithc.yaml` (darts-api): Added `MANUAL_DELETION_ENABLED: false` to the environment variables.
- `prod.yaml` (darts-api): Added `MANUAL_DELETION_ENABLED: false` to the environment variables.
- `stg.yaml` (darts-api): Added `MANUAL_DELETION_ENABLED: true` to the environment variables.
- `test.yaml` (darts-api): Added `MANUAL_DELETION_ENABLED: false` to the environment variables.
- `demo.yaml` (darts-portal): Added `MANUAL_DELETION_ENABLED: false` to the environment variables.
- `ithc.yaml` (darts-portal): Added `MANUAL_DELETION_ENABLED: false` to the environment variables.
- `prod.yaml` …
> Added MANUAL_DELETION_ENABLED flag

- apps/juror/juror-public/image-policy.yaml
- Updated `image-policy.yaml`: Changed the pattern for filterTags from `'^pr-248-[a-f0-9]+-(?P<ts>[0-9]+)'` to `'^pr-256-[a-f0-9]+-(?P<ts>[0-9]+)'` 🔄
> juror: update public to release 2

- apps/darts-modernisation/darts-ucf-test-harness/demo.yaml
- apps/darts-modernisation/darts-ucf-test-harness/stg.yaml
https://tools.hmcts.net/jira/browse/DMP-3511
> DMP-3511 - test harness

- apps/pdda/pdda-public-display-manager/stg.yaml
- Updated `stg.yaml`:
- Changed `TRIGGER_RESTART` environment variable from 0 to 1.
- Updated logging levels for `UK_GOV_HMCTS_PDM`, `ORG_SPRINGFRAMEWORK_SECURITY`, and `COM_ZAXXER_HIKARI` to `DEBUG`.
> Restart pdm

- apps/pre/pre-api-cron-cleanup-live-events/stg.yaml
- Updated the schedule for the cron job from \"30 17 * * *\" to \"59 * * * *\" 🔄
> Cronjob stg to 0.59 every hr Update stg.yaml

- apps/juror/juror-scheduler-execution/demo.yaml
- apps/juror/juror-scheduler-execution/ithc.yaml
https://centralgovernmentcgi.atlassian.net/browse/JM-7921
Updating juror ITHC and Demo for release2
this is to deploy for testing
- Updated the value of the `java` image to `sdshmctspublic.azurecr.io/juror/scheduler-execution:pr-225-af2ae4e-20241003110808` 🔄
> update for ithc and demo testing

- apps/pre/pre-api-cron-cleanup-live-events/stg.yaml
cron tested OK. reverting
- Updated file: `stg.yaml`
- Changed the schedule from \"59 * * * *\" to \"30 17 * * *\" for the `pre-api-cron-cleanup-live-events` job. 🔄
> Revert cron time change

- clusters/test/base/kustomization.yaml
https://tools.hmcts.net/jira/browse/S28-3351
- Added a new resource for `./././apps/pre/base/kustomize.yaml`
- Removed a resource for `./././apps/monitoring/base/kustomize.yaml`
- Removed a resource for `./././apps/keda/base/kustomize.yaml`
> Enable PRE in Test

- apps/pre/test/base/kustomization.yaml
https://tools.hmcts.net/jira/browse/S28-3295
add cronjobs to test for PRE
S28-3295
- File: kustomization.yaml
- Added references to pre-api-cron-cleanup-live-events.yaml and pre-api-cron-cleanup-streaming-locators.yaml
- Added test.yaml references for pre-api-cron-cleanup-streaming-locators and pre-api-cron-cleanup-live-events.
> add cronjobs to test for PREhttps://tools.hmcts.net/jira/browse/S28-3295

- apps/pip/account-management/test.yaml
- apps/pip/data-management/test.yaml
- apps/pip/frontend/test.yaml
- apps/pip/publication-services/test.yaml
- apps/pip/subscription-management/test.yaml
- Updated test.yaml in apps/pip/account-management: Added autoscaling configuration with specific values.
- Updated test.yaml in apps/pip/data-management: Added autoscaling configuration with specific values.
- Updated test.yaml in apps/pip/frontend: Added autoscaling configuration with specific values.
- Updated test.yaml in apps/pip/publication-services: Added autoscaling configuration with specific values.
- Updated test.yaml in apps/pip/subscription-management: Added autoscaling configuration with specific values.
> PUB-1692 - Autoscaling Test

- apps/juror/juror-scheduler-execution/ithc.yaml
deploying juror scheduler exec service update
This deployment is for release2 testing
- Updated the `image` value to `sdshmctspublic.azurecr.io/juror/scheduler-execution:pr-225-1695f06-20241009093321` in the `java` section.
> update for ITHC deployment

- apps/pip/account-management/test.yaml
- apps/pip/data-management/test.yaml
- apps/pip/frontend/test.yaml
- apps/pip/publication-services/test.yaml
- apps/pip/subscription-management/test.yaml
- `test.yaml`:
- Added memory and CPU request and limit specifications for various services.
- Updated autoscaling configurations for these services.
> PUB-1692 - Set cpu and memory requests equal to limits for autoscaling testing

- apps/pip/frontend/test.yaml
https://tools.hmcts.net/jira/browse/PUB-2618
Testing frontend build
- Added new image for `nodejs`
- Updated the replicas to 2
> PUB-2618 - Dependency updates

- apps/pip/data-management/test.yaml
- apps/pip/frontend/ithc.yaml
https://tools.hmcts.net/jira/browse/PUB-2587
Add data-management image for date field validation
- `apps/pip/data-management/test.yaml` 🐳
- Added a new image configuration for Java replicas.
- `apps/pip/frontend/ithc.yaml` 🐳
- Removed a specific image configuration for nodejs.
- Updated the environment URL for data management.
> PUB-2587 Add data-management image for date field validation

- apps/darts-modernisation/darts-ucf-test-harness/stg.yaml
- apps/darts-modernisation/darts-ucf-test-harness/test.yaml
- Updated `stg.yaml`: Changed the `TEST_HARNESS_AUTOMATION_ENABLED` value from true to false.
- Updated `test.yaml`: Changed the `TEST_HARNESS_AUTOMATION_ENABLED` value from false to true and added a `replicas` value of 10 for the `java` section.
> test harness activate on test environment

- apps/darts-modernisation/darts-ucf-test-harness/test.yaml
- In `test.yaml`, the number of replicas for the `java` service has been changed from 10 to 1.
- Additionally, `TEST_HARNESS_AUTOMATION_ENABLED` has been changed from `true` to `false`.
> test harness deactivate on test environment

- apps/pip/data-management/stg.yaml
- apps/pip/data-management/test.yaml
https://tools.hmcts.net/jira/browse/PUB-2587
Add data-management image for date field validation to stg env
- Added a new image for the java replicas.
- Updated the ingressHost to point to the staging environment.
- Removed the image configuration for java replicas.
- Updated the ingressHost to point to the testing environment.
> PUB-2587 Add data-management image for date field validation to stg env

- apps/pip/frontend/test.yaml
Testing PUB-2340
- Added multiple environment variables and their aliases
- Updated the image for nodejs and specified the keyVaults and resourceGroup
> PUB-2617 - Updated test config

- apps/pip/frontend/test.yaml
Updated flux config
- Updated the image for the nodejs module from \"sdshmctspublic.azurecr.io/pip/frontend:pr-1365-d19b15a-20241011091052\" to \"sdshmctspublic.azurecr.io/pip/frontend:pr-1365-7c84339-20241011101022\".
> PUB-2617 - Updated test image

- apps/pip/frontend/test.yaml
- Updated the image for the pip-frontend in the nodejs section, changing from \"pr-1365-7c84339\" to \"pr-1367-0ff7351\"
> PUB-2617 - Updated image

- apps/pip/frontend/stg.yaml
- apps/pip/frontend/test.yaml
Temporarily updated staging for testing
- Added image tag and key vault configuration for secrets. ⭐
> PUB-2617 - Testing update

- apps/juror/juror-api/image-policy.yaml
- apps/juror/juror-bureau/image-policy.yaml
- apps/juror/juror-public/image-policy.yaml
Juror deployment into ITHC and Demo for release3 
Testing to be done on this deployment
- Updated image-policy.yaml``` in ```juror-api``` and ```juror-bureau``` apps:
- Added annotations for disabling automated production deployment.
- Added filterTags to extract and pattern matching for production and pull request images.
- Set policy for alphabetical order in production and pull request images.
- Updated filterTags pattern in ```image-policy.yaml``` for ```juror-public``` app to match pull request images with a different number.
> juror deployment into ITHC and Demo via image policy

- apps/juror/juror-scheduler-api/ithc.yaml
https://centralgovernmentcgi.atlassian.net/browse/JM-7626
Update to scheduler-api on juror
deployment into ITHC for testing
- Updated the image for the Java values, adding \"+ image: sdshmctspublic.azurecr.io/juror/scheduler-api:pr-234-3335ffa-20241015080630\" and including the \"ingressHost: juror-scheduler-api.ithc.platform.hmcts.net\".
> deploying update to juror-scheduler-api for release3

- apps/jenkins/jenkins/ptl/jenkins.yaml
https://tools.hmcts.net/jira/browse/MRD-221
Add a new dashboard for the MRD team
N/A
- Added configuration for a new buildMonitor for \"Master and Reference Data Dashboard\" with specific includeRegex pattern and title.
> Add MRD Jenkins project dashboard

- apps/pre/pre-api/prod.yaml
- apps/pre/pre-portal/prod.yaml
- apps/pre/prod/base/kustomization.yaml
DO NOT MERGE until release
- Added `MEDIA_SERVICE: MediaKind` under `spec` section.
- Updated the `PLATFORM_ENV_TAG` value to `Production`.
- Added `USE_MK_ON_WATCH_PAGE: true` under `spec` section.
- Added `./pre-api-cron-cleanup-live-events/pre-api-cron-cleanup-live-events.yaml` and `./pre-api-cron-cleanup-streaming-locators/pre-api-cron-cleanup-streaming-locators.yaml` to the resources.
> Switching PRE from AMS to MK

- apps/pip/data-management/test.yaml
- apps/pip/frontend/test.yaml
https://tools.hmcts.net/jira/browse/PUB-2233
Testing parties at hearing level
- `test.yaml` in `apps/pip/data-management`: added a new field `image` with the value `sdshmctspublic.azurecr.io/pip/data-management:pr-638-d199d14-20241016085844`
- `test.yaml` in `apps/pip/frontend`: updated the `image` field to `sdshmctspublic.azurecr.io/pip/frontend:pr-1359-514000b-20241011095331` and removed several keyVaults and alias configurations.
> PUB-2233-Test-Env

- apps/pre/pre-api/prod.yaml
- apps/pre/pre-portal/prod.yaml
- apps/pre/prod/base/kustomization.yaml
DO NOT MERGE until release
- `apps/pre/pre-api/prod.yaml`:
- Added `MEDIA_SERVICE: MediaKind` to the environment variables.
- `apps/pre/pre-portal/prod.yaml`:
- Set `USE_MK_ON_WATCH_PAGE: true` to enable a new feature.
- `apps/pre/prod/base/kustomization.yaml`:
- Added cron jobs for cleanup of live events and streaming locators in the Kustomization resources.
> Pre mk go live

- apps/pre/pre-api/prod.yaml
- Added a new environment variable `TRIGGER` with the value `init-1`.
- Updated the `MEDIA_SERVICE` environment variable to `MediaKind`.
> trigger rebuild prod Update prod.yaml

- apps/pip/data-management/test.yaml
- apps/pip/frontend/test.yaml
https://tools.hmcts.net/jira/browse/PUB-2326
Testing PUB-2326
- Removed the `image` and `environment` fields from the configuration.
- Updated the `image` field to a newer version for the pip/frontend service.
> PUB-2326 - Updated pip test

- apps/pre/pre-api-cron-cleanup-streaming-locators/prod.yaml
- Updated the schedule for the CronJob from \"30 18 * * *\" to \"0 0 * * *\" 🔄
> PRE cleanup streaming locators at midnight in prod

- apps/pip/frontend/test.yaml
https://tools.hmcts.net/jira/browse/PUB-2625
Update test image for testing Crime IDAM integration
- Updated the image to `sdshmctspublic.azurecr.io/pip/frontend:pr-1322-49f8b8d-20241016142122`
- Added keyVaults and their respective secrets for environment configuration.
> PUB-1566 Update test image for testing Crime IDAM integration

- apps/darts-modernisation/darts-api/demo.yaml
- apps/darts-modernisation/darts-api/ithc.yaml
- apps/darts-modernisation/darts-api/prod.yaml
- apps/darts-modernisation/darts-api/stg.yaml
- apps/darts-modernisation/darts-api/test.yaml
- apps/darts-modernisation/darts-automated-tasks/demo.yaml
- apps/darts-modernisation/darts-automated-tasks/ithc.yaml
- apps/darts-modernisation/darts-automated-tasks/prod.yaml
- apps/darts-modernisation/darts-automated-tasks/stg.yaml
- apps/darts-modernisation/darts-automated-tasks/test.yaml
See [DMP-4015](https://tools.hmcts.net/jira/browse/DMP-4015)
Added new environment variables
- demo.yaml, ithc.yaml, prod.yaml, stg.yaml, and test.yaml in apps/darts-modernisation/darts-api/: Added a new environment variable 'PROCESS_E2E_ARM_RPO' with the value 'false'.
- demo.yaml, ithc.yaml, prod.yaml, stg.yaml, and test.yaml in apps/darts-modernisation/darts-api/: Added the environment variable 'ARM_RPO_HOURS' with the value '24h'.
- demo.yaml, ithc.yaml, prod.yaml, stg.yaml, and test.yaml in apps/darts-modernisation/darts-automated-tasks/: Added a new environment variable 'PROCESS_E2E_ARM_RPO' with the value 'false'.
- prod.yaml in apps/darts-modernisation/darts-automated-tasks/: Added the environment variable 'ARM_RPO_HOURS' with the value '24h'.
> Added new environment variables

- apps/pre/pre-portal/stg.yaml
- File: stg.yaml
- Added a new environment variable DYNATRACE_JSTAG with a Dynatrace JavaScript tag url.
> PRE Dynatrace tag

- apps/jenkins/jenkins/jenkins-controller-version.yaml
https://tools.hmcts.net/jira/browse/DTSPO-19576
- New controller version fixes issues seen above
- linked PRs - https://github.com/hmcts/cnp-jenkins-docker/pull/1524 & https://github.com/hmcts/cnp-jenkins-docker/pull/1524
- Updated `jenkins-controller-version.yaml`
- Changed the Jenkins controller tag from 2.481-783 to 2.481-785 🚀
> Jenkins: controller version to 2.481-785

- apps/darts-modernisation/darts-api/darts-api.yaml
- Added a `nodejs` section with an image and replicas configuration for the darts portal.
- Increased memoryLimits to '3G' and added a memoryRequests of '2G'.
> DARTS API - 0 nodejs replicas

- apps/darts-modernisation/darts-api/darts-api.yaml
- apps/darts-modernisation/darts-automated-tasks/darts-automated-tasks.yaml
- `darts-api.yaml` 🛠️
- added configuration for disabling autoscaling by setting `autoscaling` to `false`
- `darts-automated-tasks.yaml` 🛠️
- added configuration for disabling autoscaling by setting `autoscaling` to `false`
> DARTS fixes - 0 nodejs replicas

- apps/pre/pre-api-cron-cleanup-live-events/prod.yaml
- apps/pre/pre-api-cron-cleanup-streaming-locators/prod.yaml
- Update "clean up streaming locator" cron job to use MediaKind
- Update "clean up live event" cron job to use MediaKind
> Fix: pre-api cron jobs to use MediaKind

- apps/juror/juror-scheduler-execution/ithc.yaml
This deployment is for testing in ITHC
- Updated `ithc.yaml` in `apps/juror/juror-scheduler-execution`:
- Changed the image version to `pr-227-c53685f-20241022114307` for the `scheduler-execution` module.
> juror scheduler execution service release3 deployment to ITHC

- apps/met/batch-jobs/test.yaml
- apps/met/pod-delete-cron/test.yaml
- `apps/met/batch-jobs/test.yaml` 🔄
- Updated schedule from \"0 19 * * *\" to \"0-59/5 * * *\"
- Changed suspend from true to false
- `apps/met/pod-delete-cron/test.yaml` 🔄
- Updated schedule from \"45 10 * * *\" to \"0-59/10 * * *\"
- No other changes made
> feat: update libragob test cron schedules

- apps/met/batch-jobs/test.yaml
1. Secrets have been added to the keyvault as asked per the ticket from Mark
2. Raising this PR now to map the secrets in flux to the pod volume mount.
- Added new environment variables for PostgreSQL and SFTP configurations.
- Added environment variables for Themis gateway credentials.
> Adding key vault secrets to map the secrets in flux to the pod volume mount

- apps/pip/frontend/stg.yaml
Testing in Env
yaml
apps/pip/frontend/stg.yaml
- Added new image for nodejs
- Updated replicas to 2
```
> PUB-2617 - Updated staging

- apps/pre/prod/base/kustomization.yaml
- apps/pre/stg/base/kustomization.yaml
- apps/pre/test/base/kustomization.yaml
- Added the pre-api-cron-close-pending-cases to the resources and patches.
- Added the pre-api-cron-close-pending-cases to the resources and patches.
- Added the pre-api-cron-close-pending-cases to the resources and patches.
> add cronjob for PRE

- apps/pip/frontend/test.yaml
https://tools.hmcts.net/jira/browse/PUB-2636
Update test image for testing removal of Firewall custom rule
- Updated the image for the pip-frontend test to reference a new image: `sdshmctspublic.azurecr.io/pip/frontend:pr-1292-144d009-20241024134322` 🐳
> PUB-2485 Update test image for testing removal of Firewall custom rule

- apps/pip/frontend/stg.yaml
- apps/pip/frontend/test.yaml
https://tools.hmcts.net/jira/browse/PUB-2636
Revert test image
- **stg.yaml**
- Removed a replica and updated the image for the frontend application in the staging environment.
- Updated the image for the frontend application in the test environment.
> PUB-2485 Revert test image

- apps/juror/juror-scheduler-execution/ithc.yaml
https://centralgovernmentcgi.atlassian.net/browse/JM-8273
update to juror scheduler execution service to fix issue
This deployment is for testing the update to timeouts
- Updated the image tag for the Java service from `pr-227` to `pr-229` 🐞
> juror update to ITHC scheduler execution service

- apps/juror/juror-scheduler-execution/ithc.yaml
https://centralgovernmentcgi.atlassian.net/browse/JM-8273
update to scheduler execution image name
deployment for testing
- Updated the `java` image from `pr-229-c53685f-20241022114307` to `pr-229-d043b28-20241028124749`.
- Updated the `ingressHost` to `juror-scheduler-execution.ithc.platform.hmcts.net`.
> juror deployment for scheduler-execution service

- apps/pre/pre-portal/test.yaml
- Added a new environment variable `TRIGGER` with the value `init-1`.
- Updated the `pdb` configuration to disable the feature.
> trigger test env Update test.yaml

- apps/juror/juror-api/image-policy.yaml
- apps/juror/juror-bureau/image-policy.yaml
- apps/juror/juror-public/image-policy.yaml
Juror deployment into ITHC and Demo for release3
Testing to be done on this deployment
- Updated image filter patterns for `juror-api` and `juror-bureau` to match the specified format.
- Added annotations for `juror-api` and `juror-bureau` indicating that prod-automated is disabled.
- Updated image filter pattern for `juror-public` to match the specified format.
> Juror deployments into ITHC and Demo via image policy

- apps/pre/pre-api-cron-close-pending-cases/pre-api-cron-close-pending-cases.yaml
- pre-api-cron-close-pending-cases.yaml
- Updated the releaseName to pre-api-cron-close-pending-cases
- Set java to enabled: false and job to enabled: true
- Added environment variable TASK_NAME: ClosePendingCases
- Updated the chart spec with sourceRef and interval
> formatting cronjob for PRE

- apps/juror/juror-scheduler-execution/ithc.yaml
https://centralgovernmentcgi.atlassian.net/browse/JM-8273
updated logging
deployment to test logging
- Updated the image to `sdshmctspublic.azurecr.io/juror/scheduler-execution:pr-229-01e5fc6-20241028154328`
- Modified the ingressHost to `juror-scheduler-execution.ithc.platform.hmcts.net`
> juror deploy to scheduler execution service

- apps/darts-modernisation/darts-api/test.yaml
- Added `MODERNISED_DARTS_START_DATE` with value `2024-10-01`.
> testing RemoveDuplicateEventsProcessor

- apps/mi/mi-adf-shir-2/prod.yaml
- Updated the image version from \"prod-91ba39e-20240312133745\" to \"prod-91ba39e-20241028151058\" 🔄
> Fix image policy

- apps/pre/pre-portal/stg.yaml
- apps/pre/pre-portal/test.yaml
- stg.yaml
- Added a new environment variable \"TRIGGER\" with value \"init-1\"
> Trigger Update test.yaml

- apps/darts-modernisation/darts-api/darts-api.yaml
- apps/darts-modernisation/darts-automated-tasks/darts-automated-tasks.yaml
N/A
- this is no longer required as the chart in the repo does not include it
- **darts-api.yaml**
- Removed the nodejs section which contained image, replicas, and autoscaling information.
- **darts-automated-tasks.yaml**
- Removed the nodejs section which contained image, replicas, and autoscaling information.
> Removing nodejs chart from darts-api and darts-automated-tasks

- apps/met/themis-fe/themis-fe.yaml
- Changed the value of `TEMP_VAR` from 1 to 0.
> Update themis-fe.yaml restart 11/04/2024

- apps/pip/frontend/test.yaml
Testing change
- The `test.yaml` file in `apps/pip/frontend` has been modified to update the image for the `nodejs` section to `sdshmctspublic.azurecr.io/pip/frontend:pr-1365-0bb2b40-20241031105011`.
- The number of replicas has also been updated to 2.
> PUB-2617 - Testing change

- apps/pip/frontend/test.yaml
Testing in Test Env
- Removed a section that contained a list of keyVaults and their respective secrets and aliases.
- Updated the environment variables DATA_MANAGEMENT_URL and ACCOUNT_MANAGEMENT_URL.
> PUB-2617 - Updated test env

- apps/pdda/pdda-public-display-manager/stg.yaml
- File: apps/pdda/pdda-public-display-manager/stg.yaml
- Changed the value of TRIGGER_RESTART from 1 to 0
- Updated LOGGING_LEVEL_UK_GOV_HMCTS_PDM, LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_SECURITY, and LOGGING_LEVEL_COM_ZAXXER_HIKARI to DEBUG
> Trigger restart of PDM.

- apps/pip/frontend/demo.yaml
Deploy SSO to Demo env
- Added a new image for the frontend with a specific tag.
- Added key vaults and their respective secrets to the environment variables.
- Updated the environment URLs for data management and account management.
> PUB-2364 Deploy SSO to Demo env

- apps/pip/frontend/test.yaml
Deploy SSO to Test env
- `test.yaml` 🛠️
- Changed the image for `pip-frontend`
- Added keyVaults and their respective secrets for the frontend app
- Updated environment URLs for data management and account management
> PUB-2364 Deploy SSO to Test env

- apps/pip/frontend/test.yaml
Deploy SSO to Test with logging
- Updated the image version for the frontend service in the test environment.
- Changed the image from \"sdshmctspublic.azurecr.io/pip/frontend:pr-1379-9efcbe8-20241106085811\" to \"sdshmctspublic.azurecr.io/pip/frontend:pr-1380-6990680-20241106114320\" 🐞
> PUB-2364 Deploy SSO to Test with logging

- apps/pip/frontend/demo.yaml
- apps/pip/frontend/test.yaml
Update SSO images for Test and Demo
- Changed `demo.yaml` and `test.yaml` in `apps/pip/frontend/`
- Updated the image tag for the `frontend` service in both files to `pr-1379-67d2edc-20241107104349`
> PUB-2364 Update SSO images for Test and Demo

- apps/darts-modernisation/darts-portal/demo.yaml
- Changed `EVENT_OBFUSCATION_ENABLED` from `false` to `true` 🔄
> DARTS portal demo set EVENT_OBFUSCATION_ENABLED true

- apps/pip/frontend/ithc.yaml
- apps/pip/frontend/stg.yaml
Deploy SSO to Staging and ITHC
- ithc.yaml```:
- Added environment variables and updated image for PIP frontend in the ithc environment.
- ```stg.yaml```:
- Added environment variables and updated image for PIP frontend in the staging environment.
> PUB-2364 Deploy SSO to Staging and ITHC

- apps/pip/frontend/ithc.yaml
- apps/pip/frontend/stg.yaml
Fix key vault values in Staging and ITHC
- Updated apps/pip/frontend/ithc.yaml
- Changed resourceGroup from \"pip-ss-test-rg\" to \"pip-ss-ithc-rg\"
- Renamed secrets \"auto-pip-test-pip-frontend-test-id\" to \"auto-pip-ithc-pip-frontend-ithc-id\" and \"auto-pip-test-pip-frontend-test-pwd\" to \"auto-pip-ithc-pip-frontend-ithc-pwd\"
- Updated apps/pip/frontend/stg.yaml
- Changed resourceGroup from \"pip-ss-test-rg\" to \"pip-ss-stg-rg\"
- Renamed secrets \"auto-pip-test-pip-frontend-test-id\" to \"auto-pip-stg-pip-frontend-stg-id\" and \"auto-pip-test-pip-frontend-test-pwd\" to \"auto-pip-stg-pip-frontend-stg-pwd\"
> PUB-2364 Fix key vault values in Staging and ITHC

- apps/pip/frontend/ithc.yaml
- apps/pip/frontend/stg.yaml
Remove SSO image from ITHC and Staging
- ithc.yaml```: Removed a long list of environment variables and their aliases that were previously hardcoded, likely moved to a more secure location or configuration setup.
- ```stg.yaml```: Similar to the above, removed a long list of environment variables and their aliases from the file.
> PUB-2364 Remove SSO image from ITHC and Staging

- apps/pre/pre-api/test.yaml
- apps/pre/pre-portal/test.yaml
https://tools.hmcts.net/jira/browse/S28-3445
- `apps/pre/pre-api/test.yaml`:
- Added `MEDIA_SERVICE: MediaKind` under `spec` section.
- `apps/pre/pre-portal/test.yaml`:
- Added `USE_MK_ON_WATCH_PAGE: true` under `spec` section.
> Update test with stg MK options

- apps/pre/pre-portal/stg.yaml
- Added the `TS_AND_CS_REDIRECT_ENABLED: true` configuration.
- Added the `ENABLE_CASE_STATE_COLUMN: true` configuration.
> Enable 4.1.0 release features

- apps/juror/juror-scheduler-execution/ithc.yaml
juror deployment of updated scheduler execution service
- Updated the `image` value to `sdshmctspublic.azurecr.io/juror/scheduler-execution:pr-231-fe03bd0-20241108154215` 🔧
> juror deployment of scheduler execution service to ITHC

- apps/pdda/pdda-public-display-manager/stg.yaml
- Updated the environment variable `TRIGGER_RESTART` from `0` to `1`
- Changed logging levels for `UK_GOV_HMCTS_PDM`, `ORG_SPRINGFRAMEWORK_SECURITY`, and `COM_ZAXXER_HIKARI` to `DEBUG`
> Restart Pdm app after the delete of pdda-app-secret

- apps/darts-modernisation/darts-api/darts-api.yaml
- Added configuration for `darts-portal` with `ingressHost` set to `darts-portal-nodejs.{{ .Values.global.environment }}.apps.hmcts.net`. ⚙️
> Fixing duplicate ingress hosts for DARTS portal

- apps/darts-modernisation/darts-api/darts-api.yaml
- apps/darts-modernisation/darts-automated-tasks/darts-automated-tasks.yaml
- Modified file: darts-api.yaml
- Added darts-portal replicas: 0
- Added autoscaling enabled: false
- Modified file: darts-automated-tasks.yaml
- Added darts-portal replicas: 0
- Added autoscaling enabled: false
> Removing DARTS portal deployments for DARTS API

- apps/darts-modernisation/darts-api/darts-api.yaml
- apps/darts-modernisation/darts-automated-tasks/darts-automated-tasks.yaml
- darts-api.yaml 🛠️:
- Set the `darts-portal` to `enabled: false`.
- darts-automated-tasks.yaml 🛠️:
- Set the `darts-portal` to `enabled: false`.
> DARTS portal disabled for DARTS API

- apps/azureserviceoperator-system/aso/kustomization.yaml
See [DTSPO-22106](https://tools.hmcts.net/jira/browse/DTSPO-22106)
upgrade aso to 2.10.0 version 
Tested on sbox on https://github.com/hmcts/sds-flux-config/pull/5734
> upgrade ASO to version 2.10.0 

- apps/darts-modernisation/darts-portal/demo.yaml
N/A
md
apps/darts-modernisation/darts-portal/demo.yaml
- Changed EVENT_OBFUSCATION_ENABLED from true to false
```
> Disabled DARTS event obfuscation on demo

- apps/pre/pre-portal/demo.yaml
- `demo.yaml`: 
- Added `TS_AND_CS_REDIRECT_ENABLED: true`
- Added `ENABLE_CASE_STATE_COLUMN: true`
> PRE release 4.1 demo feature toggles

- apps/pre/pre-api-cron-close-pending-cases/demo.yaml
- Enable close pending cases cron job in demo
- Changed the `suspend` value from `true` to `false` to enable the job to run regularly.
- Updated the job schedule to run every hour.
> Fix: PRE Enable close pending cases cron in demo

- apps/pre/demo/base/kustomization.yaml
- Updated `apps/pre/demo/base/kustomization.yaml`
- Added a new resource `pre-api-cron-close-pending-cases.yaml` to the list of resources
- Added a path for the new resource `pre-api-cron-close-pending-cases/demo.yaml`
> Add cron close cases to demo

- apps/monitoring/cveinfo/cveinfo.yaml
Getting `OOMKilled`, increasing resource limit for the job when i runs.
- Added resources requests for CPU and memory.
- CPU request: 250m
- Memory request: 1Gi
> Updated request resource job run

- apps/mi/mi-adf-shir/dev.yaml
See [RMI-3314](https://tools.hmcts.net/jira/browse/RMI-3314)
- Updated the image for mi-adf-shir to `sdshmctspublic.azurecr.io/mi/adf-integration-runtime:dev-7971dcc-20241119154447`
- Increased replica count to 4
- Set memory limits to '4096Mi'
- Environment set to \"dev\"
> Fix SHIR version on dev

- apps/monitoring/cveinfo/cveinfo.yaml
Overwriting default resource request limits
- Increased the memory limit to 2Gi. 🚀
> Update resource request

- apps/mi/mi-adf-shir/dev.yaml
- Updated the image version for the ADF integration runtime to `dev-7971dcc-20241119154447`.
- Increased the replica count to 4.
- Adjusted the memory limit to '4096Mi' for the development environment.
> Pin SHIR in dev

- apps/juror/juror-api/image-policy.yaml
- apps/juror/juror-bureau/image-policy.yaml
- apps/juror/juror-public/image-policy.yaml
Juror deployments for release5 
release for testing in ITHC and Demo
- **image-policy.yaml**
- Updated image tag patterns for juror-api, juror-bureau, and juror-public.
- Updated annotations for prod-automated to be disabled for juror-bureau and juror-bureau-pr.
> juror deployments for release5

- apps/darts-modernisation/darts-api/demo.yaml
- apps/darts-modernisation/darts-api/ithc.yaml
- apps/darts-modernisation/darts-api/prod.yaml
- apps/darts-modernisation/darts-api/stg.yaml
- apps/darts-modernisation/darts-api/test.yaml
- apps/darts-modernisation/darts-automated-tasks/demo.yaml
- apps/darts-modernisation/darts-automated-tasks/ithc.yaml
- apps/darts-modernisation/darts-automated-tasks/prod.yaml
- apps/darts-modernisation/darts-automated-tasks/stg.yaml
- apps/darts-modernisation/darts-automated-tasks/test.yaml
(https://tools.hmcts.net/jira/browse/DMP-4144)
Added the new env variable IS_MOCK_ARM_RPO_DOWNLOAD_CSV.
- [x ] README and other documentation has been updated / added (if needed)
- [x ] tests have been updated / new tests has been added (if needed)
- Updated various YAML files in the `darts-api` and `darts-automated-tasks` directories to include the new parameter `IS_MOCK_ARM_RPO_DOWNLOAD_CSV` with different values based on the environment (true or false).
> DMP-4144 ARM RPO - Integrate all Endpoints for ARMRPOPollAutomatedTask

- apps/pip/frontend/demo.yaml
- apps/pip/frontend/test.yaml
- Update expired SSO image in demo
- Remove SSO image from test
- Updated the `image` field with a new tag: `pr-1379-f0daad5-20241120105906`
- Removed the `image` field with the tag: `pr-1379-67d2edc-20241107104349`
> PUB-2364 Update expired SSO image in demo

- apps/vh/admin-web/demo.yaml
- apps/vh/admin-web/image-policy.yaml
- apps/vh/booking-queue-subscriber/demo.yaml
- apps/vh/booking-queue-subscriber/image-policy.yaml
- apps/vh/bookings-api/demo.yaml
- apps/vh/bookings-api/image-policy.yaml
- apps/vh/notification-api/demo.yaml
- apps/vh/notification-api/image-policy.yaml
- apps/vh/scheduler-jobs/demo.yaml
- apps/vh/scheduler-jobs/image-policy.yaml
- apps/vh/user-api/demo.yaml
- apps/vh/user-api/image-policy.yaml
- apps/vh/video-api/demo.yaml
- apps/vh/video-api/image-policy.yaml
- apps/vh/video-web/demo.yaml
- apps/vh/video-web/image-policy.yaml
Jira link
https://tools.hmcts.net/jira/browse/VIH-11180
Changing Demo env Flux config for all apps to use demo image policy instead of dev
- Updated demo.yaml and image-policy.yaml in apps/vh/admin-web: Changed image version for demo environment of admin-web.
- Updated image-policy.yaml in apps/vh/booking-queue-subscriber: Added a new image policy for demo environment of booking-queue-subscriber.
- Updated demo.yaml and image-policy.yaml in apps/vh/bookings-api: Changed image version and added a new image policy for demo environment of bookings-api.
- Updated demo.yaml and image-policy.yaml in apps/vh/notification-api: Changed image version and added a new image policy for demo environment …
> VIH-11180 Add demo image

- apps/darts-modernisation/darts-api/demo.yaml
- apps/darts-modernisation/darts-api/stg.yaml
- apps/darts-modernisation/darts-automated-tasks/demo.yaml
- apps/darts-modernisation/darts-automated-tasks/stg.yaml
Enabled PROCESS_E2E_ARM_RPO for staging and demo
ℹ️ demo.yaml:
- Set PROCESS_E2E_ARM_RPO to true
ℹ️ stg.yaml:
- Set PROCESS_E2E_ARM_RPO to true
These changes were made in the darts-api and darts-automated-tasks directories.
> DARTS - Enable PROCESS_E2E_ARM_RPO for staging and demo

- apps/pre/pre-portal/stg.yaml
See [S28-2792](https://tools.hmcts.net/jira/browse/S28-2792)
Added a feature flag to disable this change in Prod and enable in Stg
- Added the `REMOVE_WITNESS_LAST_NAME` environment variable set to true.
> Add flag for remove witness last name

- apps/pip/frontend/prod.yaml
https://tools.hmcts.net/jira/browse/PUB-2663
Restart pod
- Changed the value of `RESTART_PROD` from `true` to `false`.
> PUB-2663 - Updated pod

- apps/mi/mi-adf-shir-2/prod.yaml
Enable auto-updated on SHIR-2
- **prod.yaml**: 
- Updated the image tag from `prod-91ba39e-20240312133745` to `prod-91ba39e-20241028151058`.
> enable shir latest version

- apps/juror/juror-api/image-policy.yaml
- apps/juror/juror-bureau/image-policy.yaml
Update for interim-5 release testing on Juror 
- Updated `image-policy.yaml` in `juror-api` and `juror-bureau` apps
- Updated image tag pattern from `^pr-808-` to `^pr-815-` in `juror-api` image policy
- Updated image tag pattern from `^pr-843-` to `^prod-` in `juror-bureau` image policy
> juror deployment into ITHC and Demo for testing

- apps/juror/juror-api/image-policy.yaml
- apps/juror/juror-bureau/image-policy.yaml
Juror deployment for release5 into ITHC and Demo
Deployment is for testing
- Changed `image-policy.yaml` in `juror-api` and `juror-bureau` apps
- Updated image tag pattern from `'^pr-815-[a-f0-9]+-(?P<ts>[0-9]+)'` to `'^pr-808-[a-f0-9]+-(?P<ts>[0-9]+)'` for `juror-api`
- Updated image tag pattern from `'^prod-[a-f0-9]+-(?P<ts>[0-9]+)'` to `'^pr-843-[a-f0-9]+-(?P<ts>[0-9]+)'` for `juror-bureau`
> juror deployment for release5 into ITHC and Demo

- apps/pip/frontend/test.yaml
https://tools.hmcts.net/jira/browse/PUB-2664
Update test image for ServiceNow link
- The file `test.yaml` in `apps/pip/frontend` has been modified.
- The `keyVaults` block has been removed, and an `image` field has been added.
- Replicas have been reduced from 60 to 2.
- Some `environment` variables have been added.
> PUB-2664 Update test image for ServiceNow link

- apps/pip/frontend/test.yaml
https://tools.hmcts.net/jira/browse/PUB-2664
Removed test image
- Removed the `image` field referencing a specific image tag.
- Environment variables `DATA_MANAGEMENT_URL` and `ACCOUNT_MANAGEMENT_URL` are still present.
> PUB-2664 Removed test image

- apps/pre/pre-api-cron-close-pending-cases/prod.yaml
- Updated the job schedule from \"0 * * * *\" to \"*/5 * * * *\" 🔄
> run pre disassociation every 5mins in prod

- apps/pre/pre-portal/prod.yaml
- Changed the value of `TS_AND_CS_REDIRECT_ENABLED` from `true` to `false`.
- Changed the value of `ENABLE_CASE_STATE_COLUMN` from `true` to `false`.
> Disable pre-portal Ts&Cs and Case State column

- apps/pre/demo/base/kustomization.yaml
https://tools.hmcts.net/jira/browse/S28-3563
- kustomization.yaml
- Added two new resources for cron cleanup live events and streaming locators
- Updated paths for cron cleanup streaming locators and live events demo files
> Add pre crons to demo Update kustomization.yaml

- apps/pre/pre-portal/stg.yaml
- Updated the `DYNATRACE_JSTAG` URL from `https://js-cdn.dynatrace.com/jstag/17177a07246/bf24054dsx/636bef1033a59525_complete.js` to `https://js-cdn.dynatrace.com/jstag/17177a07246/bf24054dsx/9f9a4af51c7fab2c_complete.js` 🔄
> Update PRE DT tag in stg

- apps/pre/pre-api-cron-close-pending-cases/prod.yaml
- Changed file: prod.yaml
- Updated job schedule from \"*/5 * * * *\" to \"0 * * * *\"
- The job schedule was modified to run at the top of every hour instead of every 5 minutes.
> revert cron to hourly Update prod.yaml

- apps/pip/frontend/test.yaml
- apps/pip/subscription-management/test.yaml
Deploy changes on TEST env only
- `test.yaml`:
- Added image and image tags for both frontend and subscription management services.
- Updated environment variables for data management and account management URLs.
> PUB-2682 Deploy list type subscription on Test

- apps/pre/pre-portal/prod.yaml
- Added the DYNATRACE_JSTAG environment variable with a specific URL. 🚀
> Add DT RUM jstag to PRE portal

- apps/juror/juror-api/image-policy.yaml
- apps/juror/juror-bureau/image-policy.yaml
Juror deployment to ITHC and Demo via image policy
Deployments are for testing
- `image-policy.yaml` 🖼️
- Added annotations for prod-automated disabled to both juror-api and juror-bureau sections
- Specified filterTags and policy to extract and order image tags accordingly for prod and PR environments.
> juror deployment for ITHC and Demo

- apps/juror/juror-scheduler-execution/image-policy.yaml
updating deployment for juror scheduler execution service in ITHC and Demo 
Deployments are for testing
- File: image-policy.yaml
- Changed the pattern from '^pr-1-[a-f0-9]+-(?P<ts>[0-9]+)' to '^pr-233-[a-f0-9]+-(?P<ts>[0-9]+)' for the filterTags section.
> update to ITHC and Demo for juror scheduler execution service

- apps/juror/juror-scheduler-execution/ithc.yaml
- Updated the image value for Java to `sdshmctspublic.azurecr.io/juror/scheduler-execution:pr-231-fe03bd0-20241108154215`  🐞
> juror: define ithc imagepolicy

- apps/juror/juror-public/image-policy.yaml
Updating image-policy for juror-public deployment into ITHC and Demo
Changes enable deployments for testing
- **image-policy.yaml:**
- Changed the pattern from '^pr-272-[a-f0-9]+-(?P<ts>[0-9]+)' to '^pr-275-[a-f0-9]+-(?P<ts>[0-9]+)' in the filterTags section.
>  juror-public deployment for ITHC and Demo

- apps/jenkins/jenkins/jenkins.yaml
- Changed the image for the `configAutoReload` sidecar from `kiwigrid/k8s-sidecar:1.25.2` to `hmctspublic.azurecr.io/imported/kiwigrid/k8s-sidecar:1.25.2` 🐳
> fix: switch to acr cached image

- apps/darts-modernisation/darts-api/stg.yaml
- Added a new environment variable `MODERNISED_DARTS_START_DATE` with the value `'2024-12-01'` 🆕.
> Set Modernised darts start date env variable on staging

- apps/juror/juror-public/demo.yaml
- apps/juror/juror-public/ithc.yaml
Update to deploy latest juror api image into ITHC and Demo
Deployment is for testing
- Updated `demo.yaml` and `ithc.yaml` in `apps/juror/juror-public` directory
- Changed the image version from `pr-275-03d7436-20241217151441` to `pr-830-a1cb60d-20241218123913` for both files
> update to juror api deployment

- apps/toffee/dev/aso/toffee-postgres-config.yaml
- apps/toffee/dev/aso/toffee-postgres.yaml
- apps/toffee/dev/sops-secrets/kustomization.yaml
- apps/toffee/dev/sops-secrets/recipe-backend-values.enc.yaml
DTSPO-18332
test postgres-setup script
- Created a new file `toffee-postgres-config.yaml` in the `apps/toffee/dev/aso/` directory.
- Added configuration for Flexible Servers in the `toffee-postgres.yaml` file in the `apps/toffee/dev/aso/` directory.
- Added new files `kustomization.yaml` and `recipe-backend-values.enc.yaml` in the `sops-secrets` directory to manage Kustomize resources and encrypted secret values, respectively.
> DTSPO-18332 - test postgres-setup script

- apps/pip/frontend/test.yaml
https://tools.hmcts.net/jira/browse/PUB-2716
Testing filter overlap
- Added a new `image` under `nodejs` with the value `sdshmctspublic.azurecr.io/pip/frontend:pr-1409-1b13bd0-20250107162605`
- Updated the number of `replicas` to 2
> PUB-2716 - Fixed filter overlap

- apps/toffee/dev/base/kustomization.yaml
- apps/toffee/dev/sops-secrets/recipe-backend-values.enc.yaml
…stomization
DTSPO-18332
test changes to script: automate adding aso resource group to base kustomization
- Updated kustomization.yaml in /apps/toffee/dev/base:
- Added resource-group.yaml to resources.
- Updated recipe-backend-values.enc.yaml in /apps/toffee/dev/sops-secrets:
- Updated PASSWORD encryption data.
- Updated created_at and lastmodified timestamps.
> DTSPO-18332 - test changes to script: automate adding aso resource group to base kustomization

- apps/toffee/dev/aso/toffee-postgres-config.yaml
- apps/toffee/dev/aso/toffee-postgres.yaml
DTSPO-18332
update api server version to allow postgres v16
- `toffee-postgres-config.yaml` 🔄 Updated `apiVersion` from `dbforpostgresql.azure.com/v1api20210601` to `dbforpostgresql.azure.com/v1api20230601preview`.
- `toffee-postgres.yaml` 🔄 Updated `apiVersion` from `dbforpostgresql.azure.com/v1api20210601` to `dbforpostgresql.azure.com/v1api20230601preview`.
> DTSPO-18332 - update api server version to allow postgres v16

- apps/juror/dev/aso/juror-postgres.yaml
- Modified file: apps/juror/dev/aso/juror-postgres.yaml
- Increased the version from \"14\" to \"16\"
- Added a new sku with name \"Standard_D2ds_v5\" and tier \"GeneralPurpose\"
> update to postgres 16 and use GeneralPurpose

- apps/toffee/dev/aso/toffee-postgres.yaml
- apps/toffee/dev/sops-secrets/recipe-backend-values.enc.yaml
DTSPO-18332
test new script changes to postgres.yaml file
- `toffee-postgres.yaml` 📦
- Added a new sku with name \"Standard_D2ds_v5\" and tier \"GeneralPurpose\".
- `recipe-backend-values.enc.yaml` 📄
- Updated the password encryption with a new value.
- Updated the `created_at` and `lastmodified` timestamps.
> DTSPO-18332 - test new script changes to postgres.yaml file

- apps/pip/frontend/test.yaml
https://tools.hmcts.net/jira/browse/PUB-2718
Crime Idam testing on TEST environment only
- Added image reference for the frontend with a specific tag.
- Added keyVaults and their corresponding resource group and secrets for the frontend application environment.
> PUB-2718 Crime Idam Testing

- apps/toffee/dev/sops-secrets/recipe-backend-values.enc.yaml
DTSPO-18332
replace password creation step due to known issue with openssl rand base64 encode
- Updated the `PASSWORD` value in the `sops-secrets/recipe-backend-values.enc.yaml` file.
- Changed the `created_at` and `enc` values to new values.
- Modified the `lastmodified` and `mac` values to new values.
> DTSPO-18332 - replace password creation step due to known issue with openssl rand base64 encode

- apps/toffee/dev/sops-secrets/recipe-backend-values.enc.yaml
DTSPO-18332
base64 encode password for secret
- `recipe-backend-values.enc.yaml`
- Updated PASSWORD encryption values
- Updated created_at and lastmodified timestamps
- Updated mac encryption value.
> DTSPO-18332 - base64 encode password for secret

- apps/pre/pre-portal/prod.yaml
https://tools.hmcts.net/jira/browse/DTSPO-23284
- Changed the value of the `TRIGGER` parameter from `init-1` to `init-2`. 🔄
> Trigger prod rebuild Update prod.yaml

- apps/juror/juror-public/ithc.yaml
JS-195:
https://tools.hmcts.net/jira/browse/JS-195
Add environmental settings for juror-public web-chat functionality
This change adds settings to enable testing in ITHC
- Added environment variables for web chat integration: `WEB_CHAT_UUID`, `WEB_CHAT_CHANNEL`, `WEB_CHAT_CHANNEL_UUID`, and `WEB_CHAT_TENNANT`.
> Juror JS-195 update ithc.yaml

- apps/darts-modernisation/darts-api/demo.yaml
- apps/darts-modernisation/darts-api/ithc.yaml
- apps/darts-modernisation/darts-api/prod.yaml
- apps/darts-modernisation/darts-api/test.yaml
- apps/darts-modernisation/darts-portal/demo.yaml
- apps/darts-modernisation/darts-portal/ithc.yaml
- apps/darts-modernisation/darts-portal/prod.yaml
- apps/darts-modernisation/darts-portal/test.yaml
---
1. apps/darts-modernisation/darts-api/demo.yaml
- Changed MANUAL_DELETION_ENABLED from false to true
- Changed EVENT_OBFUSCATION_ENABLED from false to true
2. apps/darts-modernisation/darts-api/ithc.yaml
- Changed MANUAL_DELETION_ENABLED from false to true
- Changed EVENT_OBFUSCATION_ENABLED from false to true
3. apps/darts-modernisation/darts-api/prod.yaml
- Changed MANUAL_DELETION_ENABLED from false to true
- Changed EVENT_OBFUSCATION_ENABLED from false to true
4. apps/darts-modernisation/darts-api/test.yaml
- Changed MANUAL_DELETION_ENABLED from false to true
- Changed EVENT_OBFUSCATION_ENABLED from false to true
5. apps/darts-modernisation/darts-portal/demo.yaml
- Changed MANUAL_DELETION_ENABLED from false to true
- Changed EVENT_OBFUSCATION_ENABLED from false to true
6. …
> Switch on manual deletion features

- apps/juror/juror-api/image-policy.yaml
- apps/juror/juror-bureau/image-policy.yaml
- apps/juror/juror-public/image-policy.yaml
Juror deployment into ITHC and Demo via image policy
- Updated `image-policy.yaml` in `juror-api` and `juror-bureau` to add annotations for disabling prod automated deployment.
- Added filterTags and policy settings for both `juror-api` and `juror-bureau`.
- Updated filterTags pattern in `juror-public` from '^pr-275...' to '^pr-291...'.
> deployment of juror app into ITHC and Demo

- apps/pre/pre-portal/prod.yaml
Fix https://tools.hmcts.net/jira/browse/S28-3628
See [S28-3628](https://tools.hmcts.net/jira/browse/S28-3628)
> Retrigger prod pod deployment (Update prod.yaml)

- apps/juror/juror-scheduler-execution/image-policy.yaml
JS-59 
Update to Juror scheduler execution service image policy for release5.2
- Updated image-policy.yaml``` in ```apps/juror/juror-scheduler-execution```:
- Updated the image pattern from '^pr-233-[a-f0-9]+-(?P<ts>[0-9]+)' to '^pr-237-[a-f0-9]+-(?P<ts>[0-9]+)'.
> update for juror scheduler exec service

- apps/juror/juror-public/prod.yaml
JS-195:
https://tools.hmcts.net/jira/browse/JS-195
Add environmental settings for juror-public web-chat functionality
Testing of environmental settings in ITHC
- Added new environment variables for web chat feature.
- Added WEB_CHAT_UUID, WEB_CHAT_CHANNEL, WEB_CHAT_CHANNEL_UUID, and WEB_CHAT_TENNANT with their respective values.
> Juror JS-195 update prod.yaml

- Docs/aso-setup-v2.md
- Docs/secrets-sops-encryption.md
DTSPO-18332
ASO setup postgres documentation
- **Docs/aso-setup-v2.md**
- Added a new file `aso-setup-v2.md` with instructions on configuring Azure Service Operator resources in the repository.
- Provides steps for configuring resource groups, service bus instances, and applying patches in the Kustomize setup.
- Includes instructions for creating SOPS secrets and referring to them in application helm charts.
- Also provides guidance for setting up PostgreSQL using the `postgres-setup.sh` script.
- **Docs/secrets-sops-encryption.md**
- Made minor formatting changes and added an example for using kube-prometheus-stack with sops encryption.
- Added a note about using the correct keyvault version for the environment.
> DTSPO-18332 - ASO setup postgres documentation

- apps/mi/mi-adf-shir/dev.yaml
Pin DEV SHIR to version 5.48.9106.2
- Updated the image version of the ADF integration runtime from `dev-2022-367d351-20240603132048` to `dev-8ecc906-20250120162319` 🔄
- Replica count increased to 4
- Memory limit set to '4096Mi'
> Bump up shir version

- apps/pip/frontend/test.yaml
Removed outdated frontend image from test env
- `test.yaml`
- Removed the image reference `sdshmctspublic.azurecr.io/pip/frontend:pr-1322-7569222-20250113103406` in line 8.
> Removed outdated frontend image from test env

- apps/met/themis-fe/test.yaml
See [DTSPO-23255](https://tools.hmcts.net/jira/browse/DTSPO-23255)
Change logging level from ERROR to INFO, so more information is provided.
None - Simple change.  Will change back, once issue has been resolved.
- Added logging_level_root to set the root logging level to INFO.
> LibraGob-Logging-INFO

- apps/met/themis-fe/test.yaml
swap themes-fe test
- The file `test.yaml` was modified.
- The following properties were removed: `UPDATES_FIXEDRATE_IN_MILLISECONDS`, `UPDATES_FIXEDRATE_LOW_PRIORITY_IN_MILLISECONDS`, `HIGH_PRIORITY_KEYS_PER_DAC`, `ALIAS_NAME`, `cacerts`, `cacerts-password`.
- The property `servicebus-connectionstring` was modified.
> swap themes-fe test

- apps/monitoring/cveinfo/cveinfo.yaml
Adding some more capacity request for the job to complete
- `cveinfo.yaml` 🔄
- Updated resource requests and limits for the job.
- Changed memory requests to 2Gi and CPU requests to 500m.
- Set CPU limits to 1000m.
> Adding more resource to job run

- apps/monitoring/cveinfo/cveinfo.yaml
cveinfo resource requests updated
- Updated file: cveinfo.yaml
- Added resource requests and limits for memory and CPU
- Updated job schedule from \"0 */4 * * 1-5\" to \"0 */5 * * 1-5\"
- Removed previous job memory and CPU requests and limits
> cveinfo resource requests updated

- apps/monitoring/cveinfo/cveinfo.yaml
Updating these default values
https://github.com/hmcts/chart-job/blob/master/job/values.yaml#L6C1-L9C19
- Updated cveinfo.yaml in apps/monitoring/cveinfo/cveinfo.yaml
- Changed memory and CPU requests and limits
- Updated job schedule to run every 4 hours on weekdays
> test as per chart values

- apps/pip/data-management/ithc.yaml
https://tools.hmcts.net/jira/browse/PUB-2727
Enable data-management testing support API on ITHC
- Added a new key-value pair `ENABLE_TESTING_SUPPORT_API: true` to the YAML file. 🚀
> PUB-2727 Enable data-management testing support API on ITHC

- apps/pre/pre-api-cron-cleanup-live-events/stg.yaml
- apps/pre/pre-api-cron-cleanup-streaming-locators/stg.yaml
https://tools.hmcts.net/jira/browse/S28-3669
- `pre-api-cron-cleanup-live-events/stg.yaml` 🔄
- Updated the schedule from \"30 17 * * *\" to \"0 19 * * *\"
- `pre-api-cron-cleanup-streaming-locators/stg.yaml` 🔄
- Updated the schedule from \"30 18 * * *\" to \"10 19 * * *\"
> Update cron schedule to run later

- apps/met/themis-fe/test.yaml
See [DTSPO-23255](https://tools.hmcts.net/jira/browse/DTSPO-23255)
Back out change to logging level, so that it returns to the lower level of ERROR.  As the issue has been resolved.
None, simple change, returning file to original condition.
yaml
- Removed the `logging_level_root: INFO` and `LOGGING_LEVEL_ROOT: INFO` lines
```
> DTSPO-23255-LigraGob-debug-level-error

- apps/pre/pre-api-cron-cleanup-live-events/stg.yaml
- Updated the job schedule from \"0 19 * * *\" to \"15 11 * * *\" 🔄
> Test PRE STG cleanup live events cron

- apps/darts-modernisation/darts-ucf-test-harness/test.yaml
[DMP-4548](https://tools.hmcts.net/jira/browse/DMP-4548)
- test.yaml
- Changed the number of replicas for the `java` service from 1 to 0.
- Added a new environment variable `TEST_HARNESS_AUTOMATION_TRANSFER_FORMAT: MTOM` 🚀
> DMP-4548 DARTS UCF test harness to use MTOM to gateway

- apps/darts-modernisation/darts-ucf-test-harness/test.yaml
[DMP-4548](https://tools.hmcts.net/jira/browse/DMP-4548)
- Changed the number of replicas for the `java` service from 0 to 1.
- Set the `DARTS_LOG_LEVEL` environment variable to `DEBUG`.
> DMP-4548 Start DARTS UCF test harness on test env

- apps/pre/pre-api-cron-cleanup-live-events/stg.yaml
- Updated the job schedule from \"15 11 * * *\" to \"15 15 * * *\" 🔄
> PRE STG clean up live events cron schedule

- apps/pre/pre-api-cron-cleanup-live-events/stg.yaml
- File: stg.yaml
- Updated the job schedule from \"15 15 * * *\" to \"0 19 * * *\"
- Removed the old schedule and added a new schedule. 🔄
> PRE STG revert live event cron schedule

- apps/darts-modernisation/darts-ucf-test-harness/test.yaml
replicas back to 0 to turn the instances off
- Updated `test.yaml`
- Changed the number of replicas from 10 to 0
> replicas back to 0 to turn the instances off

- apps/pre/pre-api-cron-cleanup-live-events/stg.yaml
- Updated the schedule of the cron job from \"0 19 * * *\" to \"0 10 * * *\" ⏰
> PRE STG clean up live events cron test schedule

- apps/pre/pre-api-cron-cleanup-live-events/stg.yaml
- Updated file: stg.yaml
- Changed the schedule of the CronJob from \"0 10 * * *\" to \"0 19 * * *\" 🔄
> PRE STG clean up live events cron schedule reset

- apps/darts-modernisation/darts-api/prod.yaml
- apps/darts-modernisation/darts-automated-tasks/prod.yaml
Updated PROCESS_E2E_ARM_RPO to true for prod
See (https://tools.hmcts.net/jira/browse/DMP-4631)
Updated PROCESS_E2E_ARM_RPO to true for prod
- Modified `prod.yaml` in `darts-api` and `darts-automated-tasks`:
- Updated `PROCESS_E2E_ARM_RPO` from `false` to `true`
> DMP-4631 (Dev Only) Enable ARM RPO feature flag on PROD

- apps/jenkins/jenkins/ptl/jenkins-azure-vm-agent.yaml
- apps/jenkins/jenkins/ptlsbox/jenkins-azure-vm-agent.yaml
- Updates Jenkins image in SDS
- Tested new image on CFT SBOX by updating image and running plum pipelines
- Changed galleryImageDefinition from \"jenkins-ubuntu\" to \"jenkins-ubuntu-v2\"
- Updated galleryImageVersion from \"1.4.220\" to \"1.0.1\"
- Changed galleryImageDefinition from \"jenkins-ubuntu\" to \"jenkins-ubuntu-v2\"
- Updated galleryImageVersion from \"1.4.220\" to \"1.0.1\"
> Update jenkins image SDS

- apps/jenkins/jenkins/ptl/jenkins-azure-vm-agent.yaml
- Setting to latest Jenkins image as renovate was picking up a PR image
- Updated the `galleryImageVersion` from \"244.0.1\" to \"1.0.1\" for the Azure VM agent in Jenkins. 🔄
> Set to latest jenkins image

- apps/darts-modernisation/darts-ucf-test-harness/test.yaml
Turning the test harness on for 20 instances
- Changed the number of Java replicas from 0 to 10.
> Turning the test harness on for 20 instances

- apps/jenkins/jenkins/ptl/jenkins-azure-vm-agent.yaml
- apps/jenkins/jenkins/ptlsbox/jenkins-azure-vm-agent.yaml
- Using new jenkins image in SDS that has fix for puppeteer issue
- `jenkins-azure-vm-agent.yaml`:
- Changed `galleryImageVersion` from \"1.0.1\" to \"24.0.0\" for `jenkins-azure-vm-agent.yaml`.
- Updated `galleryImageVersion` from \"244.0.1\" to \"24.0.0\" for `jenkins-azure-vm-agent.yaml` in `ptlsbox` directory.
> Use new jenkins image in SDS

- apps/darts-modernisation/darts-ucf-test-harness/test.yaml
Turning off the test harness
- Modified file: test.yaml
- Updated the number of replicas from 10 to 0 for the Java service.
> Turning off the test harness

- apps/darts-modernisation/darts-gateway/demo.yaml
- demo.yaml
- Added DAR_PC_MAX_TIME_DRIFT configuration with a value of 1s.
> Add DAR_PC_MAX_TIME_DRIFT to gateway demo

- apps/juror/juror-api/image-policy.yaml
deployment of juror-api with JS-190
- Changed the image version pattern from 'pr-845' to 'pr-855' for the juror-api. 🔧
> juror deployment of juror-api

- apps/pip/account-management/stg.yaml
- apps/pip/data-management/stg.yaml
- apps/pip/publication-services/stg.yaml
- apps/pip/subscription-management/stg.yaml
https://tools.hmcts.net/jira/browse/PUB-2708
Deploy MI data changes to staging env
- Updated image for java replicas in each file for **account-management**, **data-management**, **publication-services**, and **subscription-management** apps.
The new image is sdshmctspublic.azurecr.io/pip/{app-name}:pr-{pr-number}-{commit-hash}-{timestamp}```.
> PUB-2708 Deploy MI data changes to staging env

- apps/darts-modernisation/darts-ucf-test-harness/test.yaml
Turn off the test harness
- Updated replicas value from 11 to 0 in `test.yaml` for the `darts-ucf-test-harness` release.
> Turn off the test harness

- apps/juror/juror-api/image-policy.yaml
- apps/juror/juror-bureau/image-policy.yaml
- apps/juror/juror-pnc/demo.yaml
- apps/juror/juror-pnc/image-policy.yaml
- apps/juror/juror-pnc/ithc.yaml
- apps/juror/juror-public/image-policy.yaml
- apps/juror/juror-scheduler-api/demo.yaml
- apps/juror/juror-scheduler-api/image-policy.yaml
- apps/juror/juror-scheduler-api/ithc.yaml
- apps/juror/juror-scheduler-execution/demo.yaml
- apps/juror/juror-scheduler-execution/image-policy.yaml
updating juror images in ITHC and Demo for release5.3
This PR is for testing
- Changed apps/juror/juror-api/image-policy.yaml
- Updated filterTags pattern from '^pr-855-[a-f0-9]+-(?P<ts>[0-9]+)' to '^pr-857-[a-f0-9]+-(?P<ts>[0-9]+)'
- Changed apps/juror/juror-bureau/image-policy.yaml
- Updated filterTags pattern from '^pr-879-[a-f0-9]+-(?P<ts>[0-9]+)' to '^pr-888-[a-f0-9]+-(?P<ts>[0-9]+)'
- Changed apps/juror/juror-pnc/demo.yaml
- Updated image value from 'sdshmctspublic.azurecr.io/juror/pnc:prod-c71b09d-20240701102144' to 'sdshmctspublic.azurecr.io/juror/pnc:prod-c71b09d-20240701102144'
- Changed apps/juror/juror-pnc/image-policy.yaml
- Updated filterTags pattern from '^pr-1-[a-f0-9]+-(?P<ts>[0-9]+)' to …
> updating juror images for ITHC and Demo

- apps/keda/ithc/base/kustomization.yaml
- apps/keda/keda/nonprod.yaml
See [DTSPO-23721](https://tools.hmcts.net/jira/browse/DTSPO-23721)
Patch Keda to 2.16.0 from older version 2.15.2. did not wanted to patch to latest version . This will be testing on ithc env by applying patch from keda directory for nonprod
Please delete options that are not relevant.
This will be testing on ITHC env 
Please list any issues found during testing and how they were resolved:
N/A
Please provide the steps required to deploy these changes to Azure.
Please add any other information that is important to this PR, such as screenshots, logs, or links to other related PRs.
> Nonprod Keda patch to 2.16.0

- apps/pdda/pdda-public-display-manager/stg.yaml
- The environment variable `TRIGGER_RESTART` has been updated from `1` to `0`.
- Logging levels for `UK_GOV_HMCTS_PDM`, `ORG_SPRINGFRAMEWORK_SECURITY`, and `COM_ZAXXER_HIKARI` have been set to `DEBUG`.
> Triggering a PDM Restart

- apps/keda/demo/base/kustomization.yaml
- apps/keda/dev/base/kustomization.yaml
- apps/keda/ptlsbox/base/kustomization.yaml
- apps/keda/sbox/base/kustomization.yaml
- apps/keda/stg/base/kustomization.yaml
See [DTSPO-23721](https://tools.hmcts.net/jira/browse/DTSPO-23721)
Patch Keda to 2.16.0 from older version 2.15.2. did not wanted to patch to latest version .  Apply patch to rest of non prod environment 
Please delete options that are not relevant.
Tested on ithc here  https://github.com/hmcts/sds-flux-config/pull/6065
N/A
Please provide the steps required to deploy these changes to Azure.
Please add any other information that is important to this PR, such as screenshots, logs, or links to other related PRs.
- Added a new file `././keda/nonprod.yaml` to the list of patches.
- Added a new file `././keda/nonprod.yaml` to the list of patches.
- Added a new file `././keda/nonprod.yaml` to the list of patches.
- Added a new file `././keda/nonprod.yaml` to the list of patches.
- Added a new …
> Keda Patch to 2.16.0  - Add to reminding nonprod

- apps/darts-modernisation/darts-gateway/demo.yaml
- Removed the `DAR_PC_MAX_TIME_DRIFT` configuration setting.
- Added the `FORCE_CHECKSUM_FAILURE` configuration setting with a value of `false`.
> Remove DAR_PC_MAX_TIME_DRIFT from gateway demo

- apps/pdda/pdda-public-display-manager/stg.yaml
- Changed environment variable TRIGGER_RESTART from 0 to 1
- Logging levels for UK_GOV_HMCTS_PDM, ORG_SPRINGFRAMEWORK_SECURITY, and COM_ZAXXER_HIKARI set to DEBUG
> Restarting PDM

- apps/darts-modernisation/darts-ucf-test-harness/test.yaml
Turning the test harness on.
- Updated the number of replicas for the Java service from 0 to 10.
- Set the ingress host to \"darts-ucf-test-harness.test.platform.hmcts.net\"
- Set the environment variable DARTS_LOG_LEVEL to DEBUG.
> Turning the test harness on.

- apps/pdda/pdda-public-display-manager/stg.yaml
- Changed the value of `TRIGGER_RESTART` from 0 to 1
- Updated the `LOGGING_LEVEL_UK_GOV_HMCTS_PDM`, `LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_SECURITY`, and `LOGGING_LEVEL_COM_ZAXXER_HIKARI` to `DEBUG`
> PDM Restart

- apps/met/themis-fe/test.yaml
switch to a volume mount
- Changed file: test.yaml
- Removed TZ: CET-1CEST,M3.5.0,M10.5.0/3 and replicas: 1
- Added volumeMounts and volumes for timezone configuration
- Updated servicebus-connectionstring and added hostPath for timezone configuration
> switch to a volume mount

- apps/met/themis-fe/test.yaml
indentation change
- Added a new volume called `tz-config` with a hostPath to `/usr/share/zoneinfo/Europe/Paris`.
- Removed the redundant volume definition for `tz-config`.
> indentation change

- apps/met/themis-fe/test.yaml
revert themesis-fe tz attempt
- Removed volume and volume mounts configuration
- Updated image and ingress host configuration
> revert themesis-fe tz attempt

- apps/darts-modernisation/darts-ucf-test-harness/test.yaml
Turning on the Test Harness
- Increased the number of Java replicas from 0 to 10
- Updated the ingressHost to darts-ucf-test-harness.test.platform.hmcts.net
> Turning on the Test Harness

- apps/darts-modernisation/darts-api/image-policy-pr.yaml
- apps/darts-modernisation/darts-api/test.yaml
- Removed the annotation \"hmcts.github.com/prod-automated: disabled\"
- Updated the image repository reference to \"sdshmctspublic.azurecr.io/darts/api:pr-2568-f9f2007-20250211125721\" and the environment variables for DARTS_GATEWAY_URL and DARTS_LOG_LEVEL.
> Image policy update

- apps/pdda/pdda-public-display-data-aggregator/stg.yaml
- Updated `stg.yaml` in `apps/pdda/pdda-public-display-data-aggregator`:
- Changed `TRIGGER_RESTART` environment variable from 0 to 1.
- Updated logging levels for `UK_GOV_HMCTS_PDDA`, `ORG_SPRINGFRAMEWORK_SECURITY`, and `COM_ZAXXER_HIKARI` to DEBUG.
> Restarting PDDA

- apps/pre/pre-api-cron-cleanup-live-events/stg.yaml
- apps/pre/pre-api-cron-cleanup-streaming-locators/stg.yaml
- apps/pre/pre-api-cron-close-pending-cases/stg.yaml
- `pre-api-cron-cleanup-live-events/stg.yaml` 🛠️
- Added `ENABLE_NEW_EMAIL_SERVICE: true` to the spec.
- `pre-api-cron-cleanup-streaming-locators/stg.yaml` 🛠️
- Added `ENABLE_NEW_EMAIL_SERVICE: true` to the spec.
- `pre-api-cron-close-pending-cases/stg.yaml` 🛠️
- Added `ENABLE_NEW_EMAIL_SERVICE: true` to the spec.
> Enable gov notify email in PRE stg cron jobs

- apps/pdda/pdda-public-display-data-aggregator/stg.yaml
- Changed the value of `TRIGGER_RESTART` from 1 to 0.
- Updated logging levels for `UK_GOV_HMCTS_PDDA`, `ORG_SPRINGFRAMEWORK_SECURITY`, and `COM_ZAXXER_HIKARI` to DEBUG.
> Restart PDDA

- apps/pre/pre-api-cron-close-pending-cases/stg.yaml
- Updated file: stg.yaml
- Changed the schedule from \"0 * * * *\" to \"0 8-19 * * 1-5\" to run the job from 8 am to 7 pm on weekdays
> PRE don't run cron when infra is down in stg

- apps/pdda/pdda-public-display-manager/stg.yaml
- Changed the `TRIGGER_RESTART` environment variable from `1` to `0`
- Updated logging levels for `UK_GOV_HMCTS_PDM`, `ORG_SPRINGFRAMEWORK_SECURITY`, and `COM_ZAXXER_HIKARI` to `DEBUG`
> pdda-474 Restart PDM

- apps/jenkins/jenkins/ptlsbox/jenkins-azure-vm-agent.yaml
- Updating Jenkins image in sbox
- Updated galleryImageDefinition from \"jenkins-ubuntu\" to \"jenkins-ubuntu-v2\"
- Updated galleryImageVersion from \"1.4.220\" to \"247.0.0\"
> Update jenkins image in sbox

- apps/jenkins/jenkins/ptl/jenkins-azure-vm-agent.yaml
- Updates Jenkins to use new Ubuntu 24.04 image
- Using a PR image for now and will replace once confirmed no issues
- **jenkins-azure-vm-agent.yaml**
- Changed `galleryImageDefinition` from \"jenkins-ubuntu\" to \"jenkins-ubuntu-v2\"
- Changed `galleryImageVersion` from \"1.4.220\" to \"247.0.0\"
> Use new Jenkins image in PTL

- apps/vh/dev/base/kustomization.yaml
- apps/vh/serviceaccount/dev.yaml
See [VIH-11295](https://tools.hmcts.net/jira/browse/VIH-11295)
Updates VH app Flux in Dev to use correct Dev Managed Identity
Cannot be tested until deployed.
- Updated `kustomization.yaml` in `apps/vh/dev/base`:
- Removed `serviceaccount/stg.yaml` and added `serviceaccount/dev.yaml`.
- Added `serviceaccount/dev.yaml` in `apps/vh/serviceaccount`:
- Defined a ServiceAccount with specific metadata and annotations.
> VIH-11295 update flux vh dev config to use dev managed identity

- apps/jenkins/jenkins/ptl/jenkins-azure-vm-agent.yaml
- apps/jenkins/jenkins/ptlsbox/jenkins-azure-vm-agent.yaml
- Updating Jenkins image in all envs to latest
- Tested the same image as a PR already but this is the image created from running master on jenkins-packer repo
- jenkins-azure-vm-agent.yaml
- Changed `galleryImageVersion` from \"247.0.0\" to \"24.04.0\" for both `jenkins-azure-vm-agent.yaml` and `ptlsbox/jenkins-azure-vm-agent.yaml`.
> Updating Jenkins to use new image in all envs

- apps/jenkins/jenkins/ptl/jenkins-azure-vm-agent.yaml
- apps/jenkins/jenkins/ptlsbox/jenkins-azure-vm-agent.yaml
https://tools.hmcts.net/jira/browse/DTSPO-24175
- Jenkins image as missing dependencies that were causing pipelines to fail
- Changed galleryImageVersion from \"24.04.0\" to \"24.04.1\"
- Changed galleryImageVersion from \"24.04.0\" to \"24.04.1\"
> Use patched jenkins image

- apps/pre/pre-api-cron-cleanup-live-events/stg.yaml
- Updated the job schedule from \"0 14 * * *\" to \"0 19 * * *\" 🔄
> Returning PRE stg cron to 7pm

- apps/jenkins/jenkins/ptl/jenkins-azure-vm-agent.yaml
- apps/jenkins/jenkins/ptlsbox/jenkins-azure-vm-agent.yaml
- Too many different breaking changes due to dependency versions used by teams
- Reverting upgrade until after we've deprecated these versions and teams have upgraded
- Changed galleryImageDefinition from \"jenkins-ubuntu-v2\" to \"jenkins-ubuntu\"
- Updated galleryImageVersion from \"24.04.1\" to \"1.4.221\"
- Changed galleryImageDefinition from \"jenkins-ubuntu-v2\" to \"jenkins-ubuntu\"
- Updated galleryImageVersion from \"24.04.1\" to \"1.4.221\"
> Revert Jenkins image to Ubuntu 20

- apps/jenkins/jenkins/ptl/jenkins-azure-vm-agent.yaml
- apps/jenkins/jenkins/ptlsbox/jenkins-azure-vm-agent.yaml
- Setting Jenkins image to most recent stable image
- `jenkins-azure-vm-agent.yaml` 🔄
- Updated `galleryImageVersion` from \"24.04.2\" to \"1.4.222\" for both `ptl/jenkins-azure-vm-agent.yaml` and `ptlsbox/jenkins-azure-vm-agent.yaml`.
> Set jenkins image

- apps/darts-modernisation/darts-gateway/test.yaml
- `test.yaml`: Changed `DAR_NOTIFY_ENABLED` from true to false.
> Disable DAR notify on test env

- apps/darts-modernisation/darts-ucf-test-harness/test.yaml
Turning back on the Test Harness
- Changed the number of replicas for the `java` service from 0 to 25.
> Turning back on the Test Harness

- apps/darts-modernisation/darts-ucf-test-harness/test.yaml
Turning on for 50 instances
- Changed the number of replicas for the Java service from 0 to 25.
> Turning on for 50 instances

- apps/pre/pre-api-cron-cleanup-live-events/stg.yaml
- apps/pre/pre-api-cron-cleanup-streaming-locators/stg.yaml
- apps/pre/pre-api-cron-close-pending-cases/stg.yaml
- apps/pre/pre-api/stg.yaml
- `pre-api-cron-cleanup-live-events/stg.yaml` 🔄
- Changed `ENABLE_NEW_EMAIL_SERVICE` from `true` to `false`.
- `pre-api-cron-cleanup-streaming-locators/stg.yaml` 🔄
- Changed `ENABLE_NEW_EMAIL_SERVICE` from `true` to `false`.
- `pre-api-cron-close-pending-cases/stg.yaml` 🔄
- Changed `ENABLE_NEW_EMAIL_SERVICE` from `true` to `false`.
- `pre-api/stg.yaml` 🔄
- Changed `ENABLE_NEW_EMAIL_SERVICE` from `true` to `false`.
- Changed `ENABLE_STREAMING_LOCATOR_ON_START` from `true` to `false`.
> Disable Gov Notify in PRE STG

- apps/dynatrace/dynatrace-operator-upgrade.yaml
https://tools.hmcts.net/jira/browse/DTSPO-23727
CSI drivers not installing, this should install them
- Updated `dynatrace-operator-upgrade.yaml`
- Added new values for `oneAgent`:
- `useCSIDriver: true`
> set useCSIDriver to true

- apps/dynatrace/dynatrace-operator-upgrade.yaml
Reverts hmcts/sds-flux-config#6197
> Revert "set useCSIDriver to true"

- apps/dynatrace/dynatrace-operator-upgrade.yaml
Reverts hmcts/sds-flux-config#6200
> Revert "Update dynatrace-operator-upgrade.yaml"

- apps/pre/pre-api-cron-cleanup-live-events/test.yaml
- Updated the job schedule from \"30 17 * * *\" to \"30 07 * * *\" 🔄
> change pre corn to 7.30am

- apps/pre/pre-api-cron-cleanup-streaming-locators/test.yaml
- Updated the schedule of the job from \"30 18 * * *\" to \"30 09 * * *\" 🔄
> can pre cron to 9.30

- apps/darts-modernisation/darts-ucf-test-harness/test.yaml
Turn on 100 instances (50 replicas)
- Modified file: test.yaml
- Updated the `replicas` value from 0 to 50 for the `java` service.
> Turn on 100 instances (50 replicas)

- apps/juror/juror-api/ithc.yaml
Update juror-api in ITHC only 
- Updated the `java` image version to `pr-876-e430640-20250227114010` from `pr-876-1c91eb3-20250226121104` 📷
- The environment variable `RUN_DB_MIGRATION_ON_STARTUP` is now set to `true` 🔄
> update juror api in ITHC

- apps/darts-modernisation/darts-gateway/stg.yaml
N/A
**apps/darts-modernisation/darts-gateway/stg.yaml**
- Added the `FORCE_CHECKSUM_FAILURE` with a value of `true` to the configuration.
> DARTS gateway - temp force checksum failure on staging

- apps/darts-modernisation/darts-gateway/stg.yaml
N/A
- for testing lack of connectivity to API
- stg.yaml
- Changed DARTS_API_URL from https://darts-api.staging.platform.hmcts.net to https://darts-api.nope.staging.platform.hmcts.net
- Removed FORCE_CHECKSUM_FAILURE: true from the environment configuration
> Removing force checksum failure, adding dodgy DARTS API URL

- apps/darts-modernisation/darts-api/stg.yaml
- apps/darts-modernisation/darts-gateway/stg.yaml
N/A
- scaling DARTS API down to 0 pods
- Updated `apps/darts-modernisation/darts-api/stg.yaml`:
- Increased the number of replicas for the Java service to 0.
- Updated the `ingressHost` to darts-api.staging.platform.hmcts.net.
- Updated `apps/darts-modernisation/darts-gateway/stg.yaml`:
- Updated the `DARTS_API_URL` environment variable to https://darts-api.staging.platform.hmcts.net.
> Removing dodgy DARTS API URL for DARTS gateway

- apps/darts-modernisation/darts-api/stg.yaml
N/A
- Remove the `replicas` key from the `java` section.
- Remove the `ingressHost` property from the values.
- Update the `DARTS_GATEWAY_URL` to `http://darts-gateway.staging.platform.hmcts.net`.
> Reset DARTS API replicas to normal

- apps/darts-modernisation/darts-api/demo.yaml
- Updated file: `demo.yaml`
- Changed `CASE_EXPIRY_DELETION_ENABLED` from `false` to `true`
> DARTS - Enable expiry deletion feature on demo

- apps/darts-modernisation/darts-api/demo.yaml
Reverts hmcts/sds-flux-config#6227
- Changed `CASE_EXPIRY_DELETION_ENABLED` from `true` to `false` 🔄.
> Revert "DARTS - Enable expiry deletion feature on demo"

- apps/darts-modernisation/darts-external-component-test-harness/test.yaml
Turning off, need to do a restart.
- `test.yaml`
- Changed the number of replicas from 50 to 0 for the `java` component.
> Turning off, need to do a restart.

- apps/darts-modernisation/darts-external-component-test-harness/test.yaml
Turn on Test harness for 120
- Changed replicas value from 0 to 60.
> Turn on Test harness for 120

- apps/pre/pre-api/stg.yaml
- File: `apps/pre/pre-api/stg.yaml`
- Changes:
- Updated `ENABLE_NEW_EMAIL_SERVICE` from `false` to `true`
- Added `ENABLE_STREAMING_LOCATOR_ON_START: true`
> Enable Gov Notify on PRE STG

- apps/darts-modernisation/darts-external-component-test-harness/test.yaml
Turing on the test harness for 120
- Changed the number of replicas from 0 to 60 under the 'java' section.
> Turing on the test harness for 120

- apps/pre/pre-api-cron-cleanup-live-events/stg.yaml
- apps/pre/pre-api-cron-cleanup-streaming-locators/stg.yaml
- apps/pre/pre-api-cron-close-pending-cases/stg.yaml
- `pre-api-cron-cleanup-live-events/stg.yaml` ✨
- Changed the value of `ENABLE_NEW_EMAIL_SERVICE` from `false` to `true`.
- `pre-api-cron-cleanup-streaming-locators/stg.yaml` ✨
- Changed the value of `ENABLE_NEW_EMAIL_SERVICE` from `false` to `true`.
- `pre-api-cron-close-pending-cases/stg.yaml` ✨
- Changed the value of `ENABLE_NEW_EMAIL_SERVICE` from `false` to `true`.
> PRE STG enable Gov Notify on close case cron

- apps/flux-system/stg/base/kustomization.yaml
- Commenting out workload identity changes
- Removed ././workload-identity``` resource
- Added two new patches:
- ```././serviceaccount/stg.yaml```
- ```././base/patches/kustomize-controller-patch.yaml```
> DTSPO-24310: Commenting out workload identity changes

- apps/flux-system/dev/base/kustomization.yaml
Commenting out WI in dev
- Removed references to `workload-identity` and `aso-controller-settings-patch.yaml` patches.
- Added a new patch `kustomize-controller-patch.yaml`.
> DTSPO-24310: Commenting out WI in dev

- apps/darts-modernisation/darts-external-component-test-harness/test.yaml
Turning on test harness
- File: test.yaml
- Changed replicas from 0 to 60 for the \"java\" component.
- Updated the \"ingressHost\" to \"darts-external-component-test-harness.test.platform.hmcts.net\".
> Turning on test harness

- apps/darts-modernisation/darts-external-component-test-harness/test.yaml
Turning off, need to do a restart
- Reduced the number of replicas for the Java service from 60 to 0.
- Updated the environment variable DARTS_LOG_LEVEL to DEBUG.
> Turning off, need to do a restart

- apps/pre/pre-api-cron-cleanup-live-events/prod.yaml
- Updated the schedule of the cron job from \"0 20 * * *\" to \"0 18 * * *\" 🔄
> PRE prod cleanup cron before CVP cron

- apps/juror/juror-public/image-policy.yaml
juror-public deployment into ITHC and Demo
This update is for deployment into test
- The `image-policy.yaml` file in the `apps/juror/juror-public` directory has been modified to include annotations and filter tags for the `juror-public` image repository. This includes setting up extraction patterns and ordering policies for both the main and PR branches. An annotation for disabling automated production deployments has also been added.
> juror-public deployment for ITHC and Demo

- apps/opal/opal-frontend-test/stg.yaml
Reverts hmcts/sds-flux-config#6325
- stg.yaml: 
- Removed keyVaults and its related secrets
- Removed FRONTEND_SESSION_SECRET and FRONTEND_COOKIE_SECRET variables
- Updated environment variables DUMMY_VAR and FRONTEND_HOSTNAME
> Revert "Update stg.yaml"

- apps/darts-modernisation/darts-api/demo.yaml
- apps/darts-modernisation/darts-api/ithc.yaml
- apps/darts-modernisation/darts-api/prod.yaml
- apps/darts-modernisation/darts-api/stg.yaml
- apps/darts-modernisation/darts-api/test.yaml
- apps/darts-modernisation/darts-automated-tasks/demo.yaml
- apps/darts-modernisation/darts-automated-tasks/ithc.yaml
- apps/darts-modernisation/darts-automated-tasks/prod.yaml
- apps/darts-modernisation/darts-automated-tasks/stg.yaml
- apps/darts-modernisation/darts-automated-tasks/test.yaml
https://tools.hmcts.net/jira/browse/DMP-4873
Added optional command line options for azcopy
- Updated the `demo.yaml`, `ithc.yaml`, `prod.yaml`, `stg.yaml`, and `test.yaml` files in the `darts-api` directory, as well as the `demo.yaml`, `ithc.yaml`, `prod.yaml`, `stg.yaml`, and `test.yaml` files in the `darts-automated-tasks` directory
- Added `AZCOPY_LOG_LEVEL` and `AZCOPY_OUTPUT_LEVEL` configurations with different values to all the mentioned files.
> DMP-4873 Performance Testing - Investigate azcopy command line parameter options

- apps/darts-modernisation/darts-external-component-test-harness/test.yaml
Turning the test harness back on for 60 (120)
> Turning the test harness back on for 60 (120)

- apps/pre/pre-api/stg.yaml
- apps/pre/pre-api/test.yaml
https://tools.hmcts.net/jira/browse/S28-3750
- **apps/pre/pre-api/stg.yaml**
- Added memory requests and limits for the Java application.
- Added a new environment variable VAR_TA with the value of Trigger-1.
- **apps/pre/pre-api/test.yaml**
- Updated the value of ENABLE_STREAMING_LOCATOR_ON_START from false to false.
> test mem to 3Gb

- apps/pre/pre-api-cron-cleanup-live-events/demo.yaml
- apps/pre/pre-api-cron-cleanup-streaming-locators/demo.yaml
- apps/pre/pre-api-cron-close-pending-cases/demo.yaml
- apps/pre/pre-api-cron-start-live-events/demo.yaml
- apps/pre/pre-api/demo.yaml
- `demo.yaml` ⭐️
- Added `ENABLE_NEW_EMAIL_SERVICE: true` to the `spec` section.
- `demo.yaml` ⭐️
- Added `ENABLE_NEW_EMAIL_SERVICE: true` to the `spec` section.
- `demo.yaml` ⭐️
- Added `ENABLE_NEW_EMAIL_SERVICE: true` to the `spec` section.
- `demo.yaml` ⭐️
- Added `ENABLE_NEW_EMAIL_SERVICE: true` to the `spec` section.
- `demo.yaml` ⭐️
- Added `ENABLE_NEW_EMAIL_SERVICE: true` to the `spec` section.
> Enable gov notify on demo for PRE

- apps/pip/account-management/stg.yaml
- apps/pip/data-management/stg.yaml
- apps/pip/publication-services/stg.yaml
- apps/pip/subscription-management/stg.yaml
Remove outdated images from staging
- Removed a specific image reference from the file.
- Removed a specific image reference from the file.
- Removed a specific image reference from the file.
- Removed a specific image reference from the file.
> Remove outdated images from staging

- apps/pre/pre-api/pre-api.yaml
https://tools.hmcts.net/jira/browse/S28-3750
- Increased the memory requests and limits to '3Gi'.
- Enabled autoscaling with a maximum of 4 replicas.
> Increase pre-api mem

- apps/flux-system/base/patches/kustomize-controller-patch.yaml
- Re-adding kustomize-controller-patch for bootstrap
- Created a new file `kustomize-controller-patch.yaml`.
- Added a deployment specification for `kustomize-controller` in the `flux-system` namespace.
- Specified environment variable `AZURE_AUTH_METHOD` with value `msi` for the `manager` container.
> DTSPO-24310: Re-adding kustomize-controller-patch for bootstrap

- apps/darts-modernisation/darts-external-component-test-harness/test.yaml
Turn on test harness for 60
- `test.yaml` 🔄
- Updated replicas from 0 to 60.
- Updated TEST_HARNESS_AUTOMATION_MAX_ITERATIONS from 30 to -1.
> Turn on test harness for 60

- apps/darts-modernisation/darts-external-component-test-harness/test.yaml
Turn on test harness
- `test.yaml` 🔄
- Changed `replicas` from 0 to 60
- Changed `TEST_HARNESS_AUTOMATION_MAX_ITERATIONS` from 30 to -1
> Turn on test harness

- apps/pip/frontend/stg.yaml
N/A
Change back staging
- Removed a large block of environment variables and secrets from the file.
- Update includes removal of specific secret names and their aliases.
> Updated staging for pip

- apps/mi/base/mi-developer-rbac.yaml
- The file `mi-developer-rbac.yaml` was modified.
- An API group was adjusted by removing a space before `customresourcedefinitions.apiextensions.k8s.io`.
> fix whitespace

- apps/juror/juror-pnc/ithc.yaml
- Updated PNC service host and port from `juror-dev-psnp.pnc.pnn.police.uk:7103` to `api.test.leds.police.uk:443` 🔄
> juror-ithc: test pnc leds

- apps/darts-modernisation/darts-automated-tasks/stg.yaml
[DMP-4775](https://tools.hmcts.net/jira/browse/DMP-4775)
- `stg.yaml`:
- Added `replicas: 0` under the `java` section.
- Updated `DARTS_GATEWAY_URL` to `http://darts-gateway.staging.platform.hmcts.net`.
- Updated `DARTS_PORTAL_URL` to `https://darts.staging.apps.hmcts.net`.
> DMP-4775 Temporarily disable DARTS automated tasks on staging

- apps/jenkins/jenkins/ptl/jenkins-azure-vm-agent.yaml
- apps/jenkins/jenkins/ptlsbox/jenkins-azure-vm-agent.yaml
- Upgrading Jenkins image to use Ubuntu 24.04
- Updated galleryImageDefinition from \"jenkins-ubuntu\" to \"jenkins-ubuntu-v2\" 👷
- Updated galleryImageVersion from \"1.4.222\" to \"24.04.3\" 👷
- Updated galleryImageDefinition from \"jenkins-ubuntu\" to \"jenkins-ubuntu-v2\" 👷
- Updated galleryImageVersion from \"1.4.222\" to \"24.04.3\" 👷
> Update jenkins images

- apps/pip/account-management/ithc.yaml
- apps/pip/data-management/ithc.yaml
- apps/pip/frontend/ithc.yaml
- apps/pip/publication-services/ithc.yaml
Update images for AM/SM merge
ℹ️ The following changes were made in the pull request:
- `ithc.yaml` files in `account-management`, `data-management`, `frontend`, and `publication-services` directories were updated to include new image versions and environment variables for Azure Key Vault secrets and other configurations.
> Update images for AM/SM merge

- apps/jenkins/jenkins/ptl/jenkins-azure-vm-agent.yaml
- apps/jenkins/jenkins/ptlsbox/jenkins-azure-vm-agent.yaml
https://tools.hmcts.net/jira/browse/DTSPO-25084
- Bumping Jenkins agent image
- Includes fix for cross browser tests from above ticket
> Update jenkins agent image

- apps/darts-modernisation/darts-api/test.yaml
Log level update
- Changed the value of `DARTS_LOG_LEVEL` from DEBUG to INFO.
> Log level update

- apps/pip/account-management/test.yaml
- apps/pip/data-management/test.yaml
- apps/pip/frontend/test.yaml
- apps/pip/publication-services/test.yaml
- apps/pip/subscription-management/test.yaml
N/A
Change back pip test
- `test.yaml` in `account-management`: Removed the `image` field.
- `test.yaml` in `data-management`: Removed the `image` field.
- `test.yaml` in `frontend`: Removed the `image` field.
- `test.yaml` in `publication-services`: Removed the `image` field.
- `test.yaml` in `subscription-management`: Updated the `replicas` field from 0 to 2.
> Change back pip test env

- apps/jenkins/jenkins/ptl/jenkins.yaml
N/A
- Removed the buildMonitor configurations for DARTS-Modernisation and Darts Shared Infrastructure, including the includeRegex, name, recurse, and title properties.
> Temporarily removing the DARTS build monitor

- apps/pre/pre-api-cron-cleanup-live-events/demo.yaml
- apps/pre/pre-api-cron-cleanup-streaming-locators/demo.yaml
- apps/pre/pre-api-cron-close-pending-cases/demo.yaml
- apps/pre/pre-api/demo.yaml
- Added the `ENABLE_NEW_EMAIL_SERVICE` parameter and set its value to `true`.
- Added the `ENABLE_NEW_EMAIL_SERVICE` parameter and set its value to `true`.
- Added the `ENABLE_NEW_EMAIL_SERVICE` parameter and set its value to `true`.
- Added the `ENABLE_NEW_EMAIL_SERVICE` parameter and set its value to `true`.
> Enable gov notify in PRE demo

- apps/jenkins/jenkins/ptl/jenkins.yaml
N/A
- Added a new build monitor \"DARTS Modernisation\" with specific includeRegex for DARTS modernization.
> Re-add DARTS modernisation build monitor

- apps/flux-system/sbox/00/kustomization.yaml
- apps/flux-system/sbox/01/kustomization.yaml
- clusters/sbox/00/kustomization.yaml
- clusters/sbox/01/kustomization.yaml
- clusters/sbox/base/kustomization.yaml
- Adding the ptl gotk-components to ss-sbox-01-aks. This is needed to test the changes to the bootstrapping.
- ss-sbox-00-aks should not be affected
- Added a new file with kustomization configurations for sbox environment.
- Added a new file with kustomization configurations for sbox environment.
- Updated the resources path to include apps/flux-system/sbox/00.
- Updated the resources path to include apps/flux-system/sbox/01.
- Removed a resource path for apps/flux-system/sbox/base.
- Updated the resource paths in the file.
> DTSPO-24310: Adding the ptl gotk-components to sbox-01

- apps/pre/demo/base/kustomization.yaml
- apps/pre/pre-api-cron-start-live-events/demo.yaml
https://tools.hmcts.net/confluence/pages/editpage.action?pageId=1838613085
- Added a new resource: `pre-api-cron-start-live-events/pre-api-cron-start-live-events.yaml`
- Updated the path for `pre-api-cron-start-live-events/demo.yaml`
- Updated the schedule time from \"0 8 * * *\" to \"0 7 * * *\"
> Start live events enable demo cron

- apps/flux-system/sbox/00/kustomization.yaml
- apps/flux-system/sbox/00/kustomize.yaml
- apps/flux-system/sbox/01/kustomization.yaml
- apps/flux-system/sbox/01/kustomize.yaml
- clusters/sbox/00/kustomization.yaml
- clusters/sbox/01/kustomization.yaml
- clusters/sbox/base/kustomization.yaml
- Adding the ptl gotk-components to ss-sbox-01-aks. This is needed to test the changes to the bootstrapping.
- Added new kustomization.yaml file in apps/flux-system/sbox/00 directory, specifying resources and patches for customization
- Updated kustomize.yaml file in apps/flux-system/sbox/00 directory, setting WI_CLUSTER to \"sbox-00\"
- Added new kustomization.yaml file in apps/flux-system/sbox/01 directory, specifying resources and patches for customization
- Updated kustomize.yaml file in apps/flux-system/sbox/01 directory, setting WI_CLUSTER to \"sbox-01\"
- Updated kustomization.yaml file in clusters/sbox/00 directory, added a new resource from apps/flux-system/sbox/00 and specified patches
- Updated kustomization.yaml file in …
> DTSPO-24310: Testing changes to bootstrap

- apps/pre/pre-api-cron-cleanup-live-events/test.yaml
- Updated the schedule of the CronJob from \"30 07 * * *\" to \"00 10 * * *\" ⏰
> updating to cleanup liveevents

- apps/pre/pre-api-cron-close-pending-cases/demo.yaml
- Added a new environment variable `VAR_TA` with the value `trigger1`. 🆕
> Trigger cronjob to rebuild demo.yaml

- apps/pre/pre-api-cron-close-pending-cases/demo.yaml
- Updated the environment variables by indenting and adding new lines for better readability.
- Updated the schedule to run the job every hour.
> Fix indenting demo.yaml

- apps/pre/pre-portal/prod.yaml
https://tools.hmcts.net/jira/browse/S28-3817
- Changed the value of TRIGGER from \"init-3\" to \"init-4\" 🔄
> Trigger PRE Portal prod.yaml

- apps/pre/demo/00/kustomization.yaml
- apps/pre/demo/01/kustomization.yaml
- apps/pre/demo/base/kustomization.yaml
- apps/pre/pre-api-cron-start-live-events/demo/00.yaml
- apps/pre/pre-api-cron-start-live-events/demo/01.yaml
See [S28-3815](https://tools.hmcts.net/jira/browse/S28-3815)
- Created new file `kustomization.yaml` in the `apps/pre/demo/00/` directory, specifying resources and patches for the pre-demo environment
- Created new file `kustomization.yaml` in the `apps/pre/demo/01/` directory, specifying resources and patches for the pre-demo environment
- Updated `kustomization.yaml` in the `apps/pre/demo/base/` directory, removing the path for `pre-api-cron-start-live-events/demo.yaml`
- Renamed `pre-api-cron-start-live-events/demo.yaml` to `pre-api-cron-start-live-events/demo/00.yaml` in the `apps/pre/` directory, and updated the schedule from \"0 7 * * *\" to \"0 7 1-31/2 * *\"
- Created new file `pre-api-cron-start-live-events/demo/01.yaml` in the `apps/pre/` directory, specifying a HelmRelease for …
> PRE: Start Live Events Cron DEMO

- apps/pre/pre-api-cron-start-live-events/demo/00.yaml
- apps/pre/pre-api-cron-start-live-events/demo/01.yaml
See [S28-3815](https://tools.hmcts.net/jira/browse/S28-3815)
- Updated the environment variables.
- Updated the PORTAL_URL value.
- Updated the environment variables.
- Updated the schedule time.
> PRE: Fix Start Live Events Cron DEMO

- apps/darts-modernisation/darts-external-component-test-harness/test.yaml
Starting the test harness for 150 to create data for inbound
- Updated `test.yaml`
- Increased replicas from 0 to 75 for the `java` service
> Starting the test harness for 150 to create data for inbound

- apps/flux-system/sbox/base/git-credentials.enc.yaml
N/A
known_hosts was double encrypted which caused issues
- **git-credentials.enc.yaml**
- Updated `created_at` from \"2025-04-10T13:26:34Z\" to \"2025-04-10T14:05:12Z\".
- Updated `enc` values.
- Updated `lastmodified` from \"2025-04-10T13:26:35Z\" to \"2025-04-10T14:05:13Z\".
- Updated `mac` value.
> fix secret

- apps/juror/juror-api/image-policy.yaml
image policy update for juror-api for interim9
This deployment is for testing in ITHC
- Updated the `pattern` under `filterTags` from `'^pr-891-[a-f0-9]+-(?P<ts>[0-9]+)'` to `'^pr-902-[a-f0-9]+-(?P<ts>[0-9]+)'`.
> juror-api image policy deployment for ITHC/Demo

- apps/pdda/pdda-public-display-manager/stg.yaml
- Changed the environment variable `TRIGGER_RESTART` from `0` to `1`
- Updated logging levels for `UK_GOV_HMCTS_PDM`, `ORG_SPRINGFRAMEWORK_SECURITY`, and `COM_ZAXXER_HIKARI` to `DEBUG`
> restart PDM app

- apps/pip/refresh-views-cron/test/01.yaml
https://tools.hmcts.net/jira/browse/PUB-2857
Updated cron trigger for pip
- Updated file: `apps/pip/refresh-views-cron/test/01.yaml`
- Updated the job schedule from \"10 15 * * 1,3,5\" to \"0 8 * * 1,3,5\" 🔄
> PUB-2857 - Updated Cron Trigger

- apps/juror/juror-api/image-policy.yaml
- apps/juror/juror-bureau/image-policy.yaml
Juror release5.6 deployment to ITHC and Demo
Deployment for testing
- Added annotations for disabling prod-automated for juror-api and juror-bureau
- Added filterTags and policy for matching and ordering image tags for juror-api and juror-bureau, both for prod and pr images.
> juror deployments for testing

- apps/pip/account-management/ithc.yaml
- apps/pip/data-management/ithc.yaml
- apps/pip/frontend/ithc.yaml
- apps/pip/publication-services/ithc.yaml
Remove expired ITHC image
- `apps/pip/account-management/ithc.yaml` 🔒
- Removed a list of image, key vaults, and secrets and updated the environment variables for PUBLICATION_SERVICES_URL and SUBSCRIPTION_MANAGEMENT_URL.
- `apps/pip/data-management/ithc.yaml` 🔒
- Removed a list of image, key vaults, and secrets and updated the environment variables for SUBSCRIPTION_MANAGEMENT_URL and ACCOUNT_MANAGEMENT_URL.
- `apps/pip/frontend/ithc.yaml` 🔒
- Removed a list of image, key vaults, and secrets and updated the environment variables for DATA_MANAGEMENT_URL and ACCOUNT_MANAGEMENT_URL.
- `apps/pip/publication-services/ithc.yaml` 🔒
- Removed a list of image, key vaults, and secrets and updated the environment variables for DATA_MANAGEMENT_URL and SUBSCRIPTION_MANAGEMENT_URL.
> Remove expired ITHC image

- apps/darts-modernisation/darts-gateway/darts-gateway.yaml
- apps/pip/account-management/test.yaml
- apps/pip/data-management/test.yaml
- apps/pip/frontend/test.yaml
- apps/pip/publication-services/test.yaml
- apps/pip/refresh-views-cron/test/01.yaml
- apps/pip/subscription-management/test.yaml
N/A
Checking Impl plan for CaTH (refresh views)
- The file `test.yaml` in `apps/pip/account-management` had multiple changes including addition of keyVaults, secrets, and aliases, along with changes to the image and replicas values.
- The file `test.yaml` in `apps/pip/data-management` had a change in the image value.
- The file `test.yaml` in `apps/pip/frontend` had a change in the image value.
- The file `test.yaml` in `apps/pip/publication-services` had a change in the image value.
- The file `01.yaml` in `apps/pip/refresh-views-cron` had a change in the image and schedule values.
- The file `test.yaml` in `apps/pip/subscription-management` had a change in the replicas value.
> Checking implementation plan cath

- apps/pre/demo/00/kustomization.yaml
- apps/pre/demo/01/kustomization.yaml
- apps/pre/demo/base/kustomization.yaml
- apps/pre/pre-api-cron-start-live-events/demo.yaml
See [S28-3815](https://tools.hmcts.net/jira/browse/S28-3815)
- Remove old cluster code
- Change schedule time to 9
- Deleted files: 
- `kustomization.yaml` in `apps/pre/demo/00`
- `kustomization.yaml` in `apps/pre/demo/01`
- Updated file `kustomization.yaml` in `apps/pre/demo/base`: Added a new patch path for cron job `pre-api-cron-start-live-events`
- Updated file `demo.yaml` in `apps/pre/pre-api-cron-start-live-events`: Changed the job schedule from \"0 7 * * *\" to \"0 9 * * *\"
> Fix: pre-api Demo Start Live Event Cron

- apps/pip/account-management/test.yaml
- apps/pip/data-management/test.yaml
- apps/pip/frontend/test.yaml
- apps/pip/publication-services/test.yaml
- apps/pip/subscription-management/test.yaml
Revert SM merge test images
- In `test.yaml` within the `pip/account-management` directory, the replicas for Java are changed from 2 to 0, and several keyVaults and secrets are removed.
- In `test.yaml` within the `pip/data-management` directory, the image for Java is changed.
- In `test.yaml` within the `pip/frontend` directory, the image for nodejs is changed, and several keyVaults and secrets are removed.
- In `test.yaml` within the `pip/publication-services` directory, the image for Java is changed.
- In `test.yaml` within the `pip/subscription-management` directory, the replicas for Java are changed from 0 to 2.
> Revert SM merge test images

- apps/darts-modernisation/darts-external-component-test-harness/test.yaml
Turning on the Test harness 150 instances
- `test.yaml` 🛠️
- Updated the number of replicas from 0 to 75.
> Turning on the Test harness 150 instances

- apps/pip/account-management/test.yaml
- apps/pip/data-management/test.yaml
- apps/pip/frontend/test.yaml
- apps/pip/publication-services/test.yaml
- apps/pip/subscription-management/test.yaml
Add SM merge test images
- Added image, keyVaults, and secrets for various services: account-management, data-management, frontend, publication-services, and subscription-management.
- Updated replica values for data-management and subscription-management services.
- Updated image paths for account-management, data-management, frontend, and publication-services services.
- Updated the replica value for subscription-management from 2 to 0.
> Add SM merge test images

- apps/darts-modernisation/darts-api/darts-api.yaml
- Added a new job section with an active deadline of 7200 seconds.
- Updated the image to sdshmctspublic.azurecr.io/darts/api:prod-0ccdd64-20250425162004.
- Adjusted CPU and memory requests and limits.
> increase ats timeout

- apps/pip/refresh-views-cron/prod/00.yaml
CHG5020830
Updated Cron Trigger time
- Updated the schedule for the job from \"0 2 * * 0,2,4,6\" to \"15 15 * * 0,2,4,6\" 🕒
> Updated cron trigger time

- apps/darts-modernisation/darts-api/prod.yaml
- Added a new environment variable `MAX_HANDHELD_AUDIO_FILES` with a value of 500.
> Set max handheld audio files

- apps/pre/pre-portal/prod.yaml
https://mojcppprod.service-now.com/nav_to.do?uri=%2Fincident.do%3Fsys_id%3Df525e41ec315ea501c85351c050131e0%26sysparm_stack%3D%26sysparm_view%3D
- Changed the value of TRIGGER from \"init-4\" to \"init-5\" 🔄
> Update prod.yaml to poke prod

- apps/juror/juror-api/demo.yaml
deploying interim10 on Demo for juror-api via image policy
deployment is for UAT 
yaml
apps/juror/juror-api/demo.yaml
- Updated the image for the Java application to \"sdshmctspublic.azurecr.io/juror/api:prod-b57be62-20250501130209\"
```
> deploy interim10 to Demo via image policy

- apps/darts-modernisation/darts-api/test.yaml
- apps/darts-modernisation/darts-automated-tasks/test.yaml
Added feign logging full to DARTS test
- `test.yaml`:
- Added `FEIGN_LOG_LEVEL: full` to the configuration.
This is the only relevant change for this pull request.
> Added DARTS feign logging level full to test

- apps/darts-modernisation/darts-api/test.yaml
- apps/darts-modernisation/darts-automated-tasks/test.yaml
Removed DARTS feign logging level full for test
- `apps/darts-modernisation/darts-api/test.yaml`
- Removed the `FEIGN_LOG_LEVEL` configuration.
- `apps/darts-modernisation/darts-automated-tasks/test.yaml`
- Removed the `FEIGN_LOG_LEVEL` configuration.
> Removed DARTS feign logging level full for test

- apps/pre/pre-api-cron-check-for-missing-recordings/test.yaml
- apps/pre/pre-api-cron-cleanup-live-events/test.yaml
- apps/pre/pre-api-cron-cleanup-streaming-locators/test.yaml
- apps/pre/pre-api-cron-close-pending-cases/test.yaml
- apps/pre/pre-api-cron-start-live-events/test.yaml
Changing environment tags and enabling cron 
- `test.yaml`
- Updated the `PLATFORM_ENV_TAG` from \"Test\" to \"Testing\" for various cron jobs.
- Changed the `suspend` schedule for the `pre-api-cron-start-live-events` job from \"30 7 * * *\" to \"30 16 * * *\".
> Update env tag pre

- apps/pre/pre-api-cron-cleanup-live-events/test.yaml
Updating cron timing on test env
- Changed the schedule from \"30 16 * * *\" to \"30 11 * * *\"
> update cron timing

- apps/pre/pre-api-cron-cleanup-live-events/test.yaml
- Changed schedule from \"30 11 * * *\" to \"30 15 * * *\"
- Updated image to sdshmctspublic.azurecr.io/pre/api:pr-921-3a04c4e-20250516081344
> reset policy name

- apps/pre/pre-api-cron-cleanup-live-events/test.yaml
- apps/pre/pre-api-cron-start-live-events/test.yaml
- Updated the job schedule from \"30 9 * * *\" to \"0 10 * * *\"
- Updated the job schedule from \"30 16 * * *\" to \"0 10 * * *\"
> PRE perf test cron times

- apps/pre/pre-api-cron-cleanup-live-events/test.yaml
- apps/pre/pre-api-cron-start-live-events/test-image-policy.yaml
- apps/pre/pre-api-cron-start-live-events/test.yaml
- `apps/pre/pre-api-cron-cleanup-live-events/test.yaml`
- Updated the schedule from \"0 10 * * *\" to \"30 11 * *\"
- `apps/pre/pre-api-cron-start-live-events/test-image-policy.yaml`
- Updated the pattern to 'pr\-920\-51b5474\-20250519091257'
- `apps/pre/pre-api-cron-start-live-events/test.yaml`
- Updated the schedule from \"0 10 * * *\" to \"0 11 * *\"
- Updated the image to \"sdshmctspublic.azurecr.io/pre/api:pr-920-51b5474-20250519091257\"
> PRE test env start live event image

- apps/darts-modernisation/darts-gateway/test.yaml
- Added a new image for the Java service.
- Updated the ingress host to darts-gateway.test.platform.hmcts.net.
> temp logging gateway 

- apps/dynatrace/demo/base/kustomization.yaml
- clusters/demo/base/kustomization.yaml
https://tools.hmcts.net/jira/browse/DTSPO-25380
Upgrade not deploying on demo, rolling back for test (only commenting out lines as plan to add back) 
---
- **apps/dynatrace/demo/base/kustomization.yaml**
- Removed paths for `dynatrace-operator-upgrade.yaml` and `dynatrace-operator-helmrepo-upgrade.yaml`.
- **clusters/demo/base/kustomization.yaml**
- Removed path for `apps/dynatrace/demo/base/kustomize.yaml`.
> Revert back to last version for testing

- apps/dynatrace/demo/base/kustomization.yaml
- clusters/demo/base/kustomization.yaml
Reverts hmcts/sds-flux-config#6620
- The `apps/dynatrace/demo/base/kustomization.yaml` file was modified to include a new path for `dynatrace-operator-helmrepo-upgrade.yaml`.
- The `clusters/demo/base/kustomization.yaml` file was modified to include a new path for `apps/dynatrace/demo/base/kustomize.yaml`.
> Revert "Revert back to last version for testing"

- apps/monitoring/version-reporter/ptl/version-reporter.enc.yaml
Updated secrets from CNP PR - https://github.com/hmcts/cnp-flux-config/pull/36752/files 
- Updated the `client_id`, `client_secret`, `cosmos_key`, and `tenant_id` with new values.
- Updated the `vault_url` to a new address.
- Updated the `version` and `created_at` fields with new values.
- Updated the `lastmodified` and `mac` fields with new values.
> trying with secrets from cnp

- apps/juror/juror-api/image-policy.yaml
- apps/juror/juror-bureau/image-policy.yaml
Juror api and bureau deployments for release5.8
- Updated image-policy.yaml``` in the ```juror-api``` and ```juror-bureau``` directories
- Changed the pattern to match image tags from ```^pr-922``` to ```^pr-929``` for ```juror-api```
- Changed the pattern to match image tags from ```^pr-941``` to ```^pr-945``` for ```juror-bureau```
> update juror deployment for release5.8 into test

- apps/opal/demo/base/kustomization.yaml
- apps/opal/opal-file-handler/demo.yaml
- apps/opal/opal-fines-service/demo.yaml
- apps/opal/opal-frontend/demo.yaml
- apps/opal/opal-legacy-db-stub/demo.yaml
- apps/opal/opal-user-service/demo.yaml
- apps/opal/serviceaccount/demo.yaml
- clusters/demo/base/kustomization.yaml
ℹ️ Created a new file `apps/opal/demo/base/kustomization.yaml` containing kustomization configurations for Opal application demo environment.
📄 Added new files for HelmReleases and updated configurations for opal-file-handler, opal-fines-service, opal-frontend, opal-legacy-db-stub, opal-user-service, and service account in the `apps/opal` directory for demo environment.
📄 Updated `clusters/demo/base/kustomization.yaml` to include references to Opal application kustomize.yaml file.
> Add Kustomization and HelmRelease configurations for Opal application

- apps/darts-modernisation/darts-api/darts-api.yaml
- **darts-api.yaml**
- Updated memory and CPU requests and limits for the `darts-api` job.
- Changed `memoryRequests` from '2G' to 500Mi.
- Added `cpuRequests: 500m`.
- Changed `memoryLimits` from '3G' to 4Gi.
- Added `cpuLimits: 4`.
> move keda limits up

- apps/darts-modernisation/darts-api/prod.yaml
- apps/darts-modernisation/darts-automated-tasks/prod.yaml
- apps/darts-modernisation/darts-gateway/prod.yaml
was enabled as part of https://tools.hmcts.net/jira/browse/DTSPO-16592 but didn't get removed
---
- Removed `pdb` related configurations for `darts-api`, `darts-automated-tasks`, and `darts-gateway` in the production environment 🛠️
> set pdb back to default

- apps/darts-modernisation/darts-api/stg.yaml
- stg.yaml
- Added a preStop lifecycle hook to the container, running a command to sleep for 10 seconds before termination.
> Trying preStop hook in staging darts-api

- apps/darts-modernisation/darts-api/stg.yaml
- Updated stg.yaml in apps/darts-modernisation/darts-api
- Added readinessPeriod: 5 and terminationGracePeriodSeconds: 65
- Added GRACEFUL_SHUTDOWN_TIMEOUT: '35s'
> DARTS API staging changes

- apps/pip/data-management/test.yaml
Remove old data-management image
Remove old data-management image
yaml
apps/pip/data-management/test.yaml
- Removed one entry from the 'java' values under 'spec'
- Updated the image tag to 'pr-712-3e09f5b-20250520110317'
- Updated the number of replicas to 2
```
> Remove old data-management image

- apps/neuvector/neuvector/ithc/ithc.yaml
- apps/neuvector/neuvector/neuvector.yaml
- apps/neuvector/neuvector/stg/stg.yaml
- apps/neuvector/neuvector/test/test.yaml
https://tools.hmcts.net/jira/browse/DTSPO-26055
Patching neuvector version to 1.6.3
- `ithc.yaml` 🔄:
- Removed `chart` and `spec` fields from the YAML file.
- `neuvector.yaml` 🔄:
- Updated `version` from 1.5.9 to 1.6.3 in the YAML file.
- `stg.yaml` 🔄:
- Removed `chart` and `spec` fields from the YAML file.
- `test.yaml` 🔄:
- Removed `chart` and `spec` fields from the YAML file.
> update neuvector version

- apps/dynatrace/dynatrace-crds/kustomization.yaml
n/a
Patch CRD version
- **kustomization.yaml**
- Updated the URL for the Dynatrace Operator CRD from version 1.3.2 to version 1.5.1. 🔄
> Patch crd version

- apps/juror/juror-api/demo.yaml
testing JS-410
deploying JS-410 into Demo only
* [ x] No
- Updated the Java image version to `pr-940-e268652-20250611131432` 🛠️
> deploying juror api to demo for PR 940

- apps/juror/juror-bureau/demo.yaml
- apps/juror/juror-public/demo.yaml
deploying JS-359, JS-368, and JS-355 into Demo only
This deployment is for testing.
- Changed `demo.yaml` in `apps/juror/juror-bureau/`: Updated the image tag to `pr-952-ea8d0b0-20250612102300`.
- Changed `demo.yaml` in `apps/juror/juror-public/`: Updated the image tag to `pr-304-1fd2e8c-20250613105301`.
> deploy juror-bureau and juror-public into demo

- apps/juror/juror-api/image-policy.yaml
- apps/juror/juror-bureau/image-policy.yaml
- apps/juror/juror-public/image-policy.yaml
Update ITHC with release5.9 for juror-api, bureau and public via image policy
deployment Is for testing
- `apps/juror/juror-api/image-policy.yaml`
- `apps/juror/juror-bureau/image-policy.yaml`
- `apps/juror/juror-public/image-policy.yaml`
- Updated image pattern to `'^pr-944-[a-f0-9]+-(?P<ts>[0-9]+)'` in `image-policy.yaml` for `juror-api` app.
- Updated image pattern to `'^pr-954-[a-f0-9]+-(?P<ts>[0-9]+)'` in `image-policy.yaml` for `juror-bureau` app.
- Updated image pattern to `'^pr-306-[a-f0-9]+-(?P<ts>[0-9]+)'` in `image-policy.yaml` …
> juror deployment to update ITHC with release5.9

- apps/juror/juror-public/demo.yaml
Updating juror Demo with latest prod image for juror-api
- Changed file: `demo.yaml`
- Updated the `nodejs` image from `sdshmctspublic.azurecr.io/juror/public:pr-304-1fd2e8c-20250613105301` to `sdshmctspublic.azurecr.io/juror/public:prod-1f1a0a7-20250613110208`
> update Juror Demo with latest prod image for api

- apps/mi/mi-azure-functions/test.yaml
- Updated the image tag from \"pr-233-21dca66-20250527155416\" to \"test-9099fba-20250613132610\" for mi-azure-functions.
> Update Mi Azure Functions test image

- clusters/test/base/kustomization.yaml
https://tools.hmcts.net/jira/browse/VIH-9650?filter=-1
Remove Test Environment from SDS.
```
[ ] Yes
[ X] No
```
> VIH-9650 remove test environment from SDS

- apps/jenkins/jenkins/jenkins.yaml
https://tools.hmcts.net/jira/browse/DTSPO-26313
- Changed `repoOwner` from `hmcts` to `HMCTS`.
- Adjusted `repoOwner` value from `hmcts` to `HMCTS`.
> DTSPO-26313 changing repoOwner to HMCTS

- apps/courtfines/demo/base/kustomization.yaml
- apps/courtfines/ithc/base/kustomization.yaml
- apps/courtfines/prod/base/kustomization.yaml
- apps/courtfines/test/base/kustomization.yaml
- clusters/demo/base/kustomization.yaml
- clusters/ithc/base/kustomization.yaml
- clusters/prod/base/kustomization.yaml
- clusters/test/base/kustomization.yaml
Added demo,test,ithc and prod envs configs to courtfines
- apps/courtfines/demo/base/kustomization.yaml 🎉
- Added a new kustomization file for demo environment with resource and namespace configuration.
- apps/courtfines/ithc/base/kustomization.yaml 🎉
- Added a new kustomization file for ithc environment with resource and namespace configuration.
- apps/courtfines/prod/base/kustomization.yaml 🎉
- Added a new kustomization file for prod environment with resource and namespace configuration.
- apps/courtfines/test/base/kustomization.yaml 🎉
- Added a new kustomization file for test environment with resource and namespace configuration.
- clusters/demo/base/kustomization.yaml
- Added reference to the courtfines kustomization within the demo environment resources.
- …
> Added additional court fines apps

- apps/juror/juror-public/demo.yaml
Deploy juror-public into Demo
This deployment is for testing.
- Updated the image version from `pr-304-60bcfc4-20250618112212` to `pr-304-53c12c6-20250619060130` 📷
> Deploy juror-public to demo

- apps/courtfines/courtfines-app/demo.yaml
- apps/courtfines/courtfines-app/stg.yaml
Added Demo and stage env files 
- `demo.yaml` 🆕
- Added a new file for the courtfines app's demo environment configuration.
- Specifies HelmRelease metadata, releaseName, values for nodejs, ingressHost, and environment.
- `stg.yaml` 🆕
- Added a new file for the courtfines app's staging environment configuration.
- Specifies HelmRelease metadata, releaseName, values for nodejs, ingressHost, and environment.
> Added courtfines env files

- apps/darts-modernisation/darts-portal/stg.yaml
Reducing down to the default 2 replicas, same as all other environments.
- Removed 1 replica from the `nodejs` deployment.
- Updated the `DARTS_API_URL` environment variable to `https://darts-api.staging.platform.hmcts.net`.
- Updated the `ingressHost` to `darts.staging.apps.hmcts.net`.
> Amend DARTS portal staging replicas

- apps/juror/juror-bureau/demo.yaml
Deploying [JS-436](https://tools.hmcts.net/jira/browse/JS-436) into Demo.
This deployment is for testing.
- Updated the `nodejs` image to `sdshmctspublic.azurecr.io/juror/bureau:pr-952-e63e5ab-20250624105205` and `ingressHost` to `juror.demo.apps.hmcts.net`.
- Added `SKIP_SSO: true` to the environment variables.
> Deploy juror-bureau GDS Update branch to demo

- apps/darts-modernisation/darts-external-component-test-harness/test.yaml
- Changed the number of replicas from 75 to 0.
- Updated the value for `ingressHost` to darts-external-component-test-harness.test.platform.hmcts.net.
> Turn off test harness

- apps/pip/frontend/demo.yaml
https://tools.hmcts.net/jira/browse/PUB-2825
Add GOV.UK frontend rebrand image to demo
- Changed file: `demo.yaml`
- Updated the `nodejs` image to `sdshmctspublic.azurecr.io/pip/frontend:pr-1495-26c7256-20250625081357` 🐳
- Updated `ingressHost` to `pip-frontend.demo.platform.hmcts.net` 🌐
- Updated `DATA_MANAGEMENT_URL` to `https://pip-data-management.demo.platform.hmcts.net`
> PUB-2825 Add GOV.UK frontend rebrand image to demo

- apps/pip/frontend/demo.yaml
- apps/pip/publication-services-mi-reporting-cron/ithc/00.yaml
- apps/pip/publication-services-mi-reporting-cron/test/01.yaml
- apps/pip/refresh-views-cron/test/01.yaml
Revert PIP images and cron timer
Revert PIP images and cron timer
- Removed one of the values for the nodejs image.
- Updated the schedule for the job from \"15 15 * * *\" to \"01 08 * * 0,2,4,6\".
- Updated the schedule for the job from \"50 14 * * 1,3,5\" to \"01 08 * * 1,3,5\".
- Removed an image value for the job.
> Revert PIP images and cron timer

- apps/darts-modernisation/darts-gateway/test.yaml
- Removed the `autoscaling` section from the YAML file.
- Updated the `TESTING_SUPPORT_ENDPOINTS_ENABLED` to `true`.
> DARTS gateway - enable autoscaling in test

- apps/darts-modernisation/darts-api/test.yaml
- Updated test.yaml``` in ```darts-modernisation/darts-api```:
- Reduced the number of replicas from 6 to 4.
> DARTS Gateway - set test replicas to 4

- apps/juror/juror-bureau/image-policy.yaml
Updating the PR branch to release5.9b for bureau
release is for testing and UAT
* [ x] No
- Updated file: image-policy.yaml
- Changed the filterTags pattern from '^pr-954-[a-f0-9]+-(?P<ts>[0-9]+)' to '^pr-962-[a-f0-9]+-(?P<ts>[0-9]+)' 🔒
> update for deploying release5.9b PR for juror bureau

- apps/darts-modernisation/darts-external-component-test-harness/test.yaml
- Increased the number of replicas for the `java` service from 0 to 75.
- Updated the `ingressHost` to darts-external-component-test-harness.test.platform.hmcts.net.
- Set the `DARTS_LOG_LEVEL` environment variable to INFO.
> Start test harness

- apps/darts-modernisation/darts-external-component-test-harness/test.yaml
- Changed the number of replicas from 75 to 0
- Updated the value of `ingressHost` to `darts-external-component-test-harness.test.platform.hmcts.net`
> Stop test harness

- apps/juror/juror-pnc/ithc.yaml
https://tools.hmcts.net/jira/browse/JS-371
Updating juror-pnc deployment to ITHC
deployment for testing
* [ x] No
- apps/juror/juror-pnc/ithc.yaml```
- Changed the Java image version to ```pr-196-6afe5b2-20250707120711``` from ```prod-fe04bfc-20250227143053```.
> juror deployment for juror pnc

- apps/juror/juror-pnc/ithc.yaml
this is for release5.10
[JS-137 ](https://tools.hmcts.net/jira/browse/JS-371)
Replace Jitpack as its no longer supported
Fix failing integration tests
Deployment is for testing
* [x ] No
- Updated the image version to `pr-197-8da70e1-20250707140609` in the `java` section under `values`.
- Environment variable `PNC_SERVICE_PNC_TRAN_CODE` has been set to an empty string.
> juror deployment for pnc into ITHC

- apps/pre/pre-api/stg.yaml
- `stg.yaml` 🔄
- Added a new environment variable `HIKARI_POOL_SIZE` with a value of 25.
- Modified the value of `VAR_TA` to `Trigger-1`.
> Increase PRE stg db pool size

- apps/azureserviceoperator-system/dev/base/kustomization.yaml
- apps/azureserviceoperator-system/dev/base/toleration_patch.yaml
See [DTSPO-26608](https://tools.hmcts.net/jira/browse/DTSPO-26608)
Updating ASO in dev to v2.14.0
k kustomize . is good and shows 2.14 to be installed
- Updated `kustomization.yaml` in `apps/azureserviceoperator-system/dev/base`:
- Added a new resource from a URL link to Azure Service Operator release.
- Added a new resource from local directory `././cert-manager`.
- Added a new patch to include additional args for a container and update nodeSelector for a deployment.
- Added `toleration_patch.yaml` in `apps/azureserviceoperator-system/dev/base`:
- Contains toleration settings for …
> chore(dev): update aso to v2.14.0

- CODEOWNERS
- apps/courtfines/demo/base/kustomization.yaml
- apps/courtfines/ithc/base/kustomization.yaml
- apps/courtfines/stg/base/kustomization.yaml
Added patches for courtfines app
- **CODEOWNERS**:
- Added codeowners for `apps/courtfines` and `apps/appreg`.
- **apps/courtfines/demo/base/kustomization.yaml**:
- Added a path for `courtfines-app/demo.yaml` in the resources section.
- **apps/courtfines/ithc/base/kustomization.yaml**:
- Added a path for `courtfines-app/ithc.yaml` in the resources section.
- **apps/courtfines/stg/base/kustomization.yaml**:
- Added a path for `courtfines-app/stg.yaml` in the resources section.
> Updated courtfines ingress config

- apps/pdda/demo/base/kustomization.yaml
- apps/pdda/pdda-public-display-data-aggregator/demo.yaml
- apps/pdda/pdda-public-display-manager/demo.yaml
- apps/pdda/serviceaccount/demo.yaml
- Modified `kustomization.yaml` in `apps/pdda/demo/base/`:
- Added references to `pdda-public-display-data-aggregator.yaml` and `pdda-public-display-manager.yaml`.
- Added `demo.yaml` files for `pdda-public-display-data-aggregator` and `pdda-public-display-manager` in `apps/pdda/`:
- Each file sets up a HelmRelease for the respective applications and includes specific values for Java, environment variables, and logging levels.
- Added `demo.yaml` for the service account in `apps/pdda/serviceaccount/`:
- Specifies the service account metadata, including …
> add in pdda demo config

- CODEOWNERS
- apps/pdda/demo/base/kustomization.yaml
- clusters/demo/base/kustomization.yaml
- Updated the CODEOWNERS``` file, changing the ownership of the ```apps/pdda/``` and ```apps/courtfines/``` directories to start with uppercase letters. 
- Removed the deletion of the ```workload-identity``` and updated the paths in the ```apps/pdda/demo/base/kustomization.yaml``` file.
- Added the ```apps/pdda/base/kustomize.yaml``` resource in the ```clusters/demo/base/kustomization.yaml``` file.
> Pdda demo namespace

- apps/flux-system/base/kustomization.yaml
- apps/flux-system/base/neuvector-helmrepo.yaml
- apps/neuvector/crds/crds-neuvector.yaml
- apps/neuvector/crds/kustomization.yaml
- clusters/ithc/base/kustomization.yaml
- clusters/stg/base/kustomization.yaml
- clusters/test/base/kustomization.yaml
https://tools.hmcts.net/jira/browse/DTSPO-26371
Like the recent changes in CFT, SDS now uses the new Neuvector CRDS.
ℹ️  apps/flux-system/base/kustomization.yaml
- Added a new file neuvector-helmrepo.yaml to the resources list.
🔄 apps/flux-system/base/neuvector-helmrepo.yaml
- Added a new HelmRepository neuvector-helmrepo.yaml.
🆕 apps/neuvector/crds/crds-neuvector.yaml
- Added a new file crds-neuvector.yaml defining a HelmRelease for neuvector-crd.
🔄 apps/neuvector/crds/kustomization.yaml
- Included crds-neuvector.yaml in the resources list.
🔄 clusters/ithc/base/kustomization.yaml
- Updated the resources list by adding …
> Update non prod SDS to use Neuvector CRDs

- apps/appreg/base/kustomization.yaml
- apps/appreg/base/kustomize.yaml
- apps/appreg/demo/base/kustomization.yaml
- apps/appreg/dev/base/kustomization.yaml
- apps/appreg/ithc/base/kustomization.yaml
- apps/appreg/stg/base/kustomization.yaml
- clusters/demo/base/kustomization.yaml
- clusters/dev/base/kustomization.yaml
- clusters/ithc/base/kustomization.yaml
- clusters/stg/base/kustomization.yaml
added initial appreg flux config
- Added kustomization files for appreg, demo, dev, ithc, and stg environments specifying resources and namespaces
- Updated kustomization files for various clusters by adding appreg as a resource
- Patched kustomization files for dev, ithc, and stg clusters to include appreg as a resource
> added initial appreg flux config

- apps/flux-system/automation/kustomization.yaml
- apps/rota/automation/kustomization.yaml
- apps/rota/base/kustomization.yaml
- apps/rota/base/kustomize.yaml
- apps/rota/demo/base/kustomization.yaml
- apps/rota/ithc/base/kustomization.yaml
- apps/rota/rota-frontend/image-policy.yaml
- apps/rota/rota-frontend/image-repo.yaml
- apps/rota/serviceaccount/demo.yaml
- apps/rota/serviceaccount/ithc.yaml
- apps/rota/serviceaccount/stg.yaml
- apps/rota/serviceaccount/test.yaml
- apps/rota/stg/base/kustomization.yaml
- apps/rota/test/base/kustomization.yaml
- clusters/demo/base/kustomization.yaml
- clusters/ithc/base/kustomization.yaml
- clusters/stg/base/kustomization.yaml
- clusters/test/base/kustomization.yaml
- Added `apps/flux-system/automation/kustomization.yaml`
- Added `apps/rota/automation/kustomization.yaml`
- Added `apps/rota/base/kustomization.yaml`
- Added `apps/rota/base/kustomize.yaml`
- Added `apps/rota/demo/base/kustomization.yaml`
- Added `apps/rota/ithc/base/kustomization.yaml`
- Added `apps/rota/rota-frontend/image-policy.yaml`
- Added `apps/rota/rota-frontend/image-repo.yaml`
- Added `apps/rota/serviceaccount/demo.yaml`
- Added `apps/rota/serviceaccount/ithc.yaml`
- Added `apps/rota/serviceaccount/stg.yaml`
- Added …
> add in rota config

- apps/darts-modernisation/darts-api/test.yaml
- Changed the value of RESTART_ME from '009' to '010' 🔄
> Restart Perf Test

- apps/juror/juror-scheduler-execution/demo.yaml
- apps/juror/juror-scheduler-execution/ithc.yaml
Update deployment for juror-scheduler-execution into ITHC and DEMO
This change required to carry out testing 
- Updated the image version to `pr-246-0ad76d5-20250716134840`
- Updated the `ingressHost` to `juror-scheduler-execution.demo.platform.hmcts.net`
- Updated the image version to `pr-246-0ad76d5-20250716134840`
- Updated the `ingressHost` to `juror-scheduler-execution.ithc.platform.hmcts.net`
> Update  juror-scheduler-execution deployment into ITHC and DEMO

- apps/pre/pre-api/demo.yaml
- Changed `ENABLE_AUTOMATED_EDITING` from `false` to `true` 🔄
> S28-0000 Set enable automated editing to true for PRE

- apps/juror/juror-pnc/demo.yaml
- apps/juror/juror-public/demo.yaml
updating public and pnc in Demo with release5.10 images
* [ x] No
- Updated the Java image to `sdshmctspublic.azurecr.io/juror/pnc:pr-197-8da70e1-20250707140609`
- Modified the `ingressHost` to `juror-pnc.demo.platform.hmcts.net`
- Environment variable `PNC_SERVICE_PNC_TRAN_CODE` set to `'`
- No relevant changes
> updating Demo with public and pnc for release5.10

- apps/pre/pre-api-cron-perform-edit-requests/demo.yaml
- Un-suspend edit cron in demo
> feat(pre-api): un-suspend edit cron in demo

- apps/juror/juror-bureau/demo.yaml
- apps/juror/juror-public/demo.yaml
- apps/opal/opal-frontend-test/opal-frontend-test.yaml
Deploy juror frontend Bureau and Public apps into Demo 
Deploying into Demo for testing
- Updated the image version to \"pr-969-5d299af-20250709112116\"
- Set environment variable \"SKIP_SSO\" to true
- Updated the image version to \"pr-310-44e63d1-20250709113033\"
> juror-bureau and juror-public deploy into Demo

- apps/met/pod-delete-cron/prod.yaml
md
- Changed file: apps/met/pod-delete-cron/prod.yaml
- Updated the schedule from \"50 22 * * *\" to suspend the cron job at those times by setting ```suspend: true```
```
> Update prod.yaml INC3486825 suspend overnight pod bounce

- apps/darts-modernisation/darts-api/prod.yaml
- Changed the value of `RESTART_ME` from `'008'` to `'009'`.
> Redeploy to ensure new B2C secret is picked up

- apps/met/pod-delete-cron/prod.yaml
- Changed file: prod.yaml```
- Updated the schedule from \"50 22 * * *\" to \"50 22 * * *\"
- Set the `suspend` value to `true` instead of `false`
> Update prod.yaml INC3486825

- apps/pip/frontend/test.yaml
https://tools.hmcts.net/jira/browse/PUB-2555
Updated frontend test image for pip
- Added new image for nodejs: `sdshmctspublic.azurecr.io/pip/frontend:pr-1509-e47db52-20250729105857`
- Increased replicas to 2 for the frontend component
> PUB-2555 - Updated frontend

- apps/darts-modernisation/darts-api/test.yaml
- apps/darts-modernisation/darts-gateway/test.yaml
- Removed the image field with value `sdshmctspublic.azurecr.io/darts/api:pr-2989`.
- Removed the replicas field value 4.
- Removed the memory and CPU request and limit values.
- Removed the job section with its activeDeadlineSeconds field.
- Removed the replicas field value 6.
> Aligned darts test to prod

- apps/juror/juror-pnc/ithc.yaml
https://tools.hmcts.net/jira/browse/JS-519
Deploying PNC service to test new LEDS interface
Deployment is for testing and will be rolled back
* [ x] No
- `ithc.yaml` 🔄 Changed image version for juror PNC app to `pr-198-cc26d82-20250801143626`
- `ithc.yaml` 🔄 Updated `PNC_SERVICE_HOST` to `api.test.leds.nprod.tgwv2.police.uk` and `PNC_SERVICE_POST` to `443`
> Testing the juror LEDS connectivity

- apps/darts-modernisation/darts-api/demo.yaml
- apps/darts-modernisation/darts-api/test.yaml
- apps/darts-modernisation/darts-automated-tasks/demo.yaml
- apps/darts-modernisation/darts-automated-tasks/test.yaml
Restarting test & demo envs for darts-api & automated tasks
- `demo.yaml`:
- Updated the `RESTART` value from `001` to `002`.
- `test.yaml`:
- Updated the `RESTART_ME` value from `'011'` to `'012'`.
- `demo.yaml` in `darts-automated-tasks`:
- Updated the `RESTART` value from `001` to `002`.
- `test.yaml` in `darts-automated-tasks`:
- Updated the `RESTART` value from `001` to `002`.
> Restarting test/demo

- apps/azureserviceoperator-system/dev/base/kustomization.yaml
- apps/azureserviceoperator-system/dev/base/toleration_patch.yaml
See [DTSPO-27197](https://tools.hmcts.net/jira/browse/DTSPO-27197)
Bumps ASO to v2.14.0 to attempt to resolve some issues that we are seeing on the ASO pods:
```
E0815 10:32:07.229067       1 reflector.go:158] "Unhandled Error" err="pkg/mod/k8s.io/client-go@v0.31.1/tools/cache/reflector.go:243: Failed to watch *storage.FlexibleServer: failed to list │
│  *storage.FlexibleServer: request to convert CR from an invalid group/version: dbforpostgresql.azure.com/v1api20240801storage" logger="UnhandledError"
```
```
➜ k get flexibleservers -A                                               
Error from server: request to convert CR from an invalid group/version: dbforpostgresql.azure.com/v1api20240801storage
```
k kustomize . shows valid output
**CVE Suppression:** Are there any CVEs present in the …
> chore(aso): bump to v2.14.0 in dev

- apps/monitoring/kube-prometheus-stack-crds-upgrade/kustomization.yaml
- apps/monitoring/kube-prometheus-stack-crds-upgrade/kustomize.yaml
- apps/monitoring/kube-prometheus-stack/sbox/00.yaml
- apps/monitoring/kube-prometheus-stack/sbox/01.yaml
- clusters/sbox/base/kustomization.yaml
DTSPO-26956
Upgrade prometheus in sbox with patch file
> DTSPO-26956 - Upgrade prometheus in sbox with patch file

- apps/monitoring/kube-prometheus-stack/ptl/00.yaml
- clusters/ptl/base/kustomization.yaml
DTSPO-26956
Upgrade Prometheus in PTL using patch file
> DTSPO-26956 - Upgrade Prometheus in PTL using patch file

- apps/admin/traefik2/demo/00-traefik2.yaml
- apps/admin/traefik2/demo/01-traefik2.yaml
- apps/admin/traefik2/dev/00-traefik2.yaml
- apps/admin/traefik2/dev/01-traefik2.yaml
- clusters/demo/base/kustomization.yaml
- clusters/dev/base/kustomization.yaml
See [DTSPO-26576](https://tools.hmcts.net/jira/browse/DTSPO-26576)
Upgrade Traefik to version 37.0.0 for dev and demo envs
N/A
> Upgrade Traefik to version 37.0.0 for dev and demo envs

- apps/appreg/appreg-frontend/demo.yaml
- apps/appreg/appreg-frontend/ithc.yaml
- apps/appreg/appreg-frontend/stg.yaml
Updated Ingress host for Applications Register
> ARCPOC-168 - Updated Ingress host for Applications Register

- apps/juror/juror-api/ithc.yaml
- apps/juror/juror-pnc/ithc.yaml
- apps/juror/juror-scheduler-api/ithc.yaml
- apps/juror/juror-scheduler-execution/ithc.yaml
updating images in ITHC for SpringBoot testing
* [ x] No
> updating images in ITHC for springboot update

- apps/pre/pre-api-cron-cleanup-null-durations/demo.yaml
- Enable null duration cron in demo
> feat(pre-api): enable null duration cron in demo

- apps/pip/frontend/stg.yaml
https://tools.hmcts.net/jira/browse/PUB-2982
Deploy Crime Idam changes on STG environment
> Deploy Crime Idam changes on STG environment

- apps/pip/account-management/test.yaml
https://tools.hmcts.net/jira/browse/PUB-2634
Added auto scaling to test
> PUB-2634 - Added Autoscaling

- apps/pip/account-management/test.yaml
- apps/pip/data-management/test.yaml
- apps/pip/publication-services/test.yaml
https://tools.hmcts.net/jira/browse/PUB-2634
Updated auto-scaling in Test
> PUB-2634 - Updated auto scaling in Test

- apps/pre/pre-api-cron-vodafone-etl-fetch-data/prod.yaml
Runs Wednesday on 27 Aug 4.3pm UTC (5.3pm BST)
> Vodafone - FetchData job 

- apps/darts-modernisation/darts-api/demo.yaml
https://github.com/hmcts/darts-api/pull/2967
Point demo to PR for dmp-5138
> DMP-5138 Update demo.yaml

- apps/pip/account-management/test.yaml
- apps/pip/data-management/test.yaml
- apps/pip/frontend/test.yaml
- apps/pip/publication-services/test.yaml
https://tools.hmcts.net/jira/browse/PUB-2634
Enable autoscaling for PIP frontend in Test
> PUB-2634 - Enable auto scaling for Frontend + Update values

- apps/pip/account-management/test.yaml
- apps/pip/data-management/test.yaml
- apps/pip/frontend/test.yaml
https://tools.hmcts.net/jira/browse/PUB-3002
Deploy security header changes on test environment
> PUB-3002 Deploy security header test environment

- apps/pip/account-management/stg.yaml
- apps/pip/frontend/stg.yaml
https://tools.hmcts.net/jira/browse/PUB-2979
Update frontend image to test new redis dependency
> PUB-2979 Update frontend image to test new redis dependency

- apps/pip/frontend/stg.yaml
https://tools.hmcts.net/jira/browse/PUB-2979
Revert frontend test image on Staging
> PUB-2979 Revert frontend test image on Staging

- apps/pre/pre-api-cron-vodafone-etl-process-full/stg.yaml
Runs Tuesday on 2 Sept 17.40 UTC (6.40pm BST)
> Vodafone process  job

- apps/pip/data-management/prod.yaml
https://tools.hmcts.net/jira/browse/PUB-2993
Disable PDDS LCSU for PROD
> PUB-2993 Disable PDDS LCSU for PROD

- apps/azure-devops/azure-devops-agent-keda/ptlsbox.yaml
> feat: try new agent image in ptlsbox

- apps/azure-devops/azure-devops-agent-keda/ptl.yaml
- apps/azure-devops/azure-devops-agent-keda/ptlsbox.yaml
> feat: revert ptlsbox image and bump cpu resource

- apps/opal/opal-user-service/test.yaml
- apps/opal/test/base/kustomization.yaml
> Activate opal-user-service in perftest

- apps/pip/account-management/test.yaml
- apps/pip/data-management/test.yaml
- apps/pip/frontend/test.yaml
https://tools.hmcts.net/jira/browse/PUB-3002
Deploy Changes on TEST Environment
> Deploy Changes on TEST Environment

- apps/pip/account-management/test.yaml
- apps/pip/data-management/test.yaml
https://tools.hmcts.net/jira/browse/PUB-3002
Deploy changes to TEST Env
> PUB-3002 Deploy changes to TEST Env

- apps/neuvector/ithc/base/kustomize.yaml
- apps/neuvector/neuvector/ithc/ithc.yaml
- apps/neuvector/patching-crds/crds-neuvector.yaml
- apps/neuvector/patching-crds/kustomization.yaml
- apps/neuvector/patching-crds/kustomize.yaml
- clusters/ithc/base/kustomization.yaml
See [DTSPO-27407](https://tools.hmcts.net/jira/browse/DTSPO-27407)
> making changes to patch neuvector 2.8.7 for ITHC

- apps/juror/juror-api/demo.yaml
- apps/juror/juror-api/image-policy.yaml
- apps/juror/juror-api/ithc.yaml
- apps/juror/juror-pnc/ithc.yaml
- apps/juror/juror-scheduler-api/ithc.yaml
- apps/juror/juror-scheduler-execution/ithc.yaml
Jira link
Update Juror-api
Scheduler-execution
scheduler-api
pnc-api to spring boot 3.5.4 and all realted depencies 
Testing  to be done
Security Vulnerability Assessment 
CVE Suppression:Are there any CVEs present in the codebase (either newly introduced or pre-existing) that are being intentionally suppressed or ignored by this commit?
* [x ] No
> Update ITHC with Spring boot 3.5.4

- apps/pip/account-management/stg.yaml
- apps/pip/publication-services/test.yaml
> Removed old images

- apps/pip/account-management/stg.yaml
- apps/pip/data-management/stg.yaml
- apps/pip/frontend/stg.yaml
https://tools.hmcts.net/jira/browse/PUB-3002
revert the deployment
> PUB-3002 Revert the deployment

- apps/pre/pre-api-cron-vodafone-etl-process-full/prod.yaml
Runs 16 Sept at 14.05UTC (15.05 BST)
> Run Vodafone Process Job

- apps/pre/pre-api-cron-vodafone-etl-process-full/prod.yaml
Runs 16 Sept 17.10 UTC (18.10 BST)
> Vodafone process job

- apps/neuvector/ithc/00/kustomization.yaml
- clusters/ithc/base/kustomization.yaml
> removing patch and resources from ithc 00

- apps/pre/pre-api/prod.yaml
Minor change to trigger pod updates for pre-api in prod
> Update prod.yaml to trigger pod updates

- apps/neuvector/ithc/00/kustomization.yaml
Reverts hmcts/sds-flux-config#7176
> Revert "removing patch and resources from ithc 00"

- apps/neuvector/stg/01/kustomization.yaml
> removing neuvector from stg 01

- apps/pre/pre-api-cron-vodafone-mk-import/stg.yaml
Runs Sept 17 14.30UTC (15.30BST)
> MK Assets STG

- apps/pre/pre-api-cron-vodafone-mk-import/stg.yaml
Runs 17 Sept 14:45UTC (15.45 BST)
> MK Asset STG

- apps/met/themis-fe/test.yaml
See [DTSPO-27571](https://tools.hmcts.net/jira/browse/DTSPO-27571)
Relaxed timings on startup probes in TEST env
> Relaxed timings on startup probes in TEST env

- apps/pre/pre-api-cron-vodafone-etl-process-full/stg.yaml
Runs 17 Sept at 17.00UTC (18.00BST)
> Run Process Job in staging against one test record #7175

- apps/neuvector/neuvector/stg/stg.yaml
> useWorkloadIdentity to true for stg config

- apps/pre/pre-api-cron-vodafone-etl-process-full/stg.yaml
Runs 18 Sept 15.10 UTC (16.10 BST)
> Vodafone process job #7157

- apps/toffee/frontend/sbox.yaml
Reverts hmcts/sds-flux-config#7226
Reverts  breaking change on toffee used for red hackathon
> Revert "introduce breaking change to test holmes"

- apps/pre/pre-api-cron-check-for-missing-recordings/test.yaml
- apps/pre/pre-api-cron-cleanup-live-events/test.yaml
- apps/pre/pre-api-cron-cleanup-null-durations/test.yaml
- apps/pre/pre-api-cron-cleanup-streaming-locators/test.yaml
- apps/pre/pre-api-cron-close-pending-cases/test.yaml
- apps/pre/pre-api-cron-perform-edit-requests/test.yaml
- apps/pre/pre-api-cron-start-live-events/test.yaml
- apps/pre/pre-api-cron-vodafone-etl-fetch-data/test.yaml
- apps/pre/pre-api/test.yaml
Remove pinning Test PRE API to PR-1118
> NO TICKET - remove pinning test env to pr-1118 image

- apps/pre/pre-api-cron-perform-edit-requests/prod.yaml
- apps/pre/pre-api/prod.yaml
See [S28-4365|https://tools.hmcts.net/jira/browse/S28-4365)
Configuration flags for 4.4.0 release (https://tools.hmcts.net/confluence/pages/viewpage.action?pageId=1864481321)
> S28-4365 configuration for PRE release 4.4.0

- apps/pre/pre-api-cron-cleanup-null-durations/prod.yaml
Suspend cleanup null durations job
> Suspend cleanup null durations job

- apps/pip/frontend/prod.yaml
https://tools.hmcts.net/jira/browse/PUB-3048
Restart prod pods
> Restart prod

- apps/darts-modernisation/darts-api/demo.yaml
> Restart demo api

- apps/admin/external-dns/external-dns.yaml
See [DTSPO-27856](https://tools.hmcts.net/jira/browse/DTSPO-27856)
Updates the external DNS chart to a version that still exists.
> Update external DNS chart for SDS

- apps/toffee/frontend/sbox.yaml
https://tools.hmcts.net/jira/browse/DTSPO-27899
Fix all the typos that were added that I was blind and somehow didn't notice were also there 🙄 
> Fix ALL the errors added to the toffee sbox config
