- k8s/environments/prod/cluster-00-overlay/.flux.yaml
- k8s/environments/prod/cluster-00-overlay/kustomization.yaml
- k8s/environments/prod/cluster-01-overlay/.flux.yaml
- k8s/environments/prod/cluster-01-overlay/kustomization.yaml
- k8s/namespaces/azure-devops/azure-devops-agent/patches/prod/cluster-00/azure-devops-agent.yaml
- k8s/namespaces/azure-devops/azure-devops-agent/patches/prod/cluster-01/azure-devops-agent.yaml
- k8s/stg/releases/mi/mi-data-extractor.yaml
- k8s/stg/releases/video-hearings/vh-video-api.yaml
https://tools.hmcts.net/jira/browse/DTSPO-588
Update to create flux folder structure in prod to deploy admin components and azure devops agent.
Note: Kube-slack, Kured and traefik manifests are currently disabled and to be enable later as required once the base components are in place and tested.
```
[ ] Yes
[x] No
```
> DTSPO-588 - Enable flux admin applications

- k8s/namespaces/admin/aad-pod-identity/mic-exception.yaml
- k8s/namespaces/kube-system/aad-pod-identity/mic-exception.yaml
Hitting an issue where the exception can't be applied in the same apply
as the CRD, so just applying the exception separately after, don't think
I really need kustomize for this
> Add namespace so that kubectl apply -f works

- k8s/environments/prod/cluster-00-overlay/kustomization.yaml
- k8s/environments/prod/cluster-01-overlay/kustomization.yaml
- k8s/environments/prod/common/secrets/kured-values.yaml
- k8s/release/admin/kured/patches/prod/cluster-00/kured.yaml
- k8s/release/admin/kured/patches/prod/cluster-01/kured.yaml
- k8s/release/admin/traefik/patches/prod/cluster-00/traefik.yaml
- k8s/release/admin/traefik/patches/prod/cluster-01/traefik.yaml
https://tools.hmcts.net/jira/browse/DTSPO-588
Update to enable Kured and Traefik on new shared service prod cluster
Leaving kube-slack disabled as I understand no longer in use
```
[ ] Yes
[x] No
```
> DTSPO 588 - enable kured and traefik

- k8s/environments/prod/cluster-00/mi/mi-integration-service-historical-notify.yaml
https://tools.hmcts.net/jira/browse/RMI-1044
Adds a one time job to ingest all historical notify data from a specified storage account (stored in key vault)
```
[ ] Yes
[x] No
```
> Add Historical Notify Ingestion Job for MI Prod

- k8s/release/admin/secrets-csi-driver/secrets-csi-driver.yaml
This is to fix a breaking change with kubernetes cluster update:
https://github.com/hmcts/aks-build-infrastructure/commit/3be7e5a031da07566e6b8b9a0e6cd7e3a72e78bf
AKS cluster was updated from 1.19.9 to 1.20.5
According to the changelog, there is a breaking change:
https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.20.md#no-really-you-must-read-this-before-you-upgrade-1
See the point about CSI drivers, from this PR:
https://github.com/kubernetes/kubernetes/pull/88759
Looking at the solution: the spec details:
https://github.com/container-storage-interface/spec/blob/master/spec.md#nodepublishvolume
This is a fix that should be done on the csi driver side. I can see this has been resolved as of 0.0.18 release: …
> Update csi secrets azure provider to latest 0.0.18

- k8s/environments/dev/common/mi/mi.yaml
- k8s/environments/test/common/mi/mi.yaml
Envs supporting kustomize for the specified namespace can derive its namespace details from the k8s/namespaces directory instead.
> Removed duplicate namespace from kustomized env

- k8s/namespaces/toffee/toffee-recipe-backend/toffee-recipe-backend.yaml
Upgrade toffee-recipe-backend chart to 0.8.3 to match the recent upgrade to the plum chart: https://github.com/hmcts/cnp-plum-recipes-service/blob/master/charts/plum-recipe-backend/Chart.yaml
```
[ ] Yes
[x] No
```
> Upgrade toffee-recipe-backend chart to 0.8.3

- k8s/release/mi/common/job/Chart.yaml
- k8s/release/mi/common/job/templates/secretprovider.yaml
- k8s/release/mi/mi-data-extractor-job/Chart.yaml
- k8s/release/mi/mi-extraction-service/Chart.yaml
- k8s/release/mi/mi-house-keeping-service/Chart.yaml
- k8s/release/mi/mi-integration-service/Chart.yaml
- k8s/release/mi/mi-staging-service/Chart.yaml
Helm doesn't interpolate values in the values.yaml by default.
This updates the mi-job chart to template the variable before using it in the context.
> Fixed wrong resourceGroup for vaults and bumped chart versions

- k8s/namespaces/mi/mi-sftp-server/mi-sftp-server.yaml
- k8s/release/mi/common/job/Chart.yaml
- k8s/release/mi/common/job/templates/_helpers.tpl
- k8s/release/mi/common/job/templates/_jobspec.tpl
- k8s/release/mi/common/job/templates/secretprovider.yaml
- k8s/release/mi/mi-data-extractor-job/Chart.yaml
- k8s/release/mi/mi-extraction-service/Chart.yaml
- k8s/release/mi/mi-house-keeping-service/Chart.yaml
- k8s/release/mi/mi-integration-service/Chart.yaml
- k8s/release/mi/mi-staging-service/Chart.yaml
Using mi-extraction-service pod identity instead to match its immediate using service.
Removed globals.environment from the secret provider class naming to simplify its usage by other components.
Updated chart history to maintain visibility.
> Update identity used by mi-sftp and simplified mi-job chart secret provider naming

- k8s/environments/dev/common/mi/mi-azure-functions.yaml
- k8s/environments/ithc/common/mi/mi-azure-functions.yaml
- k8s/environments/sbox/common/mi/mi-azure-functions.yaml
- k8s/environments/stg/common/mi/mi-azure-functions.yaml
- k8s/environments/test/common/mi/mi-azure-functions.yaml
Added mounting the encryption-publicKey secret for all envs (except prod)
Added mounting the encryption-publicKey secret for all envs (except prod)
This allows the mi-azure-functions to properly encrypt blobs on request.
Also added ingestion ADF config to ITHC and STG allowing the scheduled ingestion cleanup to run.
```
[ ] Yes
[x] No
```
> MI Update Azure Functions secrets

- k8s/namespaces/jenkins/patches/ptlsbox/cluster-00/jenkins.yaml
Updating tf_state_storage_template to match standard syntax. Previous setting matched pre-existing storage account name
> DTSPO-2879 - State store name update

- k8s/environments/stg/common/mi/mi-sftp-server.yaml
Add local mi sftp server on stg for export tests.
This is so we don't push test data to MoJ SFTP.
Note this is a quick fix and we should migrate to use kustomize in the future.
```
[ ] Yes
[x] No
```
> Add local mi sftp server on stg for export tests.

- k8s/environments/ithc/common-overlay/flux-patch.yaml
- DTSPO-2880 - Updating flux patch for toffee to point to sdshmctspublic acr
- DTSPO-2880 - Updating flux patch for toffee to point to sdshmctspublic acr
> DTSPO-2880 - updating toffee image acr in ithc

- k8s/release/admin/secrets-csi-driver/secrets-csi-driver.yaml
Reverts hmcts/shared-services-flux#1111
```
I0817 13:31:59.594168       1 request.go:668] Waited for 1.046232657s due to client-side throttling, not priority and fairness, request: GET:https://10.0.0.1:443/apis/flowcontrol.apiserver.k8s.io/v1beta1?timeout=32s
F0817 13:32:00.748507       1 main.go:174] failed to run manager, error: failed to wait for secretproviderclasspodstatus caches to sync: no matches for kind "SecretProviderClassPodStatus" in version "secrets-store.csi.x-k8s.io/v1alpha1"
goroutine 31 [running]:
k8s.io/klog/v2.stacks(0xc0000c2001, 0xc00013a2c0, 0xed, 0x291)
/go/pkg/mod/k8s.io/klog/v2@v2.8.0/klog.go:1021 +0xb9
k8s.io/klog/v2.(*loggingT).output(0x2947320, 0xc000000003, 0x0, 0x0, 0xc000343ea0, 0x217a880, 0x7, 0xae, 0x0)
/go/pkg/mod/k8s.io/klog/v2@v2.8.0/klog.go:970 +0x191 …
```
> Revert "Upgrade CSI driver"

- k8s/environments/dev/common/mi/mi-azure-functions.yaml
- k8s/environments/sbox/common/mi/mi-azure-functions.yaml
- k8s/environments/test/common/mi/mi-azure-functions.yaml
Potential bug due to the cleanup of :pr- tagged images resulting in:
---
ts=2021-09-22T14:13:11.534632584Z caller=images.go:106 component=sync-loop workload=mi:helmrelease/mi-azure-functions-deployment container=chart-image repo=sdshmctspublic.azurecr.io/mi/azure-functions pattern=glob:pr-* current=sdshmctspublic.azurecr.io/mi/azure-functions:pr-15-e0d0018 warning="image with zero created timestamp" current="sdshmctspublic.azurecr.io/mi/azure-functions:pr-15-e0d0018 (0001-01-01 00:00:00 +0000 UTC)" latest="sdshmctspublic.azurecr.io/mi/azure-functions:pr-17-846fe59 (2021-09-22 11:05:06.304627483 +0000 UTC)" action="skip container"
---
This change manually updates the image tags in hopes it resolves the issue.
```
[ ] Yes …
```
> Update MI Azure Functions PR Images Manually

- k8s/common/omsagent-configmap.yaml
This scraping is incurring significant ingestion charges and consists largely of verbose DNS statistics
> Disable prometheus log analytics ingestion

- k8s/environments/ptl/common/secrets/netbox-redis.yaml
current access key is incorrect - updating to use PTL instance's
(I reverted https://github.com/hmcts/shared-services-flux/pull/1287 as I updated the wrong environment, this PR is to update correctly)
```
[ ] Yes
[x] No
```
> PTL - update netbox redis secret

- k8s/environments/test/common/mi/mi-azure-functions.yaml
The previous tag seems to have been removed as part of cleanup and now flux can't automatically update it.
This manually fixes the issue to use the latest tag.
```
[ ] Yes
[x] No
```
> Update MI Azure Functions Test Image Tag

- k8s/environments/prod/common/mi/mi-azure-functions.yaml
Flux doesn't seem to have auto released the latest prod tag for the MI Azure Functions. Raising this manual PR for now.
```
[ ] Yes
[x] No
```
> Updating mi azure functions prod tag manually

- apps/monitoring/kube-prometheus-stack/kube-prometheus-stack.yaml
Attempting to fix the error below, looks like api has slightly changed.
```bash
k get kustomizations.kustomize.toolkit.fluxcd.io monitoring        
NAME         READY   STATUS   AGE
monitoring   False   HelmRelease/monitoring/kube-prometheus-stack dry-run failed, error: failed to create typed patch object: .spec.forceUpgrade: field not declared in schema
34m
```
```
[ ] Yes
[x] No
```
> Fix helm release

- k8s/namespaces/monitoring/kube-prometheus-stack/kube-prometheus-stack.yaml
Attempting to fix the below error 🤞🏼 :
```bash
monitoring     False   HelmRelease/monitoring/kube-prometheus-stack dry-run failed, error: failed to create typed patch object: .spec.valuesFrom[0].secretKeyRef: field not declared in schema
46m
```
```
[ ] Yes
[x] No
```
> Fix kube-prometheus-stack HR

- k8s/namespaces/jenkins/patches/ptl/cluster-00/jenkins.yaml
This PR adds employment tribunals to Jenkins dashboard. It clones the previous change for tax tribunals and modified accordingly
```
[ ] Yes
[X] No
```
> Added employment tribunals to Jenkins

- apps/flux-system/dev/00/kustomize.yaml
- apps/flux-system/dev/01/kustomize.yaml
- apps/flux-system/dev/base/kustomization.yaml
Trying to fix script error in https://dev.azure.com/hmcts/PlatformOperations/_build/results?buildId=203628&view=logs&j=ea2ffe14-2e90-56d6-306f-4291b0be40fb&t=a1ee437a-aef6-50cc-929a-d1e6d9ce954a
by ensuring necessary files exist first.
> DTSPO-6258 - Enable fluxv2 on dev cluster

- apps/flux-system/dev/base/kustomization.yaml
- dev: migrate az-devops to fluxv2
- Remove git-credentials from dev
> DTSPO-6258 - remove git-credentials from dev

- apps/vh/identity/dev.yaml
- apps/vh/identity/vh-azure-identity.yaml
Amend VH Azure Identity name to vh-aad-identity to fir error:
`"No AzureIdentityBinding found for pod vh/vh-test-web-d68b89c89-pr5kz that matches selector: vh-aad-identity."`
```
[ ] Yes
[x] No
```
> Amend VH Azure Identity name

- k8s/namespaces/pip/pip-frontend/patches/demo/pip-frontend.yaml
- k8s/namespaces/pip/pip-frontend/patches/dev/pip-frontend.yaml
- k8s/namespaces/pip/pip-frontend/patches/ithc/pip-frontend.yaml
- k8s/namespaces/pip/pip-frontend/patches/prod/pip-frontend.yaml
- k8s/namespaces/pip/pip-frontend/patches/stg/pip-frontend.yaml
- k8s/namespaces/pip/pip-frontend/patches/test/pip-frontend.yaml
https://tools.hmcts.net/jira/browse/PUB-1021
Added the AUTH_RETURN_URL to each pip-frontend environment. 
```
[ ] Yes
[x] No
```
> PUB-1021 Add auth return url to each pip-frontend env

- k8s/environments/demo/cluster-00-overlay/kustomization.yaml
- k8s/environments/demo/cluster-01-overlay/kustomization.yaml
- k8s/namespaces/admin/oauth2-proxy/identity-binding.yaml
- k8s/namespaces/admin/oauth2-proxy/kustomization.yaml
- k8s/namespaces/admin/oauth2-proxy/oauth2-proxy-values.enc.yaml
- k8s/namespaces/admin/oauth2-proxy/oauth2-proxy.yaml
- k8s/namespaces/admin/oauth2-proxy/patches/demo/cluster-00/oauth2-proxy.yaml
- k8s/namespaces/admin/oauth2-proxy/patches/demo/cluster-01/oauth2-proxy.yaml
- k8s/namespaces/admin/oauth2-proxy/patches/demo/kustomization.yaml
- k8s/namespaces/admin/oauth2-proxy/patches/demo/secret-provider.yaml
- k8s/namespaces/admin/oauth2-proxy/secret-provider.yaml
- k8s/namespaces/toffee/toffee-frontend/demo/demo.yaml
A client secret and id is required. This could be added via a keyvault but started off adding via secret values file as not sure which key vault should be used.
Also have a secret provider class pointing to acmedtssdsdemo to get the wildcard cert for demo.platform.hmcts.net
Identity added to access the keyvault
Have adapted the cnp code to match more recent version of the helm values
```
[ ] Yes
[x] No
```
> DTSPO-6480 - Add oauth2-proxy in sds demo

- k8s/namespaces/admin/oauth2-proxy/oauth2-proxy.yaml
- k8s/namespaces/admin/oauth2-proxy/secret-provider.yaml
tools.hmcts.net/browse/DTSPO-6480
Patch to fix volumes and volume mounts
Update secret provider, volume and mounts to use same name
Was using incorrect extraVolumes syntax previously
[ ] Yes
[x] No
> DTSPO-6480 - Oauth2-proxy: patch 1

- k8s/environments/demo/cluster-00-overlay/kustomization.yaml
- k8s/environments/demo/cluster-01-overlay/kustomization.yaml
- k8s/namespaces/admin/external-dns/external-dns.yaml
- k8s/namespaces/admin/external-dns/identity-binding.yaml
- k8s/namespaces/admin/external-dns/kustomization.yaml
- k8s/namespaces/admin/external-dns/patches/demo/cluster-00/external-dns.yaml
- k8s/namespaces/admin/external-dns/patches/demo/cluster-01/external-dns.yaml
This external-dns instance will work for azure public dns zones, but due to the annotation filter, will only work for traefik-no-proxy. I think we should add another label or annotation to ingresses e.g.
`external.dns/provider: azure-public-dns` & `external.dns/provider: azure-private-dns`
- Added configuration to deploy external dns to demo 
- Uses the external dns helm chart
- Uses the AKS Managed Identity - may want to create a new one
Leaving debug logging on for now, until everything is proven to work 
```
[ ] Yes
[x] No
```
> DTSPO-6498 - deploy external dns to demo

- k8s/environments/demo/common-overlay/kustomization.yaml
Removing toffee from flux to more easily test oauth2-proxy
[ ] Yes
[x] No
> DTSPO-6480 - Oauth2-proxy: remove toffee flux

- k8s/namespaces/toffee/toffee-frontend/demo/demo.yaml
Set enableOauth flag for toffee in demo to true to add required ingress annotations﻿
> DTSPO-6480 - set enableOauth flag for toffee

- k8s/namespaces/admin/traefik2/patches/demo/cluster-00/traefik-auth-proxy.yaml
- k8s/namespaces/admin/traefik2/patches/demo/cluster-00/traefik-no-proxy.yaml
- k8s/namespaces/admin/traefik2/patches/demo/cluster-01/traefik-no-proxy.yaml
- k8s/namespaces/admin/traefik2/traefik-auth-proxy.yaml
- k8s/namespaces/admin/traefik2/traefik-no-proxy.yaml
- k8s/namespaces/pip/pip-account-management/patches/demo/pip-account-management.yaml
- k8s/namespaces/pip/pip-channel-management/patches/demo/pip-channel-management.yaml
- k8s/namespaces/pip/pip-data-management/patches/demo/pip-data-management.yaml
- k8s/namespaces/pip/pip-frontend/patches/demo/pip-frontend.yaml
- k8s/namespaces/pip/pip-publication-services/patches/demo/pip-publication-services.yaml
- k8s/namespaces/pip/pip-subscription-management/patches/demo/pip-subscription-management.yaml
Set traefik-auth-proxy as default ingressClass
Update pip to continue using traefik-no-proxy
[ ] Yes
[x] No
> DTSPO-6480 - set traefik-auth-proxy to default

- k8s/namespaces/admin/oauth2-proxy/oauth2-proxy.yaml
- k8s/namespaces/admin/traefik2/oauth-errors.yaml
- k8s/namespaces/admin/traefik2/oauth-routes.yaml
Following https://community.traefik.io/t/forwardauth-does-not-pass-x-forwarded-uri/3277﻿
> DTSPO-6480 - patch 20

- k8s/namespaces/jenkins/patches/ptlsbox/cluster-00/jenkins.yaml
DTSPO-7181
Update Sbox Jenkins version to 3.9.0. Testing sbox as version update broke production jenkins.
```
[ ] Yes
[X] No
```
> DTSPO-7181 -Update sbox jenkins version to 3.9.0

- apps/mi/mi-azure-functions/dev.yaml
- apps/mi/mi-azure-functions/image-policy.yaml
- apps/mi/mi-azure-functions/sbox.yaml
- k8s/release/mi/mi-azure-functions/templates/deployment.yaml
- k8s/release/mi/mi-azure-functions/values.yaml
Setting a resource request of 512MiB memory and 200m CPU.
Setting a limit of 2048MiB and 2000m CPU, which should be sufficient for even high loads.
> Set resource limits for mi azure functions

- apps/mi/base/mi-developer-rbac.yaml
- apps/mi/mi-azure-functions/dev.yaml
- k8s/namespaces/mi/mi-developer-rbac.yaml
Previous version left in unnecessary part after the api setting so it didn't work.
This is correct and a working example can be seen from: https://github.com/hmcts/sds-flux-config/commit/4b7e4d40e6a830ffe8df647edcf0508d0b8e5182
> Update mi flux v2 perms

- k8s/namespaces/azure-devops/azure-devops-agent/azure-devops-agent.yaml
Previous image deleted from container registry and azure-devops agents failing to restart in ss-prod-01-cluster. Picked the latest image to use instead
```
[ ] Yes
[x] No
```
> bump devops agent image

- apps/hmi/automation/kustomization.yaml
Fixes error in flux-system
`accumulation err='accumulating resources from '../hmi-az-devops-agent/image-repo.yaml': open /tmp/flux-system3623365517/apps/hmi/hmi-az-devops-agent/image-repo.yaml: no such file or directory
`
- Might look at some CI for this going forward, no CI check for apps/namespace/automation 
```
[ ] Yes
[X] No
```
> fix flux errors in ss-ptl

- apps/azure-devops/azure-devops-agent/ithc.yaml
Fix typo in ithc keyvault name for azure-devops
```
[ ] Yes
[x] No
```
> DTSPO-6489 - fluxv2 ithc migration - azure-devops - patch 2

- apps/admin/aad-pod-identity/ithc/azure-identity-patch.yaml
- apps/admin/ithc/00/kustomization.yaml
- apps/admin/ithc/01/kustomization.yaml
- apps/admin/ithc/base/kustomization.yaml
- apps/admin/kured/ithc/00.yaml
- apps/admin/kured/ithc/01.yaml
- apps/admin/kured/ithc/kured-values.enc.yaml
- apps/admin/secrets-csi-driver/ithc/01.yaml
- apps/admin/traefik2/ithc/00-traefik2.yaml
- apps/admin/traefik2/ithc/01-traefik2.yaml
- apps/admin/traefik2/ithc/kustomization.yaml
- apps/admin/traefik2/ithc/secret-provider.yaml
- k8s/environments/ithc/cluster-00-overlay/kustomization.yaml
- k8s/environments/ithc/cluster-01-overlay/kustomization.yaml
Migrating some admin apps to flux v2
Will move kube-system and neuvector separately
```
[ ] Yes
[x] No
```
> DTSPO-6489 - fluxv2 ithc migration - admin

- apps/admin/traefik-auth-proxy/oauth-routes.yaml
Fixing error: `"error":"IngressRoute/admin/oauth2-proxy dry-run failed, error: failed to create typed patch object: .spec.forwardedHeaders`
```
[ ] Yes
[x] No
```
> DTSPO-6491 - fix oauth config

- apps/admin/oauth2-proxy/oauth2-proxy.yaml
Waiting for ingressClassName filter to be available in external dns: https://github.com/kubernetes-sigs/external-dns/pull/2054
```
[ ] Yes
[x] No
```
> DTSPO-6491 - add annotation for automatic dns

- apps/admin/aad-pod-identity/test/azure-identity-patch.yaml
- apps/admin/keda/test/identity.yaml
- apps/admin/test/00/kustomization.yaml
- apps/admin/test/01/kustomization.yaml
- apps/admin/test/base/kustomization.yaml
- clusters/test/base/kustomization.yaml
https://tools.hmcts.net/jira/browse/DTSPO-8053
Enable keda on test cluster
Requires admin namespace in test to be added to flux v2 config
Requires aad-pod-identity for test to be added
```
[ ] Yes
[x] No
```
> DTSPO-8053 - Enable keda on test

- clusters/test/base/kustomization.yaml
https://tools.hmcts.net/jira/browse/DTSPO-8053
Fix kustomization for test so admin flux v2 config is enabled
```
[ ] Yes
[x] No
```
> DTSPO-8053 - Fix admin ns test cluster kustomization

- apps/neuvector/neuvector/neuvector.yaml
Bump neuvector chart version to 1.2.7 to mitigate error with post-install script
```
[ ] Yes
[x] No
```
> DTSPO-6488 - Bump neuvector chart version

- apps/toffee/dev/base/kustomization.yaml
Remove toffee apps from dev but mi's and namespace
Tested locally and looks good
```
[ ] Yes
[x] No
```
> Remove toffee apps from dev but mi's and namespace

- apps/toffee/base/kustomization.yaml
- apps/toffee/demo/base/kustomization.yaml
- apps/toffee/dev/base/kustomization.yaml
- apps/toffee/frontend/demo.yaml
- apps/toffee/frontend/ithc.yaml
- apps/toffee/frontend/prod.yaml
- apps/toffee/frontend/sbox.yaml
- apps/toffee/frontend/toffee-frontend.yaml
- apps/toffee/identity/prod.yaml
- apps/toffee/ithc/base/kustomization.yaml
- apps/toffee/prod/base/kustomization.yaml
- apps/toffee/recipe-backend/demo.yaml
- apps/toffee/recipe-backend/ithc.yaml
- apps/toffee/recipe-backend/prod.yaml
- apps/toffee/recipe-backend/sbox.yaml
- apps/toffee/recipe-backend/toffee-recipe-backend.yaml
- apps/toffee/recipe-receiver/prod.yaml
- apps/toffee/sbox/base/kustomization.yaml
- apps/toffee/stg/base/kustomization.yaml
- clusters/prod/base/kustomization.yaml
DTSPO-6494
- Migrate Toffee to Flux V2
- Deploy Toffee to prod
- Remove old annotations
- Only deploy apple mi to sbox
```
[ ] Yes
[X] No
```
> DTSPO-6494 - Migrate Toffee to Flux V2

- apps/toffee/frontend/stg.yaml
- apps/toffee/recipe-backend/stg.yaml
- apps/toffee/stg/base/kustomization.yaml
Adding staging back, not sure if it was removed on purpose, but toffee is still being deployed just without an ingress and whatever else in the hr overlay for staging.
```
[ ] Yes
[x] No
```
> Adding staging back

- apps/toffee/frontend/toffee-frontend.yaml
- apps/toffee/recipe-backend/toffee-recipe-backend.yaml
Updating startup thresholds as toffee takes 2 minutes to report as "Ready", even though the apps look like they come up pretty quickly. These settings will allow toffee to take 3 minutes to become ready, but will check every 10s. 
```
[ ] Yes
[x] No
```
> Changing toffee startup thresholds to improve readiness time

- k8s/namespaces/jenkins/patches/ptl/cluster-00/jenkins.yaml
- k8s/namespaces/jenkins/patches/ptlsbox/cluster-00/jenkins.yaml
https://tools.hmcts.net/jira/browse/DTSPO-9193
https://github.com/hmcts/jenkins-packer/commit/82cc8d660144bedeb9c6c3d59dfe0e80e7782f95
Updates the jenkins-packer version used on jenkins builders to v 1.2.0
```
[ ] Yes
[ ] No
```
> Bump jenkins-packer version to 1.2.0

- apps/mailrelay2/mailrelay2/dev/dev.yaml
https://tools.hmcts.net/jira/browse/DTSPO-8561
The change may not have been necessary now that we are able to locate where the smtp settings are.
Reverting to see if relay is still functions as expected.
```
[ ] Yes
[ ] No
```
> DTSPO-8561: Revert to previous value

- apps/jenkins/jenkins/helmrepo.yaml
- apps/jenkins/jenkins/jenkins.yaml
- apps/jenkins/jenkins/ptlsbox/jenkins.yaml
Disabling env var substitution on jenkins variables by using $${var} syntax, this is needed as flux was trying to substitute them and failing . Also needed to update the chart info as I missed doing that in the previous PR. Flux seems happy with the config now after the changes.
```
[ ] Yes
[x] No
```
> DTSPO-6493 - fix jenkins config

- clusters/ptl/base/kustomization.yaml
Adding admin & netbox namespaces to flux v2 sync, but not removing from flux v1 yet. Will make sure the hr is looking good first.
```
[ ] Yes
[x] No
```
> DTSPO-6492 - add admin & netbox namespaces to flux v2 sync

- apps/monitoring/kube-prometheus-stack/ptl/prometheus-values.enc.yaml
Not sure if something has changed upstream but the helm release is complaining it can't find the secret data as its looking for `values.yaml` key.
Error: `missing key 'values.yaml' in Secret 'monitoring/prometheus-values'`
```
[ ] Yes
[x] No
```
> DTSPO-6492 - rename secret data to values.yaml

- apps/mailrelay2/mailrelay2/dev/01.yaml
- apps/mailrelay2/mailrelay2/dev/dev.yaml
`Troubleshot:` Testing mail delivery to other domain other then `.hmcts.net`.
Noticed that the relay would drop external domain email but deliver the email if its a `.hmcts.net`
Updating the pod image for one of the clusters to test out changes to the exim config
`NOTE:` This would be reverted soon as the exercise is complete. mailrelay pods in the cluster would be in and out of a healthy state for a bit as i tweak the config
```
[ ] Yes
[ ] No
```
> Troubleshot: updating image on pod in dev 01

- apps/admin/sbox/01/kustomization.yaml
- clusters/sbox/01/kustomization.yaml
Removing csi driver and crds from sbox 01 to be able to test the cluster add-on properly
```
[ ] Yes
[x] No
```
> DTSPO-9539 - remove csi driver and crds from sbox 01 temporarily

- apps/admin/traefik-auth-proxy/traefik-auth-proxy.yaml
Ingress endpoint ip for traefik-auth-proxy looks to have been updated - possibly during move to panorama
Updating ip to match current ip on firewall
```
[ ] Yes
[x] No
```
> Update traefik-auth-proxy endpoint ip

- apps/admin/traefik2/sbox/01-traefik2.yaml
Testing in sbox 01, but we should probably do this all the way up to Prod. Currently the ingressClassName is being set in the ingress config in the kube-prometheus-stack spec, so we either remove that or do this. I think it's probably better to be explicit with setting the name but open to suggestions.
```
[ ] Yes
[x] No
```
> Fix sbox monitoring ingress by adding ingressclass

- apps/admin/traefik2/sbox/01-traefik2.yaml
- apps/admin/traefik2/traefik2.yaml
Adding the ingressClass to all environments. I have suspended the admin kustomization on the prod clusters and will resume on cluster at a time.
```
[ ] Yes
[x] No
```
> Add ingressclass to all environments

- apps/monitoring/kube-prometheus-stack/kube-prometheus-stack.yaml
- apps/monitoring/kube-prometheus-stack/sbox/01.yaml
Now the traefik ingressClass has been deployed to all envs we can set the ingressClassName in the ingresses spec and stop using the deprecated way of using annotations.
- Set ingressClassName in ingress spec 
- Clean up sbox config
```
[ ] Yes
[x] No
```
> Set ingressClass in spec rather than an annotation

- apps/admin/sbox/01/kustomization.yaml
- apps/admin/sbox/base/kustomization.yaml
- clusters/sbox/01/kustomization.yaml
- clusters/sbox/base/kustomization.yaml
Removing csi driver from both sbox clusters as we're using the aks add-on now
```
[ ] Yes
[x] No
```
> DTSPO-9539 - remove csi driver from both sbox clusters

- apps/toffee/frontend/prod.yaml
- apps/toffee/frontend/stg.yaml
https://tools.hmcts.net/jira/browse/DTSPO-9517
Testing toffee with new image to ensure stg and prod clusters can pull from private acr
Will be reverted after confirmation that authentication to private acr on prod is working
[ ] Yes
[x] No
> DTSPO-9517 - Test using private acr for toffee

- apps/toffee/frontend/prod.yaml
- apps/toffee/frontend/stg.yaml
Reverts hmcts/sds-flux-config#2130
Pulling from private acr is working on both stg and prod clusters so this can be reverted
> Revert "DTSPO-9517 - Test using private acr for toffee"

- apps/mailrelay2/mailrelay2/dev/dev.yaml
- apps/mailrelay2/mailrelay2/mailrelay2.yaml
Now looking to the exchange server configuration. Turns out it'd not been configed to work with the `dev-in` certificate for mailrelay2 traffic. taking investigation down one
```
[ ] Yes
[ ] No
```
> DTSPO-8561: Update exim image tag revert

- apps/admin/aad-pod-identity/aks-kubelet-binding.yaml
- apps/admin/aad-pod-identity/aks-kubelet-identity.yaml
- apps/flux-system/demo/base/kustomization.yaml
- apps/flux-system/dev/base/kustomization.yaml
- apps/flux-system/ithc/base/kustomization.yaml
- apps/flux-system/prod/base/kustomization.yaml
- apps/flux-system/ptlsbox/base/kustomization.yaml
- apps/flux-system/sbox/base/kustomization.yaml
- apps/flux-system/stg/base/kustomization.yaml
- apps/flux-system/test/base/kustomization.yaml
- remove image automation components from all envs apart from ptl
- move image reflector identity to flux-system 
```
[ ] Yes
[x] No
```
> DTSPO-9517 - remove image automation components

- CODEOWNERS
- apps/dts-legacy/lgy-iac-web/lgy-iac-web.yaml
Change the default liveness path from /health/liveness to /IACFees/health/liveness.do (the struts application needs .do suffix on url names)
```
[ ] Yes
[x] No
```
> Change the default liveness path for lgy-iac-web

- apps/admin/demo/base/kustomization.yaml
- apps/admin/reply-urls-operator/demo/kustomization.yaml
- apps/admin/reply-urls-operator/kustomization.yaml
- apps/admin/reply-urls-operator/sbox/kustomization.yaml
- apps/admin/sbox/00/kustomization.yaml
- Using tag instead of master branch
- Moved kustomizations to environment folders so different versions of the reply urls operator can be used in sbox/demo
```
[ ] Yes
[x] No
```
> DTSPO-6556 - set version for reply urls operation's kustomization base

- k8s/release/mi/mi-azure-functions/values.yaml
mi-azure-functions has been updated to use a non-root user. This means it can no longer start services on ports lower than 1024. The new internal port is 7072.
> Change MI Azure Functions internal port to 7072

- apps/mi/mi-adf-shir/dev.yaml
- apps/mi/mi-adf-shir/ithc.yaml
- apps/mi/mi-adf-shir/mi-adf-shir.yaml
- apps/mi/mi-adf-shir/prod.yaml
- apps/mi/mi-adf-shir/sbox.yaml
- apps/mi/mi-adf-shir/stg.yaml
- apps/mi/mi-adf-shir/test.yaml
Default service account from Windows node can access the vault using managed identity now.
We no longer need sops but can pull values from vault now.
> Setup managed identity and secret mount path for SHIR

- apps/mi/mi-adf-shir/test.yaml
- k8s/release/mi/mi-adf-shir/Chart.yaml
- k8s/release/mi/mi-adf-shir/templates/deployment.yaml
- k8s/release/mi/mi-adf-shir/values.yaml
If NodeName in the SHIR chart is not defined, default to using the pod's name as the node name for better identification.
Also updates test env SHIR to have a higher memory limit since the usage on that environment is high compared to all the others.
> Set SHIR pod name as Node Name in ADF

- apps/admin/external-dns/demo/01-external-dns-private.yaml
- apps/admin/external-dns/demo/01-external-dns.yaml
ERROR 
```
41m         Warning   InvalidChartReference        helmchart/admin-external-dns           invalid chart reference: failed to get chart version for remote reference: no 'external-dns' chart with version matching '6.1.4' found
41m         Warning   InvalidChartReference        helmchart/admin-external-dns-private   invalid chart reference: failed to get chart version for remote reference: no 'external-dns' chart with version matching '6.1.4' found
```
This moves to the latest version, testing inactive cluster to validate before adding to base
```
[ ] Yes
[ ] No
```
> Upgrade external-dns in inactive demo

- apps/neuvector/stg/base/nv-storage-secret.yaml
https://tools.hmcts.net/jira/browse/DTSPO-10284
STG Neuvector secret was incorrectly encrypted with ithc storage account key, this is now corrected
```
[ ] Yes
[x] No
```
> Correct neuvector sa name/key from ithc to stg for stg env

- apps/mi/mi-adf-shir/dev.yaml
Set dev SHIR memory limit to 4GB (up from default 2GB)
Added replicaCount property set to use 4 node instead of the default 2 as there is only 1 dev cluster.
> Increase memory limits for dev ADF SHIR

- apps/toffee/frontend/demo.yaml
Reverts hmcts/sds-flux-config#2560 -- this does cause a drop in health for backend
> Revert "Test FD connectivity with TLS flag"

- apps/mi/automation/kustomization.yaml
Potential issue, we see other namespaces use repo the policy in that order, whilst we are not seeing our imagepolicies apply. So testing a change in the load order.
> Set order of policy to load repo setup first for MI

- .gitignore
- apps/mi/mi-sftp-server/mi-sftp-server-secret-provider.yaml
- apps/mi/mi-sftp-server/mi-sftp-server.yaml
https://tools.hmcts.net/jira/browse/RMI-2379
Revived the ticket because there was an issue with the sftp-server. Update the api version for the sftp server's secret provider
```
[ ] Yes
[X] No
```
> Rmi 2379 update api version

- apps/mi/mi-sftp-server/dev-secret-provider-patch.yaml
- apps/mi/mi-sftp-server/ithc-secret-provider-patch.yaml
- apps/mi/mi-sftp-server/sbox-secret-provider-patch.yaml
- apps/mi/mi-sftp-server/stg-secret-provider-patch.yaml
- apps/mi/mi-sftp-server/test-secret-provider-patch.yaml
https://tools.hmcts.net/jira/browse/RMI-2379
The config value had incorrect spelling for the KeyVaultName. This has been fixed
```
[ ] Yes
[X] No
```
> Rename KeyVaultName value to keyvaultName

- apps/toffee/recipe-backend/demo.yaml
Reverts hmcts/sds-flux-config#2570 -- This flag gives 502 error for backend apps from client machine
> Revert "Test flag behaviour for backend application"

- k8s/release/mi/mi-house-keeping-service/Chart.yaml
Update mi job to use chart-job 0.7.11
Enables compatibility with kubernetes 1.25 on aks
```
[ ] Yes
[x] No
```
> DTSPO-12090 - Update mi job chart

- k8s/release/mi/common/job/Chart.yaml
- k8s/release/mi/common/job/templates/CronJob.yaml
- k8s/release/mi/mi-house-keeping-service/Chart.yaml
Update mi job
Enables compatibility with kubernetes 1.25 on aks
```
[ ] Yes
[x] No
```
> DTSPO-12090 - Update mi job chart - 2

- apps/monitoring/dev/01/kustomization.yaml
- apps/monitoring/kube-prometheus-stack/dev/01.yaml
- apps/monitoring/loki-stack/dev/01.yaml
Adds ingress for loki to setup external datasource for loki logs on grafana"
```
[ ] Yes
[X] No
```
> Dtspo 12412 loki ingress

- apps/mailrelay/mailrelay/prod/00.yaml
Current error found during redeploy of cluster - 
`n desc = failed to mount secrets store objects for pod mailrelay/mailrelay-exim-0, err: rpc error: code = Unknown desc = failed to mount objects, error: failed to create auth config, error: failed to get credentials, nodePublishSecretRef secret is not set`
```
[ ] Yes
[X] No
```
> testing of promethus is issue

- apps/darts-modernisation/demo/base/kustomization.yaml
darts-api is already referenced in base, removing it from the demo kustomization
```
[ ] Yes
[x] No
```
> Fix broken kustomization

- apps/darts-modernisation/darts-portal/demo.yaml
- apps/darts-modernisation/darts-portal/stg.yaml
Overriding staging `ingressHost` to match the public DNS record, otherwise the chart in the darts-portal repo uses `darts-portal.stg.platform.hmcts.net` which doesn't match.
```
[ ] Yes
[ ] No
```
> Minor changes for darts-portal

- apps/neuvector/neuvector/ithc/00.yaml
- apps/neuvector/neuvector/ithc/01.yaml
- apps/neuvector/neuvector/neuvector.yaml
- apps/neuvector/neuvector/stg/00.yaml
- apps/neuvector/neuvector/stg/01.yaml
- apps/neuvector/neuvector/test/00.yaml
- apps/neuvector/neuvector/test/01.yaml
https://tools.hmcts.net/jira/browse/DTSPO-12488
remove the image tags for neuvector to match CFT flux config. Image version will now be managed by the release version of helm chart (hmcts/chart-neuvector) that is being used.
```
[ ] Yes
[x] No
```
> Remove neuvector image tags to match CFT flux config

- apps/admin/traefik2/sbox/00-traefik2.yaml
Adding Priority to Traefik deployment so it's started first.
Testing on sbox 00 first. 
```
[ ] Yes
[x] No
```
> DTSPO-13194 - set priority class name for traefik in sbox 00

- apps/jenkins/jenkins/ptl/jenkins.yaml
Setting the Preview/Dev subscription ID as its missing and is using DCD-CFTAPPS-DEV
PRE reported this after trying to use the Postgres flexible server TF module
```
[ ] Yes
[x] No
```
> Set dev subscription ID

- apps/admin/kured/kured.yaml
- apps/base/kustomization.yaml
- apps/base/service-account.yaml
- apps/jenkins/jenkins/jenkins.yaml
Chart changes include a base service account reference, but this was forgotten for SDS
```
[ ] Yes
[ ] No
```
> Add base service accounts SDS

- apps/dynatrace/dynakube.yaml
Reverting to ignoring MI namespace so their pods can start whilst we try and reach a solution to do this on an application basis with Dynatrace
```
[ ] Yes
[ ] No
```
> Revert to working approach

- apps/dynatrace/dynakube.yaml
Pods have now been annotated with 
`oneagent.dynatrace.com/inject: false`
So dynatrace should ignore them
```
[ ] Yes
[ ] No
```
> Remove namespace exclusion

- apps/met/themis-fe/themis-fe.yaml
Lowering replicas to 1 to make debugging easier across nodes. Increasing startup healthprobe delays
> increasing startup delay

- clusters/test/base/kustomization.yaml
* darts-modernisation namespace has containers which do not deploy properly
* stopping AKS version upgrade
* Have spoken to team, they're unsure if they need to deploy to test or not
```
[ ] Yes
[x] No
```
> Remove darts-modernisation from test environment

- clusters/prod/base/kustomization.yaml
Doing checks before AKS-SDS prod upgrades and all applications in this namespace are unhealthy which could cause issues. Spoke with @scott-robertson1 about this and these applications are not in use yet in prod and the issue can not be reasonably solved in a short period of time, so the plan is to remove these from sds-prod temporarily.
```
[ ] Yes
[ ] No
```
> Remove darts-modernisation from sds-prod

- apps/monitoring/version-reporter/version-reporter.yaml
The `paloalto` report uses a `desired version` variable as part of its ETL process to determine how far off we are from where our desired version is and the current version. It creates a verdict which is part of the report.
This variable would be fairly stable but would need updating from time to time depending on us. Adding it as an env so we don't have to touch the actual code when this needs to be updated in the future.
```
[ ] Yes
[ ] No
```
> DTSPO-7962: Setting the "desired version" for report

- apps/monitoring/version-reporter/rbac.yaml
https://tools.hmcts.net/jira/browse/DTSPO-14148
Getting the following errors in the report logs
`Error from server (Forbidden): helmrepositories.source.toolkit.fluxcd.io is forbidden: User "system:serviceaccount:monitoring:version-reporter-service-sa" cannot list resource "helmrepositories" in API group "source.toolkit.fluxcd.io" at the cluster scope`
and 
`23/07/26 13:20:01 There was an error while executing the Command: list: failed to list: secrets is forbidden: User "system:serviceaccount:monitoring:version-reporter-service-sa" cannot list resource "secrets" in API group "" at the cluster scope`
This is an attempt to rectify
```
[ ] Yes
[ ] No
```
> DTSPO-14148: List rbac on helmrepositories needed

- apps/jenkins/jenkins/ptl/jenkins-azure-vm-agent.yaml
https://tools.hmcts.net/jira/browse/DTSPO-14661
* Add daily label to VM Template allowing daily pipeline to run on standard SDS agents from the singular VM Template
* This is needed as the the jenkins config is shared across CFT/SDS and CFT now has segregation of daily/ad-hoc builds through separate VM Templates selected using the label
* As the standard SDS VM Template is set to NORMAL & not EXCLUSIVE the label adding the label allows both daily/ad-hoc builds to run on the standard SDS agents from the singular VM Template
```
[ ] Yes
[x] No
```
> Jenkins: Add daily label to VM Template for PTL

- apps/monitoring/version-reporter/kustomization.yaml
- apps/monitoring/version-reporter/renovate/image-policy.yaml
- apps/monitoring/version-reporter/renovate/image-repo.yaml
- apps/monitoring/version-reporter/renovate/renovate.yaml
https://tools.hmcts.net/jira/browse/DTSPO-14763
The renovate report in the version reporter service, searches for all opened renovate and update cli PRs and tells of how long it been opened for and a `verdict` is arrived at. This gives us s central place to view such data and we can also see how well we are doing based on volume of "old" opened renovate PRs.
In this PR I am setting the configuration to create to necessary pods and execution of the cron job. The schedule is initially set to run every 10min, this is just for testing and setting up, once confirm alls working as expected cron schedule would be updated to run 4 times in a day and weekdays only.
```
[ ] Yes
[ ] No
```
> DTSPO-14763: Configuration renovate report

- apps/jenkins/jenkins/ptl/jenkins-azure-vm-agent.yaml
- apps/jenkins/jenkins/ptlsbox/jenkins-azure-vm-agent.yaml
We pay per second used and I'm seeing a lot of idle agents sitting there after builds in the morning.
We can tune this as required to get a good balance but these should only take ~1 min to spawn a new one
> Tune idle timeout of agent

- apps/neuvector/fluentbit-log/fluentbit-log.yaml
- apps/neuvector/neuvector/neuvector.yaml
https://tools.hmcts.net/jira/browse/DTSPO-14808
Move to point to acr cache
Aware that this is sds-flux talking to hmctspublic as opposed to sdshmctspublic, but our cache rules have only been added via automation to hmctspublic repo. Do we want to also add them to sdshmctspublic, or is it fine to point across this way?
```
[ ] Yes
[ ] No
```
> Update neuvector & fluentbit ACR repo locations

- apps/neuvector/neuvector/neuvector.yaml
https://github.com/hmcts/sds-flux-config/pull/3368
Was giving image source as `docker.io/hmctspublic...`  --- registry is defined at top level instead https://github.com/neuvector/neuvector-helm/blob/master/charts/core/values.yaml#L7
```
[ ] Yes
[ ] No
```
> Fix wrong source by adding registry

- apps/neuvector/neuvector/neuvector.yaml
Reverting to update in https://github.com/hmcts/chart-neuvector/blob/master/neuvector-azure-keyvault/values.yaml
Interestingly, this still didn't work, still pulling from `docker.io` even though registry value is set in the chart
```
[ ] Yes
[ ] No
```
> Revert changes to image, look in our chart instead

- apps/neuvector/neuvector/neuvector.yaml
This change will allow azureserviceoperator-system,cert-manager to deploy the deployments.
Similar change done here on CNP - https://github.com/hmcts/cnp-flux-config/pull/24336/files 
```
[ ] Yes
[ X ] No
```
> allow aso namespaces on neuvector

- apps/flux-system/prod/00/kustomize.yaml
- apps/flux-system/prod/01/kustomize.yaml
- apps/flux-system/stg/00/kustomize.yaml
- apps/flux-system/stg/01/kustomize.yaml
- apps/toffee/frontend/prod.yaml
- apps/toffee/frontend/stg.yaml
- apps/toffee/prod/base/kustomization.yaml
- apps/toffee/prod/base/kustomize.yaml
- apps/toffee/prod/base/workload-identity.yaml
- apps/toffee/recipe-backend/prod.yaml
- apps/toffee/recipe-backend/stg.yaml
- apps/toffee/stg/base/kustomization.yaml
- apps/toffee/stg/base/kustomize.yaml
- apps/toffee/stg/base/workload-identity.yaml
- clusters/prod/base/kustomization.yaml
- clusters/stg/base/kustomization.yaml
moved toffee to use workload identity for prod and staging environments..
```
[ ] Yes
[X ] No
```
> added workload identity for prod and stg envs

- apps/flux-system/ptl/00/kustomize.yaml
- apps/flux-system/ptlsbox/00/kustomize.yaml
Toffee app is not there for ptl and ptlsbox envs so added issuer url for it to be ready in order if other apps on those envs need to move to use workload identity
```
[ ] Yes
[X ] No
```
> added resources for ptl and ptlsbox

- apps/netbox/netbox/ptl/netbox.yaml
- apps/netbox/ptl/netbox-postgresql.enc.yaml
Reverts hmcts/sds-flux-config#3454
Performed manual migration and data looks to be in the flexible server db now
> Revert "DTSPO-14224 - Revert to old postgres"

- apps/jenkins/jenkins-webhook-relay/ptl/jenkins-webhook-relay.yaml
https://tools.hmcts.net/jira/browse/DTSPO-13992
Update connection url to main jenkins url instead of kubernetes service
Successfully triggered builds on master/main seem to be using this url instead of the kubernetes service so testing if this will fix the issue across the board
```
[ ] Yes
[x] No
```
> DTSPO-13992 - Update ptl jenkins webhook relay connection url

- apps/admin/traefik2/traefik2.yaml
https://tools.hmcts.net/jira/browse/DTSPO-14808
Point to our ACR cache
Image tag defaults to appversion from helm chart https://github.com/traefik/traefik-helm-chart/commit/6df869b8e8bcd6757e7934b554b97d925350c9fa#diff-cb0545645bb355dbe0ab58bb31707a6527115c6337d2abf3e83f15dda8f21f35R780
```
[ ] Yes
[ ] No
```
> Point to azure acr cache for traefik

- clusters/ithc/base/kustomization.yaml
https://tools.hmcts.net/jira/browse/DTSPO-15360
Removing my time app to upgrade ithc cluster, my-frontend app broken and is no longer required.
> removing my time app to upgrade ithc cluster

- apps/admin/external-dns/dev/00-external-dns.yaml
- apps/admin/external-dns/dev/01-external-dns.yaml
Reverts hmcts/sds-flux-config#3646 - didn't fix the error so reverting to bring pods back up
> Revert "Remove potential client id overrid"

- apps/admin/serviceaccount/dev.yaml
The federated identity credentials on the cluster are using stg-mi, but the one i added in code was the dev-mi - leading to an error that no federated credentials were found
> Update to use stg mi

- apps/admin/sbox/base/kustomize.yaml
- apps/admin/traefik2/demo/00-traefik2.yaml
- apps/admin/traefik2/demo/01-traefik2.yaml
- apps/admin/traefik2/dev/00-traefik2.yaml
- apps/admin/traefik2/dev/01-traefik2.yaml
- apps/admin/traefik2/ithc/00-traefik2.yaml
- apps/admin/traefik2/ithc/01-traefik2.yaml
- apps/admin/traefik2/prod/00-traefik2.yaml
- apps/admin/traefik2/prod/01-traefik2.yaml
- apps/admin/traefik2/ptl/00-traefik.yaml
- apps/admin/traefik2/ptlsbox/00-traefik.yaml
- apps/admin/traefik2/sbox/00-traefik2.yaml
- apps/admin/traefik2/sbox/01-traefik2.yaml
- apps/admin/traefik2/sbox/secret-provider.yaml
- apps/admin/traefik2/stg/00-traefik2.yaml
- apps/admin/traefik2/stg/01-traefik2.yaml
- apps/admin/traefik2/test/00-traefik2.yaml
- apps/admin/traefik2/test/01-traefik2.yaml
- apps/admin/traefik2/traefik2.yaml
- clusters/sbox/base/kustomization.yaml
Enables me to disable this per env for migrating to workload identity
Also adds sbox kustomize needed for that env in this PR
Similar done in CFT
https://github.com/hmcts/cnp-flux-config/pull/25193/files
> DTSPO-12677 Move podidbinding label out of base traefik

- apps/flux-system/base/chart-job-test-gitrepo.yaml
- apps/flux-system/base/kustomization.yaml
[DTSPO-15146](https://tools.hmcts.net/jira/browse/DTSPO-15146)
adding another git repo for chart-job to run test on helm releases without having to constantly merge into master chart-job repo.
> DTSPO-15146-Create chart-job-test-gitrepo.yaml

- apps/admin/traefik2/sbox/00-traefik2.yaml
- apps/admin/traefik2/sbox/01-traefik2.yaml
- apps/admin/traefik2/sbox/secret-provider.yaml
[DTSPO-12677](https://tools.hmcts.net/jira/browse/DTSPO-12677)
Role assignment for acme already added as pre-req
This change:
- Updates traefik in sbox to use workload identity
> Migrate sbox traefik to workload identity

- apps/admin/external-dns/identity-binding.yaml
- apps/admin/external-dns/kustomization.yaml
External-dns has been migrated to workload identity so no longer uses this
> Remove external-dns binding after migration completed

- apps/admin/dev/base/kustomize.yaml
Originally set this as external-dns was using it -- external-dns role assignments etc also exist for stg-mi which I think is the correct one to be using. Updating this switches dev to use the stg-mi.
> Update to use STG-MI to avoid traefik issues

- apps/admin/base/workload-identity/kustomization.yaml
- apps/admin/base/workload-identity/workload-identity-federated-credential.yaml
- apps/admin/base/workload-identity/workload-identity-rg.yaml
- apps/admin/base/workload-identity/workload-identity-ua-identity.yaml
- apps/admin/dev/base/kustomization.yaml
Usually dev uses stg infrastucture, MIs etc, but for traefik it is reading from acmedtsdev key vault -- without this change we would need role assignments to give the admin-stg-mi access to the above vault.
This change:
- Overrides base workload identity resources in admin dev only, by changing the environment used when creating resources with ASO in dev from `stg` to `dev` -- so that the federated identity credentials are made on the admin-dev-mi for use by traefik instead
- Mainly `WI_ENVIRONMENT` has been changed to `ENVIRONMENT` in workload identity resources
Will not affect any apps besides those using workload identity in admin namespace and on dev clusters. I have already added role assignments for external dns with the dev-mi as well
> Add a patch for dev workload identity in admin namespace

- apps/admin/external-dns/external-dns.yaml
https://tools.hmcts.net/jira/browse/DTSPO-14559
Adding annotationFilter
I was looking at the official helm repo from kubernetes-sigs which doesn't have this value
We're using bitnami which has it templated
> DTSPO-14559 - Add annotationFilter in external-dns

- apps/azure-devops/azure-devops-agent-keda/azure-devops-agent.yaml
- apps/azure-devops/azure-devops-agent-keda/dev.yaml
- apps/azure-devops/azure-devops-agent-keda/ptlsbox.yaml
- apps/azure-devops/azure-devops-agent-keda/sbox.yaml
- apps/azure-devops/azure-devops-agent-keda/stg.yaml
- apps/azure-devops/azure-devops-agent-keda/test.yaml
- apps/azure-devops/prod/base/kustomization.yaml
- apps/azure-devops/ptl/base/kustomization.yaml
- apps/azure-devops/serviceaccount/prod.yaml
- apps/azure-devops/serviceaccount/ptl.yaml
Checked nonprod went through fine yesterday
This change:
- Adds serviceaccount for prod&ptl
- Moves chart upgrade into base instead of env-specific
> DTSPO-15812: Add prod&ptl, move chart upgrade to base

- apps/base/alert.yaml
- apps/base/provider.yaml
* Flux upgrade to v2.2.0 has seen apiversion for _Alert_ & _Provider_ increase from _notification.toolkit.fluxcd.io/v1beta2_ to _notification.toolkit.fluxcd.io/v1beta3_
* v1beta3 API is backwards compatible with v1beta2. All current config will be valid
> upgrade Alert/Provider from v1beta2 to v1beta3 introudced in flux 2.2.0

- apps/azure-devops/azure-devops-agent-keda/dev/identity.yaml
- apps/azure-devops/azure-devops-agent-keda/ithc/identity.yaml
- apps/azure-devops/azure-devops-agent-keda/ptlsbox/identity.yaml
- apps/azure-devops/azure-devops-agent-keda/sbox/identity.yaml
- apps/azure-devops/azure-devops-agent-keda/stg/identity.yaml
- apps/azure-devops/azure-devops-agent-keda/test/identity.yaml
- apps/azure-devops/dev/base/kustomization.yaml
- apps/azure-devops/ithc/base/kustomization.yaml
- apps/azure-devops/ptlsbox/base/kustomization.yaml
- apps/azure-devops/sbox/base/kustomization.yaml
- apps/azure-devops/stg/base/kustomization.yaml
- apps/azure-devops/test/base/kustomization.yaml
All envs in ADO now using workload identity in SDS and confirmed working ok - removing old pod identities as cleanup work in nonprod, and will do prod afterwards
https://tools.hmcts.net/jira/browse/DTSPO-15812
> DTSPO-15812: Remove nonprod old identities

- apps/azure-devops/azure-devops-agent-keda/stg.yaml
Example of failure https://dev.azure.com/hmcts/MI%20Reporting/_build/results?buildId=513334&view=logs&s=6e00c4af-236e-555a-ee60-91129ae06a5d
[DTSPO-16540](https://tools.hmcts.net/jira/browse/DTSPO-16540)
Seems the agent is being kicked for some reason, re-establishing the session and then the build is breaking because between then it lost contact. 
I watched the mem/cpu usage during a failing stage, and they were sat consistently at 997Mi&1900mi for cpu/mem respectively and then the job failed and pod was restarted. 
Want to increase this ceiling for troubleshooting purposes to see if it's causing the failure.
> Upgrade ss-stg agents cpu&memory limits

- apps/ipam/ipam-ingress.yaml
DTSPO-16537 
Fix
ipam             6h48m   False   Ingress/ipam/ipam-ingress dry-run failed (Conflict): Operation cannot be fulfilled on ingresses.networking.k8s.io "ipam-ingress": uid mismatch: the provided object specified uid cc8c5e4e-f8c7-4308-b8f8-e83718affbfb, and no existing object was found...
> DTSPO-16537  removed uid

- apps/azureserviceoperator-system/aso/kustomization.yaml
https://tools.hmcts.net/jira/browse/DTSPO-16538
to fix this error
DatabaseAccount/ipam/ipam-ptl-cosmos dry-run failed: failed to get API group resources: unable to retrieve the complete
> DTSPO-16538 - added missing document db

- apps/admin/traefik2/ptl/00-traefik.yaml
- clusters/ptl/base/kustomization.yaml
[DTSPO-16658](https://tools.hmcts.net/jira/browse/DTSPO-16658)
Upgraded traefik to v26, followed what has been done on the non-prod environment https://github.com/hmcts/sds-flux-config/pull/4156
> DTSPO-16658 Updating ptl traefik v26.0.0

- apps/darts-modernisation/darts-automated-tasks/darts-automated-tasks.yaml
- apps/darts-modernisation/darts-migration/darts-api-migration.yaml
N/A
Setting ingress for darts-automated-tasks and darts-migration so that they don't use the default for the darts-api chart.
> Darts ingress fixes

- clusters/sbox/base/kustomization.yaml
https://tools.hmcts.net/jira/browse/DTSPO-16590
Turning off failed pods to continue with AKS upgrade
> DTSPO-16590 - Turned off failing pods

- clusters/ithc/base/kustomization.yaml
Turning off ITHC juror and darts because of  failed pods and HRs to continue with upgrade
> DTSPO-16591 - turn off Juror and darts because of failed pods

- apps/darts-modernisation/darts-api/prod.yaml
- apps/darts-modernisation/darts-automated-tasks/prod.yaml
- apps/darts-modernisation/darts-gateway/prod.yaml
https://tools.hmcts.net/jira/browse/DTSPO-16592
Disable Darts PDB to upgrade production clusters
> DTSPO-16592 - disble Darts pdb

- apps/keda/keda/ptlsbox.yaml
drop version to test
- Updated file: `ptlsbox.yaml`
- The version of the chart has been downgraded from 2.14.2 to 2.14.0.
> drop version

- bin/v2/add-helm-release.sh
- Upadting script to use new api version introduced in flux v2.3
md
- In `add-helm-release.sh`, the API version has been changed from `helm.toolkit.fluxcd.io/v2beta2` to `helm.toolkit.fluxcd.io/v2`.
```
> Update script to use new api version

- apps/vh/video-api/demo.yaml
- Changed the chart reference from ./stable/vh-video-api/prod``` to ```./stable/vh-video-api/non-prod```. 🔄
> Updated demo.yml to refer to non-prod chart 0.17

- apps/juror/juror-api/test.yaml
Reverts hmcts/sds-flux-config#4699
- Added the image `sdshmctspublic.azurecr.io/juror/api:prod-80aa422-20240515120635` to the `java` values.
> Revert "juror: temp unlock api"

- apps/admin/external-dns/dev/01-external-dns.yaml
https://tools.hmcts.net/jira/browse/DTSPO-17589
Updating external-dns version to 7.5.1
- The file `01-external-dns.yaml` in the `apps/admin/external-dns/dev` directory has been updated to include a new chart specification for external-dns with version 7.5.1 and relevant source references.
> Updating external-dns version

- apps/darts-modernisation/darts-automated-tasks/darts-automated-tasks.yaml
- apps/darts-modernisation/darts-automated-tasks/demo.yaml
- apps/darts-modernisation/darts-automated-tasks/ithc.yaml
- apps/darts-modernisation/darts-automated-tasks/prod.yaml
- apps/darts-modernisation/darts-automated-tasks/sbox.yaml
- apps/darts-modernisation/darts-automated-tasks/stg.yaml
- apps/darts-modernisation/darts-automated-tasks/test.yaml
https://tools.hmcts.net/jira/browse/DMP-2765
- k8s to 120s
- spring to 2m
- Made changes to `darts-automated-tasks.yaml`:
- Added `terminationGracePeriodSeconds: 120`.
- Updated `demo.yaml`:
- Added `GRACEFUL_SHUTDOWN_TIMEOUT: 2m`.
- Updated `ithc.yaml`:
- Added `GRACEFUL_SHUTDOWN_TIMEOUT: 2m`.
- Updated `prod.yaml`:
- Added `GRACEFUL_SHUTDOWN_TIMEOUT: 2m`.
- Updated `sbox.yaml`:
- Added `GRACEFUL_SHUTDOWN_TIMEOUT: 2m`.
- Updated `stg.yaml`:
- Added `GRACEFUL_SHUTDOWN_TIMEOUT: 2m`.
- Updated `test.yaml`:
- Added `GRACEFUL_SHUTDOWN_TIMEOUT: 2m`.
> DMP-2765 Setting graceful shutdown timeout for DARTS automated tasks

- apps/mi/mi-adf-shir-2/dev.yaml
- apps/mi/mi-adf-shir/dev.yaml
- Updated file: `dev.yaml`
- Updated the image tag for `mi-adf-shir-2` and `mi-adf-shir` to `dev-138fe9e-20240603124222`
- Updated replica count to 4 and memory limits to '4096Mi' for both configurations
> Update dev shir image for MI

- apps/dynatrace/dynatrace-crds-upgrade/kustomization.yaml
- apps/dynatrace/dynatrace-operator-upgrade.yaml
https://tools.hmcts.net/jira/browse/DTSPO-17585
bump version back to 1.1.0, dynatrace merged possible fix - https://github.com/Dynatrace/dynatrace-operator/pull/3219/files
- In `apps/dynatrace/dynatrace-crds-upgrade/kustomization.yaml`, the file path `dynatrace-operator-crd.yaml` was updated from version 1.0.1 to 1.1.0.
- In `apps/dynatrace/dynatrace-operator-upgrade.yaml`, the version of the chart `dynatrace-operator` was updated from 1.0.1 to 1.1.0. The `labels` section was removed.
> bump version back to 1.1.0, dynatrace merged possible fix

- apps/dynatrace/stg/00/kustomization.yaml
- apps/dynatrace/stg/base/kustomization.yaml
- clusters/stg/00/kustomization.yaml
- clusters/stg/base/kustomization.yaml
https://tools.hmcts.net/jira/browse/DTSPO-17585
Adds upgrade patch to stg 01
- `apps/dynatrace/stg/00/kustomization.yaml`
- Removed patches for dynatrace-operator-upgrade.yaml.
- `apps/dynatrace/stg/base/kustomization.yaml`
- Added dynakube-secret.enc.yaml to resources.
- Removed dynakube.yaml from patches.
- Added dynakube.yaml and dynatrace-operator-upgrade.yaml to patches.
- `clusters/stg/00/kustomization.yaml`
- Added base to resources.
- Removed paths for apps/flux-system/stg/00/kustomize.yaml.
- `clusters/stg/base/kustomization.yaml`
- Added paths for apps/admin/stg/base/kustomize.yaml and apps/dynatrace/base/kustomize-upgrade.yaml.
> Adds upgrade patch to stg 01

- apps/darts-modernisation/darts-api/darts-api.yaml
Reverts hmcts/sds-flux-config#4864
- darts-api.yaml 🔄
- Removed the `maxReplicaCount` field with a value of 5.
> Revert "Increasing darts-api KEDA function maxReplicaCount to 5"

- apps/admin/traefik2/sbox/00-traefik2.yaml
- apps/admin/traefik2/sbox/01-traefik2.yaml
N/A
Correct traefik config based on docs.
- `apps/admin/traefik2/sbox/00-traefik2.yaml` 🔄
- Added configuration to set the `traefik` port to be internally exposed with `default: false` and `internal: true`.
- Updated the `loadBalancerIP` to \"10.140.15.250\".
- `apps/admin/traefik2/sbox/01-traefik2.yaml` 🔄
- Added configuration to set the `traefik` port to be internally exposed with `default: false` and `internal: true`.
- Updated the `loadBalancerIP` to \"10.140.31.250\".
> fix: correct traefik config sbox

- apps/admin/sbox/base/kustomization.yaml
- apps/admin/traefik2/sbox/kustomization.yaml
N/A
Include the new Traefik ping ingress in the correct kustomization so it actually gets applied 🤦 
- `apps/admin/sbox/base/kustomization.yaml`:
- Added a reference to `././traefik2/sbox/traefik-ping-ingress.yaml` under the `resources` section.
- Removed the reference to `./traefik-ping-ingress.yaml` under the `patches` section.
- `apps/admin/traefik2/sbox/kustomization.yaml`:
- Removed the reference to `./traefik-ping-ingress.yaml` under the `resources` section.
> fix: include ping ingress in correct Kustomization

- apps/azure-devops/azure-devops-agent-keda/azure-devops-agent.yaml
- apps/azure-devops/azure-devops-agent-keda/dev.yaml
- apps/azure-devops/azure-devops-agent-keda/ithc.yaml
- apps/azure-devops/azure-devops-agent-keda/prod.yaml
- apps/azure-devops/azure-devops-agent-keda/ptl.yaml
- apps/azure-devops/azure-devops-agent-keda/ptlsbox.yaml
- apps/azure-devops/azure-devops-agent-keda/sbox.yaml
- apps/azure-devops/azure-devops-agent-keda/stg.yaml
- apps/azure-devops/azure-devops-agent-keda/test.yaml
[DTSPO-13833](https://tools.hmcts.net/jira/browse/DTSPO-13833)
Did some local testing replacing the pat token with using a managed identity.  Want to test this through flux using my chart-function branch.
- `azure-devops-agent.yaml`:
- Removed 'secrets' section and 'AZP_TOKEN' configuration.
- `dev.yaml`, `ithc.yaml`, `prod.yaml`, `ptl.yaml`, `sbox.yaml`, `stg.yaml`, `test.yaml`:
- Added 'secrets' section and 'AZP_TOKEN' configuration.
- `ptlsbox.yaml`:
- Added new configurations for image, triggerAuth, and chart.
> DTSPO-13833-testing-managed-identity-ptlsbox

- apps/mi/mi-adf-shir-2/stg.yaml
- Updated the image version to `prod-91ba39e-20240312133745` from `prod-91ba39e-20240607154028` 🔄
- Changed memoryLimits to `'4096Mi'`
- Updated environment to \"stg\"
- Updated resourceGroup to \"mi-stg-rg\"
> Fix Mi SHIR 2 stg image

- apps/monitoring/version-reporter/docsoutdated/docs-outdated.yaml
- apps/monitoring/version-reporter/helmcharts/helm-charts.yaml
- apps/monitoring/version-reporter/paloalto/palo-alto.yaml
- apps/monitoring/version-reporter/renovate/renovate.yaml
https://tools.hmcts.net/jira/browse/DTSPO-17826
Update version reporter values to use new custom service account settings
- The `saEnabled` field has been set to `false`.
- The `serviceAccountName` field has been replaced with `customServiceAccountName`.
- The `saEnabled` field has been set to `false`.
- The `serviceAccountName` field has been replaced with `customServiceAccountName`.
- The `saEnabled` field has been set to `false`.
- The `serviceAccountName` field has been replaced with `customServiceAccountName`.
- The `saEnabled` field has been set to `false`.
- The `serviceAccountName` field has been replaced with `customServiceAccountName`.
> Update version reporter values to use new custom service account settings

- apps/monitoring/automation/kustomization.yaml
- apps/monitoring/version-reporter/aksversions/aks-versions.yaml
- apps/monitoring/version-reporter/aksversions/image-policy.yaml
- apps/monitoring/version-reporter/aksversions/image-repo.yaml
- apps/monitoring/version-reporter/kustomization.yaml
https://tools.hmcts.net/jira/browse/DTSPO-17828
Adding aks version reporter service release to SDS monitoring namespace as a cronjob
- Added new file `aks-versions.yaml` in `apps/monitoring/version-reporter` for defining a CronJob to report AKS versions with specific configurations.
- Updated `kustomization.yaml` in `apps/monitoring/automation` to include references to the newly added `aks-versions.yaml` and related image repositories and policies.
> Adding aks version reporter service release to SDS monitoring namespace as a cronjob

- apps/darts-modernisation/darts-api/stg.yaml
- stg.yaml
- Updated DARTS_GATEWAY_URL to http://darts-gateway.staging.platform.hmcts.net/removeme
> Temp breaking of DARTS_GATEWAY URL for DARTS API

- apps/mi/mi-house-keeping-service/dev.yaml
- apps/mi/mi-house-keeping-service/ithc.yaml
- apps/mi/mi-house-keeping-service/mi-house-keeping-service.yaml
- apps/mi/mi-house-keeping-service/prod.yaml
- apps/mi/mi-house-keeping-service/sbox.yaml
- apps/mi/mi-house-keeping-service/stg.yaml
- apps/mi/mi-house-keeping-service/test.yaml
Removed unused aadIdentity and mi client ID (now using workload identity via serviceaccount)
Added required envs for storage account names now moved from mi-job to chart-job
ℹ️ `dev.yaml`
- Removed `aadIdentityName` and `userAssignedIdentityID`
- Changed `schedule` to \"45 * * * *\"
- Removed `environment` and `MI_CLIENT_ID`
ℹ️ `ithc.yaml`
- Removed `aadIdentityName` and `userAssignedIdentityID`
- Changed `schedule` to \"45 * * * *\"
- Removed `environment` and `MI_CLIENT_ID`
ℹ️ `mi-house-keeping-service.yaml`
- Added environment variables for storage landing, export, persistent, and audit
- Changed `schedule` to '45 * * * *'
ℹ️ `prod.yaml`
- Removed `aadIdentityName` and `MI_CLIENT_ID`
- Changed `schedule` from \"45 2 * * *\" to \"45 2 * * *\"
ℹ️ `sbox.yaml`
- Removed …
> Update envs for housekeeping job chart

- apps/juror/juror-api/ithc.yaml
- Modified the image value to `sdshmctspublic.azurecr.io/juror/api:pr-541-90ff1e3-20240627105900` for the Java environment.
- Also updated the ingressHost to `juror-api.ithc.platform.hmcts.net`.
> juror: lock ithc with a pr image

- apps/darts-modernisation/darts-api/stg.yaml
Reverts hmcts/sds-flux-config#4944
- Updated `stg.yaml`: Changed the value of `DARTS_GATEWAY_URL` environment variable from `http://darts-gateway.staging.platform.hmcts.net/removeme` to `http://darts-gateway.staging.platform.hmcts.net`
> Revert "Temp breaking of DARTS_GATEWAY URL for DARTS API"

- apps/juror/juror-api/demo.yaml
- apps/juror/juror-bureau/demo.yaml
- apps/juror/juror-pnc/demo.yaml
- apps/juror/juror-public/demo.yaml
- apps/juror/juror-scheduler-api/demo.yaml
- apps/juror/juror-scheduler-execution/demo.yaml
- Updated image tag for juror-api, juror-bureau, juror-pnc, juror-public, juror-scheduler-api, and juror-scheduler-execution in their respective demo.yaml files
- Updated the image tag for each service to a new version with a timestamp ending in 20240628073923, 20240628075655, 20240628065426, 20240628063330, 20240628073923, and 20240628065044 respectively
> juror: update demo images

- apps/juror/juror-scheduler-execution/ithc.yaml
- Added a new environment variable `BAIS_PORT` with the value of `2220`. 🚀
> juror: break ithc BAIS_PORT

- apps/juror/juror-scheduler-execution/ithc.yaml
Reverts hmcts/sds-flux-config#4965
- Added environment variable \"BAIS_PORT\" with a value of 2220 🌐
> juror: break ithc bais

- apps/juror/juror-scheduler-execution/ithc.yaml
Reverts hmcts/sds-flux-config#4966
- Updated ithc.yaml```
- Removed environment variables BAIS_PORT: 2220
- Defined spec for ingressHost: juror-scheduler-execution.ithc.platform.hmcts.net
> Revert "juror: break ithc bais"

- apps/juror/juror-api/ithc.yaml
unlock API in ithc
- Updated the value of the `image` key under `java` to `sdshmctspublic.azurecr.io/juror/api:pr-541-e95fdad-20240701113008`
- Added `ingressHost` key with the value `juror-api.ithc.platform.hmcts.net` under `java` section.
> unlock API in ithc

- apps/met/pod-delete-cron/prod.yaml
- apps/met/prod/base/kustomization.yaml
N/A
Added nightly pod "restarts" in prod
- Created new file `prod.yaml` in `apps/met/pod-delete-cron/` to define a HelmRelease for deleting pods nightly at 22:50 with a 5-minute interval.
- Updated `kustomization.yaml` in `apps/met/prod/base/` to add references to the new pod-delete-cron resources.
> feat: prod pod restart nightly

- apps/vh/video-api/dev.yaml
Added Vodafone configuration
- Added new aliases for kinlyconfiguration--kinlyapiurl and kinlyconfiguration--kinlyselftestapiurl.
- Renamed aliases for kinlyconfiguration--telephoneconferencenumber and kinlyconfiguration--telephoneconferencenumberwelsh to vodafoneconfiguration--conferencephonenumber and vodafoneconfiguration--conferencephonenumberwelsh.
- Added vodafoneconfiguration parameters: apisecret, selftestapikey, apiurl, selftestapiurl, pexipnode, pexipselftestnode, and callbacksecret.
> Update dev.yaml  - Added Vodafone configuration

- apps/jenkins/jenkins/ptlsbox/jenkins-controller-version.yaml
https://tools.hmcts.net/jira/browse/DTSPO-17734 
Upgrade sbox java to 21
md
- apps/jenkins/jenkins/ptlsbox/jenkins-controller-version.yaml
- Updated the Jenkins controller tag from 2.426-523 to pr-1436-2.464-1076.
```
> Java upgrade for sbox jenkins

- apps/darts-modernisation/darts-gateway/stg.yaml
This reverts commit e2be46bc7d19383772f3fbe03805bd4dfa1d6720.
- stg.yaml
- Removed a line specifying the number of replicas for the Java service in the staging environment.
> Revert " temporarily stop darts gateway staging (#5019)"

- apps/pre/pre-portal/stg.yaml
Enable mk watch page in stg
- Added the `ENABLE_MK_WATCH_PAGE` environment variable with the value `true`. 🆕
> Add env var to enable mk watch page in stg

- apps/juror/juror-api/ithc.yaml
Initial lock of juror-api in ithc to PR-590
- Updated the image value to `sdshmctspublic.azurecr.io/juror/api:pr-590-95fd00a-20240715131301` and removed the `EMPTY_VAR` environment variable.
> Initial lock of juror-api in ithc to PR-590

- apps/darts-modernisation/darts-gateway/stg.yaml
temporarily stop darts gateway staging to QA https://tools.hmcts.net/jira/browse/DMP-3354
- Added a new configuration for the `darts-gateway` to manage replicas.
- Updated the `ingressHost` to `darts-gateway.staging.platform.hmcts.net`.
- Updated the `DARTS_API_URL` to `https://darts-api.staging.platform.hmcts.net`.
> DMP-3354 temporarily stop darts gateway staging

- apps/darts-modernisation/darts-gateway/stg.yaml
This reverts commit 926d5055b33bea06faa99415c720d42593c3234c.
re-starting darts gateway on stg
- Removed one of the replicas for the `java` service.
- Updated the `ingressHost` to `darts-gateway.staging.platform.hmcts.net`.
- Set the `DARTS_API_URL` environment variable to `https://darts-api.staging.platform.hmcts.net`.
> Revert " temporarily stop darts gateway staging (#5019) (#5028)"

- apps/darts-modernisation/darts-gateway/stg.yaml
needed to QA DMP-3354
- Added `replicas: 0` under `java` values.
- Added `ingressHost: darts-gateway.staging.platform.hmcts.net` under `values`.
>  DMP-3354 temporarily stopping darts gateway on stg

- apps/darts-modernisation/darts-gateway/stg.yaml
- **stg.yaml**
- Added a new configuration for the `java` part, setting `replicas` to 0.
- Modified the `ingressHost` to `darts-gateway.staging.platform.hmcts.net`.
> NOJIRA stop darts gateway stg

- apps/darts-modernisation/darts-gateway/test.yaml
N/A
Enable the clean test endpoint on the test darts gateway deployment. This endpoint is required for performance testing the gateway.
- Updated `test.yaml`: Added `TESTING_SUPPORT_ENDPOINTS_ENABLED: true` and modified `APPLICATIONINSIGHTS_INSTRUMENTATION_LOGGING_LEVEL` from `ALL` to `ALL` 🚀
> Enable the clean endpoint in test gateway

- apps/darts-modernisation/darts-gateway/stg.yaml
- Removed the `replicas: 0` configuration for the `java` component.
- Updated the `ingressHost` to `darts-gateway.staging.platform.hmcts.net`.
- Set the `DARTS_API_URL` environment variable to `https://darts-api.staging.platform.hmcts.net`.
>  NOJIRA start darts gateway

- apps/opal/automation/kustomization.yaml
- apps/opal/opal-user-service/image-policy.yaml
- apps/opal/opal-user-service/image-repo.yaml
- apps/opal/opal-user-service/opal-user-service.yaml
- apps/opal/opal-user-service/stg.yaml
- apps/opal/stg/base/kustomization.yaml
Rename Opal Auth service to Opal user service
- Updated `kustomization.yaml` in `apps/opal/automation/`
- Renamed image repository and image policy for `opal-auth-service` to `opal-user-service`
- Renamed `image-policy.yaml` and `image-repo.yaml` in `apps/opal/opal-auth-service` to `image-policy.yaml` and `image-repo.yaml` respectively under `opal-user-service`
- Renamed `opal-auth-service.yaml` and `stg.yaml` in `apps/opal/opal-auth-service` to `opal-user-service.yaml` and `stg.yaml` respectively under `opal-user-service`
- Updated `kustomization.yaml` in `apps/opal/stg/base/`
- Updated the reference from `opal-auth-service` to `opal-user-service`
> Rename Opal Auth service to Opal user service

- apps/darts-modernisation/darts-api/prod.yaml
- apps/darts-modernisation/darts-gateway/prod.yaml
- apps/darts-modernisation/darts-portal/prod.yaml
DMP-2526
Updated PROD Azure Ad B2C configs
- `prod.yaml`:
- Changed the `ACTIVE_DIRECTORY_B2C_BASE_URI` and `ACTIVE_DIRECTORY_B2C_AUTH_URI` from the old URLs to the new URLs.
- Updated the `ACTIVE_DIRECTORY_B2C_ON_MICROSOFT_URI` to the new URL.
- Updated the `DARTS_AZUREAD_B2C_ORIGIN_HOST` to a new URL.
> dmp-2526: update PROD config for Azure AD B2C

- apps/pre/pre-api-cron-cleanup-live-events/prod.yaml
- Updated `prod.yaml` in `pre-api-cron-cleanup-live-events`:
- Changed the `suspend` value from `false` to `true`.
- Removed the `disableActiveClusterCheck` field from the file.
- Updated the `schedule` from `\"0 20 * * *\"` to `\"0 20 * * *\"` (no change).
> disable pre cleanup live event job in prod

- apps/juror/juror-api/demo.yaml
- apps/juror/juror-api/ithc.yaml
- apps/juror/juror-bureau/demo.yaml
- apps/juror/juror-bureau/ithc.yaml
updating the images in ITHC and Demo for testing
- `demo.yaml`: Updated the image for the java service to `sdshmctspublic.azurecr.io/juror/api:pr-612-66e29fa-20240719115823` and the ingressHost to `juror-api.demo.platform.hmcts.net`.
- `ithc.yaml`: Updated the image for the java service to `sdshmctspublic.azurecr.io/juror/api:pr-612-66e29fa-20240719115823` and the ingressHost to `juror-api.ithc.platform.hmcts.net`.
- `demo.yaml`: Updated the image for the nodejs service to `sdshmctspublic.azurecr.io/juror/bureau:pr-644-ca6765c-20240719104710` and the ingressHost to `juror.demo.apps.hmcts.net`, with the environment variable `SKIP_SSO` set to `true`.
- `ithc.yaml`: Updated the image for the nodejs service to `sdshmctspublic.azurecr.io/juror/bureau:pr-644-ca6765c-20240719104710` and the …
> juror deployment - latest version of stabilisation3

- apps/juror/juror-api/demo.yaml
Updated deployment of stabilisation3 for juror-api, taking out the index creation steps to reduce deployment time in prod
- Updated the `image` value for Java to `sdshmctspublic.azurecr.io/juror/api:pr-612-04a4647-20240722131513`.
> updated deployment of stabilisation3 juror-api

- apps/rbac/reader-clusterrole.yaml
To support devs being able to `top pod` for example. This is already enabled in `cnp-flux-config`.
> Grant pod metrics access to readers

- apps/dynatrace/demo/base/kustomization.yaml
- apps/dynatrace/dynatrace-crds-upgrade/kustomization.yaml
- apps/dynatrace/dynatrace-operator-upgrade.yaml
- clusters/demo/base/kustomization.yaml
1.1.0 has this bug
```
Helm install failed for release dynatrace/dynatrace-operator with chart dynatrace-operator@1.1.0: Unable to continue with install: CustomResourceDefinition "dynakubes.dynatrace.com" in namespace "" exists and cannot be imported into the current release: invalid ownership metadata; label validation error: missing key "app.kubernetes.io/managed-by": must be set to "Helm"; annotation validation error: missing key "meta.helm.sh/release-name": must be set to "dynatrace-operator"; annotation validation error: missing key "meta.helm.sh/release-namespace": must be set to "dynatrace"
```
https://github.com/Dynatrace/dynatrace-operator/issues/3215
Don't see it mentioned in release notes.. but a pr for it was merged a while back so it should be in the latest release
- Added a …
> Ugpgrade dynatrace in ss-demo

- apps/base/alert.yaml
- apps/darts-modernisation/darts-portal/darts-portal.yaml
- apps/toffee/sbox/base/slack-token.enc.yaml
https://tools.hmcts.net/jira/browse/DTSPO-15798
- add working slack-token
- increase severity for alerts to error again
- Modified `alert.yaml` in `apps/base`:
- Changed `eventSeverity` from `info` to `error`.
- Added `slack-token.enc.yaml` to `apps/toffee/sbox/base`:
- Contains encrypted Slack token information as a Kubernetes Secret.
- Includes creation and modification timestamps.
> DTSPO-15798 - toffee sbox: Add working slack-token, alerts to error severity again

- apps/dynatrace/demo/base/dynakube.yaml
- apps/dynatrace/dynakube-upgrade.yaml
Try to force upgrade and get around broken kustomization
Moving to v1beta2 at the same time as 1.2.1 seems to give problems. Rolling this back first to see if the webhook conversion service will no longer be needed to try and get some pods deployed. After that, can try to re-upgrade 🤦🏻 
- Updated `dynakube.yaml` 🔄: 
- Changed `apiVersion` from `dynatrace.com/v1beta2` to `dynatrace.com/v1beta1`.
- Updated `dynakube-upgrade.yaml` 🔄: 
- Changed `apiVersion` from `dynatrace.com/v1beta2` to `dynatrace.com/v1beta1`.
- Updated the `metadataEnrichment` section within `spec`.
> Attempt DynaKube v1beta1 again sds-demo

- apps/juror/juror-api/demo.yaml
- apps/juror/juror-api/ithc.yaml
Juror api deployment of stabilisation5 branch into ITHC and Demo
- Updated the Java image from `sdshmctspublic.azurecr.io/juror/api:pr-644-6fea0e0-20240725161921` to `sdshmctspublic.azurecr.io/juror/api:pr-644-bcd5d4f-20240726130544`
- Modified the `ingressHost` to `juror-api.demo.platform.hmcts.net`
- Updated the Java image from `sdshmctspublic.azurecr.io/juror/api:pr-644-6fea0e0-20240725161921` to `sdshmctspublic.azurecr.io/juror/api:pr-644-bcd5d4f-20240726130544`
- Added `EMPTY_VAR: one` to the environment
> juror-api deployment of stabilisation5 in Demo and ITHC

- apps/darts-modernisation/darts-api/prod.yaml
https://tools.hmcts.net/jira/browse/DMP-3365
Setting MODERNISED_DARTS_START_DATE for prod
- Added MODERNISED_DARTS_START_DATE with value 2099-01-01 🚀
> DMP-3365: Setting MODERNISED_DARTS_START_DATE for prod

- apps/juror/juror-api/demo.yaml
- apps/juror/juror-api/ithc.yaml
- apps/juror/juror-bureau/demo.yaml
- apps/juror/juror-bureau/ithc.yaml
- apps/juror/juror-scheduler-api/ithc.yaml
Juror stabilisation6 deployment for juror-api, juror-bureau and an update for scheduler-api repo
- Updated image for juror-api in demo and ithc environments, changing the tag to pr-655-3e9663d-20240730085827
- Updated image for juror-bureau in demo and ithc environments, changing the tag to pr-672-2b07f14-20240730095912
- Updated image for juror-scheduler-api in ithc environment, but the diff does not provide the new image tag.
> juror deployments for stabilisation6

- apps/juror/juror-api/demo.yaml
- apps/juror/juror-api/ithc.yaml
- apps/juror/juror-bureau/demo.yaml
- apps/juror/juror-bureau/ithc.yaml
- apps/juror/juror-scheduler-api/ithc.yaml
Stabilisation7 deployment into ITHC and Demo for juror-api and juror-bureau
- Updated the image version to `pr-665-2b00ea3-20240731122830` and the `ingressHost` to `juror-api.demo.platform.hmcts.net`.
- Updated the image version to `pr-665-2b00ea3-20240731122830` and the `ingressHost` to `juror-api.ithc.platform.hmcts.net`.
- Updated the image version to `pr-676-6e39ac1-20240731120558` and the `ingressHost` to `juror.demo.apps.hmcts.net`.
- Updated the image version to `pr-676-6e39ac1-20240731120558` and the `ingressHost` to `juror.ithc.apps.hmcts.net`.
> Juror deployments

- apps/juror/juror-api/demo.yaml
- apps/juror/juror-api/ithc.yaml
- apps/juror/juror-bureau/demo.yaml
- apps/juror/juror-bureau/ithc.yaml
Stabilisation8 deployment into ITHC and Demo
- demo.yaml```: Updated the Java image from sdshmctspublic.azurecr.io/juror/api:pr-665-16cd22a-20240731143058 to sdshmctspublic.azurecr.io/juror/api:pr-673-2fe09ea-20240801144016 for the demo environment, along with the ingress host and environment settings.
- ```ithc.yaml```: Similar changes to the Java image, ingress host, and environment for the ithc environment.
- ```demo.yaml```: Updated the Nodejs image from sdshmctspublic.azurecr.io/juror/bureau:pr-676-6e39ac1-20240731120558 to sdshmctspublic.azurecr.io/juror/bureau:pr-681-29488f4-20240801140824 for the demo environment, along with the ingress host and environment settings.
- ```ithc.yaml```: Similar changes …
```
> stabilisation8 update for juror

- apps/pre/pre-api/stg.yaml
- In `apps/pre/pre-api/stg.yaml`, the `MEDIA_SERVICE` value was changed from `AzureMediaService` to `MediaKind`. 🔄
> Changing media service to Mediakind

- apps/keda/demo/base/kustomization.yaml
- apps/keda/dev/base/kustomization.yaml
- apps/keda/ithc/base/kustomization.yaml
- apps/keda/keda/patching.yaml
- apps/keda/ptlsbox/base/kustomization.yaml
- apps/keda/sbox/base/kustomization.yaml
- apps/keda/stg/base/kustomization.yaml
- apps/keda/test/base/kustomization.yaml
- apps/toffee/recipe-receiver/toffee-recipe-receiver.yaml
https://tools.hmcts.net/jira/browse/DTSPO-18304
Adding KEDA patching yaml file and patch to each non-prod environment
- Updated files in the `apps/keda` directory:
- Updated kustomization.yaml files in the `base`, `dev`, `ithc`, `ptlsbox`, `sbox`, `stg`, and `test` directories to add a new `patching.yaml` file.
- Added a new `keda/patching.yaml` file with HelmRelease configuration.
- Updated the `apps/toffee/recipe-receiver/toffee-recipe-receiver.yaml` file to change the value of `namespace` to `serviceBusName` under triggers.
> Adding KEDA patching yaml file and patch to each non-prod environment

- apps/pdda/serviceaccount/stg.yaml
Reverts hmcts/sds-flux-config#5208
- Updated file: `apps/pdda/serviceaccount/stg.yaml`
- Changed the `azure.workload.identity/client-id` annotation value from \"76981322-2cf0-44ea-a49c-bda08c7878c5\" to \"ee71b40f-90bf-49af-936d-04fbde2023fc\" 🔄
> Revert "Update stg.yaml to the correct client id for pdda and pdm"

- apps/juror/juror-api/demo.yaml
- apps/juror/juror-api/ithc.yaml
- apps/juror/juror-bureau/demo.yaml
- apps/juror/juror-bureau/ithc.yaml
Juror Stabilisation10 deployment to ITHC and Demo for juror-api and juror-bureau
- Updated the image version for the `juror-api` to `pr-685-3674b98-20240808112849`.
- Updated the ingress host to `juror-api.demo.platform.hmcts.net`.
- Updated the image version for the `juror-api` to `pr-685-3674b98-20240808112849`.
- Updated the ingress host to `juror-api.ithc.platform.hmcts.net`.
- Updated the image version for the `juror-bureau` to `pr-705-5900b39-20240808105945`.
- Informed to skip SSO for the bureau in the `demo` environment.
- Updated the image version for the `juror-bureau` to `pr-705-5900b39-20240808105945`.
- Informed to skip SSO for the bureau in the `ithc` environment.
> juror deployment to ITHC and Demo

- apps/pip/channel-management/test.yaml
- apps/pip/frontend/test.yaml
- apps/pip/publication-services/test.yaml
Update frontend and publication-services image, and disable channel-management in test env
- Decreased the number of replicas for `pip-channel-management` from 2 to 0. 
- Updated the image for `pip-frontend` to `sdshmctspublic.azurecr.io/pip/frontend:pr-1311-ec1fc47-20240809075846` and increased replicas to 2.
- Updated the image for `pip-publication-services` to `sdshmctspublic.azurecr.io/pip/publication-services:pr-447-4e4baa1-20240809081246` and increased replicas to 2.
> PUB-2359 Update frontend and PS image, and disable CM in test env

- apps/juror/juror-api/demo.yaml
- apps/juror/juror-api/ithc.yaml
- apps/juror/juror-bureau/demo.yaml
- apps/juror/juror-bureau/ithc.yaml
- apps/juror/juror-public/demo.yaml
- apps/juror/juror-public/ithc.yaml
juror deployment into ITHC and Demo for Stabilisation11 updates: juror-public, juror-bureau, juror-api
- In `demo.yaml` and `ithc.yaml` files under `apps/juror/juror-api/`, the image has been updated from `sdshmctspublic.azurecr.io/juror/api:pr-696-0ba8b12-20240809102412` to `sdshmctspublic.azurecr.io/juror/api:pr-697-1c27578-20240813095335`.
- In `demo.yaml` and `ithc.yaml` files under `apps/juror/juror-bureau/`, the image has been updated from `sdshmctspublic.azurecr.io/juror/bureau:pr-705-5900b39-20240808105945` to `sdshmctspublic.azurecr.io/juror/bureau:pr-715-6fd316a-20240813090115`.
- In `demo.yaml` and `ithc.yaml` files under `apps/juror/juror-public/`, the image has been updated from `sdshmctspublic.azurecr.io/juror/public:pr-238-4dd791d-20240806115937` to …
> juror deployment into ITHC and DEMO

- apps/dynatrace/demo/base/dynakube.yaml
- apps/dynatrace/demo/base/kustomization.yaml
Change demo back to 1.1.0 to test
- **dynakube.yaml**
- Changed `apiVersion` from `dynatrace.com/v1beta2` to `dynatrace.com/v1beta1` for `DynaKube`.
- **kustomization.yaml**
- Removed `././dynakube-upgrade.yaml` and added `././dynakube.yaml` as a resource.
- Removed `././dynatrace-operator-upgrade.yaml` as a patch.
> Change demo back to 1.1.0 to test

- apps/dynatrace/demo/base/dynakube.yaml
- apps/dynatrace/demo/base/kustomization.yaml
Using dynakube api version v1beta2 to try and get dynatrace agent upgrade running
- Updated `apps/dynatrace/demo/base/dynakube.yaml` 🔄
- Changed the `apiVersion` from `dynatrace.com/v1beta1` to `dynatrace.com/v1beta2`.
- Updated `apps/dynatrace/demo/base/kustomization.yaml` 🔄
- Replaced `././dynakube.yaml` with `././dynakube-upgrade.yaml` in the list of resources.
> Use dynakube api v1beta2

- apps/pip/channel-management/pip-channel-management.yaml
- apps/pip/channel-management/prod.yaml
- apps/pip/channel-management/stg.yaml
- apps/pip/channel-management/test.yaml
Scale down replicas for channel management
- `pip-channel-management.yaml`
- Added a `replicas: 0` for the `java` service
- Updated the image to `sdshmctspublic.azurecr.io/pip/channel-management:prod-737f843-20240813125024`
- Added `disableTraefikTls: true` to the chart
- `prod.yaml`
- Changed the number of replicas for `java` service from 2 to unspecified
- Updated `ingressHost` to `pip-channel-management.platform.hmcts.net`
- Added `ACCOUNT_MANAGEMENT_URL: https://pip-account-management.platform.hmcts.net`
- `stg.yaml`
- Changed the number of replicas for `java` service from 2 to unspecified
- Updated `ingressHost` to `pip-channel-management.staging.platform.hmcts.net`
- Added `MANAGED_IDENTITY_CLIENT_ID: 8d0ead51-3b31-44df-a78e-ada4eea9fe87` …
> PUB-2359 - Scale down replicas for channel management

- apps/base/alert.yaml
- Flux alert integration is intermittently firing false error events occuring when kustomization takes place with latest flux repo revision
- Some of these come from prod cluster and worrying dev teams
- this PR removes kustomization from alert spec for time being
- The file `apps/base/alert.yaml` has been modified. The changes involve removing the `eventSources` section and its related content, including `kind`, `namespace`, and `name` fields.
> Remove kustomization from alert spec

- apps/juror/juror-bureau/ithc.yaml
Updated ithc versions
- Updated the `image` value for `nodejs` to `sdshmctspublic.azurecr.io/juror/bureau:pr-715-dbfa869-20240816144128` 📷
- Set `SKIP_SSO` environment variable to `true`
> Updated ithc versions

- apps/monitoring/kube-prometheus-stack-crds/kustomization.yaml
- apps/monitoring/kube-prometheus-stack/kube-prometheus-stack.yaml
Patch prometheus grafana on sds
- apps/monitoring/kube-prometheus-stack-crds/kustomization.yaml
- Updated the URLs for kube-prometheus-stack crds from version 58.5.1 to version 61.9.0
- apps/monitoring/kube-prometheus-stack/kube-prometheus-stack.yaml
- Updated the version of kube-prometheus-stack in the Helm chart from 58.5.1 to 61.9.0
> Patch prometheus grafana on sds

- apps/juror/juror-scheduler-api/ithc.yaml
switch juror scheduler to master now pr228 has been merged
- Updated the `java` image to `sdshmctspublic.azurecr.io/juror/scheduler-api:pr-228-b0108b6-20240730090229`
- Added `ingressHost: juror-scheduler-api.ithc.platform.hmcts.net`  🚀
> juror: switch juror-scheduler-api to master as pr228 now merged

- apps/vh/admin-web/demo.yaml
- apps/vh/booking-queue-subscriber/demo.yaml
- apps/vh/bookings-api/demo.yaml
- apps/vh/notification-api/demo.yaml
- apps/vh/scheduler-jobs/demo.yaml
- apps/vh/test-api/demo.yaml
- apps/vh/test-web/demo.yaml
- apps/vh/user-api/demo.yaml
- apps/vh/video-api/demo.yaml
- apps/vh/video-api/image-policy.yaml
- apps/vh/video-web/demo.yaml
- apps/vh/video-web/image-policy.yaml
See [VIH-10889](https://tools.hmcts.net/jira/browse/VIH-10889)
Updates all vh app's Flux Demo env patches to trigger on Dev image pushes 
Testing can only be done via Flux on PR completion
- Modified apps/vh/admin-web/demo.yaml
- Updated image tag from prod-c065873-202408191245 to dev-8b76cb6-202408150929
- Modified apps/vh/booking-queue-subscriber/demo.yaml
- Updated image tag from prod-5137449-202408191239 to dev-89bc8f3-202408060944
- Modified apps/vh/bookings-api/demo.yaml
- Updated image tag from prod-b147a9d-202408191242 to dev-3f9f0e3-202408200915
- Modified apps/vh/notification-api/demo.yaml
- Updated image tag from prod-661abad-202408191246 to dev-f3bea10-202405291308
- Modified apps/vh/scheduler-jobs/demo.yaml
- Updated image tag from prod-a2dd498-202408191239 to …
> set vm apps to use dev image for demo env

- CODEOWNERS
- remove prod approvals group from codeowners file
- prod approvals group is legacy and not used anymore
md
- Removed clusters/prod/ from the list of CODEOWNERS for @hmcts/production-apps-approvals
```
> Remove prod approvals group from codeowners - legacy

- apps/vh/notification-api/ithc.yaml
See [VIH-10911](https://tools.hmcts.net/jira/browse/VIH-10911)
Changes vh-notification-api to use staging image
- Updated the image from `prod` to `staging` with a different timestamp.
> change vh-notification-api ithc to use stg image policy

- apps/pip/frontend/test.yaml
Remove test image with rate limiting prototype
- Removed one instance of `replicas: 2` 
- Removed the `image` field
- Updated `ingressHost` to `pip-frontend.test.platform.hmcts.net`
- Updated `DATA_MANAGEMENT_URL` to point to `https://pip-data-management.test.platform.hmcts.net`
> PUB-2327 Remove test image with rate limiting prototype

- apps/darts-modernisation/darts-api/demo.yaml
- apps/darts-modernisation/darts-automated-tasks/demo.yaml
Changes:
During QA it it sometimes important to see the full details of http requests and responses Darts is making to external services, e.g. ARM.
This PR configures Feign clients to log headers, body, and metadata for both requests and responses on Demo
depends on: 
https://github.com/hmcts/darts-api/pull/1916
> NO_JIRA: log Darts feign clients requests/responses full details on Demo

- apps/pip/frontend/demo.yaml
- apps/pip/frontend/ithc.yaml
- apps/pip/frontend/prod.yaml
- apps/pip/frontend/stg.yaml
- apps/pip/frontend/test.yaml
See [PUB-2531](https://tools.hmcts.net/jira/browse/PUB-2531)
Removed ENABLE_CFT flag from PIP frontend
- demo.yaml
- Removed ENABLE_CFT: true from the spec.
- ithc.yaml
- Removed ENABLE_CFT: true from the spec.
- prod.yaml
- Removed ENABLE_CFT: true from the spec.
- stg.yaml
- Removed ENABLE_CFT: true from the spec.
- test.yaml
- Removed ENABLE_CFT: true from the spec.
> PUB-2531 Removed ENABLE_CFT flag from PIP frontend

- apps/pip/frontend/test.yaml
Reverts hmcts/sds-flux-config#5353
- Removed an image reference for `sdshmctspublic.azurecr.io/pip/frontend:pr-1330-dd1fbe7-20240829113917`.
- Updated the replicas value to 2.
> Revert "add pr image for test"

- apps/pip/dev/base/kustomization.yaml
See [PUB-2564](https://tools.hmcts.net/jira/browse/PUB-2564)
Add Azure Service Operator resource group for dev env to provision blob storage
- Added a resource for Azure Service Operator system resource group.
- Updated the namespace to \"pip\".
- Added a patch for dev identity.
> PUB-2564 Add Azure Service Operator resource group for dev env to provision blob storage

- apps/azureserviceoperator-system/resources/resource-group.yaml
- apps/base/workload-identity/workload-identity-federated-credential.yaml
- apps/base/workload-identity/workload-identity-rg.yaml
- apps/base/workload-identity/workload-identity-ua-identity.yaml
[DTSPO-18113](https://tools.hmcts.net/jira/browse/DTSPO-18113)
Enable ASO upgrade by updating any beta versions for aso resources
2.4 breaking changes detailed here: https://github.com/Azure/azure-service-operator/releases/tag/v2.4.0
Same work was done on CFT previously
- Updated the `apiVersion` from `v1beta20200601` to `v1api20200601`.
- Changed the `apiVersion` from `v1beta20220131preview` to `v1api20220131preview`.
- Modified the `apiVersion` from `v1beta20200601` to `v1api20200601`.
- Updated the `apiVersion` from `v1beta20181130` to `v1api20181130`.
> ASO: beta resources update - needed for ASO upgrade

- apps/pip/data-management/test.yaml
Reverts hmcts/sds-flux-config#5389
- Changed the autoscaling configuration to specify the number of replicas (replicas: 2) instead of using autoscaling with a minReplicas of 2, maxReplicas of 5, and targetCPUUtilizationPercentage of 80.
> Revert "PUB-1692 - Testing autoscaling"

- apps/darts-modernisation/darts-portal/prod.yaml
- apps/darts-modernisation/darts-portal/sbox.yaml
- apps/darts-modernisation/darts-portal/stg.yaml
- demo and staging use the staging B2C
- set the URL on staging to demo so that a link we provide to the internal login page points to demo
https://tools.hmcts.net/jira/browse/DMP-3863
- Added a new environment variable `DARTS_AZUREAD_B2C_HOSTNAME` with value `https://darts.apps.hmcts.net`.
- Added a new environment variable `DARTS_AZUREAD_B2C_HOSTNAME` with value `https://darts.sandbox.apps.hmcts.net`.
- Added a new environment variable `DARTS_AZUREAD_B2C_HOSTNAME` with value `https://darts.demo.apps.hmcts.net`.
> Setting DARTS portal DARTS_AZUREAD_B2C_HOSTNAME appropriately

- apps/pre/pre-api-cron-cleanup-live-events/stg.yaml
- apps/pre/pre-api-cron-cleanup-streaming-locators/stg.yaml
- apps/pre/pre-api/stg.yaml
- `pre-api-cron-cleanup-live-events/stg.yaml` 🔄
- Changed `MEDIA_SERVICE` from `AzureMediaService` to `MediaKind`.
- `pre-api-cron-cleanup-streaming-locators/stg.yaml` 🔄
- Changed `MEDIA_SERVICE` from `AzureMediaService` to `MediaKind`.
- `pre-api/stg.yaml` 🔄
- Changed `MEDIA_SERVICE` from `AzureMediaService` to `MediaKind`.
> Set PRE STG to use MediaKind now

- apps/pip/account-management/test.yaml
- apps/pip/data-management/test.yaml
- apps/pip/frontend/test.yaml
- apps/pip/publication-services/test.yaml
- apps/pip/subscription-management/test.yaml
Reverts hmcts/sds-flux-config#5425
- Modified files: 
- test.yaml in account-management, data-management, frontend, publication-services, and subscription-management
- In each file:
- Replaced the autoscaling configuration with a simple replicas field, setting its value to 2
- Updated the ingress host to point to the test environment platform URL
- Updated the environment variables for each service to point to the appropriate test environment URLs
> Revert "PUB-1692 - Autoscaling test"

- apps/mailrelay2/mailrelay2/dev/dev.yaml
https://tools.hmcts.net/jira/browse/DTSPO-18598
Changing disk size for mailrelay2 from 500gb to 64gb and standard ssd
- Updated `dev.yaml` in `mailrelay2` app:
- Changed `storageClass` from \"managed-premium\" to \"managed\"
- Changed `storageSize` from 500Gi to 64Gi
- Set `enableOutboundTls` to true
> DTSPO-18598 - changing disk size for mailrelay2

- apps/vh/admin-web/image-policy.yaml
- apps/vh/admin-web/test.yaml
- apps/vh/booking-queue-subscriber/image-policy.yaml
- apps/vh/booking-queue-subscriber/test.yaml
- apps/vh/bookings-api/image-policy.yaml
- apps/vh/bookings-api/test.yaml
- apps/vh/notification-api/image-policy.yaml
- apps/vh/notification-api/test.yaml
- apps/vh/scheduler-jobs/image-policy.yaml
- apps/vh/scheduler-jobs/test.yaml
- apps/vh/user-api/image-policy.yaml
- apps/vh/user-api/test.yaml
- apps/vh/video-api/image-policy.yaml
- apps/vh/video-api/test.yaml
- apps/vh/video-web/image-policy.yaml
- apps/vh/video-web/test.yaml
See [VIH-10983](https://tools.hmcts.net/jira/browse/VIH-10983)
Creates new test image policy for all VH apps to use in test env config.
- Updated `image-policy.yaml` files for `vh-admin-web`, `vh-booking-queue-subscriber`, `vh-bookings-api`, `vh-notification-api`, `vh-scheduler-jobs`, `vh-user-api`, `vh-video-api`, and `vh-video-web` to add a new test policy with disabled prod-automated annotations and filterTags pattern.
- Updated `test.yaml` files for `vh-admin-web`, `vh-booking-queue-subscriber`, `vh-bookings-api`, `vh-notification-api`, `vh-scheduler-jobs`, `vh-user-api`, `vh-video-api`, and `vh-video-web` to update the dev image versions.
> VIH-10983 set Test env to use test image policy

- apps/jenkins/jenkins/ptl/jenkins.yaml
Before removing 01 from appgw for the AKS upgrade
- Updated the value of \"STG_AKS_CLUSTER_NAME\" from \"ss-stg-01-aks\" to \"ss-stg-00-aks\"
- Updated the value of \"STG_AKS_RESOURCE_GROUP\" from \"ss-stg-01-rg\" to \"ss-stg-00-rg\"
> Point jenkins to stg00 whilst upgrading 01

- apps/pip/account-management/test.yaml
- apps/pip/data-management/test.yaml
- apps/pip/frontend/test.yaml
- apps/pip/publication-services/test.yaml
- apps/pip/subscription-management/test.yaml
- Added configuration for `cpu` and `memory` with both enabled and an averageUtilization of 40.
- Added configuration for `cpu` and `memory` with both enabled and an averageUtilization of 40.
- Added configuration for `cpu` and `memory` with both enabled and an averageUtilization of 40.
- Added configuration for `cpu` and `memory` with both enabled and an averageUtilization of 40.
- Added configuration for `cpu` and `memory` with both enabled and an averageUtilization of 40.
> PUB-1692 - Update reference name for autoscaling config

- apps/juror/juror-scheduler-execution/ithc.yaml
This reverts commit dc2f96fa199db9ea4c786030e6d6801b025bf42a.
md
- The file `apps/juror/juror-scheduler-execution/ithc.yaml` has had the environment section removed from the spec.
```
> juror: Revert "break bais connection (#5541)"

- apps/pip/frontend/test.yaml
https://tools.hmcts.net/jira/browse/PUB-2618
Removed test image following testing
- Removed a line that specified the number of replicas for the frontend service.
- Updated the image for the frontend service to `sdshmctspublic.azurecr.io/pip/frontend:pr-1363-9aebad8-20241010110422`.
- Updated the ingress host to `pip-frontend.test.platform.hmcts.net`.
> PUB-2618 - Removed test image

- apps/jenkins/jenkins/ptl/jenkins-azure-vm-agent.yaml
See [DTSPO-19360](https://tools.hmcts.net/jira/browse/DTSPO-19360)
Jenkins agents on SDS are limited to 10 which has been a bottleneck this past few days.
I've noticed it in some testing but it's now being reported by users.
- File: `apps/jenkins/jenkins/ptl/jenkins-azure-vm-agent.yaml`
- Changed `maxVirtualMachinesLimit` from 10 to 20.
> DTSPO-19360 - Increase max limit on ptl agents

- apps/pre/pre-api/prod.yaml
- apps/pre/pre-portal/prod.yaml
- apps/pre/prod/base/kustomization.yaml
- Removed the `MEDIA_SERVICE` configuration
- Updated `PLATFORM_ENV_TAG` to \"Production\"
- Removed the `USE_MK_ON_WATCH_PAGE` configuration
- Removed references to `pre-api-cron-cleanup-live-events` and `pre-api-cron-cleanup-streaming-locators` resource files
> Revert PRE prod to AMS again

- apps/vh/video-api/prod.yaml
- apps/vh/video-api/stg.yaml
VIH-10931
Override the format for the callbackuri environment variable for Vodafone to match Kinly:
Environment configuration updates:
* [`apps/vh/video-api/prod.yaml`](diffhunk://#diff-a9c387e26e5cdb7afee0202a7c64118a1e323c0ea3e67dea0987743d359ae42dR14): Added `VODAFONECONFIGURATION__CALLBACKURI` with the value `https://video.hearings.reform.hmcts.net/callback`.
* [`apps/vh/video-api/stg.yaml`](diffhunk://#diff-a8a073ea69efce17136197c7a278350c66caf54d961799438c7c6be459d9a5dcR14): Added `VODAFONECONFIGURATION__CALLBACKURI` with the value `https://video.staging.hearings.reform.hmcts.net/callback`.
- Added VODAFONECONFIGURATION__CALLBACKURI with URL for production environment.ℹ️
- Added VODAFONECONFIGURATION__CALLBACKURI with URL for staging environment.ℹ️
> VIH-10931 override the format for the callbackuri environment variable for Vodafone to match Kinly

- apps/darts-modernisation/darts-api/demo.yaml
- apps/darts-modernisation/darts-api/prod.yaml
- apps/darts-modernisation/darts-automated-tasks/demo.yaml
- apps/darts-modernisation/darts-automated-tasks/prod.yaml
Updated ARM_RPO_HOURS to be ARM_RPO_DURATION to better reflect object
- `demo.yaml`:
- Updated the `ARM_RPO_HOURS` field to `ARM_RPO_DURATION` with a value of `24h`.
- `prod.yaml`:
- Updated the `ARM_RPO_HOURS` field to `ARM_RPO_DURATION` with a value of `24h`.
- `darts-automated-tasks/demo.yaml`:
- Updated the `ARM_RPO_HOURS` field to `ARM_RPO_DURATION` with a value of `24h`.
- `darts-automated-tasks/prod.yaml`:
- Updated the `ARM_RPO_HOURS` field to `ARM_RPO_DURATION` with a value of `24h`.
> Updated ARM_RPO_HOURS to be ARM_RPO_DURATION to better reflect object

- apps/monitoring/vm-hourlyusage/fiveminuteusage.yaml
- apps/monitoring/vm-hourlyusage/hourlyusage.yaml
- apps/monitoring/vm-hourlyusage/kustomization.yaml
No Jira for this as Felix contacted directly on the Slack. 
David Fielding asked to change the frequency of this report from being hourly to run every 5 minutes.
- Created a new file `fiveminuteusage.yaml` in the `apps/monitoring/vm-hourlyusage` directory.
- Defined a HelmRelease resource for `vm-fiveminuteusage` with various specifications including chart, schedule, image, environment variables, and nodeSelector.
- Updated `kustomization.yaml` to include the newly created `fiveminuteusage.yaml` file.
> Change hourly report to run every 5 minutes

- apps/pre/pre-portal/stg.yaml
- `stg.yaml` 🔄
- Changed `ENABLE_MK_WATCH_PAGE` to `USE_MK_ON_WATCH_PAGE`
- Updated the `PRE_API_URL` and `PORTAL_URL` to staging URLs.
- Updated the `B2C_APP_CLIENT_ID`.
- Updated the `DYNATRACE_JSTAG`.
- `TRIGGER` was changed to `init-1`.
> PRE STG default to mk

- apps/admin/aad-pod-identity/sbox/azure-identity-auto-cluster-01.yaml
- apps/admin/sbox/01/kustomization.yaml
[DTSPO-19027](https://tools.hmcts.net/jira/browse/DTSPO-19027)
I am unable to setup auto cluster (ss-sbox-01-aks) with user assigned identity, so need to add the system assigned identity to allow the auto cluster access to the sop key for flux
- Created new file `azure-identity-auto-cluster-01.yaml` under `apps/admin/aad-pod-identity/sbox` with operations to replace `resourceID` and `clientID` values.
- Updated `kustomization.yaml` in `apps/admin/sbox/01` to include a new patch for `azure-identity-auto-cluster-01.yaml` targeting `group: aadpodidentity.k8s.io`, `kind: AzureIdentity`, `name: aks-pod-identity-mi`, `version: v1`.
> DTSPO-19027 adding auto cluster system identity to flux config

- apps/admin/aad-pod-identity/sbox/azure-identity-auto-cluster-01.yaml
- apps/admin/sbox/01/kustomization.yaml
Reverts hmcts/sds-flux-config#5690
- The file `azure-identity-auto-cluster-01.yaml` has been deleted.
- In the `kustomization.yaml` file, the reference to the deleted `azure-identity-auto-cluster-01.yaml` file has been removed.
> Revert "DTSPO-19027 adding auto cluster system identity to flux config"

- apps/admin/aad-pod-identity/sbox/azure-identity-auto-cluster-01.yaml
- apps/admin/sbox/01/kustomization.yaml
- apps/flux-system/sbox/01/kustomize.yaml
[DTSPO-19027](https://tools.hmcts.net/jira/browse/DTSPO-19027)
I am unable to setup auto cluster (ss-sbox-01-aks) with user assigned identity, so need to add the system assigned identity to allow the auto cluster access to the sop key for flux
- 📄 Created a new file named azure-identity-auto-cluster-01.yaml.
- Replaced the /spec/resourceID and /spec/clientID values.
- Updated the kustomization.yaml file to include the azure-identity-auto-cluster-01.yaml as a resource and added target information.
- Updated the ISSUER_URL value in the kustomize.yaml file.
> adding auto cluster system identity to flux config

- apps/monitoring/vm-hourlyusage/fiveminuteusage.yaml
- apps/monitoring/vm-hourlyusage/hourlyusage.yaml
- apps/monitoring/vm-hourlyusage/image-repo.yaml
Updating image location as it has been updated here - 
https://github.com/hmcts/version-reporter-services/pull/146/files#diff-9eedc1d7d657ddb36b1105a0fffb4852f6d34e26454371f27b6e0ad1391f290eR31 
- `fiveminuteusage.yaml` 🛠️: Updated the image repository for the cron job to use the new image from `hmctspublic.azurecr.io`.
- `hourlyusage.yaml` 🛠️: Updated the image repository for the cron job to use the new image from `hmctspublic.azurecr.io`.
- `image-repo.yaml` 🛠️: Updated the image repository to use the new image from `hmctspublic.azurecr.io`.
> Updating image location as its updated upstream

- apps/dynatrace/dynatrace-operator.yaml
- apps/monitoring/vm-hourlyusage/fiveminuteusage.yaml
Trying to fix this errors on SDS.  This may allow csi pods to to schedule on the cronjobs nodes
`MountVolume.SetUp failed for volume "oneagent-bin" : kubernetes.io/csi: mounter.SetUpAt failed to get CSI client: driver name csi.oneagent.dynatrace.com not found in the list of registered CSI drivers`
- `apps/dynatrace/dynatrace-operator.yaml` 🛠️
- Added a new nodeSelector rule for the key `dedicated` with the operator `Equal` and value `jobs`.
- `apps/monitoring/vm-hourlyusage/fiveminuteusage.yaml` 🛠️
- Updated the nodeSelector rule from `agentpool: cronjob` to `kubernetes.io/os: linux`.
- Tolerations now include a rule with the key `dedicated` and effect `NoSchedule`.
> Allow dynatrace csidriver onto cronjob nodes

- apps/admin/traefik2/demo/00-traefik2.yaml
- apps/admin/traefik2/demo/01-traefik2.yaml
- apps/admin/traefik2/dev/00-traefik2.yaml
- apps/admin/traefik2/dev/01-traefik2.yaml
- apps/admin/traefik2/ithc/00-traefik2.yaml
- apps/admin/traefik2/ithc/01-traefik2.yaml
- apps/admin/traefik2/ptlsbox/00-traefik.yaml
- apps/admin/traefik2/stg/00-traefik2.yaml
- apps/admin/traefik2/stg/01-traefik2.yaml
- apps/admin/traefik2/test/00-traefik2.yaml
- apps/admin/traefik2/test/01-traefik2.yaml
- clusters/demo/base/kustomization.yaml
- clusters/dev/base/kustomization.yaml
- clusters/ithc/base/kustomization.yaml
- clusters/ptlsbox/base/kustomization.yaml
- clusters/stg/base/kustomization.yaml
- clusters/test/base/kustomization.yaml
Successful upgrade in sbox
Moving onto all nonprod 
- Updated the Helm chart version to 33.0.0 and specified the Helm repository for the traefik2 application in multiple demo, dev, ithc, ptlsbox, stg, and test environments in the corresponding YAML files. 📦
- Added the path to the `traefik-v33-crds/kustomize.yaml` in the kustomization.yaml file for dev, ithc, ptlsbox, stg, and test environments. 🛠️
> Upgrade all nonprod traefik

- apps/monitoring/automation/kustomization.yaml
- apps/monitoring/cveinfo/cveinfo.yaml
- apps/monitoring/cveinfo/image-policy.yaml
- apps/monitoring/cveinfo/image-repo.yaml
- apps/monitoring/cveinfo/kustomization.yaml
- apps/monitoring/cveinfo/rbac.yaml
- apps/monitoring/ptl/base/kustomization.yaml
Off the back of the vulnerability calls, the idea of this repo is to run a cron job that will pull in cveinfo from the [cveproject](https://github.com/CVEProject) repository, summarised and store in the cosmosdb for reports.
This can them be used in many ways to enhance reports or easy access to current cves. Ideas around enhancing the vulnerably reports and using the info to facilitate conversation are hoped to be end results of how the data is consumed.
The data is free for public use, no licence required.
The job will run every 4 hours in the weekday to keep data up-to-date. image build in the [version reporter service](https://github.com/hmcts/version-reporter-services) repo 
- In `apps/monitoring/automation/kustomization.yaml`, a new resource `./cveinfo/image-policy.yaml` was added. …
> Setting up job to run on cluster for cveinfo

- apps/darts-modernisation/darts-ucf-test-harness/test.yaml
Removed replacers on UCF test harness for darts
- Changed the number of replicas from 25 to 0 for the Java service.
- Updated the ingress host to darts-ucf-test-harness.test.platform.hmcts.net.
- Modified the environment variable DARTS_LOG_LEVEL to DEBUG.
> Removed replacers on UCF test harness for darts

- apps/flux-system/base/hmctspublic-ocirepo.yaml
- apps/flux-system/base/kustomization.yaml
See [DTSPO-22647](https://tools.hmcts.net/jira/browse/DTSPO-22647)
Adding oci repo for future use
md
- Added new file apps/flux-system/base/hmctspublic-ocirepo.yaml
- Defines a Helm repository for hmctspublic-oci with a specified URL and interval
- Modified apps/flux-system/base/kustomization.yaml
- Added hmctspublic-ocirepo.yaml to the list of resources
```
> DTSPO-22647 - Add oci repo

- apps/dynatrace/dynatrace-crds/kustomization.yaml
- apps/dynatrace/dynatrace-operator.yaml
https://tools.hmcts.net/jira/browse/DTSPO-22277
Patch dynatrace operator to 1.3.2
- Updated `kustomization.yaml`: Updated the URL for Dynatrace Operator CRD from v1.2.2 to v1.3.2.
- Updated `dynatrace-operator.yaml`: Updated the version of Dynatrace Operator from 1.2.2 to 1.3.2.
> Patch dynatrace operator

- apps/pip/frontend/test.yaml
- apps/pip/subscription-management/test.yaml
Reverts hmcts/sds-flux-config#5841
- `test.yaml`:
- Removed the `image` field from `pip-frontend` and `pip-subscription-management` services.
> Revert "PUB-2682 deploy list type subscription"

- apps/keda/dev/base/workload-identity.yaml
Updating Keda dev deployment to use stg MI and not AAT MI (wrong platform)
- Updated the `client-id` annotation for azure workload identity from \"d7a2a92e-63ba-4ee3-b8fb-9680afee622f\" to \"8469c7cb-7be4-46c7-a76b-74674726520e\".
> Updating Keda dev deployment to use stg MI and not AAT MI (wrong platform)

- README.md
- apps/jenkins/jenkins/ptlsbox/disk.yaml
- File: apps/jenkins/jenkins/ptlsbox/disk.yaml
- Updated the diskName from \"sds-jenkins-ptlsbox-disk\" to \"sds-jenkins-ptlsbox-disk-standard\"
- Updated the diskURI accordingly
> Ops/dtspo 22513/sds jenkins

- apps/jenkins/jenkins/jenkins-controller-version.yaml
- apps/jenkins/jenkins/ptlsbox/jenkins-controller-version.yaml
https://tools.hmcts.net/jira/browse/DTSPO-23036
- new image without upgrade to azure-vm-agents plugin to fix jenkins agent pools
- Updated Jenkins controller version from 2.491-828 to 2.491-829.
- Updated Jenkins controller version from 2.491-828 to 2.491-829.
> DTSPO-23036: fix jenkins controller image

- apps/toffee/dev/base/kustomization.yaml
- apps/toffee/dev/sops-secrets/kustomization.yaml
- apps/toffee/dev/sops-secrets/recipe-backend-values.enc.yaml
DTSPO-18332 
test changes to script
- Updated `kustomization.yaml` in `apps/toffee/dev/base`: Added new resources for flexibleserver-postgres and flexibleserver-postgres-config, removed sops-secrets from resources list.
- Updated `kustomization.yaml` in `apps/toffee/dev/sops-secrets`: Removed resources for flexibleserver-postgres, flexibleserver-postgres-config, and recipe-backend-postgres.enc.yaml, added resource for recipe-backend-values.enc.yaml, and updated the PASSWORD field in recipe-backend-values.enc.yaml.
- Updated `recipe-backend-values.enc.yaml` in `apps/toffee/dev/sops-secrets`: Updated the encryption and modification details for the PASSWORD field.
> DTSPO-18332 - test changes to script

- apps/toffee/dev/base/kustomization.yaml
- apps/toffee/dev/sops-secrets/recipe-backend-values.enc.yaml
DTSPO-18332
Test changes of script: adding aso folder as a patch in kustomization
- The `kustomization.yaml` file in the `apps/toffee/dev/base` directory has been modified to add a new patch at path `./aso/toffee-postgres.yaml` and remove `./././base/workload-identity` and `./././identity/toffee-azure-identity.yaml` from the resources.
- The `recipe-backend-values.enc.yaml` file in the `apps/toffee/dev/sops-secrets` directory has been updated with a new `PASSWORD` value and changes in `created_at` and `enc` fields for the secret data.
> DTSPO-18332 - test changes of script: adding aso folder as a patch in kustomization

- apps/toffee/frontend/sbox.yaml
Set to Paris time as a test
- Tested locally on toffee container, only POSIX format works. Did try `Europe/Paris` with no success
TLDR: This is for a quick fix for a pod to be GMT / UK time. I dont want to spend much time on updating a base image or such. 
- Added a new environment variable \"TZ\" with value \"CET-1CEST,M3.5.0,M10.5.0/3\"
> Set to Paris time as a test

- apps/toffee/frontend/sbox.yaml
Reverts hmcts/sds-flux-config#5949
PR works fine, back to normal
- Removed `TZ: CET-1CEST,M3.5.0,M10.5.0/3` from the file.
> Revert "Set to Paris time as a test"

- apps/toffee/dev/aso/toffee-postgres.yaml
- apps/toffee/dev/base/kustomization.yaml
- apps/toffee/dev/sops-secrets/kustomization.yaml
- apps/toffee/dev/sops-secrets/recipe-backend-values.enc.yaml
DTSPO-18332
Test script after some additional cleanup steps and terminal output
- Created file: `apps/toffee/dev/aso/toffee-postgres.yaml` 🆕
- Defines a FlexibleServer instance for PostgreSQL with specific version and SKU settings.
- Updated file: `apps/toffee/dev/base/kustomization.yaml`
- Added resources for Azure Service Operator to handle FlexibleServer PostgreSQL.
- Created file: `apps/toffee/dev/sops-secrets/kustomization.yaml` 🆕
- Defines a Kustomization to handle secrets encryption for PostgreSQL.
- Created file: `apps/toffee/dev/sops-secrets/recipe-backend-values.enc.yaml` 🆕
- Defines an encrypted Secret for PostgreSQL, including encryption details.
> DTSPO-18332 - Test script after some additional cleanup steps and terminal output

- bin/v2/postgres-setup.sh
DTSPO-18332
Create a script to automate and simplify onboarding to persistent preview databases
Tested when merged [PR-5953](https://github.com/hmcts/sds-flux-config/pull/5953)
Created flexible server and resource group containing it: [toffee-dev flexible server](https://portal.azure.com/#@HMCTS.NET/resource/subscriptions/74dacd4f-a248-45bb-a2f0-af700dc4cf68/resourceGroups/toffee-aso-dev-rg/providers/Microsoft.DBforPostgreSQL/flexibleServers/toffee-dev/overview)
- Added a new script `postgres-setup.sh` in the `bin/v2` directory to set up a PostgreSQL instance for a given namespace and app.
- The script creates configuration files for the PostgreSQL instance and encrypts sensitive values using `sops`.
- It also updates the kustomization in `dev/base` with new resources and patches if …
> DTSPO-18332 - Simplify onboarding to persistent preview databases

- Docs/aso-setup-v2.md
- bin/v2/add-postgres-server.sh
DTSPO-18332
- Rename postgres-setup.sh to 'add-postgres-server.sh'
- Update references to script ^^
- Include example output from script in documentation
N/A
- Updated the documentation to mention running [add-postgres-server.sh](./bin/v2/add-postgres-server.sh) instead of [postgres-setup.sh](./bin/v2/postgres-setup.sh) for setting up the Postgres server.
- Added a note to refer to a PR for expected output of the script.
- File renamed from `postgres-setup.sh` to `add-postgres-server.sh`.
- Updated the usage function to reflect the new filename `add-postgres-server.sh`.
> DTSPO-18332 - Rename aso postgres server script and update documentation

- apps/darts-modernisation/darts-ucf-test-harness/test.yaml
Changes to TEST_HARNESS_PROXY_URL from proxy to gateway and adding 1 to replicas to start the test running
- Updated `test.yaml`
- Changed the number of replicas from 0 to 1 for the `java` service
- Updated `TEST_HARNESS_PROXY_URL` to use `darts-gateway` instead of `darts-proxy`
> Changes to TEST_HARNESS_PROXY_URL from proxy to gateway and adding 1

- apps/jenkins/jenkins/ptl/jenkins-azure-vm-agent.yaml
- apps/jenkins/jenkins/ptlsbox/jenkins-azure-vm-agent.yaml
- Reverting to previous Jenkins image to unblock pipelines
- `apps/jenkins/jenkins/ptl/jenkins-azure-vm-agent.yaml`
- Updated `galleryImageVersion` from \"24.0.0\" to \"1.4.220\" for `jenkins-ubuntu` image.
- `apps/jenkins/jenkins/ptlsbox/jenkins-azure-vm-agent.yaml`
- Updated `galleryImageVersion` from \"24.0.0\" to \"1.4.220\" for `jenkins-ubuntu` image.
> Revert to previous Jenkins image

- apps/admin/traefik-crds-upgrade-v34/kustomization.yaml
- apps/admin/traefik-crds-upgrade-v34/kustomize.yaml
- apps/admin/traefik2/ptlsbox/00-traefik.yaml
- apps/admin/traefik2/sbox/00-traefik2.yaml
- apps/admin/traefik2/sbox/01-traefik2.yaml
- clusters/ptlsbox/base/kustomization.yaml
- clusters/sbox/base/kustomization.yaml
https://tools.hmcts.net/jira/browse/DTSPO-23720
- Patching Traefik to v34.2.0 on sbox and ptlsbox
- Added a new file \"apps/admin/traefik-crds-upgrade-v34/kustomization.yaml\" which includes references to multiple CRDs related to Traefik.
- Added a new file \"apps/admin/traefik-crds-upgrade-v34/kustomize.yaml\" with specification for traefik-crd.
- Updated \"apps/admin/traefik2/ptlsbox/00-traefik.yaml\" to use chart version 34.2.0 from HelmRepository.
- Updated \"apps/admin/traefik2/sbox/00-traefik2.yaml\" to use chart version 34.2.0 from HelmRepository.
- Updated \"apps/admin/traefik2/sbox/01-traefik2.yaml\" to use chart version 34.2.0 from HelmRepository.
- Updated \"clusters/ptlsbox/base/kustomization.yaml\" to add path \"./././apps/admin/traefik-crds-upgrade-v34/kustomize.yaml\".
- …
> DTSPO 23720 - Patching Traefik to v34.2.0 on sbox and ptlsbox

- apps/admin/traefik2/demo/00-traefik2.yaml
- apps/admin/traefik2/demo/01-traefik2.yaml
- apps/admin/traefik2/dev/00-traefik2.yaml
- apps/admin/traefik2/dev/01-traefik2.yaml
- apps/admin/traefik2/ithc/00-traefik2.yaml
- apps/admin/traefik2/ithc/01-traefik2.yaml
- apps/admin/traefik2/stg/00-traefik2.yaml
- apps/admin/traefik2/stg/01-traefik2.yaml
- apps/admin/traefik2/test/00-traefik2.yaml
- apps/admin/traefik2/test/01-traefik2.yaml
- clusters/demo/base/kustomization.yaml
- clusters/dev/base/kustomization.yaml
- clusters/ithc/base/kustomization.yaml
- clusters/stg/base/kustomization.yaml
- clusters/test/base/kustomization.yaml
https://tools.hmcts.net/jira/browse/DTSPO-23720
- Patching Traefik to v34.2.0 on non-prod
- Updated traefik chart to version 34.2.0 in various environment specific YAML files (`00-traefik2.yaml` and `01-traefik2.yaml`)
- Updated kustomization.yaml files in different environment folders to include `traefik-crds-upgrade-v34/kustomize.yaml` file for traefik-crds upgrade.
> DTSPO 23720 - Patching Traefik to v34.2.0 on non-prod

- apps/darts-modernisation/darts-ucf-test-harness/test.yaml
Turning on the test harness by adding 10 replicas
- Increased the number of replicas for the `java` service from 0 to 10.
- Set the `DARTS_LOG_LEVEL` environment variable to `DEBUG`.
> Turning on the test harness

- apps/darts-modernisation/darts-ucf-test-harness/test.yaml
Turning off the Test Harness
- Changed replicas from 10 to 0 for the Java service in the darts-ucf-test-harness deployment.
> Turning off the Test Harness

- apps/met/themis-fe/test.yaml
Set to Paris time as a test
Tested locally on toffee container, only POSIX format works. Did try Europe/Paris with no success
TLDR: This is for a quick fix for a pod to be GMT / UK time. I dont want to spend much time on updating a base image or such.
tested fine previous on test app - https://github.com/hmcts/sds-flux-config/pull/5949
- Added `TZ: CET-1CEST,M3.5.0,M10.5.0/3` to the environment variables for the Themis Frontend service. 🕒
> testing with Paris timezone

- apps/met/themis-fe/test.yaml
switch volumes to separate values
- `test.yaml`: 
- Added a new volume `tz-config` with a `hostPath` pointing to `/usr/share/zoneinfo/Europe/Paris`.
- Removed the duplicate `volumes` section.
- Updated the configuration for `nodejs` and `volumeMounts`.
- Updated `keyVaults` configuration, removing the `volumes` section and adding `excludeEnvironmentSuffix` property.
> switch volumes to separate values

- apps/admin/traefik2/ptl/00-traefik.yaml
- clusters/ptl/base/kustomization.yaml
https://tools.hmcts.net/jira/browse/DTSPO-23725
Patching Traefik to v34.2.0 on ptl
- Updated 00-traefik.yaml``` in ```apps/admin/traefik2/ptl```:
- Added a new version of the Traefik chart (34.2.0) sourced from the Helm repository.
- Updated ```kustomization.yaml``` in ```clusters/ptl/base```:
- Added a new path for ```./././apps/admin/traefik-crds-upgrade-v34/kustomize.yaml```
> DTSPO-23725 - Patching ptl traefik to 34.2.0

- apps/darts-modernisation/darts-api/image-policy-pr.yaml
- apps/darts-modernisation/darts-api/test.yaml
Image policy update
- Added a new file `image-policy-pr.yaml` with an `ImagePolicy` resource to specify image filtering and ordering for the `darts-api` application.
- Updated the `test.yaml` file to include a new image reference for the `darts-api` application pointing to `sdshmctspublic.azurecr.io/darts/api:pr-2568-ef9148d-20250210170553`.
> Image policy update

- apps/pre/pre-api/demo.yaml
- apps/pre/pre-api/prod.yaml
- apps/pre/pre-api/stg.yaml
- apps/pre/pre-api/test.yaml
See [S28-3667](https://tools.hmcts.net/jira/browse/S28-3667)
Add feature toggle for create streaming locator on start feature. Enabled in stg, disabled elsewhere
- Added `ENABLE_STREAMING_LOCATOR_ON_START: false` to the configuration for the `MediaKind` service in the demo environment.
- Added `ENABLE_STREAMING_LOCATOR_ON_START: false` to the configuration for the `MediaKind` service in the production environment.
- Added `ENABLE_STREAMING_LOCATOR_ON_START: true` to the configuration for the `MediaKind` service in the staging environment.
- Added `ENABLE_STREAMING_LOCATOR_ON_START: false` to the configuration for the `MediaKind` service in the testing environment.
> PRE API Feature Toggle: Create Streaming Locator on Start 

- apps/jenkins/jenkins/ptl/jenkins.yaml
- Added configuration for a new dashboard \"List Assist\" under the \"buildMonitor\" section.
> Add list assist dashboard

- apps/darts-modernisation/darts-api/test.yaml
- The `test.yaml` file in `darts-modernisation/darts-api` has been modified.
- The `image` value has been updated to point to a new image: `sdshmctspublic.azurecr.io/darts/api:pr-2568-f9f2007-20250211125721`.
- An `environment` block has been added with two key-value pairs: `DARTS_GATEWAY_URL: http://darts-gateway.test.platform.hmcts.net` and `DARTS_LOG_LEVEL: DEBUG`.
> Removed branch lock from test

- apps/dynatrace/dynatrace-crds/kustomization.yaml
- apps/dynatrace/dynatrace-operator.yaml
https://tools.hmcts.net/jira/browse/DTSPO-23727
Patch dynatrace one agent to v 1.4.1
- **apps/dynatrace/dynatrace-crds/kustomization.yaml**
- Updated the URL for Dynatrace Operator CRD from v1.3.2 to v1.4.1.
- **apps/dynatrace/dynatrace-operator.yaml**
- Updated the version of the Dynatrace Operator from 1.3.2 to 1.4.1.
> Patch dynatrace one agent

- apps/monitoring/kube-prometheus-stack-crds/kustomization.yaml
- apps/monitoring/kube-prometheus-stack/kube-prometheus-stack.yaml
https://tools.hmcts.net/jira/browse/DTSPO-23730
Patching kube prometheus stack to 69.3.1
- Updated `kube-prometheus-stack-crds/kustomization.yaml` to use version 69.3.1 of the kube-prometheus-stack Helm charts instead of version 66.2.1, and updated the corresponding CRD resources.
- In `kube-prometheus-stack/kube-prometheus-stack.yaml`, the Helm chart version has been updated from 66.2.1 to 69.3.1.
> Patching kube prometheus stack to 69.3.1

- apps/dynatrace/dynatrace-crds/kustomization.yaml
- apps/dynatrace/dynatrace-operator.yaml
Reverts hmcts/sds-flux-config#6135
- The source URL for the Dynatrace operator custom resource definition (CRD) has been downgraded from v1.4.1 to v1.3.2.
- The version of the Dynatrace operator has been downgraded from 1.4.1 to 1.3.2.
> Revert "Patch dynatrace one agent"

- clusters/test/base/kustomization.yaml
https://tools.hmcts.net/jira/browse/DTSPO-23727
Remove dynatrace from test clusters to fully remove then will re add to troubleshoot issues
- Replaced the reference to `apps/dynatrace` with `apps/mi` in the resources list.
> Remove dynatrace from test clusters

- clusters/test/base/kustomization.yaml
Put dynatrace back onto test clusters
Reverts hmcts/sds-flux-config#6151
- **kustomization.yaml**
- Added a reference to the `dynatrace` application kustomization file.
> Revert "Remove dynatrace from test clusters"

- apps/darts-modernisation/darts-ucf-test-harness/test.yaml
Turning on the Test Harness for 20 instances
- Changed the number of replicas from 0 to 10.
- Updated the value of ingressHost to \"darts-ucf-test-harness.test.platform.hmcts.net\".
- Set environment variable DARTS_LOG_LEVEL to \"DEBUG\".
> Turning on the Test Harness for 20 instances

- apps/darts-modernisation/darts-ucf-test-harness/test.yaml
Turning Test Harness on with 20
- Updated the number of replicas from 0 to 10 for the Java component.
- Changed the value of ingressHost to \"darts-ucf-test-harness.test.platform.hmcts.net\".
- Set the environment variable DARTS_LOG_LEVEL to \"DEBUG\".
> Turning Test Harness on with 20

- clusters/test/base/kustomization.yaml
https://tools.hmcts.net/jira/browse/DTSPO-23727
Removing dynatrace agent from test, will clean env of deployment then do clean install of new version
The file `clusters/test/base/kustomization.yaml` has been modified. The change involves replacing the path to `apps/dynatrace/base/kustomize.yaml` with the path to `apps/mi/base/kustomize.yaml`.
> Remove dynatrace from test env

- apps/darts-modernisation/darts-ucf-test-harness/test.yaml
Turning off Test Harness
- Changed the number of replicas from 10 to 0 for the `darts-ucf-test-harness` service.
- Modified the `DARTS_LOG_LEVEL` environment variable to `DEBUG`.
> Turning off Test Harness

- apps/darts-modernisation/darts-ucf-test-harness/test.yaml
Turning 50 instances on for the test harness
- Updated the `replicas` value from 0 to 25 for the `java` service.
- Set the `DARTS_LOG_LEVEL` environment variable to `DEBUG`.
> Turning 50 instances on for the test harness

- apps/darts-modernisation/darts-ucf-test-harness/test.yaml
Turn off Test harness
- Reduced the number of replicas for the `java` service from 25 to 0.
> Turn off Test harness

- apps/darts-modernisation/darts-ucf-test-harness/test.yaml
Turning on 70 instances
- Increased the number of replicas for the Java service from 0 to 70.
- Modified the environment variable `DARTS_LOG_LEVEL` to `DEBUG`.
> Turning on 70 instances

- apps/juror/juror-api/ithc.yaml
- apps/juror/juror-bureau/ithc.yaml
[JS-280](https://tools.hmcts.net/jira/browse/JS-280)
deployment of JS-280 for testing
Deployment for testing in ITHC only
- Updated the image version to `pr-876-1c91eb3-20250226121104` for the `java` container.
- Updated the image version to `pr-899-edd1399-20250224164846` for the `nodejs` container.
> juror deployments for JS-280

- apps/darts-modernisation/darts-ucf-test-harness/test.yaml
Turn off instances of test harness
- Changed the number of replicas for the \"java\" service from 70 to 0
- Updated the \"ingressHost\" to darts-ucf-test-harness.test.platform.hmcts.net
> Turn off instances of test harness

- apps/darts-modernisation/darts-ucf-test-harness/test.yaml
Turn 35 replicas on for 70 instances
- Increased the number of replicas for the `java` service from 0 to 35.
- Set the `DARTS_LOG_LEVEL` environment variable to `DEBUG`.
> Turn 35 replicas on for 70 instances

- apps/darts-modernisation/darts-ucf-test-harness/test.yaml
Turning off 100 instances
- Reduced the number of replicas for the `java` service from 50 to 0.
- Set the environment variable `DARTS_LOG_LEVEL` to `DEBUG`.
> Turning off 100 instances

- apps/darts-modernisation/automation/kustomization.yaml
- apps/darts-modernisation/base/kustomization.yaml
- apps/darts-modernisation/darts-external-component-test-harness/darts-external-component-test-harness.yaml
- apps/darts-modernisation/darts-external-component-test-harness/demo.yaml
- apps/darts-modernisation/darts-external-component-test-harness/image-policy.yaml
- apps/darts-modernisation/darts-external-component-test-harness/image-repo.yaml
- apps/darts-modernisation/darts-external-component-test-harness/stg.yaml
- apps/darts-modernisation/darts-external-component-test-harness/test.yaml
- apps/darts-modernisation/demo/base/kustomization.yaml
- apps/darts-modernisation/stg/base/kustomization.yaml
- apps/darts-modernisation/test/base/kustomization.yaml
Rename the DARTS UCF test harness to DARTS External Component test harness. 
A further PR will follow to remove the UCF references once this one is up and running. 
> DMP-4488 Clone darts test harness for rename

- apps/darts-modernisation/darts-external-component-test-harness/test.yaml
Turning on the test for 100 instances
- Updated the number of replicas for the \"java\" service from 0 to 50.
- Updated the \"ingressHost\" to \"darts-external-component-test-harness.test.platform.hmcts.net\".
- Set the environment variable \"DARTS_LOG_LEVEL\" to \"DEBUG\".
> Turning on the test for 100 instances

- apps/darts-modernisation/darts-api/demo.yaml
- apps/opal/automation/kustomization.yaml
- apps/opal/opal-frontend-test/image-policy.yaml
- apps/opal/opal-frontend-test/image-repo.yaml
- apps/opal/opal-frontend-test/opal-frontend-test.yaml
- apps/opal/opal-frontend-test/stg.yaml
- apps/opal/stg/base/kustomization.yaml
[PO-1288](https://tools.hmcts.net/jira/browse/PO-1288)
- As part of PO-1288 we want to spin up another instance of the opal-frontend staging environment with a new url to test the cookie being exchanged between the two instances
N/A
- Modified `apps/opal/automation/kustomization.yaml`:
- Added references to image repository and image policy for opal-frontend-test.
- Added `apps/opal/opal-frontend-test/image-policy.yaml`:
- Defined image policy for opal-frontend-test.
- Added `apps/opal/opal-frontend-test/image-repo.yaml`:
- Defined image repository for opal-frontend-test.
- Added `apps/opal/opal-frontend-test/opal-frontend-test.yaml`:
- Added helm release configuration for opal-frontend-test with specified image.
- Added `apps/opal/opal-frontend-test/stg.yaml`:
- Defined helm release …
> PO-1288: Add opal-frontend-test

- apps/darts-modernisation/darts-external-component-test-harness/test.yaml
Turning off test harness.
- Reduced the number of replicas to 0 for the `darts-external-component-test-harness` service.
- Updated the `DARTS_LOG_LEVEL` environment variable to `DEBUG`.
> Turning off test harness.

- apps/darts-modernisation/darts-external-component-test-harness/test.yaml
Turning on the test harness for 120
- Changed replicas value from 0 to 60 for the java component.
- Updated the ingress host to darts-external-component-test-harness.test.platform.hmcts.net.
- Set the environment DARTS_LOG_LEVEL to DEBUG.
> Turning on the test harness for 120

- apps/flux-system/ithc/base/kustomization.yaml
- apps/flux-system/serviceaccount/ithc.yaml
- Changes should only affect ithc.
- Adding workload-identity to ithc as done and working in cnp-flux-config.
- Added to sbox in [this PR](https://github.com/hmcts/sds-flux-config/pull/6273)
- Added a new workload-identity patch.
- Added a new service account patch for ithc.
- Added a reference to git-credentials.enc.yaml.
- Created a new file for ServiceAccount ithc.
- Includes metadata for name, namespace, annotations, and labels.
> DTSPO-24310: Adding workload identity to ithc

- apps/flux-system/demo/base/kustomization.yaml
- apps/flux-system/dev/base/kustomization.yaml
- apps/flux-system/ithc/base/kustomization.yaml
- apps/flux-system/stg/base/kustomization.yaml
- apps/flux-system/test/base/kustomization.yaml
- Upgrade Flux to 2.5.1 for nonprod
- `apps/flux-system/demo/base/kustomization.yaml`
- Replaced `gotk-components.yaml` with `gotk-components-2.5.1.yaml`.
- `apps/flux-system/dev/base/kustomization.yaml`
- Replaced `gotk-components.yaml` with `gotk-components-2.5.1.yaml`.
- `apps/flux-system/ithc/base/kustomization.yaml`
- Replaced `gotk-components.yaml` with `gotk-components-2.5.1.yaml`.
- `apps/flux-system/stg/base/kustomization.yaml`
- Replaced `gotk-components.yaml` with `gotk-components-2.5.1.yaml`.
- `apps/flux-system/test/base/kustomization.yaml`
- Replaced `gotk-components.yaml` with `gotk-components-2.5.1.yaml`.
> NONPROD: Upgrade Flux to 2.5.1 nonprod

- apps/flux-system/demo/base/kustomization.yaml
- apps/flux-system/dev/base/kustomization.yaml
- apps/flux-system/ptlsbox/base/kustomization.yaml
- apps/flux-system/serviceaccount/demo.yaml
- apps/flux-system/serviceaccount/dev.yaml
- apps/flux-system/serviceaccount/ptlsbox.yaml
- apps/flux-system/serviceaccount/stg.yaml
- apps/flux-system/serviceaccount/test.yaml
- apps/flux-system/stg/base/kustomization.yaml
- apps/flux-system/test/base/kustomization.yaml
Reverts hmcts/sds-flux-config#6280
- A new patch file `kustomize-controller-patch.yaml` was added to the `kustomization.yaml` file in the `base` directory for the `demo`, `dev`, `ptlsbox`, `stg`, and `test` environments of the flux-system.
- Service account files for `demo`, `dev`, `ptlsbox`, `stg`, and `test` environments were deleted. Each file contained a service account for the `kustomize-controller` with specific annotations and labels.
> Revert "DTSPO-24310: Adding workload identity to non-prod"

- apps/flux-system/workload-identity/workload-identity-federated-credential.yaml
- apps/flux-system/workload-identity/workload-identity-ua-identity.yaml
- Changing WI_ENVIRONMENT to ENVIRONMENT in flux workload-identity dir
- This is needed because WI_ENVIRONMENT is set as stg in the dev environment whereas ENVIRONMENT is a 1 to 1 mapping with the env.
- WI_ENVIRONMENT and ENVIRONMENT do not differ in the other envs.
- Changed owner name from \"aks-${WI_ENVIRONMENT}-mi\" to \"aks-${ENVIRONMENT}-mi\"
- Updated audiences and issuer fields
- Modified user assigned identity name from \"aks-${WI_ENVIRONMENT}-mi\" to \"aks-${ENVIRONMENT}-mi\"
- Updated the metadata namespace and annotations
> DTSPO-24310: Changing WI_ENVIRONMENT to ENVIRONMENT in flux workload-identity dir

- apps/flux-system/dev/base/kustomization.yaml
- apps/flux-system/serviceaccount/dev.yaml
- Adding workload identity to flux dev
- Dev has a serviceaccount patch and have a workload-identity deployment patch.
- Tested in both [sbox](https://github.com/hmcts/sds-flux-config/pull/6273) and [ithc](https://github.com/hmcts/sds-flux-config/pull/6274.)
- Added a new file `dev.yaml` in the `serviceaccount` directory.
- Added a path for `workload-identity-deployment.yaml` in the patches section.
- Created a new file `dev.yaml` containing specifications for a service account with metadata and annotations for Azure workload identity.
> DTSPO-24310: Adding workload identity to flux dev

- apps/flux-system/serviceaccount/dev.yaml
- apps/flux-system/workload-identity/workload-identity-federated-credential.yaml
- apps/flux-system/workload-identity/workload-identity-ua-identity.yaml
- Changing ENVIRONMENT to WI_ENVIRONMENT in flux workload identity dir.
- This is needed as WI_ENVIRONMENT corresponds to 'stg' for the dev environment, which is needed for the STG Mi.
- ENVIRONMENT and WI_ENIRONMENT do not differ in other envs.
- Updating flux dev client id to point to stg MI.
- Updated client-id from \"b86d64c4-ec90-451a-ab22-77cea15aeb68\" to \"fa0102b9-d3d3-4134-ad45-85a529ce9a9e\" in the annotations.
- Changed owner name from \"aks-${ENVIRONMENT}-mi\" to \"aks-${WI_ENVIRONMENT}-mi\" in the spec.
- Modified the name from \"aks-${ENVIRONMENT}-mi\" to \"aks-${WI_ENVIRONMENT}-mi\" in the metadata.
> DTSPO-24310: Updating flux dev client id to STG MI

- apps/flux-system/stg/base/kustomization.yaml
Reverts hmcts/sds-flux-config#6301
- `apps/flux-system/stg/base/kustomization.yaml` 🛠️
- Removed the `git-credentials.enc.yaml` resource
- Added the `././serviceaccount/stg.yaml` path
- Modified the `././base/patches/kustomize-controller-patch.yaml` to `././base/patches/workload-identity-deployment.yaml`
> Revert "DTSPO-24310: Commenting out workload identity changes"

- apps/flux-system/demo/base/kustomization.yaml
- apps/flux-system/serviceaccount/demo.yaml
- Adding workload identity to flux-system demo
- Demo has a serviceaccount patch and a workload-identity deployment patch
- MI has been given write access over the resource group
- Currently working on all other non-prod envs
- Modified `kustomization.yaml` in `apps/flux-system/demo/base`:
- Added `demo.yaml` to the patches section
- Added `git-credentials.enc.yaml` to resources
- Added new file `demo.yaml` in `apps/flux-system/serviceaccount` with ServiceAccount configuration containing annotations and labels.
> DTSPO-24310: Adding Workload Identity to flux-system demo

- apps/darts-modernisation/darts-external-component-test-harness/test.yaml
Turn on test harness for 120
- Changed replicas value from 0 to 60 for the Java component.
- Updated the ingress host to darts-external-component-test-harness.test.platform.hmcts.net.
- Set the environment variable DARTS_LOG_LEVEL to DEBUG.
> Turn on test harness for 120

- apps/darts-modernisation/darts-external-component-test-harness/test.yaml
Turn off the test harness
- Reduced the number of replicas for the `java` component from 60 to 0. 🔄
> Turn off the test harness

- apps/flux-system/ptl/base/kustomization.yaml
- apps/flux-system/serviceaccount/ptl.yaml
- apps/opal/opal-frontend-test/stg.yaml
- Changing PTL flux to use workload identity rather than aadpodidentity.
- Adding serviceaccount ptl.yaml with client ID of aks-ptl-mi.
- Permissions of manager identity have been checked.
- Image automation is still using aadpodidentity.
- Added and working on all non-live sds envs.
- Removed the `kustomize-controller-patch.yaml` and added `workload-identity-deployment.yaml` and `ptl.yaml` in the patches section.
- Added a new file `ptl.yaml` to define a ServiceAccount with annotations and labels for azure.workload.identity integration.
> DTSPO-24310: Adding WI to ptl flux kustomize-controller

- apps/darts-modernisation/darts-external-component-test-harness/test.yaml
Perf test harness run2
- The file `apps/darts-modernisation/darts-external-component-test-harness/test.yaml` has been modified.
- The `replicas` value for `java` has been changed from `80` to `0`.
- The `ingressHost` has been set to `darts-external-component-test-harness.test.platform.hmcts.net`.
- The `DARTS_LOG_LEVEL` environment variable has been set to `DEBUG`.
> Perf test harness run2

- apps/pre/pre-api-cron-cleanup-live-events/demo.yaml
- apps/pre/pre-api-cron-cleanup-streaming-locators/demo.yaml
- apps/pre/pre-api-cron-close-pending-cases/demo.yaml
- apps/pre/pre-api-cron-start-live-events/demo.yaml
- apps/pre/pre-api/demo.yaml
Reverts hmcts/sds-flux-config#6347
- Removed the `ENABLE_NEW_EMAIL_SERVICE` field.
- Removed the `ENABLE_NEW_EMAIL_SERVICE` field.
- Removed the `ENABLE_NEW_EMAIL_SERVICE` field.
- Removed the `ENABLE_NEW_EMAIL_SERVICE` field.
- Removed the `ENABLE_NEW_EMAIL_SERVICE` field.
- Removed the `ENABLE_STREAMING_LOCATOR_ON_START` field.
> Revert "Enable gov notify on demo for PRE"

- apps/darts-modernisation/darts-external-component-test-harness/test.yaml
Turn off test harness.
- Changed replicas value from 60 to 0 for the `java` component
- Updated the `ingressHost` to `darts-external-component-test-harness.test.platform.hmcts.net`
- Set the `DARTS_LOG_LEVEL` to `DEBUG` for the environment
> Turn off test harness.

- apps/darts-modernisation/darts-external-component-test-harness/test.yaml
Turning on the test harness for 120 and 30 iterations
- Changed the number of replicas from 0 to 60.
- Added a new configuration for maximum iterations: 30.
> Turning on the test harness for 120 and 30 iterations

- apps/darts-modernisation/darts-external-component-test-harness/test.yaml
Turning on the test harness for 150
- Changed the number of replicas from 0 to 75 for the Java component.
- Updated the ingress host to \"darts-external-component-test-harness.test.platform.hmcts.net\".
- Set the environment variable DARTS_LOG_LEVEL to \"DEBUG\".
> Turning on the test harness for 150

- apps/darts-modernisation/darts-external-component-test-harness/test.yaml
Turning off test harness of 150
- test.yaml
- Changed the number of replicas from 75 to 0 for the java component.
> Turning off test harness of 150

- apps/darts-modernisation/darts-automated-tasks/stg.yaml
Reverts hmcts/sds-flux-config#6394
- Removed a replica specification for Java, setting it to 0.
- Updated the environment variables `DARTS_GATEWAY_URL` and `DARTS_PORTAL_URL`.
> Revert "DMP-4775 Temporarily disable DARTS automated tasks on staging"

- apps/azureserviceoperator-system/cert-manager/kustomization.yaml
- Bumping version of cert-manager to latest
- Required to try and fix error in sds-deploy pipeline. The flux bootstrapping of the clusters is being updated to use workload identity.
- Updated the cert-manager version from 1.14.4 to 1.17.1.
> DTSPO-24310: Bumping version of cert-manager

- apps/azureserviceoperator-system/cert-manager/kustomization.yaml
Reverts hmcts/sds-flux-config#6400
- File: apps/azureserviceoperator-system/cert-manager/kustomization.yaml
- Updated the cert-manager version from v1.17.1 to v1.14.4.
> Revert "DTSPO-24310: Bumping version of cert-manager"

- apps/pip/subscription-management/ithc.yaml
Set replica to zero for subscription-management on ITHC
- Changed the `replicas` value to 0
- Added `ingressHost` with value `pip-subscription-management.ithc.platform.hmcts.net`
> Set replica to zero for subscription-management on ITHC

- apps/juror/juror-pnc/ithc.yaml
revert from leds testing for the time being
- Updated PNC_SERVICE_HOST and PNC_SERVICE_POST from \"api.test.leds.police.uk:443\" to \"juror-dev-psnp.pnc.pnn.police.uk:7103\" 🔄
> juror: revert from leds testing

- apps/pre/pre-api-cron-cleanup-live-events/demo.yaml
- apps/pre/pre-api-cron-cleanup-live-events/prod.yaml
- apps/pre/pre-api-cron-cleanup-live-events/test.yaml
- apps/pre/pre-api-cron-cleanup-streaming-locators/demo.yaml
- apps/pre/pre-api-cron-cleanup-streaming-locators/prod.yaml
- apps/pre/pre-api-cron-cleanup-streaming-locators/test.yaml
- apps/pre/pre-api-cron-close-pending-cases/demo.yaml
- apps/pre/pre-api-cron-close-pending-cases/prod.yaml
- apps/pre/pre-api-cron-close-pending-cases/test.yaml
- apps/pre/pre-api-cron-start-live-events/demo.yaml
- apps/pre/pre-api-cron-start-live-events/prod.yaml
- apps/pre/pre-api-cron-start-live-events/test.yaml
- apps/pre/pre-api/demo.yaml
- apps/pre/pre-api/prod.yaml
- apps/pre/pre-api/test.yaml
- Updated demo.yaml, prod.yaml, and test.yaml files in apps/pre/pre-api-cron-cleanup-live-events:
- Added PORTAL_URL with respective URLs for different environments.
- Updated demo.yaml, prod.yaml, and test.yaml files in apps/pre/pre-api-cron-cleanup-streaming-locators:
- Added PORTAL_URL with respective URLs for different environments.
- Updated demo.yaml, prod.yaml, and test.yaml files in apps/pre/pre-api-cron-close-pending-cases:
- Added PORTAL_URL with respective URLs for different environments.
- Updated demo.yaml, prod.yaml, and test.yaml files in apps/pre/pre-api-cron-start-live-events:
- Added PORTAL_URL with respective URLs for different environments.
- Updated demo.yaml, prod.yaml, and test.yaml files in apps/pre/pre-api:
- Added PORTAL_URL with respective URLs for different …
> Adds PRE_PORTAL value to all PRE envs

- apps/pre/pre-api-cron-start-live-events/demo.yaml
Enables start live event cron in DEMO
- Unset the `suspend` attribute to `false` to enable the cron job.
- Modified the schedule to run the job every day at 7:00 AM.
> Enable start live event cron in DEMO

- clusters/stg/base/kustomization.yaml
- Temporarily commenting out Opal in staging.
- This is needed because Opal is causing the [aks-sds-deploy pipeline to fail](https://dev.azure.com/hmcts/PlatformOperations/_build/results?buildId=792299&view=logs&j=845f5419-8480-55bc-30e7-60324046543e&t=47b59580-3d51-551c-3548-6a86d4e65d0f). The opal-user-service-java pods are ina crash loop which is causing PDB errors.
- Opal is not currently in use on staging.
- Removed the line `- ./././apps/opal/base/kustomize.yaml` and added the line `- ./././apps/pdda/base/kustomize.yaml`.
- Applied a patch to `./././apps/base/kustomize.yaml`.
> DTSPO-24310: Removing opal from stg temporarily

- clusters/stg/base/kustomization.yaml
Reverts hmcts/sds-flux-config#6460
- Adding Opal back into staging after it was removed temporarily to allow the rollout of the new bootstrapping for sds.
- File: clusters/stg/base/kustomization.yaml
- Removed the reference to ./././apps/opal/base/kustomize.yaml from resources
- Added a patch to ./././apps/base/kustomize.yaml
> Revert "DTSPO-24310: Removing opal from stg temporarily"

- apps/pip/publication-services-mi-reporting-cron/test/01.yaml
- apps/pip/refresh-views-cron/test/01.yaml
PUB-2870
Updated cron trigger
- In `apps/pip/publication-services-mi-reporting-cron/test/01.yaml`, the image for the job has been updated to `sdshmctspublic.azurecr.io/pip/cron-trigger:pr-192-9df4529-20250414103358` and the schedule has been changed from \"01 08 * * 1,3,5\" to \"50 14 * * 1,3,5\"
- In `apps/pip/refresh-views-cron/test/01.yaml`, the schedule for the job has been updated from \"0 8 * * 1,3,5\" to \"50 14 * * 1,3,5\"
> Updated cron timer for CaTH

- apps/pre/pre-api-cron-start-live-events/demo.yaml
- apps/pre/pre-api-cron-start-live-events/prod.yaml
See [S28-3815](https://tools.hmcts.net/jira/browse/S28-3815)
- Revert start live event cron scheduled time to 7 am
- Remove `disableActiveClusterCheck` from prod
- Updated the schedule for the cron job from \"30 10 * * *\" to \"0 7 * * *\"
- Removed the 'suspend' and 'disableActiveClusterCheck' configurations
- Updated the schedule for the cron job from \"30 10 * * *\" to \"0 7 * * *\"
> pre-api: Change Start Live Event Scheduled Time + Prepare Prod

- apps/pre/pre-api-cron-start-live-events/demo.yaml
- apps/pre/pre-api-cron-start-live-events/prod.yaml
- apps/pre/pre-api-cron-start-live-events/stg.yaml
- apps/pre/pre-api-cron-start-live-events/test.yaml
- Decrement start-live-events cron start time by 1hr in all envs
- Updated schedule times in the following files within the apps/pre/pre-api-cron-start-live-events directory:
- demo.yaml
- prod.yaml
- stg.yaml
- test.yaml
- In each file, the schedule was changed from \"0 7 * * *\" to \"0 6 * * *\" or from \"30 8 * * *\" to \"30 7 * * *\".
> pre-api: Decrement start-live-events Scheduled Time by 1 hr

- apps/pre/pre-api-cron-cleanup-live-events/prod.yaml
- apps/pre/pre-api-cron-cleanup-streaming-locators/prod.yaml
- apps/pre/pre-api-cron-close-pending-cases/prod.yaml
- apps/pre/pre-api-cron-start-live-events/prod.yaml
- apps/pre/pre-api/prod.yaml
- Enable GovNotify feature flag in pre-api prod + all crons
- Enable start-live-events cron job
- apps/pre/pre-api-cron-cleanup-live-events/prod.yaml
- Added ENABLE_NEW_EMAIL_SERVICE: true to the environment variables.
- apps/pre/pre-api-cron-cleanup-streaming-locators/prod.yaml
- Added ENABLE_NEW_EMAIL_SERVICE: true to the environment variables.
- apps/pre/pre-api-cron-close-pending-cases/prod.yaml
- Added ENABLE_NEW_EMAIL_SERVICE: true to the environment variables.
- apps/pre/pre-api-cron-start-live-events/prod.yaml
- Changed job suspension from true to false.
- Updated the schedule from \"0 6 * * *\" to its new value.
- Modified environment variables.
- apps/pre/pre-api/prod.yaml
- Added ENABLE_NEW_EMAIL_SERVICE: true to the environment variables.
> feat(pre-api prod): Enable Feature Toggles for GovNotify + Enable start-live-events Cron

- apps/pre/pre-api-cron-cleanup-live-events/test-image-policy.yaml
- apps/pre/pre-api-cron-cleanup-live-events/test.yaml
- apps/pre/pre-api-cron-start-live-events/test-image-policy.yaml
- apps/pre/pre-api-cron-start-live-events/test.yaml
- Added new file `test-image-policy.yaml` under `pre-api-cron-cleanup-live-events` and `pre-api-cron-start-live-events` directories for specifying image policies.
- Updated `test.yaml` files in `pre-api-cron-cleanup-live-events` and `pre-api-cron-start-live-events` directories to use a new image with a tag starting with `pr-921` and `pr-920` respectively.
> Test S28-3665 on PRE perftest

- apps/pip/subscription-management/demo.yaml
- apps/pip/subscription-management/prod.yaml
- apps/pip/subscription-management/stg.yaml
CHG5020830
Spin down subscription management for CaTH
- Updated `demo.yaml`, `prod.yaml`, and `stg.yaml` in `apps/pip/subscription-management/`:
- Set the `replicas` value for `java` to 0 in all three files.
- Updated `ingressHost` for each environment accordingly.
> Spin down pods for CaTH

- apps/juror/juror-api/demo.yaml
- apps/juror/juror-api/image-policy.yaml
deployment of interim10 to ITHC only
- `demo.yaml` 🔄 Updated the image value for Java to `sdshmctspublic.azurecr.io/juror/api:prod-b57be62-20250501130209` and set `RUN_DB_MIGRATION_ON_STARTUP` to true.
- `image-policy.yaml` 🔄 Added annotations for `hmcts.github.com/prod-automated: disabled` and updated the filterTags and policy for imageRepositoryRef name `juror-api` and `juror-api-pr`.
> deploy interim10 for juror-api to ITHC only

- apps/met/pod-delete-cron/pod-delete-cron.yaml
- Added a new field `customServiceAccountName` with the value `pod-delete-service-account` within the `spec` section.
> fix: set custom service account on libragob pod delete cron

- apps/darts-modernisation/darts-external-component-test-harness/test.yaml
Starting up E2E Test harness
- Changed the number of replicas from 0 to 75 for the Java component.
- Updated the ingressHost to \"darts-external-component-test-harness.test.platform.hmcts.net\".
- Set the environment variable DARTS_LOG_LEVEL to \"INFO\".
> Starting up E2E Test harness

- apps/met/batch-jobs/batch-jobs-rbac.yaml
- apps/met/batch-jobs/batch-jobs-service-account-prod.yaml
- apps/met/batch-jobs/batch-jobs-service-account-test.yaml
- apps/met/batch-jobs/test.yaml
- apps/met/prod/base/kustomization.yaml
- apps/met/test/base/kustomization.yaml
- Created `batch-jobs-rbac.yaml` defining a Role and RoleBinding for managing pods in the `met` namespace.
- Added `batch-jobs-service-account-prod.yaml` to define a ServiceAccount for batch jobs in the `met` namespace, with an Azure workload identity client ID annotation.
- Added `batch-jobs-service-account-test.yaml` to define a ServiceAccount for batch jobs in the `met` namespace, with an Azure workload identity client ID annotation.
- In `test.yaml`, set `saEnabled` to false and provided a custom service account name for the batch job, in the `met` namespace.
- Updated `pod-delete-cron-rbac.yaml` to add the \"watch\" verb for pods resource, in the `met` namespace.
- In `prod/base/kustomization.yaml`, added references to the new RBAC and ServiceAccount YAML files for batch jobs in the …
> feat: use separate service account for batch jobs

- apps/keda/demo/base/kustomization.yaml
- apps/keda/dev/base/kustomization.yaml
- apps/keda/ithc/base/kustomization.yaml
- apps/keda/keda/keda-patch.yaml
- apps/keda/ptlsbox/base/kustomization.yaml
- apps/keda/sbox/base/kustomization.yaml
- apps/keda/stg/base/kustomization.yaml
- apps/keda/test/base/kustomization.yaml
https://tools.hmcts.net/jira/browse/DTSPO-25374
Adding Keda 2.16.1 chart to all non-prod clusters
- Updated multiple `kustomization.yaml` files in the `apps/keda` directory to include a new `keda-patch.yaml` path under patches
- Added a new file `keda-patch.yaml` under the `apps/keda/keda` directory containing a HelmRelease specification for Keda version 2.16.1
> Adding Keda 2.16.1 chart to all non-prod clusters

- apps/darts-modernisation/darts-api/prod.yaml
- Updated the `MAX_HANDHELD_AUDIO_FILES` from 500 to 10.
> Reset max handheld to 10 files on prod

- apps/met/batch-jobs/batch-jobs.yaml
- apps/met/batch-jobs/test.yaml
- Changed `batch-jobs.yaml`:
- Added `saEnabled: false` and `customServiceAccountName: libragob-batch-jobs-service-account` to the spec.
- Changed `test.yaml`:
- Removed `saEnabled: false` and `customServiceAccountName: libragob-batch-jobs-service-account` from the spec.
> feat: separate service account for libragob reporting

- apps/admin/traefik-crds-upgrade-v35/kustomization.yaml
- apps/admin/traefik-crds-upgrade-v35/kustomize.yaml
- apps/admin/traefik2/sbox/00-traefik2.yaml
- apps/admin/traefik2/sbox/01-traefik2.yaml
- clusters/sbox/base/kustomization.yaml
https://tools.hmcts.net/jira/browse/DTSPO-25373
upgrade traefik to v35.2.0
ℹ️ Created `traefik-crds-upgrade-v35/kustomization.yaml` to include a list of resources from the Traefik Helm chart version 35.2.0 for CRDs upgrade.
✨ Created `traefik-crds-upgrade-v35/kustomize.yaml` to specify the interval and path for customization of Traefik CRDs upgrade.
🔄 Updated `traefik2/sbox/00-traefik2.yaml` and `traefik2/sbox/01-traefik2.yaml` to use chart version 35.2.0 from HelmRepository `traefik` in the `admin` namespace.
🔄 Updated `clusters/sbox/base/kustomization.yaml` to include a path for `traefik-crds-upgrade-v35/kustomize.yaml`.
> upgrade traefik to v35.2 in sbox 00 and 01

- apps/admin/traefik2/demo/00-traefik2.yaml
- apps/admin/traefik2/demo/01-traefik2.yaml
- apps/admin/traefik2/dev/00-traefik2.yaml
- apps/admin/traefik2/dev/01-traefik2.yaml
- apps/admin/traefik2/ithc/00-traefik2.yaml
- apps/admin/traefik2/ithc/01-traefik2.yaml
- apps/admin/traefik2/ptl/00-traefik.yaml
- apps/admin/traefik2/ptlsbox/00-traefik.yaml
- apps/admin/traefik2/stg/00-traefik2.yaml
- apps/admin/traefik2/stg/01-traefik2.yaml
- apps/admin/traefik2/test/00-traefik2.yaml
- apps/admin/traefik2/test/01-traefik2.yaml
- clusters/demo/base/kustomization.yaml
- clusters/dev/base/kustomization.yaml
- clusters/ithc/base/kustomization.yaml
- clusters/ptl/base/kustomization.yaml
- clusters/ptlsbox/base/kustomization.yaml
- clusters/stg/base/kustomization.yaml
- clusters/test/base/kustomization.yaml
https://tools.hmcts.net/jira/browse/DTSPO-25373
upgrade traefik crds to v35.2 in NLEs e.g. test, stg, ptl, ptlbox, etc
- Updated multiple YAML files in `apps/admin/traefik2/` with a new chart configuration for Traefik version 35.2.0 and source reference
- Updated multiple YAML files in `clusters/` with a path to `apps/admin/traefik-crds-upgrade-v35/kustomize.yaml` for different environments: demo, dev, ithc, ptl, ptlsbox, stg, test
> point to newer traefik CRD v35.2 customisation files

- apps/juror/juror-api/demo.yaml
- apps/juror/juror-api/image-policy.yaml
- apps/juror/juror-bureau/image-policy.yaml
deployment of juror release5.7 into ITHC and Demo
- Updated demo.yaml``` in ```juror-api```:
- Changed the Java image to ```sdshmctspublic.azurecr.io/juror/api:prod-b57be62-20250501130209```.
- Updated ```image-policy.yaml``` in ```juror-api``` and ```juror-bureau```:
- Added annotations for disabling automated production.
- Added filter tags for extracting timestamps.
- Applied an alphabetical order policy for image tagging.
> Juror deploys into ITHC and Demo

- apps/darts-modernisation/darts-external-component-test-harness/test.yaml
Stop the test harness
- The file `test.yaml` in `darts-external-component-test-harness` has been modified.
- The `replicas` value for `java` has been changed from 75 to 0.
> Stop the test harness

- apps/jenkins/jenkins/ptl/jenkins.yaml
N/A
Update DARTs dashboard regex to exclude darts-automation.
- **jenkins.yaml**
- Changed the `includeRegex` for `buildMonitor` to exclude `HMCTS.*\/darts-automation` branches from DARTS Modernisation.
> feat: exclude darts-automation from DARTs dashboard

- apps/pre/pre-api-cron-cleanup-live-events/pre-api-cron-cleanup-live-events.yaml
- apps/pre/pre-api-cron-cleanup-live-events/test.yaml
See [S28-3665](https://tools.hmcts.net/jira/browse/S28-3665)
Increase memory limit on CleanupLiveEvents cron from 1Gi to 2Gi in test env
Increase memory request on CleanupLiveEvents cron from 512Mi to 1Gi in test env
- Changed job schedule from \"15 15 * * *\" to \"30 16 * * *\"
- Added memory requests: '1Gi'
- Added memory limits: '2Gi'
> PRE: Increase memory limit on cleanup live event cron

- apps/darts-modernisation/darts-external-component-test-harness/darts-external-component-test-harness.yaml
- apps/pip/subscription-management/pip-subscription-management.yaml
https://tools.hmcts.net/jira/browse/DTSPO-25673
Temporarily disabling pdb for these two services for SDS ITHC cluster upgrade.
This will be reverted once the upgrade is completed.
- Enabled pdb key with value `false`.
- Enabled pdb key with value `false`.
> DTSPO-25673 temporarily disbling pdb for cluster upgrade

- apps/pre/pre-api-cron-cleanup-live-events/test-image-policy.yaml
- apps/pre/pre-api-cron-cleanup-live-events/test.yaml
- Removed the old pattern and extract rules and added a new pattern rule for test-image-policy.yaml.
- Updated the schedule from \"30 15 * * *\" to \"30 9 * * *\" in test.yaml.
> set image policy to latest pr-921

- apps/darts-modernisation/darts-api/demo.yaml
- apps/darts-modernisation/darts-api/prod.yaml
- apps/darts-modernisation/darts-api/stg.yaml
- Added `AUDIO_LINKING_TASK_PRE_AMBLE_DURATION: '0m'` and `AUDIO_LINKING_TASK_POST_AMBLE_DURATION: '0m'` 
- Updated `MODERNISED_DARTS_START_DATE` from '2099-01-01' to '2025-05-25'
- Added `AUDIO_LINKING_TASK_PRE_AMBLE_DURATION: '0m'` and `AUDIO_LINKING_TASK_POST_AMBLE_DURATION: '0m' 
- Added `AUDIO_LINKING_TASK_PRE_AMBLE_DURATION: '0m'` and `AUDIO_LINKING_TASK_POST_AMBLE_DURATION: '0m'
> Set audio linking task pre and post amble to 0

- apps/darts-modernisation/darts-api/test.yaml
- Added `AUDIO_LINKING_TASK_PRE_AMBLE_DURATION` and `AUDIO_LINKING_TASK_POST_AMBLE_DURATION` with values `'0m'` 🎵.
> Set audio linking pre post amble

- apps/dynatrace/demo/base/kustomization.yaml
- apps/dynatrace/demo/base/kustomize.yaml
- apps/dynatrace/stg/base/kustomization.yaml
- apps/dynatrace/stg/base/kustomize.yaml
- clusters/demo/base/kustomization.yaml
- clusters/stg/base/kustomization.yaml
https://tools.hmcts.net/jira/browse/DTSPO-25380
Push patch for dynatrace to rest of nle
test env working
- Added/modified kustomization.yaml in apps/dynatrace/demo/base and apps/dynatrace/stg/base to include paths for dynatrace-operator-upgrade.yaml and dynatrace-operator-helmrepo-upgrade.yaml, and added a new file apps/dynatrace/demo/base/kustomize.yaml
- Added a new file apps/dynatrace/stg/base/kustomize.yaml
- Updated clusters/demo/base/kustomization.yaml and clusters/stg/base/kustomization.yaml to include path for apps/dynatrace/demo/base/kustomize.yaml and apps/dynatrace/stg/base/kustomize.yaml
> Push patch for dynatrace to rest of nle

- apps/darts-modernisation/darts-external-component-test-harness/darts-external-component-test-harness.yaml
- apps/pip/subscription-management/pip-subscription-management.yaml
Reverts hmcts/sds-flux-config#6586
- `darts-external-component-test-harness.yaml` 🛠️ Removed the PDB configuration and its related block.
- `pip-subscription-management.yaml` 🛠️ Removed the PDB configuration and its related block.
> Revert "DTSPO-25673 temporarily disbling pdb for cluster upgrade"

- apps/pre/pre-api-cron-start-live-events/pre-api-cron-start-live-events.yaml
- apps/pre/pre-api-cron-start-live-events/test.yaml
- Increase memory for StartLiveEvents cron in all envs
ℹ️  **apps/pre/pre-api-cron-start-live-events/pre-api-cron-start-live-events.yaml**
- Increased memory requests to '1Gi' and memory limits to '2Gi' for the enabled job.
**apps/pre/pre-api-cron-start-live-events/test.yaml**
- Removed memory requests and memory limits for the job. Updated the schedule to run at 13:00 daily.
> PRE: Increase Memory for StartLiveEvents cron in all Envs

- apps/jenkins/jenkins/ptl/jenkins.yaml
https://tools.hmcts.net/jira/browse/DTSPO-25685
Update jenkins global vars for sds stg cluster to use 01.  
- Updated the value of `STG_AKS_CLUSTER_NAME` from `ss-stg-00-aks` to `ss-stg-01-aks`.
- Updated the value of `STG_AKS_RESOURCE_GROUP` from `ss-stg-00-rg` to `ss-stg-01-rg`.
> DTSPO-25685 Update Jenkins vars for STG_AKS to 01

- apps/monitoring/version-reporter/ptl/version-reporter.enc.yaml
Fix secret name
- Changed the `name` field from `postgres` to `version-reporter` in the `data` section.
> fixing secret name

- apps/met/batch-jobs/batch-jobs-rbac.yaml
See [DTSPO-22833](https://tools.hmcts.net/jira/browse/DTSPO-22833)
Add missing pods/log resource to fix error:
```
User "system:serviceaccount:met:libragob-batch-jobs-service-account" cannot get resource "pods/log" in API group "" in the namespace "met"
```
- Updated file: `batch-jobs-rbac.yaml`
- Added `\"pods/log\"` to the list of resources under the `pods` section with the `verbs` \"get\", \"list\", \"logs\".
> DTSPO-22833 - Add pods log resource

- apps/mi/mi-azure-functions/image-policy.yaml
- apps/mi/mi-azure-functions/test.yaml
To assist with testing azure functions on test environment
md
- image-policy.yaml
- Added a new ImagePolicy for mi-azure-functions-qa with filterTags and policy settings
- test.yaml
- Updated the image tag for mi-azure-functions to test-026ced4-20250620091502
```
> Set azure functions test to update to latest pr

- apps/mi/mi-azure-functions/image-policy.yaml
- Removed the `mi-azure-functions-dev` ImagePolicy metadata and spec.
- Updated the `mi-azure-functions-qa` ImagePolicy filterTags pattern from `'^test-[a-f0-9]+-(?P<ts>[0-9]+-[0-9]+)'` to `'^test-[a-f0-9]+-(?P<ts>[0-9]+)'`.
> Fixed qa tag for mi-azure-functions

- apps/courtfines/automation/kustomization.yaml
- apps/courtfines/base/kustomization.yaml
- apps/courtfines/courtfines-app/courtfines-app.yaml
- apps/courtfines/courtfines-app/image-policy.yaml
- apps/courtfines/courtfines-app/image-repo.yaml
- apps/courtfines/serviceaccount/test.yaml
- apps/courtfines/stg/base/kustomization.yaml
- apps/courtfines/test/base/kustomization.yaml
- apps/flux-system/automation/kustomization.yaml
- clusters/prod/base/kustomization.yaml
- clusters/test/base/kustomization.yaml
Updated flux config for Court Fines
- Added new files: 
- `apps/courtfines/automation/kustomization.yaml`
- `apps/courtfines/courtfines-app/courtfines-app.yaml`
- `apps/courtfines/courtfines-app/image-policy.yaml`
- `apps/courtfines/courtfines-app/image-repo.yaml`
- `apps/courtfines/serviceaccount/test.yaml`
- `apps/courtfines/test/base/kustomization.yaml` (renamed from prod/base/kustomization.yaml) 
- Modified files:
- `apps/courtfines/base/kustomization.yaml`: Added reference to courtfines-app/courtfines-app.yaml and removed workload-identity
- `apps/courtfines/stg/base/kustomization.yaml`: Added a patch to include serviceaccount/stg.yaml
- `apps/flux-system/automation/kustomization.yaml`: Added reference to courtfines/automation
- `clusters/prod/base/kustomization.yaml`: Removed …
> Updated flux config for Court Fines

- apps/neuvector/neuvector/neuvector.yaml
https://tools.hmcts.net/jira/browse/DTSPO-26362
Updating neuvector.yml to use the OCI version of the chart.
- Updated `neuvector.yaml`
- Updated the HelmRepository name from `hmctspublic` to `hmctspublic-oci` for the NeuVector app.
> Pointing neuvector to the OCI chart

- apps/jenkins/jenkins/ptlsbox/jenkins-azure-vm-agent.yaml
See [DTSPO-26431](https://tools.hmcts.net/jira/browse/DTSPO-26431)
Use PR image in jenkins ptlsbox agents
Testing changes to how SSH keys are handled
- File: apps/jenkins/jenkins/ptlsbox/jenkins-azure-vm-agent.yaml
- Changed the galleryImageVersion from \"24.04.27\" to \"282.0.0\" 🔄
> DTSPO-26431 - Use PR image in Jenkins ptlsbox

- apps/pre/pre-api-cron-check-for-missing-recordings/prod.yaml
See [S28-4013](https://tools.hmcts.net/jira/browse/S28-4013)
Configure the Missing Recordings cron job to run early morning instead of evening, since it checks for missing recordings from the previous day. 
Why: it will alert us earlier to incidents such as https://hmcts.haloitsm.com/tickets?area=1&mainview=team&viewid=0&selid=109&sellevel=1&selparentid=all%20teams&id=19283 
Not needed. Config change only. 
- Updated file: apps/pre/pre-api-cron-check-for-missing-recordings/prod.yaml
- Changed schedule from \"30 21 * * *\" to \"15 6 * * *\"
```
> Configure missing recordings alert to run early morning

- apps/jenkins/jenkins/jenkins.yaml
- apps/jenkins/jenkins/ptl/jenkins.yaml
- apps/jenkins/jenkins/ptlsbox/jenkins.yaml
See [DTSPO-26524](https://tools.hmcts.net/jira/browse/DTSPO-26524)
Some fields have been altered in the new version
Updating them as per the guidance in https://github.com/jenkinsci/helm-charts/blob/main/charts/jenkins/UPGRADING.md
Had to move some fields from base into patches due to changes in value type. Actual values aren't changing.
- Removed duplicate `image` field in the `spec` section.
- Updated the `configAutoReload` sidecar image to version 1.25.2.
- Added `image: \"hmctspublic.azurecr.io/jenkins/jenkins\"` under `controller` in the `spec` section.
- Updated the `configAutoReload` sidecar image to version …
> DTSPO-26524 - Fix v5 helm chart upgrade

- apps/pre/demo/base/kustomization.yaml
- apps/pre/pre-api-cron-check-for-missing-recordings/test-image-policy.yaml
- apps/pre/pre-api-cron-check-for-missing-recordings/test.yaml
- apps/pre/pre-api-cron-cleanup-live-events/test-image-policy.yaml
- apps/pre/pre-api-cron-cleanup-live-events/test.yaml
- apps/pre/pre-api-cron-cleanup-null-durations/demo.yaml
- apps/pre/pre-api-cron-cleanup-null-durations/pre-api-cron-cleanup-null-durations.yaml
- apps/pre/pre-api-cron-cleanup-null-durations/prod.yaml
- apps/pre/pre-api-cron-cleanup-null-durations/stg.yaml
- apps/pre/pre-api-cron-cleanup-null-durations/test-image-policy.yaml
- apps/pre/pre-api-cron-cleanup-null-durations/test.yaml
- apps/pre/pre-api-cron-cleanup-streaming-locators/test-image-policy.yaml
- apps/pre/pre-api-cron-cleanup-streaming-locators/test.yaml
- apps/pre/pre-api-cron-close-pending-cases/test-image-policy.yaml
- apps/pre/pre-api-cron-close-pending-cases/test.yaml
- apps/pre/pre-api-cron-perform-edit-requests/test-image-policy.yaml
- apps/pre/pre-api-cron-perform-edit-requests/test.yaml
- apps/pre/pre-api-cron-start-live-events/test-image-policy.yaml
- apps/pre/pre-api-cron-start-live-events/test.yaml
- apps/pre/pre-api-cron-vodafone-etl/test.yaml
- apps/pre/pre-api/demo.yaml
- apps/pre/pre-api/prod.yaml
- apps/pre/pre-api/stg.yaml
- apps/pre/pre-api/test-image-policy.yaml
- apps/pre/pre-api/test.yaml
- apps/pre/prod/base/kustomization.yaml
- apps/pre/stg/base/kustomization.yaml
- apps/pre/test/base/kustomization.yaml
- apps/pre/demo/base/kustomization.yaml
- Added a new YAML file for pre-api-cron-cleanup-null-durations.
- Updated the resources and patches sections to include pre-api-cron-cleanup-null-durations.yaml and demo.yaml respectively.
- Updated the schedule for pre-api-cron-cleanup-null-durations.yaml.
- Added a new path for pre-api-cron-cleanup-null-durations/demo.yaml.
- apps/pre/pre-api-cron-check-for-missing-recordings/test-image-policy.yaml
- Created a new file for test-image-policy for pre-api-cron-check-for-missing-recordings.
- apps/pre/pre-api-cron-check-for-missing-recordings/test.yaml
- Changed the image tag from prod-cda3aab-20250710142538 to pr-1118.
- Updated the schedule to \"20 19 * * *\".
- apps/pre/pre-api-cron-cleanup-live-events/test-image-policy.yaml
- Updated the image …
> Pin PRE test env to api pr 1118

- apps/pre/pre-api-cron-cleanup-null-durations/demo.yaml
- apps/pre/pre-api-cron-cleanup-null-durations/prod.yaml
- apps/pre/pre-api-cron-cleanup-null-durations/stg.yaml
- apps/pre/pre-api-cron-cleanup-null-durations/test.yaml
Update job name in charts
- Updated files:
- demo.yaml
- prod.yaml
- stg.yaml
- test.yaml
- In each file, the name field under metadata was changed from `pre-api-cron-close-pending-cases` to `pre-api-cron-cleanup-null-durations`.
> S28-0000 Fix cron job name

- apps/pre/pre-api-cron-start-live-events/demo.yaml
- apps/pre/pre-api-cron-start-live-events/prod.yaml
- apps/pre/pre-api-cron-start-live-events/stg.yaml
- apps/pre/pre-api-cron-start-live-events/test.yaml
See [S28-4106](https://tools.hmcts.net/jira/browse/S28-4106)
- Adds ENABLE_STREAMING_LOCATOR_ON_START flag to start-live-events crons in all envs
- stg = true
- test, demo, prod = false 
- Updated files:
- demo.yaml
- prod.yaml
- stg.yaml
- test.yaml
- Added `ENABLE_STREAMING_LOCATOR_ON_START: false` to the spec in demo.yaml, prod.yaml, and test.yaml
- Added `ENABLE_STREAMING_LOCATOR_ON_START: true` to the spec in stg.yaml
> feat(pre-api): `ENABLE_STREAMING_LOCATOR_ON_START` for start live event cron

- apps/pre/pre-api-cron-cleanup-null-durations/stg.yaml
See [S28-4043](https://tools.hmcts.net/jira/browse/S28-4043)
- Enables pre-api-cron-cleanup-null-durations in staging
- `stg.yaml`
- Changed job schedule from `0 19 * * *` to `0 11 * * Thu`
- Updated `suspend` from `true` to `false`
- Updated `ENABLE_NULL_DURATION_UPSERT` from `false` to `true`
> feat(pre-api): enable pre-api-cron-cleanup-null-durations in stg

- apps/pip/frontend/stg.yaml
https://tools.hmcts.net/jira/browse/PUB-2981
Remove old staging image
- Removed the `image` field that specifies the image URL for the frontend application.
- The image field was removed from spec, which indicates a removal of a specified image for the frontend application.
> PUB-2981 - Removed old staging image

- apps/juror/juror-scheduler-execution/demo.yaml
- apps/juror/juror-scheduler-execution/image-policy.yaml
- apps/juror/juror-scheduler-execution/ithc.yaml
only deploying into ITHC for now via image policy
deploying scheduler exec service update for release5.11 into ITHC only via image policy, Demo to have latest prod image
release is for testing
- Updated the image version from \"pr-246-0ad76d5-20250716134840\" to \"prod-804c9ab-20250724132741\" for the Juror Scheduler Execution demo environment.
- Updated the image tag pattern from '^pr-239-[a-f0-9]+-(?P<ts>[0-9]+)' to '^pr-248-[a-f0-9]+-(?P<ts>[0-9]+)' in the image policy for Juror Scheduler Execution.
- No changes.
> juror deployment to scheduler exec service on for release5.11

- apps/pre/pre-api-cron-close-pending-cases/prod.yaml
Reverts hmcts/sds-flux-config#6877
See https://tools.hmcts.net/jira/browse/S28-4104
The relevant cron job has now been fixed 
yaml
- File: prod.yaml
- Changed job suspension from true to false
- Updated job schedule from \"0 * * * *\" to new schedule
```
> Reinstate pending closure cron job

- apps/pre/pre-api-cron-perform-edit-requests/demo.yaml
- apps/pre/pre-api-cron-perform-edit-requests/prod.yaml
- apps/pre/pre-api-cron-perform-edit-requests/stg.yaml
- apps/pre/pre-api-cron-perform-edit-requests/test.yaml
See [S28-4152](https://tools.hmcts.net/jira/browse/S28-4152)
- Enable ENABLE_MULTI_FFMPEG_COMMAND in staging, disabled everywhere else for perform-edit-requests cron
- Updated `demo.yaml`, `prod.yaml`, `stg.yaml`, and `test.yaml` in the `pre-api-cron-perform-edit-requests` directory
- Added `ENABLE_MULTI_FFMPEG_COMMAND: false` to `demo.yaml`, `prod.yaml`, and `test.yaml`
- Updated `ENABLE_MULTI_FFMPEG_COMMAND` to `true` in `stg.yaml`
> feat(pre-api): configure ENABLE_MULTI_FFMPEG_COMMAND for environments

- apps/pre/pre-api-cron-cleanup-null-durations/demo.yaml
- Enable cleanup null duration cron in demo env
- Runs at 2:15 BST, today 21st August
> feat(pre-api): enable cleanup null duration cron in demo

- apps/jenkins/jenkins/ptlsbox/jenkins.yaml
Reverts hmcts/sds-flux-config#7195
SDS Jenkins is working again so this is no longer required
> Revert "Update jenkins image tag - ptlsbox"

- apps/mi/mi-adf-shir-2/dev.yaml
- apps/mi/mi-adf-shir/dev.yaml
Require network connection to ListAssist training environment so we can use ADF to pull data from there.
> Add ListAssist mcmshmcts training alias for MI SHIR

- apps/monitoring/prod/00/hourlyusage.enc.yaml
- apps/monitoring/prod/00/version-reporter.enc.yaml
Updated the credentials for the vm hourly report jobs. The jobs have been failing due to a change in the creds, reports is need by the finops team to enable RI calculations at the end of a period.
> Updating creds for hourlyusage reports
