k8s/environments/prod/common/mi/mi-data-extractor-identity.yaml
k8s/environments/prod/common/mi/mi-extraction-service-identity.yaml
k8s/environments/prod/common/mi/mi-house-keeping-service-identity.yaml
k8s/environments/prod/common/mi/mi-integration-service-identity.yaml
k8s/environments/prod/common/mi/mi-staging-service-identity.yaml

Add MI Prod Identities

---

k8s/environments/prod/cluster-00/mi/mi-data-extractor.yaml
k8s/environments/prod/cluster-00/mi/mi-extraction-service.yaml
k8s/environments/prod/cluster-00/mi/mi-house-keeping-service.yaml
k8s/environments/prod/cluster-00/mi/mi-integration-service.yaml
k8s/environments/prod/cluster-00/mi/mi-staging-service.yaml
k8s/environments/test/common/mi/mi-extraction-service.yaml

Add MI cronjobs and identities for prod new cluster

---

k8s/environments/prod/common/mi/mi-data-extractor-identity.yaml
k8s/environments/prod/common/mi/mi-extraction-service-identity.yaml

Fixed wrong rg for mi identity

---

k8s/release/vh/vh-user-api/Chart.yaml
k8s/release/vh/vh-user-api/templates/deployment.yaml
k8s/release/vh/vh-user-api/templates/ingress.yaml
k8s/release/vh/vh-user-api/templates/service.yaml
k8s/release/vh/vh-user-api/values.yaml

yamllint fixed

---

k8s/release/vh/vh-user-api/templates/deployment.yaml

fixing indent

---

k8s/release/vh/vh-user-api/templates/ingress.yaml

remove git syntax from file

---

k8s/release/vh/vh-user-api/templates/ingress.yaml

removed more git syntax

---

k8s/environments/prod/cluster-00/mi/mi-extraction-service.yaml

Update sftp server address

---

k8s/environments/dev/common/video-hearings/vh-kvuser-identity.yaml
k8s/environments/dev/common/video-hearings/vh-user-api.yaml

fixing yaml issues

---

k8s/environments/dev/common/video-hearings/vh-user-api.yaml
k8s/release/vh/vh-user-api/templates/deployment.yaml

Vh user api setup

---

k8s/release/vh/vh-user-api/values.yaml

more testing

---

k8s/release/vh/vh-user-api/templates/deployment.yaml

more fixing

---

k8s/environments/dev/common/video-hearings/vh-user-api.yaml
k8s/release/vh/vh-user-api/templates/deployment.yaml

testing env

---

k8s/environments/dev/common/video-hearings/vh-user-api.yaml

fixing more env var issues

---

k8s/environments/dev/common/video-hearings/vh-user-api.yaml

more testing env vars

---

k8s/environments/dev/common/video-hearings/vh-user-api.yaml
k8s/release/vh/vh-user-api/templates/deployment.yaml

more env var fixes

---

k8s/environments/dev/common/video-hearings/vh-user-api.yaml

more env var fixing

---

k8s/environments/dev/common/video-hearings/vh-user-api.yaml
k8s/release/vh/vh-user-api/templates/deployment.yaml

fixing vars

---

k8s/environments/dev/common/video-hearings/vh-user-api.yaml

removed rogue <

---

k8s/environments/dev/common/video-hearings/vh-user-api.yaml

fixing version

---

k8s/environments/dev/common/video-hearings/vh-user-api.yaml

fixing aad location

---

k8s/environments/prod/cluster-00/mi/mi-integration-service.yaml

MI enable   sources smoke test to verify connection

---

k8s/environments/prod/common/mi/mi-developer-rbac.yaml

Update mi config

---

k8s/environments/prod/cluster-00/mi/mi-integration-service.yaml

MI add dummy change

---

k8s/environments/dev/common/video-hearings/vh-user-api.yaml

adding aad-identity

---

k8s/environments/dev/common/video-hearings/vh-user-api.yaml

aadIdentityName

---

k8s/release/vh/vh-user-api/templates/aadpodidentity.yaml

fixing aad-pod-ident

---

k8s/environments/dev/common/video-hearings/vh-user-api.yaml

changing version

---

k8s/environments/dev/common/video-hearings/vh-user-api.yaml

changing back to latest

---

k8s/environments/dev/common/video-hearings/vh-user-api.yaml

enableKeyVaults: true

---

k8s/environments/dev/common/video-hearings/vh-user-api.yaml

disabling pod addinity

---

k8s/environments/prod/cluster-00/mi/mi-extraction-service.yaml

Increase memory request and limit for extraction service

---

k8s/environments/test/common/mi/mi-integration-service-8x8-hist.yaml

MI 8x8 historical data test

---

k8s/environments/test/common/mi/mi-data-extractor.yaml

Disable validate blob data-extractor on smoketest for now

---

k8s/environments/test/common/mi/mi-integration-service-8x8-hist.yaml

MI Fix comment

---

k8s/environments/test/common/mi/mi-integration-service-8x8-hist.yaml

Create 8x8 testing job

---

k8s/environments/dev/common-overlay/kustomization.yaml
k8s/environments/dev/common-overlay/video-hearings/kustomization.yaml
k8s/namespaces/video-hearings/kustomization.yaml

adding dev-helmrelease

---

k8s/environments/dev/common-overlay/toffee/flux-patch.yaml

Updating image tag to one that exists
```
[ ] Yes
[x] No
```

DTSPO-242 - fixing image tag for backend

---

k8s/environments/dev/dev-helmrelease.yaml

trying quotes

---

k8s/environments/dev/common-overlay/video-hearings/azure-identity-patch.yaml
k8s/environments/dev/common-overlay/video-hearings/kustomization.yaml
k8s/environments/dev/common-overlay/video-hearings/vh-user-api-identity.yaml
k8s/namespaces/video-hearings/kustomization.yaml
k8s/namespaces/video-hearings/vh-user-api/vh-user-api-identity-binding.yaml
k8s/namespaces/video-hearings/vh-user-api/vh-user-api-identity.yaml

fixing aad

---

k8s/environments/ithc/common-overlay/kustomization.yaml
k8s/environments/ithc/common-overlay/toffee/azure-identity-patch.yaml
k8s/environments/ithc/common-overlay/toffee/flux-patch.yaml
k8s/environments/ithc/common-overlay/toffee/kustomization.yaml
k8s/environments/ithc/ithc-helmrelease.yaml
k8s/namespaces/toffee/toffee-backend/toffee-recipe-backend.yaml

Deploy toffee ithc
```
[ ] Yes
[x] No
```

DTSPO-242 - ithc toffee

---

k8s/environments/ithc/common-overlay/.flux.yaml

DTSPO-242 - add flux.yaml file

---

k8s/environments/dev/common-overlay/flux-patch.yaml
k8s/environments/ithc/common-overlay/flux-patch.yaml

Add frontend patch into flux-patch file
```
[ ] Yes
[x] No
```

Add frontend patch into flux-patch file

---

k8s/environments/dev/common-overlay/video-hearings/vh-user-api-identity.yaml
k8s/namespaces/video-hearings/vh-user-api/vh-user-api.yaml

fixing aad-pod issue

---

k8s/environments/sbox/common-overlay/kustomization.yaml
k8s/environments/sbox/common-overlay/video-hearings/kustomization.yaml
k8s/environments/sbox/common-overlay/video-hearings/vh-user-api-identity.yaml
k8s/environments/sbox/sbox-helmrelease.yaml

setting up sbox

---

k8s/environments/dev/common-overlay/video-hearings/vh-user-api-identity.yaml
k8s/environments/sbox/common-overlay/video-hearings/vh-user-api-identity.yaml

fixing mi rg issue

---

k8s/environments/dev/common-overlay/video-hearings/vh-user-api-identity.yaml

mi client id

---

k8s/namespaces/video-hearings/vh-user-api/vh-user-api.yaml

trying secrets

---

k8s/namespaces/video-hearings/vh-user-api/vh-testing.yaml

fixing test pod

---

k8s/namespaces/video-hearings/kustomization.yaml

adding missing part to deploy test pod

---

k8s/namespaces/video-hearings/vh-user-api/vh-testing.yaml

fixing testing

---

k8s/environments/prod/cluster-00/mi/mi-integration-service-8x8-hist.yaml

MI Update  hr name

---

k8s/environments/sbox/common-overlay/video-hearings/kustomization.yaml
k8s/environments/sbox/common-overlay/video-hearings/vh-user-api-identity.yaml
k8s/namespaces/video-hearings/vh-user-api/vh-testing.yaml

adding sbox

---

k8s/namespaces/video-hearings/vh-user-api/vh-user-api.yaml

updating user-api chart branch name

---

k8s/namespaces/video-hearings/vh-user-api/vh-testing.yaml

updating readiness and liveness paths

---

k8s/environments/sbox/common/maintenance/maintenance.yaml

fixing maintenance

---

k8s/environments/sbox/sbox-helmrelease.yaml

changin sbox to sandbox

---

k8s/environments/prod/cluster-00/mi/mi-integration-service-8x8-hist.yaml

MI updated 8x8 historical data

---

k8s/environments/prod/cluster-00/mi/mi-integration-service-8x8-hist.yaml

MI Disabled group activities

---

k8s/environments/sbox/sbox-helmrelease.yaml

reverting name to sbox

---

k8s/namespaces/video-hearings/kustomization.yaml

removing vh-testing

---

k8s/environments/prod/cluster-00/mi/mi-integration-service-8x8-hist.yaml

Update release name

---

k8s/environments/prod/cluster-00/mi/mi-data-extractor.yaml
k8s/environments/prod/cluster-00/mi/mi-extraction-service.yaml
k8s/environments/prod/cluster-00/mi/mi-house-keeping-service.yaml
k8s/environments/prod/cluster-00/mi/mi-integration-service.yaml
k8s/environments/prod/cluster-00/mi/mi-staging-service.yaml

https://tools.hmcts.net/jira/browse/RMI-1073
Point MI prod images from ssprivateprod to sdshmctspublic
```
[ ] Yes
[x] No
```

Point MI prod images to sdshmctspublic

---

k8s/namespaces/video-hearings/kustomization.yaml
k8s/namespaces/video-hearings/vh-video-api/vh-video-api.yaml
k8s/namespaces/video-hearings/vh-video-web/vh-video-web.yaml

init vh-video-api

---

k8s/environments/stg/common/neuvector/fluentbit-log.yaml

https://tools.hmcts.net/jira/browse/DTSPO-25

dtspo:25 automate nuevector

---

k8s/environments/dev/common-overlay/video-hearings/flux-patch.yaml
k8s/environments/sbox/common-overlay/video-hearings/flux-patch.yaml
k8s/namespaces/video-hearings/kustomization.yaml
k8s/namespaces/video-hearings/vh-video-api/vh-video-api.yaml

adding video web

---

k8s/namespaces/video-hearings/vh-video-api/vh-video-api.yaml

updating branch

---

k8s/prod/releases/netbox/netbox.yaml
k8s/stg/releases/netbox/netbox.yaml

https://tools.hmcts.net/jira/browse/DTSPO-1097

DTSPO-1097 Update netbox whitelisting

---

k8s/namespaces/video-hearings/kustomization.yaml

removing testing

---

k8s/environments/dev/cluster-00-overlay/kustomization.yaml
k8s/environments/dev/cluster-01-overlay/kustomization.yaml

Fix kustomization

---

k8s/namespaces/video-hearings/kustomization.yaml

swaping builds around

---

k8s/namespaces/video-hearings/kustomization.yaml
k8s/namespaces/video-hearings/vh-azure-devops-agent/vh-azure-devops-agent.yaml

Vh sds tidyup

---

k8s/environments/sbox/cluster-00/mi/mi-data-extractor.yaml
k8s/environments/sbox/cluster-00/mi/mi-extraction-service.yaml
k8s/environments/sbox/cluster-00/mi/mi-house-keeping-service.yaml
k8s/environments/sbox/cluster-00/mi/mi-integration-service.yaml
k8s/environments/sbox/cluster-00/mi/mi-staging-service.yaml

MI enable jobs on sbox

---

k8s/environments/dev/common/hmi/hmi-wiremock.yaml
k8s/environments/sbox/common/hmi/hmi-wiremock.yaml
k8s/environments/test/common/hmi/hmi-wiremock.yaml
k8s/release/hmi/hmi-wiremock/values.yaml

Disabling wiremock as currently it's not in use

disable wiremock whilst not in use

---

k8s/namespaces/video-hearings/kustomization.yaml

adding azure devops agent

---

k8s/namespaces/video-hearings/vh-video-web/vh-video-web.yaml

updating chart to master

---

k8s/namespaces/video-hearings/kustomization.yaml
k8s/namespaces/video-hearings/vh-bookings-api/vh-bookings-api.yaml

adding bookings-api

---

k8s/namespaces/video-hearings/kustomization.yaml

adding test-api

---

k8s/namespaces/video-hearings/kustomization.yaml
k8s/namespaces/video-hearings/vh-notification-api/vh-notification-api.yaml

notification-api

---

k8s/namespaces/video-hearings/kustomization.yaml
k8s/namespaces/video-hearings/vh-admin-web/vh-admin-web.yaml

adding vh-admin-web

---

k8s/namespaces/video-hearings/vh-video-web/vh-video-web.yaml

fixing video-web

---

k8s/environments/dev/common/secrets/mailrelay-values.yaml
k8s/environments/prod/cluster-00-overlay/kustomization.yaml
k8s/environments/prod/cluster-01-overlay/kustomization.yaml
k8s/environments/prod/common/secrets/mailrelay-values.yaml
k8s/release/mailrelay/mailrelay/patches/prod/cluster-00/mailrelay.yaml
k8s/release/mailrelay/mailrelay/patches/prod/cluster-01/mailrelay.yaml

DTSPO-901 deploy mail relay prod

---

k8s/environments/prod/cluster-01-overlay/kustomization.yaml

DTSPO-901 Fix kustomization typo

---

k8s/environments/dev/cluster-00-overlay/kustomization.yaml
k8s/environments/dev/cluster-01-overlay/kustomization.yaml
k8s/environments/prod/cluster-01-overlay/kustomization.yaml

DTSPO-900 enable dev mail relay

---

k8s/environments/ithc/common/neuvector/fluentbit-log.yaml
k8s/environments/ithc/common/neuvector/identity.yaml
k8s/environments/ithc/common/neuvector/nv-storage-secret.yaml
k8s/environments/prod/common/neuvector/fluentbit-log.yaml
k8s/environments/prod/common/neuvector/identity.yaml
k8s/environments/prod/common/neuvector/nv-storage-secret.yaml
k8s/environments/test/common/neuvector/fluentbit-log.yaml
k8s/environments/test/common/neuvector/identity.yaml
k8s/environments/test/common/neuvector/nv-storage-secret.yaml

DTSPO-661 Add NeuVector secrets

---

k8s/namespaces/video-hearings/kustomization.yaml
k8s/namespaces/video-hearings/vh-service-web/vh-service-web.yaml

adding service-web

---

k8s/prod/releases/juror-digital/jd-bureau.yaml
k8s/prod/releases/juror-digital/jd-public.yaml

N/A
Changed weighting to show splash pages. DB Patching this weekend
```
[ ] Yes
[x] No
```

Changed weighting percentages to show splash pages

---

k8s/prod/releases/juror-digital/jd-bureau.yaml
k8s/prod/releases/juror-digital/jd-public.yaml

Changed weighting percentages to bring down splash pages
```
[ ] Yes
[x] No
```

Changed weighting percentages to bring down splash pages

---

k8s/environments/dev/cluster-00-overlay/kustomization.yaml
k8s/environments/dev/cluster-01-overlay/kustomization.yaml
k8s/environments/dev/common/neuvector/fluentbit-log.yaml
k8s/environments/dev/common/neuvector/identity.yaml
k8s/environments/dev/common/neuvector/nv-storage-secret.yaml
k8s/namespaces/neuvector/patches/dev/cluster-00/neuvector.yaml
k8s/namespaces/neuvector/patches/dev/cluster-01/neuvector.yaml

Add Neuvector to SDS Dev

---

k8s/namespaces/neuvector/patches/dev/cluster-00/neuvector.yaml

Neuvector network rules mta dev

---

k8s/namespaces/neuvector/patches/dev/cluster-00/neuvector.yaml

Revert neuvector dev mta network rules

---

k8s/release/mailrelay/mailrelay/patches/dev/cluster-00/mailrelay.yaml
k8s/release/mailrelay/mailrelay/patches/dev/cluster-01/mailrelay.yaml

Mailrelay dev log to stdout/stderr

---

k8s/namespaces/video-hearings/kustomization.yaml

removing azure devops

---

k8s/environments/dev/common-overlay/video-hearings/vh-aad-identity.yaml

wrong subscription

---

k8s/environments/ithc/common/neuvector/nv-storage-secret.yaml
k8s/environments/test/common/neuvector/nv-storage-secret.yaml

Removed hyphen from storage account name in SS test and ITHC sealed secrets.
```
[ ] Yes
[x] No
```

DTSPO-661 - Neuvector Nonprod deployment

---

k8s/environments/dev/common-overlay/video-hearings/flux-patch.yaml
k8s/environments/dev/common-overlay/video-hearings/vh-aad-identity.yaml

updating pod aad

---

k8s/environments/ithc/common/neuvector/identity.yaml
k8s/environments/test/cluster-01-overlay/kustomization.yaml

Updated ITHC pod id resource and client ID
Updated Test Kustomize patch location
```
[ ] Yes
[x] No
```

DTSPO-661 - Neuvector Nonprod deployment 2

---

k8s/environments/dev/common-overlay/video-hearings/vh-azure-devops-agent.yaml

fixing name

---

k8s/environments/dev/common-overlay/video-hearings/kustomization.yaml

changing order

---

k8s/namespaces/toffee/toffee-frontend/toffee-frontend.yaml

https://tools.hmcts.net/jira/browse/DTSPO-658
toffee-frontend updated to contact the backend over load balanced url rather than cluster local url

DTSPO-658 Ammend toffee-frontend.yaml

---

k8s/environments/dev/common-overlay/video-hearings/vh-aad-identity.yaml

updating clientid

---

k8s/environments/stg/cluster-01-overlay/kustomization.yaml
k8s/release/admin/traefik/patches/dev/cluster-01/traefik.yaml

Minor updates to fix stg01 and traefik in dev01.
```
[ ] Yes
[x] No
```

DTSPO-661 - Neuvector Nonprod deployment 3

---

k8s/environments/prod/cluster-00-overlay/kustomization.yaml
k8s/environments/prod/cluster-01-overlay/kustomization.yaml
k8s/environments/prod/common/neuvector/nv-storage-secret.yaml
k8s/namespaces/neuvector/patches/prod/cluster-00/neuvector.yaml
k8s/namespaces/neuvector/patches/prod/cluster-01/neuvector.yaml
k8s/namespaces/neuvector/patches/prod/neuvector.yaml

Added config files for prod deployment
```
[ ] Yes
[x ] No
```

DTSPO-661 - Neuvector Prod deployment 

---

k8s/environments/prod/cluster-00-overlay/kustomization.yaml
k8s/environments/prod/cluster-01-overlay/kustomization.yaml
k8s/environments/prod/prod-helmrelease.yaml

fixed missing env patch
```
[ ] Yes
[x] No
```

DTSPO-661 - Neuvector Prod deployment 2

---

k8s/namespaces/video-hearings/vh-test-web/vh-test-web.yaml

adding test-web

---

k8s/release/mailrelay/mailrelay/patches/dev/cluster-00/mailrelay.yaml
k8s/release/mailrelay/mailrelay/patches/dev/cluster-01/mailrelay.yaml

DTSPO-1629 Mailrelay logs filter + stdout

---

k8s/release/mailrelay/mailrelay/patches/dev/cluster-00/mailrelay.yaml
k8s/release/mailrelay/mailrelay/patches/dev/cluster-01/mailrelay.yaml

DTSPO-1629 fluentbit registry

---

k8s/stg/releases/juror-digital/jd-bureau.yaml
k8s/stg/releases/juror-digital/jd-public.yaml

Updated Bureau and Public version numbers for release 2.21
```
[ ] Yes
[X] No
```

Updated version numbers for Bureau and Public

---

k8s/namespaces/toffee/toffee-backend/toffee-recipe-backend.yaml

move to latest plum chart

---

k8s/environments/prod/cluster-00/mi/mi-extraction-service-recovery.yaml
k8s/environments/stg/cluster-00/mi/mi-extraction-service-recovery.yaml

Push Missing MI Export Data to SFTP

---

k8s/environments/demo/common-overlay/video-hearings/vh-aad-identity.yaml
k8s/environments/ithc/common-overlay/video-hearings/flux-patch.yaml
k8s/environments/ithc/common-overlay/video-hearings/kustomization.yaml
k8s/environments/ithc/common-overlay/video-hearings/vh-aad-identity.yaml
k8s/environments/stg/common-overlay/video-hearings/flux-patch.yaml
k8s/environments/stg/common-overlay/video-hearings/kustomization.yaml
k8s/environments/stg/common-overlay/video-hearings/vh-aad-identity.yaml
k8s/environments/test/common-overlay/video-hearings/flux-patch.yaml
k8s/environments/test/common-overlay/video-hearings/kustomization.yaml
k8s/environments/test/common-overlay/video-hearings/vh-aad-identity.yaml

VIH-7466
Flux config for VH lower environments.
```
[ ] Yes
[x] No
```

Amended flux for VH

---

k8s/environments/sbox/common-overlay/toffee/frontend-patch.yaml

https://tools.hmcts.net/jira/browse/DTSPO-658

DTSPO-658  updated toffee frontend

---

k8s/environments/prod/cluster-00/mi/mi-extraction-service-recovery-payment-bar.yaml

https://tools.hmcts.net/jira/browse/RMI-1248
Job to extract payment bar data from export service from "2021-03-17" to "2021-03-19"
```
[ ] Yes
[ ] No
```

Mi export payment bar

---

k8s/environments/prod/cluster-00/mi/mi-extraction-service-recovery-ccd.yaml

Job to extract ccd  data from export service from "2021-03-19" to "2021-03-20"
```
[ ] Yes
[ ] No
```

mi recover ccd extraction

---

k8s/environments/sbox/common/mi/mi-developer-rbac.yaml

Update mi rbac permssions on sbox

---

k8s/environments/dev/common-overlay/video-hearings/busybox.yaml

adding busybox for testing

---

k8s/namespaces/video-hearings/busybox.yaml
k8s/namespaces/video-hearings/kustomization.yaml

moved busybox test pod

---

k8s/namespaces/video-hearings/busybox.yaml

trying to get a test host deployed

---

k8s/environments/prod/cluster-00/mi/mi-data-extractor.yaml
k8s/environments/prod/cluster-00/mi/mi-integration-service.yaml

Correcting 2 comments
```
[ ] Yes
[x] No
```

DTSPO-70 Amend Comments

---

k8s/namespaces/vh/vh-busybox-test/vh-busybox-test.yaml

trying again

---

k8s/environments/dev/common-overlay/vh/kustomization.yaml

removing test pod

---

k8s/environments/sbox/cluster-00-overlay/kustomization.yaml
k8s/environments/sbox/cluster-01-overlay/kustomization.yaml
k8s/environments/sbox/common/secrets/prometheus-values.yaml
k8s/namespaces/monitoring/kube-prometheus-stack/patches/sbox/cluster-00/kube-prometheus-stack.yaml
k8s/namespaces/monitoring/kube-prometheus-stack/patches/sbox/cluster-01/kube-prometheus-stack.yaml

https://tools.hmcts.net/jira/browse/DTSPO-178
```
[ ] Yes
[x] No
```

DTSPO-178 Install Prometheus and Alertmanager for Sbox

---

k8s/namespaces/monitoring/kube-prometheus-stack/patches/dev/cluster-00/kube-prometheus-stack.yaml
k8s/namespaces/monitoring/kube-prometheus-stack/patches/dev/cluster-01/kube-prometheus-stack.yaml

Update prometheus ingress

---

k8s/environments/prod/cluster-00-overlay/kustomization.yaml
k8s/environments/prod/cluster-01-overlay/kustomization.yaml
k8s/environments/prod/common/secrets/prometheus-values.yaml
k8s/namespaces/monitoring/kube-prometheus-stack/patches/prod/cluster-00/kube-prometheus-stack.yaml
k8s/namespaces/monitoring/kube-prometheus-stack/patches/prod/cluster-01/kube-prometheus-stack.yaml

DTSPO-1455 prometheus and alertmanager config for Prod

---

k8s/environments/dev/common/neuvector/nv-storage-secret-hack.yaml
k8s/environments/ithc/common/neuvector/nv-storage-secret-hack.yaml
k8s/environments/prod/common/neuvector/nv-storage-secret-hack.yaml
k8s/environments/stg/common/neuvector/nv-storage-secret-hack.yaml
k8s/environments/test/common/neuvector/nv-storage-secret-hack.yaml

Add Neuvector workaround
```
[ ] Yes
[x] No
```

Add Neuvector Hack

---

k8s/release/admin/secrets-csi-driver/secrets-csi-driver.yaml

Add Toleration for Windows to secrets-csi-driver.yaml

---

k8s/environments/sbox/common/mi/mi-sftp-server.yaml

Fix apiVersion for mi-sftp-server

---

k8s/release/mailrelay/mailrelay/mailrelay.yaml
k8s/release/mailrelay/mailrelay/patches/dev/cluster-00/mailrelay.yaml
k8s/release/mailrelay/mailrelay/patches/dev/cluster-01/mailrelay.yaml

Mailrelay logging prod

---

k8s/release/admin/secrets-csi-driver/secrets-csi-driver.yaml

- Enabled windows csi-secrets-store-provider-azure pods 
```
[ ] Yes
[x] No
```

DTSPO-2168 - update secrets store config for windows nodes

---

k8s/release/mailrelay/mailrelay/patches/dev/cluster-00/mailrelay.yaml
k8s/release/mailrelay/mailrelay/patches/dev/cluster-01/mailrelay.yaml

remove valuefilesecrets mailrelay

---

k8s/environments/dev/cluster-00/mi-azure-functions.yaml
k8s/environments/sbox/cluster-00/mi/mi-azure-functions.yaml
k8s/environments/test/cluster-00/mi/mi-azure-functions.yaml
k8s/release/mi/mi-azure-functions/.helmignore
k8s/release/mi/mi-azure-functions/Chart.yaml
k8s/release/mi/mi-azure-functions/templates/deployment.yaml
k8s/release/mi/mi-azure-functions/templates/secretprovider.yaml
k8s/release/mi/mi-azure-functions/templates/service.yaml
k8s/release/mi/mi-azure-functions/values.yaml

https://tools.hmcts.net/jira/browse/RMI-1218
Helm release to deploy azure functions with service.
```
[ ] Yes
[x] No
```

MI Azure Functions HelmRelease Charts

---

k8s/namespaces/monitoring/kube-prometheus-stack/patches/sbox/cluster-00/kube-prometheus-stack.yaml
k8s/namespaces/monitoring/kube-prometheus-stack/patches/sbox/cluster-01/kube-prometheus-stack.yaml

Correct Prometheus Ingress Class Sbox

---

k8s/environments/prod/cluster-00/mi/mi-extraction-recovery.yaml

For incidient INC5196664
Runs export service for 04th May 2021 data.

Export MI data from 04th May 2021

---

k8s/release/admin/traefik/patches/sbox/cluster-00/traefik.yaml

Amend Git Path for Sandbox Traefik

---

k8s/release/admin/traefik/patches/sbox/cluster-00/traefik.yaml
k8s/release/admin/traefik/traefik.yaml

Amend Git Path for Sandbox Traefik 

---

k8s/namespaces/mi/mi-sftp-server/mi-sftp-server.yaml

Fix indentation in mi-sftp-server.yaml

---

k8s/environments/dev/cluster-00/mi/mi-adf-shir.yaml
k8s/environments/dev/common/mi/mi-azure-functions.yaml
k8s/environments/dev/common/secrets/mi-adf-auth-values.yaml
k8s/environments/ithc/common/mi/mi-azure-functions.yaml
k8s/environments/sbox/cluster-00/mi/mi-adf-shir.yaml
k8s/environments/sbox/common/mi/mi-azure-functions.yaml
k8s/environments/stg/common/mi/mi-azure-functions.yaml
k8s/environments/test/cluster-00/mi/mi-adf-shir.yaml
k8s/environments/test/common/mi/mi-azure-functions.yaml
k8s/environments/test/common/secrets/mi-adf-auth-values.yaml
k8s/release/mi/mi-adf-shir/.helmignore
k8s/release/mi/mi-adf-shir/Chart.yaml
k8s/release/mi/mi-adf-shir/templates/deployment.yaml
k8s/release/mi/mi-adf-shir/templates/secretprovider.yaml
k8s/release/mi/mi-adf-shir/values.yaml
k8s/release/mi/mi-azure-functions/Chart.yaml
k8s/release/mi/mi-azure-functions/templates/deployment.yaml
k8s/release/mi/mi-azure-functions/templates/secretprovider.yaml
k8s/release/mi/mi-azure-functions/values.yaml

A release chart with default values for sbox.
A sbox environment chart as example usage for a Helm Release.

Initial NonProd Charts For MI ADF SHIR Setup

---

k8s/release/mailrelay/mailrelay/patches/dev/cluster-00/mailrelay.yaml
k8s/release/mailrelay/mailrelay/patches/dev/cluster-01/mailrelay.yaml

updated image tag with mountpath fixes

---

k8s/release/mailrelay/mailrelay/patches/dev/cluster-00/mailrelay.yaml
k8s/release/mailrelay/mailrelay/patches/dev/cluster-01/mailrelay.yaml

DTSPO-1425 Dev fixes for exim container initialisation issues

---

k8s/release/mailrelay/mailrelay/patches/dev/cluster-00/mailrelay.yaml
k8s/release/mailrelay/mailrelay/patches/dev/cluster-01/mailrelay.yaml

Fixing tag issues

---

k8s/release/admin/traefik/patches/sbox/cluster-00/traefik.yaml

https://tools.hmcts.net/jira/browse/DTSPO-178
```
[ ] Yes
[x] No
```

DTSPO-178 Add Traefik v2 Fields

---

k8s/namespaces/monitoring/kube-prometheus-stack/kube-prometheus-stack.yaml
k8s/namespaces/monitoring/kube-prometheus-stack/patches/dev/cluster-00/kube-prometheus-stack.yaml
k8s/namespaces/monitoring/kube-prometheus-stack/patches/dev/cluster-01/kube-prometheus-stack.yaml

DTSPO-1425-Exim-monitoring

---

k8s/prod/releases/juror-digital/jd-public.yaml

n/a
n/a
```
[ ] Yes
[x] No
```

Updated to show public splash page due to outage

---

k8s/environments/dev/common/secrets/mailrelay-values.yaml

Mailrelay dev conf update

---

k8s/environments/dev/common/secrets/mailrelay-values.yaml

Mailrelay dev conf fix

---

k8s/environments/dev/common/secrets/mailrelay-values.yaml

Update configuration (with right dashes)

---

k8s/release/mailrelay/mailrelay/patches/dev/cluster-00/mailrelay.yaml
k8s/release/mailrelay/mailrelay/patches/dev/cluster-01/mailrelay.yaml

changes for podMetricsEndpoints in Prometheus

---

k8s/environments/stg/common-overlay/flux-patch.yaml
k8s/environments/stg/common-overlay/kustomization.yaml
k8s/environments/stg/common-overlay/toffee/azure-identity-patch.yaml
k8s/environments/stg/common-overlay/toffee/flux-patch.yaml
k8s/environments/stg/common-overlay/toffee/kustomization.yaml

deploy toffee to stg

---

k8s/release/mailrelay/mailrelay/patches/dev/cluster-00/mailrelay.yaml
k8s/release/mailrelay/mailrelay/patches/dev/cluster-01/mailrelay.yaml

adding portname for exim exporter

---

k8s/namespaces/monitoring/kube-prometheus-stack/kube-prometheus-stack.yaml
k8s/namespaces/monitoring/kube-prometheus-stack/patches/dev/cluster-00/kube-prometheus-stack.yaml
k8s/namespaces/monitoring/kube-prometheus-stack/patches/dev/cluster-01/kube-prometheus-stack.yaml

Dtspo 1425 mailrelay monitoring nonprod

---

k8s/environments/dev/cluster-00/mi/mi-adf-shir.yaml
k8s/environments/dev/common/mi/mi-azure-functions.yaml
k8s/environments/sbox/cluster-00/mi/mi-adf-shir.yaml
k8s/environments/sbox/common/mi/mi-azure-functions.yaml
k8s/environments/stg/cluster-00/mi/mi-adf-shir.yaml
k8s/environments/stg/common/mi/mi-azure-functions.yaml
k8s/environments/test/common/mi/mi-azure-functions.yaml

and fixed flux automated release taggig for mi azure functions and SHIR charts

Deploy SHIR to staging env

---

k8s/release/mailrelay/mailrelay/mailrelay.yaml
k8s/release/mailrelay/mailrelay/patches/dev/cluster-00/mailrelay.yaml
k8s/release/mailrelay/mailrelay/patches/dev/cluster-01/mailrelay.yaml

deploying exim exporter service to dev

---

k8s/release/admin/traefik/patches/sbox/cluster-00/traefik.yaml

Add annotation to add internal load balancer to Traefik 2

---

k8s/release/mailrelay/mailrelay/mailrelay.yaml
k8s/release/mailrelay/mailrelay/patches/dev/cluster-00/mailrelay.yaml
k8s/release/mailrelay/mailrelay/patches/dev/cluster-01/mailrelay.yaml

fixing the correct port name mapping

---

k8s/release/mailrelay/mailrelay/mailrelay.yaml
k8s/release/mailrelay/mailrelay/patches/dev/cluster-00/mailrelay.yaml
k8s/release/mailrelay/mailrelay/patches/dev/cluster-01/mailrelay.yaml

fix hr timed out issue on dev

---

k8s/release/mailrelay/mailrelay/patches/dev/cluster-00/mailrelay.yaml
k8s/release/mailrelay/mailrelay/patches/dev/cluster-01/mailrelay.yaml

port name mapping cleanup

---

k8s/release/mailrelay/mailrelay/patches/dev/cluster-00/mailrelay.yaml
k8s/release/mailrelay/mailrelay/patches/dev/cluster-01/mailrelay.yaml

to fix metrics readability issue on dev

---

k8s/environments/stg/common-overlay/flux-patch.yaml
k8s/environments/stg/common-overlay/toffee/flux-patch.yaml

update toffee stg patches

---

k8s/environments/stg/common-overlay/.flux.yaml

flux config to fix HR image tag issue

---

k8s/release/mailrelay/mailrelay/patches/dev/cluster-00/mailrelay.yaml
k8s/release/mailrelay/mailrelay/patches/dev/cluster-01/mailrelay.yaml

changed values for exim HR release

---

k8s/release/mailrelay/mailrelay/patches/dev/cluster-00/mailrelay.yaml
k8s/release/mailrelay/mailrelay/patches/dev/cluster-01/mailrelay.yaml

mailrelay - subdirectory for default outbound cert

---

k8s/environments/prod/cluster-00/mi/mi-data-extractor.yaml

To update the HR and force the smoketest to run.

Removed unnecessary env var from mi-data-extractor.yaml

---

k8s/environments/prod/cluster-00/mi/mi-data-extractor.yaml

Resets the HelmRelease to unstuck it in prod env

Re-create mi-data-extractor in Prod

---

k8s/release/mailrelay/mailrelay/patches/dev/cluster-00/mailrelay.yaml
k8s/release/mailrelay/mailrelay/patches/dev/cluster-01/mailrelay.yaml

change to 0.1.9 exim release

---

k8s/release/mailrelay/mailrelay/patches/dev/cluster-00/mailrelay.yaml
k8s/release/mailrelay/mailrelay/patches/dev/cluster-01/mailrelay.yaml

Include starttls enabled
```
[ ] Yes
[x ] No
```

Dev - mailrelay image update

---

k8s/namespaces/monitoring/kube-prometheus-stack/patches/dev/cluster-00/kube-prometheus-stack.yaml

Add admin namespace for tests

---

k8s/release/mailrelay/mailrelay/patches/dev/cluster-00/mailrelay.yaml
k8s/release/mailrelay/mailrelay/patches/dev/cluster-01/mailrelay.yaml

now includes port 587/8587 for starttls
```
[ ] Yes
[ x] No
```

Dev - update mailrelay image

---

k8s/release/mailrelay/mailrelay/patches/dev/cluster-00/mailrelay.yaml
k8s/release/mailrelay/mailrelay/patches/dev/cluster-01/mailrelay.yaml

DTSPO-1425 exim exporter updates

---

k8s/namespaces/monitoring/kube-prometheus-stack/patches/dev/cluster-00/kube-prometheus-stack.yaml
k8s/namespaces/monitoring/kube-prometheus-stack/patches/dev/cluster-00/mailrelay-alerts-rules.yaml

adding new alert rules for exim

---

k8s/namespaces/vh/vh-admin-web/vh-admin-web.yaml

Testing filter removal to trigger deployment
```
[ ] Yes
[ x] No
```

Test vh admin deploy

---

k8s/environments/ithc/common-overlay/kustomization.yaml
k8s/environments/ithc/common-overlay/vh/flux-patch.yaml
k8s/environments/ithc/common-overlay/vh/vh-azure-devops-agent/Chart.yaml
k8s/environments/ithc/common-overlay/vh/vh-azure-devops-agent/templates/_helpers.tpl
k8s/environments/ithc/common-overlay/vh/vh-azure-devops-agent/templates/deployment.yaml
k8s/environments/ithc/common-overlay/vh/vh-azure-devops-agent/templates/pod-identity-binding.yaml
k8s/environments/ithc/common-overlay/vh/vh-azure-devops-agent/templates/pod-identity.yaml
k8s/environments/ithc/common-overlay/vh/vh-azure-devops-agent/templates/secretproviderclass.yaml
k8s/environments/ithc/common-overlay/vh/vh-azure-devops-agent/values.yaml
k8s/environments/ithc/common-overlay/vh/vh-devops-agent.yaml

configure vh in ithc

---

k8s/release/admin/traefik/patches/sbox/cluster-00/kustomization.yaml

https://tools.hmcts.net/jira/browse/DTSPO-178
Add Kustomise to sbox-00 Traefik2
```
[ ] Yes
[x] No
```

DTSPO-178 Kustomize Traefik2 sbox00

---

k8s/release/mailrelay/mailrelay/mailrelay.yaml
k8s/release/mailrelay/mailrelay/patches/dev/cluster-00/mailrelay.yaml
k8s/release/mailrelay/mailrelay/patches/dev/cluster-01/mailrelay.yaml

Added to dev patches for now
https://tools.hmcts.net/jira/browse/DTSPO-3221
```
[ ] Yes
[ x] No
```

Mailrelay Dev - increased volumes size

---

k8s/namespaces/mi/mi-developer-rbac.yaml

Allow MI Devs to view pod metrics

---

k8s/environments/stg/common-overlay/toffee/frontend-patch.yaml

update backend url

---

k8s/namespaces/monitoring/kube-prometheus-stack/patches/dev/cluster-00/kube-prometheus-stack.yaml
k8s/namespaces/monitoring/kube-prometheus-stack/patches/dev/cluster-00/mailrelay-alerts-rules.yaml

Fixalertrules

---

k8s/release/hmi/hmi-casehqemulator/templates/secret.yaml
k8s/release/hmi/hmi-casehqemulator/values.yaml

Revert changes for hmi

---

k8s/namespaces/monitoring/kube-prometheus-stack/patches/dev/cluster-00/mailrelay-alerts-rules.yaml

changed alerts rules

---

k8s/environments/dev/cluster-00-overlay/kustomization.yaml
k8s/environments/dev/cluster-01-overlay/kustomization.yaml
k8s/namespaces/monitoring/kube-prometheus-stack/kustomization.yaml
k8s/namespaces/monitoring/kube-prometheus-stack/mailrelay-alerts-rules.yaml
k8s/namespaces/monitoring/kube-prometheus-stack/patches/dev/cluster-01/mailrelay-alerts-rules.yaml

added kustomization file

---

k8s/namespaces/monitoring/kube-prometheus-stack/patches/dev/cluster-00/mailrelay-alerts-rules.yaml
k8s/namespaces/monitoring/kube-prometheus-stack/patches/dev/cluster-01/mailrelay-alerts-rules.yaml

modified alerts rules

---

k8s/namespaces/monitoring/kube-prometheus-stack/patches/dev/cluster-00/mailrelay-alerts-rules.yaml
k8s/namespaces/monitoring/kube-prometheus-stack/patches/dev/cluster-01/mailrelay-alerts-rules.yaml

alert rules

---

k8s/release/admin/traefik2/traefik2.yaml

- Mount sandbox wildcard cert
```
[ ] Yes
[ ] No
```

DTSPO-178 - mount sandbox wildcard

---

README.md

alert rules simple

---

k8s/namespaces/monitoring/kube-prometheus-stack/patches/dev/cluster-00/mailrelay-alerts-rules.yaml
k8s/namespaces/monitoring/kube-prometheus-stack/patches/dev/cluster-01/mailrelay-alerts-rules.yaml

fix alert rules

---

k8s/namespaces/monitoring/kube-prometheus-stack/patches/dev/cluster-01/mailrelay-alerts-rules.yaml

changed alerts rule

---

k8s/release/admin/traefik2/traefik2.yaml

- remove old config
- add label to use pod identity

DTSPO-178 - use pod identity and remove old config

---

k8s/environments/sbox/common/traefik/secret-provider.yaml
k8s/environments/sbox/common/traefik/tlsstore.yaml
k8s/release/admin/traefik2/traefik2.yaml

- update secret provider config 
- add tlsstore
```
[ ] Yes
[ ] No
```

DTSPO-178 tls traefik

---

k8s/namespaces/monitoring/kube-prometheus-stack/patches/dev/cluster-00/mailrelay-alerts-rules.yaml
k8s/namespaces/monitoring/kube-prometheus-stack/patches/dev/cluster-01/mailrelay-alerts-rules.yaml

alert rules finalized

---

k8s/environments/sbox/common/traefik/tlsoptions.yaml

https://tools.hmcts.net/jira/browse/DTSPO-178
```
[ ] Yes
[x] No
```

DTSPO-178 Add tlsoptions traefik

---

k8s/namespaces/monitoring/kube-prometheus-stack/patches/sbox/cluster-00/kube-prometheus-stack.yaml
k8s/namespaces/monitoring/kube-prometheus-stack/patches/sbox/cluster-01/kube-prometheus-stack.yaml

change ingress class monitoring sbox

---

k8s/environments/prod/cluster-00-overlay/kustomization.yaml
k8s/environments/prod/cluster-01-overlay/kustomization.yaml
k8s/namespaces/monitoring/kube-prometheus-stack/patches/prod/cluster-00/mailrelay-alerts-rules.yaml
k8s/namespaces/monitoring/kube-prometheus-stack/patches/prod/cluster-01/mailrelay-alerts-rules.yaml

modifications for prom alert rules

---

k8s/environments/sbox/cluster-00-overlay/kustomization.yaml

remove traefik base for sbox00

---

k8s/release/mailrelay/mailrelay/mailrelay.yaml
k8s/release/mailrelay/mailrelay/patches/dev/cluster-00/mailrelay.yaml
k8s/release/mailrelay/mailrelay/patches/dev/cluster-01/mailrelay.yaml

changed mailrelay.yaml base file

---

k8s/environments/sbox/common/traefik/secret-provider.yaml
k8s/environments/sbox/common/traefik/tlsstore.yaml
k8s/release/admin/traefik2/traefik2.yaml

traefik sbox00 change certificate to wildcard

---

k8s/namespaces/monitoring/kube-prometheus-stack/patches/prod/cluster-00/mailrelay-alerts-rules.yaml
k8s/namespaces/monitoring/kube-prometheus-stack/patches/prod/cluster-01/mailrelay-alerts-rules.yaml

added total message sent alert on prod

---

k8s/environments/sbox/common-overlay/flux-patch.yaml

Update toffee-frontend Image

---

k8s/namespaces/monitoring/kube-prometheus-stack/patches/prod/cluster-00/kube-prometheus-stack.yaml
k8s/namespaces/monitoring/kube-prometheus-stack/patches/prod/cluster-01/kube-prometheus-stack.yaml

added missed configurations to kube-prom-stack.yaml

---

k8s/environments/dev/common-overlay/mailrelay/kustomization.yaml
k8s/release/mailrelay/mailrelay/kustomization.yaml

Fix kustomization duplicates

---

k8s/release/mailrelay/mailrelay/mailrelay-azure-identity-binding.yaml
k8s/release/mailrelay/mailrelay/mailrelay-azure-identity.yaml

Fix mailrelay MI dev namespace

---

k8s/release/mailrelay/mailrelay/mailrelay.yaml
k8s/release/mailrelay/mailrelay/patches/dev/cluster-00/mailrelay.yaml
k8s/release/mailrelay/mailrelay/patches/dev/cluster-01/mailrelay.yaml
k8s/release/mailrelay/mailrelay/patches/prod/cluster-00/mailrelay.yaml
k8s/release/mailrelay/mailrelay/patches/prod/cluster-01/mailrelay.yaml

DTSPO-2912 mailrelay smtp auth dev

---

k8s/release/mailrelay/mailrelay/patches/dev/cluster-00/mailrelay.yaml
k8s/release/mailrelay/mailrelay/patches/dev/cluster-01/mailrelay.yaml

DTSPO-2912 mailrelay dev image

---

k8s/namespaces/monitoring/kube-prometheus-stack/patches/prod/cluster-00/mailrelay-alerts-rules.yaml
k8s/namespaces/monitoring/kube-prometheus-stack/patches/prod/cluster-01/mailrelay-alerts-rules.yaml

removed total alerts

---

k8s/release/mailrelay/mailrelay/patches/dev/cluster-00/mailrelay.yaml
k8s/release/mailrelay/mailrelay/patches/dev/cluster-01/mailrelay.yaml

DTSPO-2912 Fix typo

---

k8s/release/admin/secrets-csi-driver/secrets-csi-driver.yaml

DTSPO-178 CSI Driver Change Config

---

k8s/environments/sbox/cluster-01-overlay/kustomization.yaml

Update sbox01  Kustomize

---

k8s/namespaces/monitoring/kube-prometheus-stack/patches/dev/cluster-00/mailrelay-alerts-rules.yaml
k8s/namespaces/monitoring/kube-prometheus-stack/patches/dev/cluster-01/mailrelay-alerts-rules.yaml
k8s/namespaces/monitoring/kube-prometheus-stack/patches/prod/cluster-00/mailrelay-alerts-rules.yaml
k8s/namespaces/monitoring/kube-prometheus-stack/patches/prod/cluster-01/mailrelay-alerts-rules.yaml

Mailrelay queue alert warning level

---

k8s/namespaces/admin/traefik2/traefik2.yaml

Cosmetic change, specifying a release name so that traefik doesn't default to creating a release name that prefixes the chart name with the namespace.
```
[ ] Yes
[x] No
```

Traefikname

---

k8s/charts/jd-bureau/templates/deployment.yaml
k8s/charts/jd-bureau/values.yaml
k8s/charts/jd-public/templates/deployment.yaml
k8s/charts/jd-public/values.yaml
k8s/stg/releases/juror-digital/jd-bureau.yaml
k8s/stg/releases/juror-digital/jd-public.yaml

dtspo-3228:: access secrets from KV 

---

k8s/namespaces/admin/traefik2/patches/ptlsbox/cluster-00/traefik2.yaml

DTSPO-1032 Use address from subnet space not vnet :facepalm:

---

k8s/environments/prod/common-overlay/.flux.yaml

Prod flux fix

---

k8s/namespaces/juror-digital/jd-bureau/jd-bureau.yaml
k8s/namespaces/juror-digital/jd-public/jd-public.yaml

dtspo-3224:: JD update api version 

---

k8s/prod/releases/juror-digital/jd-bureau.yaml
k8s/prod/releases/juror-digital/jd-public.yaml

dtspo-3228:: PROD:: access secrets from KV  

---

k8s/environments/prod/common-overlay/kustomization.yaml

dtspo-3229:: PROD:: removed JD 

---

k8s/environments/prod/common-overlay/kustomization.yaml
k8s/namespaces/juror-digital/jd-bureau/jd-bureau.yaml
k8s/namespaces/juror-digital/jd-public/jd-public.yaml

dtspo-3229:: PROD:: update acr to point to hmctspublic 

---

k8s/environments/sbox/common-overlay/mi/kustomization.yaml

Added missing managed identity setup for azure functions on sbox
```
[ ] Yes
[x] No
```

Added mi-azure-functions-identity for sbox

---

k8s/charts/jd-bureau/templates/deployment.yaml
k8s/charts/jd-public/templates/deployment.yaml

dtspo-3228 Update Mount point in the chart  to access secrets from KV  

---

k8s/release/mailrelay/mailrelay2/mailrelay2.yaml

DTSPO-3352 fix secret name

---

k8s/release/mailrelay/mailrelay/mailrelay.yaml
k8s/release/mailrelay/mailrelay/patches/dev/cluster-00/mailrelay.yaml
k8s/release/mailrelay/mailrelay/patches/dev/cluster-01/mailrelay.yaml
k8s/release/mailrelay/mailrelay2/patches/dev/cluster-00/mailrelay2.yaml
k8s/release/mailrelay/mailrelay2/patches/dev/cluster-01/mailrelay2.yaml

DTSPO-3352 disable internalTls mailrelay2 dev

---

k8s/environments/ptlsbox/cluster-00-overlay/kustomization.yaml
k8s/namespaces/jenkins/additional-service-monitors.yaml
k8s/namespaces/jenkins/disk.yaml
k8s/namespaces/jenkins/identity.yaml
k8s/namespaces/jenkins/jenkins.yaml
k8s/namespaces/jenkins/kustomization.yaml
k8s/namespaces/jenkins/logging.yaml
k8s/namespaces/jenkins/namespace.yaml
k8s/namespaces/jenkins/patches/ptlsbox/cluster-00/disk.yaml
k8s/namespaces/jenkins/patches/ptlsbox/cluster-00/identity.yaml
k8s/namespaces/jenkins/patches/ptlsbox/cluster-00/jenkins.yaml
tests/helm-release-naming.sh

https://tools.hmcts.net/jira/browse/DTSPO-2879
Adding config for jenkins in sds sbox
```
[ ] Yes
[ x ] No
```

DTSPO-2879 - SDS SBOX Jenkins

---

k8s/release/mailrelay/mailrelay/patches/dev/cluster-00/mailrelay.yaml
k8s/release/mailrelay/mailrelay/patches/dev/cluster-01/mailrelay.yaml
k8s/release/mailrelay/mailrelay2/patches/dev/cluster-00/mailrelay2.yaml
k8s/release/mailrelay/mailrelay2/patches/dev/cluster-01/mailrelay2.yaml

DTSP-1134 load credentials

---

k8s/environments/sbox/common-overlay/flux-patch.yaml

changed image name

---

k8s/environments/sbox/common-overlay/flux-patch.yaml

Fix toffee image name

---

k8s/namespaces/jenkins/patches/ptlsbox/cluster-00/disk.yaml

DTSPO-2879  Jenkins: changed disk rg

---

k8s/release/mailrelay/mailrelay/mailrelay.yaml
k8s/release/mailrelay/mailrelay/patches/dev/cluster-00/mailrelay.yaml
k8s/release/mailrelay/mailrelay/patches/dev/cluster-01/mailrelay.yaml
k8s/release/mailrelay/mailrelay2/mailrelay2.yaml
k8s/release/mailrelay/mailrelay2/patches/dev/cluster-00/mailrelay2.yaml
k8s/release/mailrelay/mailrelay2/patches/dev/cluster-01/mailrelay2.yaml

Mailrelay dev load inbound cert + key

---

k8s/namespaces/jenkins/jenkins.yaml
k8s/namespaces/jenkins/patches/ptlsbox/cluster-00/jenkins.yaml

https://tools.hmcts.net/jira/browse/DTSPO-2879
Adding annotation to fix errors with routing in jenkins ingress
```
[ ] Yes
[ x ] No
```

DTSPO-2879 - Adding annotation for jenkins ingress

---

k8s/namespaces/jenkins/jenkins.yaml

DTSPO-2879  Using latest jenkins image

---

k8s/namespaces/jenkins/patches/ptlsbox/cluster-00/jenkins.yaml

DTSPO-2879  Jenkins: updated KV 

---

k8s/namespaces/jenkins/patches/ptlsbox/cluster-00/identity.yaml

DTSPO-2879  Jenkins: updated MI

---

k8s/namespaces/jenkins/patches/ptlsbox/cluster-00/jenkins.yaml

Added Publishing & Information Project and Video Hearings build monitors
```
[ ] Yes
[X] No
```

Added PIP and VH build monitors

---

k8s/namespaces/jenkins/patches/ptlsbox/cluster-00/jenkins.yaml

DTSPO-2879  Jenkins: Added new env

---

k8s/namespaces/jenkins/patches/ptlsbox/cluster-00/jenkins.yaml

https://tools.hmcts.net/jira/browse/DTSPO-2879 - Removing recent environment variable additions for sbox

DTSPO-2879 - Fixing Jenkins pipeline errors

---

k8s/namespaces/jenkins/patches/ptlsbox/cluster-00/jenkins.yaml

Reverts hmcts/shared-services-flux#996

Revert "DTSPO-2879 - State store name update"

---

k8s/namespaces/pip/kustomization.yaml
k8s/namespaces/pip/pip-frontend/pip-frontend.yaml

in the `k8s.namespaces.pip`, added `pip-frontend.pip-frontend.yaml` along with the reference in the kustomization.yaml file
```
[ ] Yes
[x] No
```

Adding pip-frontend to shared services

---

k8s/stg/releases/juror-digital/jd-bureau.yaml
k8s/stg/releases/juror-digital/jd-public.yaml

Changed public and bureau versions to reflect latest release.
```
[ ] Yes
[x] No
```

Changed the version numbers to reflect 2.22 release

---

k8s/environments/demo/common-overlay/flux-patch.yaml
k8s/environments/dev/common-overlay/flux-patch.yaml
k8s/environments/ithc/common-overlay/flux-patch.yaml
k8s/environments/stg/common-overlay/flux-patch.yaml

updating images to one that exists.
```
[ ] Yes
[x] No
```

Update flux-patch.yaml toffee-frontend image for non-prod envs

---

k8s/namespaces/pip/kustomization.yaml
k8s/namespaces/pip/pip-subscription-management/pip-subscription-management.yaml

added pip-subscription-management service to the pip directory 
```
[ ] Yes
[x] No
```

added pip-subscription-management service

---

k8s/release/mi/mi-azure-functions/Chart.yaml
k8s/release/mi/mi-azure-functions/values.yaml

Fixes wrong IR being cleaned up in ADFs.

Fixed wrong IR default name for MI

---

k8s/environments/dev/common-overlay/mi/kustomization.yaml

Add in missing mi azure functions chart patch for dev

---

k8s/prod/releases/netbox/netbox.yaml
k8s/stg/releases/netbox/netbox.yaml

https://tools.hmcts.net/jira/browse/DTSPO-3734
Update Netbox Traefik whitelist.
```
[ ] Yes
[X] No
```

Tom kimber patch 1

---

k8s/charts/jd-public/templates/deployment.yaml

Remove JD secret cm

---

k8s/environments/stg/common/maintenance/maintenance.yaml

Update registry for maintenance 
```
[ ] Yes
[x] No
```

DTSPO-3555 fix maintenance

---

k8s/environments/demo/common/maintenance/maintenance.yaml
k8s/environments/test/common/maintenance/maintenance.yaml

https://tools.hmcts.net/jira/browse/DTSPO-3444
Update registry for maintenance in ithc, test. Add maintenance for demo.
```
[ ] Yes
[x] No
```

DTSPO-3444 fix maintenance in demo,test,ithc

---

k8s/environments/dev/common-overlay/juror-digital/azure-identity-patch.yaml
k8s/environments/dev/common-overlay/juror-digital/jd-bureau-patch.yaml
k8s/environments/dev/common-overlay/juror-digital/jd-public-patch.yaml
k8s/environments/dev/common-overlay/juror-digital/kustomization.yaml
k8s/environments/dev/common-overlay/kustomization.yaml

https://tools.hmcts.net/jira/browse/DTSPO-3574

DTSPO-3574  Deploy juror digital apps to sds dev

---

k8s/environments/ptl/common/secrets/kube-slack-values.enc.yaml
k8s/environments/ptl/common/secrets/kured-values.enc.yaml

- Add kube slack and kured secrets
```
[ ] Yes
[x] No
```

DTSPO-3555 - add kured and kube-slack secrets

---

k8s/environments/ptl/common/secrets/kube-slack-values.enc.yaml
k8s/environments/ptl/common/secrets/kured-values.enc.yaml

DTSPO-3555 ptl slack notifications

---

k8s/release/admin/kube-slack/patches/ptl/cluster-00/kube-slack.yaml
k8s/release/admin/kured/patches/ptl/cluster-00/kured.yaml

DTSPO-3555 - update slackchannel

---

k8s/namespaces/pip/kustomization.yaml
k8s/namespaces/pip/pip-publication-services/pip-publication-services.yaml

added the publication services to the namespaces and updated the kustomization file
```
[ ] Yes
[ ] No
```

added pip publication services to the k8s namespaces

---

k8s/environments/ptl/cluster-00-overlay/kustomization.yaml
k8s/namespaces/jenkins/patches/ptl/cluster-00/disk.yaml
k8s/namespaces/jenkins/patches/ptl/cluster-00/identity.yaml
k8s/namespaces/jenkins/patches/ptl/cluster-00/jenkins.yaml

DTSPO-2880 - add initial jenkins config for ptl env

---

k8s/namespaces/jenkins/patches/ptl/cluster-00/jenkins.yaml

- update jenkins configuration for ptl
```
[ ] Yes
[x] No
```

DTSPO-2880 - update jenkins config for ptl

---

k8s/stg/releases/juror-digital/jd-bureau.yaml
k8s/stg/releases/juror-digital/jd-public.yaml

Reverts hmcts/shared-services-flux#1003

Revert "Changed the version numbers to reflect 2.22 release"

---

k8s/environments/sbox/common-overlay/kustomization.yaml
k8s/environments/sbox/common-overlay/pip/azure-identity-patch.yaml
k8s/environments/sbox/common-overlay/pip/flux-patch.yaml
k8s/environments/sbox/common-overlay/pip/kustomization.yaml

added the pip directory to sbox common overlay and updated the common kustomization to include pip as well
```
[ ] Yes
[ ] No
```

added pip namespace to sbox common overlay

---

k8s/environments/sbox/common-overlay/toffee/apple-azure-identity.yaml

https://tools.hmcts.net/jira/browse/DTSPO-2879 Create apple identity in flux

DTSPO-2879 update apple identity for jenkins pipeline

---

k8s/namespaces/pip/kustomization.yaml
k8s/namespaces/pip/pip-azure-identity-binding.yaml
k8s/namespaces/pip/pip-azure-identity.yaml

added missing root azure identity file and referenced in kustomization.yaml
```
[ ] Yes
[ ] No
```

added missing root azure identity file and referenced in kustomization.yaml

---

k8s/namespaces/neuvector/patches/dev/cluster-00/neuvector.yaml
k8s/namespaces/neuvector/patches/dev/cluster-01/neuvector.yaml

Added annotations for traefik ingress class in dev patch for neuvector
```
[ ] Yes
[x] No
```

Fix Neuvector https in Dev

---

k8s/namespaces/neuvector/patches/ithc/cluster-00/neuvector.yaml
k8s/namespaces/neuvector/patches/ithc/cluster-01/neuvector.yaml
k8s/namespaces/neuvector/patches/stg/cluster-00/neuvector.yaml
k8s/namespaces/neuvector/patches/stg/cluster-01/neuvector.yaml
k8s/namespaces/neuvector/patches/test/cluster-00/neuvector.yaml
k8s/namespaces/neuvector/patches/test/cluster-01/neuvector.yaml

Fix Neuvector Https in non-prod envs

---

k8s/environments/dev/common/secrets/mi-adf-auth-values.yaml

Was invalid format before.
```
[ ] Yes
[x] No
```

Update adf secret in dev env

---

k8s/namespaces/jenkins/patches/ptl/cluster-00/jenkins.yaml

- DTSPO-2880 - updating nonprod subscription name to fix pipeline error
- updating staging to stg
- Removing nonprod and preview. Updating prod sub name to ptl

DTSPO 2880/nonprod env vars update

---

k8s/environments/sbox/common-overlay/pip/flux-patch.yaml
k8s/namespaces/pip/kustomization.yaml
k8s/namespaces/pip/pip-channel-management/pip-channel-management.yaml

added pip channel management to sbox and also added to namespaces
```
[ ] Yes
[ ] No
```

added pip channel management

---

k8s/environments/stg/common/neuvector/fluentbit-log.yaml
k8s/environments/stg/common/neuvector/nv-storage-secret-hack.yaml
k8s/environments/stg/common/neuvector/nv-storage-secret.yaml
k8s/environments/stg/common/secrets/kube-slack-values.enc.yaml
k8s/environments/stg/common/secrets/kured-values.enc.yaml
k8s/environments/stg/common/secrets/mi-adf-auth-values.yaml

https://tools.hmcts.net/jira/browse/DTSPO-4150
Re-encrypt all secrets with the new key
```
[ ] Yes
[x ] No
```

DTSPO-4150 update sds stg secrets with new sops key

---

k8s/environments/stg/cluster-00/mi/mi-data-extractor.yaml
k8s/environments/stg/cluster-00/mi/mi-extraction-service.yaml
k8s/environments/stg/cluster-00/mi/mi-house-keeping-service.yaml
k8s/environments/stg/cluster-00/mi/mi-integration-service.yaml
k8s/environments/stg/cluster-00/mi/mi-staging-service.yaml
k8s/environments/stg/common/mi/mi-azure-functions-identity.yaml
k8s/environments/stg/common/mi/mi-data-extractor-identity.yaml
k8s/environments/stg/common/mi/mi-extraction-service-identity.yaml
k8s/environments/stg/common/mi/mi-house-keeping-service-identity.yaml
k8s/environments/stg/common/mi/mi-integration-service-identity.yaml
k8s/environments/stg/common/mi/mi-staging-service-identity.yaml

Fixes the now changed Management Information managed identity clientIds for stg env
```
[ ] Yes
[x] No
```

Fixed MI stg env managed identity client ids

---

k8s/namespaces/hmi/kustomization.yaml
k8s/namespaces/hmi/namespace.yaml
k8s/namespaces/hmi/pip-azure-identity-binding.yaml
k8s/namespaces/hmi/pip-azure-identity.yaml

HMIS-902
Adding HMI namespace
```
[ ] Yes
[ x] No
```

adding hmi namespace

---

k8s/environments/ptlsbox/common/secrets/netbox-postgresql.yaml
k8s/environments/ptlsbox/common/secrets/netbox-redis.yaml

DTSPO-3990 netbox stg secrets

---

k8s/namespaces/jenkins/patches/ptl/cluster-00/jenkins.yaml

- DTSPO-2880 - adding vars for missing envs
- DTSPO-2880 - some more missing env vars

DTSPO-2880 - some more missing env vars

---

k8s/environments/dev/common-overlay/juror-digital/jd-bureau-patch.yaml
k8s/environments/dev/common-overlay/juror-digital/jd-public-patch.yaml

Fixing ingress for jd frontend and bureau 
```
[ ] Yes
[ ] No
```

DTPSO-4362 - fix jd hostnames

---

k8s/release/mailrelay/mailrelay/patches/dev/cluster-00/mailrelay.yaml

points to mailrelay exim latest

---

k8s/namespaces/toffee/toffee-frontend/toffee-frontend.yaml
k8s/namespaces/toffee/toffee-recipe-backend/toffee-recipe-backend.yaml

Also updated backend to use latest tag from ACR﻿

DTSPO-2880 - pointing frontend to hmcts/charts repo

---

k8s/environments/demo/common-overlay/flux-patch.yaml
k8s/environments/dev/common-overlay/flux-patch.yaml
k8s/environments/sbox/common-overlay/flux-patch.yaml
k8s/environments/stg/common-overlay/flux-patch.yaml

- DTSPO-2880 - Updating flux patch for toffee to point to sdshmctspublic acr
- DTSPO-2880 - Updating flux patch for toffee to point to sdshmctspublic acr
- DTSPO-2880 - updating toffee image in demo, dev, sbox, stg

DTSPO-2880 - updating toffee image in demo, dev, sbox, stg

---

k8s/environments/prod/common-overlay/kustomization.yaml

- Deploy JD apps to production
```
[ ] Yes
[x] No
```

DTSPO-188 - deploy JD apps to prod cluster

---

k8s/release/mailrelay/mailrelay/patches/dev/cluster-00/mailrelay.yaml

DTSPO-2913 changed exim relay image to 0.13

---

k8s/release/mailrelay/mailrelay/patches/dev/cluster-01/mailrelay.yaml

DTSPO-2942 point cluster 01 0.13

---

k8s/namespaces/monitoring/kube-prometheus-stack/kube-prometheus-stack.yaml

I've already updated the CRDs in all installed envs

Upgrade prometheus

---

k8s/charts/netbox-chart/values.yaml
k8s/namespaces/netbox/netbox/patches/ptlsbox/cluster-00/netbox.yaml

change references from stg environment to ptlsbox
```
[ ] Yes
[x ] No
```

DTSPO-3990 update netbox helm chart values

---

k8s/namespaces/vh/kustomization.yaml
k8s/namespaces/vh/vh-nginx/vh-nginx.yaml

N/A
adding an nginx service
```
[ ] Yes
[X] No
```

added vh-nginx service

---

k8s/environments/dev/common-overlay/vh/vh-azure-devops-agent/templates/deployment.yaml

N/A
added the pat token to the ada config
```
[ ] Yes
[X] No
```

added AZP_TOKEN to ada config

---

k8s/environments/ptlsbox/common/secrets/netbox-postgresql.yaml
k8s/environments/ptlsbox/common/secrets/netbox-redis.yaml

amend secrets - it had an extra line before
```
[ ] Yes
[ x] No
```

DTSPO-3990 amend netbox ptlsbox secrets

---

k8s/namespaces/juror-digital/jd-public/jd-public.yaml

@msl8r and I noticed that HPA is running hot when this isn't doing anything.
Here's some initial tuning, let's see how this goes

DTSPO-188 Resource tuning for public

---

k8s/namespaces/netbox/netbox/patches/ptlsbox/cluster-00/netbox.yaml

change host to netbox.sandbox so it's accessible through https
```
[ ] Yes
[x] No
```

DTSPO-3990 change netbox ptlsbox host from sbox to sandbox

---

k8s/environments/dev/common-overlay/kustomization.yaml
k8s/environments/dev/common-overlay/pip/azure-identity-patch.yaml
k8s/environments/dev/common-overlay/pip/flux-patch.yaml
k8s/environments/dev/common-overlay/pip/kustomization.yaml
k8s/environments/test/common-overlay/kustomization.yaml
k8s/environments/test/common-overlay/pip/azure-identity-patch.yaml
k8s/environments/test/common-overlay/pip/flux-patch.yaml
k8s/environments/test/common-overlay/pip/kustomization.yaml

added pip services to test and dev common overlay and updated the kustimization.yaml
```
[ ] Yes
[ ] No
```

added pip services to dev env and test env

---

k8s/charts/jd-bureau/values.yaml

Enable Sticky sessions for JD apps

---

k8s/charts/netbox-chart/values.yaml

Change port to 443 to allow https
```
[ ] Yes
[x] No
```

DTSPO-3990 change netbox service port to 443

---

k8s/environments/dev/common/secrets/mailrelay-values.yaml

dtspo-2943 - update to sop secret for mailrelay

---

k8s/namespaces/netbox/netbox/patches/ptlsbox/cluster-00/netbox.yaml

add netbox sbox tls host
```
[ ] Yes
[x] No
```

DTSPO-3990 netbox sandbox tls host

---

k8s/charts/netbox-chart/templates/ingress.yaml

DTSPO-3990 update netbox ingress object apiversion

---

k8s/charts/netbox-chart/templates/ingress.yaml

DTSPO-3990 netbox new apiversion syntax

---

k8s/charts/netbox-chart/templates/ingress.yaml

DTSPO-3990 add missing pathtype attribute for netbox ingress

---

k8s/environments/dev/cluster-00/mi/mi-adf-shir.yaml
k8s/environments/dev/common/mi/mi-azure-functions.yaml
k8s/environments/ithc/cluster-00/mi/mi-adf-shir.yaml
k8s/environments/ithc/common/mi/mi-azure-functions.yaml
k8s/environments/prod/cluster-00/mi/mi-adf-shir.yaml
k8s/environments/prod/common/mi/mi-azure-functions.yaml
k8s/environments/sbox/cluster-00/mi/mi-adf-shir.yaml
k8s/environments/sbox/common/mi/mi-azure-functions.yaml
k8s/environments/stg/cluster-00/mi/mi-adf-shir.yaml
k8s/environments/stg/common/mi/mi-azure-functions.yaml
k8s/environments/test/cluster-00/mi/mi-adf-shir.yaml
k8s/environments/test/common/mi/mi-azure-functions.yaml
k8s/release/mi/mi-azure-functions/Chart.yaml
k8s/release/mi/mi-azure-functions/values.yaml

Set ClientID to use for MSI connections
```
[ ] Yes
[x] No
```

Updated Azure Function charts with MI ClientID values

---

k8s/environments/prod/common/mi/mi-azure-functions.yaml

Updated Prod MI Azure Functions clientId

---

k8s/release/mailrelay/mailrelay/patches/dev/cluster-00/mailrelay.yaml

DTSPO-4399 changed exim image to 0.13.0

---

k8s/release/mailrelay/mailrelay/patches/dev/cluster-00/mailrelay.yaml

dtspo3353 WIP

---

k8s/release/mailrelay/mailrelay/patches/dev/cluster-00/mailrelay.yaml

DTSPO-3353 wip

---

k8s/environments/prod/common/mi/mi-azure-functions.yaml

Fixed missing Optic URL for production

---

k8s/release/mailrelay/mailrelay/patches/dev/cluster-00/mailrelay.yaml

DTSPO 3353 changed patch certificate

---

k8s/environments/test/cluster-00/mi/mi-data-extractor-recover.yaml

Test delete blob task

---

k8s/environments/test/cluster-00/mi/mi-data-extractor-recover.yaml
k8s/environments/test/cluster-00/mi/mi-data-extractor.yaml

Fix data extractor pr tag

---

k8s/environments/stg/cluster-00/mi/mi-staging-service.yaml

Filter out v2 containers

---

k8s/release/mailrelay/mailrelay/mailrelay.yaml
k8s/release/mailrelay/mailrelay/patches/dev/cluster-00/mailrelay.yaml
k8s/release/mailrelay/mailrelay/patches/dev/cluster-01/mailrelay.yaml
k8s/release/mailrelay/mailrelay2/mailrelay2.yaml
k8s/release/mailrelay/mailrelay2/patches/dev/cluster-00/mailrelay2.yaml
k8s/release/mailrelay/mailrelay2/patches/dev/cluster-01/mailrelay2.yaml
k8s/release/mailrelay/mailrelay2/patches/prod/cluster-00/mailrelay2.yaml
k8s/release/mailrelay/mailrelay2/patches/prod/cluster-01/mailrelay2.yaml

Mailrelay2 with outbound certs for prod now added
Also included enableOutboundTls in all, as I changed it in the new version for readability.
```
[ ] Yes
[ x] No
```

Prod Mailrelay2 - version with prod outbound certs

---

k8s/release/mailrelay/mailrelay2/patches/prod/cluster-00/mailrelay2.yaml
k8s/release/mailrelay/mailrelay2/patches/prod/cluster-01/mailrelay2.yaml

Prevent conflict with mailrelay
```
[ ] Yes
[x ] No
```

Mailrelay 2 LBs

---

k8s/release/mailrelay/mailrelay2/patches/dev/cluster-00/mailrelay2.yaml
k8s/release/mailrelay/mailrelay2/patches/dev/cluster-01/mailrelay2.yaml

https://tools.hmcts.net/jira/browse/DTSPO-4398
WIP: Update to use PR. resolving certificate key issues with the relay when using the csi driver to fetch from keyvault
```
[ ] Yes
[x] No
```

DTSPO-4398WIP: Fixing certificate errors with exim

---

k8s/release/mailrelay/mailrelay2/patches/dev/cluster-00/mailrelay2.yaml
k8s/release/mailrelay/mailrelay2/patches/dev/cluster-01/mailrelay2.yaml

https://tools.hmcts.net/jira/browse/DTSPO-4398
Reverting image back to latest build
```
[ ] Yes
[x] No
```

DTSPO-4398: Updated the image version to the lates build version

---

k8s/stg/releases/juror-digital/jd-bureau.yaml
k8s/stg/releases/juror-digital/jd-public.yaml

enabling maintenance..

---

k8s/release/mailrelay/mailrelay/patches/dev/cluster-00/mailrelay.yaml
k8s/release/mailrelay/mailrelay/patches/dev/cluster-01/mailrelay.yaml
k8s/release/mailrelay/mailrelay2/patches/prod/cluster-00/mailrelay2.yaml
k8s/release/mailrelay/mailrelay2/patches/prod/cluster-01/mailrelay2.yaml

aligning mailrelays to 0.2.8 except prod mailrelay1

---

k8s/environments/dev/common-overlay/pip/kustomization.yaml

Add permissions for the pip pods dev
```
[ ] Yes
[ X ] No
```

Add permissions for the pip pods dev

---

k8s/environments/dev/common-overlay/flux-patch.yaml

temp remove pip fe
```
[ ] Yes
[ X ] No
```

temp remove pip fe

---

k8s/namespaces/jenkins/patches/ptl/cluster-00/jenkins.yaml
k8s/namespaces/jenkins/patches/ptlsbox/cluster-00/jenkins.yaml

Add HMI to build monitors
```
[ ] Yes
[ X ] No
```

Setup build Monitor for HMI

---

k8s/environments/demo/common-overlay/flux-patch.yaml
k8s/environments/dev/common-overlay/flux-patch.yaml
k8s/environments/ithc/common-overlay/flux-patch.yaml
k8s/environments/stg/common-overlay/flux-patch.yaml
k8s/namespaces/toffee/toffee-frontend/toffee-frontend.yaml

Update toffee image in demo, dev, ithc, stg

---

k8s/environments/demo/cluster-00-overlay/kustomization.yaml
k8s/environments/demo/cluster-01-overlay/kustomization.yaml

https://tools.hmcts.net/jira/browse/DTSPO-4608
```
[ ] Yes
[x] No
```

DTSPO-4608 add kustomize patches for csi driver update demo

---

k8s/release/mailrelay/mailrelay/patches/dev/cluster-00/mailrelay.yaml

removed v from tag num

---

k8s/environments/ptl/cluster-00-overlay/kustomization.yaml
k8s/environments/ptl/common/secrets/netbox-postgresql.yaml
k8s/environments/ptl/common/secrets/netbox-redis.yaml
k8s/namespaces/netbox/netbox/patches/ptl/cluster-00/netbox.yaml
k8s/namespaces/netbox/netbox/patches/ptl/cluster-00/traefik-netbox.yaml

https://tools.hmcts.net/jira/browse/DTSPO-1878
Added ptl patches, kustomize config and secrets
```
[ ] Yes
[x] No
```

DTSPO-1878 deploy netbox prod in SDS PTL

---

k8s/release/mailrelay/mailrelay/patches/dev/cluster-00/mailrelay.yaml

added v to release tag

---

k8s/release/mailrelay/mailrelay/patches/dev/cluster-00/mailrelay.yaml

removed unused configurations

---

k8s/environments/ptl/common/secrets/netbox-redis.yaml
k8s/namespaces/netbox/netbox/patches/ptl/cluster-00/netbox.yaml

https://tools.hmcts.net/jira/browse/DTSPO-1878
```
[ ] Yes
[x] No
```

DTSPO-1878 netbox - point prod to new ptl instances

---

k8s/release/mailrelay/mailrelay/patches/dev/cluster-00/mailrelay.yaml
k8s/release/mailrelay/mailrelay/patches/dev/cluster-01/mailrelay.yaml

aligning config for mailrelay2 and mailrelay 1

---

k8s/namespaces/monitoring/kube-prometheus-stack/kube-prometheus-stack.yaml
k8s/namespaces/monitoring/kube-prometheus-stack/patches/ptl/cluster-00/kube-prometheus-stack.yaml
k8s/namespaces/monitoring/kube-prometheus-stack/patches/ptlsbox/cluster-00/kube-prometheus-stack.yaml

Also disable by default as we don't need it in every env...

DTSPO-4610 Add ingress for grafana

---

k8s/namespaces/monitoring/kube-prometheus-stack/kube-prometheus-stack.yaml
k8s/namespaces/monitoring/kube-prometheus-stack/patches/ptl/cluster-00/kube-prometheus-stack.yaml
k8s/namespaces/monitoring/kube-prometheus-stack/patches/ptlsbox/cluster-00/kube-prometheus-stack.yaml

Grafana is looking very sad, adding in dashboards from CFT

Add grafana dashboards

---

k8s/environments/sbox/cluster-01-overlay/kustomization.yaml
k8s/release/admin/secrets-csi-driver/patches/sbox.yaml

- old non-prod patch was deleted, adding a patch back in for sbox
```
[ ] Yes
[x] No
```

DTSPO-4675 - adding back overlay with tolerations

---

k8s/environments/sbox/cluster-00-overlay/kustomization.yaml
k8s/namespaces/admin/traefik2/patches/sbox/cluster-00/traefik2.yaml
k8s/namespaces/monitoring/kube-prometheus-stack/patches/sbox/cluster-00/kube-prometheus-stack.yaml
k8s/release/admin/kured/patches/sbox/cluster-00/kured.yaml

- Copy node pool split changes over to sbox-00
```
[ ] Yes
[x] No
```

DTSPO-4675 - apply node pool tolerations and affinity rules to sbox-00

---

k8s/prod/releases/juror-digital/jd-bureau.yaml
k8s/prod/releases/juror-digital/jd-public.yaml

Enabling maintenance for 2.22 release..

---

k8s/prod/releases/juror-digital/jd-bureau.yaml
k8s/prod/releases/juror-digital/jd-public.yaml

Removing maintenance and updating release to 2.22..

---

k8s/environments/dev/common-overlay/flux-patch.yaml
k8s/environments/stg/common-overlay/flux-patch.yaml

https://tools.hmcts.net/jira/browse/PUB-751
Add pip-business-rules and hmi-case-hq-emulator to dev/stg
```
[ ] Yes
[ X ] No
```

Add pip-business-rules and hmi-case-hq-emulator to env

---

k8s/namespaces/jenkins/jenkins.yaml

- Add affinity and toleration rules to accommodate the node split 
```
[ ] Yes
[x] No
```

Add affinity and toleration rules to jenkins

---

k8s/namespaces/monitoring/kube-prometheus-stack/kube-prometheus-stack.yaml

- Add missing tolerations to prometheus admission job
```
[ ] Yes
[x] No
```

Add tolerations and affinity rules to prometheus admission job

---

k8s/namespaces/jenkins/jenkins.yaml

DTSPO-4577 Update Jenkins to release plugins

---

k8s/namespaces/jenkins/jenkins.yaml

- Revert Jenkins tolerations and affinity changes
```
[ ] Yes
[x] No
```

Revert Jenkins tolerations and affinity changes

---

k8s/environments/test/cluster-00/mi/mi-adf-shir.yaml

Force SHIR version

---

k8s/environments/test/cluster-00/mi/mi-adf-shir.yaml

Updated image tag for MI ADF SHIR test env

---

k8s/environments/stg/common-overlay/flux-patch.yaml
k8s/environments/stg/common-overlay/pip/kustomization.yaml
k8s/namespaces/pip/kustomization.yaml
k8s/namespaces/pip/pip-business-rules/patches/stg/pip-business-rules.yaml
k8s/namespaces/pip/pip-business-rules/pip-business-rules.yaml

Add pip business rule app to flux
```
[ ] Yes
[ X ] No
```

add missing application details

---

k8s/environments/stg/common-overlay/flux-patch.yaml
k8s/namespaces/hmi/hmi-case-hq-emulator/stg/hmi-case-hq-emulator.yaml
k8s/namespaces/pip/pip-business-rules/patches/stg/pip-business-rules.yaml
k8s/namespaces/pip/pip-business-rules/pip-business-rules.yaml

correct the app type
```
[ ] Yes
[ X ] No
```

update app type

---

k8s/environments/dev/common-overlay/flux-patch.yaml
k8s/namespaces/pip/kustomization.yaml
k8s/namespaces/pip/pip-account-management/patches/stg/pip-account-management.yaml
k8s/namespaces/pip/pip-account-management/pip-account-management.yaml
k8s/namespaces/pip/pip-channel-management/patches/stg/pip-channel-management.yaml
k8s/namespaces/pip/pip-channel-management/pip-channel-management.yaml
k8s/namespaces/pip/pip-data-management/patches/stg/pip-data-management.yaml
k8s/namespaces/pip/pip-data-management/pip-data-management.yaml
k8s/namespaces/pip/pip-publication-services/patches/stg/pip-publication-services.yaml
k8s/namespaces/pip/pip-publication-services/pip-publication-services.yaml
k8s/namespaces/pip/pip-subscription-management/patches/stg/pip-subscription-management.yaml
k8s/namespaces/pip/pip-subscription-management/pip-subscription-management.yaml

https://tools.hmcts.net/jira/browse/PUB-760
Setup remaining pip services on STG
```
[ ] Yes
[ X ] No
```

PUB-760 create stg for pip services

---

k8s/environments/stg/common-overlay/flux-patch.yaml

https://tools.hmcts.net/jira/browse/PUB-760
Add the PIP services to staging
```
[ ] Yes
[ X ] No
```

PUB-760 add pip services to stg

---

k8s/namespaces/jenkins/patches/ptl/cluster-00/jenkins.yaml
k8s/namespaces/jenkins/patches/ptlsbox/cluster-00/jenkins.yaml

Apparently they are ~2 minutes quicker to start up

Use ephemeral disk for agents

---

k8s/environments/stg/common-overlay/pip/kustomization.yaml

https://tools.hmcts.net/jira/browse/PUB-760
add dns patch
```
[ ] Yes
[ X ] No
```

PUB-760 - add patches for staging

---

k8s/stg/releases/juror-digital/jd-bureau.yaml
k8s/stg/releases/juror-digital/jd-public.yaml

Weighted Changes

---

k8s/stg/releases/juror-digital/jd-bureau.yaml
k8s/stg/releases/juror-digital/jd-public.yaml

Release 2.23

---

k8s/namespaces/jenkins/patches/ptlsbox/cluster-00/jenkins.yaml

- Updating jenkins-agent in ptlsbox
- Bumping init agent tag

DTSPO-4613 - update ptlsbox init agent tag

---

k8s/namespaces/pip/pip-account-management/pip-account-management.yaml
k8s/namespaces/pip/pip-channel-management/pip-channel-management.yaml
k8s/namespaces/pip/pip-publication-services/pip-publication-services.yaml
k8s/namespaces/pip/pip-subscription-management/pip-subscription-management.yaml

Correct the language type on the tag filter
```
[ ] Yes
[ X ] No
```

Correct Language Type

---

k8s/environments/dev/common/mi/mi-azure-functions.yaml

Updates tag to actual active image tag for Mi Azure Functions on dev
```
[ ] Yes
[x] No
```

Updated Dev MI Azure Functions Image Tag

---

k8s/environments/dev/common-overlay/juror-digital/jd-bureau-patch.yaml
k8s/environments/dev/common-overlay/juror-digital/jd-public-patch.yaml

- bump juror_digital_bureau_portal to 2.23.166
- bump juror_digital_public_portal to 2.23.490
```
[ ] Yes
[x] No
```

Update Juror digital images in dev

---

k8s/environments/stg/common-overlay/pip/kustomization.yaml

Add access to PIP staging pods so we can exec in and get more information
```
[ ] Yes
[ X ] No
```

Add access to PIP stg pods

---

k8s/environments/dev/common-overlay/toffee/azure-identity-patch.yaml

- Set toffee to use the toffee stg mi 
```
[ ] Yes
[x] No
```

Use toffee-stg-mi for toffee dev

---

k8s/namespaces/pip/pip-frontend/patches/prod/pip-frontend.yaml

Add prod patch so we remember to configure later
```
[ ] Yes
[ X ] No
```

Add prod patch

---

k8s/release/mi/mi-azure-functions/Chart.yaml
k8s/release/mi/mi-azure-functions/values.yaml

Load Encryption secrets for Azure Functions as required
```
[ ] Yes
[x] No
```

Add encryption secrets for functions

---

k8s/environments/demo/common-overlay/flux-patch.yaml
k8s/environments/demo/common-overlay/kustomization.yaml
k8s/environments/demo/common-overlay/pip/azure-identity-patch.yaml
k8s/environments/demo/common-overlay/pip/kustomization.yaml
k8s/namespaces/pip/pip-frontend/patches/demo/pip-frontend.yaml

https://tools.hmcts.net/jira/browse/PUB-905
Add flux configuration for the demo environment
```
[ ] Yes
[ X ] No
```

PUB-905 - Add demo config for pip

---

k8s/namespaces/jenkins/jenkins.yaml
k8s/namespaces/jenkins/patches/ptlsbox/cluster-00/jenkins.yaml

https://tools.hmcts.net/jira/browse/DTSPO-5762
```
[ ] Yes
[x] No
```

DTSPO-5762 Update Jenkins for ptlsbox

---

k8s/namespaces/jenkins/jenkins.yaml
k8s/namespaces/jenkins/patches/ptlsbox/cluster-00/jenkins.yaml

as per https://github.com/jenkinsci/azure-vm-agents-plugin/releases/tag/795.vd5903dae1139

DTSPO-5762 Update usageMode to fix

---

k8s/namespaces/jenkins/jenkins.yaml
k8s/namespaces/jenkins/patches/ptl/cluster-00/jenkins.yaml
k8s/namespaces/jenkins/patches/ptlsbox/cluster-00/jenkins.yaml

https://tools.hmcts.net/jira/browse/DTSPO-5762
Upgrading Jenkins to the latest version + updating plugins
```
[ ] Yes
[x] No
```

DTSPO-5762 Upgrade Jenkins

---

k8s/namespaces/jenkins/patches/ptl/cluster-00/jenkins.yaml
k8s/namespaces/jenkins/patches/ptlsbox/cluster-00/jenkins.yaml

as per https://github.com/jenkinsci/azure-vm-agents-plugin/releases/tag/795.vd5903dae1139
```
[ ] Yes
[x] No
```

Remove optional fields

---

k8s/namespaces/jenkins/jenkins.yaml

https://tools.hmcts.net/jira/browse/DTSPO-5745
```
[ ] Yes
[x] No
```

DTSPO-5745 Comment out Traefik annotation to enable http for Jenkins

---

k8s/environments/sbox/common-overlay/toffee/frontend-patch.yaml

Testing disabling automation for toffee sbox

---

k8s/namespaces/jenkins/jenkins.yaml

https://tools.hmcts.net/jira/browse/DTSPO-5865
```
[ ] Yes
[x] No
```

DTSPO-5865 Uncomment traefik annotation to re-enable https Jenkins

---

k8s/namespaces/admin/traefik2/patches/ptlsbox/cluster-00/traefik2.yaml

DTSPO-5745 Amend traefik2.yaml ptlsbox

---

apps/azure-devops/azure-devops-agent/image-policy.yaml
apps/azure-devops/azure-devops-agent/image-repo.yaml

- Fixed image policy regex and repo for azure devops agent
```
[ ] Yes
[x] No
```

DTSPO-5577 - create image policy for azure devops agent

---

k8s/environments/dev/cluster-00/mi/mi-adf-shir.yaml
k8s/environments/ithc/cluster-00/mi/mi-adf-shir.yaml
k8s/environments/prod/cluster-00/mi/mi-adf-shir.yaml
k8s/environments/stg/cluster-00/mi/mi-adf-shir.yaml
k8s/environments/test/cluster-00/mi/mi-adf-shir.yaml

Use 4 SHIR nodes in 1 cluster for most envs

---

k8s/release/mailrelay/mailrelay2/patches/dev/cluster-00/mailrelay2.yaml
k8s/release/mailrelay/mailrelay2/patches/dev/cluster-01/mailrelay2.yaml
k8s/release/mailrelay/mailrelay2/patches/prod/cluster-00/mailrelay2.yaml
k8s/release/mailrelay/mailrelay2/patches/prod/cluster-01/mailrelay2.yaml

https://tools.hmcts.net/jira/browse/DTSPO-4402
Added mailrelay-dev-user and tenable user objects to Prod and Dev
```
[ ] Yes
[x] No
```

Added user mailrelay-prod-user

---

k8s/namespaces/juror-digital/jd-bureau/jd-bureau.yaml
k8s/namespaces/juror-digital/jd-public/jd-public.yaml

Disabling automation for the JD applications, these images are manually updated for now.
```
[ ] Yes
[x] No
```

Disable automation on jd apps

---

k8s/release/mi/mi-azure-functions/Chart.yaml
k8s/release/mi/mi-azure-functions/values.yaml

Added appinsights secret to functions chart

---

k8s/environments/dev/common-overlay/juror-digital/jd-bureau-patch.yaml
k8s/environments/dev/common-overlay/juror-digital/jd-public-patch.yaml

2.24 NLE Release
```
[ ] Yes
[X] No
```

Changed image names to reflect 2.24 deployment

---

k8s/environments/dev/common-overlay/juror-digital/jd-bureau-patch.yaml

Reverted Bureau back to 2.23

---

k8s/environments/dev/common-overlay/juror-digital/jd-bureau-patch.yaml

2.24 JD Deployment Bureau updated
```
[ ] Yes
[ ] No
```

Updated version numbers to reflect 2.24 deployment

---

k8s/environments/dev/common-overlay/juror-digital/jd-bureau-patch.yaml

Changed bureau version to 2.24.152
```
[ ] Yes
[ ] No
```

Updated to 2.24.152 in order to test

---

k8s/environments/dev/common-overlay/juror-digital/jd-bureau-patch.yaml

"Changed version to 2.24.146 for Bureau"
```
[ ] Yes
[ ] No
```

Changed version to 2.24.146

---

apps/toffee/frontend/sbox.yaml
apps/toffee/frontend/toffee-frontend.yaml
apps/toffee/identity/sbox.yaml
apps/toffee/recipe-backend/sbox.yaml
apps/toffee/recipe-backend/toffee-recipe-backend.yaml

Add Sandbox Patches for Toffee flux v2

---

apps/toffee/frontend/toffee-frontend.yaml

Amend toffee-frontend.yaml

---

apps/toffee/recipe-backend/sbox.yaml
apps/toffee/recipe-backend/toffee-recipe-backend.yaml

Amend recipe-backend.yaml

---

apps/toffee/identity/sbox.yaml
apps/toffee/identity/toffee-azure-identity.yaml

Update toffee azure identity

---

k8s/environments/dev/common-overlay/juror-digital/jd-bureau-patch.yaml

Changed version number from 2.24.146 to 2.24.154
```
[ ] Yes
[x] No
```

Changed version number from 2.24.146 to 2.24.154

---

k8s/environments/dev/common-overlay/flux-patch.yaml

Flux patch not needed for jd apps - automation has been turned off and this patch config is stopping the app from updating.
```
[ ] Yes
[x] No
```

Fix JD bureau

---

k8s/environments/dev/common-overlay/juror-digital/jd-public-patch.yaml

Updated image version to display 2.24.100 update
```
[ ] Yes
[X] No
```

Adjusted image version to reflect 2.24.100 update

---

apps/base/kustomize.yaml

This should fix the decryption issues 
```
[ ] Yes
[x] No
```

Add sops config to base kustomize file

---

k8s/environments/dev/common/mi/mi-azure-functions.yaml
k8s/environments/ithc/common/mi/mi-azure-functions.yaml
k8s/environments/prod/common/mi/mi-azure-functions.yaml
k8s/environments/stg/common/mi/mi-azure-functions.yaml
k8s/environments/test/common/mi/mi-azure-functions.yaml
k8s/release/mi/mi-azure-functions/values.yaml

Added environment to override mi-metadata database being used.
```
[ ] Yes
[x] No
```

Added MI Metadata DB details for Azure Functions

---

apps/admin/kured/kured.yaml
apps/admin/kured/sbox/00.yaml
apps/admin/kured/sbox/01.yaml

Fix helm release

---

apps/admin/traefik2/kustomization.yaml
apps/admin/traefik2/sbox/00-traefik2.yaml
apps/admin/traefik2/sbox/01-traefik2.yaml
apps/admin/traefik2/traefik2-helmrepo.yaml
apps/admin/traefik2/traefik2.yaml

fix traefik hr for flux v2
```
[ ] Yes
[x] No
```

Fix traefik helm release

---

apps/admin/kured/kured-helmrepo.yaml
apps/admin/kured/kured.yaml
apps/admin/kured/kustomization.yaml

fix kured hr for flux v2
```
[ ] Yes
[x] No
```

fix kured helm release

---

apps/admin/base/kustomization.yaml
apps/admin/secrets-csi-driver/kustomization.yaml
apps/admin/secrets-csi-driver/sbox/01.yaml
apps/admin/secrets-csi-driver/secrets-csi-driver-helmrepo.yaml
apps/admin/secrets-csi-driver/secrets-csi-driver.yaml

fix csi driver hr for flux v2
```
[ ] Yes
[x] No
```

fix secrets csi driver hr for flux v2

---

apps/admin/kube-slack/kube-slack.yaml

fix kube-slack helm release for flux v2
```
[ ] Yes
[x] No
```

fix kube-slack helm release

---

k8s/environments/prod/cluster-00/mi/mi-data-extractor.yaml

Disable data ingestion

---

clusters/dev/00/kustomization.yaml
clusters/dev/01/kustomization.yaml
clusters/dev/base/kustomization.yaml

Fix error on cluster - 'kustomization path not found: stat /tmp/flux-system503463956/clusters/dev/00: no such file or directory'

DTSPO-6285 - add dev cluster kustomization

---

apps/admin/kube-slack/kustomization.yaml
apps/admin/kured/kustomization.yaml
apps/admin/secrets-csi-driver/kustomization.yaml
apps/admin/traefik2/kustomization.yaml

Add namespace to admin app kustomizations

---

apps/admin/kube-slack/kube-slack.yaml
apps/admin/kured/kured.yaml
apps/admin/secrets-csi-driver/secrets-csi-driver.yaml
apps/admin/traefik2/traefik2.yaml

- Amend admin apps charts to go to admin namespace instead of flux-system

Amend admin apps charts

---

apps/admin/kube-slack/kube-slack.yaml

- Amend kube-slack chart namespace

Amend kube-slack chart namespace

---

k8s/environments/prod/common-overlay/flux-patch.yaml
k8s/environments/prod/common-overlay/kustomization.yaml
k8s/environments/prod/common-overlay/pip/azure-identity-patch.yaml
k8s/environments/prod/common-overlay/pip/kustomization.yaml
k8s/namespaces/pip/pip-frontend/patches/stg/pip-frontend.yaml

https://tools.hmcts.net/jira/browse/PUB-1007
Setup PIP on Production
```
[ ] Yes
[ X ] No
```

PUB-1007 Add PIP Production Configuration

---

apps/admin/kured/dev/kured-values.enc.yaml

- Add env specific kured values
- Adding encrypred regex for flux v2
- fixing sops encryption for dev

DTSPO-6258 - dev: migrate kured to fluxv2

---

apps/admin/kured/dev/kustomization.yaml

- Fixing kured secret reference
```
[ ] Yes
[x] No
```

DTSPO-6258 - fix kured values reference

---

apps/pip/data-management/pip-azure-identity-binding.yaml

- Update pip-data-management azure identity
- Update identity binding selector

DTSPO-6527 - update pip identity binding selector

---

apps/pip/identity/pip-azure-identity-binding.yaml
apps/pip/identity/pip-azure-identity.yaml

- move ot single pip identity
- Add namespace to identity and binding

DTSPO-6527 - add namespace to identity and binding

---

apps/pip/base/kustomization.yaml
apps/pip/base/nonprod-team-permissions-rbac.yaml
apps/pip/data-management/pip-data-management.yaml

- Add namespace to identity and binding
- Adding rbac to pip

DTSPO-6527 - add rbac to pip

---

apps/pip/data-management/image-repo.yaml
clusters/dev/base/kustomization.yaml

- Adding rbac to pip
- Adding pip namespace to dev

DTSPO-6527 - add pip namespace to dev

---

apps/pip/account-management/pip-account-management.yaml
apps/pip/channel-management/pip-channel-management.yaml
apps/pip/data-management/pip-data-management.yaml
apps/pip/frontend/pip-frontend.yaml
apps/pip/publication-services/pip-publication-services.yaml
apps/pip/subscription-management/pip-subscription-management.yaml

- migrate remaining pip apps to flux v2
- Increase interval in pip

DTSPO-6258 - dev: increase interval in pip

---

apps/pip/data-management/pip-data-management.yaml

- migrate remaining pip apps to flux v2
- Increase interval in pip
- Fix chart path - pip-data-management

DTSPO-6258 - dev: fix chart path - pip-data-management

---

apps/pip/account-management/pip-account-management.yaml
apps/pip/channel-management/pip-channel-management.yaml
apps/pip/data-management/pip-data-management.yaml
apps/pip/frontend/pip-frontend.yaml
apps/pip/publication-services/pip-publication-services.yaml
apps/pip/subscription-management/pip-subscription-management.yaml

- Fix chart paths - pip
- Remove namespace from app yaml

DTSPO-6258 - dev: fix chart paths - pip

---

apps/pip/frontend/pip-frontend.yaml

- updates to pip structure
- updates to pip structure
- Add disable timeout to pip-frontend

DTSPO-6258 - add disablewait to pip-frontend

---

apps/pip/account-management/pip-account-management.yaml
apps/pip/channel-management/pip-channel-management.yaml
apps/pip/data-management/pip-data-management.yaml
apps/pip/publication-services/pip-publication-services.yaml
apps/pip/subscription-management/pip-subscription-management.yaml

- Add disable timeout to pip-frontend
- add disableWait to other pip apps

DTSPO-6258 - add disableWait to other pip apps

---

apps/admin/traefik2/sbox/kustomization.yaml

Add sbox kustomization for traefik

---

apps/juror-digital/base/kustomization.yaml
apps/juror-digital/base/kustomize.yaml
apps/juror-digital/dev/base/kustomization.yaml
apps/juror-digital/identity/dev-identity-patch.yaml
apps/juror-digital/identity/dev.yaml
apps/juror-digital/identity/juror-digital-azure-identity-binding.yaml
apps/juror-digital/identity/juror-digital-azure-identity.yaml
apps/juror-digital/jd-bureau/jd-bureau.yaml
apps/juror-digital/jd-public/jd-public.yaml
apps/juror-digital/moj-reverse-proxy/moj-reverse-proxy.yaml
clusters/dev/base/kustomization.yaml
k8s/environments/dev/common-overlay/kustomization.yaml

- add jd to fluxv2 dev
- dev: migrate jd to flux v2

DTSPO-6258 - dev: migrate jd to fluxv2

---

k8s/environments/test/common-overlay/vh/vh-aad-identity.yaml

Correct the client id for test MI
```
[ ] Yes
[ x ] No
```

correct test MI

---

apps/mailrelay/dev/base/kustomization.yaml
apps/mailrelay2/dev/base/kustomization.yaml

- flux v2 dev mailrelay
- update migration status in readme
- Add namespace to azure identity

DTSPO-6258 - dev: fix mailrelay identity

---

apps/vh/bookings-api/bookings-api.yaml
apps/vh/notification-api/notification-api.yaml
apps/vh/scheduler-jobs/scheduler-jobs.yaml
apps/vh/service-web/service-web.yaml
apps/vh/test-api/test-api.yaml
apps/vh/test-web/test-web.yaml
apps/vh/user-api/user-api.yaml
apps/vh/video-api/video-api.yaml
apps/vh/video-web/video-web.yaml

Correct the repo for charts.
```
[ ] Yes
[ X ] No
```

Update Chart Repos for Dev VH

---

k8s/environments/demo/cluster-00-overlay/kustomization.yaml
k8s/environments/demo/cluster-01-overlay/kustomization.yaml
k8s/namespaces/admin/traefik2/patches/demo/cluster-00/traefik2-no-proxy.yaml
k8s/namespaces/admin/traefik2/patches/demo/cluster-01/traefik2-no-proxy.yaml
k8s/namespaces/admin/traefik2/traefik2-no-proxy.yaml

- Probably needs a bit more thought when moving over to v2, but this should work. 
```
[ ] Yes
[x] No
```

DTSPO-6478 - traefik no proxy demo

---

k8s/environments/stg/common-overlay/vh/vh-aad-identity.yaml

Update the new Client ID for the VH MI
```
[ ] Yes
[ X ] No
```

Update VH MI Client ID

---

apps/juror-digital/jd-bureau/jd-bureau.yaml
apps/juror-digital/jd-public/jd-public.yaml
apps/juror-digital/moj-reverse-proxy/moj-reverse-proxy.yaml

- Add chart git repo
- add image to jd

DTSPO-6258 - dev: add image to jd

---

apps/azure-devops/azure-devops-agent/azure-devops-agent.yaml
apps/toffee/frontend/toffee-frontend.yaml
apps/toffee/recipe-backend/toffee-recipe-backend.yaml

DTSPO-5953 Amend helm chart namespaces

---

apps/mi/mi-adf-shir/dev.yaml
apps/mi/mi-adf-shir/mi-adf-shir.yaml
apps/mi/mi-adf-shir/sbox.yaml

- Add dev values to mi-adf
- fix mi-adf secret

DTSPO-6258 - dev: fix mi-adf secret

---

k8s/environments/ithc/common-overlay/flux-patch.yaml
k8s/environments/ithc/common-overlay/kustomization.yaml
k8s/environments/ithc/common-overlay/pip/azure-identity-patch.yaml
k8s/environments/ithc/common-overlay/pip/kustomization.yaml
k8s/environments/test/common-overlay/flux-patch.yaml
k8s/environments/test/common-overlay/kustomization.yaml
k8s/environments/test/common-overlay/pip/azure-identity-patch.yaml
k8s/environments/test/common-overlay/pip/kustomization.yaml
k8s/namespaces/pip/pip-frontend/patches/ithc/pip-frontend.yaml
k8s/namespaces/pip/pip-frontend/patches/test/pip-frontend.yaml

https://tools.hmcts.net/jira/browse/PUB-1042
Configure ITHC and Test Environments
```
[ ] Yes
[ X ] No
```

PUB-1042 - Configure PIP ITHC and Test

---

k8s/release/mi/mi-adf-shir/templates/deployment.yaml
k8s/release/mi/mi-adf-shir/templates/secretprovider.yaml
k8s/release/mi/mi-adf-shir/values.dev.yaml
k8s/release/mi/mi-adf-shir/values.sbox.yaml
k8s/release/mi/mi-adf-shir/values.yaml

- fix helm values mi
- fix deployment.yaml template

DTSPO-6258 - dev: fix mi deployment.yaml template

---

k8s/release/mi/mi-adf-shir/templates/secretprovider.yaml

- fix helm values mi
- fix deployment.yaml template
- revert resourceGroup in template
- remove quotes from uaid

DTSPO-6258 - dev: fix mi secret provider template

---

k8s/namespaces/vh/kustomization.yaml

Add the missing identity YAML to the Kustomize file
```
[ ] Yes
[ X ] No
```

Add VH ad yaml to Kustomize file

---

apps/mi/mi-adf-shir/dev.yaml

- Update mi-adf to use uami
- update secrets mount path dev

DTSPO-6258 - dev: mi-adf secrets mount path

---

apps/mi/mi-adf-shir/mi-adf-shir.yaml
apps/mi/mi-azure-functions/mi-azure-functions.yaml
apps/mi/mi-data-extractor/mi-data-extractor.yaml
apps/mi/mi-extraction-service/mi-extraction-service.yaml
apps/mi/mi-house-keeping-service/mi-house-keeping-service.yaml
apps/mi/mi-integration-service/mi-integration-service.yaml
apps/mi/mi-staging-service/mi-staging-service.yaml

Add interval field
Remove labels
```
[ ] Yes
[x] No
```

DTSPO-5953 Amend MI helm releases for Flux v2

---

k8s/release/mi/mi-data-extractor-job/Chart.yaml
k8s/release/mi/mi-data-extractor-job/values.yaml
k8s/release/mi/mi-extraction-service/Chart.yaml
k8s/release/mi/mi-extraction-service/values.yaml
k8s/release/mi/mi-house-keeping-service/Chart.yaml
k8s/release/mi/mi-house-keeping-service/values.yaml
k8s/release/mi/mi-integration-service/Chart.yaml
k8s/release/mi/mi-integration-service/values.yaml
k8s/release/mi/mi-staging-service/Chart.yaml
k8s/release/mi/mi-staging-service/values.yaml

Amend MI charts and bump versions
```
[ ] Yes
[x] No
```

DTSPO-5953 Amend MI charts

---

apps/hmi/hmi-pactbroker/dev.yaml
apps/hmi/hmi-pactbroker/sbox.yaml

Add hmi pactbroker identities
```
[ ] Yes
[x] No
```

Add hmi pactbroker identities

---

apps/mi/mi-staging-service/dev.yaml
apps/mi/mi-staging-service/sbox.yaml

Fix mi-staging-service image policy

---

apps/monitoring/base/kustomize.yaml
apps/monitoring/kube-prometheus-stack-crds/kustomization.yaml
apps/monitoring/kube-prometheus-stack/kube-prometheus-stack.yaml

DTSPO-5953 Pre-install CRDs for prometheus

---

apps/admin/base/kustomize.yaml
apps/admin/traefik-crds/kustomization.yaml
apps/admin/traefik2/traefik2.yaml

DTSPO-5953 Pre-install CRDs for traefik

---

apps/admin/traefik2/dev/kustomization.yaml

DTSPO-6258 Add dev traefik kustomization

---

apps/admin/aad-pod-identity/dev/azure-identity-patch.yaml
apps/admin/dev/base/kustomization.yaml

DTSPO-6258 Add dev aad pod identity

---

apps/flux-system/base/user-api-gitrepo.yaml
apps/flux-system/base/video-api-gitrepo.yaml

Fix vh video-api and user-api

---

apps/mi/mi-adf-shir/dev/dev.yaml
apps/mi/mi-adf-shir/dev/mi-adf-auth-values.enc.yaml

To match expected path in the release
```
[ ] Yes
[x] No
```

Fix secret for mi-adf-shir dev

---

k8s/namespaces/jenkins/patches/ptl/cluster-00/jenkins.yaml

DTSPO-6258 Swap Jenkins on cluster 00 to use 01

---

k8s/namespaces/admin/traefik2/patches/demo/cluster-00/traefik-no-proxy.yaml
k8s/namespaces/admin/traefik2/traefik-no-proxy.yaml

DTSPO-6478 - update traefik-no-proxy load balancer

---

.gitignore
k8s/environments/demo/cluster-00-overlay/kustomization.yaml
k8s/environments/demo/cluster-01-overlay/kustomization.yaml
k8s/namespaces/admin/traefik2/patches/demo/traefik-private.yaml

DTSPO-6478 - remove traefik2 from demo

---

k8s/namespaces/admin/traefik2/patches/demo/traefik-private.yaml

DTSPO-6478 - Update traefik-private default

---

apps/mailrelay/base/kustomization.yaml
apps/mailrelay/mailrelay/mailrelay.yaml
apps/mailrelay2/base/kustomization.yaml
apps/mailrelay2/mailrelay2/mailrelay2.yaml

Add fluxv2 bits to make the mailrelay and mailrelay2 apps work in dev
```
[ ] Yes
[x] No
```

DTSPO-6258 Add mailrelay kustomizations

---

apps/mailrelay/mailrelay/mailrelay.yaml
apps/mailrelay2/mailrelay2/mailrelay2.yaml

Correct paths for mailrelay apps to reach their charts
```
[ ] Yes
[x] No
```

Correct paths for mailrelay apps

---

k8s/namespaces/admin/traefik2/patches/demo/traefik-private.yaml
k8s/namespaces/admin/traefik2/traefik-no-proxy.yaml

- Set ingressClass filters for traefik-private and traefik-no-proxy
```
[ ] Yes
[x] No
```

DTSPO-6478 - set ingress classes for demo

---

k8s/namespaces/toffee/toffee-frontend/demo/demo.yaml
k8s/namespaces/toffee/toffee-recipe-backend/demo/demo.yaml

- Set ingressClass names for toffee frontend and backend 
```
[ ] Yes
[x] No
```

DTSPO-6478 - set ingressclass names for toffee apps

---

k8s/environments/ithc/common-overlay/pip/azure-identity-patch.yaml
k8s/environments/ithc/common-overlay/pip/kustomization.yaml
k8s/environments/test/common-overlay/pip/azure-identity-patch.yaml
k8s/environments/test/common-overlay/pip/kustomization.yaml

Correct the MIs used for Test and ITHC in PIP
```
[ ] Yes
[ x ] No
```

add PIP test and ithc MIs

---

apps/mailrelay2/dev/base/kustomization.yaml
apps/mailrelay2/mailrelay2/dev.yaml

[tools.hmcts.net/jira/browse/DTSPO-6258](https://tools.hmcts.net/jira/browse/DTSPO-6258)
```
[ ] Yes
[x] No
```

Add mailrelay2 dev patch

---

k8s/namespaces/admin/oauth2-proxy/oauth2-proxy.yaml

tools.hmcts.net/browse/DTSPO-6480
Add defaultBackend to ingress
Add missing serviceAccount
[ ] Yes
[x] No

DTSPO-6480 - Oauth2-proxy: patch 2

---

k8s/namespaces/admin/oauth2-proxy/patches/demo/secret-provider.yaml

Update secret provider class for demo
[ ] Yes
[x] No

DTSPO-6480 - Oauth2-proxy: patch 3

---

k8s/namespaces/admin/traefik2/patches/demo/traefik-private.yaml
k8s/namespaces/admin/traefik2/traefik-no-proxy.yaml

Not great, but this IP shouldn't change very often.
```
[ ] Yes
[x] No
```

Get ingress status to populate IP address of the firewall

---

k8s/namespaces/pip/pip-account-management/patches/demo/pip-account-management.yaml
k8s/namespaces/pip/pip-channel-management/patches/demo/pip-channel-management.yaml
k8s/namespaces/pip/pip-data-management/patches/demo/pip-data-management.yaml
k8s/namespaces/pip/pip-frontend/patches/demo/pip-frontend.yaml
k8s/namespaces/pip/pip-publication-services/patches/demo/pip-publication-services.yaml
k8s/namespaces/pip/pip-subscription-management/patches/demo/pip-subscription-management.yaml

https://tools.hmcts.net/jira/browse/DTSPO-6784
Disable Traefix TLS for PIP Demo
```
[ ] Yes
[ X ] No
```

Disable Traefix TLS for PIP Demo

---

k8s/namespaces/admin/oauth2-proxy/oauth2-proxy.yaml

Add serviceName and port to ingress
[ ] Yes
[x] No

DTSPO-6480 - Oauth2-proxy: patch 4

---

k8s/namespaces/admin/external-dns/external-dns.yaml

- Missed change in last pr, this will filter the domain properly
```
[ ] Yes
[x] No
```

Fix configuration to filter domain

---

k8s/environments/demo/common-overlay/flux-patch.yaml

update image name for PIP Demo
```
[ ] Yes
[ x ] No
```

update image name for PIP Demo

---

k8s/environments/demo/cluster-00-overlay/kustomization.yaml
k8s/namespaces/admin/oauth2-proxy/oauth2-proxy.yaml

Remove oauth2-proxy from flux in demo-00 while testing
[ ] Yes
[x] No

DTSPO-6480 - Oauth2-proxy: remove from demo-00 flux

---

apps/juror-digital/jd-bureau/jd-bureau.yaml
apps/juror-digital/jd-public/jd-public.yaml
apps/juror-digital/moj-reverse-proxy/moj-reverse-proxy.yaml

intervals are now a required field
```
[ ] Yes
[x] No
```

DTSPO-6533 Fix jd hr's for flux v2

---

k8s/namespaces/admin/oauth2-proxy/patches/demo/kustomization.yaml

Update kustomizations
[ ] Yes
[x] No

DTSPO-6480 - Oauth2-proxy: patch 7

---

apps/toffee/dev/base/azure-identity-patch.yaml
apps/toffee/dev/base/kustomization.yaml

remove toffee dev patch so it doesn't try to deploy
```
[ ] Yes
[x] No
```

Remove toffee from dev

---

k8s/namespaces/admin/oauth2-proxy/oauth2-proxy-values.enc.yaml
k8s/namespaces/admin/oauth2-proxy/oauth2-proxy.yaml

Update values and add extraEnv
[ ] Yes
[x] No

DTSPO-6480 - Oauth2-proxy: patch 8

---

apps/mailrelay2/dev/base/mailrelay2-values.enc.yaml

remove namespace from secret

---

apps/admin/kube-slack/kube-slack.yaml
apps/admin/kured/kured.yaml
apps/mailrelay/mailrelay/mailrelay.yaml
apps/mailrelay2/mailrelay2/mailrelay2.yaml
apps/monitoring/kube-prometheus-stack/kube-prometheus-stack.yaml

Move secret file to .spec

---

k8s/environments/dev/common-overlay/juror-digital/jd-bureau-patch.yaml
k8s/environments/dev/common-overlay/juror-digital/jd-public-patch.yaml

release 2.25

---

k8s/namespaces/admin/oauth2-proxy/oauth2-proxy.yaml

More fixes to get oauth2-proxy working
[ ] Yes
[x] No

DTSPO-6480 - Oauth2-proxy: patch 10

---

k8s/environments/demo/common-overlay/flux-patch.yaml

Update PIP Data Management Image for Demo as it has been removed.
```
[ ] Yes
[ X ] No
```

Update PIP Data Management Image for Demo

---

k8s/environments/demo/common-overlay/flux-patch.yaml

update image tag manually for pip data management demo
```
[ ] Yes
[ x ] No
```

update image tag manually for pip data management demo

---

k8s/environments/demo/common-overlay/flux-patch.yaml

remove pip data management and readd
```
[ ] Yes
[ x ] No
```

remove pip data management

---

k8s/environments/demo/common-overlay/flux-patch.yaml

Add PIP Data Management Demo back in
```
[ ] Yes
[ X ] No
```

Add PIP Data Management Demo back in

---

k8s/environments/demo/common-overlay/flux-patch.yaml

- this should fix flux in demo 
```
[ ] Yes
[x] No
```

Remove toffee patches that are currently breaking flux on demo

---

k8s/namespaces/admin/external-dns/external-dns-private.yaml
k8s/namespaces/admin/external-dns/kustomization.yaml

- deploy external-dns for private dns records 
```
[ ] Yes
[x] No
```

DTSPO-6498 - add external dns deployment for private dns

---

k8s/environments/demo/cluster-00-overlay/kustomization.yaml
k8s/environments/demo/cluster-01-overlay/kustomization.yaml
k8s/namespaces/admin/external-dns/external-dns-private.yaml
k8s/namespaces/admin/external-dns/patches/demo/cluster-00/external-dns-private.yaml
k8s/namespaces/admin/external-dns/patches/demo/cluster-01/external-dns-private.yaml

- Added overlays for private external dns
```
[ ] Yes
[x] No
```

DTSPO-6498 private external dns

---

k8s/namespaces/pip/pip-frontend/patches/demo/pip-frontend.yaml
k8s/namespaces/pip/pip-frontend/patches/dev/pip-frontend.yaml
k8s/namespaces/pip/pip-frontend/patches/prod/pip-frontend.yaml
k8s/namespaces/pip/pip-frontend/patches/stg/pip-frontend.yaml
k8s/namespaces/pip/pip-frontend/patches/test/pip-frontend.yaml

https://tools.hmcts.net/jira/browse/PUB-1095
Added ACCOUNT_MANAGEMENT_URL variable

PUB -1095 - Added Env_URL variable

---

k8s/environments/demo/common-overlay/flux-patch.yaml

Update the Subscription Management image for PIP Demo
```
[ ] Yes
[ X ] No
```

Update the Subscription Management image for PIP Demo

---

apps/admin/dev/base/kustomization.yaml
apps/admin/sbox/base/kustomization.yaml
apps/rbac/reader-clusterrole.yaml

Add cluster reader role to dev and sbox for developers

---

k8s/environments/prod/common-overlay/juror-digital/jd-bureau-patch.yaml
k8s/environments/prod/common-overlay/juror-digital/jd-public-patch.yaml

release 2.25 changes

---

apps/flux-system/base/dynatrace-operator-helmrepo.yaml
apps/flux-system/base/kustomization.yaml
apps/monitoring/dynatrace/dynatrace-operator/dynatrace-operator-helmrepo.yaml
apps/monitoring/dynatrace/staging/kustomization.yaml

DTSPO-6917 Move OneAgent helm repo config

---

k8s/namespaces/admin/oauth2-proxy/kustomization.yaml
k8s/namespaces/admin/oauth2-proxy/oauth2-proxy-values.enc.yaml

Missing values file and kustomization
[ ] Yes
[x] No

DTSPO-6480 - Oauth2-proxy: patch 12

---

apps/flux-system/base/dynatrace-operator-helmrepo.yaml

correct namespace for helmrepo

---

k8s/namespaces/admin/oauth2-proxy/oauth2-proxy-values.enc.yaml

Fix oauth2-proxy values
[ ] Yes
[x] No

DTSPO-6480 - Oauth2-proxy: patch 13

---

k8s/namespaces/admin/oauth2-proxy/kustomization.yaml
k8s/namespaces/admin/oauth2-proxy/oauth2-proxy.enc.yaml

Fix oauth2-proxy secrets
[ ] Yes
[x] No

DTSPO-6480 - Oauth2-proxy: patch 15

---

k8s/namespaces/admin/oauth2-proxy/oauth2-proxy.yaml

Add proxyVarsAsSecrets flag
[ ] Yes
[x] No

DTSPO-6480 - Oauth2-proxy: patch 17

---

clusters/stg/base/kustomization.yaml

DTSPO-6917 Add monitoring namespace to staging

---

k8s/environments/demo/cluster-00-overlay/kustomization.yaml

Test fix to 403: "CSRF token mismatch, potential attack" error

DTSPO-6480 - remove oauth2-proxy from flux

---

apps/monitoring/stg/00/kustomization.yaml
apps/monitoring/stg/01/kustomization.yaml
apps/monitoring/stg/base/kustomization.yaml

DTSPO-6917 Fix kustomizations

---

k8s/namespaces/admin/oauth2-proxy/oauth2-proxy.yaml
k8s/namespaces/toffee/toffee-frontend/demo/demo.yaml

Update ingress class for toffee and oauth
[ ] Yes
[x] No

DTSPO-6480 - update oauth and toffee ingress

---

apps/monitoring/stg/base/oneagent-values.enc.yaml

DTSPO-6917 Change oneagent tokens

---

k8s/namespaces/admin/traefik2/patches/demo/cluster-00/traefik-auth-proxy.yaml

- Add fullNameOverride
- Add fullName

DTSPO-6480 - add fullName

---

k8s/namespaces/admin/traefik2/patches/demo/cluster-00/traefik-auth-proxy.yaml

Previous PR had fullNameOverride instead of fullnameOverride﻿

DTSPO-6480 - add fullnameOverride

---

apps/monitoring/dynatrace/dynatrace-operator.yaml

DTSPO-6917 Upgrade dynatrace-operator

---

apps/monitoring/dynatrace-crds/kustomization.yaml

DTSPO-6917 change crd format

---

k8s/namespaces/pip/pip-frontend/patches/test/pip-frontend.yaml

Correct the ingress url for PIP frontend test
```
[ ] Yes
[ x ] No
```

correct ingress url for pip frontend test

---

k8s/namespaces/admin/traefik2/traefik-auth-proxy.yaml

Add entryPoints forwardedHeaders
Found in comment on github issue https://github.com/oauth2-proxy/oauth2-proxy/issues/1297#issuecomment-1062316085﻿

DTSPO-6480 - patch 21

---

k8s/namespaces/toffee/toffee-frontend/demo/demo.yaml

Rename enableOauth to enableOAuth﻿

DTSPO-6480 - update toffee demo enableOAuth

---

apps/monitoring/dynatrace/dynatrace-operator.yaml

DTSPO-6917 Update Dynatrace Operator

---

apps/monitoring/stg/base/kustomization.yaml

want to see if flux-system is fine prior to dynatrace
```
[ ] Yes
[X] No
```

want to see if flux-system is fine prior to dynatrace

---

apps/flux-system/stg/base/kustomization.yaml

swap to test on stg
```
[ ] Yes
[X] No
```

swap to test on stg

---

apps/monitoring/dynatrace/stg/dynatrace-operator-values.enc.yaml

DTSPO-6917 Use CFT PaaS Token

---

apps/monitoring/dynatrace/dynatrace-operator.yaml

Reverts hmcts/sds-flux-config#1693

Revert "Try 0.3.0 of dynatrace-operator"

---

k8s/namespaces/neuvector/neuvector.yaml

DTSPO-6920
added flux-system and dynatrace namespaces to neuvector.yaml
```
[ ] Yes
[X] No
```

DTSPO-6920 - added flux-system and dynatrace namespaces to neuvector.yaml

---

k8s/namespaces/neuvector/neuvector.yaml

DTSPO-6920
fix ingress for neuvector
```
[ ] Yes
[X] No
```

DTSPO-6920 - fix ingress for neuvector

---

apps/dynatrace/prod/00/kustomization.yaml
apps/dynatrace/prod/01/kustomization.yaml
apps/dynatrace/prod/base/kustomization.yaml
apps/dynatrace/prod/dynatrace-operator-values.enc.yaml
apps/dynatrace/prod/dynatrace-operator.yaml
clusters/prod/base/kustomization.yaml

DTSPO-6920 Deploy dynatrace to prod

---

apps/dynatrace/dynatrace-operator.yaml

Use system node pools
```
[ ] Yes
[x] No
```

DTSPO-6917 Add node selector to dynatrace operator

---

apps/dynatrace/dynatrace-operator.yaml

DTSPO-6917 Add toleration to dynatrace operator

---

k8s/namespaces/juror-digital/jd-bureau/jd-bureau.yaml

Reducing max replicas to match no of available nodes
```
[ ] Yes
[x] No
```

Reduce Replicas to 4

---

apps/dynatrace/dynatrace-operator.yaml

Might possibly fix our connection issue with Dynatrace:
https://www.dynatrace.com/support/help/setup-and-configuration/setup-on-container-platforms/kubernetes/set-up-k8s-monitoring-with-helm#installation
Is described here also:
https://github.com/Dynatrace/dynatrace-operator/blob/master/config/helm/chart/default/values.yaml#L124
```
[ ] Yes
[x] No
```

DTSPO-6917 Add ActiveGate Dynatrace stg

---

k8s/namespaces/jenkins/patches/ptlsbox/cluster-00/jenkins.yaml

DTSPO-7181
Added secondary ingress for sbox jenkins
```
[ ] Yes
[X] No
```

DTSPO-7181 - Added secondary ingress for sbox jenkins

---

k8s/namespaces/jenkins/patches/ptlsbox/cluster-00/jenkins.yaml

DTSPO-7181
Edit Secondary Ingress for SDS Sbox Jenkins
```
[ ] Yes
[X] No
```

DTSPO-7181 - Edit Secondary Ingress for SDS Sbox Jenkins

---

k8s/environments/demo/common-overlay/flux-patch.yaml

N/A
Update demo images for PIP
```
[ ] Yes
[x] No
```

Updated demo images

---

k8s/namespaces/pip/pip-subscription-management/patches/demo/pip-subscription-management.yaml

added env var of account management in the subscription management demo env
```
[ ] Yes
[x] No
```

added env var to subscription management

---

k8s/namespaces/jenkins/patches/ptlsbox/cluster-00/jenkins.yaml

DTSPO-7181 
Added trafik annotation to ingress and secondaryIngress
```
[ ] Yes
[X] No
```

DTSPO-7181 - Added trafik annotation to ingress and secondaryIngress

---

k8s/namespaces/jenkins/jenkins.yaml

DTSPO-7181
Update Jenkins chart version
```
[ ] Yes
[X] No
```

DTSPO-7181 - Update Jenkins chart version

---

k8s/namespaces/jenkins/jenkins.yaml

Reverts hmcts/sds-flux-config#1715

Revert "DTSPO-7181 - Update Jenkins chart version"

---

k8s/namespaces/jenkins/patches/ptlsbox/cluster-00/jenkins.yaml

DTSPO-7181
Updated Sbox Jenkins Version. Testing new version as latest version broke production Jenkins.
```
[ ] Yes
[X] No
```

DTSPO-7181 - Update Sbox Jenkins Version

---

k8s/namespaces/jenkins/patches/ptlsbox/cluster-00/jenkins.yaml

DTSPO-7181
Enabling secondary ingress and adding correct annotation
```
[ ] Yes
[X] No
```

DTSPO-7181 - Enabling secondary ingress

---

k8s/namespaces/jenkins/patches/ptlsbox/cluster-00/jenkins.yaml

Add path to get jenkins secondary ingress working
```
[ ] Yes
[x] No
```

Fix secondary ingress

---

k8s/namespaces/pip/pip-data-management/patches/demo/pip-data-management.yaml

added subscription management url to demo data management
```
[ ] Yes
[ ] No
```

added subscription management url to demo data management

---

k8s/namespaces/jenkins/patches/ptlsbox/cluster-00/jenkins.yaml

DTSPO-7181
Adding resource root URL to configuration as code
```
[ ] Yes
[X] No
```

DTSPO-7181 - Adding resource root URL to configuration as code

---

k8s/namespaces/jenkins/patches/ptlsbox/cluster-00/jenkins.yaml

DTSPO-7181
Edit resource root label format to fix helm release
```
[ ] Yes
[X] No
```

DTSPO-7181 - Edit resource root label format to fix helm release

---

k8s/namespaces/jenkins/jenkins.yaml
k8s/namespaces/jenkins/patches/ptl/cluster-00/jenkins.yaml
k8s/namespaces/jenkins/patches/ptlsbox/cluster-00/jenkins.yaml

DTSPO-7165
Add secondary ingress for sds build jenkins. Similar change tested and working for sds sandbox jenkins.
```
[ ] Yes
[X] No
```

DTSPO-7165 - Add secondary ingress for sds build jenkins

---

k8s/namespaces/jenkins/patches/ptl/cluster-00/jenkins.yaml

DTSPO-7165
Add resource URL to configuration as code
```
[ ] Yes
[X] No
```

DTSPO-7165 - Add resource URL to configuration as code

---

k8s/namespaces/jenkins/patches/ptl/cluster-00/jenkins.yaml

DTSPO-7165
Edit Resource Root label from camel case
```
[ ] Yes
[X] No
```

DTSPO-7165 - Edit Resource Root label from camel case

---

k8s/namespaces/jenkins/jenkins.yaml

DTSPO-7165
Remove CSP Policy
```
[ ] Yes
[X] No
```

DTSPO-7165 - Remove CSP Policy

---

apps/vh/bookings-api/bookings-api.yaml

Change the repo details for flux 2
```
[ ] Yes
[ x ] No
```

update repo details for bookings api

---

k8s/release/mi/mi-azure-functions/values.yaml

Remove MI Metadata Admin and Password secrets

---

apps/mi/base/mi-developer-rbac.yaml
k8s/namespaces/mi/mi-developer-rbac.yaml

Needed to manually delete or update HR charts for flux v2 envs such as sbox or dev

Add mi permissions for flux v2

---

k8s/environments/prod/common-overlay/juror-digital/jd-bureau-patch.yaml
k8s/environments/prod/common-overlay/juror-digital/jd-public-patch.yaml

New deployment of Juror Digital 2.25

---

k8s/environments/demo/common-overlay/flux-patch.yaml

N/A
Updated DM image
```
[ ] Yes
[x] No
```

Updated pip data management image

---

k8s/environments/demo/common-overlay/flux-patch.yaml

N/A
Fix subscription management image for demo
```
[ ] Yes
[x] No
```

Updated subscription management

---

apps/azure-devops/azure-devops-agent/image-repo.yaml

add annotation for image automation hmctspublic
```
[ ] Yes
[X] No
```

add annotation for image automation hmctspublic

---

k8s/environments/demo/common-overlay/flux-patch.yaml

N/A
Update DM image for PIP
```
[ ] Yes
[x] No
```

Updated data management image

---

k8s/environments/demo/common-overlay/flux-patch.yaml

N/A
Update image for data management
```
[ ] Yes
[x] No
```

Updated image name

---

k8s/environments/prod/cluster-00/mi/mi-integration-service.yaml

Disabling 8x8 ingestion in prod

---

apps/azure-devops/azure-devops-agent/ithc.yaml
apps/azure-devops/ithc/base/kustomization.yaml
clusters/ithc/00/kustomization.yaml
clusters/ithc/01/kustomization.yaml
clusters/ithc/base/kustomization.yaml
k8s/environments/ithc/cluster-00-overlay/kustomization.yaml
k8s/environments/ithc/cluster-01-overlay/kustomization.yaml

Migrate azure-devops to flux v2 in ithc
```
[ ] Yes
[x] No
```

DTSPO-6489 - fluxv2 ithc migration - azure-devops

---

apps/admin/kube-slack/ithc/00.yaml
apps/admin/kube-slack/ithc/01.yaml
apps/admin/kube-slack/ithc/kube-slack-values.enc.yaml
clusters/ithc/base/kustomization.yaml
k8s/environments/ithc/cluster-00-overlay/kustomization.yaml
k8s/environments/ithc/cluster-01-overlay/kustomization.yaml

Migrate kube-slack in ithc to flux v2
```
[ ] Yes
[x] No
```

DTSPO-6489 - fluxv2 ithc migration - kube-slack

---

apps/admin/ithc/00/kustomization.yaml
apps/admin/ithc/01/kustomization.yaml

Add missing patches to ithc
```
[ ] Yes
[x] No
```

DTSPO-6489 - fluxv2 ithc migration - admin - patch 2

---

k8s/namespaces/pip/pip-frontend/patches/prod/pip-frontend.yaml

PUB-1209
Update the ingress for pip production
```
[ ] Yes
[ x ] No
```

PUB-1209 - Update ingress to custom domain

---

k8s/namespaces/jenkins/patches/ptl/cluster-00/jenkins.yaml

Move Jenkins stg to 01

---

apps/pip/ithc/base/kustomization.yaml

Fix file paths for pip identity in ithc
```
[ ] Yes
[x] No
```

DTSPO-6489 - fluxv2 ithc migration - pip - patch 2

---

apps/neuvector/base/kustomization.yaml
apps/neuvector/base/kustomize.yaml
apps/neuvector/fluentbit-log/fluentbit-log.yaml
apps/neuvector/identity/identity.yaml
apps/neuvector/identity/ithc.yaml
apps/neuvector/ithc/00/kustomization.yaml
apps/neuvector/ithc/01/kustomization.yaml
apps/neuvector/ithc/base/fluentbit-log.yaml
apps/neuvector/ithc/base/kustomization.yaml
apps/neuvector/ithc/base/nv-storage-secret-hack.yaml
apps/neuvector/ithc/base/nv-storage-secret.yaml
apps/neuvector/neuvector/ithc/00.yaml
apps/neuvector/neuvector/ithc/01.yaml
apps/neuvector/neuvector/ithc/ithc.yaml
apps/neuvector/neuvector/neuvector.yaml
clusters/ithc/base/kustomization.yaml
k8s/environments/ithc/cluster-00-overlay/kustomization.yaml
k8s/environments/ithc/cluster-01-overlay/kustomization.yaml

https://tools.hmcts.net/jira/browse/DSTPO-6489
Migrate neuvector in ithc to flux v2
```
[ ] Yes
[x] No
```

DTSPO-6489 - fluxv2 ithc migration - neuvector

---

apps/neuvector/fluentbit-log/fluentbit-log.yaml

Update fluentbit-log to move chart into its own spec
```
[ ] Yes
[x] No
```

DTSPO-6489 - fluxv2 ithc migration - neuvector - patch 2

---

apps/neuvector/fluentbit-log/fluentbit-log.yaml

Fix indenting in fluentbit-log
```
[ ] Yes
[x] No
```

DTSPO-6489 - fluxv2 ithc migration - neuvector - patch 3

---

apps/neuvector/fluentbit-log/fluentbit-log.yaml

Update chart spec for neuvector
```
[ ] Yes
[x] No
```

DTSPO-6489 - fluxv2 ithc migration - neuvector - patch 4

---

apps/neuvector/neuvector/neuvector.yaml

Update neuvector.yaml to use flux v2 config
```
[ ] Yes
[x] No
```

DTSPO-6489 - fluxv2 ithc migration - neuvector - patch 5

---

apps/neuvector/neuvector/neuvector.yaml

Update spec.chart for neuvector
```
[ ] Yes
[x] No
```

DTSPO-6489 - fluxv2 ithc migration - neuvector - patch 6

---

clusters/ithc/base/kustomization.yaml

Temporarily remove neuvector from ithc kustomization to test fixes to current errors
```
[ ] Yes
[x] No
```

DTSPO-6489 - fluxv2 ithc migration - remove neuvector

---

apps/neuvector/neuvector/ithc/00.yaml
apps/neuvector/neuvector/ithc/01.yaml

tools.hmcts.net/jira/browse/DTSPO-6489
Remove spec.chart from 00 and 01.yaml
[ ] Yes
[x] No

DTSPO-6489 - fluxv2 ithc migration - neuvector - patch 9

---

apps/neuvector/neuvector/ithc/ithc.yaml
apps/neuvector/neuvector/neuvector.yaml

tools.hmcts.net/jira/browse/DTSPO-6489
Remove spec.chart from all neuvector
[ ] Yes
[x] No

DTSPO-6489 - fluxv2 ithc migration - neuvector - patch 10

---

k8s/environments/prod/common-overlay/flux-patch.yaml
k8s/environments/prod/common-overlay/vh/kustomization.yaml
k8s/environments/prod/common-overlay/vh/vh-aad-identity.yaml

[VIH-8960](https://tools.hmcts.net/jira/browse/VIH-8960)
VH - Add Bookings API Production Flux Config
```
[ ] Yes
[ X ] No
```

VIH-8960 - Add Production Flux Configuration Bookings API

---

k8s/environments/prod/common-overlay/flux-patch.yaml
k8s/environments/prod/common-overlay/kustomization.yaml
k8s/environments/prod/common-overlay/vh/kustomization.yaml
k8s/environments/prod/common-overlay/vh/vh-aad-identity.yaml

VH - Add Bookings API Production Flux Config Namespace
```
[ ] Yes
[ X ] No
```

VIH-8960 - Add Production Flux Configuration Bookings API Namespace

---

README.md

Update readme to reflect migration of ithc
```
[ ] Yes
[x] No
```

DTSPO-6489 - fluxv2 ithc migration - Update readme

---

k8s/environments/demo/common-overlay/flux-patch.yaml
k8s/environments/prod/common-overlay/flux-patch.yaml
k8s/environments/stg/common-overlay/flux-patch.yaml

Remove the filters from the charts
```
[ ] Yes
[ x ] No
```

VH Remove Filters from config

---

apps/toffee/dev/base/azure-identity-patch.yaml
apps/toffee/dev/base/kustomization.yaml

https://tools.hmcts.net/jira/browse/DTSPO-6817
Adding toffee to dev cluster so PRs work in pipeline
```
[ ] Yes
[x] No
```

DTSPO-6817 - Add toffee to dev

---

README.md

DTSPO-6491
Change Migration 'Status' from 'Not Migrated' to 'Started Migration'
```
[ ] Yes
[X] No
```

DTSPO-6491 - Change Migration 'Status' from 'Not Migrated' to 'Started Migration'

---

apps/pip/data-management/ithc.yaml

PIP Manual Update to ITHC image for Data Management
```
[ ] Yes
[ x ] No
```

PIP Manual Update to ITHC image for Data Management
